### ISSUE TITLE
Enable data with more than 32 bits in xdrv_17_rcswitch.ino

### ISSUE THREAD

**Issue by joetriskaide** [arendst/Tasmota#10010]
**Have you looked for this feature in other issues and in the docs?**  Yes
The rc-switch library in tasmoa is capable of sending such payload , the CmndRfSend command in xdrv_17_rcswitch.ino not.

**Is your feature request related to a problem? Please describe.**  
I won a Dooya 1603 remote which uses payload data of 40 bits

**Describe the solution you'd like**  
xdrv_17_rcswitch  xdrv_17_rcswitch.ino
line 101, change to  `unsigned long long data = 0;`
line 112 change to ' `data = root.getULong(PSTR(D_JSON_RF_DATA), data);`'
**Describe alternatives you've considered**  
None

**Additional context**  
I tried the changes on gitpod and they work

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
If the code size increase is not too big a provided PR will be merged

**Comment by nosaj66au** [comment]
Hi Guys, Been working and testing in this area it appear the fix above only addresses the transition section of the code, enabling 40 bits of data to be transmitted. Can you please also add it to the receive section.
Jason
