### ISSUE TITLE
Thermostat Mode : Telemetry output (why power off ?)

### ISSUE THREAD

**Issue by Bibinsa** [arendst/Tasmota#10018]
**Have you looked for this feature in other issues and in the docs?**  
Yes
**Is your feature request related to a problem? Please describe.**  
Thermostat Mode : output power while TEMPTARGETSET > TEMPMEASUREDSET.
Need to know why.

**Describe the solution you'd like**  
A periodic JSON telemetry output whith main parameters of Ramp-Up/Pi strategy counters.
A "reason" why output is power off.

**Describe alternatives you've considered**  
Tried weblog 3, weblog 4

**Additional context**  
Tasmota 9.1.0 with USE_THERMOSTAT

**(Please, remember to close the issue when the problem has been addressed)**  

Hi ! I'm using Thermostat feature since a fex days now.

I wonder if there is any option to activate telemetry with the different counters used (cycle reset, max time, ...) and for any reasons that trigger Power ON/OFF ?
If not, could it be possible to implement that ?

Thanks.

**Comment by ascillato2** [comment]
@arijav 

Can you take a look on this? Thanks.

**Comment by PoorNewb23** [comment]
That would be lovely to see.

**Comment by arijav** [comment]
I take the point and will have a look

**Comment by arijav** [comment]
@Bibinsa : Please check 2 topics to identify if there is really an issue

1) The PI controller do switch the output OFF even if the desired temperature is not reached. The cycle time is 30 minutes, for how long the controller outputs ON fully depends on the delta between target temp and set temp and the time you have tried to reach your set temp. This is how a PI controller works, to be able to reach the set temperature without a big overshoot.

2) After reading the first point, in case you still think you have an issue, please activate the DEBUG of the thermostat (define in your "user_config_override.h" file "#define DEBUG_THERMOSTAT", capture the serial output and please explain in detail what is the behavior you think is wrong.

**Comment by Bibinsa** [comment]
@arijav Thanks for your help.
T'm trying Hybrid system for a few days but I think 8 have to tweak a little bit the driver as I'm running a Heating Pump (is that correct in english ?) with a floor heating.

I will try with DEBUG_THERMOSTAT and let you know if I find something.

**Comment by arijav** [comment]
The driver is by default configure to actuate heating floor valves (as I've created it and tested it initially for this application in my apartment). For driving a heating pump you will have to check surely the application. It is important to understand and configure well the required period for heating (which depends on the time constant, long for slow changes, short for very fast reaction systems), any constraints about switching ON/OFF the heating pump and so on.

At best read the documentation of the driver in detail, the main parameters to adapt to your system are shown there, as well as the documentation of your heating pump. 

For the information I got I do not see any bug in the driver itself but more the need of adapting the parameters to your specific setup needs.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
