### ISSUE TITLE
Sonoff mini with Tasmota 9.1 unresponsive trough Philips Remote -> HomeBridge after some hours OFF

### ISSUE THREAD

**Issue by mactsk** [arendst/Tasmota#10023]
Regularly every X hours my Sonoff Mini seems to not respond to MQTT commands sent to a remote via HomeBridge
The mini does respond to PING and opening the Web page seems to solve the problem, i ma conducing some other test to see if the ping alone is enough, since i don't know how many hours needs to pass to "lock the device" it's a long process.

is there any test that i can do?

**Comment by Jason2866** [comment]
Try Setoption41 <x>  The complete explanation can be found in the documentation
