### ISSUE TITLE
ESP32 GPIO ISSUE

### ISSUE THREAD

**Issue by DevianceQcmic** [arendst/Tasmota#10036]
### PROBLEM DESCRIPTION
GPIO 25 and 26 are ADC and DAC so if want to use it like analog input the value was return is 4095 suppose to be 0.
I try to make a test whit pin 18 but even worse i have no more information show on main page. 
I did not test all GPIO but 13 is ADC only and same issue here.
Other thing if you save your ADC input and did not change input position like all 1 then 80 % time you will not be able to access WEB interface need to reset from serial.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic):ESP32 custom board
- [ ] Tasmota binary firmware version number used: 9.1.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
06:28:13 RSL: stat/tasmota_C740A8/RESULT = {"NAME":"ESP32-DevKit","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
06:28:13 RSL: stat/tasmota_C740A8/RESULT = {"Module":{"1":"ESP32-DevKit"}}
06:28:13 RSL: stat/tasmota_C740A8/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"ADC Input4"},"GPIO14":{"480":"Buzzer"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"4706":"ADC Input3"},"GPIO26":{"4706":"ADC Input4"},"GPIO27":{"288":"Led1"},"GPIO28":{"0":"None"},"GPIO29":{"0":"None"},"GPIO30":{"0":"None"},"GPIO31":{"0":"None"},"GPIO32":{"4704":"ADC Input ...


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
06:30:35 RSL: stat/tasmota_C740A8/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_C740A8","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software reset CPU","Uptime":"0T00:07:00","StartupUTC":"2020-12-02T05:23:35","Sleep":50,"CfgHolder":4617,"BootCount":12,"BCResetTime":"2020-12-02T05:57:09","SaveCount":32}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T12:32:13","Core":"1_0_4","SDK":"v3.2.3-14-gd3e562907","CpuFrequency":80,"Hardware":"ESP32","CR":"405/699"}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SOMR_Invites",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS4 = {"StatusMEM":{"ProgramSize":1052,"Free":1984,"Heap":111,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","00140001","000000CF","010013C0","40000981","00004000","00000000"],"Drivers":"1,2,3,4,5,7,8,9,10,12,20,21,24,26,27,29","Sensors":"1,2,3,5,6"}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS5 = {"StatusNET":{"Hostname":"tasmota_C740A8-0168","IPAddress":"172.30.4.11","Gateway":"172.30.4.1","Subnetmask":"255.255.254.0","DNSServer":"1.1.1.1","Mac":"80:7D:3A:C7:40:A8","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C740A8","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS7 = {"StatusTIM":{"UTC":"2020-12-02T05:30:35","Local":"2020-12-02T06:30:35","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"08:24","Sunset":"16:54"}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS10 = {"StatusSNS":{"Time":"2020-12-02T06:30:35","ANALOG":{"A1":0,"A2":0,"A3":4095,"A4":4095}}}
06:30:35 RSL: stat/tasmota_C740A8/STATUS11 = {"StatusSTS":{"Time":"2020-12-02T06:30:35","Uptime":"0T00:07:00","UptimeSec":420,"Heap":111,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":76,"MqttCount":0,"Wifi":{"AP":1,"SSId":"SOMR_Invites","BSSId":"FA:1C:BA:47:D1:CF","Channel":1,"RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:37"}}}


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Althought the ESP32 could support ADC on those GPIO's Tasmota does not.

Tasmota only supports ADC input on GPIO32-GPIO39 as other GPIO's interfere with wifi.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
