### ISSUE TITLE
RFBridge not changing back to "RfRaw 0"-Mode via Mqtt

### ISSUE THREAD

**Issue by jldmn** [arendst/Tasmota#10047]
I'm currently trying to send raw data via the Sonoff RF-Bridge an then automatically change back to the default Rf-mode which would be activated by running `RfRaw 0`. This somehow works perfectly when executed via the web console. But it does not work when send as a mqtt command from home-assistant or any other mqtt-client. In fact I'm unable to even run the single `RfRaw 0` command via mqtt and the device is still in `RfRaw: On` mode.

I took a quick look into the `CmndRfRaw()` function inside the `xdrv_06_snfbridge.ino` and thought that maybe `SnfBridge.receive_raw_flag = 0;` is missing in the `case 0´ block. But maybe this is also handled via fall-trough to `case 1`.

Maybe someone who is more into the code could help me with this problem?
Or can someone explain me from where the `CmndRfRaw()` function is called when commanda are received via mqtt?

**Comment by ascillato** [comment]
Hi,

To send any command by MQTT be sure that:

topic is cmnd/yourdevicetopic/rfraw
payload 0

if you are sending the command all together in the topic ( topic: cmnd/yourdevicetopic/rfraw 0 ) that is not going to work.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
