### ISSUE TITLE
Changes to checkbox MQTT -> "MQTT TLS"  are not saved through webinterface

### ISSUE THREAD

**Issue by WillemJansen** [arendst/Tasmota#10064]
Quick and really not urgent bug report:
- The value of the "MQTT TLS"-Checkbot (Option103) seems to be saved, when changed via Webinterface

What I did:
- Compile my own firmware with TLS enabled
- Ran into strage TLS errors (not part of this report)
- Wanted to deactivate TLS for debugging purposes
- Had to use SetOption103 as WebInterface did to carry over changes to the Checkbox.

What I expected: Switching on/off TLS via WebInterface should work

What happened instead: Removal of the TLS checkbox was not saved, when I clicked save

Hope it helps!

Best,
  Willem

**Comment by gregersrygg** [comment]
This has been fixed in #10583
