### ISSUE TITLE
Tasmota for Winner Micro W600

### ISSUE THREAD

**Issue by oliver602** [arendst/Tasmota#10077]
Feature request: Support for devices using [Winner Micro W600](https://w600.chip.haus/) or perhaps another popular Wi-Fi SoC.

**Have you looked for this feature in other issues and in the docs?** 
Yes

**Is your feature request related to a problem? Please describe.**  
More new devices are starting to use alternatives to the ESP8266. They can't be flashed with Tasmota.

**Describe the solution you'd like**  
The ability to flash Tasmota to devices using modules like the TW-02.

**Describe alternatives you've considered**  
Not sure. Find other firmware.

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Tasmota was developed on top of Arduino core for ESP8266 and ESP32.

The Winner Micro W600 has a very different hardware architecture and is not Arduino compatible. So Tasmota can't run on those chips. Sorry.
