### ISSUE TITLE
Websend command to other non tasmota host  with username&password

### ISSUE THREAD

**Issue by mamrai1** [arendst/Tasmota#10073]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
example 2: WebSend [myserver.com] /fancy/data.php?log=1234 sends http://myserver.com/fancy/data.php?log=1234
but 
WebSend [myserver.com,username:password] /fancy/data.php?log=1234 fails!

**Describe the solution you'd like**  
WebSend [myserver.com,username:password] /fancy/data.php?log=1234 should send:
http://username:password@myserver.com/fancy/data.php?log=1234

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
In order to send http://username:password@myserver.com/fancy/data.php?log=1234

have you tried the following?
```lua
WebSend [username:password@myserver.com] /fancy/data.php?log=1234
```

**Comment by mamrai1** [comment]
Yes, tried this: websend [admin:password@192.168.1.41] /relay/0?turn=off
but i get {"WebSend":"Connect failed"}

**Comment by mamrai1** [comment]
oh. the problem is my password that cntains the '@' character.. is there a way to fix it wiithout changing my pass?

**Comment by ascillato** [comment]
Sorry, there isn't.

**Comment by mamrai1** [comment]
ok thanks
