### ISSUE TITLE
Possible to invert LED in TopGreener TGWF15S (TuyaMCU based)?

### ISSUE THREAD

**Issue by Rickerdo** [arendst/Tasmota#10094]
### PROBLEM DESCRIPTION
I have a couple of these: https://www.amazon.com/gp/product/B07D8YR75X/ref=ppx_yo_dt_b_asin_title_o00_s00 running Tasmota 9.1.0. Using this template: https://templates.blakadder.com/topgreener_TGWF15S.html the switch works as expected.

Is it possible to invert the status LED so that the LED is on when the switch is off and vice versa? The default functionality has the LED on when the switch is on and vice versa.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
16:54:48 MQT: garage-lights/stat/RESULT = {"NAME":"TopGreener-Switch","GPIO":[0,0,0,0,0,0,0,0,0,2304,0,2272,0,0],"FLAG":0,"BASE":54}
16:54:48 MQT: garage-lights/stat/RESULT = {"Module":{"54":"Tuya MCU"}}
16:54:49 MQT: garage-lights/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"2304":"Tuya Rx"},"GPIO14":{"0":"None"},"GPIO15":{"2272":"Tuya Tx"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
16:56:12 MQT: garage-lights/stat/STATUS = {"Status":{"Module":54,"DeviceName":"topgreener","FriendlyName":["topgreener"],"Topic":"garage-lights","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
16:56:12 MQT: garage-lights/stat/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T01:03:44","StartupUTC":"2020-12-08T14:52:28","Sleep":50,"CfgHolder":4617,"BootCount":35,"BCResetTime":"2020-12-07T15:02:48","SaveCount":165,"SaveAddress":"F4000"}}
16:56:12 MQT: garage-lights/stat/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"421/699"}}
16:56:12 MQT: garage-lights/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["twinknoll",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008008","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
16:56:12 MQT: garage-lights/stat/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":23,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashFrequency":40,"FlashMode":0,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
16:56:12 MQT: garage-lights/stat/STATUS5 = {"StatusNET":{"Hostname":"garage-lights","IPAddress":"192.168.1.48","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.217","Mac":"84:0D:8E:B7:1F:CF","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
16:56:12 MQT: garage-lights/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.4","MqttPort":1883,"MqttClientMask":"garage-lights","MqttClient":"garage-lights","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
16:56:12 MQT: garage-lights/stat/STATUS7 = {"StatusTIM":{"UTC":"2020-12-08T15:56:12","Local":"2020-12-08T16:56:12","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"08:31","Sunset":"16:53"}}
16:56:12 MQT: garage-lights/stat/STATUS10 = {"StatusSNS":{"Time":"2020-12-08T16:56:12"}}
16:56:12 MQT: garage-lights/stat/STATUS11 = {"StatusSTS":{"Time":"2020-12-08T16:56:12","Uptime":"0T01:03:44","UptimeSec":3824,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"twinknoll","BSSId":"F0:9F:C2:77:1D:8F","Channel":11,"RSSI":42,"Signal":-79,"LinkCount":1,"Downtime":"0T00:00:04"}}}


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Sorry, that led is controlled by the tuya mcu and it isn't under the control of Tasmota.
