### ISSUE TITLE
Constant fading duration

### ISSUE THREAD

**Issue by bpuder** [arendst/Tasmota#10109]
**Have you looked for this feature in other issues and in the docs?**  

Yes, I searched in the issues for a fixed fade duration, that takes always the same amount of time. I found https://github.com/arendst/Tasmota/issues/6942 but this was more related to gamma control.

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

I had an RGB controller in my bathroom. This is triggered by a motion sensor via Home Assistant. Generally the fading works smooth and nice in a time of about 2 seconds. But at the night I limited the maximum brightness to 20%. This is really cool because when I wake up late, it's not that blinding. But the disadvantage is that the duration of the fading is also just 20% of the time, when faded to 100%. This make it some kind of flashing because it reaches the maximum brightness within a really short time which can be really challenging for the eyes.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

It would be great if the fading is a constant time. Longer fade distances will be reached in the same amount of time as shorter distances.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

I also already enabled the gamma control, which makes the transition more linear for the physiological characteristics of the eyes but this didn't satisfy my needs.

**Additional context**  
_Add any other context or screenshots about the feature request here._

I checked out the code and looked for a nice place to put this functionality. I was neither able to build the code nor to test it. But I'd like to share the patch with you to present a possible solution.

[constant_fade.txt](https://github.com/arendst/Tasmota/files/5681014/constant_fade.txt)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
It was a debate whether the fading should be fixed duration or fixed slew rate. It was decided to be fixed slew rate, but it shouldn't be difficult to have a fixed duration as an alternative. I guess it means yet another `SetOption`?.
