### ISSUE TITLE
Mqtt ButtonTopic power messages swapped

### ISSUE THREAD

**Issue by rkojedzinszky** [arendst/Tasmota#10126]
### PROBLEM DESCRIPTION
When using MqttButtonTopic, the sent message has a swapped topic compared to normal button events.

This is a dump of messages when single-pressing and later double-pressing the _same_ button:
```
$ mosquitto_sub -h mqtt.lan -t '+/sw_nappali/#' -t '+/sw_nappali_alt/#' -v
tele/sw_nappali/LWT Online
stat/sw_nappali/RESULT {"POWER1":"OFF"}
stat/sw_nappali/POWER1 OFF
stat/sw_nappali/RESULT {"POWER1":"ON"}
stat/sw_nappali/POWER1 ON
cmnd/sw_nappali_alt/POWER2 TOGGLE
cmnd/sw_nappali_alt/POWER2 TOGGLE
```
This was definitely working the right way with Tasmota compiled in Dec 2019.

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Touch T1 2CH
- [x] Tasmota binary firmware version number used: 9.0.1
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: platformio
- [ ] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
18:45:52 CMD: Backlog Template; Module; GPIO 255
18:45:52 MQT: stat/sw_nappali/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
18:45:52 MQT: stat/sw_nappali/RESULT = {"Module":{"29":"Sonoff T1 2CH"}}
18:45:53 MQT: stat/sw_nappali/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"225":"Relay2"},"GPIO9":{"33":"Button2"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
```

### EXPECTED BEHAVIOUR
When pressing or double-pressing the same button, the topic postfix should be the same.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
