### ISSUE TITLE
Gosund P1 button switches wrong relay

### ISSUE THREAD

**Issue by FuXXz** [arendst/Tasmota#10143]
Hello everybody,

maybe someone can help me and tell me if I did something wrong.
I flashed a Gosund P1 bar with Tasmota 9.1
Everything works, except the buttons.

Most of the time they switch correctly. However, sometimes when I press button 2, relay 1 comes on. When I press button 2 again, relay 2 comes on. If I press button 3, relay1 sometimes switches on, etc.
It's messed up.

I have also set up this Rules
https://templates.blakadder.com/gosund_P1.html

I hope for help. thx

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
