### ISSUE TITLE
JSON template for sonoff mini is not saved

### ISSUE THREAD

**Issue by oferbar** [arendst/Tasmota#10157]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Saving a template from the Sonoff MINR2 Switch config page into other parameters page does not persist and is different when device started after the Save.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Mini R2
- [x] Tasmota binary firmware version number used: 9.1.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: tasmotizer-1.2
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

08:40:20 CMD: Backlog Template; Module; GPIO 255
08:40:20 MQT: stat/tasmota_629405/RESULT = {"NAME":"Sonoff MINIR2","GPIO":[32,0,0,0,160,0,0,0,224,320,0,0,1,0],"FLAG":0,"BASE":1}
08:40:20 MQT: stat/tasmota_629405/RESULT = {"Module":{"0":"Sonoff MINIR2"}}
08:40:20 MQT: stat/tasmota_629405/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"160":"Switch1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

08:40:58 CMD: Backlog Rule1; Rule2; Rule3
08:40:59 MQT: stat/tasmota_629405/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
08:40:59 MQT: stat/tasmota_629405/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
08:40:59 MQT: stat/tasmota_629405/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

08:41:26 CMD: Status 0
08:41:26 MQT: stat/tasmota_629405/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota_closet","FriendlyName":["Tasmota Closet"],"Topic":"tasmota_629405","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
08:41:26 MQT: stat/tasmota_629405/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T10:24:20","StartupUTC":"2020-12-16T21:17:06","Sleep":50,"CfgHolder":4617,"BootCount":14,"BCResetTime":"2020-12-16T17:06:06","SaveCount":65,"SaveAddress":"FB000"}}
08:41:26 MQT: stat/tasmota_629405/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"482/699"}}
08:41:26 MQT: stat/tasmota_629405/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["barshavit-tp2.4",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00000200","00006000","00000000"]}}
08:41:26 MQT: stat/tasmota_629405/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
08:41:26 MQT: stat/tasmota_629405/STATUS5 = {"StatusNET":{"Hostname":"tasmota_629405-5125","IPAddress":"192.168.0.197","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"C8:2B:96:62:94:05","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
08:41:26 MQT: stat/tasmota_629405/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.3","MqttPort":1883,"MqttClientMask":"tasmota_closet","MqttClient":"tasmota_closet","MqttUser":"homeassistant","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
08:41:26 MQT: stat/tasmota_629405/STATUS7 = {"StatusTIM":{"UTC":"2020-12-17T07:41:26","Local":"2020-12-17T08:41:26","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"08:38","Sunset":"16:53"}}
08:41:26 MQT: stat/tasmota_629405/STATUS10 = {"StatusSNS":{"Time":"2020-12-17T08:41:26","Switch1":"ON"}}
08:41:26 MQT: stat/tasmota_629405/STATUS11 = {"StatusSTS":{"Time":"2020-12-17T08:41:26","Uptime":"0T10:24:20","UptimeSec":37460,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SSID-XXXX","BSSId":"D8:07:B6:4C:71:1B","Channel":10,"RSSI":66,"Signal":-67,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Copy the Mini R2 template from: 
https://templates.blakadder.com/sonoff_MINIR2.html
Paste in the Other parameters page and Save.
After started up, the value of the template is different

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

The template value should have been saved

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

I have tried with different module types:
Sonoff Basic
Sonoff MINIR2
Generic

Same result, value not saved

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
