### ISSUE TITLE
DS18B20 not working in Tasmota v 9.2.0

### ISSUE THREAD

**Issue by helmar74** [arendst/Tasmota#10161]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X ] Device used (e.g., Sonoff Basic): _____Wemos Mini D with DS18B20
- [X ] Tasmota binary firmware version number used: _____v9.2.0
  - [ ] Pre-compiled
  - [X ] Self-compiled
    - [X ] IDE / Compiler used: _____PlatformIO
- [ ] Flashing tools used: _____OTA
- [X ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

15:08:22 SRC: WebConsole from 192.168.1.31
15:08:22 CMD: Gruppe 0, Index 1, Befehl "BACKLOG", Daten "Template; Module; GPIO 255"
15:08:22 SRC: Backlog
15:08:22 CMD: Gruppe 0, Index 1, Befehl "TEMPLATE", Daten ""
15:08:22 MQT: stat/sonoffWemosMini_9/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
15:08:23 SRC: Backlog
15:08:23 CMD: Gruppe 0, Index 1, Befehl "MODULE", Daten ""
15:08:23 MQT: stat/sonoffWemosMini_9/RESULT = {"Module":{"18":"Generic"}}
15:08:23 SRC: Backlog
15:08:23 CMD: Gruppe 0, Index 1, Befehl "GPIO", Daten "255"
15:08:23 MQT: stat/sonoffWemosMini_9/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"1312":"DS18x20"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ X] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS = {"Status":{"Module":18,"DeviceName":"sonoffWemosMini9","FriendlyName":["sonoffWemosMini9"],"Topic":"sonoffWemosMini_9","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffStandardGruppe","OtaUrl":"http://192.168.1.2:5555/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:49","StartupUTC":"2020-12-17T14:06:31","Sleep":50,"CfgHolder":4617,"BootCount":30,"BCResetTime":"2020-06-16T08:13:44","SaveCount":99,"SaveAddress":"FA000"}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS2 = {"StatusFWR":{"Version":"9.2.0(tasmota)","BuildDateTime":"2020.12.17 14:28:02","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"480/699"}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["hs.net_aussen_24GHz","hs.net_EG"],"TelePeriod":322,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS4 = {"StatusMEM":{"ProgramSize":586,"Free":416,"Heap":25,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashFrequency":40,"FlashMode":3,"Features":["00000407","8FA0C58F","04268BA1","02081CCF","002033C0","C2007081","00004024","00001000"],"Drivers":"1,2,3,4,6,8,9,10,13,16,18,19,22,24,26,35,37,45","Sensors":"1,3,4,5,6,9,10,16,22,35,41"}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS5 = {"StatusNET":{"Hostname":"sonoffWemosMini-9","IPAddress":"192.168.1.211","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.2","Mac":"CC:50:E3:C4:9A:3F","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.50","MqttPort":1883,"MqttClientMask":"sonoffWemosMini-9","MqttClient":"sonoffWemosMini-9","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS7 = {"StatusTIM":{"UTC":"2020-12-17T14:07:20","Local":"2020-12-17T15:07:20","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"07:56","Sunset":"16:13"}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS10 = {"StatusSNS":{"Time":"2020-12-17T15:07:20"}}
15:07:20 MQT: stat/sonoffWemosMini_9/STATUS11 = {"StatusSTS":{"Time":"2020-12-17T15:07:20","Uptime":"0T00:00:49","UptimeSec":49,"Vcc":2.945,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":2,"SSId":"hs.net_EG","BSSId":"E8:DF:70:67:B9:00","Channel":6,"RSSI":64,"Signal":-68,"LinkCount":1,"Downtime":"0T00:00:05"}}}

```
- [ X] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
5:07:45 SRC: WebConsole from 192.168.1.31
15:07:45 CMD: Gruppe 0, Index 1, Befehl "TELEPERIOD", Daten ""
15:07:45 MQT: stat/sonoffWemosMini_9/RESULT = {"TelePeriod":322}
15:07:46 MQT: tele/sonoffWemosMini_9/STATE = {"Time":"2020-12-17T15:07:46","Uptime":"0T00:01:15","UptimeSec":75,"Vcc":2.945,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":2,"SSId":"hs.net_EG","BSSId":"E8:DF:70:67:B9:00","Channel":6,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:05"}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Hi, I self compiled tasmota 9.2.0.
Everything is working, but DS18B20 on two different Wemos Mini D aren't recognized anymore.
I downgraded to 9.1.0. there it's working without an problem

Anything I can try?

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Have you tried the precompiled Tasmota-sensors.bin?

**Comment by helmar74** [comment]
> Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?
> 
> Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.
> 
> ### Support Information
> See [Docs](https://tasmota.github.io/docs/) for more information.
> See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
> See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
> See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

Updated the template.

**Comment by helmar74** [comment]
DS18x20 is configured on D4 GPIO2. But temperature isn't shown

**Comment by ascillato2** [comment]
Please try the precompiled Tasmota-sensors.bin?

**Comment by helmar74** [comment]
Tasmota-sensors.bin is working...

What could I have done wrong in my_user_config.h

**Comment by ascillato2** [comment]
> What could I have done wrong in my_user_config.h

I don't know. You haven't post that file. Sorry.

As it is a self compilation issue, it is better to address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). Hope you don't mind as the chat is a better and more dynamic channel for helping you in these types of cases.

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
