### ISSUE TITLE
Issues connecting device to AWS iot.  TSL error 1002

### ISSUE THREAD

**Issue by litzenberger** [arendst/Tasmota#10163]
### PROBLEM DESCRIPTION
I have followed directions and from AWS side I am able to connection using `test-invoke-authorizer` for the TasmotaAuth.

I used the output from AWS which is:
```
BackLog SetOption3 1; SetOption103 1; MqttHost XXXXX.iot.us-east-1.amazonaws.com; MqttPort 443; MqttUser tasmota?x-amz-customauthorizer-name=TasmotaAuth; MqttPassword XXXXXXXXXXXXXXXXX
```
Flashed the device according to docs.  Not sure what I am missing but the device gives:

17:57:49 MQT: TLS connection error: -1002
17:57:49 MQT: Connect failed to  XXXXXXX-ats.iot.us-east-1.amazonaws.com:443, rc -2. Retry in 10 sec

I have tried a coupe different ways to get this to work and same results.  Any ideas?

Thanks!

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Sonoff Basic - generic18_____
- [] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: __vscode/ platformio___
- [X] Flashing tools used: _Tasmotizer____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
18:37:40 CMD: Backlog Template; Module; GPIO 255
18:37:40 RSL: stat/Cardswipe7/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
18:37:41 RSL: stat/Cardswipe7/RESULT = {"Module":{"18":"Generic"}}
18:37:41 RSL: stat/Cardswipe7/RESULT = {"GPIO0":{"640":"I2C SDA"},"GPIO1":{"0":"None"},"GPIO2":{"608":"I2C SCL"},"GPIO3":{"353":"Counter2"},"GPIO4":{"352":"Counter1"},"GPIO5":{"224":"Relay1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"2880":"PN532 Rx"},"GPIO13":{"2848":"PN532 Tx"},"GPIO14":{"0":"None"},"GPIO15":{"480":"Buzzer"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
18:37:47 MQT: Attempting connection...
18:37:57 MQT: TLS connection error: -1002
18:37:57 MQT: Connect failed to  a1jmwrjvxtg55c-ats.iot.us-east-1.amazonaws.com:443, rc -2. Retry in 10 sec

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
18:39:24 CMD: Backlog Rule1; Rule2; Rule3
18:39:24 RSL: stat/Cardswipe7/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":271,"Free":240,"Rules":"ON mqtt#connected DO Subscribe Swipe6, tele/Cardswipe6/SENSOR, VL53L0X.Distance ENDON ON Event#Swipe6==0 DO Var1 0 ENDON ON Event#Swipe6==1 DO Var1 1 ENDON ON mqtt#connected DO Subscribe UID6, tele/Cardswipe6/SENSOR, PN532.UID ENDON ON Event#UID6!=0 DO Var6 %value% ENDON"}
18:39:24 RSL: stat/Cardswipe7/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
18:39:24 RSL: stat/Cardswipe7/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}

```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
18:39:54 CMD: Status 0
18:39:54 RSL: stat/Cardswipe7/STATUS = {"Status":{"Module":18,"DeviceName":"CardSwipe7","FriendlyName":["Display","Relay1","Coin1","Coin2","Coin3","Coin4","OpenPort","OKtoPlayLED"],"Topic":"Cardswipe7","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"Cardswipe6","SwitchMode":[1,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:39:54 RSL: stat/Cardswipe7/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:17:10","StartupUTC":"2020-12-17T16:22:44","Sleep":50,"CfgHolder":4617,"BootCount":3,"BCResetTime":"2020-11-20T08:14:13","SaveCount":11,"SaveAddress":"F5000"}}
18:39:54 RSL: stat/Cardswipe7/STATUS2 = {"StatusFWR":{"Version":"9.1.0.1(tasmota)","BuildDateTime":"2020-12-17T10:04:57","Boot":31,"Core":"2_7_4_7","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"486/699"}}
18:39:54 RSL: stat/Cardswipe7/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ARCADEASSISTANT",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028009","2805C8000100060000005A00000000000000","80000200","20606000","00000000"]}}
18:39:54 RSL: stat/Cardswipe7/STATUS4 = {"StatusMEM":{"ProgramSize":583,"Free":420,"Heap":20,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FF007C7","04108121","00000007","041000C0","40000A01","00000000","00000000"],"Drivers":"1,2,3,4,7,8,9,10,12,13,16,20,21,24,28,29","Sensors":"1,2,3,40,45"}}
18:39:54 RSL: stat/Cardswipe7/STATUS5 = {"StatusNET":{"Hostname":"Cardswipe7-4937","IPAddress":"192.168.0.104","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"F4:CF:A2:D1:53:49","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
18:39:54 RSL: stat/Cardswipe7/STATUS6 = {"StatusMQT":{"MqttHost":" a1jmwrjvxtg55c-ats.iot.us-east-1.amazonaws.com","MqttPort":443,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D15349","MqttUser":"tasmota?x-amz-customauthorizer-name=TasmotaAuth","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
18:39:54 RSL: stat/Cardswipe7/STATUS7 = {"StatusTIM":{"UTC":"2020-12-17T17:39:54","Local":"2020-12-17T18:39:54","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"08:38","Sunset":"16:53"}}
18:39:54 RSL: stat/Cardswipe7/STATUS10 = {"StatusSNS":{"Time":"2020-12-17T18:39:54","COUNTER":{"C1":0,"C2":0},"VL53L0X":{"Distance":1}}}
18:39:54 RSL: stat/Cardswipe7/STATUS11 = {"StatusSTS":{"Time":"2020-12-17T18:39:54","Uptime":"0T01:17:10","UptimeSec":4630,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":39,"MqttCount":0,"POWER1":"OFF","POWER2":"ON","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"ARCADEASSISTANT","BSSId":"74:DA:88:94:1D:A8","Channel":6,"RSSI":100,"Signal":-37,"LinkCount":1,"Downtime":"0T00:00:02"}}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
18:40:52 CMD: weblog 4
18:40:52 RSL: stat/Cardswipe7/RESULT = {"WebLog":4}
18:40:52 CFG: Saved to flash at F4, Count 12, Bytes 4096
18:40:56 RSL: tele/Cardswipe7/STATE = {"Time":"2020-12-17T18:40:56","Uptime":"0T01:18:12","UptimeSec":4692,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":38,"MqttCount":0,"POWER1":"OFF","POWER2":"ON","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"ARCADEASSISTANT","BSSId":"74:DA:88:94:1D:A8","Channel":6,"RSSI":100,"Signal":-36,"LinkCount":1,"Downtime":"0T00:00:02"}}
18:40:56 RSL: tele/Cardswipe7/SENSOR = {"Time":"2020-12-17T18:40:56","COUNTER":{"C1":0,"C2":0},"VL53L0X":{"Distance":1}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
1. Compile code with AWS_IOT_LIGHT and other directives according to docs
2. Use CloudFormation template for TasmotaAuth
3. flash device with new tasmota.bin
4. run backlog command from AWS cloudformation output.

Connection to AWS gives a TLS error 1002

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
connect to AWS mqtt

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
<img width="1250" alt="Screen Shot 2020-12-17 at 11 44 51 AM" src="https://user-images.githubusercontent.com/6003995/102523550-4d6c2000-405d-11eb-974f-f28e0497d769.png">

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by litzenberger** [comment]
> Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?
> 
> Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.
> 
> ### Support Information
> See [Docs](https://tasmota.github.io/docs/) for more information.
> See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
> See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
> See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

yes, sorry about that.  Updated template

**Comment by litzenberger** [comment]
the one things I cant verify is if the password is saved.  when I open the Configure MQTT, password is just three stars.  When I updated it to the current password and save it still shows three stars.  Is this expected?

**Comment by ascillato** [comment]
Yes, for security your password is never sent from Tasmota to the web browser.

**Comment by litzenberger** [comment]
I just tested my AWS on a nodeJS client and it is connecting.

**Comment by s-hadinger** [comment]
Error -1002 means that the tcp connection failed. I suppose that the domain name is correct. 

Your Tasmota device can't reach the endpoint.  Either DNS failed or something is blocking the connection on your network (firewall?)

**Comment by litzenberger** [comment]
yeah, that was my thought too nut I can reach the endpoint from my laptop connected to the same network.

**Comment by litzenberger** [comment]
The last thing I did was overwrite the host in the configure MQTT screen and its now connecting.  Thanks Ill close this.
