### ISSUE TITLE
Wrong sensor identification

### ISSUE THREAD

**Issue by tgonzalez1969** [arendst/Tasmota#10273]
Hi, 

Let me describe my issue. 

I've trying to control a VL53L0x Sensor -CJVL53L0XV2- (distance time-of-flight) with a tasmotized ESP01s. I use tasmota-sensors.bin file and the configuration is i2C SDA in GPIO0 and I2C SLC in GPIO2. 

Tasmota identifies it quickly and without problems, but it says it is a TSL2561 luminance sensor ¡¡¿?!! giving the following MQTT message:
4:06:01 MQT: tele/sensor/gasoleo/SENSOR = {"Time":"2020-12-27T14:06:01","TSL2561":{"Illuminance":0.000,"IR":0,"Broadband":0}}

I've purchased a new sensor to check if there is a HW problem. I'm waiting for its delivery in order to make some tests but meanwhile I ask here because i'm not sure if i'm doing something wrong, there is something I've lost or any previous configuration i must implement. 

Thanks in advance.

**Comment by joba-1** [comment]
look for the i2cdriver command in the docs. I think this is what you need
