### ISSUE TITLE
Rules failing afters set SwitchTopic to 1

### ISSUE THREAD

**Issue by Frans1960** [arendst/Tasmota#10306]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
The rules are not executed after setting SwitchTopic to 1. The Switch1 powers Power1, insteat of running the rules

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): SonOff Basic
- [ ] Tasmota binary firmware version number used: 9.0.2.
  - [x ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: OTA_____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [x ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
11:25:11 CMD: SwitchTopic 1
11:25:11 MQT: stat/SonoffCVPomp/RESULT = {"SwitchTopic":"SonoffCVPomp"}
11:25:19 MQT: cmnd/SonoffCVPomp/POWER1 = ON
11:25:19 MQT: stat/SonoffCVPomp/SWITCH1 = {"STATE":"ON"}
11:25:19 MQT: tele/SonoffCVPomp/STATE = {"Time":"2020-12-29T11:25:19","Uptime":"0T00:21:04","UptimeSec":1264,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21,"MqttCount":1,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"vanGalenAccessPoint#8","BSSId":"CC:32:E5:D6:FA:10","Channel":11,"RSSI":100,"Signal":-47,"LinkCount":1,"Downtime":"0T00:00:03"}}
11:25:19 MQT: stat/SonoffCVPomp/RESULT = {"POWER1":"ON"}
11:25:19 MQT: stat/SonoffCVPomp/POWER1 = ON
11:25:45 MQT: tele/SonoffCVPomp/STATE = {"Time":"2020-12-29T11:25:45","Uptime":"0T00:21:30","UptimeSec":1290,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"ON","POWER2":"ON","Wifi":{"AP":1,"SSId":"vanGalenAccessPoint#8","BSSId":"CC:32:E5:D6:FA:10","Channel":11,"RSSI":100,"Signal":-45,"LinkCount":1,"Downtime":"0T00:00:03"}}
11:25:45 MQT: stat/SonoffCVPomp/RESULT = {"POWER2":"ON"}
11:25:45 MQT: stat/SonoffCVPomp/POWER2 = ON
11:26:02 CMD: SwitchTopic 0
11:26:02 MQT: stat/SonoffCVPomp/RESULT = {"SwitchTopic":""}
11:26:15 RUL: SWITCH1#STATE performs "backlog event SwitchCV=0"
11:26:15 RUL: SWITCH1#STATE==OFF performs "ruletimer1 300"
11:26:15 MQT: stat/SonoffCVPomp/RESULT = {"T1":300,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
11:26:15 MQT: stat/SonoffCVPomp/SWITCH1 = {"STATE":"OFF"}
11:26:15 MQT: stat/SonoffCVPomp/RESULT = {"Event":"Done"}
11:26:15 RUL: EVENT#SWITCHCV performs "Power2 0"
11:26:15 MQT: tele/SonoffCVPomp/STATE = {"Time":"2020-12-29T11:26:15","Uptime":"0T00:22:00","UptimeSec":1320,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":30,"MqttCount":1,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"vanGalenAccessPoint#8","BSSId":"CC:32:E5:D6:FA:10","Channel":11,"RSSI":100,"Signal":-44,"LinkCount":1,"Downtime":"0T00:00:03"}}
11:26:15 MQT: stat/SonoffCVPomp/RESULT = {"POWER2":"OFF"}
11:26:15 MQT: stat/SonoffCVPomp/POWER2 = OFF


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
As designed. Switchtopic overrides rules. Please refer to Tasmota docs. Thanks.
