### ISSUE TITLE
[Feature Request] Telegram bypass certificate check

### ISSUE THREAD

**Issue by Tigger2014** [arendst/Tasmota#10320]
**Have you looked for this feature in other issues and in the docs?**
Yes, continuation of  #8619 

**A clear and concise description of what the problem is.**
Telegram support needs TLS and currently certificate must be validated, we should be able to disable this like is possible for MQTT over TLS

**Describe the solution you'd like**
Being able to set the telegram fingerprint to all FF to disable the check like the MQTT option
MqttFingerprint2 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF

Thanks

**Comment by fmarzocca** [comment]
Could it be useful that Universal Arduino Telegram Bot library has been updated by including a certificate to connect to https://..telegram...?

**Comment by Tigger2014** [comment]
Reopen, maybe move to discussion?

**Comment by bam80** [comment]
Ping on reopen?
