### ISSUE TITLE
SM2135 LED Bulb - switch between rgb/wy mode causes restart

### ISSUE THREAD

**Issue by SintraDD** [arendst/Tasmota#10356]
### PROBLEM DESCRIPTION
An LED lamp (MagicHome) with SM2135 cannot be switched  between rgb/wy mode
the bulb randomly reset (software watchdog) on power on/power off

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): 9W wifi Bulb RGBCW E27 with MagicHome Firmware
- [ ] Tasmota binary firmware version number used: 9.2.0.2(tasmota)2021.01.01 16:33:51
  - [x ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: OTA, Tasmotizer
- [ ] Provide the output of command: 
  Configuration output here:

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Switch form RGB to WY Mode via the GUI causes reboot
{"RestartReason":{"Exception":4,"Reason":"Software Watchdog","EPC":["400043e6","00000000","00000000"],"EXCVADDR":"00000000","DEPC":"00000000","CallChain":["40106a8f","4000410f","40004a3c","40106d20","40201c38","40242ef6","40201c88","40103918","40207fd7","4021543c","40230895","40101234","40101258","40101234","4021a135","4021a2c2","4021a376","4021a498","4021a7c2","4021a8e9","40229b6c","4020d2a4","40229ee1","401011ca","4021f8f1","40231147","40100a40","402459c8","40101e49"]}

### EXPECTED BEHAVIOUR
like described at https://github.com/curzon01/Tasmota/commit/b42955bd084d4ff605fcf6e4014f9a357dd86dd4
all channels should be power off, before power on rgb or wy mode

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
on this lamp GPIO4 is SM2135 Data, GPIO5 is SM2135 CLK
i used model mode 4 in config, because this mode is the onliy one, where i could power off the bulb with the off button
The Lamp has a ESP8285 with 2MB
R and B Channel is crossed, you must use "SetOption37 54"
(SM2135 Ch1=r, Ch2=G, Ch3=B, Ch4=warm, Ch5=cold)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
