### ISSUE TITLE
Tasmota webserver not reachable on Sonoff devices after some time

### ISSUE THREAD

**Issue by TungstenE2** [arendst/Tasmota#10361]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I have 2 Sonoff POW2 and 3 Sonoff S20 plugs. All are updated with 9.2.0.

On all devices the webserver becomes unreachable after some time, while MQTT is still working.

I have seen older posts with the same error reported but no solution.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Pow R2 and Sonoff Basic 
- [x] Tasmota binary firmware version number used: 9.2.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: OTA
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
11:18:50 CMD: Backlog Template; Module; GPIO 255
11:18:50 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,4704],"FLAG":0,"BASE":18}
11:18:50 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"Module":{"1":"Sonoff Basic"}}
11:18:50 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}}


```
- [] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
11:19:40 CMD: Status 0
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS = {"Status":{"Module":1,"DeviceName":"S20-02 Steckdose","FriendlyName":["S20-02 Steckdose"],"Topic":"Sonoff-S20-02","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T01:32:09","StartupUTC":"2021-01-02T08:47:31","Sleep":50,"CfgHolder":4617,"BootCount":67,"BCResetTime":"2020-08-04T18:35:07","SaveCount":6962,"SaveAddress":"FA000"}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS2 = {"StatusFWR":{"Version":"9.2.0(tasmota)","BuildDateTime":"2020-12-21T15:03:40","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"410/699"}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["12345",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["04008009","2805C8000100060000005AFF000000000000","00000001","00006000","00000000"]}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS4 = {"StatusMEM":{"ProgramSize":586,"Free":416,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS5 = {"StatusNET":{"Hostname":"Sonoff-S20-02-7987","IPAddress":"192.168.178.72","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.44","Mac":"DC:4F:22:2D:DF:33","Webserver":2,"WifiConfig":5,"WifiPower":17.0}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.44","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2DDF33","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS7 = {"StatusTIM":{"UTC":"2021-01-02T10:19:40","Local":"2021-01-02T11:19:40","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:36","Sunset":"16:36"}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS10 = {"StatusSNS":{"Time":"2021-01-02T11:19:40"}}
11:19:40 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/STATUS11 = {"StatusSTS":{"Time":"2021-01-02T11:19:40","Uptime":"0T01:32:09","UptimeSec":5529,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"on","Wifi":{"AP":1,"SSId":"12345","BSSId":"E0:63:DA:80:11:xx","Channel":1,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
11:20:34 CMD: weblog 4
11:20:34 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"WebLog":4}
11:20:34 CFG: Saved to flash at F9, Count 6963, Bytes 4096
11:20:37 WIF: Checking connection...
11:20:48 CMD: weblog
11:20:48 SRC: WebConsole from 192.168.178.20
11:20:48 CMD: Group 0, Index 1, Command "WEBLOG", Data ""
11:20:48 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"WebLog":4}
11:20:57 WIF: Checking connection...
11:21:10 CMD: lua
11:21:10 SRC: WebConsole from 192.168.178.20
11:21:10 CMD: Group 0, Index 1, Command "LUA", Data ""
11:21:10 MQT: /SmartHome/Steckdosen/Sonoff-S20-02/stat/RESULT = {"Command":"Unknown"}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Webserver becomes not reachable after some time, not special steps to reproduce

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Webserver should be reachable always

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

![grafik](https://user-images.githubusercontent.com/39955685/103455223-9bcf1f00-4ceb-11eb-89f6-3b20f06377e9.png)
![grafik](https://user-images.githubusercontent.com/39955685/103455228-ac7f9500-4ceb-11eb-828f-8ac658665f79.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Which wifi equipment do you have (brand type)? Is it a Mesh network?
Have you tried `SetOption41`?
Asus and Ubiquiti is known to have issues for some users. The reason for is still not found.
It is probably a incompatibility between espressif nonos-sdk  (closed source) and the firmware of the wifi equipment

**Comment by TungstenE2** [comment]
Yes, it is Mesh by Ubiquiti Unifi wifi network.

I also have serveral ESP8266 and ESP32 devices (espressif). 

ESP8266 running ESPeasy and have no Wifi issues.

So how best to identify the issue with Tasmota?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by TungstenE2** [comment]
@ascillato2 thx for your reply. Why do you believe this is not a software bug?

The reported issue is only with Tasmota software, none of my other IoT devices is having this issue.
Thats why I opened this ticket reporting an issue with the Tasmota webserver.

**Comment by TungstenE2** [comment]
How can this issue be network related if MQTT is working but webserver is not responding? Both is operated by the same network.

Here is older ticket with similar issue:
https://github.com/arendst/Tasmota/issues/266

@ascillato2 you marked the ticket as duplicated, please give ticket number of the other ticket you are referring to. Thx.

**Comment by Jason2866** [comment]
Because we have some feedbacks from users with Ubiquiti hardware with exactly this behaviour. Webserver is timing out but mqtt is working. After changing the wifi hardware the issue is gone.
So the question is why are you sure it is NOT the wifi hardware?
The issue you refer is very old. The issue has been found in Arduino ESP8266 core and it is fixed since 2019.

**Comment by TungstenE2** [comment]
Dear @Jason2866, thanks for your kind answer.

The reason I have my doubts about the wifi hw being the reason is that I have several other IoT devices connected to the same wifi hw and network without any issues. I have several Wemos D1 mini (ESP8266) and ESP32 where the webserver is not timing out. Only differnce is the software running on the devices. All devices with Tasmota the webserver is timing out and becomes unreachable. That is the reason I doubt the wifi network to be the reason of the issue.

So please reopen the issue in order to find the reason together, but just closing the issue is not a good way of dealing with it.

Happy to support in order to find the root cause, as you already stated this has been reported before. 

thx a lot.

**Comment by TungstenE2** [comment]
I have tried `SetOption41 60` via the console on all my devices, and for the last 18hrs the webserver was active and reachable.
May be this solved the issue.

**Comment by netzspezialist** [comment]
Same issue here:

**Device:** ESP-01s + [ESP-01 Relay V4.0 Relay Board](https://templates.blakadder.com/ESP-01S-Relay-v4.html)
**Firmware:** 15.0.1

Initially, during the Wi-Fi setup process, the Tasmota web UI worked perfectly fine. However, after the initial configuration was complete, I started experiencing intermittent issues accessing the UI. When I *was* able to connect to the module's IP address, only the main menu would load successfully. I was consistently unable to open any sub-menus (e.g., Configuration, Consoles, etc.) – clicking on them would either do nothing or lead to a page that wouldn't load.

I eventually managed to configure both the Wi-Fi and MQTT settings for the module using Tasmotizer, which allowed me to get the device working for its intended purpose.

**Temporary UI Access & Subsequent Loss:**
Approximately one hour after the initial setup and Tasmotizer configuration, I was surprisingly able to access the Tasmota WebUI completely and it functioned perfectly. During this period, I successfully changed the Tasmota template ({"NAME":"ESP01v4","GPIO":[256,320,0,32,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":18}) and then mounted the ESP-01s onto a relay board.

Since then, the MQTT functionality and ping responses have been working flawlessly (allowing me to control the relay ON/OFF). However, I am now completely unable to access the WebUI again. Attempts to reach the module's IP address in a browser result in no response or a connection timeout.

**Comment by sfromis** [comment]
Typical cause of Wifi trouble is power issues. Both about available ampere, voltage, stability and (especially with borderline hardware like ESP-01) if decoupling capacitor is sufficient. This also fits your initial symptoms about "intermittent issues".
