### ISSUE TITLE
Stopping fade in progress with Fade 0 is buggy

### ISSUE THREAD

**Issue by plamenko** [arendst/Tasmota#10382]
### PROBLEM DESCRIPTION

There is a bug in how tasmota handles fading. Repro steps:
1. Set max brightness with `backlog fade 0; dimmer 100`
2. Start decreasing brightness with some speed: `backlog fade 1; speed 8; dimmer 10`
3. Stop the transition started with 2. while it's still in progress: `fade 0`
4. Start another transition: `backlog fade 1; speed 8; dimmer 10`

The last command 4 should continue fading from where the bulb last left off when the transition 2 was stopped with 3.

However, when the command 4 gets issued, the bulb first instantly jumps to 100% brightness (a bug!) and only then starts fading out.

Also, the dimmer value reported with `state` is incorrect when the transition is interrupted with `fade 0`. Namely, state reports the target dimmer value as if the transition completed rather than the actual dimmer value where the bulb left off when the transition has been stopped with `fade 0`.

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Fulighture RGBW 15W RGBW Bulb
- [x] Tasmota binary firmware version number used: Tasmota 9.1.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: tuyaconvert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

01:23:45 MQT: stat/rgbw_led3/RESULT = {"NAME":"Fulighture RGBW 15W","GPIO":[0,0,0,0,0,0,0,0,0,3008,0,3040,0,0],"FLAG":0,"BASE":18}
01:23:46 MQT: stat/rgbw_led3/RESULT = {"Module":{"0":"Fulighture RGBW 15W"}}
01:23:46 MQT: stat/rgbw_led3/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"3008":"MY92x1 DI"},"GPIO14":{"0":"None"},"GPIO15":{"3040":"MY92x1 DCKI"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

01:25:11 CMD: Status 0
01:25:11 MQT: stat/rgbw_led3/STATUS = {"Status":{"Module":0,"DeviceName":"rgbw_led3","FriendlyName":["rgbw_led3"],"Topic":"rgbw_led3","ButtonTopic":"0","Power":1,"PowerOnState":1,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
01:25:11 MQT: stat/rgbw_led3/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"3T06:41:13","StartupUTC":"2020-12-30T17:43:58","Sleep":50,"CfgHolder":4617,"BootCount":229,"BCResetTime":"2020-12-01T22:44:47","SaveCount":1123,"SaveAddress":"F4000"}}
01:25:11 MQT: stat/rgbw_led3/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"442/699"}}
01:25:11 MQT: stat/rgbw_led3/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["plamenko-uiot",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00080200","00006000","00000000"]}}
01:25:11 MQT: stat/rgbw_led3/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440C8","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
01:25:11 MQT: stat/rgbw_led3/STATUS5 = {"StatusNET":{"Hostname":"rgbw_led3","IPAddress":"192.168.20.5","Gateway":"192.168.20.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.20.1","Mac":"BC:DD:C2:A4:4B:C9","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
01:25:11 MQT: stat/rgbw_led3/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.123","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A44BC9","MqttUser":"mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
01:25:11 MQT: stat/rgbw_led3/STATUS7 = {"StatusTIM":{"UTC":"2021-01-03T00:25:11","Local":"2021-01-03T01:25:11","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:43","Sunset":"17:05"}}
01:25:11 MQT: stat/rgbw_led3/STATUS10 = {"StatusSNS":{"Time":"2021-01-03T01:25:11"}}
01:25:11 MQT: stat/rgbw_led3/STATUS11 = {"StatusSTS":{"Time":"2021-01-03T01:25:11","Uptime":"3T06:41:13","UptimeSec":283273,"Heap":23,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"POWER":"ON","Dimmer":100,"Color":"0,0,0,255","HSBColor":"0,100,0","White":100,"Channel":[0,0,0,100],"Scheme":0,"Fade":"OFF","Speed":8,"LedTable":"ON","Wifi":{"AP":1,"SSId":"plamenko-uiot","BSSId":"76:AC:B9:9B:ED:7C","Channel":11,"RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

01:26:31 CMD: backlog fade 1; speed 8; dimmer 10
01:26:31 SRC: WebConsole from 192.168.2.191
01:26:31 CMD: Group 0, Index 1, Command "BACKLOG", Data "fade 1; speed 8; dimmer 10"
01:26:31 SRC: Backlog
01:26:31 CMD: Group 0, Index 1, Command "FADE", Data "1"
01:26:31 MQT: stat/rgbw_led3/RESULT = {"Fade":"ON"}
01:26:31 SRC: Backlog
01:26:31 CMD: Group 0, Index 1, Command "SPEED", Data "8"
01:26:31 MQT: stat/rgbw_led3/RESULT = {"Speed":8}
01:26:31 SRC: Backlog
01:26:31 CMD: Group 0, Index 1, Command "DIMMER", Data "10"
01:26:31 MQT: tele/rgbw_led3/STATE = {"Time":"2021-01-03T01:26:31","Uptime":"3T06:42:33","UptimeSec":283353,"Heap":24,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"POWER":"ON","Dimmer":10,"Color":"0,0,0,26","HSBColor":"0,100,0","White":10,"Channel":[0,0,0,10],"Scheme":0,"Fade":"ON","Speed":8,"LedTable":"ON","Wifi":{"AP":1,"SSId":"plamenko-uiot","BSSId":"76:AC:B9:9B:ED:7C","Channel":11,"RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:06"}}
01:26:31 MQT: stat/rgbw_led3/RESULT = {"POWER":"ON","Dimmer":10,"Color":"0,0,0,26","HSBColor":"0,100,0","White":10,"Channel":[0,0,0,10]}
01:26:36 CFG: Saved to flash at F8, Count 1127, Bytes 4096

```

### TO REPRODUCE

See the problem description.

### EXPECTED BEHAVIOUR

`Fade 0` should stop the current transition (if any), and leave the bulb in a correct state with the dimmer value being the current dimmer value rather than the original transition's target dimmer value.

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
N/A

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
Changing Fade during a fade is not supported and behavior is u predictable. 

Fade code is complex enough and code will not be added for corner cases that are not supposed to happen. Unless you have a use case that interests multiple users.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
