### ISSUE TITLE
'template' cmd reports not what is configured?

### ISSUE THREAD

**Issue by btsimonh** [arendst/Tasmota#10389]
### PROBLEM DESCRIPTION
compiled development branch, built and flashed a Gosund WB4-D buld with 'tasmota'.
Configured as 'Generic (0)' and setup PWM on GPIOS.

issued 'template' command

I get 
20:04:38.325 RSL: stat/tasmota_C25B0F/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}

I expected it to be more like:
{"NAME":"Generic","GPIO":[0,0,0,0,419,0,0,0,416,417,418,0,0,0],"FLAG":0,"BASE":18}

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Generic
- [x] Tasmota binary firmware version number used: 9.2.0.2(lite)
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: platformio
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
20:09:29.239 CMD: Backlog Template; Module; GPIO 255
20:09:29.298 RSL: stat/tasmota_C25B0F/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
20:09:29.499 RSL: stat/tasmota_C25B0F/RESULT = {"Module":{"0":"Generic"}}
20:09:29.710 RSL: stat/tasmota_C25B0F/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"419":"PWM4"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"416":"PWM1"},"GPIO13":{"417":"PWM2"},"GPIO14":{"418":"PWM3"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
20:08:18.140 CMD: status 0
20:08:18.146 RSL: stat/tasmota_C25B0F/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_C25B0F","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
20:08:18.150 RSL: stat/tasmota_C25B0F/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:42:31","StartupUTC":"2021-01-03T18:25:47","Sleep":50,"CfgHolder":4617,"BootCount":7,"BCResetTime":"2021-01-03T18:14:09","SaveCount":152,"SaveAddress":"F4000"}}
20:08:18.155 RSL: stat/tasmota_C25B0F/STATUS2 = {"StatusFWR":{"Version":"9.2.0.2(lite)","BuildDateTime":"2021-01-03T15:32:38","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"363/699"}}
20:08:18.159 RSL: stat/tasmota_C25B0F/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MYSSID","GARDEN"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
20:08:18.165 RSL: stat/tasmota_C25B0F/STATUS4 = {"StatusMEM":{"ProgramSize":477,"Free":524,"Heap":29,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F000783","04108001","00000006","010001C0","00000000","00004004","00000000"],"Drivers":"1,2,3,4,9,10,16,20,21,37","Sensors":"3"}}
20:08:18.169 RSL: stat/tasmota_C25B0F/STATUS5 = {"StatusNET":{"Hostname":"tasmota_C25B0F-6927","IPAddress":"192.168.1.64","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"10:52:1C:C2:5B:0F","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
20:08:18.173 RSL: stat/tasmota_C25B0F/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C25B0F","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
20:08:18.179 RSL: stat/tasmota_C25B0F/STATUS7 = {"StatusTIM":{"UTC":"2021-01-03T19:08:18","Local":"2021-01-03T20:08:18","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:43","Sunset":"17:05"}}
20:08:18.183 RSL: stat/tasmota_C25B0F/STATUS10 = {"StatusSNS":{"Time":"2021-01-03T20:08:18"}}
20:08:18.189 RSL: stat/tasmota_C25B0F/STATUS11 = {"StatusSTS":{"Time":"2021-01-03T20:08:18","Uptime":"0T00:42:31","UptimeSec":2551,"Vcc":3.440,"Heap":29,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"MYSSID","BSSId":"00:37:B7:30:E0:0E","Channel":4,"RSSI":86,"Signal":-57,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
