### ISSUE TITLE
Energy Meters lost datas

### ISSUE THREAD

**Issue by FalkPe** [arendst/Tasmota#10456]
Hello everybody,
All of my Tasmotized Energy Meters (different Manufacturer) loose their EnergyTotal when they be unplugged.
EnergyYesterday will be kept.

I have to search in my database the kWh and add them manually by Energyreset3 xxxxx with hands.

What is the problem? All units use the 9.2.0

Greetings

**Comment by ascillato** [comment]
Please, search in issues. Yours is duplicated and has been answered several times before. Thanks.
