### ISSUE TITLE
SH1106 Text Issue - every other line of dots

### ISSUE THREAD

**Issue by scargill** [arendst/Tasmota#10516]
I have an SH1106 OLED I2c  display - 1.3" 128*64. I'm using Latest Tasmota-display.bin dev version 9.2.0.3

The display will not show text correctly - every alternative line seems blank. 

If I use an SSD1306 - again 128*64 but 0.96" display - text, circles, rectangles work perfectly but the SH1106 not.

I've tried various DISPLAYMODEL including 2 and 7.

Can anyone help, Antonio (Mr Shark, Squazaloo) had the same issue with the SH1106 - but is now stuck miles away from the board thanks to Covid. Anyone with experience of this board and Tasmota please help?
![2021-01-11 13_50_52-Your Phone](https://user-images.githubusercontent.com/1889411/104184648-10087180-5414-11eb-9e19-0fa137b25825.png)
![2021-01-09 12_23_33-Your Phone](https://user-images.githubusercontent.com/1889411/104184743-3c23f280-5414-11eb-98b8-49785f0a4cde.png)

The SSD1306 is shown working fine here, see SH1106 - every other line is blank

**Comment by arendst** [comment]
Pete,

pls provide output of command ``Display``

**Comment by arendst** [comment]
I've played around with some parameters but I fail to see the result like yours.

It could well be your display is broken failing to display the odd lines.

**Comment by scargill** [comment]
Thanks for the quick response Theo - I normally figure out stuff like this on my own - but this has me. Ok, so to make sure neither of us uis making assumptions - tasmota-display.bin 9.2.0.3  - plugged the display in. Set displaymode 0. Displaymodel 7. Rebooted (no other flags set - this was a clean ESP8266.

Your request... "Display" output.
18:07:52.871 MQT: stat/sh1106/RESULT = {"Display":{"Model":7,"Width":128,"Height":64,"Mode":0,"Dimmer":1,"Size":1,"Font":1,"Rotate":0,"Refresh":2,"Cols":[16,8],"Rows":2}}

I've no idea why I see "Row!:2" at the end. My REFRESH is different to yours, as is "Cols" -  no idea why.

And after that if I simply type "DisplayText Hi There" I get "Hi there" with the first line there, second missing, third there etc.  So the horizontal line in "H" is missing etc.

Anything I need to change/add?

**Comment by scargill** [comment]
Elsewhere you commented about a potential duff display. Depending o your response to the above, I will tackle anggood for a replacement - or not... But as Antonio (Mr Shark) in Italy suffered the same issue, possibly we're missing something?

**Comment by scargill** [comment]
I figured out that rows and cols so mine is now the same as yours - exactly the same result. The only differnce is "mode" and thats because you are showing time/date wher I'm doing text. I changed mode to 1 - same result - every other line missing - but it is clearly trying to show the time and date inc seconds.

**Comment by scargill** [comment]
My display IS duff - Antonio just replicated what exactly what I did and his works. I am SO sorry to take up your time.
