### ISSUE TITLE
Sonoff devices and release 9.2.0.3

### ISSUE THREAD

**Issue by elkorleone** [arendst/Tasmota#10530]
### PROBLEM DESCRIPTION
I have update all devices in my lan but a couple of them cant update to 9.2.0.3. It shows 9.2.0 and program size is lower than 9.2.0.3 (see snapshop below)

### REQUESTED INFORMATION
How can I update to the last version?

### TO REPRODUCE
I use the same .bin file for all of them. First the minimal one and then the last version

### SCREENSHOTS
https://fotos.subefotos.com/5be194b16f848a4a2e3d2133f5d61238o.png

**Comment by sfromis** [comment]
Always use the .bin.gz versions for OTA upgrades

**Comment by elkorleone** [comment]
But I've used the local upload

**Comment by Jason2866** [comment]
Use the .bin.gz. files for local upload too.

**Comment by sfromis** [comment]
Anytime you use the web UI for upgrades, it is OTA, be it via URL or file.

**Comment by elkorleone** [comment]
Ah ok! I mean via file, not url

Problem fixed using the .bin.bz file!!!
