### ISSUE TITLE
Sonoff ZBBridge - Zigbee stack

### ISSUE THREAD

**Issue by moodyblue** [arendst/Tasmota#10552]
All is ok with 9.1.0, but with 9.2.0 the zigbee service aborts with message `zig: timeout, goto label 99`

In other words, in 9.1.0 `tasmota-zbbridge.bin` + `ncp-uart-sw_6.7.6_115200.ota` is ok, but in 9.2.0 it produces above error.

**Comment by s-hadinger** [comment]
Please reach out on Discord or open a Github discussion. Also provide `Weblog 3` logs of the failed Zigbee start.

**Comment by ascillato2** [comment]
#10553
