### ISSUE TITLE
Gosund SP111 Plug Meter TotalPower loss

### ISSUE THREAD

**Issue by martin2704-Ger** [arendst/Tasmota#10588]
After update from ver 8.5.0 to 9.1.0 the TotalPower State loses its data after unplugging it from the outlet. My othe Gosund plug still on 8.5.0 keeps it data

**Comment by ascillato** [comment]
As designed. When it is unplugged. Today is resetted. Total is saved only at midnight.

If you need further information, please search in old issues as this has been already answered several times before. 

Thanks.
