### ISSUE TITLE
BN-LINK BNC-60/U133TJ loses all energy totals after a power cycle 9.2.0 lite

### ISSUE THREAD

**Issue by Black6spdZ** [arendst/Tasmota#10608]
BN-LINK smart switch BNC-60/U133TJ loses all energy totals after a power cycle, I don't remember this happening on alder versions.

**Comment by ascillato** [comment]
As designed. Please do a quick search in issues. Already explained several times. Thanks.

**Comment by Black6spdZ** [comment]
https://github.com/arendst/Tasmota/issues/1202#issuecomment-345512402

This is NOT the behavior seen

**Comment by ascillato** [comment]
See in recent issues. Please do a quick search.
