### ISSUE TITLE
Please document Tasmota variables

### ISSUE THREAD

**Issue by GijsTimmers** [arendst/Tasmota#10645]
### PROBLEM DESCRIPTION
There must be some variables available in Tasmota. For instance, in wifi config: `%s-%04d`. It seems like these variables are not documented. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): LSC Smart Plug
- [ ] Tasmota binary firmware version number used: 8.5.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
21:08:24 MQT:0 stat/kza/RESULT = {"NAME":"Sonoff Mini","GPIO":[17,0,0,0,9,0,0,0,21,56,0,0,255],"FLAG":0,"BASE":1}
21:08:24 MQT: stat/kza/RESULT = {"Module":{"0":"Sonoff Mini"}}
21:08:24 MQT: stat/kza/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"9":"Switch1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
21:09:40 MQT: stat/kza/STATUS = {"Status":{"Module":0,"DeviceName":"kza","FriendlyName":["kza"],"Topic":"kza","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":8,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[5,3,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
21:09:40 MQT: stat/kza/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"7T23:04:54","StartupUTC":"2021-01-12T21:04:46","Sleep":50,"CfgHolder":4617,"BootCount":53,"BCResetTime":"2020-10-23T19:35:38","SaveCount":673,"SaveAddress":"FB000"}}
21:09:40 MQT: stat/kza/STATUS2 = {"StatusFWR":{"Version":"8.5.1(tasmota)","BuildDateTime":"2020-10-02T10:09:47","Boot":7,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"428/699"}}
21:09:40 MQT: stat/kza/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXX",""],"TelePeriod":0,"Resolution":"558180C0","SetOption":["00008029","2805C8000100060000005A00000000000000","000000E0","00006000","00000000"]}}
21:09:40 MQT: stat/kza/STATUS4 = {"StatusMEM":{"ProgramSize":596,"Free":404,"Heap":20,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
21:09:40 MQT: stat/kza/STATUS5 = {"StatusNET":{"Hostname":"kza","IPAddress":"192.168.1.176","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"F4:CF:A2:16:70:53","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
21:09:40 MQT: stat/kza/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.4","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_167053","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
21:09:40 MQT: stat/kza/STATUS7 = {"StatusTIM":{"UTC":"2021-01-20T20:09:40","Local":"2021-01-20T21:09:40","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:34","Sunset":"17:28"}}
21:09:40 MQT: stat/kza/STATUS10 = {"StatusSNS":{"Time":"2021-01-20T21:09:40","Switch1":"ON"}}
21:09:40 MQT: stat/kza/STATUS11 = {"StatusSTS":{"Time":"2021-01-20T21:09:40","Uptime":"7T23:04:54","UptimeSec":687894,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXX","BSSId":"XXX","Channel":11,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:07"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
N/A

### EXPECTED BEHAVIOUR
N/A

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
N/A

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the Tasmota Docs ( https://github.com/tasmota/docs/issues ).

Thanks.

--------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
