### ISSUE TITLE
Tasmota configuration for LED Strip model spider T

### ISSUE THREAD

**Issue by ilanoud** [arendst/Tasmota#10681]
Hi,
Recently got the same LED strip (spider T), successfully flashed it with Tasmota but now I can’t figure how to configurate it ...

Can someone explain please? (what module, what parameters, ...)
I’d like to select colors, brightness and use on/off, all by using Tasmota directly at first...

Thx

_Originally posted by @ilanoud in https://github.com/arendst/Tasmota/issues/7091#issuecomment-766434706_

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
