### ISSUE TITLE
BUG / FEATURE-REQUEST / Scan for Wifi every 10 Minutes and connect to strongest network

### ISSUE THREAD

**Issue by RcRaCk2k** [arendst/Tasmota#10739]
Hi,

i have 13 WLAN Access-Points in my home. Tasmota is selecting random Access-Point instead of strongest one.

Will there be a better WLAN selection in near future?

Also if i reboot an Access-Point, after some time the Tasmota should reconnect to the strongest AP, instead of hanging around with an -79dBm connection where a -44dBm connection is available.

If there will be a new field where you can insert a preferred BSSID that will be cool. So i can select an Access-Point that i desire.

**Comment by ascillato** [comment]
Hi,

Please, check in the docs https://tasmota.github.io/docs/Commands/#setoption56 and https://tasmota.github.io/docs/Commands/#setoption57
