### ISSUE TITLE
Dimmer + command not working via web requests

### ISSUE THREAD

**Issue by EPstudios** [arendst/Tasmota#10737]
### PROBLEM DESCRIPTION
Dimmer + not working via web requests, Dimmer - works fine, as does specifying a percentage 
ie say my dimmer is at 50%
running `/cm?cmnd=Dimmer%20-` returns `{"POWER":"ON","Dimmer":40}` and the light dims
then running `/cm?cmnd=Dimmer%20+`still returns `{"POWER":"ON","Dimmer":40}` and the light doesn't change as opposed to the expected increase.

Dimmer + works fine using the console

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _TCP Smart 810lm Filament Dimmable Bulb____
- [ ] Tasmota binary firmware version number used: __9.2___
  - [ ] Pre-compiled Y
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

20:14:00 RSL: stat/tasmota_EE3947/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
20:14:00 RSL: stat/tasmota_EE3947/RESULT = {"Module":{"0":"Generic"}}
20:14:00 RSL: stat/tasmota_EE3947/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"448":"PWM_i1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
20:15:03 RSL: stat/tasmota_EE3947/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_EE3947","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release-9.1.0/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:21:21","StartupUTC":"2021-01-28T18:53:42","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2021-01-26T20:04:36","SaveCount":108,"SaveAddress":"F7000"}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"358/699"}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ASUS",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS5 = {"StatusNET":{"Hostname":"tasmota_EE3947-6471","IPAddress":"192.168.3.2","Gateway":"192.168.3.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.3.1","Mac":"DC:4F:22:EE:39:47","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_EE3947","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS7 = {"StatusTIM":{"UTC":"2021-01-28T19:15:03","Local":"2021-01-28T20:15:03","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:25","Sunset":"17:40"}}
20:15:03 RSL: stat/tasmota_EE3947/STATUS10 = {"StatusSNS":{"Time":"2021-01-28T20:15:03"}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

20:17:01 SRC: WebCommand from 192.168.3.5
20:17:01 CMD: Group 0, Index 1, Command "DIMMER", Data ""
20:17:01 RSL: stat/tasmota_EE3947/RESULT = {"Dimmer":40}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

as per description 

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

as per description 

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Bad HTTP encoding.

Your command should be **http://IP/cm?cmnd=Dimmer%20%2B**
