### ISSUE TITLE
Support using Bluetooth when Wifi is off

### ISSUE THREAD

**Issue by yoyanec** [arendst/Tasmota#10733]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I am using module LilyGO ttgo-t-eth-poe with Tasmota 9.2.0.4. Ethernet works like a charm. When module is cnnected to Wifi, it can read data from Thermometer LYWSD03MMC with no issue. But when i disable Wifi with command `wifi off`, bluetooth stop working. I dont thing it is a bug, so i want to kindly ask for support for bluetooth with wifi off.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): LILYGO® TTGO T-Internet-POE ESP32-WROOM LAN8720A
- [x] Tasmota binary firmware version number used: Custom build based on tasmota32 with ethernet support
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: Platformio (esptool)
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
{"NAME":"LilyGO ttgo-t-eth-poe","GPIO":[0,1,1,1,1,1,1,1,1,1,1,1,1,1,5600,1,0,1,1,5568,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
{"Module":{"0":"LilyGO ttgo-t-eth-poe"}}
{"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"5600":"ETH MDIO"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"5568":"ETH MDC"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO28":{"0":"None"}}`
{"GPIO29":{"0":"None"},"GPIO30":{"0":"None"},"GPIO31":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
19:14:57.601 CMD: Group 0, Index 1, Command "STATUS", Data "0"
19:14:57.607 RSL: stat/poe_bt_55A5D4/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"poe_bt_55A5D4","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:14:57.635 RSL: stat/poe_bt_55A5D4/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"*********","RestartReason":"Software reset CPU","Uptime":"0T00:00:26","StartupUTC":"2021-01-28T18:14:31","Sleep":0,"CfgHolder":4619,"BootCount":37,"BCResetTime":"2021-01-28T17:01:45","SaveCount":67}}
19:14:57.666 RSL: stat/poe_bt_55A5D4/STATUS2 = {"StatusFWR":{"Version":"9.2.0.4(tasmota)","BuildDateTime":"2021-01-28T18:25:24","Core":"1_0_5_RC6","SDK":"v3.3.4-402-gcd59d107b","CpuFrequency":80,"Hardware":"ESP32","CR":"394/699"}}
19:14:57.687 RSL: stat/poe_bt_55A5D4/STATUS3 = {"StatusLOG":{"SerialLog":4,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Mona",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000001","00004000","00000002"]}}
19:14:57.715 RSL: stat/poe_bt_55A5D4/STATUS4 = {"StatusMEM":{"ProgramSize":1409,"Free":1984,"Heap":111,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F8004CA","00000001","00000045","010001C0","40000800","40004000","00200000","00000000"],"Drivers":"1,2,3,4,8,9,10,29,50,79,82","Sensors":"1,3,5,62"}}
19:14:57.744 RSL: stat/poe_bt_55A5D4/STATUS5 = {"StatusNET":{"Hostname":"poe_bt_55A5D4-1492_eth","IPAddress":"10.10.12.139","Gateway":"10.10.12.1","Subnetmask":"255.255.252.0","DNSServer":"10.10.12.1","Mac":"84:CC:A8:55:A5:D7","Webserver":2,"WifiConfig":0,"WifiPower":17.0}}
19:14:57.767 RSL: stat/poe_bt_55A5D4/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_55A5D4","MqttUser":"BILKA_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
19:14:57.789 RSL: stat/poe_bt_55A5D4/STATUS7 = {"StatusTIM":{"UTC":"2021-01-28T18:14:57","Local":"2021-01-28T19:14:57","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:25","Sunset":"17:40"}}
19:14:57.808 RSL: stat/poe_bt_55A5D4/STATUS10 = {"StatusSNS":{"Time":"2021-01-28T19:14:57"}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
M32: Kick off readOneSensor
M32: Kick off tele sending
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Enable Ethernet support, set correct template, enable bluetooth driver with `setoption115 1` and disable wifi with `wifi off`.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Read sensor data from Thermometer LYWSD03MMC and send them via MQTT exactly like with `wifi on`

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![Alt text](https://blog.bilka.sk/screenshot.png "Screenshot")

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving to Discussions as it is a Feature Request and not an issue.
