### ISSUE TITLE
Sonoff: enable 'vcc' in mqtt state messages via console

### ISSUE THREAD

**Issue by RaSTuS26** [arendst/Tasmota#10742]
I've noticed vcc is now missing in mqtt tele/state messages.  Is there any way to enable this behaviour from the console?

There's the "#define USE_ADC_VCC" in my_user_config.h, but I don't want to really go through the trouble of flashing them all (approx 20) again manually.

**Comment by Jason2866** [comment]
No way, since it is only possible at compile time. This is a Esp8266 restriction.

**Comment by ascillato** [comment]
Duplicated issue

#5671
https://github.com/arendst/Tasmota/discussions/10744
