### ISSUE TITLE
Using tasmota to flash other device via wifi

### ISSUE THREAD

**Issue by podarok** [arendst/Tasmota#10752]
Is there any way to tune tasmota to become wifi flasher for another esp8266, connected to gpio ports?

Right now upgrade of firmware works for the chip, which runs http server, but would be great to have in arsenal just a workhorse which could be used in AP mode to flash connected board to it.

**Comment by ascillato** [comment]
Hi, 

That is already implemented. Please, read the docs at https://tasmota.github.io/docs/TasmotaClient/

Thanks.
