### ISSUE TITLE
reset bootcount cmd didn't work properly

### ISSUE THREAD

**Issue by ChrSchultz** [arendst/Tasmota#10797]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
if i  type in tasmota console  on my d1_mini_pro: `reset 99` for reset the bootcount to zero in the logging appears:
`CMD: Gruppe 0, Index 1, Befehl "RESET", Daten "99"
22:11:53 MQT: stat/tasmota_5B4E21/RESULT = {"Reset":"Done"}
22:11:54 CFG: in Flash gespeichert am FA, zählen 98, Bytes 4096`
so i think, the bootcount is set to count +1. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Are you assuming that the number displayed in the flash save message is bootcount?
`22:11:54 CFG: in Flash gespeichert am FA, zählen 98, Bytes 4096`
That number is number of saves to flash, not the number of boots. On one particular device, in the output of `Status 1`, I'm seeing both `"BootCount":162`, and `"SaveCount":794` with the latter being the number you see in the message.
