### ISSUE TITLE
Unable to connect to MQTT server starting with version 9.2.0

### ISSUE THREAD

**Issue by joeH68** [arendst/Tasmota#10809]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

1. Two years old Sonoff RF Bridge device running different Tasmota versions worked without any problems until 9.2 was installed. From that point on, the device could not connect to the MQTT server and reported "Connect failed ... retry in XX sec".
2. The problem was almost permanent (>90% of the time). The embedded Webserver could be accessed without problems. The Websend command was able to submit HTTP commands.
3. Downgrading to version 9.1 immediately solved the issue and the Sonoff device connected to the MQTT server at the first attempt.
4. I have other Sonoff RF&ZB Bridge devices (local and remote) with Tasmota 9.2, working with the same MQTT server without any problems.
5. The remote devices are installed at different locations and use VPN links to communicate with the MQTT server.
6. The failing Sonoff RF Bridge uses a particularly "slow" connection (Ping shows rtt min/avg/max/mdev = 195.592/218.146/276.517/24.229 ms).
7. In this configuration, the Sonoff RF Bridge is used by local, non-time critical sensors, to report information to openHab via MQTT.
8. The Tasmota 9.2 changelog includes following change:  "MQTT Wifi connection timeout from 5000 to 200 mSec #9886". I have the impression my problem has to do with this change.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: v9.2.0 Julie 
  - [x ] Pre-compiled
  - [ ] Self-compiled
- [X] Flashing tools used: OTA
- [NA ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ NA] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
18:04:42 CMD: Status 0
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS = {"Status":{"Module":25,"DeviceName":"MIMB758-TR-SONOFF-RF-BRIDGE","FriendlyName":["MIMB758-TR-SONOFF-RF-BRIDGE"],"Topic":"SonoffRFbridge_C0CCE3","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":1,"SwitchRetain":1,"SensorRetain":0,"PowerRetain":1}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS1 = {"StatusPRM":{"Baudrate":19200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release-9.1.0/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:49:47","StartupUTC":"2021-02-02T22:14:55","Sleep":0,"CfgHolder":4617,"BootCount":505,"BCResetTime":"2020-04-07T09:31:03","SaveCount":2430,"SaveAddress":"F8000"}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":7,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"489/699"}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":1,"SysLog":3,"LogHost":"10.120.11.4","LogPort":514,"SSId":["LRS-WiFi",""],"TelePeriod":900,"Resolution":"558180C0","SetOption":["8400A0E9","2805FF000100060000965A00000000000000","0000800D","00086002","00000000"]}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS5 = {"StatusNET":{"Hostname":"MIMB758-SONOFF-RFBRIDGE-C0CCE3","IPAddress":"10.120.88.230","Gateway":"10.120.88.1","Subnetmask":"255.255.255.0","DNSServer":"10.120.88.1","Mac":"2C:F4:32:C0:CC:E3","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS6 = {"StatusMQT":{"MqttHost":"10.120.11.4","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C0CCE3","MqttUser":"TASMOTA","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS7 = {"StatusTIM":{"UTC":"2021-02-02T23:04:42","Local":"2021-02-02T18:04:42","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"-05:00","Sunrise":"06:03","Sunset":"18:39"}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS10 = {"StatusSNS":{"Time":"2021-02-02T18:04:42-05:00"}}
18:04:42 MQT: mimb758/SonoffRFbridge_C0CCE3/STATUS11 = {"StatusSTS":{"Time":"2021-02-02T18:04:42-05:00","Uptime":"0T00:49:47","UptimeSec":2987,"Heap":21,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":1,"Wifi":{"AP":1,"SSId":"LRS-WiFi","BSSId":"84:16:F9:57:BD:21","Channel":1,"RSSI":100,"Signal":-31,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
