### ISSUE TITLE
Sensor29 Config

### ISSUE THREAD

**Issue by TheRocktagon** [arendst/Tasmota#10868]
### PROBLEM DESCRIPTION
Try to Config the MCP23017 with inputs and outputs. The Config zb "->sensor29 4,1,0,2" will be ignored if #define USE_MCP230xx_OUTPUT is active. Using Scripts.

Solution: in File xsns_29_mcp230xx.ino about Line 648 :
if(Settings.mcp230xx_config[pin].pinmode >= 5) {
    change to:
if ((paramcount == 2) && (Settings.mcp230xx_config[pin].pinmode >= 5)) {
    
Cause if OUPTPUT active the Data zb "->sensor29 4,1,0,2" are used to switch an then return instead go to the next step to config the port.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic):  ESP32
- [x ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ x] Self-compiled
- [ ] Flashing tools used: VS
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior 
Just activate Script, #define USE_MCP230xx_OUTPUT and try to configure one Port as Input
>BS
->sensor29 0,5,0
->sensor29 1,5,0
->sensor29 2,5,0
->sensor29 3,5,0
->sensor29 5,5,0
->sensor29 6,5,0
->sensor29 9,6,0
->sensor29 10,6,0

->sensor29 4,1,0,2
->sensor29 7,1,0,2
->sensor29 8,1,0,2
->sensor29 11,1,0,2
->sensor29 12,1,0,2
->sensor29 13,1,0,2
->sensor29 14,1,0,2
->sensor29 15,1,0,2

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
PR #11104
