### ISSUE TITLE
Servo Shutter feature request is to set pwm to 0 after movement is finished.

### ISSUE THREAD

**Issue by mikep1998** [arendst/Tasmota#10872]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

With servo controlled shutters the shutter code current leaves the PWM valve for the servo motor at the target position.  This leaves the servo rotation in a locked position. The servo can not be moved by hand until the power to the servo is removed or the PWM is set to 0.

I do not have a relay for the servo power. 

I would like an option to allow the PWM valve set to 0 after the movement is finished to allow the rotation of the blinds servo by hand. 

This also reduces the power consumption of the servo motor.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
NA

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
NA

```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
NA

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
NA

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving to Discussions as it is a feature request and not an issue.
