### ISSUE TITLE
Support WindowCovering cluster auto-config in Zigbee2Tasmota

### ISSUE THREAD

**Issue by chollier** [arendst/Tasmota#10962]
### PROBLEM DESCRIPTION
Zigbee2Tasmota has auto-config / auto-binding for a number of clusters of interest:
https://github.com/arendst/Tasmota/blob/development/tasmota/xdrv_23_zigbee_8_parsers.ino#L658-L663

It is missing support for the `WindowCovering` type (cluster `Cx0102`)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [x] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
N/A

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Hook up an IKEA Fyrtur rollerblinds device to you zigbee2tasmota bridge. The `CurrentPositionLiftPercentage` won't be reported

### EXPECTED BEHAVIOUR
It tries to auto-config this kind of device upon pairing

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
N/A

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by orichienal** [comment]
Hi,
I have a total of 4 of the Fyrtur blinds.
Two of them regularly report their position and battery when opening or closing.
But I can't do that with the other two.
Do I have to configure that extra?

It would be great if someone could give me a hint.

Best wishes
orichienal
