### ISSUE TITLE
Many text/source files in this repo have execution bit set

### ISSUE THREAD

**Issue by eku** [arendst/Tasmota#11075]
### PROBLEM DESCRIPTION

Many text/source files in this git repo have execution bit set.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE

```
git clone ...
find tasmota -type f -executable
or
ls -l 
```

### EXPECTED BEHAVIOUR

Only executable files in this repo have executable status.

### SCREENSHOTS

```
$ find tasmota  -type f -executable
tasmota/WiFiClientSecureLightBearSSL.h
tasmota/WiFiClientSecureLightBearSSL.cpp
tasmota/xsns_52_ibeacon.ino
tasmota/xdrv_10_scripter.ino
tasmota/xdrv_13_display.ino
tasmota/xnrg_15_teleinfo.ino
tasmota/xsns_53_sml.ino
```

### ADDITIONAL CONTEXT

Can be fixed with 

```
git update-index --chmod=-x  <file>
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Thanks, but Github doesn't have files attributes. Those attributes are on your own system.
