### ISSUE TITLE
Wifi problems

### ISSUE THREAD

**Issue by wm1962** [arendst/Tasmota#11080]
### PROBLEM DESCRIPTION
I've updated my SONOFF POW R2 with Tasmotizer to version 8.5.1
The device doesn't connect to Wifi
WIF: Connect failed with AP timeout

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Pow R2
- [x] Tasmota binary firmware version number used: 8.5.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Tasmotizer 1.2
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
00:02:52 CMD: Backlog Template; Module; GPIO 255
00:02:52 RSL: stat/tasmota_681441/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
00:02:52 RSL: stat/tasmota_681441/RESULT = {"Module":{"1":"Sonoff Basic"}}
00:02:52 RSL: stat/tasmota_681441/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}



```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
00:03:26 CMD: Status 0
00:03:26 RSL: stat/tasmota_681441/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_681441","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:03:26 RSL: stat/tasmota_681441/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:03:31","StartupUTC":"","Sleep":50,"CfgHolder":4617,"BootCount":3,"BCResetTime":"1970-01-01T00:00:00","SaveCount":6,"SaveAddress":"F6000"}}
00:03:26 RSL: stat/tasmota_681441/STATUS2 = {"StatusFWR":{"Version":"8.5.1(lite)","BuildDateTime":"2020-10-02T10:10:35","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"353/699"}}
00:03:26 RSL: stat/tasmota_681441/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FRITZ!Box 7490 DG",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
00:03:26 RSL: stat/tasmota_681441/STATUS4 = {"StatusMEM":{"ProgramSize":473,"Free":528,"Heap":34,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F000783","04108001","00000006","010001C0","00000000","00004004","00000000"],"Drivers":"1,2,3,4,9,10,16,20,21,37","Sensors":"3"}}
00:03:26 RSL: stat/tasmota_681441/STATUS5 = {"StatusNET":{"Hostname":"tasmota_681441-5185","IPAddress":"(IP unset)","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"CC:50:E3:68:14:41","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
00:03:26 RSL: stat/tasmota_681441/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_681441","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
00:03:26 RSL: stat/tasmota_681441/STATUS7 = {"StatusTIM":{"UTC":"1970-01-01T00:03:26","Local":"1970-01-01T00:03:26","StartDST":"1970-01-01T00:00:00","EndDST":"1970-01-01T00:00:00","Timezone":"+00:00","Sunrise":"20:13","Sunset":"05:47"}}
00:03:26 RSL: stat/tasmota_681441/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:03:26"}}
00:03:26 RSL: stat/tasmota_681441/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:03:26","Uptime":"0T00:03:31","UptimeSec":211,"Vcc":3.537,"Heap":34,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF"}}



```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
00:04:14 CMD: weblog 4
00:04:14 RSL: stat/tasmota_681441/RESULT = {"WebLog":4}


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
the device doesn't connect to the Wifi, the Wifi-Datas are correct
00:00:00 CFG: Loaded from flash at F7, Count 5
00:00:00 QPC: Count 1
00:00:00 Project tasmota Tasmota Version 8.5.1(lite)-2_7_4_1
00:00:00 WIF: Connecting to AP1 FRITZ!Box 7490 DG in mode 11N as tasmota_681441-5185...
00:00:06 QPC: Reset
00:00:08 WIF: Connect failed with AP timeout
00:00:08 WIF: Connecting to AP1 FRITZ!Box 7490 DG in mode 11N as tasmota_681441-5185...
00:00:15 WIF: Connect failed with AP timeout
00:00:16 WIF: Connecting to AP1 FRITZ!Box 7490 DG in mode 11N as tasmota_681441-5185...
00:00:24 WIF: Connect failed with AP timeout
00:00:24 WIF: Connecting to AP1 FRITZ!Box 7490 DG in mode 11N as tasmota_681441-5185...
00:00:31 WIF: Connect failed with AP timeout
00:00:32 WIF: Connecting to AP1 FRITZ!Box 7490 DG in mode 11N as tasmota_681441-5185...

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
