### ISSUE TITLE
Sonoff Basic - Upgrade to 9.3.0 - bricks device

### ISSUE THREAD

**Issue by huwdavid** [arendst/Tasmota#11086]
### PROBLEM DESCRIPTION
Can upgrade Sonoff Basic as far as 9.2.0 but applying 9.3.0 is met with "Successful" however it does not respond.

Upon upgrade completion the green led remains lit, but not connected via wifi. The push button has no effect either.

If power is removed and reapplied the led goes out, but won't come back on.

Tried various reset / recovery procedures - holding down the button for 40 seconds, power on / off six times etc - but nothing.

Device is totally unresponsive.

### REQUESTED INFORMATION

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
N/A

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
N/A


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
N/A


```

### TO REPRODUCE
Upgrade to 9.3.0 minimal from 9.2.0 and device shows successful but is unresponsive.

### EXPECTED BEHAVIOUR
Device upgrades and operates as normal

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
This has been reproduced at least twice. So I have two bricked basics!

**Comment by ascillato2** [comment]
Your devices seems to have failed the upgrade, but they are not bricked, you can recover them by serial flashing.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you in this case.

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
