### ISSUE TITLE
ESP32 - tasmota32-display - MQTT discovery error

### ISSUE THREAD

**Issue by lluukkiinn** [arendst/Tasmota#11156]
### PROBLEM DESCRIPTION
I have some ESP32 board with LCD display and some thermo sensors.
If I flash firmware tasmota32.bin, MQTT discovery works well and thermo sensors are visible in HomeAssistant.
But if I flash tasmota32-display.bin, it doesn't work, the sensors still show the temperature, but the switch for the display does not appear and there is an error in the mosquitto broker log:

1614522833: Socket error on client esp32_LCD, disconnecting.

When flash firmware back to tasmota32.bin, it works well again...so there is maybe some problem in firmware tasmota32-display.bin

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32 DevKit
- [x] Tasmota binary firmware version number used: 9.3.1
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`: 
```lua
  Configuration output here:

{"NAME":"ESP32-LCD","GPIO": 1,1,1,1,1,1,1,1,1,1312,1,1,1,1,1,1,0,640,608,1,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
rule1 on tele-DS18B20-1#Temperature do DisplayText [s1l1c1]Sklep: %value% C endon on tele-DS18B20-2#Temperature do DisplayText [s1l2c1]Predsin: %value% C endon

```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
