### ISSUE TITLE
The on/off switch only turn on the led, but no the 230V plug

### ISSUE THREAD

**Issue by peatonet** [arendst/Tasmota#11164]
### PROBLEM DESCRIPTION

I tried 3 different templates including the Gosund SP1 v23 that uses the same HW, but I was only able to turn on the red led and there is no 230v on the plug. 
I also tried configuring all the GPIO pins one by one as a relay but is not working for me.

These are the templates:

https://templates.blakadder.com/gosund_SP1.html
https://templates.blakadder.com/blitzwolf_SHP2.html

In the beginning, I was using the v9.2.0 but now I tried also using the new version of the same firmware (Tasmota v9.3.0 Julie):

https://github.com/arendst/Tasmota/releases

### REQUESTED INFORMATION
- [X ] Device used (e.g., Sonoff Basic): Blitzwolf SHP2
- [X ] Tasmota binary firmware version number used: 9.2.0 and 9.3.0 
  - [ X] Pre-compiled
- [X ] Flashing tools used: esptool

### TO REPRODUCE
Flash Tasmota on the device, and try to switch on the light.

### EXPECTED BEHAVIOUR
The tasmota On/Off button should put On/Off the 230V plug and not only the red led.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
