### ISSUE TITLE
I can't see the switch inputs with pcf8574

### ISSUE THREAD

**Issue by turin400** [arendst/Tasmota#11174]
I have designed a pcb with 4 relay output, 4 input and pzem-16 485 support, I have compiled version 9.2 with the option for pcf8574 and I get everything to work except the inputs. I have configured them with the web interface but I don't have any message in the log when I change their status.
Could you help me. 
Thanks.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
