### ISSUE TITLE
ZbScan returns invalid JSON string

### ISSUE THREAD

**Issue by bmc-git** [arendst/Tasmota#11264]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

It seems that zbscan returns an invalid Json string:

{"ZbScan":["11":-43,"12":-44,"13":-78,"14":-33,"15":-21,"16":1,"17":5,"18":-44,"19":-78,"20":-33,"21":-85,"22":-40,"23":-45,"24":-87,"25":-88,"26":-56]}

instead of:

{"ZbScan":[{"11":-43},{"12":-44},{"13":-78},{"14":-33},{"15":-21},{"16":1},{"17":5},{"18":-44},{"19":-78},{"20":-33},{"21":-85},{"22":-40},{"23":-45},{"24":-87},{"25":-88},{"26":-56}]}

Is there missing { and } in the last ResponseAppend_P ?

void EnergyScanResults(void) {
  Response_P(PSTR("{\"" D_JSON_ZIGBEE_SCAN "\":["));
  for (uint32_t i = 0; i < USE_ZIGBEE_CHANNEL_COUNT; i++) {
    int8_t energy = zigbee.energy[i];

    if (i > 0) { ResponseAppend_P(PSTR(",")); }
    ResponseAppend_P(PSTR("\"%d\":%d"), i + USE_ZIGBEE_CHANNEL_MIN, energy);

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Sorry. It is a valid JSON as it is.

**Comment by bmc-git** [comment]
I did try different json parsers and they all give me an error, if I 
change the string as the proposed one if works.

------ Original Meddelelse ------
Fra: "Adrian Scillato" <notifications@github.com>
Til: "arendst/Tasmota" <Tasmota@noreply.github.com>
Cc: "Bo Christiansen" <bmc@bc.dk>; "Author" <author@noreply.github.com>
Sendt: 08-03-2021 18:49:46
Emne: Re: [arendst/Tasmota] zbscan returns invalid jason (#11264)

**Comment by jaymemaurice** [comment]
[ ] is an array... and array of objects would be as OP posted.
I think though the ["s are supposed to be {'s and the result is supposed to
be one object...

**Comment by bmc-git** [comment]
Yes [ ] is an array, but I thought that each entry in the array would be 
[{"xyz":12}, {"twu": 11} ..... ]

I might be wrong, but parsers seems to agree ;o)

------ Original Meddelelse ------
Fra: "jaymemaurice" <notifications@github.com>
Til: "arendst/Tasmota" <Tasmota@noreply.github.com>
Cc: "Bo Christiansen" <bmc@bc.dk>; "Author" <author@noreply.github.com>
Sendt: 08-03-2021 19:47:02
Emne: Re: [arendst/Tasmota] zbscan returns invalid jason (#11264)

**Comment by s-hadinger** [comment]
Indeed. The json is wrong. I will fix that.

**Comment by sfromis** [comment]
Simplet way to make it valid would simply to replace the [] by {} without seeing it as an array

**Comment by bmc-git** [comment]
Well in the loop it would be just as easy to add the { and }, would it 
not be 'correct' that it would be an array of channels ?


------ Original Meddelelse ------
Fra: "sfromis" ***@***.***>
Til: "arendst/Tasmota" ***@***.***>
Cc: "Bo Christiansen" ***@***.***>; "Author" ***@***.***>
Sendt: 09-03-2021 22:28:54
Emne: Re: [arendst/Tasmota] ZbScan returns invalid JSON string (#11264)

**Comment by sfromis** [comment]
No clear "right" or "wrong" there. My view is that the "names" are already index numbers, making it slightly confusing to wrap it in an array with another set of index numbers.

**Comment by s-hadinger** [comment]
My bad, I will just replace [] with {}
