### ISSUE TITLE
Subtract var values to another var

### ISSUE THREAD

**Issue by guysnraw** [arendst/Tasmota#11265]
Hi, 
Rule3 on power1#state=1 do event chktime=%time% endon on event#chktime do var1=%value% endon on power1#state=0 do event chktime2=%time% endon on event#chktime2 do backlog var2=%value%; event uptime=%var2% - %var1%; endon on event#uptime do var3=%value% endon
23:34:34 RSL: stat/tasmota_D401C0/RESULT = {"POWER1":"ON"}
23:34:34 RSL: stat/tasmota_D401C0/POWER1 = ON
23:34:34 RUL: POWER1#STATE=1 performs "backlog event chktime=1414"
23:34:34 RSL: stat/tasmota_D401C0/RESULT = {"Event":"Done"}
23:34:34 RUL: EVENT#CHKTIME performs "var1=1414"
23:34:34 RSL: stat/tasmota_D401C0/RESULT = {"Var1":"=1414"}
23:34:42 CMD: Power1 0
23:34:42 RSL: stat/tasmota_D401C0/RESULT = {"POWER1":"OFF"}
23:34:42 RSL: stat/tasmota_D401C0/POWER1 = OFF
23:34:42 RUL: POWER1#STATE=0 performs "backlog event chktime2=1414"
23:34:43 RSL: stat/tasmota_D401C0/RESULT = {"Event":"Done"}
23:34:43 RUL: EVENT#CHKTIME2 performs "backlog var2=1414; event uptime==1394 - =1414;"
23:34:43 RSL: stat/tasmota_D401C0/RESULT = {"Var2":"=1414"}
23:34:43 RSL: stat/tasmota_D401C0/RESULT = {"Event":"Done"}
23:34:43 RUL: EVENT#UPTIME performs "var3==1394 - =1414"
23:34:43 RSL: stat/tasmota_D401C0/RESULT = {"Var3":"==1394 - =1414"}

Why couldn't i subtract two var to get uptime of power1?

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
