### ISSUE TITLE
DS18x20 doesn't work any more

### ISSUE THREAD

**Issue by manoode** [arendst/Tasmota#11270]
I have a Sonoff Basic R2 V1.3 with a DS18B20 on GPIO01 (TX).
After upgrading from 9.3.0 -> 9.3.1 the Sensor doesn't appear any more. I tried many reboots, but nothing helped.
Going back to 9.1.0 solved it. Immediately the temerature is shown again.

Best regards Manuel

**Comment by ascillato** [comment]
Duplicated issue. Please do a quick search in recent issues. Thanks

**Comment by arendst** [comment]
Found a solution.

I will re-compile the release binaries and update both release and ota.tasmota.com once finished.
