### ISSUE TITLE
undefined reference to `Script_Check_HTML_Setvars()

### ISSUE THREAD

**Issue by DarkShadowNight** [arendst/Tasmota#11344]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
undefined reference to `Script_Check_HTML_Setvars() when compiling with GitPod.
Copied user_config_override_sample.h to user_config_override_sample.h.
Added:
```
#ifndef USE_SCRIPT_WEB_DISPLAY
#define USE_SCRIPT_WEB_DISPLAY
#endif
```
Compiled: platformio run -e tasmota

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Not relevant
- [x] Tasmota binary firmware version number used: Latest
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: Not relevant
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
Not relevant


```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
Not relevant

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
Not relevant

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
Not relevant

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
See problem description

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Compile without errors

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
No

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
What's the connection between xdrv_01_webserver.ino and xdrv_01_scripter.ino?
Linker?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
USE_SCRIPT_WEB_DISPLAY
is a special option of script to display web contents
it MUST be used with USE_SCRIPT.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
