### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by hardlog** [arendst/Tasmota#11341]
Hi,

Hi,
i can't get my epaper display to work.

I have a waeshare 2.9 V2.1 and bridge it in 3-wire SPI mode. On the ESP8266 (wemos D1) I have GND, 3.3V, CS on D8 (GPIO15), DIN (MOSI) on D7 (GPIO13) and CLK on D5 (GPIO14) as described above. Precompiled Tasmota-display.bin (9.3.1).
Configured:

![image](https://user-images.githubusercontent.com/16474085/111063121-38acf600-84ad-11eb-9c18-cf0f64542713.png)

Displaymodel 5,  Displaymode 0

Nothing comes of "displaytext blahblah".

What am I doing wrong.

Greetings Florian

_Originally posted by @hardlog in https://github.com/arendst/Tasmota/issues/4785#issuecomment-798873510_

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
