### ISSUE TITLE
MCP23017 issue

### ISSUE THREAD

**Issue by ahmaddxb** [arendst/Tasmota#11357]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

When I toggle the buttons on the web UI most of the time if I turn on the another button then off again it will turn all buttons to off and stop responding to further buttons pressed until I reboot.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): __d1mini___
- [x] Tasmota binary firmware version number used: __9.3.1___
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: _Tasmotizer____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

Backlog Template; Module; GPIO 25
12:07:56.744 SRC: WebConsole from 192.168.1.200
12:07:56.747 CMD: Group 0, Index 1, Command "BACKLOG", Data "Template; Module; GPIO 25"
12:07:56.766 SRC: Backlog
12:07:56.769 CMD: Group 0, Index 1, Command "TEMPLATE", Data ""
12:07:56.776 MQT: stat/sonoff/irrigation_16ch/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,640,608,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
12:07:56.987 SRC: Backlog
12:07:56.990 CMD: Group 0, Index 1, Command "MODULE", Data ""
12:07:56.996 MQT: stat/sonoff/irrigation_16ch/RESULT = {"Module":{"18":"Generic"}}
12:07:57.239 SRC: Backlog
12:07:57.242 CMD: Group 0, Index 1, Command "GPIO", Data "25"
12:07:57.250 MQT: stat/sonoff/irrigation_16ch/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"640":"I2C SDA"},"GPIO5":{"608":"I2C SCL"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

12:08:47.280 MQT: stat/sonoff/irrigation_16ch/STATUS = {"Status":{"Module":18,"DeviceName":"Irrigation 16CH","FriendlyName":["Tasmota","Tasmota2","Tasmota3","Tasmota4","Tasmota5","Tasmota6","Tasmota7","Tasmota8"],"Topic":"sonoff/irrigation_16ch","ButtonTopic":"0","Power":32768,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
12:08:47.287 MQT: stat/sonoff/irrigation_16ch/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:06:15","StartupUTC":"2021-03-16T08:02:32","Sleep":50,"CfgHolder":4617,"BootCount":27,"BCResetTime":"2021-01-24T17:28:33","SaveCount":292,"SaveAddress":"F8000"}}
12:08:47.293 MQT: stat/sonoff/irrigation_16ch/STATUS2 = {"StatusFWR":{"Version":"9.3.1(sensors)","BuildDateTime":"2021-03-16T06:33:33","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"404/699"}}
12:08:47.297 MQT: stat/sonoff/irrigation_16ch/STATUS3 = {"StatusLOG":{"SerialLog":1,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ASUS",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000AA009","2805C8000100060000005A0A000000000000","000082C8","00006000","00000000"]}}
12:08:47.309 MQT: stat/sonoff/irrigation_16ch/STATUS4 = {"StatusMEM":{"ProgramSize":651,"Free":352,"Heap":18,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDA8787","0415A005","B7FFBFCF","01DA9BF5","64367CC7","00084052","20000000","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,14,16,17,20,21,24,29,34","Sensors":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,26,28,29,31,34,37,39,40,42,43,51,52,55,56,58,59,62,64,66,67,74"}}
12:08:47.315 MQT: stat/sonoff/irrigation_16ch/STATUS5 = {"StatusNET":{"Hostname":"sonoff/irrigation_16ch-4015","IPAddress":"192.168.1.102","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.104","Mac":"2C:F4:32:14:6F:AF","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
12:08:47.320 MQT: stat/sonoff/irrigation_16ch/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.235","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_146FAF","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
12:08:47.329 MQT: stat/sonoff/irrigation_16ch/STATUS7 = {"StatusTIM":{"UTC":"2021-03-16T08:08:47","Local":"2021-03-16T12:08:47","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+04:00","Sunrise":"10:00","Sunset":"21:56"}}
12:08:47.344 MQT: stat/sonoff/irrigation_16ch/STATUS10 = {"StatusSNS":{"Time":"2021-03-16T12:08:47","BME280":{"Temperature":33.9,"Humidity":37.8,"DewPoint":17.5,"Pressure":1012.5},"MCP230XX":{"D0":1,"D1":1,"D2":1,"D3":1,"D4":1,"D5":1,"D6":1,"D7":1,"D8":1,"D9":1,"D10":1,"D11":1,"D12":1,"D13":1,"D14":1,"D15":0,"MCP230_OUT":{"OUT_D0":"OFF","OUT_D1":"OFF","OUT_D2":"OFF","OUT_D3":"OFF","OUT_D4":"OFF","OUT_D5":"OFF","OUT_D6":"OFF","OUT_D7":"OFF","OUT_D8":"OFF","OUT_D9":"OFF","OUT_D10":"OFF","OUT_D11":"OFF","OUT_D12":"OFF","OUT_D13":"OFF","OUT_D14":"OFF","OUT_D15":"ON","END":1}},"PressureUnit":"hPa","TempUnit":"C"}}
12:08:47.355 MQT: stat/sonoff/irrigation_16ch/STATUS11 = {"StatusSTS":{"Time":"2021-03-16T12:08:47","Uptime":"0T00:06:15","UptimeSec":375,"Heap":18,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","POWER9":"OFF","POWER10":"OFF","POWER11":"OFF","POWER12":"OFF","POWER13":"OFF","POWER14":"OFF","POWER15":"OFF","POWER16":"ON","Wifi":{"AP":1,"SSId":"ASUS","BSSId":"B4:FB:E4:71:42:B2","Channel":11,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

configure module

D2 GPIO4 - I2C SDA
D1 GPIO5 - I2C SCL

console

sensor29 0,6,1 
sensor29 1,6,1
sensor29 2,6,1
...
to sensor29 14,6,1

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/43728586/111276985-629f1d80-8651-11eb-83a5-94e637a189fe.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

I'm not 100% sure about this long term, but if i leave one button toggled on and restart it works as expected.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please try latest development version. Changes are made in MCP230xx driver

**Comment by theOzzieRat** [comment]
I am not sure if the change I made today will affect this, but it may. Interested to see the feedback.

**Comment by ahmaddxb** [comment]
Compiled and tested 9.3.1.1. Now is seems the relays choose to be either on or off randomly after a reboot. If i turn them all off the wont be the way i left them after i reboot the device.

**Comment by theOzzieRat** [comment]
I have done a bit more investigation and there appears to be a problem when so0 is set to 1. When so0 is set to 0 after a reboot the output values are all set as per the values specified by the sensor29 x,[5|6],y commands, but when  so0 is 1 the output values aren't random but are not what is expected (ie. not the values that were present at reboot OR the values specified in the sensor29 commands).

**Comment by theOzzieRat** [comment]
There is a definite bug when setoption0 is 1. I am currently working on a fix.

**Comment by theOzzieRat** [comment]
@ahmaddxb when you get a chance please test the latest development version of 9.3.1.2 and let me know if it fixes your issues or not.

**Comment by ahmaddxb** [comment]
The state is remembers after reboot thanks, I will let you know if the initial issue occurs still after some long term testing.

**Comment by ahmaddxb** [comment]
I dont think this is fixed initial issue is still there and all so sometime if i cut the power and plug it back in it will want to start up to the state below. Strange

![image](https://user-images.githubusercontent.com/43728586/112151350-8edf0f00-8bfa-11eb-8bcc-e8c1146da03a.png)

**Comment by theOzzieRat** [comment]
I am unable to replicate your problem. The only thing that I can find that now doesn't work is enabling INTERLOCK, the code for that looks broken to me and turning it on I get unexpected/weird results.
If you want me to investigate further I will need your full configuration, not just the sensor29 commands.

**Comment by ahmaddxb** [comment]
09:42:46.478 MQT: stat/sonoff/irrigation_16ch/RESULT = {"Interlock":"OFF","Groups":"1,2,3,4,5,6,7,8"}

**Comment by ahmaddxb** [comment]
how do I send my full config

**Comment by ahmaddxb** [comment]
[Config_sonoff_irrigation_16ch_4015_9.3.1.2.zip](https://github.com/arendst/Tasmota/files/6194673/Config_sonoff_irrigation_16ch_4015_9.3.1.2.zip)

**Comment by theOzzieRat** [comment]
I suspect that config file contains your wifi credentials. Are you on discord? If so try and message me privately on there and we can try and sort things out. My username is theRat#2205.

**Comment by theOzzieRat** [comment]
I uploaded your config onto a d1-mini with an MCP23007 attached and cannot get it to misbehave (multiple restarts and random power cycles). Are you certain that something external (ie. home assistant) isn't changing the state? Without further diagnostics from your end I am going to have to assume it is something wrong in your environment and not the MCP driver.

**Comment by ahmaddxb** [comment]
I will try do more testing with mqtt disabled and rule that out but I don't think that is the case. 

I think it may be a power supply issue running the mcp23007 and the 5v relays from the d1 mini board, the USB charger maybe can't supply enough amps. Going to try power the 16ch relay from a separate 5v supply and see.

If you have handy the compile firmware you used for testing I could try load that onto my esp as another thing to test.

**Comment by ahmaddxb** [comment]
can you send be a picture of the MCP23007 board you are using

**Comment by ahmaddxb** [comment]
also can you send me how you wired it to the esp

**Comment by rapi3** [comment]
Do you have MCP RST pin to VCC ? if not then strange problems appear.

**Comment by theOzzieRat** [comment]
Both the Tasmota doc's and the Microchip datasheets tell you that RESET must be pulled to VCC for the device to operate. The RESET pin and the address pins (A0,A1,A2) CAN NOT BE LEFT FLOATING!

**Comment by rapi3** [comment]
There is a problem if Pulsetime it is activated for relays 1-8; it will interfere with relays 9-16
and on console for relays 9-16 pulsetime is unavailable
15:38:41.212 CMD: pulsetime9
15:38:41.217 MQT: Wemos/stat/W11/RESULT = {"Command":"Error"}

It easy to reproduce:
Activate PulseTime for one or more relays 1-8 and you can see his effect on correspondent relay 9-16.

**Comment by Jason2866** [comment]
As designed.

**Comment by rapi3** [comment]
Good to know now because it is not mentioned anywhere on MCP230xx page.
https://tasmota.github.io/docs/MCP230xx/

**Comment by Jason2866** [comment]
It is a general solution for pulsetime, not only for MCP230XX

**Comment by rapi3** [comment]
Then it will be great if somebody can update the info here:
https://tasmota.github.io/docs/Commands/#pulsetime

**Comment by meingraham** [comment]
Tasmota Docs are open source as well. All users are able to contribute edits and new content. Click on the pencil icon at the top right of the article, make the edits, and submit the docs PR.

Thanks.

**Comment by rapi3** [comment]
Thank you for possibility to contribute. Note added.

**Comment by Jason2866** [comment]
The corresponding commit https://github.com/arendst/Tasmota/commit/a9630b9d053036960ac03d2de74c97fb4f7a400d
