### ISSUE TITLE
Got an error when compiling Tasmota to support TLS

### ISSUE THREAD

**Issue by smilexth** [arendst/Tasmota#11365]
### PROBLEM DESCRIPTION

According to https://tasmota.github.io/docs/TLS/,  When i try to add "lib_extra_dirs = lib/lib_ssl" into standard tasmota environment to enable tts, i got an error when i compiling about " IRremoteESP8266.h: No such file or directory" could you please give me some advise ?

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): _____
- [X] Tasmota binary firmware version number used: 9.3.1
  - [] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: platformio via visual studio code

### SCREENSHOTS
**terminal compiler debug message**

![CropperCapture 4](https://user-images.githubusercontent.com/154602/111440547-0dd6d200-8739-11eb-9c80-d999dd719815.png)

**platformio_tasmota_env.ini**

![CropperCapture 3](https://user-images.githubusercontent.com/154602/111440631-1deeb180-8739-11eb-9f5f-70155f8a88cf.png)

**Comment by Jason2866** [comment]
Do NOT change `[env:Tasmota]` all libs are already enabled.
With your change only lib `lib_ssl` is active, all others are disabled!

**Comment by smilexth** [comment]
> Do NOT change `[env:Tasmota]` all libs are already enabled.
> With your change only lib `lib_ssl` is active, all others are disabled!

Thanks sir
