### ISSUE TITLE
[Suggestion] Set setoption41 105 as default when wemo/hue emulation is active

### ISSUE THREAD

**Issue by raphamotta** [arendst/Tasmota#11367]
Hello,

I have several issues with Alexa not working sometimes (related with #10430 ) and 2 actions solved my problem after several tests:
 - Allow IGMP snooping in my LAN
 - Set option "setoption41 105" for gratuitous ARP every 5 minutes

Not every router has the IGPM option, and I had this problem on my parents house too. Then, "setoption41 105" fixed the issue.

I suggest to put option "setoption41 105" as default when wemo/hue emulation is active to prevent this problem. Any problem to to it?

Thanks

**Comment by raphamotta** [comment]
Where can I suggest it?

**Comment by raphamotta** [comment]
> In discussions. But this is not a solution for a Multicast problem.
> Setoption 41 is a workaround for routers which has not correctly implemented ARP treatment.
> This issue is a general problem and affects **all** Tasmota functions.

Well, if it's a workaround to some routers, why not to keep it by default?

**Comment by jaymemaurice** [comment]
Please don't. Don't encourage fixing some broken networking devices by shipping default broken network protocols. 
I personally don't want ARP broadcasts from all of my Tasmota devices waking up all the devices on my network because someone else's junk router/switch can't handle IGMP or keep it's ARP state.

**Comment by Jason2866** [comment]
Thats why Setoption41 is off by default. This will not be changed.

**Comment by suzsuzuki** [comment]
> Thats why Setoption41 is off by default. This will not be changed.

Well... the default value of setoption41 is 60 for a while. Never say never..

**Comment by rockbruno** [comment]
I found this thread after seeing tasmota spamming my networking for no reason and trying to find out why. Am also surprised they made this a default... In any case, thankfully you can disable it with `SetOption41 0`

**Comment by s-hadinger** [comment]
Sending one ARP packet every 105 seconds hardly qualifies for "spamming". Sending gratuitous ARP seemed to solve some multicast problems.
