### ISSUE TITLE
ESP01 not waking up from deep sleep

### ISSUE THREAD

**Issue by fpietersen** [arendst/Tasmota#11391]
### PROBLEM DESCRIPTION
I am using a ESP01 module and modified it so that the GPIO16 pin is connected to the rst pin. This is explained in many youtube video's and blogs.

When is set the module to deepsleep it will never wake up and I get an error after the deepsleeptime command as below:

`16:46:44 CMD: deepsleeptime 30 16:46:44 MQT: stat/sensor-02/RESULT = {"DeepSleepTime":30} 16:46:44 MQT: tele/sensor-02/STATE = {"Time":"2021-03-19T16:46:44","Uptime":"0T00:00:29","UptimeSec":29,"Heap":26,"SleepMode":"Normal","Sleep":250,"LoadAvg":15,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXXX","BSSId":"84:9C:A6:BD:61:9A","Channel":9,"RSSI":44,"Signal":-78,"LinkCount":1,"Downtime":"0T00:00:03"}} 16:46:44 MQT: tele/sensor-02/SENSOR = {"Time":"2021-03-19T16:46:44","AM2301":{"Temperature":23.0,"Humidity":45.7,"DewPoint":10.6},"TempUnit":"C"} 16:46:44 DSL: Reset wrong settings wakeup: 0, slip 10000 16:46:44 MQT: stat/sensor-02/RESULT = {"DeepSleep":{"Time":"2021-03-19T16:47:00","Epoch":1616168820}}
`
Sometimes I also get the error: 16:46:44 DSL: Reset wrong settings wakeup: 0, slip 0 (instead of the number 10000)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ X] Device used (e.g., Sonoff Basic): ESP01 module (with PUYA chip)
- [ x] Tasmota binary firmware version number used: 9.3.1
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ x] Flashing tools used: update via module from 9.3.0 (originaly flashed with tasmota flasher)
- [ x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
17:16:59.161 MQT: stat/sensor-02/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
17:16:59.419 MQT: stat/sensor-02/RESULT = {"Module":{"1":"Sonoff Basic"}}
17:16:59.682 MQT: stat/sensor-02/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"1216":"AM2301"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
NA

```
- [ x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
17:17:58.840 MQT: stat/sensor-02/STATUS = {"Status":{"Module":1,"DeviceName":"sensor02","FriendlyName":["sensor02"],"Topic":"sensor-02","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
17:17:58.870 MQT: stat/sensor-02/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T00:03:13","StartupUTC":"2021-03-19T16:14:45","Sleep":250,"CfgHolder":4617,"BootCount":22,"BCResetTime":"2021-02-16T20:17:07","SaveCount":74,"SaveAddress":"F6000"}}
17:17:58.904 MQT: stat/sensor-02/STATUS2 = {"StatusFWR":{"Version":"9.3.1(tasmota)","BuildDateTime":"2021-03-09T16:12:28","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"402/699"}}
17:17:58.925 MQT: stat/sensor-02/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["hotspotc8",""],"TelePeriod":120,"Resolution":"558180C0","SetOption":["000A8009","2805C8000000060000005A0A000000000000","00000680","00006000","00000000"]}}
17:17:58.956 MQT: stat/sensor-02/STATUS4 = {"StatusMEM":{"ProgramSize":593,"Free":408,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
17:17:58.989 MQT: stat/sensor-02/STATUS5 = {"StatusNET":{"Hostname":"sensor-02-3666","IPAddress":"192.168.2.12","Gateway":"192.168.2.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.254","Mac":"BC:DD:C2:23:EE:52","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:17:59.001 MQT: stat/sensor-02/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.57","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_23EE52","MqttUser":"mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
17:17:59.022 MQT: stat/sensor-02/STATUS7 = {"StatusTIM":{"UTC":"2021-03-19T16:17:59","Local":"2021-03-19T17:17:59","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"06:54","Sunset":"19:00"}}
17:17:59.044 MQT: stat/sensor-02/STATUS10 = {"StatusSNS":{"Time":"2021-03-19T17:17:59","AM2301":{"Temperature":23.8,"Humidity":44.9,"DewPoint":11.1},"TempUnit":"C"}}
17:17:59.057 MQT: stat/sensor-02/STATUS11 = {"StatusSTS":{"Time":"2021-03-19T17:17:59","Uptime":"0T00:03:14","UptimeSec":194,"Heap":25,"SleepMode":"Normal","Sleep":250,"LoadAvg":3,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"hotspotc8","BSSId":"84:9C:A6:BD:61:9A","Channel":9,"RSSI":34,"Signal":-83,"LinkCount":1,"Downtime":"0T00:00:03"}}}


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
17:18:43.750 CMD: weblog 4
17:18:43.757 MQT: stat/sensor-02/RESULT = {"WebLog":4}
17:18:43.057 CFG: Saved to flash at F5, Count 75, Bytes 4096
17:18:53.385 CMD: deepsleeptime 30
17:18:53.387 SRC: WebConsole from 192.168.2.14
17:18:53.390 CMD: Group 0, Index 1, Command "DEEPSLEEPTIME", Data "30"
17:18:53.397 MQT: stat/sensor-02/RESULT = {"DeepSleepTime":30}
17:18:53.707 CFG: Saved to flash at F4, Count 76, Bytes 4096
17:18:53.715 DSL: Reset wrong settings wakeup: 0, slip 10000
17:18:53.723 MQT: stat/sensor-02/RESULT = {"DeepSleep":{"Time":"2021-03-19T17:19:00","Epoch":1616170740}}


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
After the deepsleeptime command with a value other that 0 the module never wakes up.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Should wake up after the specified number of seconds

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
NA

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
NA

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
