### ISSUE TITLE
sml cmdtelegram in variable?

### ISSUE THREAD

**Issue by nikito7** [arendst/Tasmota#11438]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Is this possible?
Can be done?

```js
>D

raw=r010400010001,r0104006C0007,r010400730007,r0104007B0005,r010400260003,r010400160006

>BS

=>sensor53 r

>S

if something
then
raw=r010400010001
=>sensor53 r
endif

if something2
then
raw=r0104006C0007,r010400730007,r0104007B0005,r010400260003,r010400160006
=>sensor53 r
endif

>M 1

+1,14,m,1,9600,EB1,5,12,%raw%

```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ x] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
this might be possible but not as you typed. (never tested though)
give it a try

raw must be a string and strings can only have 48 chars per default.
so you must expand the maximum allowed string size by e.g.
#define SCRIPT_MAXSSIZE 100
#define SML_REPLACE_VARS

then
\>D 100
raw="r010400010001,r0104006C0007,r010400730007,r0104007B0005,r010400260003,r010400160006"

\>S

if something
then
raw="r010400010001"
=>sensor53 r
endif

if something2
then
raw="r0104006C0007,r010400730007,r0104007B0005,r010400260003,r010400160006"
=>sensor53 r
endif

\>M 1
+1,14,m,1,9600,EB1,5,12,%raw%
