### ISSUE TITLE
Rules not firing

### ISSUE THREAD

**Issue by dkotte** [arendst/Tasmota#11554]
Build the current project with Tasmota 9.3.1.
a simple rule should fire if IR code is received.
at the console i see the IR-Code and i am able to use the command.
But the rule dont work:
12:04:12.809 CMD: rule2
12:04:12.811 SRC: WebConsole from 192.168.11.254
12:04:12.814 CMD: Group 0, Index 2, Command "RULE", Data ""
12:04:12.819 RSL: stat/tasmota_0C7503/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":48,"Free":463,"Rules":"on IrReceived#Data=0x00FFF807 DO power off endon"}
12:04:18.535 IRR: RawLen 68, Overflow 0, Bits 32, Value 0x00FFF807, Decode 3
12:04:18.540 RSL: tele/tasmota_0C7503/RESULT = {"Time":"2021-04-02T12:04:18","IrReceived":{"Protocol":"NEC","Bits":32,"Data":"0x00FFF807"}}
12:04:18.586 IRR: RawLen 4, Overflow 0, Bits 0, Value 0xFFFFFFFFFFFFFFFF, Decode 3
12:04:34.221 CMD: power off
12:04:34.224 SRC: WebConsole from 192.168.11.254
12:04:34.227 CMD: Group 0, Index 1, Command "POWER", Data "off"
12:04:34.235 RSL: stat/tasmota_0C7503/RESULT = {"POWER":"OFF"}

**Comment by ascillato** [comment]
Your rule is turned off!!!!

Rule2":"OFF"

Enable it by command `rule2 1`

Please, if you continue having problems, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
