### ISSUE TITLE
BL0937 Power Reading Accuracy

### ISSUE THREAD

**Issue by Lovett1991** [arendst/Tasmota#11570]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

In [xnrg_01_hlw8012.ino](https://github.com/arendst/Tasmota/blob/development/tasmota/xnrg_01_hlw8012.ino) the power reading only takes the most recent pulse length into account as seen on [line 88](https://github.com/arendst/Tasmota/blob/d7018a9a425228c3f86d2b6da185e8b0d331f490/tasmota/xnrg_01_hlw8012.ino#L88) however the collection of Voltage/Current is an averaged value over N samples as seen [here](https://github.com/arendst/Tasmota/blob/d7018a9a425228c3f86d2b6da185e8b0d331f490/tasmota/xnrg_01_hlw8012.ino#L102).

Would it be possible/permissible to instead sum the pulse lengths in each CF1 interrupt, and average this in the 200ms collection loop? `Hlw.cf_pulse_length` is already a `uint32_t` , so it shouldn't require any more memory (should store more than an hour at 100% pulse length), and the number of periods is already counted with `Hlw.energy_period_counter`.

This may seem a bit overkill but I'm measuring the power consumption of some servers and they're quite jittery loads. Only getting a single reading every 200ms is more coarse than the average of many readings every 38us, I'm happy to make the change (I've not contributed before) but wanted to know if this would be permitted?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Gosund UP111 - BL0937 Sensor
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [X] Flashing tools used: Tuya-Convert
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
19:25:53 CMD: Backlog Template; Module; GPIO 255
19:25:53 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"NAME":"Gosund UP111","GPIO":[0,320,0,32,2720,2656,0,0,2624,576,224,0,0,0],"FLAG":0,"BASE":18}
19:25:53 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"Module":{"0":"Gosund UP111"}}
19:25:53 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"320":"Led_i1"},"GPIO2":{"0":"None"},"GPIO3":{"32":"Button1"},"GPIO4":{"2720":"BL0937 CF"},"GPIO5":{"2656":"HLWBL CF1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"2624":"HLWBL SEL_i"},"GPIO13":{"576":"LedLink_i"},"GPIO14":{"224":"Relay1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}}
```
- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
19:24:50 CMD: Backlog Rule1; Rule2; Rule3
19:24:50 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":33,"Free":478,"Rules":"ON ENERGY#Power Do status 8 ENDON"}
19:24:50 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":59,"Free":452,"Rules":"ON ENERGY#state DO publish energy/ring2/power %value% ENDON"}
19:24:50 MQT: home/servers/nx/tasmota_E582DF/stat/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
```
- [X] Provide the output of this command: `Status 0`:
```lua
 19:26:53 CMD: status 0
19:26:53 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_E582DF","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:26:53 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"2T05:51:00","StartupUTC":"2021-04-01T12:35:53","Sleep":50,"CfgHolder":4617,"BootCount":20,"BCResetTime":"2021-03-23T13:08:56","SaveCount":124,"SaveAddress":"F8000"}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS2 = {"StatusFWR":{"Version":"9.2.0(lite)","BuildDateTime":"2020-12-17T10:06:08","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"418/699"}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Shenzhou",""],"TelePeriod":300,"Resolution":"558180F0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS4 = {"StatusMEM":{"ProgramSize":476,"Free":524,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F000783","04108001","00000006","010001C0","00000000","00004004","00000000"],"Drivers":"1,2,3,4,9,10,16,20,21,37","Sensors":"3"}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS5 = {"StatusNET":{"Hostname":"tasmota_E582DF-0735","IPAddress":"192.168.1.173","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"40:F5:20:E5:82:DF","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS6 = {"StatusMQT":{"MqttHost":"mosquitto-alpha.local","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_E582DF","MqttUser":"openhab","MqttCount":21,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS7 = {"StatusTIM":{"UTC":"2021-04-03T18:26:54","Local":"2021-04-03T19:26:54","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"06:23","Sunset":"19:23"}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS10 = {"StatusSNS":{"Time":"2021-04-03T19:26:54.165","ENERGY":{"TotalStartTime":"2021-03-23T13:08:56","Total":0.043,"Yesterday":0.019,"Today":0.015,"Power":1,"ApparentPower":2,"ReactivePower":2,"Factor":0.25,"Voltage":239,"Current":0.010}}}
19:26:54 MQT: home/servers/nx/tasmota_E582DF/stat/STATUS11 = {"StatusSTS":{"Time":"2021-04-03T19:26:54.194","Uptime":"2T05:51:01","UptimeSec":193861,"Vcc":3.438,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":21,"POWER":"ON","Wifi":{"AP":1,"SSId":"Shenzhou","BSSId":"00:E1:B0:11:42:09","Channel":1,"RSSI":56,"Signal":-72,"LinkCount":2,"Downtime":"0T00:00:05"}}}
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving to discussions as this is a feature request and not an issue with Tasmota.
