### ISSUE TITLE
Dimmer stop command is not interacting properly during once off fade

### ISSUE THREAD

**Issue by Obi2000** [arendst/Tasmota#11587]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
When performing a brightness fade using the one time `Fade2 1` setting, calling `Dimmer !` fails to stop the fade. It continues to the end. Also an incorrect brightness value is shown in the console and UI afterwards.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Lohas ZN033 Bulb
- [x] Tasmota binary firmware version number used: 9.3.1.2
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
02:51:44.925 RSL: RESULT = {"NAME":"LohasRGBWW","GPIO":[0,0,0,0,417,416,0,0,420,418,419,0,0,0],"FLAG":0,"BASE":18}
02:51:45.178 RSL: RESULT = {"Module":{"0":"LohasRGBWW"}}
02:51:45.388 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"417":"PWM2"},"GPIO5":{"416":"PWM1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"420":"PWM5"},"GPIO13":{"418":"PWM3"},"GPIO14":{"419":"PWM4"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
02:52:49.021 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Office Reading","FriendlyName":["Office Reading"],"Topic":"tasmota","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
02:52:49.029 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:03:44","StartupUTC":"2021-04-05T00:49:05","Sleep":50,"CfgHolder":4617,"BootCount":104,"BCResetTime":"2020-07-04T18:45:57","SaveCount":1882,"SaveAddress":"F6000"}}
02:52:49.035 RSL: STATUS2 = {"StatusFWR":{"Version":"9.3.1.2(tasmota)","BuildDateTime":"2021-04-04T20:53:52","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"416/699"}}
02:52:49.041 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["River","RiverTest"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008001","2805C8000100060000005A0A000000000000","00000080","80006000","80000000"]}}
02:52:49.050 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
02:52:49.055 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-1580","IPAddress":"10.0.0.66","Gateway":"10.0.0.1","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"2C:F5:32:B1:C1:22","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
02:52:49.061 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-04-05T01:52:49","Local":"2021-04-05T02:52:49","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"06:18","Sunset":"19:26"}}
02:52:49.065 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-04-05T02:52:49"}}
02:52:49.072 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-04-05T02:52:49","Uptime":"0T01:03:44","UptimeSec":3824,"Heap":27,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":15,"Color":"0000002600","HSBColor":"0,0,0","White":15,"CT":153,"Channel":[0,0,0,15,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"River","BSSId":"FC:EC:D4:B3:C2:E3","Channel":9,"RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Set:
`Fade 0`
`Dimmer 1`

Then to initiate the brightness increase from 1 to 100% run:
`Backlog Fade2 1; Speed2 40;Dimmer >`

Midway through attempt to stop it by running the command:
`Dimmer !`

The brightness will continue to increase to 100%. Afterwards the Status and Dimmer commands will not show the brightness at %100. It will be listed as the value you intended to stop at eg. {"Dimmer":24}

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
The brightness should stop changing at around the time you issue the `Dimmer !` command.
The same as it would if you were using the standard `Fade 1` and `Speed 40` settings.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I normally keep fade off because I want instant changes to my lighting.

I would like to use buttons to smoothly control the brightness of my smart bulbs. Which the Dimmer <> and ! commands allow.
And using the one time Fade2 and Speed2 commands should allow for me to only use fading during this. Without having to toggle the regular Fade setting on and off all the time, and using writes to flash.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by joelinux60** [comment]
Would like to add that similar symptom happens when using fade 1 and speed 20. Wanting to use DIMMER ! to stop a Dim on it's way up to 100 doesn't stop but continues to 100. Another symptom is dimming up started with DIMMER > gets stopped with DIMMER ! but dimmer value doesn't stay but dims down to some lower value.
Doing any dim down by using DIMMER < and stopping these with DIMMER ! appear to work fine.
