### ISSUE TITLE
9.1.0 -> 9.3.0 not working

### ISSUE THREAD

**Issue by daniel-lo** [arendst/Tasmota#11640]
After flashing tasmota.bin 9.1.0 to my devices I cannot flash 9.3.0 tasmota-minimal.bin.

Is this by design? I'd like to update.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
