### ISSUE TITLE
Missing battery for the Tuya Radiator Actuator Thermostat

### ISSUE THREAD

**Issue by pickonedev** [arendst/Tasmota#11689]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I have a "Tuya ZigBee Radiator Actuator Thermostat" connected to my tasmotized Sonoff ZigBee Bridge (see image).
The device has been successfully paired, it is working flowless, I have temperature switch, actual temperature sensor, but the battery sensor it is not shown.

In the past, I used this device on Tuya ZigBee Hub and all the features were working good.
The battery percentage have only two values "5%" and "100%", no other value. If the battery is full/ok the sensor will report a constant 100% battery, when the battery is low, the device will change the value of the battery sensor from 100% to 5% and back by many times per second, seeing a "blinking" like (5, 100, 5, 100, 5, 100...).

After I started to use this device with tasmotized zigbee and seeing that there is no battery sensor revealted, I remebered about that "blinking" values 5-100 and I used some low batteries in order to see what values are trasmitted as fast as the changing battery value. I found that ['EF00/016E'] is the variable which changes the value between 0 and 1, which made me think that this is the variable, but I can't use this to request the battery level, or I don't know. I just see that the "EF00/016E" is blinking between 0 and 1 and this makes me know that the battery is low.

19:56:11.651 MQT: tele/ZigBee_Bridge/SENSOR = {"ZbReceived":{"Bedroom_Heater":{"Device":"0x3BF5","Name":"Bedroom_Heater","EF00/016E":1,"Endpoint":1,"LinkQuality":81}}}

19:56:11.651 MQT: tele/ZigBee_Bridge/SENSOR = {"ZbReceived":{"Bedroom_Heater":{"Device":"0x3BF5","Name":"Bedroom_Heater","EF00/016E":0,"Endpoint":1,"LinkQuality":81}}}

As I said before, i'm 100% sure that the variable "EF00/016E" it is representing the battery sensor, but needs to be with a proper name and value (I don't know which is which, if value "0" means "5%" or "1" means "100%")

This is the device
![image](https://user-images.githubusercontent.com/34201387/114432740-af7f0100-9bc9-11eb-950e-d38d36332585.png)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): Sonoff Zigbee Bridge & Tuya Radiator Actuator Thermostat
- [ x] Tasmota binary firmware version number used: 9.3.1
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [x ] Flashing tools used: Tasmotizer
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
20:03:02.150 MQT: stat/ZigBee_Bridge/RESULT = {"NAME":"ZHA ZBBridge","GPIO":[320,5088,0,5120,323,322,0,0,0,0,0,0,32,0],"FLAG":0,"BASE":18}
20:03:02.359 MQT: stat/ZigBee_Bridge/RESULT = {"Module":{"75":"Sonoff ZbBridge"}}
20:03:02.611 MQT: stat/ZigBee_Bridge/RESULT = {"GPIO0":{"320":"Led_i1"},"GPIO1":{"3552":"Zigbee Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3584":"Zigbee Rx"},"GPIO4":{"5312":"Zigbee Rst"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"640":"I2C SDA"},"GPIO13":{"576":"LedLink_i"},"GPIO14":{"608":"I2C SCL"},"GPIO15":{"0":"None"},"GPIO16":{"32":"Button1"},"GPIO17":{"0":"None"}}


```
- [ x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
none

```
- [x ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
20:05:45.908 MQT: stat/ZigBee_Bridge/STATUS = {"Status":{"Module":75,"DeviceName":"ZigBee_Bridge","FriendlyName":["ZigBee_Bridge"],"Topic":"ZigBee_Bridge","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
20:05:45.913 MQT: stat/ZigBee_Bridge/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Exception","Uptime":"1T04:44:36","StartupUTC":"2021-04-11T12:21:09","Sleep":50,"CfgHolder":4617,"BootCount":39,"BCResetTime":"2021-04-05T11:44:10","SaveCount":62,"SaveAddress":"F8000"}}
20:05:45.917 MQT: stat/ZigBee_Bridge/STATUS2 = {"StatusFWR":{"Version":"9.3.1(zbbridge)","BuildDateTime":"2021-03-09T16:13:51","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":160,"Hardware":"ESP8266EX","CR":"428/699"}}
20:05:45.921 MQT: stat/ZigBee_Bridge/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":3,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["PickOne_V",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00088009","2805C8000100060000005A00000000000000","00008080","00006002","00000000"]}}
20:05:45.928 MQT: stat/ZigBee_Bridge/STATUS4 = {"StatusMEM":{"ProgramSize":573,"Free":1216,"Heap":25,"ProgramFlashSize":2048,"FlashSize":2048,"FlashChipId":"1540A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F1007C4","04400001","00000002","00000000","00000000","00020000","00000000","00000000"],"Drivers":"1,2,7,9,10,20,23,41","Sensors":""}}
20:05:45.933 MQT: stat/ZigBee_Bridge/STATUS5 = {"StatusNET":{"Hostname":"ZigBee_Bridge","IPAddress":"192.168.0.207","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"84:CC:A8:9C:F4:73","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
20:05:45.937 MQT: stat/ZigBee_Bridge/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.102","MqttPort":1883,"MqttClientMask":"ZigBee_Bridge","MqttClient":"ZigBee_Bridge","MqttUser":"pickone","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
20:05:45.943 MQT: stat/ZigBee_Bridge/STATUS7 = {"StatusTIM":{"UTC":"2021-04-12T17:05:45","Local":"2021-04-12T20:05:45","StartDST":"2021-03-28T03:00:00","EndDST":"2021-10-31T04:00:00","Timezone":99,"Sunrise":"08:04","Sunset":"21:36"}}
20:05:45.948 MQT: stat/ZigBee_Bridge/STATUS10 = {"StatusSNS":{"Time":"2021-04-12T20:05:45"}}
20:05:45.955 MQT: stat/ZigBee_Bridge/STATUS11 = {"StatusSTS":{"Time":"2021-04-12T20:05:45","Uptime":"1T04:44:36","UptimeSec":103476,"Vcc":3.454,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"PickOne_V","BSSId":"74:DA:DA:FF:71:00","Channel":6,"RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}}}
20:05:45.963 MQT: stat/ZigBee_Bridge/STATUS12 = {"StatusSTK":{"Exception":9,"Reason":"Exception","EPC":["4023ab37","00000000","00000000"],"EXCVADDR":"00004bca","DEPC":"00000000","CallChain":["4023a9b8","4020e85c","4020e855","402448fa","40244830","4024535c","402448fa","40286c20","40245231","40286c20","40286c21","40244ae4","40244830","402860d5","4024535c","402448fa","402860ea","40244150","40244d2f","40244099","40104b87","40104b84","40103aeb","402440dc","401008b8","4000050c","4010393c","4020a720","40240516","4023df70","4025eded"]}}

```
- [ x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
na

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

    Install Tasmota to the Sonoff Zigbee Bridge
    Configure MQTT
    Pair the Tuya Radiator Actuator Thermostat
    Observe the MQTT messages

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
19:56:11.651 MQT: tele/ZigBee_Bridge/SENSOR = {"ZbReceived":{"Bedroom_Heater":{"Device":"0x3BF5","Name":"Bedroom_Heater","EF00/016E":1,"Endpoint":1,"LinkQuality":81}}}
19:56:11.651 MQT: tele/ZigBee_Bridge/SENSOR = {"ZbReceived":{"Bedroom_Heater":{"Device":"0x3BF5","Name":"Bedroom_Heater","EF00/016E":0,"Endpoint":1,"LinkQuality":81}}}

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
na

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
na

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving to discussion as this is a feature request for zigbee parameters.
