### ISSUE TITLE
contrôler dmx avec sonoff

### ISSUE THREAD

**Issue by arnaud-aub** [arendst/Tasmota#11729]
Bonjour, je cherche depuis un bout de temps, une façon de contrôler mes lumières DMX en wifi, j'ai en ma possession, un Sonoff basic, une carte MAX-485 (puce RS485), ainsi que des prises DMX. Comment puis-je faire ? je vous remercie, bonne journée.

**Comment by ascillato** [comment]
DMX n'est pas pris en charge dans Tasmota. Vous devez utiliser un autre firmware spécifique pour DMX. Ce référentiel Github est en anglais pour un public plus large.

**Comment by arnaud-aub** [comment]
Merci
