### ISSUE TITLE
esp8266 boards and SDCARD support

### ISSUE THREAD

**Issue by benzino77** [arendst/Tasmota#11724]
### PROBLEM DESCRIPTION
Compiling Tasmota with:
```C
#define USE_SPI
#define USE_UFILESYS
#define USE_SDCARD
```
in `user_config_override.h` file, throws an error: 
```
/workspace/Tasmota/tasmota/tasmota.ino:81:19: fatal error: SDFAT.h: No such file or directory

***************************************************************
* Looking for SDFAT.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SDFAT.h"
* Web  > https://platformio.org/lib/search?query=header:SDFAT.h
*
***************************************************************

 #include <SDFAT.h>
                   ^
compilation terminated.
*** [.pio/build/tasmota/src/tasmota.ino.cpp.o] Error 1
======================================= [FAILED] Took 10.71 seconds =======================================

Environment    Status    Duration
-------------  --------  ------------
tasmota        FAILED    00:00:10.710
================================== 1 failed, 0 succeeded in 00:00:10.710 ==================================
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): any esp8266 board
- [x] Tasmota binary firmware version number used: latest development
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: not applicable
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
not applicable

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
not applicable

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
not applicable

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
not applicable

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
compile Tasmota (on gitpod or locally) with:
```C
#define USE_SPI
#define USE_UFILESYS
#define USE_SDCARD
```
in `user_config_override.h` file

then `pio run -e tasmota`

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
It should compile without errors. Changing line [81](https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota.ino#L81) in tasmota/tasmota.ino file
from 
```C
#include SDFAT.h
```
to
```C
#include SdFat.h
```
allows compilation finish without errors. I don't have enough experience or knowledge to decide whether it is a proper fix or not. 

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Discussion https://github.com/arendst/Tasmota/discussions/11704

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Fix Merged. Thanks!!!

**Comment by benzino77** [comment]
Thanks!
