### ISSUE TITLE
DS18x20 dosn´t work in tasmota-sensors 9.3.1

### ISSUE THREAD

**Issue by luckysession** [arendst/Tasmota#11751]
DS18x20 dosn´t work in tasmota-sensors 9.3.1 - but in tasmota.bin work very well.

![image](https://user-images.githubusercontent.com/57873076/115046723-15c09800-9ed8-11eb-9bf3-8a6abba359a8.png)
(with firmware tasmota-sensors 9.3.1)
![image](https://user-images.githubusercontent.com/57873076/115047057-7223b780-9ed8-11eb-8bf9-0ed6b0f2c6ca.png)

(with firmware "tasmota-DE" but missing other sensor SDS011, BME280, BH1750, etc):
![image](https://user-images.githubusercontent.com/57873076/115047942-52d95a00-9ed9-11eb-8044-8ea909e05379.png)

Maybe missing some driver?

Thx

**Comment by ascillato** [comment]
Duplicated issue #11270
