### ISSUE TITLE
Align tasmotaglobal metrics for Prometheus to other metrics' syntax

### ISSUE THREAD

**Issue by twollweber** [arendst/Tasmota#11933]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
When using USE_PROMETHEUS, global metrics for temperature, humidity and pressure get generated. The syntax differs from all other metrics in that these are 'tasmotaglobal_xxx' where all other metrics follow the scheme 'tasmota_global_xxx'.
In addition, the humidity metric is missing the unit identifier. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Wemos D1 mini
- [x] Tasmota binary firmware version number used: 9.4.0.2
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
1. Compile with '#define USE_PROMETHEUS', '#define USE_I2C', '#define USE_BME'.
2. Configure and attach BME280, making sure that it appears in SENSOR data.
3. Check that http://ip.of.your.tasmota/metrics contains these lines:
```
# TYPE tasmotaglobal_temperature_celsius gauge
tasmotaglobal_temperature_celsius 22.3
# TYPE tasmotaglobal_humidity gauge
tasmotaglobal_humidity 26.1
# TYPE tasmotaglobal_pressure_hpa gauge
tasmotaglobal_pressure_hpa 996.8"
```

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
The above output should be:
```
# TYPE tasmota_global_temperature_celsius gauge
tasmota_global_temperature_celsius 22.3
# TYPE tasmota_global_humidity_percentage gauge
tasmota_global_humidity_percentage 26.1
# TYPE tasmota_global_pressure_hpa gauge
tasmota_global_pressure_hpa 996.8"
```

For the unit of humidity I suggest to use 'percentage' as it is used in UnitfromType().

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
PR #11931 (second commit) fixes this.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Thanks
