### ISSUE TITLE
ESP8266 - 4x Relay

### ISSUE THREAD

**Issue by DSRocker** [arendst/Tasmota#12002]
Hi,
I have 2 ESP8266 Relay boards with 4 Relay on each board. I flashed tasmota to the ESPs. It works fine. But when power on the board, the first ESP ist for mabe 0,5 seconds on and than off again.
I use the newest tasmota.
The Relays are on GPIO: 12, 13, 14, 16.

**Comment by ascillato** [comment]
That is a hardware limitation. That blink is how the Esp8266 boots and can not be controlled by software.
Some pins have several toggles or different startup level until the esp8266 starts the software in flash.

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/discussions/12004
