### ISSUE TITLE
Zigbee2Tasmota: ZBNAME (at least) not stored in Flash

### ISSUE THREAD

**Issue by schrej-zz** [arendst/Tasmota#12029]
### PROBLEM DESCRIPTION
I upgraded my selfcompiled version of Tasmota with #define USE_ZIGBEE from 9.1.0 to selfcompiled version  with #define USE_ZIGBEE version 9.4.0.
I realized, that (at least) the zbnames are not stored in flash and are gone, when device reboots.
In 9.1.0, I always saw a message in console "ZIG: Zigbee devices data in Flash..." which is now missing.
Is there a new parameter or setoption, that has to be set now to ensure storage in flash?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic):  WEMOS D1
- [ ] Tasmota binary firmware version number used: 9.4.0
  - [ ] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: Tasmocompiler
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
17:53:16.080 MQT: WL_WD1M_03/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,3584,1,3552,1,4704],"FLAG":0,"BASE":18}
17:53:16.298 MQT: WL_WD1M_03/stat/RESULT = {"Module":{"18":"Generic"}}
17:53:16.553 MQT: WL_WD1M_03/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"3584":"Zigbee Rx"},"GPIO14":{"0":"None"},"GPIO15":{"3552":"Zigbee Tx"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
7:54:09.431 MQT: WL_WD1M_03/stat/STATUS = {"Status":{"Module":18,"DeviceName":"WL_WD1M_03","FriendlyName":["OT_Zigbee_Coordinator"],"Topic":"WL_WD1M_03","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[1,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
17:54:09.444 MQT: WL_WD1M_03/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:33:44","StartupUTC":"2021-05-06T14:20:25","Sleep":50,"CfgHolder":4617,"BootCount":127,"BCResetTime":"2020-04-05T11:51:23","SaveCount":1775,"SaveAddress":"F9000"}}
17:54:09.457 MQT: WL_WD1M_03/stat/STATUS2 = {"StatusFWR":{"Version":"9.4.0(TasmoCompiler-esp82664M)","BuildDateTime":"2021-05-06T09:42:58","Boot":6,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"398/699"}}
17:54:09.468 MQT: WL_WD1M_03/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Schreiner",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["04008009","2805C8000100060000005AFF000000000000","000000C8","00006000","00000000"]}}
17:54:09.482 MQT: WL_WD1M_03/stat/STATUS4 = {"StatusMEM":{"ProgramSize":593,"Free":1452,"Heap":23,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F80458A","04660001","00000003","00000000","C000E981","00000004","00001000","00000000"],"Drivers":"1,2,4,6,8,9,10,18,19,22,23,24,26,27,29,30,35,37,45","Sensors":"1,2"}}
17:54:09.496 MQT: WL_WD1M_03/stat/STATUS5 = {"StatusNET":{"Hostname":"WL-WD1M-03","IPAddress":"192.168.13.103","Gateway":"192.168.2.1","Subnetmask":"255.255.0.0","DNSServer":"192.168.2.1","Mac":"BC:DD:C2:24:82:0B","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:54:09.509 MQT: WL_WD1M_03/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_24820B","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
17:54:09.522 MQT: WL_WD1M_03/stat/STATUS7 = {"StatusTIM":{"UTC":"2021-05-06T15:54:09","Local":"2021-05-06T17:54:09","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":99,"Sunrise":"06:20","Sunset":"21:12"}}
17:54:09.533 MQT: WL_WD1M_03/stat/STATUS10 = {"StatusSNS":{"Time":"2021-05-06T17:54:09"}}
17:54:09.545 MQT: WL_WD1M_03/stat/STATUS11 = {"StatusSTS":{"Time":"2021-05-06T17:54:09","Uptime":"0T01:33:44","UptimeSec":5624,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Schreiner","BSSId":"98:9B:CB:BE:A6:BF","Channel":6,"RSSI":100,"Signal":-50,"LinkCount":1,"Downtime":"0T00:00:07"}}}
```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
17:55:32.297 SRC: WebConsole from 192.168.4.1
17:55:32.301 CMD: Group 0, Index 1, Command "ZBNAME", Data "0x1053,ZB_BW_DW_03"
17:55:32.308 MQT: WL_WD1M_03/stat/RESULT = {"0x1053":{"Name":"ZB_BW_DW_03"}}
```

### TO REPRODUCE
enter zbname "device-id","name" in console

### EXPECTED BEHAVIOUR
Like weblog but with an additional line
ZIG: Zigbee devices data in Flash.....
### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
It is supposed to be fixed by https://github.com/arendst/Tasmota/pull/11870

Are you running a version that includes this fix?

**Comment by schrej-zz** [comment]
Hi @s-hadinger,
thanks for the fast reply.
I assume, that this fix is not in the master build 9.4.0 (compiled 13 days ago), but in one of the development builds.
I will compile a new version with development build and will give feedback.
Thanks Joerg

**Comment by schrej-zz** [comment]
I compile with current development version and it solved the issue.
Console shows expected ZIG: message afer ZBNAME and reports
`ZIG: Zigbee device information found in File System` after reeboot.
Thanks again.
Will close the issue.

**Comment by BassT23** [comment]
PLS reopen,
same problem with 9.5.0

**Comment by ascillato** [comment]
Just tested and it is working fine. Please, can you reflash your device with Tasmotizer erasing the flash before? Thanks.

**Comment by BassT23** [comment]
ok, I think there is a problem with my self compiled firmware.
The original tasmota-zigbee.bin.gz is working like a charm!

So what is wrong with my compiled firmware? Here is my userconfig:
hmmm, I see there is a mistake;
```
#ifndef USE_ZGBEE
#define USE_ZIGBEE                 
#endif
```
but my CC2530 work, ... (without saving, ...)

Will test with fixed userconfig

What are the other options, activated in tasmota-zigbee.bin.gz?

**Comment by ascillato** [comment]
> What are the other options, activated in tasmota-zigbee.bin.gz?

https://github.com/arendst/Tasmota/blob/b2a96298baa0d15612ccb7eb7fde9aa2ddaa609a/tasmota/tasmota_configurations.h#L471-L626

**Comment by BassT23** [comment]
Now I'm totally confused. This section is for building the sonoff zbbridge version?
But I need the zigbee (CC2530) version.
Also cant find zigbee in platformio_override.ini

**Comment by ascillato** [comment]
> Also cant find zigbee in platformio_override.ini

Because the environment definitions are in platformio_tasmota_env.ini file.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by BassT23** [comment]
ok, now it work.
What I do:

added "tasmota-zigbee" under "default_envs =" in platformio_override.ini

Now I had my self compiled working zigbee firmware.
THX!
