### ISSUE TITLE
Tell me why FQDN references to not resolve for MQTT broker host specification? 

### ISSUE THREAD

**Issue by dachshund-digital** [arendst/Tasmota#12109]
Tell me why FQDN references to not resolve for MQTT broker host specification?  If I have a DNS server.  If I have proper FQDN resolution for host names, Tasmota should resolve said names, period.  That is how everything works with DNS.  But what Tasmota does is some thing other than the standard default methodology?  I don't use or want to use mDNS, I don't use or want to use mDNS, I have real DNS servers, that are entire level standard.  Why, I happen to be a 30 IT retired network engineer, so creating my own DNS infrastructure was painless.  I just don't see the logic of not following standards.

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/discussions/12111
