### ISSUE TITLE
Variable not working in Power command

### ISSUE THREAD

**Issue by witwonghanchao** [arendst/Tasmota#12184]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Cannot turn on power using variable in command and rule. Try set variable to 1 or "on" but both do not work.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

From console command:
var1 1
Power1 %var1%

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Issue command
    var1 1
    Power1 %var1%

Then power turn on.
    stat/env-C45832B8/RESULT = {"POWER1":"ON"}

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

23:06:42.030 CMD: var1 1
23:06:42.049 MQT: stat/env-C45832B8/RESULT = {"Var1":"1"}
23:06:44.544 CMD: Power1 %var1%
23:06:44.557 MQT: stat/env-C45832B8/RESULT = {"POWER1":"OFF"}
23:06:44.568 MQT: stat/env-C45832B8/POWER1 = OFF
23:08:31.317 CMD: var1 on
23:08:31.334 MQT: stat/env-C45832B8/RESULT = {"Var1":"on"}
23:08:33.626 CMD: Power1 %var1%
23:08:33.639 MQT: stat/env-C45832B8/RESULT = {"POWER1":"OFF"}
23:08:33.650 MQT: stat/env-C45832B8/POWER1 = OFF

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Firmware version 9.4.0.4

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Variables like %var1% can be used only inside a rule.

Please, if you need further assistance on how to use Tasmota, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
