### ISSUE TITLE
WHERE THE FUCK IS THE DOWNLOAD BUTTON FOR SONOFF 4CH??????????

### ISSUE THREAD

**Issue by portiktamas** [arendst/Tasmota#12275]
I ONLY SEE THE DOWNLOAD FOR THE FUCKIN SOURCE CODE WHICH I DON'T NEED!!!!!
WHY IS THIS SOOOOOOO FUCKING HARD TO PUT A BIIIIIGGGGG BUTTTONN ON THE FRONT OF THE PAGE AND CALL IT A DAY????? YOU ARE COMPLICATING EVERYBODY'S LIFE! I DON'T WANT TO MIGRATE FROM AN OLDER VERSION, JUST INSTALL THE FUCKING .BIN

**Comment by Jason2866** [comment]
?
![Screenshot_20210606-112347](https://user-images.githubusercontent.com/24528715/120919430-d3d2f780-c6b9-11eb-9d51-bf016f7fe4d0.png)

**Comment by ascillato2** [comment]
@portiktamas

Hi, the button you are looking for is just a bit lower than the download source button and it is called RELEASE 9.4.0 and also you can reach the .bin files by clicking also on the DOWNLOADS button next to the release button. If you need help, you have the Tasmota discord chat to kindly ask for assistance.

Also, your post has been edited and moderated to comply with the Code of Conduct and so as to have a civilizated behaviour required by community projects.

------

User **portiktamas** has been reported to github.
