### ISSUE TITLE
Sonoff Zigbee Bridge and NAS-TH02B Temperatur and Humidity read problem

### ISSUE THREAD

**Issue by HReimann** [arendst/Tasmota#12373]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Sonoff ZBBridge by ITead didn't read the Temperatur and Humidity from Model NAS-TH02B Zigbee ID: "TS0201"; "_TZ3000_qaaysllp"

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff zigbee bridge
-  #[x] Tasmota binary firmware version number used: _9.4. 0____
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: __uart___
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

17:31:55.833 ZIG: ZbEZSPSend 34000066D30401000401010000000039010510390B0A00
17:31:55.835 ZIG: ZbZCLRawReceived: {"0xD366":{"0400/0000":13618,"Endpoint":1,"LinkQuality":126}}
17:31:55.843 ZIG: {"ZbEZSPReceived":"3400007F"}
17:31:55.845 ZIG: {"ZbEZSPReceived":"3F000066D3040100040101000000007F016600"}
17:31:56.198 MQT: tele/Sonoff_Zigbee_9F33F5/SENSOR = {"Device":"0xD366","Name":"Sensor","Illuminance":13618,"Endpoint":1,"LinkQuality":126}
17:31:56.836 ZIG: {"ZbEZSPReceived":"4500000401000401010001000086F8DA66D3FFFF0808390A0000213235"}
17:31:56.838 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0400","srcaddr":"0xD366","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":128,"securityuse":0,"seqnumber":134,"fc":"0x08","frametype":0,"direction":1,"disableresp":0,"manuf":"0x0000","transact":57,"cmdid":"0x0A","payload":"0000213235"}}
17:31:56.844 ZIG: ZbZCLRawReceived: {"0xD366":{"0400/0000":13618,"Endpoint":1,"LinkQuality":128}}
17:31:56.851 ZIG: {"ZbEZSPReceived":"34000080"}
17:31:56.853 ZIG: {"ZbEZSPReceived":"3F000066D30401000401010000000080016600"}
17:31:57.205 MQT: tele/Sonoff_Zigbee_9F33F5/SENSOR = {"Device":"0xD366","Name":"Sensor","Illuminance":13618,"Endpoint":1,"LinkQuality":128}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Still apppear after pairing the device. Only Illuminance and Battery was shown. 

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
17:39:54.010 CMD: ZbStatus2 sensor
17:39:54.014 CMD: Group 0, Index 2, Command "ZBSTATUS", Data "sensor"
17:39:54.020 MQT: stat/Sonoff_Zigbee_9F33F5/RESULT = {"ZbStatus2":[{"Device":"0xD366","Name":"Sensor","IEEEAddr":"0x847127FFFEFE814F","ModelId":"TS0201","Manufacturer":"_TZ3000_qaaysllp","Endpoints":[1],"Config":["I01"]}]}
17:39:54.056 MQT: tele/Sonoff_Zigbee_9F33F5/SENSOR = {"Device":"0xD366","Name":"Sensor","Illuminance":13618,"Endpoint":1,"LinkQuality":128}
17:39:59.696 ZIG: {"ZbEZSPReceived":"4500000401000401010001000038F8DA66D3FFFF0808750A0000213235"}

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving this issue to Ideas. Thanks.
