### ISSUE TITLE
#define USE_WEBSEND_RESPONSE leads to build error for xdrv_10_scripter.ino:2405:36: cannot convert 'String' to 'char*' in initialization

### ISSUE THREAD

**Issue by nikvostro** [arendst/Tasmota#12519]
### PROBLEM DESCRIPTION
master 9.5.0 and development builds gives an error (failing) during the build with env:tasmota32 when adding #define USE_WEBSEND_RESPONSE in user_config_override.h
"../xdrv_10_scripter.ino:2405:36: error: cannot convert 'String' to 'char*' in initialization"

### REQUESTED INFORMATION
- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32-CAM
- [x] Tasmota binary firmware version number used: 9.5.0
  - [ ] Pre-compiled
  - [x] Self-compiled (VS Code/Platformio)
- [n/a] Flashing tools used: _____
- [n/a] Provide the output of command: `Backlog Template; Module; GPIO 255`:
- [n/a] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
- [n/a] Provide the output of this command: `Status 0`:
- [n/a] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:

### TO REPRODUCE
1. Add in user_config_override.h:
```
#ifdef USE_RULES
#undef USE_RULES
#endif

#ifndef USE_SCRIPT
#define USE_SCRIPT
#endif

**#define USE_WEBSEND_RESPONSE**
```

2. Build with env:tasmota32

### EXPECTED BEHAVIOUR
Build completes successfully

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/83143316/123963722-69149380-d9bb-11eb-8ad0-cc76120c8fea.png)
![image](https://user-images.githubusercontent.com/83143316/123963739-6dd94780-d9bb-11eb-93e9-430ae66f7c58.png)

### ADDITIONAL CONTEXT
@Jason2866 

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
@gemu2015 can you have a look? Thx!
