### ISSUE TITLE
Shelly 2.5: Maxpower/ MaxPowerhold/ MaxPowerWindow/ Setoption33 not working for Relay 2

### ISSUE THREAD

**Issue by joeH68** [arendst/Tasmota#12588]
### PROBLEM DESCRIPTION

Tasmota 9.5.0.2 is ignoring the Maxpower, MaxPowerhold, MaxPowerWindow and Setoption33 settings for relay 2 of Shelly 2.5. Same settings are working fine for relay 1. This is a safety issue that complicates migrating from Shelly's stock firmware where MaxPower is applied to each relay separately.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): SHELLY 2.5
- [x] Tasmota binary firmware version number used: 9.5.0.2
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: OTA (https://github.com/yaourdt/mgos-to-tasmota)
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
17:41:10.878 CMD: Backlog Template; Module; GPIO 255
17:41:10.968 MQT: knswg12/ShellySwitch25_E523E0/TEMPLATE = {"NAME":"Shelly 2.5","GPIO":[320,0,32,0,224,193,0,0,640,192,608,225,3456,4736],"FLAG":0,"BASE":18}
17:41:11.233 MQT: knswg12/ShellySwitch25_E523E0/MODULE = {"Module":{"0":"Shelly 2.5"}}
17:41:11.540 MQT: knswg12/ShellySwitch25_E523E0/GPIO = {"GPIO0":{"320":"Led_i1"},"GPIO1":{"0":"None"},"GPIO2":{"32":"Button1"},"GPIO3":{"0":"None"},"GPIO4":{"224":"Relay1"},"GPIO5":{"193":"Switch_n2"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"640":"I2C SDA"},"GPIO13":{"192":"Switch_n1"},"GPIO14":{"608":"I2C SCL"},"GPIO15":{"225":"Relay2"},"GPIO16":{"3456":"ADE7953 IRQ"},"GPIO17":{"4736":"ADC Temp"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
17:41:56.579 MQT: knswg12/ShellySwitch25_E523E0/STATUS = {"Status":{"Module":0,"DeviceName":"KNSWG12-KU-STECKDOSEN","FriendlyName":["KNSWG12-KU-STECKDOSEN_plug1","KNSWG12-KU-STECKDOSEN_plug2"],"Topic":"ShellySwitch25_E523E0","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1,"InfoRetain":0,"StateRetain":0}}
17:41:56.585 MQT: knswg12/ShellySwitch25_E523E0/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin","RestartReason":"External System","Uptime":"0T06:52:36","StartupUTC":"2021-07-07T08:49:20","Sleep":50,"CfgHolder":4617,"BootCount":17,"BCResetTime":"2021-07-06T17:17:17","SaveCount":213,"SaveAddress":"F8000"}}
17:41:56.590 MQT: knswg12/ShellySwitch25_E523E0/STATUS2 = {"StatusFWR":{"Version":"9.5.0.2(tasmota)","BuildDateTime":"2021-07-06T14:35:13","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"541/699"}}
17:41:56.594 MQT: knswg12/ShellySwitch25_E523E0/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":1,"SysLog":3,"LogHost":"10.120.11.4","LogPort":514,"SSId":["LRS-WiFi",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["8420A039","2802FF00010006000096500A000000000000","0080808D","00006100","00000000"]}}
17:41:56.605 MQT: knswg12/ShellySwitch25_E523E0/STATUS4 = {"StatusMEM":{"ProgramSize":607,"Free":396,"Heap":23,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
17:41:56.610 MQT: knswg12/ShellySwitch25_E523E0/STATUS5 = {"StatusNET":{"Hostname":"KNSWG12-SHELLY-SWITCH25-E523E0","IPAddress":"10.120.22.34","Gateway":"10.120.22.1","Subnetmask":"255.255.255.0","DNSServer":"10.120.22.1","Mac":"3C:61:05:E5:23:E0","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:41:56.615 MQT: knswg12/ShellySwitch25_E523E0/STATUS6 = {"StatusMQT":{"MqttHost":"10.120.11.4","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_E523E0","MqttUser":"TASMOTA","MqttCount":2,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":5}}
17:41:56.623 MQT: knswg12/ShellySwitch25_E523E0/STATUS7 = {"StatusTIM":{"UTC":"2021-07-07T15:41:56","Local":"2021-07-07T17:41:56","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":99,"Sunrise":"05:33","Sunset":"21:21"}}
17:41:56.626 MQT: knswg12/ShellySwitch25_E523E0/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
17:41:56.643 MQT: knswg12/ShellySwitch25_E523E0/STATUS10 = {"StatusSNS":{"Time":"2021-07-07T17:41:56+02:00","Switch1":"OFF","Switch2":"OFF","ANALOG":{"Temperature":48.1},"ENERGY":{"TotalStartTime":"2021-07-06T17:17:17","Total":0.348,"Yesterday":0.086,"Today":0.262,"Power":[0,0],"ApparentPower":[0,0],"ReactivePower":[0,0],"Factor":[0.00,0.00],"Frequency":50,"Voltage":228,"Current":[0.000,0.000]},"TempUnit":"C"}}
17:41:56.651 MQT: knswg12/ShellySwitch25_E523E0/STATUS11 = {"StatusSTS":{"Time":"2021-07-07T17:41:56+02:00","Uptime":"0T06:52:36","UptimeSec":24756,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"LRS-WiFi","BSSId":"E8:DF:70:72:5F:CF","Channel":6,"Mode":"11n","RSSI":100,"Signal":-45,"LinkCount":1,"Downtime":"0T00:02:00"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
1. Backlog Maxpower 5; MaxPowerHold 2; MaxPowerWindow 5; setoption33 2
2. Connect 10W light to relay 2
3. Power2 1
### EXPECTED BEHAVIOUR
same as when connected to relay 1: 
light should blink 3 times:  ON (2 secs) -> OFF (5 secs)

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/73338645/124791514-67fbdd00-df4c-11eb-8e87-ad4f19b09bfd.png)

### ADDITIONAL CONTEXT
Tasmota's Power Monitoring settings / values apply:

1. sometimes to all relays (Temperature, Voltage, Frequency, Energy Today, Energy Yesterday, Energy Total)
2. other times to each relay (Current, Power, Apparent Power, Reactive Power,  Power Factor)

In case of Maxpower, MaxPowerHold, MaxPowerWindow and Setoption33 they apply to Relay 1 ONLY.  This is safety wise a risk as it is not documented that way. It also creates problems when migrating Shelly stock firmware where MaxPower may be specified per relay (when in relay mode).

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Thanks for reporting. Moving this to discussion as this is a feature request.
