### ISSUE TITLE
Issue uploading my firmware in Tasmota Device

### ISSUE THREAD

**Issue by danielvega3009** [arendst/Tasmota#12702]
Hi, 

I have modified the tasmota firmware to include a new functionality for a personal project, when uploading the firmware to my tasmota device from the application, it gives me the following error:

![image](https://user-images.githubusercontent.com/84938046/126333324-0068773d-1b33-42cf-b2cb-d7f566dff1a5.png)

How could I flash my tasmota device?? without welding please.

**Comment by ascillato** [comment]
Please, check https://github.com/arendst/Tasmota/discussions/12286
