### ISSUE TITLE
Connection issues while NOT having internet acces in local network

### ISSUE THREAD

**Issue by buzzer8** [arendst/Tasmota#12706]
My devices are connected via wlan to my accesspoint using tasmota 9.5.0. I DONT have a connection to the internet at the moment! So the devices are connected to wlan, but couldnt reach the internet. When i try to switch on or off there is a timeout of about 30 to 60 seconds from click to switch. Sometimes the first click works well, but after 2 or 3 more clicks, the timeout occurs, the web gui freezes as i said for about 30 to 60 seconds and nothing happens. This doesnt occur with 8.4.0!

**Comment by ascillato** [comment]
Hi, please, do a quick search in old issues. This was already addressed several times before.

Tasmota needs NTP. You can provide it or disable all timing functions in tasmota by command `time 1451602800` (https://tasmota.github.io/docs/Commands/)
