### ISSUE TITLE
BUG Tasmota Operator (multiplication, division, addition and subtraction) with Var or Mem

### ISSUE THREAD

**Issue by TheReiner** [arendst/Tasmota#12947]
Hi,

I have a bug with Operator...

This is my Rule
Rule1 on AS3935#Distance>0 DO Mem1=%value%*100000 endon

if value is 1... The result of my rule is "=1*100000"  (the literal string) not "100000" 

In the documentation https://tasmota.github.io/docs/Rules/#supported-commands
I don't understand "To use expressions in the Var, Mem and RuleTimer commands, an equal sign (=) character has to be used after the command. If not, the traditional syntax interpretation is used." Maybe is the solution ?

If i use the console, i have the same problem... Exemple... The Result is not 2

`22:23:30.850 CMD: Mem1=1+1
22:23:30.858 MQT: stat/tasmota_59E5D2/RESULT = {"Mem1":"=1+1"}`

Many Thanks

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/issues/12948
