### ISSUE TITLE
Issue Tasmota Operator (multiplication, division, addition and subtraction) with Var or Mem

### ISSUE THREAD

**Issue by TheReiner** [arendst/Tasmota#12948]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): WemosD1
- [x] Tasmota binary firmware version number used: 9.5
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Apple Terminal
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
Rule1 on AS3935#Distance>0 DO Mem1=%value%*100000 endon

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
"=1*100000" 

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

`22:23:30.850 CMD: Mem1=1+1

22:23:30.858 MQT: stat/tasmota_59E5D2/RESULT = {"Mem1":"=1+1"}`

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

This is my Rule
Rule1 on AS3935#Distance>0 DO Mem1=%value%*100000 endon

if value is 1... The result of my rule is "=1*100000"  (the literal string) not "100000" 

In the documentation https://tasmota.github.io/docs/Rules/#supported-commands
I don't understand "To use expressions in the Var, Mem and RuleTimer commands, an equal sign (=) character has to be used after the command. If not, the traditional syntax interpretation is used." Maybe is the solution ?

If i use the console, i have the same problem... Exemple... The Result is not 2

`22:23:30.850 CMD: Mem1=1+1
22:23:30.858 MQT: stat/tasmota_59E5D2/RESULT = {"Mem1":"=1+1"}`

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Tasmota don't support by default what you are trying to do. To use those symbolic expressions you need to enable them in the code and compile Tasmota by yourself. This is stated in the docs.

In the default versions, what it is supported are commands ADD, MULT, SUB, SCALE.

If you need further assistance, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
