### ISSUE TITLE
Missing example in the docs/Scripting-Language to retrieve .json from url: how to use gjp("host" "path")?

### ISSUE THREAD

**Issue by MagTun** [arendst/Tasmota#12964]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I want to use my tasmota smart plug to turn ON/OFF my DIY air filter when my [Luftdaten sensor](https://github.com/opendata-stuttgart/sensors-software) is above a certain threshold). 
The smart plug should connect to my json local url (like http://192.168.1.39:888/data.json) and based on the data in this json the plug should switch on and off. 
Following the [docs/Scripting-Language](https://tasmota.github.io/docs/Scripting-Language/#scripting), in user_config_override.h, I enabled reading HTTPS JSON WEB Pages with `#define SCRIPT_GET_HTTPS_JP` but don't find any ressource on how I can use gjp("host" "path") to get the data on the json. The only mention is :

`gjp("host" "path") = trigger HTTPS JSON page read as used by Tesla Powerwall (if defined SCRIPT_GET_HTTPS_JP)
`

A lot of others features are well documented but not this one.

Among other, the missing information are:
- How to define the variable to retrieve the data from gjp()?
- How to  extract the value from the json 

An example of the full script from send request/retrieve the request is really needed on the documentation 

(After these step I will have to send the command "http://192.168.1.54/cm?cmnd=Power%20On"  or "http://192.168.1.54/cm?cmnd=Power%20Off" based on the extracted json value and then recheck the json every 140secs ?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): Athom smartplug (esp8266) 
- [ x] Tasmota binary firmware version number used: 9.5.0
  - [x ] Pre-compiled
  - [ ] Self-compiled
- [x ] Flashing tools used: esptool

**Not needed** 
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving to discussions as this is a question not a Tasmota's bug report.
