### ISSUE TITLE
VINDRIKTNING: MQTT is only updated every 5 minutes

### ISSUE THREAD

**Issue by ikarisan** [arendst/Tasmota#13063]
### PROBLEM DESCRIPTION
After the issue https://github.com/arendst/Tasmota/issues/13012 has been resolved/closed I tried the newest Tasmota version from the development branch ( 9.5.0.8) and enabled VINDRIKTNING. 
As you can see, the IKEA device sends updates quit often:

18:50:17.416 DMP: 16 11 0B 00 00 00 11 00 00 02 F2 00 00 00 1C 02 00 00 0B A0
[...]
18:51:02.386 DMP: 16 11 0B 00 00 00 13 00 00 02 FA 00 00 00 1E 02 00 00 0B 94
18:51:20.793 WIF: Checking connection...
18:51:23.387 DMP: 16 11 0B 00 00 00 11 00 00 02 F3 00 00 00 1C 02 00 00 0B 9F
18:51:24.409 DMP: 16 11 0B 00 00 00 11 00 00 02 F4 00 00 00 1C 02 00 00 0B 9E
18:51:26.412 DMP: 16 11 0B 00 00 00 11 00 00 02 F4 00 00 00 1C 02 00 00 0B 9E
18:51:28.377 DMP: 16 11 0B 00 00 00 12 00 00 02 F5 00 00 00 1D 02 00 00 0B 9B
18:51:30.392 DMP: 16 11 0B 00 00 00 12 00 00 02 F6 00 00 00 1D 02 00 00 0B 9A
18:51:32.403 DMP: 16 11 0B 00 00 00 12 00 00 02 F7 00 00 00 1D 02 00 00 0B 99
18:51:35.416 DMP: 16 11 0B 00 00 00 12 00 00 02 F7 00 00 00 1D 02 00 00 0B 99
18:51:40.797 WIF: Checking connection...
18:51:56.378 DMP: 16 11 0B 00 00 00 10 00 00 02 F0 00 00 00 1B 02 00 00 0B A4
18:51:57.382 DMP: 16 11 0B 00 00 00 10 00 00 02 F0 00 00 00 1B 02 00 00 0B A4
18:51:59.388 DMP: 16 11 0B 00 00 00 10 00 00 02 F0 00 00 00 1B 02 00 00 0B A4
[...]

But the corresponding MQTT messages are apparently only sent every 5 minutes. 
(see screenshot)

I took a quick look into the "xsns_91_vindriktning.ino" file, but I did not find a "wait for five minutes" line. :( 
The MQTT messages should be sent much more often. The sensor/the IKEA controller is so sluggish that you can also send out a corresponding MQTT message with every UART message received.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Wemos D1
- [X] Tasmota binary firmware version number used: 9.5.0.8
  - [ ] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: Platformio / VS Code
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Compile and install Tasmoto 9.5.0.8 onto a Wemos D1 device. Connect it to a IKEA VINDRIKTNING device and configure MQTT. 

### EXPECTED BEHAVIOUR
The MQTT messages should be sent out much more frequently. Maybe every time, the sensor values changes. 

### SCREENSHOTS
![grafik](https://user-images.githubusercontent.com/14032966/132104333-c897788a-146f-4749-829b-53a3e7c43c46.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
As designed. Look after the command `teleperiod`. Default is 5 minutes
