### ISSUE TITLE
Need help connecting to guest network w/ a captive portal

### ISSUE THREAD

**Issue by jschwalbe** [arendst/Tasmota#13098]
This isn't a bug, sorry if I'm doing this wrong.

I would like to connect my switches to a captive portal at work. It's a cisco-based guest network (at my job) that requires a website to be loaded and then click the "I agree" button. I've accomplished it on my desktop w/ curl, but I'm wondering if any such method exists within Tasmota.

Many thanks!

**Comment by Jason2866** [comment]
No, not implemented.

**Comment by jschwalbe** [comment]
I was just investigating further into the WebSend command. But that appears to only support http (not https), otherwise I think that would work. Bummer!

**Comment by Jason2866** [comment]
You can try with Berry. Compile with support for https (only Berry!).
To enable you have to compile with `USE_WEBCLIENT_HTTPS`

**Comment by jschwalbe** [comment]
> You can try with Berry. Compile with support for https (only Berry!).
> To enable you have to compile with `USE_WEBCLIENT_HTTPS`

@Jason2866 Thanks for the idea - and forgive me if I'm misunderstanding something - but it seems like this is for esp32 only, is that correct?

**Comment by Jason2866** [comment]
Ahh, yes. So no way.
