### ISSUE TITLE
Eachen ZbBridge Pro crashes when clicking 'Configure WiFi'

### ISSUE THREAD

**Issue by pingel20** [arendst/Tasmota#13445]
### PROBLEM DESCRIPTION
The Eachen ZbBridge Pro (ESP32) crashes (resets) when clicking Configure WiFi in the Configuration menu

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Eachen ZbBridge Pro
- [x] Tasmota binary firmware version number used: 10.0.0.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: ESPFlasher
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Click 'Configure WiFi'

### EXPECTED BEHAVIOUR
Show WiFi config menu

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
The device is flashed with tasmota32-zigbeebridge.bin. No Zigbee devices paired yet.
After the reset Info3 gives some information:

```
  "Info3": {
    "RestartReason": {
      "Exception": 29,
      "Reason": "StoreProhibited",
      "EPC": "4008cc86",
      "EXCVADDR": "00000000",
      "CallChain": [
        "4008cc83",
        "4008d055",
        "40156447",
        "40088289",
        "4019eb3b",
        "40157533",
        "4008f109"
      ]
    }
  }

```
At the moment the device is used with Wifi  (no Ethernet yet). The initial Wifi setup after flashing was no problem.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Great to know that now it is working for you.

**Comment by R5fan** [comment]
> Please try latest version from the link provided here [#13445 (comment)](https://github.com/arendst/Tasmota/issues/13445#issuecomment-953803688) The i2c bug is fixed.

I also get a red blinking led and no web interface, though I can still ping the device.

**Comment by pingel20** [comment]
Yeh, a bit strange this issue is closed, because I never had a successful firmware upgrade.
I have a tasmota32-zigbeebridge.bin from October 22. That day I first serial flashed my device.
Later bins (made by Jason2866?) failed to start after upgrading from the web interface.

I now use my bin file from Oct. 22 via ethernet.
I'll wait for a more solid new version before trying to upgrade again. No need for the moment.

**Comment by R5fan** [comment]
I think @ascillato2 misread your comment. Clearly the issue isnt solved.
I dont particularly care for wifi, but if Im not mistaken, the oct 22 version will stop working if you power cycle the device?

**Comment by jibril-r6** [comment]
> The unofficial build [tasmota32-zigbeebridge](https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-zigbeebridge.bin) is now build with Tasmota Arduino core 2.0.1rc1 (IDF4.4 based) Please try. ~Do use Template `{"NAME":"ZB-GW03-V1.2","GPIO":[0,0,3552,0,3584,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0],"FLAG":0,"BASE":1}`~ Edit Original Template can be used since i2c bug is fixed

your ethernet port is working with this build?

**Comment by pingel20** [comment]
>> The unofficial build [tasmota32-zigbeebridge](https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-zigbeebridge.bin) is now build with Tasmota Arduino core 2.0.1rc1 (IDF4.4 based) Please try. 
> 
> your ethernet port is working with this build?

No, it is not.
The builds based on IDF4.4 (whatever that may be) did not work for me.
Uploading is successful, but then the device does not start in a proper way. UI unreachable.

**Comment by ascillato** [comment]
> Uploading is successful, but then the device does not start in a proper way. UI unreachable.

When changing the SDK, sometimes it is required to start from an erased device. Please, try to erase your device flash first and then flash the new version.

**Comment by s-hadinger** [comment]
I just flashed my Eachen Zigbee bridge with latest IDF4.4 build (self-compile), and it works fine: both Wifi and Eth. No reboot when configuring Wifi.

So I suppose there is hope :)

**Comment by pingel20** [comment]
> I just flashed my Eachen Zigbee bridge with latest IDF4.4 build (self-compile), and it works fine:

And did you do a Firmware upgrade from the user interface or was this a serial flash after soldering 5 wires?

**Comment by s-hadinger** [comment]
I did both. First flash with serial, then update via file upload on console.

**Comment by s-hadinger** [comment]
The is a crash on IDF4.4, I just pushed a PR to solve it. #13582
