### ISSUE TITLE
Can't configure extra GPIO pins of Sonoff POW R2

### ISSUE THREAD

**Issue by TheDuchCobra1** [arendst/Tasmota#13543]
I've reflashed a Sonoff POW R2 with the tasmota firmware (latest version).
When I select "Configure Module" and turn it into a Sonoff POW R2, I can't select any options at extra GPIO pins.
If you take a look at the board, there are a few GPIO ports free. (GPIO1, GPIO3, GPIO4 and GPIO5)

Why can't the Tasmota Sonoff POW R2 firmware don't use these GPIO pins for extra configuration?

**Comment by ascillato** [comment]
As designed. Those pins are referenced to mains AC. If you connect anything there, that will be connected to mains AC too. That is very dangerous. We don't give support to dangerous modifications.

This has been already addressed several times. Please, do a quick search for more information on old issues. Thanks.

**Comment by TheDuchCobra1** [comment]
I understand, that's clear.
I was searching, but couldn't find it directly.
Thank you for your answer!
