### ISSUE TITLE
Mem variables usage

### ISSUE THREAD

**Issue by washcroft** [arendst/Tasmota#13613]
### PROBLEM DESCRIPTION

Trying to use mem variables as values in other commands is not working correctly, mem variables are set, but the command sticks to its original value.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

n/a

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:

n/a

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

n/a

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

n/a

```

### TO REPRODUCE

```
17:26:42.282 CMD: Mem10
17:26:42.289 MQT: tasmota/stat/tasmota_31FB30/RESULT = {"Mem10":""}
17:26:48.281 CMD: Mem10 50
17:26:48.288 MQT: tasmota/stat/tasmota_31FB30/RESULT = {"Mem10":"50"}
17:26:56.321 CMD: BlinkTime %Mem10%
17:26:56.327 MQT: tasmota/stat/tasmota_31FB30/RESULT = {"BlinkTime":20}
```

### EXPECTED BEHAVIOUR

`17:26:56.327 MQT: tasmota/stat/tasmota_31FB30/RESULT = {"BlinkTime":50}`

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

The variables can be used only inside a rule. They won't work in the console.

https://tasmota.github.io/docs/Rules/

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
