### ISSUE TITLE
webui ota fw upgrade to version 10 fails with memory issue

### ISSUE THREAD

**Issue by rsteininger** [arendst/Tasmota#13639]
hi there, 
Yesterday I tried upgrading / updating a number of my devices from tasmota 9.5 to the latest 10.0.0.2.

Here a list of device types I tried:
Gosund UP111
Sonoff 433Mhz RF Bridge
Shelly 1PM

Due to memory issues, I always have to go the tasmota-minimal step first, followed by the target tasmota firmware. 
However, yesterday for the first time, the final step failed on every single device type reporting: insufficient memory. 
I downgraded back to 9.5 via minimal, followed by regular tasmota.bin v9.5 without any problems. Repeated efforts to go to 10.0.0.2 via webui manual or on-button upgrade failed every single time. 

What is however interesting is, that when going to the console, and initiating the upgrade from there, I was able to upgrade ALL my devices, no problem with the following command! 
backlog OtaUrl http://ota.tasmota.com/tasmota/tasmota.bin; upgrade 1

Comparing file sizes from v9.5.0 Michael:
tasmota.bin 622,112 bytes
tasmota-minimal.bin 398,528 Byte 

with v10.0.0 Norman:
tasmota.bin 627,248
tasmota-minimal.bin 403,056

it seems to me that in my case, these have somehow become just a tat to big for a webui OTA upgrade with minimal fw intermediate step. Not sure if anything can be down about this or if there is another workaround? 

For me, the console upgrade works great! This is actually simpler and it seems less troublesome was the browser based web ui upgrade! 

I just wanted to share my experience in case I am not the only one encountering that issue.

**Comment by barbudor** [comment]
`backlog OtaUrl http://ota.tasmota.com/tasmota/tasmota.bin; upgrade 1`
is using tasmota-minimal.bin behind the scene
So that should also work when using file upload going through minimal manually
