### ISSUE TITLE
added TSettings size check at compile...

### ISSUE THREAD

**Issue by trlafleur** [arendst/Tasmota#13637]
In my codebase, I added a compile-time static_assert to check the size of the TSettings structure.
As a check when adding variables to the structure.  In settings.h
~~~
} TSettings;

static_assert(sizeof(TSettings) == 4096, "TSettings Size is not correct");    // TRL
~~~

**Comment by s-hadinger** [comment]
Thanks for this trick that I didn't know. I love it

**Comment by arendst** [comment]
I'll add it now. Thx.
