### ISSUE TITLE
Feature Request - Shutter auto calibration

### ISSUE THREAD

**Issue by najdanovicivan** [arendst/Tasmota#13687]
### PROBLEM DESCRIPTION
This is feature request.

Regarding the Shutters and Blinds I have the motors which have mechanical limiters. Once the motor reaches the end position it will automatically stop. If will be great for devices which have means of measuring power consumption to implement some sort of auto calibration feature. Looking at the power consumption to automatically measure the time needed to open and close the shutters.

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Irrelevant
- [x] Tasmota binary firmware version number used: 10.0.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Esptool
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
```
- [ ] Provide the output of this command: `Status 0`:
```lua
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
```

### TO REPRODUCE
None

### EXPECTED BEHAVIOUR
Feature Request

### SCREENSHOTS
None

### ADDITIONAL CONTEXT
None

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
Feature requests goes in Discussion/Ideas : https://github.com/arendst/Tasmota/discussions

Don't clutter Github Issues for something that is not a qualified bug

**Comment by najdanovicivan** [comment]
Sorry. First time writing here. Will close this one and add it to the discussions
