### ISSUE TITLE
KNX not reply

### ISSUE THREAD

**Issue by bolfox** [arendst/Tasmota#13709]
Hi to all,

i have a Sonoff TH16 with Si7021 with tasmota 10.0.0(knx).

It read the temperature and humidity on web interface

![image](https://user-images.githubusercontent.com/35669017/142215624-1c605ce6-3694-49d5-be09-8d2f3cfd2683.png)

I have set the knx part

![image](https://user-images.githubusercontent.com/35669017/142215746-45e7cdec-90fb-4c4c-868b-e6009d80ca02.png)

But when i tried to read the group 8 / 1 / 1 it replay with a null value

![image](https://user-images.githubusercontent.com/35669017/142216108-676edd2d-f510-476b-8de1-1b3adab98744.png)

Tnx

**Comment by ascillato** [comment]
Hi, the zero you see in the console is not the temperature is the type of command received. Just ignore it. Tasmota is sending the temperature value to your 8/1/1. Be aware of setting in your KNX network the correct variable type (4byte_float). DPT 14
