### ISSUE TITLE
Online configuration possible

### ISSUE THREAD

**Issue by DavidSaguna** [arendst/Tasmota#13755]
So I have a friend that uses Tasmota as his router OS and he allowed me to run some security tests. After some NMap work, I discovered that you can access the configuration screen on port 8080 remotely. You can find any informations and even reboot the router in a loop, all of it, remotely. (IP:8080)

(I think the version is 8.3.1)

**Comment by ascillato** [comment]
> So I have a friend that uses Tasmota as his router OS

Sorry. I think that you have the wrong repository and wrong software name. Tasmota is NOT a router firmware. Is a firmware for ESP8266 and ESP32 smart home devices. Tasmota don't have any routing capability and the port 8080 is not open nor accesible.

Please, check [Tasmota documentation](https://tasmota.github.io/docs/) to know what Tasmota is about. Thanks.
