### ISSUE TITLE
Shelly Temperature Addon & Tasmota KNX version

### ISSUE THREAD

**Issue by Kolbi** [arendst/Tasmota#13794]
Hi guys,

I'm using an Shelly 1 + Shelly Temperature Addon and have connected 2 DS18B20.

I'm using the KNX version of Tasmota, but I only can send 1 temperature value, is it possible to increase this number to three?

Thanks in advance

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/discussions/13795
