### ISSUE TITLE
Aqara(Xiaomi) E1 Door & Window Sensor (MCCGQ14LM) not working

### ISSUE THREAD

**Issue by f45tb00t** [arendst/Tasmota#13842]
Hello,

I am using Tasmota v10.0.0(zbbridge) since today. I was with v9.4.0 before. Unfortunately the new Aqara devices are not working.

It seems the firmware needs to be upgraded.

Here are some references:
dresden-elektronik/deconz-rest-plugin#5403
Koenkk/zigbee2mqtt#9274
home-assistant/core#58985

@theo: Is there anything you can do?

Kind regards

fb

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/discussions/13848
