### ISSUE TITLE
File Size to big??

### ISSUE THREAD

**Issue by ymurawski** [arendst/Tasmota#13869]
Hi, I'm using many Sonoff Basic Modules with Tasmota 9.5.

Now I wanted to upgrade to 10.0 but when I try to upload tasmota.bin it always said file size to big. Any advice ? 

Thanks allot 😊

**Comment by ascillato2** [comment]
Hi,

You must use Tasmota.bin.gz for upgrades. Tasmota.bin is for serial flashing.

Please, check the following issue for more details. Thanks.

https://github.com/arendst/Tasmota/issues/13640

Closing this issue as it is **duplicated**. Sorry.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
