### ISSUE TITLE
POWER1 OFF issed after setting PulseTime to another Relay

### ISSUE THREAD

**Issue by mrslvd** [arendst/Tasmota#13916]
### PROBLEM DESCRIPTION
I have 8 relays on my board. When I set PulseTime (for example: pulsetime8 10) a power1 off command is issued by tasmota device. After that every time I activate relay8, power1 off is issued as well

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32S custom board
- [x] Tasmota binary firmware version number used: 10.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: ESP-Flasher-Windows-x64
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
13:40:17.433 RSL: RESULT = {"NAME":"ESP32-FULL-2","GPIO":[1,1,1,1,229,418,1,1,1,230,416,417,228,227,225,224,0,1,1,226,0,0,1,231,0,0,0,0,4704,4705,194,195,192,0,0,193],"FLAG":0,"BASE":1}
13:40:17.629 RSL: RESULT = {"Module":{"0":"ESP32-FULL-2"}}
13:40:17.889 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"229":"Relay6"},"GPIO5":{"418":"PWM3"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"230":"Relay7"},"GPIO14":{"416":"PWM1"},"GPIO15":{"417":"PWM2"},"GPIO16":{"228":"Relay5"},"GPIO17":{"227":"Relay4"},"GPIO18":{"225":"Relay2"},"GPIO19":{"224":"Relay1"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"226":"Relay3"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"231":"Relay8"},"GPIO32":{"4704":"ADC Input1"},"GPIO33":{"4705":"ADC Input2"},"GPIO34":{"194":"Switch_n3"},"GPIO35":{"195":"Switch_n4"},"GPIO36":{"192":"Switch_n1"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"193":"Switch_n2"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
13:41:46.284 CMD: Status 0
13:41:46.292 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"ESP_FULL_2","FriendlyName":["Tasmota","","","","","","",""],"Topic":"tasmota_4F5C78","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
13:41:46.299 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Vbat power on reset","Uptime":"0T02:17:56","StartupUTC":"2021-12-04T10:23:50","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2021-12-04T11:03:55","SaveCount":24}}
13:41:46.307 RSL: STATUS2 = {"StatusFWR":{"Version":"10.0.0(tasmota)","BuildDateTime":"2021-10-19T08:26:22","Core":"1_0_7_4","SDK":"v3.3.5-245-g95097b38d","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6","CR":"401/699"}}
13:41:46.313 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["NightProwler2G4",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A0A000000000000","00000080","00006000","00004000"]}}
13:41:46.332 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":1269,"Free":1856,"Heap":131,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":2,"Features":["00000809","9FDAC787","00152001","B7F7BFCF","05DA9BC0","60360DC7","000840D2","20200000","0000482D"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,17,20,21,24,26,27,29,34,38,50,52,59","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,127"}}
13:41:46.343 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-4F5C78-7288","IPAddress":"192.168.0.180","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.0.1","DNSServer2":"192.168.0.1","Mac":"08:3A:F2:4F:5C:78","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
13:41:46.349 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4F5C78","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
13:41:46.356 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-12-04T12:41:46","Local":"2021-12-04T13:41:46","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:26","Sunset":"16:54"}}
13:41:46.495 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-12-04T13:41:46","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON","ANALOG":{"A1":41,"A2":17},"ESP32":{"Temperature":53.3},"TempUnit":"C"}}
13:41:46.511 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-12-04T13:41:46","Uptime":"0T02:17:56","UptimeSec":8276,"Heap":134,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":97,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","POWER9":"OFF","Dimmer":10,"Color":"1A1A1A","HSBColor":"0,0,10","Channel":[10,10,10],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"NightProwler2G4","BSSId":"04:D4:C4:3D:76:80","Channel":1,"Mode":"11n","RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
13:43:04.261 CMD: weblog 4
13:43:04.266 RSL: RESULT = {"WebLog":4}
13:43:05.129 CFG: Saved, Count 25, Bytes 4096
13:43:13.117 WIF: Checking connection...
13:43:28.260 HTP: Main Menu
13:43:33.126 WIF: Checking connection...
13:43:34.422 SRC: WebGui from 192.168.0.2
13:43:34.428 RSL: RESULT = {"POWER8":"ON"}
13:43:34.432 RSL: POWER8 = ON
13:43:35.532 SRC: PulseTimer
13:43:35.537 RSL: RESULT = {"POWER8":"OFF"}
13:43:35.540 RSL: POWER8 = OFF
13:43:35.542 SRC: PulseTimer
13:43:35.546 RSL: RESULT = {"POWER1":"OFF"}
13:43:35.550 RSL: POWER1 = OFF

```

### TO REPRODUCE
_Steps to reproduce the behavior: 
write a command: pulsetime8 10

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I expect that only relay8 output will perform any action. In this case power8 off after 1 second.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
The following is copied from console:
12:38:47.859 CMD: pulsetime8 10
12:38:47.865 RSL: RESULT = {"PulseTime8":{"Set":10,"Remaining":10}}
12:38:48.923 RSL: RESULT = {"POWER8":"OFF"}
12:38:48.926 RSL: POWER8 = OFF
12:38:48.931 RSL: RESULT = {"POWER1":"OFF"}
12:38:48.934 RSL: POWER1 = OFF

The following is after I activate relay8:
12:45:39.819 RSL: RESULT = {"POWER8":"ON"}
12:45:39.823 RSL: POWER8 = ON
12:45:40.822 RSL: RESULT = {"POWER8":"OFF"}
12:45:40.825 RSL: POWER8 = OFF
12:45:40.830 RSL: RESULT = {"POWER1":"OFF"}
12:45:40.834 RSL: POWER1 = OFF

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Failed to reproduce.

If you did not ignore the template for documenting your situation, you could have supplied relevant info for seeing what happens, especially the extra details from increasing the logging level.

**Comment by mrslvd** [comment]
Sorry, I've missed this. I hope the updated info will help.
Best regards,
Miro

**Comment by barbudor** [comment]
I can reproduce.
If you set pulsetime on every power 1 to 8, the automatic power off of any is also issuing an off on power1

This happens as soon as there is more than 8 power devices (8 relays + 1 PWM or 9 relays).
It should not behave like that
The expected behavior is
`Defined PulseTime for relays <1-8> will also be active for correspondent Relay <9-16>.`
So in your case only POWER9 OFF should also trigger POWER1 OFF, not the other

I'm looking into it

**Comment by mrslvd** [comment]
Thanks!

**Comment by barbudor** [comment]
Fixed in https://github.com/arendst/Tasmota/pull/13920
Please wait for PR to be merged and new development binaries made available at http://ota.tasmota.com/tasmota32/

**Comment by mrslvd** [comment]
Thanks!
Best regards,
Miro
