### ISSUE TITLE
Son off 4 channel pro R3 turning channel 1 on and off

### ISSUE THREAD

**Issue by Koolinl** [arendst/Tasmota#13954]
Just flashed new 4 channel pro R3 with 10.0. 

Everything seems ok apart from Channel 1 which turns on and off on its own. 

Had anybody else experienced this?

**Comment by ascillato** [comment]
No. We haven't.

If you want help, you will need to provide a little more information. A good starting point is completing the template. If you don't want to provide that, you can also use the Tasmota support chat.
