### ISSUE TITLE
SetOption19 results in error

### ISSUE THREAD

**Issue by ConfigMgrPro** [arendst/Tasmota#13953]
I have just installed a new Sonoff Mini R2.
This unit needs to connect to Home Assistant.

When i try to configure the Option19 i get an error.
10:04:50 CMD: Group 0, Index 1, Command "SETOPTION", Data "19 0"
10:04:50 MQT: stat/tasmota_487E7F/RESULT = {"Command":"Error"}

Tested using both the 10.0.0 version as well oin the 9.1.0 release, both give the same result.
Configuration has been reset, tried with and without template configured. All results in the same error.

**Comment by ascillato** [comment]
Syntax error.

The command is

SETOPTION19 0

without spaces between setoption and 19.

Also, all setoptions have an alias, so the same can be written as

SO19 0
