### ISSUE TITLE
Sonoff rf bridge learning but not sending

### ISSUE THREAD

**Issue by atv2016** [arendst/Tasmota#13972]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I see all 433mhz messages and codes. When I put it in learning mode data it says learning complete and it beeps but data is always 000000. When I save the rfcode manually to rfkey1 it is saved.

when sending rfkey1 nothing happens. I include rfsync rflow and rfhigh in the backlog command.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____sonoff rf bridge 
- [x] Tasmota binary firmware version number used: _____latest
  - [x] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: _____esphome
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
15:49:42.587 CMD: Backlog Template; Module; GPIO 255
15:49:42.612 MQT: stat/tasmota_5AF452/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
15:49:42.836 MQT: stat/tasmota_5AF452/RESULT = {"Module":{"25":"Sonoff Bridge"}}
15:49:43.091 MQT: stat/tasmota_5AF452/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"3200":"Serial Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3232":"Serial Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
15:49:43.564 MQT: tele/tasmota_5AF452/RESULT = {"Time":"2021-12-09T15:49:43","RfReceived":{"Sync":13300,"Low":430,"High":1240,"Data":"E5242C","RfKey":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
n/a

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

15:50:11.007 CMD: status 0
15:50:11.015 MQT: stat/tasmota_5AF452/STATUS = {"Status":{"Module":25,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_5AF452","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
15:50:11.024 MQT: stat/tasmota_5AF452/STATUS1 = {"StatusPRM":{"Baudrate":19200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Power On","Uptime":"0T00:57:38","StartupUTC":"2021-12-09T13:52:33","Sleep":50,"CfgHolder":4617,"BootCount":23,"BCResetTime":"2021-12-04T01:06:36","SaveCount":51,"SaveAddress":"FB000"}}
15:50:11.033 MQT: stat/tasmota_5AF452/STATUS2 = {"StatusFWR":{"Version":"10.0.0(tasmota)","BuildDateTime":"2021-10-19T08:23:49","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"384/699"}}
15:50:11.041 MQT: stat/tasmota_5AF452/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["VM5848500",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A0A000000000000","00000080","00006000","00004000"]}}
15:50:11.054 MQT: stat/tasmota_5AF452/STATUS4 = {"StatusMEM":{"ProgramSize":612,"Free":388,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
15:50:11.063 MQT: stat/tasmota_5AF452/STATUS5 = {"StatusNET":{"Hostname":"sonoff-bridge-tasmotized","IPAddress":"192.168.50.62","Gateway":"192.168.50.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.50.1","DNSServer2":"0.0.0.0","Mac":"70:03:9F:5A:F4:52","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
15:50:11.068 MQT: stat/tasmota_5AF452/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.50.148","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_5AF452","MqttUser":"Mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:50:11.077 MQT: stat/tasmota_5AF452/STATUS7 = {"StatusTIM":{"UTC":"2021-12-09T14:50:11","Local":"2021-12-09T15:50:11","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:31","Sunset":"16:53"}}
15:50:11.084 MQT: stat/tasmota_5AF452/STATUS10 = {"StatusSNS":{"Time":"2021-12-09T15:50:11"}}
15:50:11.092 MQT: stat/tasmota_5AF452/STATUS11 = {"StatusSTS":{"Time":"2021-12-09T15:50:11","Uptime":"0T00:57:38","UptimeSec":3458,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"VM5848500","BSSId":"3C:7C:3F:6B:9D:70","Channel":3,"Mode":"11n","RSSI":94,"Signal":-53,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

15:50:54.546 CMD: weblog 4
15:50:54.552 MQT: stat/tasmota_5AF452/RESULT = {"WebLog":4}
15:50:54.871 CFG: Saved to flash at FA, Count 52, Bytes 4096
15:50:57.048 WIF: Checking connection...
15:50:57.635 DMP: A4 34 30 01 AE 04 D8 E5 24 2C 55

15:51:17.035 WIF: Checking connection...
15:51:17.591 CMD: RFKey1
15:51:17.593 SRC: WebConsole from 192.168.50.211
15:51:17.596 CMD: Grp 0, Cmnd 'RFKEY', Idx 1, Len 0, Data ''
15:51:17.608 MQT: stat/tasmota_5AF452/RESULT = {"RfKey1":"Learned sent"}
15:51:18.043 DMP: A0 55
15:51:24.572 DMP: A4 32 AA 01 AE 04 E2 E5 24 2C 55


```

and one when learning on weblog 4:

15:53:12.823 MQT: stat/tasmota_5AF452/RESULT = {"RfKey1":"Start learning"}
15:53:12.843 DMP: A0 55
15:53:17.020 WIF: Checking connection...
15:53:17.845 DMP: A3 33 FE 01 B8 04 CE E5 24 2C 55
15:53:17.850 MQT: stat/tasmota_5AF452/RESULT = {"RfKey1":"Learned"}
15:53:18.147 DMP: A4 22 74 02 E4 00 28 00 00 00 55
15:53:18.153 MQT: tele/tasmota_5AF452/RESULT = {"Time":"2021-12-09T15:53:18","RfReceived":{"Sync":8820,"Low":740,"High":40,"**Data":"000000**","RfKey":"None"}}
15:53:18.879 CFG: Saved to flash at F9, Count 53, Bytes 4096
### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

for 433 device to respond to rfcodes

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
devices seem to receive rfcodes fine. learning seems to complete, but data field is 0000000.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by atv2016** [comment]
how do i disable weblog again?

**Comment by atv2016** [comment]
It seems even when i tell the values to tasmota data is still 0.

First i use backlog command, then i use rfkey1 with weblog set to 4 but data field not reflecting that..

:57:30.610 CMD: Grp 0, Cmnd 'BACKLOG', Idx 1, Len 62, Data 'rfsync 12440; rflow 420; rfhigh 1210; rfcode #B9D671; rfkey1 4'
15:57:30.633 SRC: Backlog
15:57:30.635 CMD: Grp 0, Cmnd 'RFSYNC', Idx 1, Len 5, Data '12440'
15:57:30.642 MQT: stat/tasmota_5AF452/RESULT = {"RfSync":12440}
15:57:30.849 SRC: Backlog
15:57:30.852 CMD: Grp 0, Cmnd 'RFLOW', Idx 1, Len 3, Data '420'
15:57:30.857 MQT: stat/tasmota_5AF452/RESULT = {"RfLow":420}
15:57:31.099 SRC: Backlog
15:57:31.102 CMD: Grp 0, Cmnd 'RFHIGH', Idx 1, Len 4, Data '1210'
15:57:31.107 MQT: stat/tasmota_5AF452/RESULT = {"RfHigh":1210}
15:57:31.349 SRC: Backlog
15:57:31.352 CMD: Grp 0, Cmnd 'RFCODE', Idx 1, Len 7, Data '#B9D671'
15:57:31.364 MQT: stat/tasmota_5AF452/RESULT = {"RfCode":"#B9D671"}
15:57:31.602 SRC: Backlog
15:57:31.605 CMD: Grp 0, Cmnd 'RFKEY', Idx 1, Len 1, Data '4'
15:57:31.610 MQT: stat/tasmota_5AF452/RESULT = {"RfKey1":"Saved"}
15:57:31.835 CFG: Saved to flash at F8, Count 62, Bytes 4096
15:57:31.841 DMP: A0 55
15:57:35.211 DMP: A4 34 26 01 A4 04 D8 E5 24 2C 55
15:57:35.216 MQT: tele/tasmota_5AF452/RESULT = {"Time":"2021-12-09T15:57:35","RfReceived":{"Sync":13350,"Low":420,"High":1240,"Data":"E5242C","RfKey":"None"}}
15:57:37.011 WIF: Checking connection...
15:57:40.649 DMP: A4 2D DC 01 AE 04 CE 72 92 16 55
15:57:40.654 MQT: tele/tasmota_5AF452/RESULT = {"Time":"2021-12-09T15:57:40","RfReceived":{"Sync":11740,"Low":430,"High":1230,"Data":"729216","RfKey":"None"}}
15:57:42.356 CMD: RFKey1
15:57:42.358 SRC: WebConsole from 192.168.50.211
15:57:42.360 CMD: Grp 0, Cmnd 'RFKEY', Idx 1, Len 0, Data ''
15:57:42.373 MQT: stat/tasmota_5AF452/RESULT = {"RfKey1":"Learned sent"}

**Comment by atv2016** [comment]
i resolved this by saving the rfkey1 and sending it *after* i added a remote to the alarm panel. can be closed.

**Comment by DavideCenc** [comment]
> i resolved this by saving the rfkey1 and sending it _after_ i added a remote to the alarm panel. can be closed.

can you explain better, i have the same problem. thank you
