### ISSUE TITLE
Energytotal does not set total energy to correct value

### ISSUE THREAD

**Issue by stefanbode** [arendst/Tasmota#13989]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
If setting energytotal to 5000 and the today energy is already 1500 then the resulting total energy in teleinfo is 6500. Expectytion is that teleinfo reporting is 5000 on total energy.
Version 10.0.0

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
10:53:24.437 MQT: hm/status/ESP_029ACA/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"320":"Led_i1"},"GPIO4":{"2688":"HLW8012 CF"},"GPIO5":{"2656":"HLWBL CF1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"32":"Button1"},"GPIO14":{"2624":"HLWBL SEL_i"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
10:53:57.103 CMD: Grp 0, Cmnd 'RULE', Idx 1, Len 0, Data ''
10:53:57.110 MQT: hm/status/ESP_029ACA/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":38,"Free":473,"Rules":"ON tele-energy#power>50 savedata ENDON"}}
10:53:57.318 SRC: Backlog
10:53:57.320 CMD: Grp 0, Cmnd 'RULE', Idx 2, Len 0, Data ''
10:53:57.327 MQT: hm/status/ESP_029ACA/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
10:53:57.569 SRC: Backlog
10:53:57.572 CMD: Grp 0, Cmnd 'RULE', Idx 3, Len 0, Data ''
10:53:57.578 MQT: hm/status/ESP_029ACA/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
10:54:39.609 MQT: hm/status/ESP_029ACA/STATUS = {"Status":{"Module":0,"DeviceName":"MercedesWallbox","FriendlyName":["MercedesWallbox"],"Topic":"ESP_029ACA","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":60,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
10:54:39.617 MQT: hm/status/ESP_029ACA/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T15:19:05","StartupUTC":"2021-12-09T18:35:34","Sleep":50,"CfgHolder":4617,"BootCount":15,"BCResetTime":"2021-11-13T16:30:59","SaveCount":196,"SaveAddress":"FA000"}}
10:54:39.624 MQT: hm/status/ESP_029ACA/STATUS2 = {"StatusFWR":{"Version":"10.0.0(tasmota)","BuildDateTime":"2021-10-19T08:23:49","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"390/699"}}
10:54:39.630 MQT: hm/status/ESP_029ACA/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["BodeNet_Keller",""],"TelePeriod":30,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A0A000000000000","00000080","00006000","00004000"]}}
10:54:39.641 MQT: hm/status/ESP_029ACA/STATUS4 = {"StatusMEM":{"ProgramSize":612,"Free":388,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
10:54:39.649 MQT: hm/status/ESP_029ACA/STATUS5 = {"StatusNET":{"Hostname":"ESP-029ACA-6858","IPAddress":"192.168.178.183","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.178.1","DNSServer2":"0.0.0.0","Mac":"50:02:91:02:9A:CA","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
10:54:39.656 MQT: hm/status/ESP_029ACA/STATUS6 = {"StatusMQT":{"MqttHost":"elocm.synology.me","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_029ACA","MqttUser":"ESP_029ACA","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
10:54:39.663 MQT: hm/status/ESP_029ACA/STATUS7 = {"StatusTIM":{"UTC":"2021-12-10T09:54:39","Local":"2021-12-10T10:54:39","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:32","Sunset":"16:52"}}
10:54:39.668 MQT: hm/status/ESP_029ACA/STATUS9 = {"StatusPTH":{"PowerDelta":[150,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
10:54:39.676 MQT: hm/status/ESP_029ACA/STATUS10 = {"StatusSNS":{"Time":"2021-12-10T10:54:39","ENERGY":{"TotalStartTime":"2021-12-10T10:47:36","Total":60.608,"Yesterday":13.225,"Today":7.108,"Power": 0,"ApparentPower": 0,"ReactivePower": 0,"Factor":0.00,"Voltage":231,"Current":0.000}}}
10:54:39.682 MQT: hm/status/ESP_029ACA/STATUS11 = {"StatusSTS":{"Time":"2021-12-10T10:54:39","Uptime":"0T15:19:05","UptimeSec":55145,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"BodeNet_Keller","BSSId":"34:31:C4:E7:D9:75","Channel":6,"Mode":"11n","RSSI":38,"Signal":-81,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
10:55:42.784 WIF: Checking connection...
10:55:56.598 CMD: EnergyTotal 53500
10:55:56.600 SRC: WebConsole from 192.168.178.46
10:55:56.603 CMD: Grp 0, Cmnd 'ENERGYTOTAL', Idx 1, Len 5, Data '53500'
10:55:56.610 MQT: hm/status/ESP_029ACA/RESULT = {"EnergyTotal":{"Total":60.608,"Yesterday":13.225,"Today":7.108}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
What I see in the code of `xdrv_03_energy.ino` is that the routine `ResponseCmndEnergyTotalYesterdayToday` is called by the commands to reset energy counters, and the published *output* including data for today does not mean that the internally saved value includes today too. Implicitly, EnergyTotal is at start of "today", and I do not see it as unreasonable (albeit a bit confusing) that the consumption for today is included when reporting energy data.

**Comment by Jason2866** [comment]
Adding a explanation to the docs how it is designed would help.

**Comment by stefanbode** [comment]
MY proposal would be to substract the today value from the entered one and set it. In this case the result is as expected

**Comment by sfromis** [comment]
Subtracting would not work well, as that would make the stored value negative (not a good fit for unsigned integers), and if the next action then was to zero the today value, things would get weird.

**Comment by arendst** [comment]
Agree with @sfromis . Another issue here is that total energy is stored in flash at midnight and all energy today is just added to it until again midnight.

In short, it's as designed. Just look at it at another angle and it might make sense.

**Comment by sfromis** [comment]
Added a short explanation to the EnergyTotal command. Feel free to improve :-)

**Comment by Jason2866** [comment]
Answered from project owner.
