### ISSUE TITLE
Backlog in web request to get multiple values returns {}

### ISSUE THREAD

**Issue by nospam2k** [arendst/Tasmota#14049]
If I send http://192.168.0.94/cm?user=admin&password=pass&cmnd=Ssid1 I get back "{"SSId1":"ssid"}"
If I send http://ip/cm?user=admin&password=pass&cmnd=Backlog%20Ssid1%3bPassword1" I get back {}

Is there another way to get multiple values back in one web response? Using Tasmota 9.5.0?

**Comment by ascillato** [comment]
> Is there another way to get multiple values back in one web response?

No. You need to query them separately.

**Comment by nospam2k** [comment]
ok, thx
