### ISSUE TITLE
Latest Dev Build 10.1.0.1 crashes on "so73 1" and 6x button   

### ISSUE THREAD

**Issue by WhiteLionATX** [arendst/Tasmota#14058]
I ve compiled the latest tasmota build and did these changes:

user_config_override.h:
`#ifdef USE_SCRIPT_WEB_DISPLAY
  #undef USE_SCRIPT_WEB_DISPLAY
#endif
#define USE_SCRIPT_WEB_DISPLAY

#ifdef USE_BUTTON_EVENT
  #undef USE_BUTTON_EVENT
#endif
#define USE_BUTTON_EVENT

#ifdef USE_RULES
  #undef USE_RULES
#endif

#ifdef USE_SCRIPT
  #undef USE_SCRIPT
#endif
#define USE_SCRIPT
`
defined this: 
![image](https://user-images.githubusercontent.com/36136622/146206235-095ca5ca-4fbe-49fe-a46d-a6c9ebd260a9.png)

Entered into console: 
"so73 1"

Result:
Multi-button modes seems to work until you press it more than 5 times it will then lead to a crash.

**Comment by ascillato** [comment]
It is not a crash. You are triggering AP mode. Please, check the documentation at button multipress. You can disable this built in feature.
