### ISSUE TITLE
CAN Sniffer Sensor - Add to Tasmota

### ISSUE THREAD

**Issue by kwiatek6324** [arendst/Tasmota#14112]
Issue is a form of continuation for #7656

For my purpose i've created SENSOR based od mcp2515 and based on file xsns_87_mcp2515.ino
which for every incoming CAN packet will generate MQTT message, for example:

`/tasmota/stat/tasmota_xxxxxx/CAN {"ID":69,"LEN":5,"D0":255,"D1":71,"D2":0,"D3":0,"D4":119}`

Sending from mqtt to can will be also possible (hope in 1-2 days).

My questions are:

1. How to add this feature to official tasmota repo ?
2. If by pull request, how to get ID for XSNS (for my purposes , i took 120)

Regards

**Comment by pkkrusty** [comment]
@kwiatek6324 Did you ever complete this? Interested in the status of your work.
