### ISSUE TITLE
Flash Size to big if you want OTA upgrade to 10.1.0 with actual minimal.bin

### ISSUE THREAD

**Issue by laserrichi** [arendst/Tasmota#14138]
### PROBLEM DESCRIPTION

if you want to upgrade OTA with 10.1.0 tasmota-minimal.bin  to 10.1.0 10.1.0 tasmota-DE.bin
is not possible, not enough space for flashing.

### REQUESTED INFORMATION

size of tasmota-minimal.bin and tasmota-DE.bin are over 1024kb 

### TO REPRODUCE
the free Flash wit tasmota-DE.bin is 384 kB
the 10.1.0  tasmota-minimal.bin size is 395k  and its to large.
Use an older tasmota-minimal.bin with 380 kB  and it works

### SCREENSHOTS
no screenshot

**Comment by sfromis** [comment]
The only issue you have is that you are not using the `.bin.gz` binary. You should **always** use those for OTA, the `.bin` ones are basically only for initial flashing.

**Comment by Jason2866** [comment]
`tasmota-minimal.bin` is removed, since it is obsolete and `tasmota-minimal.bin.gz` has to be used always!
