### ISSUE TITLE
INA219 Power and Voltage only as integer

### ISSUE THREAD

**Issue by Radium78** [arendst/Tasmota#14142]
I've added the INA219 sensor to my NodeMCU with tasmota 10.1.0. It works fine, will be found by i2c scan but it shows only the current in float (3 decimals). Power an voltage is only shown as integers (no decimals).

The same issues are on firmware 9.3.1, seems not to be a firmware issue. And I've seen some pictures, where the INA219 sensors drops voltage and power values as floating number.

I've tested all breakout board with an arduino nano. Here i get 

Any ideas what's going wrong?

Here are some pictures...

That's what I can read from INA219 with an arduino nano:
![arduino-nano-test](https://user-images.githubusercontent.com/37036372/146991413-ed5d0e2d-eac2-402e-a90a-62abaecd6e9e.png)

That's what FHEM has recorded; voltages and power values are only integer steps:
![fhem-voltage-current-log](https://user-images.githubusercontent.com/37036372/146991447-d54ba2eb-b982-48be-adf7-338a4e1b22d5.png)

That's what I get on the webpage:
![tasmota-main-values](https://user-images.githubusercontent.com/37036372/146991469-e0369fcf-b71a-4b01-8d0c-641ee60d9583.png)

**Comment by barbudor** [comment]
https://tasmota.github.io/docs/Commands/#power-monitoring

VoltRes and the like are your friend

**Comment by Radium78** [comment]
Thanks... that's the missing info I need ;)
