### ISSUE TITLE
Rainsensor RG-15 driver not working

### ISSUE THREAD

**Issue by tremichl** [arendst/Tasmota#14159]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Sending data (rain detected) from Rainsensor to Tasmota results in crashing of Tasmota. Device isn't accessible anymore. After power reset same game again. For details please see [https://github.com/arendst/Tasmota/issues/14067]

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Wemos D1 mini
- [x] Tasmota binary firmware version number used: 10.1.0.1
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: Tasmotizer
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
14:47:54.763 MQT: stat/tasmota_4E80CA/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"288":"Led1"},"GPIO3":{"7424":"HRG15 Rx"},"GPIO4":{"0":"None"},"GPIO5":{"7392":"HRG15 Tx"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
14:45:48.669 MQT: stat/tasmota_4E80CA/STATUS = {"Status":{"Module":18,"DeviceName":"Rainsensor","FriendlyName":["Rainsensor"],"Topic":"tasmota_4E80CA","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
14:45:48.678 MQT: stat/tasmota_4E80CA/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T02:46:50","StartupUTC":"2021-12-23T10:58:58","Sleep":50,"CfgHolder":4617,"BootCount":14,"BCResetTime":"2021-12-22T17:40:37","SaveCount":30,"SaveAddress":"FA000"}}
14:45:48.683 MQT: stat/tasmota_4E80CA/STATUS2 = {"StatusFWR":{"Version":"10.1.0.1(TasmoCompiler-esp8266generic)","BuildDateTime":"2021-12-22T17:29:55","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"380/699"}}
14:45:48.688 MQT: stat/tasmota_4E80CA/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":4,"LogHost":"10.152.52.112","LogPort":514,"SSId":["TNet01","Recovery"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A000000000000","00000080","00006000","00004000"]}}
14:45:48.701 MQT: stat/tasmota_4E80CA/STATUS4 = {"StatusMEM":{"ProgramSize":529,"Free":472,"Heap":26,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F804582","04260001","00000003","00000000","C000E981","00000004","00001000","00001000"],"Drivers":"1,2,4,6,8,9,10,18,19,22,24,26,27,29,30,35,37,45","Sensors":"1,2,90"}}
14:45:48.711 MQT: stat/tasmota_4E80CA/STATUS5 = {"StatusNET":{"Hostname":"tasmota-4E80CA-0202","IPAddress":"10.152.52.24","Gateway":"10.152.52.254","Subnetmask":"255.255.255.0","DNSServer1":"10.152.52.254","DNSServer2":"0.0.0.0","Mac":"48:3F:DA:4E:80:CA","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
14:45:48.717 MQT: stat/tasmota_4E80CA/STATUS6 = {"StatusMQT":{"MqttHost":"10.152.52.111","MqttPort":1993,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4E80CA","MqttUser":"DVES_USER","MqttCount":2,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
14:45:48.724 MQT: stat/tasmota_4E80CA/STATUS7 = {"StatusTIM":{"UTC":"2021-12-23T13:45:48","Local":"2021-12-23T14:45:48","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:42","Sunset":"16:56"}}
14:45:48.731 MQT: stat/tasmota_4E80CA/STATUS10 = {"StatusSNS":{"Time":"2021-12-23T14:45:48","RG-15":{"Active":0.00,"Event":0.00,"Total":2.27,"FlowRate":0.00}}}
14:45:48.737 MQT: stat/tasmota_4E80CA/STATUS11 = {"StatusSTS":{"Time":"2021-12-23T14:45:48","Uptime":"0T02:46:50","UptimeSec":10010,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"Wifi":{"AP":1,"SSId":"TNet01","BSSId":"24:5A:4C:13:C1:D5","Channel":13,"Mode":"11n","RSSI":76,"Signal":-62,"LinkCount":2,"Downtime":"0T00:00:05"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Simulate Raindrops (serial data output of Sensor)

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
improved stability

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
 [https://github.com/arendst/Tasmota/issues/14067]

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
There is no need to open a new issue for the same problem. Let's continue in the original one.
