### ISSUE TITLE
CMD Dimmer executes wrong

### ISSUE THREAD

**Issue by BusinessClaes** [arendst/Tasmota#14250]
### PROBLEM DESCRIPTION
Command Dimmer with values 2 to 10 executes wrong and results in Dimmer 1 to 9 (one unit less than commanded)
Dimmer 1 executes right.
Dimmer 11 and higher executes right.
This happens in 10.1.0 but doesn’t happen in 10.0.0

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Shelly Dimmer 2
- [x] Tasmota binary firmware version number used: 10.1.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: yaourdt OTA update
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

18:35:00.541 CMD: Backlog Template; Module; GPIO 255
18:35:00.569 MQT: stat/TMT_D01/RESULT = {"NAME":"Shelly Dimmer 2","GPIO":[0,3200,0,3232,5568,5600,0,0,193,0,128,0,320,4736],"FLAG":0,"BASE":18}
18:35:00.777 MQT: stat/TMT_D01/RESULT = {"Module":{"0":"Shelly Dimmer 2"}}
18:35:00.992 MQT: stat/TMT_D01/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"3200":"Serial Tx"},"GPIO2":{"0":"None"},"GPIO3":{"3232":"Serial Rx"},"GPIO4":{"5568":"SHD Boot 0"},"GPIO5":{"5600":"SHD Reset"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"193":"Switch_n2"},"GPIO13":{"0":"None"},"GPIO14":{"128":"Button_in1"},"GPIO15":{"0":"None"},"GPIO16":{"320":"Led_i1"},"GPIO17":{"4736":"ADC Temp"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

18:40:20.022 CMD: Status 0
18:40:20.029 MQT: stat/TMT_D01/STATUS = {"Status":{"Module":0,"DeviceName":"TMT_D01","FriendlyName":["TMT_D01"],"Topic":"TMT_D01","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
18:40:20.064 MQT: stat/TMT_D01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:17:24","StartupUTC":"2022-01-03T17:22:56","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2022-01-02T13:30:49","SaveCount":82,"SaveAddress":"F4000"}}
18:40:20.099 MQT: stat/TMT_D01/STATUS2 = {"StatusFWR":{"Version":"10.1.0(tasmota)","BuildDateTime":"2021-12-08T14:47:33","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"382/699"}}
18:40:20.133 MQT: stat/TMT_D01/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["TF_IoT",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","0505C80001000600003C5A0A000000000000","00000080","00006000","00004000"]}}
18:40:20.175 MQT: stat/TMT_D01/STATUS4 = {"StatusMEM":{"ProgramSize":616,"Free":384,"Heap":23,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"15701C","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
18:40:20.213 MQT: stat/TMT_D01/STATUS5 = {"StatusNET":{"Hostname":"TMT-D01-6185","IPAddress":"20.20.20.9","Gateway":"20.20.20.1","Subnetmask":"255.255.255.0","DNSServer1":"20.20.20.1","DNSServer2":"0.0.0.0","Mac":"48:3F:DA:91:98:29","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
18:40:20.247 MQT: stat/TMT_D01/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.233","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_919829","MqttUser":"mqtt1","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
18:40:20.285 MQT: stat/TMT_D01/STATUS7 = {"StatusTIM":{"UTC":"2022-01-03T17:40:20","Local":"2022-01-03T18:40:20","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:43","Sunset":"17:05"}}
18:40:20.318 MQT: stat/TMT_D01/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
18:40:20.359 MQT: stat/TMT_D01/STATUS10 = {"StatusSNS":{"Time":"2022-01-03T18:40:20","Switch2":"OFF","ANALOG":{"Temperature":44.6},"ENERGY":{"TotalStartTime":"2022-01-02T13:30:49","Total":-20830.164,"Yesterday":0.001,"Today":0.002,"Power": 1,"ApparentPower": 1,"ReactivePower": 0,"Factor":1.00,"Voltage":232,"Current":0.004},"TempUnit":"C"}}
18:40:20.398 MQT: stat/TMT_D01/STATUS11 = {"StatusSTS":{"Time":"2022-01-03T18:40:20","Uptime":"0T00:17:24","UptimeSec":1044,"Heap":25,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"POWER":"ON","Dimmer":3,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"TF_IoT","BSSId":"26:5A:4C:23:E0:58","Channel":6,"Mode":"11n","RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

18:46:35.610 CMD: Weblog 4
18:46:35.616 MQT: stat/TMT_D01/RESULT = {"WebLog":4}
18:46:36.562 CFG: Saved to flash at F7, Count 87, Bytes 4096
18:46:40.067 CMD: Dimmer 4
18:46:40.069 SRC: WebConsole from 192.168.1.50
18:46:40.072 CMD: Grp 0, Cmnd 'DIMMER', Idx 1, Len 1, Data '4'
18:46:40.078 MQT: stat/TMT_D01/RESULT = {"POWER":"ON","Dimmer":3}
18:46:43.758 WIF: Checking connection...
18:46:47.930 CMD: Weblog 2
18:46:47.939 MQT: stat/TMT_D01/RESULT = {"WebLog":2}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
In console, writing command Dimmer 5 results in Dimmer 4.
Dimmer 11 gives Dimmer 11
Dimmer 2 to 10 gives 1 to 9

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Dimmer 2-10 should result in dimmer 2-10 :)

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
Two screenshots, same device. Just updated the device from 10.0.0 to 10.1.0 between screenshots.
![1EE52BD1-24C4-4256-84F4-D9FD5D86D18C](https://user-images.githubusercontent.com/79754463/147961631-74cfe4d9-aa87-485c-9805-0d55ffb77b4a.jpeg)
![7921DFD8-D61B-474F-9688-47AB05295B4D](https://user-images.githubusercontent.com/79754463/147961622-2c719f98-4b8f-436b-bd40-fd06799b8199.jpeg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

I thought that maybe Dimmerrange had something to do with rounding errors when scaling integer values, as pointed out by @sfromis but it doesn’t seem to be that. See the same issue appearing with different Dimmerrange settings

18:59:24.204 CMD: Dimmerrange
18:59:24.211 MQT: stat/TMT_D01/RESULT = {"DimmerRange":{"Min":48,"Max":100}}
18:59:31.678 CMD: Dimmer 5
18:59:31.685 MQT: stat/TMT_D01/RESULT = {"POWER":"ON","Dimmer":4}
18:59:42.532 CMD: Dimmerrange 0,100
18:59:42.539 MQT: stat/TMT_D01/RESULT = {"DimmerRange":{"Min":0,"Max":100}}
18:59:48.032 CMD: Dimmer 5
18:59:48.041 MQT: stat/TMT_D01/RESULT = {"POWER":"ON","Dimmer":4}
18:59:56.355 CMD: Dimmerrange 0,255
18:59:56.362 MQT: stat/TMT_D01/RESULT = {"DimmerRange":{"Min":0,"Max":255}}
19:00:00.386 CMD: Dimmer 5
19:00:00.394 MQT: stat/TMT_D01/RESULT = {"POWER":"ON","Dimmer":4}

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Due to rounding errors when scaling integer values, small deviation are entirely normal. May depend on the device or other details which you kept as a secret.

**Comment by BusinessClaes** [comment]
Sorry, I just wrote the fist post on the go while waiting in the car 😄

The device is a Shelly dimmer 2 and I have now tried to disclose as much details as possible, just tell me if I need to add some info.

In the screenshots that I’ve uploaded now you can see the problem after updating from 10.0.0 to 10.1.0 (same device, same settings, only firmware update between screenshots)

I have several Shelly dimmer 2 devices and this issue appears in all of them.

**Comment by Jason2866** [comment]
Try latest development version. There is a change with https://github.com/arendst/Tasmota/pull/14157

**Comment by BusinessClaes** [comment]
Latest development version solves the problem!
I’ll happily wait for next release. Thanks for this and for all the great work everyone does with tasmota.
Should I close the issue now or wait until release?

**Comment by Jason2866** [comment]
please close. thx
