### ISSUE TITLE
Configure Domoticz Button missing

### ISSUE THREAD

**Issue by dheuts90** [arendst/Tasmota#14314]
Good afternoon,

Today I flashed some LED bulbs with Tasmota, but the Configure Domoticz button is missing.
How to get it back? Thanks in advance!

![image](https://user-images.githubusercontent.com/53342865/148535401-f8692901-4d57-4edd-b8ad-b660f0f5c039.png)

**Comment by ascillato** [comment]
Flash latest Tasmota. Your version is too old.
