### ISSUE TITLE
Switching off WF-DS01 dimmer is not reliable

### ISSUE THREAD

**Issue by bigcookie** [arendst/Tasmota#14431]
### PROBLEM DESCRIPTION
I use this dimmer: https://templates.blakadder.com/WF-DS01.html
Until Tasmota 8 it worked fine if I recall correctly. Until updates to Tasmota 9, 10 and 2022.01.02, the following behavior SOMETIMES appear:
pre-condition: dimmer is turned on (full brightness)
1. You turn the dimmer off by using the middle touch button
2. Light dims down to zero and seems to be switched off
3. After 2-3 seconds light turns on to full brightness again automatically

This ONLY happens, when using the onboard controls (touch buttons) on the dimmer. It doenst happen, when using MQTT commands - at least I couldnt witness this issue.

Solution:
1. tap shortly the "dim low" button
2. Tap the "switch off" button
3. Light is being switched off and doesnt come on again automatically.

### REQUESTED INFORMATION
- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): WF-DS01
- [x] Tasmota binary firmware version number used: 2022.01.2
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Device Tasmota webpage
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
11:14:51.809 CMD: Backlog Template; Module; GPIO 255
11:14:51.848 MQT: licht_sz/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,4704],"FLAG":0,"BASE":18}
11:14:52.060 MQT: licht_sz/stat/RESULT = {"Module":{"54":"Tuya MCU"}}
11:14:52.316 MQT: licht_sz/stat/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"2272":"Tuya Tx"},"GPIO2":{"0":"None"},"GPIO3":{"2304":"Tuya Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"288":"Led1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
11:15:13.118 CMD: status 0
11:15:13.125 MQT: licht_sz/stat/STATUS = {"Status":{"Module":54,"DeviceName":"Schlafzimmer","FriendlyName":["Schlafzimmer"],"Topic":"licht_sz","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
11:15:13.132 MQT: licht_sz/stat/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://192.168.20.201:8180/data/firmwares/tasmota-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:40:25","StartupUTC":"2022-01-14T09:34:48","Sleep":50,"CfgHolder":4617,"BootCount":69,"BCResetTime":"2020-04-24T11:55:26","SaveCount":6079,"SaveAddress":"FB000"}}
11:15:13.137 MQT: licht_sz/stat/STATUS2 = {"StatusFWR":{"Version":"2022.01.2(tasmota)","BuildDateTime":"2022.01.14 08:29:05","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"448/699"}}
11:15:13.143 MQT: licht_sz/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["AndroLAN",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028009","2805C80001000600003C5AB0000000170700","00100280","00006000","00004000"]}}
11:15:13.156 MQT: licht_sz/stat/STATUS4 = {"StatusMEM":{"ProgramSize":618,"Free":384,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440C8","FlashFrequency":40,"FlashMode":3,"Features":["00000407","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
11:15:13.162 MQT: licht_sz/stat/STATUS5 = {"StatusNET":{"Hostname":"SH-Dimmer-SZ","IPAddress":"192.168.20.234","Gateway":"192.168.20.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.20.1","DNSServer2":"0.0.0.0","Mac":"EC:FA:BC:96:DB:9D","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
11:15:13.168 MQT: licht_sz/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.20.253","MqttPort":1883,"MqttClientMask":"licht_sz","MqttClient":"licht_sz","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
11:15:13.176 MQT: licht_sz/stat/STATUS7 = {"StatusTIM":{"UTC":"2022-01-14T10:15:13","Local":"2022-01-14T11:15:13","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:39","Sunset":"17:19"}}
11:15:13.183 MQT: licht_sz/stat/STATUS10 = {"StatusSNS":{"Time":"2022-01-14T11:15:13"}}
11:15:13.193 MQT: licht_sz/stat/STATUS11 = {"StatusSTS":{"Time":"2022-01-14T11:15:13","Uptime":"0T00:40:25","UptimeSec":2425,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Dimmer":72,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"AndroLAN","BSSId":"44:4E:6D:5F:22:03","Channel":13,"Mode":"11n","RSSI":100,"Signal":-47,"LinkCount":1,"Downtime":"0T00:00:05"}}}


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
unknown - happens randomly, but often enough to be annoying

### EXPECTED BEHAVIOUR
If I tap the middle button to switch off the light, while it is on, I expect the light to switch off and stay off. With the same button tap I could toggle it to "on" again.

### SCREENSHOTS
not applicable

### ADDITIONAL CONTEXT
not applicable

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Thanks for reporting. This problem is the same as reported in https://github.com/arendst/Tasmota/issues/14398

Your device has a TuyaMCU and the driver in Tasmota is no longer in active development. Please, check that issue for more information.
