### ISSUE TITLE
add docs for I2C HT16K33 based 7 segment LED

### ISSUE THREAD

**Issue by HarHarLinks** [arendst/Tasmota#14472]
PRs like #8116, #8900 seem to not have made it to the docs properly. See also https://github.com/arendst/Tasmota/discussions/14451

**Comment by HarHarLinks** [comment]
@arendst template makes no sense here

**Comment by barbudor** [comment]
@HarHarLinks 
Issue makes perfectly sense when raising for qualified bug or mis behavior.
Help should be asked in Discussion or in Discord

If you have something to say about docs, here is the place : https://github.com/tasmota/docs
The docs are open source and anyone is invited to collaborate and participate. You can easily create PR ffor the docs by clicking on the pencil button on the top right of the doc page.

Thanks for your collaboration.

**Comment by HarHarLinks** [comment]
thanks for pointing that out

**Comment by ascillato** [comment]
Link just for reference: https://github.com/tasmota/docs/issues/257
