### ISSUE TITLE
Support for BME688

### ISSUE THREAD

**Issue by muuuh** [arendst/Tasmota#14510]
Hello,

could you please add support for the Bosch BME688 sensor?

I'm using this https://www.adafruit.com/product/5046 sensor. It's reported as i2c 0x77. I'm not sure if the chip-id has changed for the BME688 https://github.com/arendst/Tasmota/blob/dba1f32c8220f21e256634dc6480a970ca71575a/tasmota/xsns_09_bmp.ino#L39

I've found some information here:
https://community.bosch-sensortec.com/t5/Knowledge-base/FAQs-BME688/ta-p/24822

Best regards,

**Comment by ascillato2** [comment]
Moving to Ideas since this is not a bug report.
