### ISSUE TITLE
Switching AP connections fails

### ISSUE THREAD

**Issue by dweston** [arendst/Tasmota#14528]
All attempts I have tested to enable switching a Tasmotarised device from one AP point to another is faiing. Try as I may attempting to achieve this by using the WiFi commands listed at:
https://tasmota.github.io/docs/Commands/#wi-fi
I cannot successfully manage to make a switch. An example of the resulting error I see in the logs is shown here:

`00:00:00.001 HDW: ESP8285
00:00:00.050 CFG: Loaded from flash at F8, Count 84
00:00:00.055 QPC: Count 1
00:00:00.065 Project tasmota - ms6107_2 Version 10.1.0(tasmota)-2_7_4_9(2021-12-08T14:47:33)
00:00:00.554 WIF: Connecting to AP2 xxxxxxxxxx Channel 1 BSSId 94:83:C4:03:BD:4C in mode 11n as ms6107-2...
00:00:06.979 QPC: Reset
00:00:09.381 WIF: Connect failed as AP cannot be reached
00:00:09.716 WIF: Connecting to AP1 yyyyyyyyyy in mode 11n as ms6107-2...
00:00:14.005 WIF: Connected
00:00:14.256 HTP: Web server active on ms6107-2 with IP address 10.0.1.xxx`

The only successful method I've been able to make work was to resort to using:
https://tasmota.github.io/docs/Device-Recovery/#fast-power-cycle-device-recoverych 
which seems an altogether inelegant, blunt instrument, approach to switching this critical parameter.

Please advise how I might trace the issue that would be causing the AP switch to fail.

**Comment by barbudor** [comment]
You don't give much details on what you are trying to achieve and what you've exactly done to reach it.
So I can see in your logs that Tasmota tries to connect to AP2 but it is obvioulsy not in range.
Enabling `Weblog 3` will provide you more details on which AP are in range
