### ISSUE TITLE
Zigbee part stops when MQTT server has slow start

### ISSUE THREAD

**Issue by pingel20** [arendst/Tasmota#14586]
### PROBLEM DESCRIPTION
My Pi (with MQTT server) and my eWeLink ZbBridge Pro Ethernet Zigbee Gateway (ZB-GW03-V1.2) are powered up at the same time.
Many times the MQTT server is not already running when Tasmota tries to connect.
After a second try Tasmota stops the Zigbee part (status 99), so no further Zigbee communiaction possible.

Is this intended behaviour or should Tasmota be given some more time to connect?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): eWeLink ZbBridge Pro Ethernet Zigbee Gateway
- [x] Tasmota binary firmware version number used: 2022.01.2
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua

00:00:00.002 HDW: ESP32-D0WDQ6-V3 
00:00:00.013 UFS: FlashFS mounted with 304 kB free
00:00:00.032 CFG: Loaded from File, Count 42
00:00:00.040 QPC: Count 1
00:00:00.076 BRY: Berry initialized, RAM used=3335
00:00:00.086 ZIG: ZBBridge EEPROM found at address 0x50
00:00:00.092 Project tasmota - Tasmota Version 2022.01.2(zig_bridge32)-2_0_2(2022-01-11T22:37:29)
00:00:01.578 ETH: Connected at 100Mbps Full Duplex
00:00:01.630 RSL: RESULT = {"ZbState":{"Status":1,"Message":"EFR32 booted","RestartReason":"Power-on","Code":2}}
00:00:01.637 ZIG: Resetting EZSP device
11:36:26.232 HTP: Web server active on tasmota-D0A570-1392-eth with IP address 192.168.178.25
11:36:27.229 MQT: Attempting connection...
11:36:30.235 MQT: Connect failed to 192.168.178.5:1883, rc -2. Retry in 10 sec
11:36:33.247 QPC: Reset
11:36:40.186 ZIG: Resetting EZSP device
11:36:41.489 RSL: RESULT = {"ZbState":{"Status":1,"Message":"EFR32 booted","RestartReason":"Power-on","Code":2}}
11:36:41.589 RSL: RESULT = {"ZbState":{"Status":55,"Version":"6.7.8.0","Protocol":8,"Stack":2}}
11:36:41.596 RSL: RESULT = {"ZbState":{"Status":3,"Message":"Configured, starting coordinator"}}
11:36:41.604 MQT: Attempting connection...
11:36:44.610 MQT: Connect failed to 192.168.178.5:1883, rc -2. Retry in 20 sec
11:36:44.616 ZIG: timeout, goto label 99
11:36:44.617 RSL: RESULT = {"ZbState":{"Status":99,"Message":"Abort"}}
11:36:44.623 ZIG: Abort
11:36:44.624 ZIG: Stopping (99)
11:37:05.428 MQT: Attempting connection...
11:37:05.436 MQT: Connected
11:37:05.439 MQT: tele/tasmota_D0A570/LWT = Online (retained)
11:37:05.443 MQT: cmnd/tasmota_D0A570/POWER = 
11:37:05.449 MQT: tele/tasmota_D0A570/INFO1 = {"Info1":{"Module":"ZB-GW03-V1.2","Version":"2022.01.2(zig_bridge32)","FallbackTopic":"cmnd/DVES_D0A570_fb/","GroupTopic":"cmnd/tasmotas/"}}
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
Give Tasmota some more time to connect to MQTT server

If the situation happens a 'restart 99' in the console (or Restart from the web interface) solves the problem.
The MQTT server is online by that time and Tasmota will connect at first try.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
This is not expected behavior. It seems that the connection to MQTT creates indirectly a timeout in the steps of initilization of Zigbee. This is an unfortunate race condition.

You could try reducing the MQTT timeout from 3 to 1 second using `MqttTimeout 1`

**Comment by pingel20** [comment]
MqttTimeout 1

Hmm...not really sure what this command does.
Shouldn't MQTT be given some more time, so perhaps MqttTimeout 20 or MqttTimeout  30 ?

Or do I have a misunderstanding?

**Comment by s-hadinger** [comment]
If you increase timeout it will make things worse. Bear in mind that Tasmota freezes during the timeout. I was more thinking of reducing the timeout to have a fail-fast and let the retry to be done later. Hopefully a pause of 1 second will not create a timeout in Zigbee.

**Comment by s-hadinger** [comment]
If it still does not work reliably, I can always increase all Zigbee timeouts to over 3 seconds. I would probably not harm.

**Comment by pingel20** [comment]
Since setting the MqttTimeout  value to 1 I powered up my system 5 times (once a day)
All 5 times the Zigbee part started correctly (no more status 99).

So this looks promising. I don't know if it's the ultimate solution, but for the moment it looks fine.

Thanks for the advice.

**Comment by pingel20** [comment]
The problem still exists.
I created a rule:
on zbstate#status==99 do backlog delay 100; restart 99 endon

So when Zigbee part does not start the rule kicks in and restarts the device after 10 seconds.
MQTT server will be up at that time.

**Comment by AkoSti0578** [comment]
Just update from latest 10 release to 11 release, things ar much better now. No more stopping zigbeezzz
