### ISSUE TITLE
Tasmota crashes on ESP8266 and won't power on anymore

### ISSUE THREAD

**Issue by Chriz02** [arendst/Tasmota#14720]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Hello,

I have got a problem with tasmota and SWA1 Module. After flashing tasmota.bin with tasmotizer and sending my wifi config and template Generic I'm able to go to WebUI. Now I config IO Pins and go to console to set pulsetime.
If the relay is switched on it will switch and tasmota will crash and not power on anymore. It's even enough to wait some minutes and tasmota will also crash. After reflashing the ESP it will power on again and I repeat from beginning. Testes on two SWA1 and also have got a third one which can be tested.

Can anyone help me?

Thanks!

Regards
Chris

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): Lingan SWA1
- [ x] Tasmota binary firmware version number used: 10.1.0
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ x] Flashing tools used: Tasmotizer
- [ x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
GOIP4 LED 1
GPIO Relay 1
GPIO13 Button_i 1

```
- [ x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
 Pulsetime 120

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
14:14:16.451 CMD: Status 0
14:14:16.456 RSL: STATUS = {"Status":{"Module":18,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_77D870","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
14:14:16.482 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:00:39","StartupUTC":"2022-02-04T13:13:37","Sleep":50,"CfgHolder":4617,"BootCount":3,"BCResetTime":"2022-02-04T14:12:06","SaveCount":10,"SaveAddress":"FA000"}}
14:14:16.514 RSL: STATUS2 = {"StatusFWR":{"Version":"10.1.0(tasmota)","BuildDateTime":"2021-12-08T14:47:33","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"360/699"}}
14:14:16.534 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Heimnetz",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A000000000000","00000080","00006000","00004000"]}}
14:14:16.564 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":616,"Free":384,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
14:14:16.593 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-77D870-6256","IPAddress":"192.168.200.54","Gateway":"192.168.200.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.200.1","DNSServer2":"0.0.0.0","Mac":"60:01:94:77:D8:70","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
14:14:16.618 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_77D870","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
14:14:16.640 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-02-04T13:14:16","Local":"2022-02-04T14:14:16","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:16","Sunset":"17:51"}}
14:14:16.658 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-02-04T14:14:16"}}
14:14:16.665 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-02-04T14:14:16","Uptime":"0T00:00:39","UptimeSec":39,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Heimnetz","BSSId":"F0:B0:14:23:CA:A2","Channel":11,"Mode":"11n","RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:03"}}}
14:14:24.013 RSL: RESULT = {"Reset":"Reset and Restarting"}
14:14:24.790 CFG: Use defaults
14:14:25.527 RSL: RESULT = {"POWER":"OFF"}
14:14:25.530 RSL: POWER = OFF

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Install Tasmota on a new SWA1, config the three GPIO, set pulstime to anytime you want, and switch on. Wait until time is 0 and tasmota will crash and not start anymore.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
A fix, that tasmota won't crash

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
not possible

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
```
14:14:16.665 ....
14:14:24.013 RSL: RESULT = {"Reset":"Reset and Restarting"}
```
40 seconds means that a pin configured as Button is registering as "pushed". Stop doing that, or do not config as "Button_i".

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
