### ISSUE TITLE
PG04-UK16A-TAS  not powering ON/OFF

### ISSUE THREAD

**Issue by jcdutton** [arendst/Tasmota#14735]
Hi,

When you switch on the Tasmota device for the first time, it acts as a Wifi Access point.
You can connect to it with a web browser and then ask for it to connect to your Wifi.
You cannot power on/off the device from this web interface.
How do I add a feature for it to power on/off from this mode?
Use case:
My Wifi access point is in a difficult to reach location. I would like to remotely power on/off the Wfii Access point using a PG04-UK16A-TAS, but if the Tasmota has to be connected to my Wifi Access point for me to reach it, I will be able to turn it off, but then the Wifi Access point will have no power, so I cannot turn it back on again.
If I could turn the PG04-UK16A-TAS ON/OFF with the PG04-UK16A-TAS acting as its own Wifi Access point, the above use case would work.

**Comment by barbudor** [comment]
_Github Issues are not meant for requiring help but only to report qualified bugs.
For Help please use the Discussion forum or Discord server_

While Tasmota is not meant to be operated from a self AP mode but only connected to a WLAN, you can check the WifiConfig command.
`WifiConfig 2` will allow Tasmota to go back to the configuration mode with it's own AP in case of loosing connection to your WLAN IP.
Although it will not present a web page with the ON/OFF button in that mode, you can still directly go to the  console page by entering `http://192.168.4.1/cs?` in your browser and enter the POWER ON command

Note that to customize the AP name and its password you must build your own firmware.
