### ISSUE TITLE
PG04-UK16A-TAS ON/OFF will not power ON/OFF

### ISSUE THREAD

**Issue by jcdutton** [arendst/Tasmota#14736]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Hi,

When you switch on the Tasmota device for the first time, it acts as a Wifi Access point.
You can connect to it with a web browser and then ask for it to connect to your Wifi.
You cannot power on/off the device from this web interface.
How do I add a feature for it to power on/off from this mode?
Use case:
My Wifi access point is in a difficult to reach location. I would like to remotely power on/off the Wfii Access point using a PG04-UK16A-TAS, but if the Tasmota has to be connected to my Wifi Access point for me to reach it, I will be able to turn it off, but then the Wifi Access point will have no power, so I cannot turn it back on again.
If I could turn the PG04-UK16A-TAS ON/OFF with the PG04-UK16A-TAS acting as its own Wifi Access point, the above use case would work.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
none

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
none

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
none

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Power on/off should work.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
Do not open 2 Issues for the same question, especially if it is for asking for help
Please close this issue
I have provided an answer on your original issue
