### ISSUE TITLE
Compilation fails on 10.1+ when using ST7789 display driver

### ISSUE THREAD

**Issue by jvitkauskas** [arendst/Tasmota#14754]
### PROBLEM DESCRIPTION
Compilation fails on 10.1+ when using ST7789 display driver

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Generic ESP32
- [X] Tasmota binary firmware version number used: latest development or 10.1.0 (no issue in 10.0.0)
  - [ ] Pre-compiled
  - [X] Self-compiled
- [ ] Flashing tools used: none
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Compile with `#define USE_DISPLAY_ST7789` and get this compiler error:

```
/tmp/Tasmota/tasmota/xdsp_12_ST7789.ino: In function 'void ST7789_InitDriver()':
/tmp/Tasmota/tasmota/xdsp_12_ST7789.ino:121:37: error: call of overloaded 'begin(int, int, int)' is ambiguous
     Wire1.begin(SDA_2, SCL_2, 400000);
```

### EXPECTED BEHAVIOUR
Compilation finishes successfully

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Thx.

Caused by bad library https://github.com/espressif/arduino-esp32/issues/6180

I will add the suggested workaround.
