### ISSUE TITLE
No cmnd outputs

### ISSUE THREAD

**Issue by haze1986** [arendst/Tasmota#14771]
Hi, I've just flashed tasmota on 7 of the Sonoff-like wall switches. On 2 out of the 7 I could not enable output of cmnd/tasmota…/ when I toggle the switches. I ensured the settings are the exact same on all 7 switches. One of them is a 1gang and the other is 3gang. Please confirm if this is a bug or I'm missing something.

**Comment by barbudor** [comment]
you are probably missing something

With zero details provided, don't expect an answer with anything valuable
The Issue template is there for a reason
