### ISSUE TITLE
Scripter "break" doesn't exit section anymore

### ISSUE THREAD

**Issue by RedBlackThunder** [arendst/Tasmota#14830]
### PROBLEM DESCRIPTION
After update to version 11.0.0 the scripter command "break" doesn't exit section anymore. So following commands gets executed.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): many, tested SonOff Touch and multiple Gosund devices
- [ ] Tasmota binary firmware version number used: 11.0.0
  - [ ] Pre-compiled
  - [X] Self-compiled
- [X Flashing tools used: ota upgrade
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
- [ ] Provide the output of this command: `Status 0`:
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:

### TO REPRODUCE
Use "break" to exit a section

### EXPECTED BEHAVIOUR
exit of section.

**Comment by gemu2015** [comment]
please post a script that shows this behavior

since it works with this simple script (print is not executed) 

\>D
\>B
\>S
break
print test

**Comment by RedBlackThunder** [comment]
`if upd[F]>0
or upd[P]>0
or upd[N]>0
or chg[S]>0
or chg[W]>0
or upd[WT]>0 {
  if F=="true" {
    =>ShutterPosition 100
    break
  }
  if (P=="false" and W>0) {
    =>ShutterPosition 0
    break
  }
  if (P=="true" and N=="false" and W==2) {
    =>ShutterPosition 100
    break
  }
  if (N=="true" or S==0) {
    =>ShutterPosition 0
    break
  }
  if S==1 {
    if WT>32 {
      =>ShutterPosition 0
    }
    if WT<32
    and WT>28 {
      =>ShutterPosition 30
    }
    if WT<28
    and WT>24 {
      =>ShutterPosition 50
    }
    if WT<24 {
      =>ShutterPosition 100
    }
  }
}
`

But also much simpler code failed. Everything in >F and inside of an if clause.

**Comment by RedBlackThunder** [comment]
Thx for pointing the issuer with the brackets out. Wasn't aware, that this was really for every condition, even the simple one. Luckily it worked all the time.

Simplest example for the break issuer:
```
>F
if P=="true" {
  =>print Case1
  break
}

if P=="true" {
  =>print Case2
  break
}  
```
In my understanding, if P=="true" Case2, should never get executed, but I can see in the console both gets executed.

**Comment by sfromis** [comment]
I do not know much about scripting, but all the examples have no leading spaces on each line. Did you try this way?

**Comment by gemu2015** [comment]
strange finding but i could reproduce the bug. happens only in >F ???
this was an inherent bug, i wonder why it did not show up in earlier versions.
here is the fix, please try and report.

[xdrv_10_scripter.ino.zip](https://github.com/arendst/Tasmota/files/8066452/xdrv_10_scripter.ino.zip)

**Comment by RedBlackThunder** [comment]
I had to remove the struct SCRIPT_SPI, to compile it with 11.0.0, but the bug seems to be fixed. Now break in >F works again. Thx a lot for your support and work!
