### ISSUE TITLE
Initial wifi setup does not work in 10.1.x (stable and dev) with Sonoff Basic R2

### ISSUE THREAD

**Issue by w4tsn** [arendst/Tasmota#14848]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

On my Sonoff Basic R2 I observe that Wifi does not connect to my 2.4GHz network with latest release 10.1 and development binaries 10.1.0.8 of `tasmota.bin`. It does work however with 9.1 stable historic release.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Basic R2
- [x] Tasmota binary firmware version number used: 10.1.0.8; 9.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: esptool.py
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
11:33:40 MQT: stat/tasmota_6B24F8/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
11:33:40 MQT: stat/tasmota_6B24F8/RESULT = {"Module":{"1":"Sonoff Basic"}}
11:33:40 MQT: stat/tasmota_6B24F8/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
11:34:10 MQT: stat/tasmota_6B24F8/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_6B24F8","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Power On","Uptime":"1T19:26:37","StartupUTC":"2022-02-12T15:07:33","Sleep":50,"CfgHolder":4617,"BootCount":6,"BCResetTime":"2022-02-12T15:25:25","SaveCount":21,"SaveAddress":"F7000"}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS2 = {"StatusFWR":{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"374/699"}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Hertie Kunden-WLAN",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS4 = {"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS5 = {"StatusNET":{"Hostname":"tasmota_6B24F8-1272","IPAddress":"192.168.2.25","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"80:7D:3A:6B:24:F8","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.42","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_6B24F8","MqttUser":"DVES_USER","MqttCount":3,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS7 = {"StatusTIM":{"UTC":"2022-02-14T10:34:10","Local":"2022-02-14T11:34:10","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:00","Sunset":"18:08"}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS10 = {"StatusSNS":{"Time":"2022-02-14T11:34:10"}}
11:34:10 MQT: stat/tasmota_6B24F8/STATUS11 = {"StatusSTS":{"Time":"2022-02-14T11:34:10","Uptime":"1T19:26:37","UptimeSec":156397,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Hertie Kunden-WLAN","BSSId":"9C:C7:A6:18:C3:17","Channel":6,"RSSI":92,"Signal":-54,"LinkCount":3,"Downtime":"0T00:02:21"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

The problem occurs on the initial setup page where I only may enter wifi credentials so I can't access the console to get logs when the problem occurs.

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Clear flash storage
2. Flash 10.1.x firmware according to the documentation using esptool.py onto a Sonoff Basic R2
3. Start the device and use the configuration UI to set correct SSID and password

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

The device successfully connects to the WLAN.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Search for Sonoff Basic R2 issues. You will find a lot.
In short it is a crappy revision of the Sonoff Basic. You can try Tasmota-lite version.
If this version does not work too. Trash it.
