### ISSUE TITLE
sonoff B1 v2 flickering and brightness reset to one in the middle of the range

### ISSUE THREAD

**Issue by damocles-dev** [arendst/Tasmota#14962]
### PROBLEM DESCRIPTION

Changing values in cold/warm light channels causes severe flickering when fading is enabled on sonoff B1 v2 (RGBWW) light bulbs. Color channels are not affected.

This flicker is easily reproducible because changing the dimmer value in cold/warm channels from 1 to 100 at value 50 the bright starts again as if it were at the value 1.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff B1 v2
- [X] Tasmota binary firmware version number used: Version 11.0.0(tasmota)-2_7_4_9(2022-02-12T14:13:50)
  - [X] Pre-compiled
  - [ ] Self-compiled
- [X] Flashing tools used: OTA
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
13:32:57.411 MQT: casa/b1-03/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
13:32:57.610 MQT: casa/b1-03/stat/RESULT = {"Module":{"26":"Sonoff B1"}}
13:32:57.817 MQT: casa/b1-03/stat/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"3008":"MY92x1 DI"},"GPIO13":{"0":"None"},"GPIO14":{"3040":"MY92x1 DCKI"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
```
- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
13:33:53.927 MQT: casa/b1-03/stat/RESULT = {"Rule1":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
13:33:54.129 MQT: casa/b1-03/stat/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
13:33:54.335 MQT: casa/b1-03/stat/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
```
- [X] Provide the output of this command: `Status 0`:
```lua
13:34:56.993 MQT: casa/b1-03/stat/STATUS = {"Status":{"Module":26,"DeviceName":"b1-03","FriendlyName":["b1-03"],"Topic":"b1-03","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
13:34:56.000 MQT: casa/b1-03/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:34:44","StartupUTC":"2022-02-24T12:00:12","Sleep":1,"CfgHolder":4617,"BootCount":27,"BCResetTime":"2021-05-17T20:42:02","SaveCount":4548,"SaveAddress":"F4000"}}
13:34:57.000 MQT: casa/b1-03/stat/STATUS2 = {"StatusFWR":{"Version":"11.0.0(tasmota)","BuildDateTime":"2022-02-12T14:13:50","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"386/699"}}
13:34:57.005 MQT: casa/b1-03/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":2,"LogHost":"10.20.30.7","LogPort":514,"SSId":["olimpo","olimpo2"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028009","2805C80001000600003C5A0A000000000000","00000080","00006200","00004000"]}}
13:34:57.017 MQT: casa/b1-03/stat/STATUS4 = {"StatusMEM":{"ProgramSize":620,"Free":380,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
13:34:57.025 MQT: casa/b1-03/stat/STATUS5 = {"StatusNET":{"Hostname":"b1-03","IPAddress":"10.20.30.141","Gateway":"10.20.30.6","Subnetmask":"255.255.255.0","DNSServer1":"10.20.30.1","DNSServer2":"0.0.0.0","Mac":"60:01:94:B4:51:31","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
13:34:57.030 MQT: casa/b1-03/stat/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.olimpo","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_B45131","MqttUser":"b1-03","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
13:34:57.036 MQT: casa/b1-03/stat/STATUS7 = {"StatusTIM":{"UTC":"2022-02-24T12:34:57","Local":"2022-02-24T13:34:57","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"07:41","Sunset":"18:24"}}
13:34:57.041 MQT: casa/b1-03/stat/STATUS10 = {"StatusSNS":{"Time":"2022-02-24T13:34:57"}}
13:34:57.049 MQT: casa/b1-03/stat/STATUS11 = {"StatusSTS":{"Time":"2022-02-24T13:34:57","Uptime":"0T00:34:45","UptimeSec":2085,"Heap":22,"SleepMode":"Dynamic","Sleep":1,"LoadAvg":999,"MqttCount":1,"POWER":"ON","Dimmer":50,"Color":"0,0,0,0,128","HSBColor":"0,0,0","White":50,"CT":500,"Channel":[0,0,0,0,50],"Scheme":0,"Fade":"ON","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"olimpo","BSSId":"D4:EE:07:61:AC:86","Channel":6,"Mode":"11n","RSSI":100,"Signal":-34,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [X] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
13:35:35.898 CMD: weblog 4
13:35:35.904 MQT: casa/b1-03/stat/RESULT = {"WebLog":4}
13:35:36.542 CFG: Saved to flash at FB, Count 4549, Bytes 4096
13:35:42.246 CMD: dimmer 49
13:35:42.248 SRC: WebConsole from 10.20.30.10
13:35:42.250 CMD: Grp 0, Cmnd 'DIMMER', Idx 1, Len 2, Data '49'
13:35:42.258 MQT: casa/b1-03/stat/RESULT = {"POWER":"ON","Dimmer":49,"Color":"0,0,0,0,125","HSBColor":"0,0,0","White":49,"CT":500,"Channel":[0,0,0,0,49]}
13:35:43.541 CFG: Saved to flash at FA, Count 4550, Bytes 4096
13:35:50.270 CMD: dimmer 50
13:35:50.272 SRC: WebConsole from 10.20.30.10
13:35:50.275 CMD: Grp 0, Cmnd 'DIMMER', Idx 1, Len 2, Data '50'
13:35:50.282 MQT: casa/b1-03/stat/RESULT = {"POWER":"ON","Dimmer":50,"Color":"0,0,0,0,128","HSBColor":"0,0,0","White":50,"CT":500,"Channel":[0,0,0,0,50]}
13:35:51.541 CFG: Saved to flash at F9, Count 4551, Bytes 4096
```

### TO REPRODUCE
test 1: enable fading on cold/warm channels causes flickering when dimmer values are changed
test 2: change the dimmer value from 49 to 50 and the brightness goes to 1, so you get two complete brightness cycles in the 1..100 range.

### EXPECTED BEHAVIOUR
no flickering with cold/warm light changes

### ADDITIONAL CONTEXT
this could be related to:
[PWM Dimmer start 2 times causing some flicker at start](https://github.com/arendst/Tasmota/issues/8423)
[9.1 Sonoff B1 flickering](https://github.com/arendst/Tasmota/issues/9966)

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by damocles-dev** [comment]
Perhaps it could be that the flickering on fading may be due to crossing the middle of the range at a higher speed to achieve the effect causing the brightness to start from 1 a second time and it is perceived as flickering.

**Comment by Uksa007** [comment]
Same similar issue with sonoff B1, with fade enabled it seems to cycle through different colour temperatures, eg warm then cold then white if you set the speed slower you can see the changes. 

Do I need to open a new issue or can we use this one?
