### ISSUE TITLE
[Feature Request] PowerDelta enhancement

### ISSUE THREAD

**Issue by muhkuhgh** [arendst/Tasmota#14967]
If I get it right, PowerDelta at the moment works like that:

PowerDelta 104 => Every 4 watt difference will be reported.

That means 

If we start on 100
105 - report
120 - report
117
114
111
108 and so on..
no report other than on telemetry period...

I think it could be very helpful, to have the differences accumulated... and not barely checked on every reported Power Value.. Because in most of the cases I guess changes of my desired PowerDelta in like a certain amount of time are also verry interesting.. 

**So like**
PowerDelta 104

We start on 100.
106 - report. Keep that 106 in mind.
107 - +1 no report alone.
108 - +1=+2 no report alone.
109 - +1=+3 no report alone.
110 - +1=+4 no report alone but seen from the last report we've seen an increase of our desired PowerDelta so we send an Report.

This should be farily easy to implement.. We just need two more variables, one to store the latest reported value and one to sum up differences on every new power value.. then one simple if routine to check the the difference of our accumulated differences minus our last reported value  and that absolute value against our desired powerdelta (maybe PowerDeltaAcc)

I have many use cases, where the generation/load slow increases in decreases.. but I don't want to send/store every single watt change.. but i neither want to wait telemetry period of time to get reported of above shown example :D

**Comment by ascillato** [comment]
Just for reference, this thread is at: https://github.com/arendst/Tasmota/discussions/14969
