### ISSUE TITLE
opensource without politics

### ISSUE THREAD

**Issue by mikesrus** [arendst/Tasmota#15024]
### Discussed in https://github.com/arendst/Tasmota/discussions/15023

<div type='discussions-op-text'>

<sup>Originally posted by **mikesrus** March  3, 2022</sup>
I see some limitations in future versions (unless of course the old ones are rebilded) according to
https://github.com/arendst/Tasmota/commit/98cbf2587a1a914bbd16996ebb48dd451d3da448

open source software is therefore called so, because it is available (openly) to everyone without restrictions.

Probably now it is fashionable to build an "iron curtain" in front of the Russian Federation. But by such actions you describe yourself as a developer.

Who will trust the software (especially for embedded devices that are connected to electricity) that can stop working/become unusable/cause a fire/ because something has gone wrong in the world.

What's next? is there a bomb? attempts to cause epilepsy by blinking light? restrictions for everyone who doesn't play Cold War 2.0?

Who now wants to put a compiled binary file if there are similar traps there.

Please don't do this.</div>

**Comment by AgentFire** [comment]
I totally agree with the proposal.

In a nutshell, this is pure racism. And it is directed versus people, 99.99% of which has no choice in the geopolitical matter.

## And it goes without saying that this is highly unprofessional.
