### ISSUE TITLE
AHT25 shows up as VEML6070

### ISSUE THREAD

**Issue by woutervddn** [arendst/Tasmota#15072]
### PROBLEM DESCRIPTION
I got my hands on an AHT25, which I thought was supported. However upon connecting the Tasmota homescreen gave me UV readings for VEML6070.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): NodeMCU
- [ x] Tasmota binary firmware version number used: 11.0.0
  - [ ] Pre-compiled
  - [ x] Self-compiled
- [ x] Flashing tools used: tasmocompiler
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Attach AHT25 and flash firmware with AHT support

### EXPECTED BEHAVIOUR
I see a temperature instead of UV values

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
I'm not sure that AHT25 is supported as I see nothing in the code that confirm it or not

However AHT devices and VEML6070 are using the same I2C address
In most of the cases, an I2Cdriver cannot properly assess that the chip that respond to an expected address is actually the right chip. So it is recommended to disable any I2Cdriver that you don't need.
To disable AHT driver : `I2CDriver12 0`
If your build also include driver USE_DISPLAY_ILI9488 or USE_DISPLAY_RA8876, you should also disable them (`i2CDriver38 0` and `I2CDriver39 0`)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
