### ISSUE TITLE
Upgrade from 5.14 to 6.7.1 does not work

### ISSUE THREAD

**Issue by jayjupdhig** [arendst/Tasmota#15144]
https://tasmota.github.io/docs/Upgrading/#gz-binaries

Get a "buffer miscompare" error when i load http://ota.tasmota.com/tasmota/release-6.7.1/sonoff.bin to a Sonoff with:

![image](https://user-images.githubusercontent.com/42765391/158376100-af307221-a568-46b1-82b1-6674fa2751ee.png)

HERE:

![image](https://user-images.githubusercontent.com/42765391/158376294-936c4987-02d1-43a0-b44b-a4879ca6637a.png)

THEN...

![image](https://user-images.githubusercontent.com/42765391/158376328-2b2ee87c-7764-4a1d-b1ff-81632781eb16.png)

(WTF...)

What you write here seems to be wrong!!

![image](https://user-images.githubusercontent.com/42765391/158376169-ff43ad5a-4a67-4123-98b4-c35319dcaee5.png)

Why that!?

Thx for feedback,
Jan

**Comment by jayjupdhig** [comment]
...

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by jayjupdhig** [comment]
Your link on https://tasmota.github.io/docs/Upgrading/#gz-binaries seems to be wrong... on the chat somebody told me i need minimal- or (???) basic- of Tasmota 6.7.1.bin file...

But which one now - "minimal" or "basic" ?? 

![image](https://user-images.githubusercontent.com/42765391/158380517-78b79e56-ea86-4255-9aaa-e45f3c7bf4d6.png)

**Comment by jayjupdhig** [comment]
After installing 6.7.1-basic, both of my devices are destroyed... only to recover with RS-232 which makes no sense for a price for 5-7 dollar...

**Comment by jayjupdhig** [comment]
It was just a reset to factory default - so i didin't put them into the trash. (Sry. i was a lil bit stressed - due to many technical problem in the same moment)
