### ISSUE TITLE
Toggle Name

### ISSUE THREAD

**Issue by crestani-federico** [arendst/Tasmota#15201]
Hi everybody,
I have a question for you: Can I change the name "Toggle 1" , "Toggle 2" , "Toggle 3" , "Toggle 4" on the WebUI interface (web interface) of my Sonoff 4ch PRO with firmware Tasmota 11.0 ?

I tried from the console with "WebButton<4>TEST" but the Toggle 4 doesn't change the name.

Can somebody help me??

Thank youuuuuu very much 😊

**Comment by ascillato** [comment]
The correct syntax is `WebButton4 TEST`.

**Comment by crestani-federico** [comment]
Thank you sooooo much 😊 
Federico Crestani
