### ISSUE TITLE
404 error on 'needed files'

### ISSUE THREAD

**Issue by blacknell** [arendst/Tasmota#15247]
### PROBLEM DESCRIPTION
The [Needed Files](https://github.com/arendst/Tasmota/tree/firmware/firmware/tasmota32/ESP32_needed_files) are not in the linked folder as outlined on [Tasmota documentation](https://templates.blakadder.com/sonoff_DUALR3_v2.html)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X ] Device used (e.g., Sonoff Basic): Sonoff DUALR3v2
- [ ] Tasmota binary firmware version number used: 11.0
  - [ X] Pre-compiled
  - [ ] Self-compiled
- [X ] Flashing tools used: esptool
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
The Tasmota Templates repo you linked is outdated, since the flashing procedure has been simplified. There is now a single file firmware (xxx.factory.bin) for easy initial flashing. **The prefered recommended way is using our [WebInstaller](https://tasmota.github.io/install/)**
You can help us to keep all Doc Sites up to date. You can open a PR by simply clicking the button `EDIT ON GITHUB`
