### ISSUE TITLE
MQTT rc-2

### ISSUE THREAD

**Issue by Tom618s** [arendst/Tasmota#15379]
Está tendo um probleminha na conexão ao MQTT nas versões mais recentes do Tasmota
![Screenshot_2022-04-10-13-35-42-875_com android chrome](https://user-images.githubusercontent.com/95147431/163655394-6c4cc733-c174-4cb8-ad31-76a7b5a1524c.jpg)
Não consegui saber ao certo qual o problema, mas uma solução é instalar a versão mais antiga 9.1 ou anterior

**Comment by devjva** [comment]
estou com o mesmo problema, funciona local mas na nuvem não funciona

**Comment by Tom618s** [comment]
Hello, I managed to fix this problem by placing the command: MqttWifiTimeout 1000
