### ISSUE TITLE
This is a feature request

### ISSUE THREAD

**Issue by GaryMilne** [arendst/Tasmota#15497]
Hi, Tasmota currently allows storage in either var or mem types. My request is to have some form of variable that persists across rules but does not require writing to NVRAM.  What is a use case?

Consider these two rules. 
**Version #1**
_ON Tele-Energy#Current DO var13 %value% ENDON
ON Tele-Energy#Power DO var14 %value% ENDON "
ON Tele-Energy#Voltage DO backlog ; webquery http://192.168.0.200:39501 POST {'TSync':'True','Current':'%var13%','Watts':'%var14%','Voltage':'%value%'} ENDON_

Basically sends some JSON to the host at whatever the TELEPERIOD is, whether the data has changed or not i.e. all zero's. Not ideal from a POV of network usage and host activity and logging.

**Version #2**
_ON Tele-Energy#Current DO backlog0 Mem11 %value% ; RuleTimer1 1 ENDON
ON Tele-Energy#Voltage DO backlog0 Mem12 %value% ; RuleTimer1 1 ENDON
ON Tele-Energy#Power DO backlog0 Mem13 %value% ; RuleTimer1 1 ENDON
ON Rules#Timer=1 DO Mem15 %Mem10%,%Mem11%,%Mem12%,%Mem13% ENDON
ON Mem15#State\$!%Mem16% DO backlog ; Mem16 %Mem15% ; webquery http://192.168.0.200:39501 POST {'TasmotaSync':'True','%Mem10%','Current':'%Mem11%','Voltage':'%Mem12%','Watts':'%Mem13%'} ENDON_

In this case the net result is that Tasmota only sends changes to the host whenever one of the three values has changed since the last period. Slightly more processing but greatly advantageous in terms of reducing network traffic and events at the host because only changes are sent.  However, the considerable downside is that with a TelePeriod of 60 seconds you would have 60 (events) x 24 (hours) x 5 (mem variables) = **7,200 mem writes per day**.  That would start killing off memory cells within a few days and obviously a non-starter.

The availability of a couple of semi-persistent in memory registers %pvar% would greatly enhance what is capable of achieving with rules within the stock compilation.

Thanks for listening.

**Comment by sfromis** [comment]
Post feature requests in Discussions, "Ideas", not as Issues. Much easier than getting whacked due to not filling in the template. Anyway, Var already does what you ask for, as these are shared among rules, and only erased in case of a restart.
