### ISSUE TITLE
SetOption103 not sticking

### ISSUE THREAD

**Issue by jpadie** [arendst/Tasmota#15559]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

setoption103 0 should disable the use of TLS for mqtt connection.  as should unticking the checkbox in the UI.
after reboot the setting remains.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): ESP32 WRover moudle_____
- [ ] Tasmota binary firmware version number used: 11.1.0
  - [ ] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: Visual Studio Code
- [ X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
5:15:05.045 RSL: RESULT = {"NAME":"ESP32-DevKit","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
15:15:05.262 RSL: RESULT = {"Module":{"1":"ESP32-DevKit"}}
15:15:05.527 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"192":"Switch_n1"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"224":"Relay1"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here: not using rules


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"lightbox","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
15:15:58.369 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T00:13:16","StartupUTC":"2022-05-06T14:02:42","Sleep":50,"CfgHolder":4617,"BootCount":26,"BCResetTime":"2022-05-06T09:33:05","SaveCount":72}}
15:15:58.382 RSL: STATUS2 = {"StatusFWR":{"Version":"11.1.0(tasmota)","BuildDateTime":"2022-04-13T06:40:58","Core":"2_0_3","SDK":"v.4.4.0","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6","CR":"421/699"}}
15:15:58.391 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Gaia-Rabastens-Free",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A190000000000","00008080","00206000","00004000"]}}
15:15:58.425 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":1394,"Free":1856,"Heap":143,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","9FDAC7CF","0015A001","B7F7BFCF","05DA9BC0","E0360DC7","400840D2","20200000","0434482D"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,56,59,62,82,86","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,127"}}
15:15:58.445 RSL: STATUS5 = {"StatusNET":{"Hostname":"lightbox-5116","IPAddress":"192.168.0.48","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.0.1","DNSServer2":"0.0.0.0","Mac":"3C:61:05:2A:F3:FC","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"0.0.0.0","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00"},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
15:15:58.461 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.****.co.uk","MqttPort":8883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2AF3FC","MqttUser":"****","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:15:58.473 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-05-06T14:15:58","Local":"2022-05-06T15:15:58","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"05:21","Sunset":"20:11"}}
15:15:58.490 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-05-06T15:15:58","Switch1":"ON","ESP32":{"Temperature":53.3},"TempUnit":"C"}}
15:15:58.502 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-05-06T15:15:58","Uptime":"0T00:13:16","UptimeSec":796,"Heap":145,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Berry":{"HeapUsed":3,"Objects":40},"POWER":"OFF","Wifi":{"AP":1,"SSId":"Gaia-Rabastens-Free","BSSId":"6C:61:F4:00:2D:26","Channel":1,"Mode":"11n","RSSI":36,"Signal":-82,"LinkCount":1,"Downtime":"0T00:00:05"}}}
15:16:02.293
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


15:17:18.520 CMD: weblog 4
15:17:18.526 RSL: RESULT = {"WebLog":4}
15:17:19.195 CFG: Saved, Count 73, Bytes 4096
15:17:29.025 WIF: Checking connection...
15:17:33.883 CMD: setoption103 0
15:17:33.886 SRC: WebConsole from 192.168.0.27
15:17:33.890 CMD: Grp 0, Cmd 'SETOPTION', Idx 103, Len 1, Pld 0, Data '0'
15:17:33.897 RSL: RESULT = {"SetOption103":"OFF"}

// WAIT FOR REBOOT

00:00:00.002 HDW: ESP32-D0WDQ6 
00:00:00.003 HDW: FoundPSRAM=0 CanUsePSRAM=0
00:00:00.102 UFS: FlashFS mounted with 304 kB free
00:00:00.194 CFG: Loaded from File, Count 74
00:00:00.199 CFG: CR 421/699, Busy 0
00:00:00.205 ROT: Mode 1
00:00:00.218 BRY: GC from 3683 to 3051 bytes, objects freed 5/22 (in 0 ms) - slots from 34/61 to 23/61
00:00:00.430 CFG: No '*.autoconf' file found
00:00:00.436 BRY: GC from 4404 to 3715 bytes, objects freed 5/38 (in 1 ms) - slots from 54/76 to 35/76
00:00:00.436 BRY: Berry initialized, RAM used=3715 bytes
00:00:00.460 BRY: No 'preinit.be'
00:00:00.464 SRC: Restart
00:00:00.471 Project tasmota - Tasmota Version 11.1.0(tasmota)-2_0_3(2022-04-13T06:40:58)
00:00:00.472 ETH: No ETH MDC and/or ETH MDIO GPIO defined
00:00:00.650 BRY: No 'autoexec.be'
00:00:00.173 CFG: Saved, Count 75, Bytes 4096
00:00:01.340 WIF: Checking connection...
00:00:01.341 WIF: Attempting connection...
00:00:01.888 WIF: Connecting to AP1 Gaia-Rabastens-Free Channel 1 BSSId 6C:61:F4:00:2D:26 in mode 11n as lightbox-5116...
00:00:04.483 WIF: Checking connection...
00:00:04.484 WIF: Attempting connection...
00:00:05.484 WIF: Checking connection...
00:00:05.485 WIF: Connected
00:00:05.697 HTP: Web server active on lightbox-5116 with IP address 192.168.0.48
00:00:05.736 NTP: Sync time...
00:00:05.815 RTC: UTC 2022-05-06T14:17:42, DST 2022-03-27T02:00:00, STD 2022-10-30T03:00:00
15:17:42.001 RTC: Synced by NTP
15:17:43.721 MQT: Attempting connection...
15:17:43.822 MQT: TLS connection error: 0
15:17:43.824 MQT: Connect failed to mqtt.no3.co.uk:8883, rc -2. Retry in 10 sec
15:17:47.715 APP: Boot Count 27
15:17:48.716 CFG: Saved, Count 76, Bytes 4096
15:17:55.750 MQT: Attempting connection...
15:17:55.844 MQT: TLS connection error: 0
15:17:55.846 MQT: Connect failed to mqtt.no3.co.uk:8883, rc -2. Retry in 20 sec

15:19:15.254 CMD: SETOPTION103
15:19:15.256 SRC: WebConsole from 192.168.0.27
15:19:15.258 CMD: Grp 0, Cmd 'SETOPTION', Idx 103, Len 0, Pld -99, Data ''
15:19:15.261 RSL: RESULT = {"SetOption103":"ON"}
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

open console
setoption103 0
//wait for reboot
setoption103
//reports on

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

the value of setoption103 should stick to survive reboot.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
Using port 8883 automatically sets TLS whatever the value of SetOption103. This is to avoid any mistake. 

Looking at the logs, the TLS connection is successful but error -2 indicates a Mqtt error. 

What makes you think that the connection over port 8883 does not use TLS?

**Comment by jpadie** [comment]
>>>What makes you think that the connection over port 8883 does not use TLS?

it's my server and I don't use TLS on that port.  a deliberate design choice from a number of years ago. 

the server logs indicate protocol error.  Given that I have many dozens of tasmota and other devices using the pubsubclient without issue I deduce that the problem is with the sticky TLS.  

 >>Using port 8883 automatically sets TLS whatever the value of SetOption103. This is to avoid any mistake.

this is a concerning design decision.  for me at least.  I will have an uncomfortable decision between not upgrading the tasmota versions in scope via the pre-compiled versions, changing server ports (which would affect hundreds of devices across multiple environments or some other solution that I have not thought of just yet.

**Comment by s-hadinger** [comment]
This design decision was meant for ESP8266 devices. Previous versions were either TLS or non-TLS, now all ESP32 variants include TLS and rely on SetOption103. It's very difficult in the code to know if SO103 is off because of a recent update or because it was manually disabled.

I suppose that I can drop this behavior on ESP32 only, since there are very few migration path issues. I'm more reluctant when it comes to ESP8266. Are your devices all ESP32?

**Comment by jpadie** [comment]
I have a mixture of ESP32 homebrew devices and a few dozen tasmotized sonoffs.  

looks like I will have to abandon the pre-compiled firmware upgrade route then.  Does the latest version still accept accept 8883 as a valid port if TLS support is not compiled?

**Comment by Jason2866** [comment]
You could use a rule at start to set so103 to off. 
I am reluctant too to change the safe guard to use TLS for port 8883.

**Comment by jpadie** [comment]
So103 causes a reboot.   If it is set in a rule does that bypass the reboot?From my side I am reluctant to add a rule to my entire supported estate to override a design decision in the core.  It would be more sense to make a permanent fork from the base code unfortunately. On 6 May 2022 20:55, Jason2866 ***@***.***> wrote:
You could use a rule at start to set so103 to off.
I am reluctant too to change the safe guard to use TLS for port 8883.

**Comment by s-hadinger** [comment]
Let me look tomorrow if I can move the TLS auto-detect to happen only when upgrading from an old version

**Comment by s-hadinger** [comment]
This is now fixed, you can disable TLS for port 8883
