### ISSUE TITLE
Script : Math operator ^ not work ?

### ISSUE THREAD

**Issue by Boxbox99** [arendst/Tasmota#15786]
Hello,
i use tasmota 11.1.0 with scripting support.
I want to use the math operator ^ in a script. It is not working, the result is only the first operator.
Here is my test case:

Script:
>D`
T=0
>S
T=10^0.56
print %T%

Result (Console):
20:14:09.378 10.00

Have i used it wrong or is it an issue?

Best regard
Bernd

**Comment by sfromis** [comment]
Do not try to open an "issue" when you just have questions about how to make it work, discussions are a better place for that, or the Discord server. Not using scripting, but the docs suggest that you need to use the function `pow(x y)` if you want exponentiation. Beware that it is really bad as a general function for that, it calculates 2 to the power of 2 as 3.88.
