### ISSUE TITLE
sunrise/sunset time in "Timer" section swapped

### ISSUE THREAD

**Issue by steinthomas** [arendst/Tasmota#15816]
### PROBLEM DESCRIPTION
The sunrise ("Sonnenaufgang") and sunset ("Sonnenuntergang") time in the "timer" section in v12.0.0 is swapped and displayed wrong.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: 12.0.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
screenshot
![tasmota_timer](https://user-images.githubusercontent.com/67026687/174304982-4a70ae49-9fd1-4f14-8c61-fe1ae813a180.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Not seeing that with version 12. What are your settings for TimeDST/TimeSTD/Timezone?
![image](https://user-images.githubusercontent.com/47082390/174309741-98149042-57c3-41e9-af45-5dd29ad5c029.png)

**Comment by barbudor** [comment]
I would bet your Tasmota doesn't get a proper time from NTP server
Check in the console that the logs have the expect date and time

**Comment by sfromis** [comment]
Saw that there may be an issue with DNS lookup for NTP/MQTT domain names, maybe this is the case here....

**Comment by barbudor** [comment]
Was getting to the same conclusion as I when using a name for the server, I don't get time. Works fine with IP address (which is my default setup)

**Comment by arendst** [comment]
I'll do a re-release today onve I verified the solution.

**Comment by Jason2866** [comment]
related to #15809

**Comment by steinthomas** [comment]
THX!!! Problem fixed...sunrise/sunset time now correct...
![tasmota_timer_fixed](https://user-images.githubusercontent.com/67026687/174329410-d57f0de2-f996-4c4c-81e3-5d6e2b9ba49a.jpg)
.
