### ISSUE TITLE
TasmotaGlobal.temperature_celsius includes ESP32 core temperature --> wrong compensation for Sensores

### ISSUE THREAD

**Issue by Links2004** [arendst/Tasmota#15834]
### PROBLEM DESCRIPTION

`TasmotaGlobal.temperature_celsius` includes `ESP32 Temperature` resulting in wrong compensation for Sensores.

for example the Absolute Humidity calculated here:

https://github.com/arendst/Tasmota/blob/c08561f67c722556655da7b8cbe1482d98aecd90/tasmota/tasmota_xsns_sensor/xsns_21_sgp30.ino#L86-L90

jumps from 8.8 g/m3 to 32.9 g/m3 and back, based on if the ESP32 Temperature where used or the connected Temperature sensor.
since there is a big difference in Temperature.

```
ESP32-DevKit
Air Sensor
MQ-2	1.02 ppm
MQ-3	null ppm
MQ-6	876.90 ppm
MQ-7	0.18 ppm
BME280 Temperature	24.0 °C
BME280 Humidity	36.6 %
BME280 Dew point	8.2 °C
BME280 Pressure	994.8 hPa
MHZ19B Carbon dioxide	410 ppm
MHZ19B Temperature	26.0 °C
SGP30 eCO₂	400 ppm
SGP30 TVOC	0 ppb
SGP30 Abs Humidity	35.2803 g/m3
ESP32 Temperature	52.8 °C
```

I found https://github.com/arendst/Tasmota/issues/12630 but my firmware is form this year.

tested with 
```
Program Version	11.1.0.3(tasmota)
Build Date & Time	2022-05-31T15:54:53
```
and
```
Program Version	12.0.1.2(tasmota)
Build Date & Time	2022-06-20T13:26:23
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): ESP32-DevKit
- [ ] Tasmota binary firmware version number used: 12.0.1.2(tasmota) 
  - [ ] Pre-compiled
  - [X] Self-compiled from master
- [X] Flashing tools used: VScode (PlatformIO) and update via Web Page
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
12:33:53.181 MQT: stat/tasmota_14FBDC/RESULT = {"NAME":"Sonoff Dual R3 v2","GPIO":[32,0,0,0,0,0,0,0,0,576,225,0,0,0,0,0,0,0,0,0,0,3200,8128,224,0,0,0,0,160,161,0,0,0,0,0,0],"FLAG":0,"BASE":1}
12:33:53.383 MQT: stat/tasmota_14FBDC/RESULT = {"Module":{"1":"ESP32-DevKit"}}
12:33:53.606 MQT: stat/tasmota_14FBDC/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"544":"LedLink"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"1376":"WS28121"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"1440":"MHZ Rx"},"GPIO17":{"1408":"MHZ Tx"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"640":"I2C SDA1"},"GPIO22":{"608":"I2C SCL1"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"8546":"ADC MQ3"},"GPIO35":{"8547":"ADC MQ4"},"GPIO36":{"8544":"ADC MQ1"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"8545":"ADC MQ2"}}
12:34:01.481 MQT: tele/tasmota_14FBDC/STATE = {"Time":"2022-06-20T12:34:01","Uptime":"0T00:04:11","UptimeSec":251,"Heap":150,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":40},"POWER":"ON","Dimmer":79,"Color":"0000C8","HSBColor":"240,100,79","Channel":[0,0,79],"Scheme":0,"Width":1,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"x","BSSId":"x","Channel":1,"Mode":"11n","RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:04"}}
12:34:01.545 MQT: tele/tasmota_14FBDC/SENSOR = {"Time":"2022-06-20T12:34:01","ANALOG":{"MQ2_1":1.02,"MQ3_2":null,"MQ6_3":858.16,"MQ7_4":0.17},"BME280":{"Temperature":23.9,"Humidity":36.6,"DewPoint":8.1,"Pressure":995.2},"MHZ19B":{"Model":"B","CarbonDioxide":418,"Temperature":26.0},"SGP30":{"eCO2":419,"TVOC":0,"aHumidity":7.7963},"ESP32":{"Temperature":52.8},"PressureUnit":"hPa","TempUnit":"C"}
12:34:01.652 MQT: stat/tasmota_14FBDC/RESULT = {"POWER":"ON","Dimmer":79,"Color":"0000C8","HSBColor":"240,100,79","Channel":[0,0,79]}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
12:34:41.472 CMD: Backlog Rule1; Rule2; Rule3
12:34:41.516 MQT: stat/tasmota_14FBDC/RESULT = {"Rule1":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
12:34:41.722 MQT: stat/tasmota_14FBDC/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
12:34:41.928 MQT: stat/tasmota_14FBDC/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
12:35:03.078 CMD: Status 0
12:35:03.092 MQT: stat/tasmota_14FBDC/STATUS = {"Status":{"Module":1,"DeviceName":"Air Sensor","FriendlyName":["Air Sensor"],"Topic":"tasmota_14FBDC","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
12:35:03.135 MQT: stat/tasmota_14FBDC/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T00:05:13","StartupUTC":"2022-06-20T11:29:50","Sleep":50,"CfgHolder":4617,"BootCount":31,"BCResetTime":"2022-05-28T10:56:33","SaveCount":162}}
12:35:03.178 MQT: stat/tasmota_14FBDC/STATUS2 = {"StatusFWR":{"Version":"12.0.1.2(tasmota)","BuildDateTime":"2022-06-20T13:26:23","Core":"2_0_3","SDK":"v4.4.1","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6 rev.1","CR":"549/699"}}
12:35:03.200 MQT: stat/tasmota_14FBDC/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["x",""],"TelePeriod":30,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A190000000000","00000080","00006000","00004000","00000000"]}}
12:35:03.252 MQT: stat/tasmota_14FBDC/STATUS4 = {"StatusMEM":{"ProgramSize":1399,"Free":1480,"Heap":146,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","9F8AC7CF","0015A001","B7F7BFCF","05DA9BC2","E0370DC7","401840D2","20200000","1434482D","00000000"],"Drivers":"1,2,3,4,5,8,9,10,11,12,14,16,17,20,21,24,26,27,29,31,34,35,38,50,52,59,62,82,86","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,30,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,75,85,92,95,127"}}
12:35:03.318 MQT: stat/tasmota_14FBDC/STATUS5 = {"StatusNET":{"Hostname":"tasmota-14FBDC-7132","IPAddress":"10.11.200.4","Gateway":"10.11.0.1","Subnetmask":"255.255.0.0","DNSServer1":"10.22.2.102","DNSServer2":"10.22.2.104","Mac":"3C:61:05:14:FB:DC","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"0.0.0.0","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00"},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
12:35:03.361 MQT: stat/tasmota_14FBDC/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.iot.ext.k8s.lan.sattlerit.de","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_14FBDC","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
12:35:03.392 MQT: stat/tasmota_14FBDC/STATUS7 = {"StatusTIM":{"UTC":"2022-06-20T11:35:03","Local":"2022-06-20T12:35:03","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:56"}}
12:35:03.427 MQT: stat/tasmota_14FBDC/STATUS10 = {"StatusSNS":{"Time":"2022-06-20T12:35:03","ANALOG":{"MQ2_1":1.03,"MQ3_2":null,"MQ6_3":858.28,"MQ7_4":0.17},"BME280":{"Temperature":23.9,"Humidity":36.3,"DewPoint":8.0,"Pressure":995.2},"MHZ19B":{"Model":"B","CarbonDioxide":426,"Temperature":26.0},"SGP30":{"eCO2":811,"TVOC":333,"aHumidity":7.7791},"ESP32":{"Temperature":53.3},"PressureUnit":"hPa","TempUnit":"C"}}
12:35:03.476 MQT: stat/tasmota_14FBDC/STATUS11 = {"StatusSTS":{"Time":"2022-06-20T12:35:03","Uptime":"0T00:05:13","UptimeSec":313,"Heap":147,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":40},"POWER":"ON","Dimmer":79,"Color":"0000C8","HSBColor":"240,100,79","Channel":[0,0,79],"Scheme":0,"Width":1,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"y","BSSId":"y","Channel":1,"Mode":"11n","RSSI":86,"Signal":-57,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE

use anything that uses `TasmotaGlobal.temperature_celsius` with the ESP32

### EXPECTED BEHAVIOUR

ESP32 temperature is not included in `TasmotaGlobal.temperature_celsius`

### SCREENSHOTS

![image](https://user-images.githubusercontent.com/974709/174592611-133bb87d-c500-4c15-9af3-db277231ae54.png)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Disable ESP32 temperature with command ``setsensor127 0``

**Comment by Links2004** [comment]
yes this works a a workaround. 
But not everyone will notice this so excluding it from `TasmotaGlobal.temperature_celsius` sounds like a good idea.

**Comment by arendst** [comment]
What works for you doesn't work for energy monitoring devices using the single present temp sensor to monitor overtemp.

So just execute the above command and you're good to go.

**Comment by sfromis** [comment]
Anyway, that ESP32 Temperature cannot generally be expected to have any relationship to reality, like actual chip temperature. May depend on chip variant.

**Comment by Links2004** [comment]
yes the MHZ19B shows to high temperatures too.
Resulting in the same problem with the ESP32 but less extrem in the Abs Humidity calculation.
the bad part is that is practically random which temperature is stored in `TasmotaGlobal`.
I ended up adding some defines to disable the Global update.
if you like I can open a PR.

It where unexpected to find that the `Convert` functions are updating the `TasmotaGlobal`, 
but I added a optional parameter to disable the update for `ConvertTemp`.

```diff
diff --git a/tasmota/tasmota_support/support.ino b/tasmota/tasmota_support/support.ino
index 0cb2d6af2..a1d5dac64 100755
--- a/tasmota/tasmota_support/support.ino
+++ b/tasmota/tasmota_support/support.ino
@@ -756,8 +756,10 @@ void UpdateGlobalTemperature(float c) {
   TasmotaGlobal.temperature_celsius = c;
 }
 
-float ConvertTemp(float c) {
-  UpdateGlobalTemperature(c);
+float ConvertTemp(float c, bool update = true) {
+  if (update) {
+    UpdateGlobalTemperature(c);
+  }
 
   return ConvertTempToFahrenheit(c);
 }
diff --git a/tasmota/tasmota_xsns_sensor/xsns_127_esp32_sensors.ino b/tasmota/tasmota_xsns_sensor/xsns_127_esp32_sensors.ino
index 8ac2ee7f6..b7559307b 100644
--- a/tasmota/tasmota_xsns_sensor/xsns_127_esp32_sensors.ino
+++ b/tasmota/tasmota_xsns_sensor/xsns_127_esp32_sensors.ino
@@ -61,9 +61,11 @@ void Esp32SensorShow(bool json) {
     add_global_temp = !ResponseContains_P(PSTR(D_JSON_TEMPERATURE));
   }
   float c = CpuTemperature();  // in Celsius
+#ifndef ESP32_SENSORS_TEMP_NO_GLOBAL
   if (add_global_temp) {
     UpdateGlobalTemperature(c);
   }
+#endif
   float t = ConvertTempToFahrenheit(c);
 
 #if CONFIG_IDF_TARGET_ESP32
diff --git a/tasmota/tasmota_xsns_sensor/xsns_15_mhz19.ino b/tasmota/tasmota_xsns_sensor/xsns_15_mhz19.ino
index 67745ddb4..2d61cd9fd 100644
--- a/tasmota/tasmota_xsns_sensor/xsns_15_mhz19.ino
+++ b/tasmota/tasmota_xsns_sensor/xsns_15_mhz19.ino
@@ -17,6 +17,7 @@
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
+
 #ifdef USE_MHZ19
 /*********************************************************************************************\
  * MH-Z19 - CO2 sensor
@@ -225,7 +226,11 @@ void MhzEverySecond(void)
       }
     } else {
       uint16_t ppm = (mhz_response[2] << 8) | mhz_response[3];
+#ifdef USE_MHZ19_TEMP_NO_GLOBAL
+      mhz_temperature = ConvertTemp((float)mhz_response[4] - 40, false);
+#else
       mhz_temperature = ConvertTemp((float)mhz_response[4] - 40);
+#endif
       uint8_t s = mhz_response[5];
       mhz_type = (s) ? 1 : 2;
       if (MhzCheckAndApplyFilter(ppm, s)) {
```

**Comment by arendst** [comment]
Thx for you input.

Now consider the fact that there are many more calls to ConvertTemp. I challenge you to come up with a solution workable for all of them, not just the ones you feel you need, and small code change without many #defines but on the fly control.

**Comment by Links2004** [comment]
If I think big with full config options, I propose:

1. remove the global update from all the `Convert` functions (its misleading naming in my opinion)
2. add a new function to do the global update that includes the ID of the sensor
3. add settings for all the different global values to set which sensor ID to use (and use this in combination with the ID parameter of the function)

May have the old behavior (no filtering) as default aka setting ID as 0
and if ID setting > 0 then only allow this sensor for this global parameter.

with this this will be flexible for any use case, and the User has full control during runtime.
but i am currently not familiar enough to say how to do this in the code base or how easy it is.

**Comment by arendst** [comment]
I'll sit and think about a solution for user selection of global temperature/humidity/pressure selection.

**Comment by Links2004** [comment]
with two assumptions this sounds fin for me use case

- the order in the JSON never changes (only when new sensors are added its ok)
- all sensors use the same key ("Temperature", "Humidity", ..... ) , so no sensor where other or similar names are used.

but the 300 sec Teleperiod default sounds to high for the over temperature use case we had in a earlier discussion.

**Comment by arendst** [comment]
- The order is mostly OK.
- The names are Tasmota standardized.
- Overtemp is an issue if it rises quick within a minute (if I decide to poll the sensors more often separated from teleperiod).

I'll implement this as an option to the current situation and see what the future brings.

Thx so far.

**Comment by Links2004** [comment]
Firmware updated and used:
```
GlobalTemp2 1
GlobalHum2 1
GlobalPress2 1
```

first look at the web interface is good, no jumping there.
will let it run a bit and check my Grafana to see it over time.

**Comment by Links2004** [comment]
looks like that the current implementation has some race condition 
![image](https://user-images.githubusercontent.com/974709/175653763-d227b096-b822-4bdb-b3bf-fa20b16f41ac.png)

**Comment by Links2004** [comment]
did some dissecting and the breaking change is the 10sec update, but no idea how to fix it.

```diff
diff --git a/tasmota/tasmota_support/support_tasmota.ino b/tasmota/tasmota_support/support_tasmota.ino
index 9c70c4890..18694c0e9 100644
--- a/tasmota/tasmota_support/support_tasmota.ino
+++ b/tasmota/tasmota_support/support_tasmota.ino
@@ -1086,7 +1086,7 @@ void PerformEverySecond(void)
   if (!(TasmotaGlobal.uptime % 10)) {
     for (uint32_t type = 0; type < 3; type++) {
       if (!Settings->global_sensor_index[type] || TasmotaGlobal.user_globals[type]) { continue; }
-      GetSensorValues();
+      //GetSensorValues();
       break;
     }
   }
```

**Comment by arendst** [comment]
I'm out the next days.

Now that you have commented out the 10 minute update global values will only be updated at teleperiod time. From your status 0 output it is set to 30 seconds which is ok as then it will use the global values from 30 seconds ago for the SGP calculation.

When I'm back I'll try to think of a more teleperiod synced approach but in your case (having already a small teleperiod set) it wouldn't make it must better.

**Comment by Links2004** [comment]
yes for my configuration the teleperiod update all 30sec is fin, since its only monitoring.

**Comment by Jason2866** [comment]
Closing, feature has been added
