### ISSUE TITLE
WEB BUTTONS FOR SHUTTER 2 NO WORKING IN 4CH DEVICE

### ISSUE THREAD

**Issue by cyberdomotik** [arendst/Tasmota#15847]
### PROBLEM DESCRIPTION
With SetOption80 1, shutter1 and their web buttons with up/down symbol are enabled. We get shutter 2 by "ShutterRelay2 1" but i can`t assign web buttons 3 and 4 for this new shutter.
 
### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): ESP-01 with 4 output relays
- [X] Tasmota binary firmware version number used: 12.0.2
  - [] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: Tasmotizer
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
= {"NAME":"LC-Tech_4CH ","GPIO":[288,1,32,1,0,0,0,0,224,225,226,227,0,0],"FLAG":0,"BASE":18}
= {"Module":{"0":"LC-Tech_4CH "}}
 = {"GPIO0":{"288":"Led1"},"GPIO1":{"0":"None"},"GPIO2":{"32":"Button1"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"225":"Relay2"},"GPIO14":{"226":"Relay3"},"GPIO15":{"227":"Relay4"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
 = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":383,"Free":128,"Rules":"on Power1#State=1 do SerialSend5 A00101A2 endon on Power1#State=0 do SerialSend5 A00100A1 endon on Power2#State=1 do SerialSend5 A00201A3 endon on Power2#State=0 do SerialSend5 A00200A2 endon on Power3#State=1 do SerialSend5 A00301A4 endon on Power3#State=0 do SerialSend5 A00300A3 endon on Power4#State=1 do SerialSend5 A00401A5 endon on Power4#State=0 do SerialSend5 A00400A4 endon"}}

```
- [X] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
= {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota","","",""],"Topic":"tasmota_166A19","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"LedMask":"FFFF","SaveData":0,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
02:08:28.818 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T02:23:07","StartupUTC":"2022-06-22T21:45:21","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2022-06-22T08:57:26","SaveCount":58,"SaveAddress":"F6000"}}
02:08:28.846 RSL: STATUS2 = {"StatusFWR":{"Version":"12.0.2(tasmota)","BuildDateTime":"2022-06-20T12:41:03","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"347/699"}}
02:08:28.872 RSL: STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ASUS_AX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00C0C009","2805C80001000600003C5A0A000000000000","40000080","00006000","00004000","00000000"]}}
02:08:28.905 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":619,"Free":384,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","14000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
02:08:28.934 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-166A19-2585","IPAddress":"192.168.1.107","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"98:CD:AC:16:6A:19","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
02:08:28.960 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_166A19","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
02:08:28.987 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-06-23T00:08:28","Local":"2022-06-23T02:08:28","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+02:00","Sunrise":"05:47","Sunset":"21:57"}}
02:08:29.026 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-06-23T02:08:29","Shutter1":{"Position":100,"Direction":0,"Target":100,"Tilt":0},"Shutter2":{"Position":30,"Direction":0,"Target":30,"Tilt":0}}}
02:08:29.054 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-06-23T02:08:29","Uptime":"0T02:23:08","UptimeSec":8588,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"ASUS_AX","BSSId":"7C:10:C9:2B:29:F0","Channel":9,"Mode":"11n","RSSI":94,"Signal":-53,"LinkCount":1,"Downtime":"0T00:04:28"}}}
02:08:29.084 RSL: STATUS13 = {"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":100,"Close":100,"50perc":50,"Delay":0,"Opt":"0000","Calib":[300,500,700,900,1000],"Mode":"1"},"SHT1":{"Relay1":1,"Relay2":2,"Open":100,"Close":100,"50perc":50,"Delay":0,"Opt":"1000","Calib":[300,500,700,900,1000],"Mode":"1"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Web buttons 3 and 4 cannot be assigned to shutter 2. They remain as independent outputs for relays 3 and 4.
By acting on the shutter 2 control bar, activates relays 1 and 2, which are associated with shutter 1.

### EXPECTED BEHAVIOUR
Web buttons 3 and 4 should be automatically assigned to shutter 2 as is the case with buttons 1 and 2 for shutter 1.

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/82421659/175181799-fc4b9f2b-4434-41b3-9a38-31ba3c2d99f7.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by baennjer** [comment]
Have you performed the console command

shutterrelay2 3

to activate shutter 2 with relay 3 (and autm. 4)?

**Comment by baennjer** [comment]
> Thank you for your reply. With "shutterrelay 2 3" I've been able to configure relay 3-4 with shutter 2. I didn't see this option for shutterrelay command anywhere so thank you very much.

There is a great docu
https://tasmota.github.io/docs/Blinds-and-Shutters/

**Comment by Jason2866** [comment]
Closing since solved

**Comment by cyberdomotik** [comment]
In shuttermode 2 (circuit safe ) I realise that sometimes when i get web button to close the shutter, first it`s activated relay 1 (ON) and then relay 2 change so this means that when relay 1 is activated, the shutter starts to open and a few moments later when relay 2 is activated, the shutter closes, causing a rapid change of rotation in the motor. 
How can I avoid this?

**Comment by baennjer** [comment]
> In shuttermode 2 (circuit safe ) I realise that sometimes when i get web button to close the shutter, first it`s activated relay 1 (ON) and then relay 2 change so this means that when relay 1 is activated, the shutter starts to open and a few moments later when relay 2 is activated, the shutter closes, causing a rapid change of rotation in the motor. How can I avoid this?

This issue is closed, you should search the still opened issues for your issue or open a new one .
