### ISSUE TITLE
[Question] Can I use this chained rule commands ?

### ISSUE THREAD

**Issue by AMoktar** [arendst/Tasmota#15925]
Hello
is there anyway to do something like 

`Rule3 ON Time#Minute Do Power2 1 Delay 30; Power2 0 ENDON`

**Comment by sfromis** [comment]
Do not open issues to ask questions. Anyway, the answer is yes, use `Backlog`

**Comment by ascillato** [comment]
```JS
Rule3 ON Time#Minute DO Backlog Power2 1;Delay 30;Power2 0 ENDON
```

**Comment by AMoktar** [comment]
> Do not open issues to ask questions. Anyway, the answer is yes, use `Backlog`

Where I can ask a question?
