### ISSUE TITLE
Sonoff basic reboots every couple of minutes

### ISSUE THREAD

**Issue by overrunner** [arendst/Tasmota#15944]
Hello,

I have a Sonoff basic which has very weak Wifi signal but is mainly controlled by its internal rules so that there is no wifi really needed.
But what happens is, that the device is rebooting very often and requests a new IP from my Firewall.
I already set the wificonfig to 5 to avoid rebooting on wifi loss.
I use currently firmware 11.1.0.
How can I avoid this permanent reboots every couple of minutes?
Wifi is only used to pull the NTP data to setup the clock.

**Comment by barbudor** [comment]
Not providing the required information from the template including logs will not help us to understand what is hapenning

You may want to upgrade to the latest development as, if I recall correctly, there have been recently some work to improve behavior with no wifi
