### ISSUE TITLE
Tasmota v12.0.2 SML arithmetic with more than one meter does not work

### ISSUE THREAD

**Issue by h-tro** [arendst/Tasmota#15950]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
The following code works:

>D
>B
->sensor53 r
>M 1
+1,04,c,1,-50,ABB
1,1-0:1.8.0*255(@1000,B21 Energy,kWh,Energy_Cnt,3
1,=m 1+#110 @1,B21 Energy Meter,kWh,Meter_Cnt,3
1,=d 1 10 @1,B21 Current Power,W,Power_curr,2
#

When I add a second meter, the arithmetic in line 7 (8) no longer updates.
**See attached sreenshots.**

>D
>B
->sensor53 r
>M 2
+1,04,c,1,-50,ABB
+2,22,m,0,2400,Modbus,21,2,0104000C,0104004A
1,1-0:1.8.0*255(@1000,B21 Energy,kWh,Energy_Cnt,3
1,=m 1+#110 @1,B21 Energy Meter,kWh,Meter_Cnt,3
1,=d 1 10 @1,B21 Current Power,W,Power_curr,2
2,010404ffffffff@i1:1,SDM120-1 Energy:,kWh,SDM120-1 Energy_out,3
2,010404ffffffff@i0:-1,SDM120-1 Curr Power,W,SDM120-1 Power_act,2
#

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32
- [x] Tasmota binary firmware version number used: v12.0.2
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: ESP-Flasher-Windows-x64.exe
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
10:43:52.537 RSL: RESULT = {"NAME":"ESP32-DevKit","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
10:43:52.769 RSL: RESULT = {"Module":{"1":"ESP32-DevKit"}}
10:43:53.029 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
10:45:19.096 CMD: Status 0
10:45:19.103 RSL: STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_A9CBD4","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
10:45:19.109 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T00:10:02","StartupUTC":"2022-07-09T08:35:17","Sleep":50,"CfgHolder":4617,"BootCount":108,"BCResetTime":"2022-04-15T14:33:06","SaveCount":170}}
10:45:19.115 RSL: STATUS2 = {"StatusFWR":{"Version":"12.0.2(tasmota)","BuildDateTime":"2022.06.27 14:15:26","Core":"2_0_3","SDK":"v4.4.1","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6 rev.1","CR":"415/699"}}
10:45:19.120 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["EDIMAX-Funkturm",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008001","2805C80001000600003C5A0A190000000000","00000080","00006000","00004000","00000000"]}}
10:45:19.143 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":1423,"Free":1856,"Heap":132,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":3,"Features":["00000407","978AC7CF","001DA001","B7F7BFCF","05DA9BC0","E0360DCF","400840D2","20200000","1434482D","00000000"],"Drivers":"1,2,3,4,5,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,62,82,86","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,31,34,37,39,40,42,43,45,51,52,53,55,56,58,59,64,66,67,74,85,92,95,127"}}
10:45:19.151 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-A9CBD4-3028","IPAddress":"192.168.1.128","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"08:3A:F2:A9:CB:D4","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"0.0.0.0","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00"},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
10:45:19.171 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-07-09T08:45:19","Local":"2022-07-09T10:45:19","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":99,"Sunrise":"05:57","Sunset":"21:53"}}
10:45:19.189 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-07-09T10:45:19","ABB":{"Energy_Cnt":1.238,"Meter_Cnt":111.238,"Power_curr":0.00},"Modbus":{"SDM120-1 Energy_out":15.653,"SDM120-1 Power_act":87.90},"ESP32":{"Temperature":53.3},"TempUnit":"C"}}
10:45:19.204 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-07-09T10:45:19","Uptime":"0T00:10:02","UptimeSec":602,"Heap":134,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"MqttCount":0,"Berry":{"HeapUsed":3,"Objects":41},"Wifi":{"AP":1,"SSId":"EDIMAX-Funkturm","BSSId":"74:DA:38:44:AC:C5","Channel":11,"Mode":"11n","RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:06"}}}
10:45:28.909 RSL: STATE = {"Time":"2022-07-09T10:45:28","Uptime":"0T00:10:11","UptimeSec":611,"Heap":136,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Berry":{"HeapUsed":3,"Objects":41},"Wifi":{"AP":1,"SSId":"EDIMAX-Funkturm","BSSId":"74:DA:38:44:AC:C5","Channel":11,"Mode":"11n","RSSI":52,"Signal":-74,"LinkCount":1,"Downtime":"0T00:00:06"}}
10:45:28.929 RSL: SENSOR = {"Time":"2022-07-09T10:45:28","ABB":{"Energy_Cnt":1.238,"Meter_Cnt":111.238,"Power_curr":0.00},"Modbus":{"SDM120-1 Energy_out":15.653,"SDM120-1 Power_act":86.80},"ESP32":{"Temperature":36.7},"TempUnit":"C"}


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
use the following line with a second meter
1,=m **1+#110** @1,B21 Energy Meter,kWh,Meter_Cnt,3

example:
>D
>B
->sensor53 r
>M 2
+1,04,c,1,-50,ABB
+2,22,m,0,2400,Modbus,21,2,0104000C,0104004A
1,1-0:1.8.0*255(@1000,B21 Energy,kWh,Energy_Cnt,3
1,=m **1+#110** @1,B21 Energy Meter,kWh,Meter_Cnt,3
1,=d 1 10 @1,B21 Current Power,W,Power_curr,2
2,010404ffffffff@i1:1,SDM120-1 Energy:,kWh,SDM120-1 Energy_out,3
2,010404ffffffff@i0:-1,SDM120-1 Curr Power,W,SDM120-1 Power_act,2
#

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
A correct calculation with updating of the values should be displayed even if there is more than one meter

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![ABB](https://user-images.githubusercontent.com/33256321/178099156-d554c134-920c-4b36-b4f3-9c519618dbfc.JPG)
![ABB+SDM120](https://user-images.githubusercontent.com/33256321/178099158-a485041b-b9a8-4891-9099-22a420166c60.JPG)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
sml channel math is only supported on frequently updated channels. a counter is only updated when the counter value changes and only then the channel math is performed. (i will update the docs for that fact)
you may use compile option #define USE_SML_SCRIPT_CMD and then read meter values directly and perform any math in script. (sml[x])
you may also hide any SML webdisplay by setting the channel name to '*' and display all values in the web section
this allows much more html formatting (e.g colored values) and any math you like.
any MQTT output may also be reformatted in the >J section

e. g. display results in Web section

\>W
 Energy Meter{m}%2(sml[1]+110)% kWh

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
