### ISSUE TITLE
BH1750 Sensor unavailable in Home Assistant after upgrading Tasmota from 11.1.0 to 12.0.2

### ISSUE THREAD

**Issue by busterwan** [arendst/Tasmota#15961]
Hardware:
- NodeMCU (see the attached NodeMCU.txt)
[NodeMCU.txt](https://github.com/arendst/Tasmota/files/9080763/NodeMCU.txt)

Firmware:
- Tasmota Sensors (tasmota-sensors.bin) 12.0.2 Paul

Platform:
- MQTT
- SetOption19 was set to ON.

Symptom:
- The BH1750 sensor state [sensor.dishwasher.sensor_bh1750_illuminance] in Home Assistant becomes unavailable after upgrading Tasmota from 11.1.0 to 12.0.2.
- Opened Tasmota Web UI and the BH1750 was working properly (i.e. reported the correct illuminance value). I also tested the sensor with various light intensity and its value changed accordingly but it was continue to be unavailable in Home Assistant.
- Downgrading it back to 11.1.0 solves the issue.

Things I did to try to resolve the issue:
- Restart the NodeMCU in question.
- Reboot/restart Home Assistant.
- Upgrade Home Assistant to the latest version.
- The only solution that works so far is to downgrade Tasmota to 11.1.0.

How to replicate this issue:
- Upgrade the said NodeMCU to Tasmota 12.0.2.

Please let me know if you need more information.

**Comment by arendst** [comment]
Try with SetOption19 Off
