### ISSUE TITLE
enabling setoption19 does remove the tasmota discovery topic but doesnt enable the mqtt discovery

### ISSUE THREAD

**Issue by AKA-47** [arendst/Tasmota#15968]
Hi.
I am on Tasmota 
Program Version	12.0.2(tasmota)
Build Date & Time	2022-06-20T12:41:03
Core/SDK Version	2_7_4_9/2.2.2-dev(38a443e)

My problem is that enabling setoption19 does remove the tasmota discovery topic but doesnt enable the mqtt discovery 

See here with weblog 4 enabled

20:02:09.918 MQT: stat/WOHNZIMMER-TESTRGB/RESULT = {"SetOption19":"OFF"}
20:02:10.416 MQT: tasmota/discovery/BCDDC2883DBF/config = {"ip":"10.174.7.79","dn":"WOHNZIMMER-TESTRGB","fn":["WOHNZIMMER-TESTRGB",null,null,null,null,null,null,null],"hn":"WOHNZIMMER-TESTRGB-7615","mac":"BCDDC2883DBF","md":"BRI E27 6,5W","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"12.0.2","t":"WOHNZIMMER-TESTRGB","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[2,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":1,"lt_st":5,"sho":[0,0,0,0],"sht":[[0,0,0],[0,0,0],[0,0,0],[0,0,0]],"ver":1} (retained)
20:02:10.426 MQT: tasmota/discovery/BCDDC2883DBF/sensors = {"sn":{"Time":"2022-07-12T20:02:10"},"ver":1} (retained)
20:02:10.817 CFG: Saved to flash at FA, Count 742, Bytes 4096

20:02:22.962 MQT: stat/WOHNZIMMER-TESTRGB/RESULT = {"SetOption19":"ON"}
20:02:23.407 MQT: tasmota/discovery/BCDDC2883DBF/config =  (retained)
20:02:23.409 MQT: tasmota/discovery/BCDDC2883DBF/sensors =  (retained)
20:02:23.820 CFG: Saved to flash at F9, Count 743, Bytes 4096

Any idea?
I was expecting something like homeassistant/switch/30AEA4xxxx ... 
on my broker as published topic but as you can see nothing is published but the retained topic from tasmota discovery is removed by setting this to ""

**Comment by sfromis** [comment]
Don't open issues to ask questions....

From version 12, the old deprecated MQTT Discovery for HA is not included in standard precompiled binaries, recommended is to use the newer improved Tasmota Integration.
