### ISSUE TITLE
SetOption19 Issue in Tasmota 12.0.2.4

### ISSUE THREAD

**Issue by f0rc3r** [arendst/Tasmota#16076]
Hello everyone,

I guess there is an Issue with "SetOption19 1". After activating it, there is nothing in the console about Home-Assistant and publishing.
I don't see the Device in the Hass.io Integration either. There is a New Device in the MQTT Add-on Logs, but it did not discover it in the Integration. 

When I make a Downgrade to Tasmota 11 "Olivia" it works all fine. I activate "SetOption19 1" and I get my Device in the MQTT Integration.

Did anyone else Discovered this ?

**Comment by ascillato2** [comment]
https://github.com/arendst/Tasmota/issues/16077
