### ISSUE TITLE
Can't set host for syslog logging

### ISSUE THREAD

**Issue by gajes9** [arendst/Tasmota#16085]
### PROBLEM DESCRIPTION
I can't set host for syslog, both from WebGui and console.
When I try to set host using command: LogHost 192.168.5.179 
I receives the response:
11:21:31.148 CMD: LogHost 192.168.5.179
11:21:31.150 SRC: WebConsole from 192.168.5.50
11:21:31.153 CMD: Grp 0, Cmd 'LOGHOST', Idx 1, Len 13, Pld 192, Data '192.168.5.179'
11:21:31.156 CFG: Text overflow by 6 char(s)
11:21:31.160 MQT: stat/sterownik_nawadniania1/RESULT = {"LogHost":""}

Propably the problem is caused by too long ip adress, because when i issue command : LogHost 3.2.3.4 
I recives the response:
11:23:32.719 CMD: LogHost 3.2.3.4
11:23:32.721 SRC: WebConsole from 192.168.5.50
11:23:32.724 CMD: Grp 0, Cmd 'LOGHOST', Idx 1, Len 7, Pld 3, Data '3.2.3.4'
11:23:32.727 CFG: CR 699/699, Busy 0
11:23:32.731 MQT: stat/sterownik_nawadniania1/RESULT = {"LogHost":"3.2.3.4"}
11:23:33.655 CFG: Saved to flash at F5, Count 447, Bytes 4096

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Pro R3 and Sonoff Pro R2
- [x] Tasmota binary firmware version number used: 12.02
  - [x] Pre-compiled
- [x] Flashing tools used: Web
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
11:41:42.153 MQT: stat/sterownik_nawadniania1/RESULT = {"NAME":"SonoffProMy","GPIO":[32,1,1,1,226,225,33,34,224,320,35,227,1,1],"FLAG":0,"BASE":23}
11:41:42.377 MQT: stat/sterownik_nawadniania1/RESULT = {"Module":{"0":"SonoffProMy"}}
11:41:42.630 MQT: stat/sterownik_nawadniania1/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"228":"Relay5"},"GPIO2":{"229":"Relay6"},"GPIO3":{"230":"Relay7"},"GPIO4":{"226":"Relay3"},"GPIO5":{"225":"Relay2"},"GPIO9":{"33":"Button2"},"GPIO10":{"34":"Button3"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"35":"Button4"},"GPIO15":{"227":"Relay4"},"GPIO16":{"231":"Relay8"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
11:43:14.888 MQT: stat/sterownik_nawadniania1/STATUS = {"Status":{"Module":0,"DeviceName":"SterownikNawadniania1","FriendlyName":["SterownikNawadniania1Przek1","SterownikNawadniania1Przek2","SterownikNawadniania1Przek3","SterownikNawadniania1Przek4","SterownikNawadniania1DummyPrzek1","SterownikNawadniania1DummyPrzek2","Sterowni],"Topic":"sterownik_nawadniania1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
11:43:14.940 MQT: stat/sterownik_nawadniania1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:16:27","StartupUTC":"2022-07-26T08:26:47","Sleep":50,"CfgHolder":4617,"BootCount":31,"BCResetTime":"2022-07-06T13:38:49","SaveCount":448,"SaveAddress":"F4000"}}
11:43:14.976 MQT: stat/sterownik_nawadniania1/STATUS2 = {"StatusFWR":{"Version":"12.0.2(tasmota)","BuildDateTime":"2022-06-20T12:41:03","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"692/699"}}
11:43:14.995 MQT: stat/sterownik_nawadniania1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MMGHomeGarage",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000E00B","2805C80001000600003C5A0A190000000000","00800080","00006008","00004000","00000000"]}}
11:43:15.002 MQT: stat/sterownik_nawadniania1/STATUS4 = {"StatusMEM":{"ProgramSize":619,"Free":384,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14325E","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","14000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
11:43:15.038 MQT: stat/sterownik_nawadniania1/STATUS5 = {"StatusNET":{"Hostname":"sterownik-nawadniania1","IPAddress":"192.168.5.38","Gateway":"192.168.5.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.5.1","DNSServer2":"217.113.224.135","Mac":"9C:9C:1F:8A:4D:46","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
11:43:15.066 MQT: stat/sterownik_nawadniania1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.5.179","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_8A4D46","MqttUser":"mosquitto","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
11:43:15.091 MQT: stat/sterownik_nawadniania1/STATUS7 = {"StatusTIM":{"UTC":"2022-07-26T09:43:15","Local":"2022-07-26T11:43:15","StartDST":"2022-03-27T03:00:00","EndDST":"2022-10-23T03:00:00","Timezone":99,"Sunrise":"05:03","Sunset":"20:53"}}
11:43:15.110 MQT: stat/sterownik_nawadniania1/STATUS10 = {"StatusSNS":{"Time":"2022-07-26T11:43:15"}}
11:43:15.120 MQT: stat/sterownik_nawadniania1/STATUS11 = {"StatusSTS":{"Time":"2022-07-26T11:43:15","Uptime":"0T01:16:28","UptimeSec":4588,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"MMGHomeGarage","BSSId":"00:1C:DF:BA:B2:51","Channel":6,"Mode":"11n","RSSI":64,"Signal":-68,"LinkCount":1,"Downtime":"0T00:00:05"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
11:21:31.148 CMD: LogHost 192.168.5.179
11:21:31.150 SRC: WebConsole from 192.168.5.50
11:21:31.153 CMD: Grp 0, Cmd 'LOGHOST', Idx 1, Len 13, Pld 192, Data '192.168.5.179'
11:21:31.156 CFG: Text overflow by 6 char(s)
11:21:31.160 MQT: stat/sterownik_nawadniania1/RESULT = {"LogHost":""}

```

### TO REPRODUCE
Issue:
LogHost 192.168.5.179

### EXPECTED BEHAVIOUR
Saved host adress

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Tasmota stores certain values in a 699 bytes text buffer. Apparently you have used up this buffer with buttonnames, friendlynames, ntpservers etc.

So change/remove one of those to make room for your loghost.

BTW "normal" buffer fill is about 450/699 (See command ``status 2``, item CR): 
```
11:48:43.443-021 MQT: stat/wemos4/STATUS2 = {"StatusFWR":{"Version":"12.0.2.4(tasmota)","BuildDateTime":"2022-07-24T15:43:34","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"417/699"}}
``

**Comment by gajes9** [comment]
You are right. The reason was no more space in buffer. When I reduce names of my dummys WebButtons, I can set host of syslog to proper value. Thanks a lot for the clarification and for your help.
