### ISSUE TITLE
MqttFingerprint cannot be set on Sonoff S20

### ISSUE THREAD

**Issue by CodingSpiderFox** [arendst/Tasmota#16299]
I am running a Sonoff S20 with Tasmota 12.1.0

I went to the Tasmota console in the browser and typed the MqttFingerprint command because I wanted to set the public key fingerprint for MQTT over TLS (my broker runs EMQX)

**Comment by sfromis** [comment]
TLS not included in regular precompiled ESP8266 binaries.
