### ISSUE TITLE
Serial buffer overrun when reading P1

### ISSUE THREAD

**Issue by andrasg** [arendst/Tasmota#16368]
### PROBLEM DESCRIPTION

I am using a Wemos D1 mini to read the P1 interface of my electricity meter. Data is arriving nicely, but is getting truncated. Tried increasing the buffer using `SerialBuffer 520`, but still get buffer overruns in each read cycle. When the buffer overrun happens, some lines are not received at all.

Log excerpt:

```lua
12:33:16.855 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:8.7.0(00.113*kvar)\r"}
12:33:16.918 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"0-0:98.1.0(220801000000S)(011181.085*kWh)(005916.460*kWh)(005264.625*kWh)(000000.000*kWh)(000000.000*kWh)(000000.000*kWh)(001842.123*kvarh)(002155.507*kvarh)(001842.123*kvarh)(000000.000*kvarh)(000000.000*kvarh)(002155.507*kvarh)(011181.087*kWh)(03.332*kW)(03.332*kW)(03.156*kW)(00.000*kW)(00.000*kW)(00.000*kW)\r"}
12:33:17.269 CMD: Serial buffer overrun
12:33:17.274 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":")\r"}
12:33:17.284 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"!46EC\r"}
12:33:26.482 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"/AUX59902711681\r"}
12:33:26.488 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"\r"}
12:33:26.503 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"0-0:1.0.0(220828133330S)\r"}
12:33:26.523 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"0-0:42.0.0(AUX1030302711681)\r"}
12:33:26.538 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"0-0:96.1.0(9902711681)\r"}
12:33:26.548 CMD: Serial buffer overrun
12:33:26.554 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":".0(.5017.0.)\r"}
12:33:26.563 CMD: Serial buffer overrun
12:33:26.567 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"0-0:1.8.4(000*kWh)\r"}
12:33:26.575 CMD: Serial buffer overrun
12:33:26.580 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":".kWh)\r"}
12:33:26.590 CMD: Serial buffer overrun
12:33:26.595 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"k0(000000.00rh)\r"}
12:33:26.600 CMD: Serial buffer overrun
12:33:26.605 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"\r"}
12:33:26.618 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:8.8.0(002230.636*kvarh)\r"}
12:33:26.633 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:15.8.0(011507.837*kWh)\r"}
12:33:26.647 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:32.7.0(241.9*V)\r"}
12:33:26.661 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:52.7.0(236.2*V)\r"}
12:33:26.674 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:72.7.0(241.7*V)\r"}
12:33:26.687 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:31.7.0(000*A)\r"}
12:33:26.699 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:51.7.0(002*A)\r"}
12:33:26.713 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:71.7.0(000*A)\r"}
12:33:26.726 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:13.7.0(0.990)\r"}
12:33:26.739 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:33.7.0(0.912)\r"}
12:33:26.753 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:53.7.0(0.978)\r"}
12:33:26.766 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:73.7.0(0.840)\r"}
12:33:26.779 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:14.7.0(50.02*Hz)\r"}
12:33:26.792 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:1.7.0(00.599*kW)\r"}
12:33:26.806 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:2.7.0(00.000*kW)\r"}
12:33:26.820 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:5.7.0(00.031*kvar)\r"}
12:33:26.833 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:6.7.0(00.000*kvar)\r"}
12:33:26.848 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:7.7.0(00.000*kvar)\r"}
12:33:26.862 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:8.7.0(00.113*kvar)\r"}
12:33:27.309 CMD: Serial buffer overrun
12:33:27.314 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":")\r"}
12:33:27.323 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"!AE83\r"}
```

What can I do to avoid the buffer overrun and read each P1 message properly?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Wmos D1 mini
- [X] Tasmota binary firmware version number used: Tasmota 12.1.1
  - [X] Pre-compiled
  - [ ] Self-compiled
- [X] Flashing tools used: browser
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
12:37:44.130 CMD: Backlog Template; Module; GPIO 255
12:37:44.162 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
12:37:44.382 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"Module":{"18":"Generic"}}
12:37:44.636 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"3232":"Serial Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
12:38:37.585 CMD: Backlog Rule1; Rule2; Rule3
12:38:37.719 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":40,"Free":471,"Rules":"ON System#Boot DO SerialBuffer 520 ENDON"}}
12:38:37.934 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
12:38:38.187 MQT: tasmota-szeher/stat/wemos-p1/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
```
- [X] Provide the output of this command: `Status 0`:
```lua
12:39:19.408 CMD: Status 0
12:39:19.415 MQT: tasmota-szeher/stat/wemos-p1/STATUS = {"Status":{"Module":18,"DeviceName":"wemos-p1","FriendlyName":["wemos-p1"],"Topic":"wemos-p1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
12:39:19.427 MQT: tasmota-szeher/stat/wemos-p1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T04:04:45","StartupUTC":"2022-08-28T07:34:34","Sleep":50,"CfgHolder":4617,"BootCount":30,"BCResetTime":"2022-07-20T20:58:28","SaveCount":189,"SaveAddress":"F9000"}}
12:39:19.439 MQT: tasmota-szeher/stat/wemos-p1/STATUS2 = {"StatusFWR":{"Version":"12.1.1(tasmota)","BuildDateTime":"2022-08-25T11:33:55","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"359/699"}}
12:39:19.449 MQT: tasmota-szeher/stat/wemos-p1/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Bobo IOT",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00408009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
12:39:19.464 MQT: tasmota-szeher/stat/wemos-p1/STATUS4 = {"StatusMEM":{"ProgramSize":624,"Free":376,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
12:39:19.477 MQT: tasmota-szeher/stat/wemos-p1/STATUS5 = {"StatusNET":{"Hostname":"wemos-p1","IPAddress":"192.168.30.107","Gateway":"192.168.30.253","Subnetmask":"255.255.255.0","DNSServer1":"1.1.1.1","DNSServer2":"0.0.0.0","Mac":"AC:0B:FB:DA:6E:DE","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
12:39:19.486 MQT: tasmota-szeher/stat/wemos-p1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.30.90","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_DA6EDE","MqttUser":"mqtt_user","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
12:39:19.498 MQT: tasmota-szeher/stat/wemos-p1/STATUS7 = {"StatusTIM":{"UTC":"2022-08-28T11:39:19","Local":"2022-08-28T12:39:19","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"06:01","Sunset":"19:40"}}
12:39:19.507 MQT: tasmota-szeher/stat/wemos-p1/STATUS10 = {"StatusSNS":{"Time":"2022-08-28T12:39:19"}}
12:39:19.519 MQT: tasmota-szeher/stat/wemos-p1/STATUS11 = {"StatusSTS":{"Time":"2022-08-28T12:39:19","Uptime":"0T04:04:45","UptimeSec":14685,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"IOT","BSSId":"C2:3D:C7:A3:38:C9","Channel":4,"Mode":"11n","RSSI":42,"Signal":-79,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [X] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
12:40:06.584 RUL: No valid JSON ({"SERIALRECEIVED":{"DATA":"000*KWH)8.4(000000.WH)\R"}})
12:40:06.590 CMD: Serial buffer overrun
12:40:06.594 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":".0(00arh)\r"}
12:40:06.599 RUL: No valid JSON ({"SERIALRECEIVED":{"DATA":".0(00ARH)\R"}})
12:40:06.611 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:8.8.0(002230.648*kvarh)\r"}
12:40:06.616 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:8.8.0(002230.648*KVARH)\R"})
12:40:06.627 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:15.8.0(011507.900*kWh)\r"}
12:40:06.633 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:15.8.0(011507.900*KWH)\R"})
12:40:06.644 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:32.7.0(243.5*V)\r"}
12:40:06.649 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:32.7.0(243.5*V)\R"})
12:40:06.660 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:52.7.0(237.0*V)\r"}
12:40:06.664 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:52.7.0(237.0*V)\R"})
12:40:06.675 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:72.7.0(242.2*V)\r"}
12:40:06.680 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:72.7.0(242.2*V)\R"})
12:40:06.690 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:31.7.0(000*A)\r"}
12:40:06.695 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:31.7.0(000*A)\R"})
12:40:06.706 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:51.7.0(002*A)\r"}
12:40:06.710 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:51.7.0(002*A)\R"})
12:40:06.721 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:71.7.0(000*A)\r"}
12:40:06.725 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:71.7.0(000*A)\R"})
12:40:06.736 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":"1-0:13.7.0(0.989)\r"}
12:40:06.741 RUL: No valid JSON ({"SERIALRECEIVED":"1-0:13.7.0(0.989)\R"})
12:40:06.747 CMD: Serial buffer overrun
12:40:06.751 MQT: tasmota-szeher/tele/wemos-p1/RESULT = {"SerialReceived":".7.0(0.907)\r"}
12:40:06.756 RUL: No valid JSON ({"SERIALRECEIVED":{"DATA":".7.0(0.907)\R"}})
```

### TO REPRODUCE
Followed guide to create P1 interface: https://tasmota.github.io/docs/P1-Smart-Meter/
Installed Tasmota, configured MQTT, set `SerialDelimiter 10` and `SerialSend 1`.
Connected to meter's P1 port.
Observed data being sent from meter.

### EXPECTED BEHAVIOUR
No buffer overrun is experienced and all messages are sent properly, each send cycle.

**Comment by barbudor** [comment]
What is the baudrate used ?

**Comment by andrasg** [comment]
> What is the baudrate used ?

The meter, according to its docs uses 115200 baud, 8N1 config.

**Comment by barbudor** [comment]
That may be a bit high. Do you know the quantity of data transmitted every second ? (roughly)

**Comment by andrasg** [comment]
> Do you know the quantity of data transmitted every second ? (roughly)

Data being sent is unfortunately controlled by the electricity company. Docs say the meter (Sanxing SX631) emits 42 data points, every 10 seconds. Each datapoint is around 20 characters on average, but there are one or two datapoints (eg: monthly summary data) that are significantly longer (200+ chars).

From the log timestamps, I see that one cycles worth of data is arriving in about 70ms.

**Comment by barbudor** [comment]
So every 10 seconds you get 40 * 20 + 2 * 250 = 1300
I think this is the problem
If it comes as a burst and you only have a buffer of 520, Tasmota cannot cope with that

I've simulated that (1300 bytes as a burst every 10 seconds) and I have to reduce the Baudrate to 19200 to avoid overrun

Any way you can change the baudrate of the meter ?
1300 Bytes every 10 seconds is around an effective 1300 bps (130 Bps). Too bad then send that as a high speed burst

**Comment by andrasg** [comment]
> So every 10 seconds you get 40 * 20 + 2 * 250 = 1300 I think this is the problem If it comes as a burst and you only have a buffer of 520, Tasmota cannot cope with that
> 
> I've simulated that (1300 bytes as a burst every 10 seconds) and I have to reduce the Baudrate to 19200 to avoid overrun
> 
> Any way you can change the baudrate of the meter ? 1300 Bytes every 10 seconds is around an effective 1300 bps (130 Bps). Too bad then send that as a high speed burst

Is this an ESP8266 limit or Tasmota?

**Comment by andrasg** [comment]
I cannot influence the sender, but have an RTS lane. Perhaps Tasmota could clear the RTS while the buffer is full?

**Comment by barbudor** [comment]
> Is this an ESP8266 limit or Tasmota?

Hum, Tasmota as far as I can see. It should be possible to allow larger size. I'm looking into it

> I cannot influence the sender, but it does offer an RTS lane. Perhaps Tasmota could clear the RTS while the buffer is full?

Unfortunately Tasmota do not support hardware handshake (software neither I'm afraid)

**Comment by barbudor** [comment]
Can you try this version with `Serialbuffer 1400` or `Serialbuffer 1500`
It seems to work with my simulation.
If you confirm that it is working stable, I will push a PR but serial management on Tasmota is a bit complex, not yet 100% sure that it is clean and acceptable

[tasmota-serialbuff2048.zip](https://github.com/arendst/Tasmota/files/9439875/tasmota-serialbuff2048.zip)

**Comment by sfromis** [comment]
Depending on what you want to do with the data, I can also recommend ESP32, not only because it has more headroom for speed, but also due to much better local processing options with Berry, where you are not getting the overhead of the logging of the incoming serial data.

**Comment by andrasg** [comment]
> Can you try this version with `Serialbuffer 1400` or `Serialbuffer 1500` It seems to work with my simulation.

It works well! I had to go to 1700, even though the actual characters of the message yielded only 1220 bytes.

Thanks for the help, I will keep monitoring it and give a shout if I encounter something unexpected.

**Comment by andrasg** [comment]
Ah, thinking about it more, it's probably the CRC that's on top of the payload making it slightly more than the 1220 bytes.

**Comment by barbudor** [comment]
In SerialBridge mode, Tasmota won't process any CRC
I don't see anything that could be a CRC in a typical line such as `{"SerialReceived":"1-0:72.7.0(241.7*V)\r"}`
May be the last line `{"SerialReceived":"!AE83\r"}` could be such CRC for the whole frame but that's just a matter of a few bytes. 
Nevertheless, I took some margin as it allows up to 2048 bytes.

**Comment by deesnow** [comment]
> > Can you try this version with `Serialbuffer 1400` or `Serialbuffer 1500` It seems to work with my simulation.
> 
> It works well! I had to go to 1700, even though the actual characters of the message yielded only 1220 bytes.
> 
> Thanks for the help, I will keep monitoring it and give a shout if I encounter something unexpected.

@andrasg I had the same issue, but with this modified version all messages are sent to mttq. Unfortunatelly here on github I cannot send you direct message and I would like to ask some question regardind the parsig of the mttq message on HomaAssistant side. Could you send me your mail address? You can find my address on profile page.

**Comment by deesnow** [comment]
> Can you try this version with `Serialbuffer 1400` or `Serialbuffer 1500` It seems to work with my simulation. If you confirm that it is working stable, I will push a PR but serial management on Tasmota is a bit complex, not yet 100% sure that it is clean and acceptable
> 
> [tasmota-serialbuff2048.zip](https://github.com/arendst/Tasmota/files/9439875/tasmota-serialbuff2048.zip)

Hi @barbudor 

In this version did you modify anything else or just the followings?
```
#define SML_MAX_VARS 60
#define SML_BSIZ 1060
#define MAX_METERS 1
#define TMSBSIZ 2048
#define USE_SML_SCRIPT_CMD
#define SML_REPLACE_VARS
```

**Comment by barbudor** [comment]
Do not use this version which was temporary
Changes made are now in Tasmota supporting 'SerialBuffer' command up to 2048
Note that if you are using scripting I have no idea if this improvement also applies to scripting

**Comment by andrasg** [comment]
> @andrasg I had the same issue, but with this modified version all messages are sent to mttq. Unfortunatelly here on github I cannot send you direct message and I would like to ask some question regardind the parsig of the mttq message on HomaAssistant side. Could you send me your mail address? You can find my address on profile page.

Hey János, I am not using HomeAssistant, cannot help you there, unfortunately.

**Comment by deesnow** [comment]
> > @andrasg I had the same issue, but with this modified version all messages are sent to mttq. Unfortunatelly here on github I cannot send you direct message and I would like to ask some question regardind the parsig of the mttq message on HomaAssistant side. Could you send me your mail address? You can find my address on profile page.
> 
> Hey János, I am not using HomeAssistant, cannot help you there, unfortunately.

Thx anyway ;)
