### ISSUE TITLE
xdrv_39_thermostat  local sensor ANALOG

### ISSUE THREAD

**Issue by serifis84** [arendst/Tasmota#16363]
### PROBLEM DESCRIPTION
Thermostat driver does not use local sensor ANALOG 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

10:53:24.919 RSL: RESULT = {"NAME":"Water Chiller","GPIO":[64,3200,320,3232,640,608,5730,0,224,225,226,1,1,4736],"FLAG":0,"BASE":18}
10:53:25.130 RSL: RESULT = {"Module":{"0":"Water Chiller"}}
10:53:25.386 RSL: RESULT = {"GPIO0":{"64":"Button_n1"},"GPIO1":{"3200":"Serial Tx"},"GPIO2":{"320":"Led_i1"},"GPIO3":{"3232":"Serial Rx"},"GPIO4":{"640":"I2C SDA"},"GPIO5":{"608":"I2C SCL"},"GPIO9":{"5730":"Option A3"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"225":"Relay2"},"GPIO14":{"226":"Relay3"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"4736":"ADC Temp"}}



```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
compiled with
#define USER_BACKLOG "TelePeriod 10; Rule1 1; PulseTime4 160; TempOffset 1; mem1 10.00; mem2 OFF"

#define USER_RULE1 "ON Power1#Boot do Backlog SensorInputSet 1; ClimateModeSet 1; ControllerModeSet 1; TimePiCycleSet 20; TimeMaxActionSet 18; TimeMinActionSet 0; ThermostatModeSet 1; DisplayText [O]; TempTargetSet %mem1%; DisplayText [f1x0y30]SET: [f4x40y30p-5]%mem1%; Teleperiod 10; POWER4 1 ENDON"


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

10:55:30.884 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Water Chiller","FriendlyName":["Water Chiller","Water Chiller2","Water Chiller3","Water Chiller4"],"Topic":"Water-Chiller_4C1444","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":6,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
10:55:30.891 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"2T12:37:51","StartupUTC":"2022-08-25T20:17:39","Sleep":50,"CfgHolder":4617,"BootCount":2,"BCResetTime":"2022-08-25T22:15:19","SaveCount":7,"SaveAddress":"FD000"}}
10:55:30.897 RSL: STATUS2 = {"StatusFWR":{"Version":"12.1.1(TasmoCompiler-esp82664M)","BuildDateTime":"2022-08-25T18:30:39","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"433/699"}}
10:55:30.904 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["HomeWLAN",""],"TelePeriod":10,"Resolution":"558180C0","SetOption":["00008008","2805C80000000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
10:55:30.915 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":710,"Free":1336,"Heap":23,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640C8","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0FA0458E","04261F81","00000003","00000000","C000E981","000004A4","003E9000","54000000","00000000"],"Drivers":"1,2,4,6,8,9,10,12,13,18,19,22,24,26,27,29,30,35,37,38,39,45,50,62","Sensors":"1,2"}}
10:55:30.923 RSL: STATUS5 = {"StatusNET":{"Hostname":"Water-Chiller-4C1444-5188","IPAddress":"192.168.1.25","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.254","DNSServer2":"192.168.1.254","Mac":"2C:3A:E8:4C:14:44","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
10:55:30.928 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4C1444","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
10:55:30.935 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-08-28T08:55:30","Local":"2022-08-28T10:55:30","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+02:00","Sunrise":"07:01","Sunset":"20:40"}}
10:55:30.944 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-08-28T10:55:30","ANALOG":{"Temperature":105.0},"Thermostat0":{"ThermostatModeSet":1,"TempTargetSet":10.00,"CtrDutyCycleRead":0},"TempUnit":"C"}}
10:55:30.952 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-08-28T10:55:30","Uptime":"2T12:37:51","UptimeSec":218271,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"HomeWLAN","BSSId":"30:B5:C2:35:39:43","Channel":11,"Mode":"11n","RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:06"}}}


```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
compile with

#ifndef USE_THERMOSTAT
#define USE_THERMOSTAT
#endif

#ifdef THERMOSTAT_SENSOR_NAME
 #undef THERMOSTAT_SENSOR_NAME
#endif               
#define THERMOSTAT_SENSOR_NAME	"ANALOG"

#ifdef THERMOSTAT_TIME_MANUAL_TO_AUTO        
 #undef THERMOSTAT_TIME_MANUAL_TO_AUTO        
#endif
#define THERMOSTAT_TIME_MANUAL_TO_AUTO 1

set analog pin as Temp
on power on i set SensorInputSet 1; ClimateModeSet 1; ControllerModeSet 1; TimePiCycleSet 20; TimeMaxActionSet 18; TimeMinActionSet 0; ThermostatModeSet 1
in console i get 10:59:29.614 RSL: SENSOR = {"Time":"2022-08-28T10:59:29","ANALOG":{"Temperature":108.7},"Thermostat0":{"ThermostatModeSet":1,"TempTargetSet":10.00,"CtrDutyCycleRead":0},"TempUnit":"C"}
but thermostat driver never reads the value of Analog Temperature

Web GUI
------------
Temperature    105.0 °C
Thermostat	Enabled
Set Point Temperature	10.0 °C
Current Temperature	0.0 °C
Gradient Temperature	0.0 °C
Duty cycle	0 %
Cycle time	20 Min
PI Auto tuning	Disabled

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

It should read the value of Analog Temperature and start acting as it should when i use a DS18b20 sensor

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Never looked at the code before but I fear that a temperature over 100 C is a problem.

Looking at the code in file ``xdrv_39_thermostat.ino`` line 1370 it checks if values between -100 and 100 C (actually it does -1000 and 1000 but it multiplied the read value by ten in line 1366).

As a workaround you might want to change the checks from 1000 to 2000 and see if it solves your issue.
