### ISSUE TITLE
max6675 - constantly showing 0 degrees with k-type sensor

### ISSUE THREAD

**Issue by 001oc** [arendst/Tasmota#16409]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Max6675 connected to k-type temperature sensor is showing 0 degrees constantly on main menu and log-files. Same sensor and chip is working with arduino ide and corresponding example without problems.

When compiling for 

tasmota32 (tried tasmota32-sensors too, but is not working at all because of missing definition)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): ESP32 WROOM
- [X] Tasmota binary firmware version number used: 2.0.4.1 / 12.1.1.1
  - [X] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: vscode (esptool)
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
12:58:42.490 RSL: RESULT = {"Module":{"0":"ESP32-WRoom SensorMax6675"}}
12:58:42.753 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"2560":"MX31855 DO"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"2496":"MX31855 CS"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"2528":"MX31855 CLK"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}

```
- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [X] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
12:59:58.237 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_C5CFB8","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
12:59:58.249 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T00:20:39","StartupUTC":"2022-09-01T10:39:19","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2022-08-31T21:32:26","SaveCount":30}}
12:59:58.263 RSL: STATUS2 = {"StatusFWR":{"Version":"12.1.1.1(tasmota)","BuildDateTime":"2022.09.01 12:09:07","Core":"2_0_4_1","SDK":"v4.4.3","CpuFrequency":80,"Hardware":"ESP32-D0WDQ6 rev.1","CR":"398/699"}}
12:59:58.273 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FB7490B",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","40000080","00007000","00004000","00000000"]}}
12:59:58.299 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":1421,"Free":1458,"Heap":146,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":"DIO","Features":["00000407","9F9AD7CF","0015A001","B7F7BFCF","05DA9BC0","E0360DC7","400840D2","20200000","D434482D","00000001"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,62,63,82,86,87","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,28,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,127"}}
12:59:58.311 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-C5CFB8-4024","IPAddress":"192.168.2.165","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.2.10","DNSServer2":"0.0.0.0","Mac":"24:0A:C4:C5:CF:B8","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"0.0.0.0","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00"},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
12:59:58.320 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C5CFB8","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
12:59:58.328 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-09-01T10:59:58","Local":"2022-09-01T12:59:58","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":99,"Sunrise":"06:45","Sunset":"20:17"}}
12:59:58.340 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-09-01T12:59:58","MAX6675":{"Temperature":0.0,"ReferenceTemperature":null,"Error":0},"ESP32":{"Temperature":36.1},"Shutter1":{"Position":0,"Direction":0,"Target":0,"Tilt":0},"TempUnit":"C"}}
12:59:58.351 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-09-01T12:59:58","Uptime":"0T00:20:39","UptimeSec":1239,"Heap":148,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":0,"Berry":{"HeapUsed":3,"Objects":40},"Wifi":{"AP":1,"SSId":"FB7490B","BSSId":"3C:A6:2F:1E:59:62","Channel":6,"Mode":"11n","RSSI":22,"Signal":-89,"LinkCount":1,"Downtime":"0T00:00:05"}}}
12:59:58.359 RSL: STATUS12 = {"StatusSTK":{"Exception":0,"Reason":"IllegalInstruction","EPC":"40174284","EXCVADDR":"00000000","CallChain":["40174281","40173781","40177d52","4017c846","4016dec9"]}}
12:59:58.365 RSL: STATUS13 = {"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":100,"Close":100,"50perc":50,"Delay":0,"Opt":"0000","Calib":[300,500,700,900,1000],"Mode":"0"}}}

```
- [X] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

13:01:29.793 RSL: sensors = {"sn":{"Time":"2022-09-01T13:01:29","MAX6675":{"Temperature":0.0,"ReferenceTemperature":null,"Error":0},"ESP32":{"Temperature":53.3},"Shutter1":{"Position":0,"Direction":0,"Target":0,"Tilt":0},"TempUnit":"C"},"ver":1}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

source code modifications:
- platformio_overide.ini:
;                          tasmota
;                          tasmota-debug
;                          tasmota-minimal
;                          tasmota-lite
;                          tasmota-knx
;                          tasmota-sensors
;                          tasmota-display
;                          tasmota-zbbridge
;                          tasmota-ir
                          tasmota32
;                          tasmota32-zbbrdgpro
;                          tasmota32-bluetooth
;                          tasmota32-webcam
;                          tasmota32-knx
;                          tasmota32-sensors
...

- user_config_override.h:

#ifdef APP_TIMEZONE
#undef APP_TIMEZONE
#endif
#define APP_TIMEZONE           99                 // [Timezone] +1 hour (Amsterdam) (-13 .. 14 = hours from UTC, 99 = use TIME_DST/TIME_STD)

#ifdef MY_LANGUAGE
#undef MY_LANGUAGE
#endif
#define MY_LANGUAGE            de_DE           // German in Germany

#ifdef USE_EXPRESSION
#undef USE_EXPRESSION
#endif
#define USE_EXPRESSION                         // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)

#ifdef SUPPORT_IF_STATEMENT
#undef SUPPORT_IF_STATEMENT
#endif
#define SUPPORT_IF_STATEMENT                 // Add support for IF statement in rules (+4k2 code, -332 bytes mem)

#ifdef USE_MAX31855
#undef USE_MAX31855
#endif
#define USE_MAX31855

after that just compile current version within vscode and transfer it to esp32 wroom. Some config on esp32 as setting "setoption94 1" in console and some settings in template has to be done ( see screenshots). After that the max6675 is displayed at main page but only with 0 degrees.

I had even tried to compile the tasmota32_sensors but that seems to be outdated as the compiler says "Error: Unknown environment names 'tasmota32-sensors'"

The sensor is running smootly with example projects in arduino ide - as of that I think the sensor is ok.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Showing actual temperatur of k-type sensor in the main menu.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

[main menu](https://www.coracing.de/ss1.png)
[console](https://www.coracing.de/ss2.png)
[template](https://www.coracing.de/ss3.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
MAX6675 is not the same as the Tasmota supported MAX31855.

**Comment by Jason2866** [comment]
Sorry missed `SetOption94 1 -> MAX6675`
@arendst  Do you have that Sensor?

**Comment by arendst** [comment]
Nope.

**Comment by 001oc** [comment]
I have such a chip and sensor ...

**Comment by JulioVillamizar** [comment]
Hi, I have the same problem, were you able to find a solution?
