### ISSUE TITLE
Reset Problem since a couple of weeks (device was working OKE for years)

### ISSUE THREAD

**Issue by MAWMN** [arendst/Tasmota#16418]
Hello,

   since a couple of weeks my device An Arduino D1 R2 is having problems of resetting itself suddenly, so to be sure I did update to the latest minimal version and had to reconfige completely the device and application settings, so I did..(previous was 10.0.0)
Without the new hardware (GPIO setting made, no resets occured, however after having set the GPIO configuration, again the resetting started (Reset every minute...)

the gpio settings I used were : 
1	GPIO0 	4	(Relay4, can also be set by the Web Interface)
2	GPIO1 	0	(None, can also be set by the Web Interface)
3	GPIO2 	1	(Relays1, can also be set by the Web Interface)
4	GPIO3 	0	(None, can also be set by the Web Interface)
5	GPIO4 	7	(Relays7, can also be set by the Web Interface)
6	GPIO5 	6	(Relays6, can also be set by the Web Interface)
7	GPIO12 	3	(Relays3, can also be set by the Web Interface)
8	GPIO13 	7	(Button1, can also be set by the Web Interface)
9	GPIO14 	2	(Led1, can also be set by the Web Interface)
10	GPIO15 	2	(Relays2, can also be set by the Web Interface)
11	GPIO16 	5	(Relays5, can also be set by the Web Interface)

Also ADC was set to Input

Configuration to do by the console (type the following commands one by one !!) :
	Rule1 on 	        Mqtt#Disconnected do Power2 ON endon on Mqtt#Connected do Power2 OFF endon
	Rule2 on 	       Wifi#Disconnected do Power3 ON endon on Wifi#Connected do Power3 OFF endon
	Rule1 1		(Switch Rule1 ON)
	Rule1 4		(Disable one-shot detection (Perform commands as long as trigger is met))
	Rule2 1		(Switch Rule2 ON)
	Rule2 4		(Disable one-shot detection (Perform commands as long as trigger is met))
	LedState 7	(Show power state and MQTT messages as a led blink)
	WifiConfig 5	(NO Reset of the board when Wifi Signal is lost, just wait for reconnect)

After a Reboot a Reset is performed every minute 
================================
00:00:00.002 HDW: ESP8266EX
00:00:00.050 CFG: Loaded from flash at F8, Count 278
00:00:00.056 QPC: Count 1
00:00:00.069 Project tasmota - Device_Main Version 12.1.1(tasmota)-2_7_4_9(2022-08-25T11:33:55)
00:00:00.557 WIF: Connecting to AP1 mna_AP Channel 8 BSSId E0:3F:49:09:D2:D0 in mode 11n as sonoff01-3173...
00:00:03.754 WIF: Connected
00:00:04.006 HTP: Web server active on sonoff01-3173 with IP address 10.0.0.191
15:40:25.022 MQT: Attempting connection...
15:40:25.034 MQT: Connected
15:40:25.037 MQT: tasmota/kamer/sonoff01/tele/LWT = Online (retained)
15:40:25.039 MQT: tasmota/kamer/sonoff01/cmnd/POWER = 
15:40:25.044 MQT: tasmota/kamer/sonoff01/tele/INFO1 = {"Info1":{"Module":"Generic","Version":"12.1.1(tasmota)","FallbackTopic":"cmnd/DVES_104C65_fb/","GroupTopic":"tasmota/kamer/tasmotas/cmnd/"}}
15:40:25.046 MQT: tasmota/kamer/sonoff01/tele/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"sonoff01-3173","IPAddress":"10.0.0.191"}}
15:40:25.048 MQT: tasmota/kamer/sonoff01/tele/INFO3 = {"Info3":{"RestartReason":"External System","BootCount":220}}
15:40:25.050 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER1":"OFF"}
15:40:25.051 MQT: tasmota/kamer/sonoff01/stat/POWER1 = OFF
15:40:25.053 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER2":"OFF"}
15:40:25.054 MQT: tasmota/kamer/sonoff01/stat/POWER2 = OFF
15:40:25.056 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER3":"OFF"}
15:40:25.057 MQT: tasmota/kamer/sonoff01/stat/POWER3 = OFF
15:40:25.059 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER4":"OFF"}
15:40:25.061 MQT: tasmota/kamer/sonoff01/stat/POWER4 = OFF
15:40:25.064 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER5":"OFF"}
15:40:25.065 MQT: tasmota/kamer/sonoff01/stat/POWER5 = OFF
15:40:25.067 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER6":"OFF"}
15:40:25.069 MQT: tasmota/kamer/sonoff01/stat/POWER6 = OFF
15:40:25.071 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER7":"OFF"}
15:40:25.072 MQT: tasmota/kamer/sonoff01/stat/POWER7 = OFF
15:40:25.419 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER4":"OFF"}
15:40:25.422 MQT: tasmota/kamer/sonoff01/stat/POWER4 = OFF
15:40:25.470 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER5":"OFF"}
15:40:25.471 MQT: tasmota/kamer/sonoff01/stat/POWER5 = OFF
15:40:25.521 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER6":"OFF"}
15:40:25.523 MQT: tasmota/kamer/sonoff01/stat/POWER6 = OFF
15:40:25.572 MQT: tasmota/kamer/sonoff01/stat/RESULT = {"POWER7":"OFF"}
15:40:25.574 MQT: tasmota/kamer/sonoff01/stat/POWER7 = OFF
15:40:26.461 QPC: Reset
15:40:29.387 MQT: tasmota/kamer/sonoff01/tele/STATE = {"Time":"2022-09-01T15:40:29","Uptime":"0T00:00:11","UptimeSec":11,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":33,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","Wifi":{"AP":1,"SSId":"mna_AP","BSSId":"E0:3F:49:09:D2:D0","Channel":8,"Mode":"11n","RSSI":100,"Signal":-43,"LinkCount":1,"Downtime":"0T00:00:05"}}
15:40:29.429 MQT: tasmota/kamer/sonoff01/tele/SENSOR = {"Time":"2022-09-01T15:40:29","ANALOG":{"A0":511}}

Question: What is going wrong ???

regards Marcel

**Comment by barbudor** [comment]
Please explain what you mean by "a reset every minute"
Do you mean a restart ?
Or a reset of every parameters and you have to reconfigure ?

**Comment by barbudor** [comment]
I believe you mean parameters are reset to default.

You have a problem with your Button_1 that Tasmota sees continuously pressed, triggering the recovery mecanism: https://tasmota.github.io/docs/Device-Recovery/#recovery-techniques

Solve your Button_1 problem
