### ISSUE TITLE
Google Charts are not loading because of a commas!

### ISSUE THREAD

**Issue by sawacs** [arendst/Tasmota#16462]
Hello.
ESP8266 and ESP32 platform...
My Tasmota 12.1.0.1 compilation with Polish language set.
I added Google Chart to my simple script. Since it didn't appear on the website.
I started checking the script. But that's not the problem in the script! 
I have debug the html generated by Tasmot www server, in the place where it should be located:
    ..... https://www.gstatic.com/charts/loader.js .....  
I got:
   <script type="text/javascript" src="https://www,gstatic,com/charts/loader,js"></script>
   <script type="text/javascript">google,charts,load('current',{packages: ['corechart']}); </script>
Of course, all the required for compilation options were set. 
I suspect that it is the language-specific settings that are causing this problem. 
In Polish, the separator f/e for numbers is "comma" and not "dot" as in other languages (we use f/e 23,124).

[script_and_html_source.txt](https://github.com/arendst/Tasmota/files/9526571/script_and_html_source.txt)

**Comment by barbudor** [comment]
@gemu2015

You shouldn't use `WSContentSend_PD(...)` to send those HTML strings but `WSContentSend_P(...)` to avoid conversion of `.` into `,`
Could you kindly fix it as you have a better view on the architecture ?
Thanks

**Comment by gemu2015** [comment]
ok, ill fix that tomorrow
