### ISSUE TITLE
BNC-60/U133TJ no longer display energy with latest Tasmota "lite"

### ISSUE THREAD

**Issue by Black6spdZ** [arendst/Tasmota#16525]
upgraded from 12.0.4.2 (lite) to12.1.1.2 (lite) and my BNC-60/U133TJ devices no longer report power. Is this intentional and if so why?

**Comment by barbudor** [comment]
Yes, move to full tasmota

https://github.com/arendst/Tasmota/commit/8c064c97494343f48950e4f4b46af0a30fe6025a#diff-00f571142d9f9ecce398802637a0fe4e073f1b2b6b36cd4712aba1a475c19567

**Comment by Black6spdZ** [comment]
thanks!
