### ISSUE TITLE
MODBUS decoder at SML leads to missing data

### ISSUE THREAD

**Issue by Erickrk** [arendst/Tasmota#16524]
### PROBLEM DESCRIPTION
Hello, I've been working with Tasmota and specially SML for one or two months now, and only in the past few days, I've noticed a curious behavior when using the "UUuuUUuu" mask that can lead to wrong Modbus readings. My testing SML script is available in the "TO REPRODUCE" section.

For this specific case, my desired reading value is 159257, which is reached by swapping both 16 bits' registers using the "UUuuUUuus" mask.

Before discovering the swap character, I was using the "UUuuUUuu" mask, which led me to said weird readings. It can be better shown by the binary values of the different masks, applied to the same frame:

![image](https://user-images.githubusercontent.com/55474466/190500715-f1ef3116-be75-4338-bebb-f605cade891c.png)

With this, I was able to see how the last byte from the second mask is 0000 when it should be 0010. My current direction is to think that the data processing from this specific mask won't deal well with values that exceed 65.536 and, for that reason, loses data not equal to zero at the High Byte. I've searched the source code for a reason for this behavior but only found out that data handling looks the same for both "UUuuUUuu" and "uuUUuuUU" masks, as can be seen below:
```
 else if (!strncmp(mp, "UUuuUUuu", 8)) {
              uint32_t val = (cp[0]<<24) | (cp[1]<<16) | (cp[2]<<8) | (cp[3]<<0);
              mp += 8;
              cp += 4;
              if (*mp == 's') {
                mp++;
                // swap words
                val = (val>>16) | (val<<16);
              }
              ebus_dval = val;
              mbus_dval = val;
            } else if (!strncmp(mp, "uuUUuuUU", 8)) {
              uint32_t val = (cp[1]<<24) | (cp[0]<<16) | (cp[3]<<8) | (cp[2]<<0);
              mp += 8;
              cp += 4;
              if (*mp == 's') {
                mp++;
                // swap words
                val = (val>>16) | (val<<16);
              }
              ebus_dval = val;
              mbus_dval = val;
```

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP12
- [ ] Tasmota binary firmware version number used:
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: PlatformIO
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
Available at the script. I've only changed GPIO2 to GPI8_LED1_INV at mytmplt8266 kModules8266[TMP_MAXMODULE_8285] PROGMEM so I can have my internal led configured since flashing.

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
20:43:20.650 RSL: STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"TEST/MAC_ADDRESS","ButtonTopic":"0","Power":1,"PowerOnState":1,"LedState":5,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
20:43:20.656 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Hardware Watchdog","Uptime":"0T03:00:22","StartupUTC":"2022-09-15T16:42:58","Sleep":50,"CfgHolder":4617,"BootCount":68,"BCResetTime":"2022-09-12T19:11:09","SaveCount":146,"SaveAddress":"FA000"}}
20:43:20.661 RSL: STATUS2 = {"StatusFWR":{"Version":"12.0.2(tasmota)","BuildDateTime":"2022-09-12T15:07:27","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"332/699"}}
20:43:20.666 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MY_SSID",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A190000000000","00000080","00006000","00006000","00000000"]}}
20:43:20.676 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":655,"Free":348,"Heap":17,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":3,"Features":["00000809","879AC787","043E8001","000000CF","010013C0","C000F989","00004004","00001000","14000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6,53"}}
20:43:20.682 RSL: STATUS5 = {"StatusNET":{"Hostname":"TEST-MAC-6373","IPAddress":"192.168.0.39","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"181.213.132.5","DNSServer2":"181.213.132.4","Mac":":::::","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
20:43:20.686 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_00D8E5","MqttUser":"","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
20:43:20.692 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-09-15T19:43:20","Local":"2022-09-15T20:43:20","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"06:27","Sunset":"19:03"}}
20:43:20.699 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-09-15T20:43:20","DATA":{"TEST_A":0,"TEST_B":0,"TEST_C":0,"TEST_D":0}}}
20:43:20.705 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-09-15T20:43:20","Uptime":"0T03:00:22","UptimeSec":10822,"Heap":17,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"MY_SSID","BSSId":"","Channel":2,"Mode":"11n","RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
You should have a 32bits variable larger than 65.536 and then try to read it using the second mask below, "UUuuUUuu". You can try using all the masks from the script and then change values to binary to make sure values have changed.
```
>D
>B
+>status 5
->sensor53 r
>M 1
+1,14,m,0,9600,DATA,5,1,010303ec
1,010304UUuuUUuus@i0:1,TEST_A,,TEST_A,0
1,010304UUuuUUuu@i0:1,TEST_B,,TEST_B,0
1,010304uuUUuuUUs@i0:1,TEST_C,,TEST_C,0
1,010304uuUUuuUU@i0:1,TEST_D,,TEST_D,0
#
```
### EXPECTED BEHAVIOUR
As said above, the processing code doesn't change much for both cases, so the high-byte variables have no reason to be lost for just one mask.

### SCREENSHOTS
Proof that this value was actually read from the UI:
![image](https://user-images.githubusercontent.com/55474466/190497373-e6035247-6507-4d60-b992-b38e4ace46a4.png)

### ADDITIONAL CONTEXT
I also haven't found a direct reference to the bit swapping option - using "s" at the end of a 32 bits mask -  at the documentation, it might be a nice idea to make the text more explicit about it.

**Comment by gemu2015** [comment]
ok, checked the issue, there is nothing wrong with the masking BUT the bug is that mbus_dval was a float by accident. it has to be double to fit the larger numbers.
i will do a pr soon.

**Comment by gemu2015** [comment]
from the docs, according to the trailing s:
"on long word values if a trailing s is added word order is reversed"

you are free to improve the docs, anybody can edit them

**Comment by Erickrk** [comment]
I wasn't familiar with the definition of trailing, thanks for showing it. I've tried to improve this small part of the docs anyway.
