### ISSUE TITLE
Error building tasmota32-Ru v12.0.2 with USE_LVGL enabled

### ISSUE THREAD

**Issue by thedemoncat** [arendst/Tasmota#16573]
### PROBLEM DESCRIPTION
Error building tasmota32-Ru v12.1.1 with USE_LVGL enabled

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): [robotdyn_ESP32R4](https://templates.blakadder.com/robotdyn_ESP32R4.html)
- [ ] Tasmota binary firmware version number used: v12.0.2
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Windows-x64 Platformio VSC
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_54_lvgl.ino: In function 'void start_lvgl(const char*)':
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_54_lvgl.ino:356:8: error: 'renderer' was not declared in this scope
   if (!renderer || uconfig) {
        ^~~~~~~~
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_54_lvgl.ino:356:8: note: suggested alternative: 'Renderer'
   if (!renderer || uconfig) {
        ^~~~~~~~
        Renderer
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_54_lvgl.ino:365:3: error: 'renderer' was not declared in this scope
   renderer->DisplayOnff(true);
   ^~~~~~~~
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_54_lvgl.ino:365:3: note: suggested alternative: 'Renderer'
   renderer->DisplayOnff(true);
   ^~~~~~~~
   Renderer
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_55_touch.ino: In function 'void TS_RotConvert(int16_t*, int16_t*)':
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_55_touch.ino:381:7: error: 'renderer' was not declared in this scope
   if (renderer) renderer->TS_RotConvert(x, y);
       ^~~~~~~~
D:/git/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_55_touch.ino:381:7: note: suggested alternative: 'Renderer'
   if (renderer) renderer->TS_RotConvert(x, y);
       ^~~~~~~~
       Renderer

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

```

### TO REPRODUCE
1. checkout to [v12.1.1.](https://github.com/arendst/Tasmota/releases/tag/v12.1.1)
2. uncomment [USE_LVGL](https://github.com/arendst/Tasmota/blob/v12.1.1/tasmota/my_user_config.h#L1062)
3. Builds Tasmota32

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT

I saw a similar error here - https://github.com/arendst/Tasmota/pull/13719

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Does compile. Used this setup
```
[env:tasmota32-lvgl_ru]
extends                 = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags} -DFIRMWARE_LVGL -DMY_LANGUAGE=ru_RU
board_build.f_cpu       = 160000000L
lib_extra_dirs          = lib/libesp32, lib/libesp32_lvgl, lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div, lib/lib_ssl, lib/lib_display
```
