### ISSUE TITLE
[tasmota.github.io] Corrections for errors in self signed Mosquitto doc

### ISSUE THREAD

**Issue by lhurt** [arendst/Tasmota#16602]
The page on [github.io documenting a self signed Mosquitto installation](https://tasmota.github.io/docs/Self-signed-Mosquitto/) has some errors.

It took me some time to successfully build an TLS version with full CA validation with my local CA. In order for other guys to save time the following changes have to be made.

[In section 2.2 Advanced: Using Full certificate validation](https://tasmota.github.io/docs/Self-signed-Mosquitto/#22-advanced-using-full-certificate-validation)

_Wrong macro identifier_
`#define INCLUDE_LOCAL_CA_CERT`

_Correct identifier_
`#define INCLUDE_LOCAL_CERT`

--

_Wrong path_
Copy or move the files created in step 1.6 above (local_ca_data.h and local_ca_descriptor.h) to the `$TASMOTAROOT/tasmota`

_Correct path_
Copy or move the files created in step 1.6 above (local_ca_data.h and local_ca_descriptor.h) to the `$TASMOTAROOT/tasmota/include`

--

_Wrong (filename typo)_
If desired, the two built-in certificates for Let's Encrypt and Amazon AWS may be omitted from the build by defining these macros in `user_config_overrirde.h`

_Correct_
If desired, the two built-in certificates for Let's Encrypt and Amazon AWS may be omitted from the build by defining these macros in `user_config_override.h`

**Comment by barbudor** [comment]
If you want to change the docs, click on the pencil icon on top right
