### ISSUE TITLE
ds18b20 probe not detect on sonoff when upgrade from 11.1. to 12.1.1

### ISSUE THREAD

**Issue by defaliz** [arendst/Tasmota#16673]
hi,
i upgrade my tasmota sonoff from 11.1. to 12.1.1 but know there is no ds18b20 probe listed in configuration menu..
do you know why ?
regards

**Comment by barbudor** [comment]
Doing twice the same error ends up with the same punition: issue closed

Neverthess Issuss are for qualified bug. To request help you should start a Discussion
You probably have uploaded the wrong variant (binary file) of Tasmota
