### ISSUE TITLE
Version 12.1.1 NOT sending MQTT autoconfig.

### ISSUE THREAD

**Issue by dss65MI** [arendst/Tasmota#16771]
Hello,
I upgraded from 10.1.0 to 12.1.0 but I noticed that verstion 12.1.1 does not send autoconfig messages.
Therefore autodiscovery on Home Assistant doesn't work.
At startup 10.1.0 sends:
14:16:03.504 MQT: homeassistant/switch/xxxxxx_RL_1/config = {"name":" etc. etc.
While 12.1.0 does not.
I am going back to 10.1.0 but I think you should know.
Thanks for the INCREDIBLE work you did.

**Comment by barbudor** [comment]
Home Assistant discovery has been deprecated in favor of Tasmota Discovery
You need to install HaTasmota plugin on Home Assistant

**Comment by nikito7** [comment]
SetOption19 0

**Comment by barbudor** [comment]
The old home assistant intégration is now deprecated.
You should use HATASMOTA plug-in in your HA with Setoption19 0

**Comment by nikito7** [comment]
"HaTasmota" is the python library :-)

![Screenshot_20221018-023255_Home Assistant](https://user-images.githubusercontent.com/45373783/196314687-a7d52710-cdeb-4900-9d89-db478ea11db4.jpg)
