### ISSUE TITLE
Publish integer to topic with rule

### ISSUE THREAD

**Issue by cconde** [arendst/Tasmota#16843]
This is absolutely simple.

I'm trying to create a rule to publish an integer to a topic, but a string with value is created instead.

It seems it's not possible, and I have a device that only takes integer values.

Best regards and thanks for such a great job!!!

**Comment by barbudor** [comment]
Issues are meant to report qualified bugs, not to ask for help

Nevertheless you should have filled the template or at least details what you've tried to do and why it is not satisfying.
MQTT message are always strings
