### ISSUE TITLE
Italiano Firmware mqtt connection error rc-4

### ISSUE THREAD

**Issue by hdjweb** [arendst/Tasmota#16912]
In italian firmware i have in 10 sonoff basic mqtt connection refused to ip broker mqtt rc-4. And i cannot upgrade or change language with english firmware. In english version All Is good. Same mqtt ip broker. How can i solve??i think It Will be firmware error. Can you help me??

**Comment by Jason2866** [comment]
Was a bug. Fixed in latest release version.
