### ISSUE TITLE
Tasmota ESP8622 BH1750 no Data

### ISSUE THREAD

**Issue by diphtong** [arendst/Tasmota#16937]
Hello,

i have a problem reading the BH17050 from i2c.

Installed Tasmota 12.2.0
configured i2c: D6 = SDA, D7 = SCL 

I2C configuration like mentioned here for ESP8266 ( D2 = SDA; D1 = SCL) does also not work
https://github.com/arendst/Tasmota/discussions/10827

i2cscan shows: MQT: stat/tasmota_FD96C3/RESULT = {"I2CScan":"Device(s) found at 0x23"}

So it can find the sensor, but it doesnt show any data from this sensor:

![Unbenannt](https://user-images.githubusercontent.com/91046964/198565370-f89c3962-6699-4a53-97a4-6c4717a9e60d.PNG)

Thank you in advance!

**Comment by sfromis** [comment]
If you upgrade to tasmota-sensors.bin.gz, BH1750 support is included, but not in the base install.

And don't open an issue (which is when having good reason to suspect bugs), when it is really just a question of how to use Tasmota.
