### ISSUE TITLE
Scripting Google Chart "cnth" Problem with Tasmota 12.x

### ISSUE THREAD

**Issue by ottelo9** [arendst/Tasmota#17038]
### PROBLEM DESCRIPTION
Scripting (not berry) problem with the Google Chart function "cnth" (cnthX/Y not yet in the documentation). @gemu2015 added this functionality to "xdrv_10_scripter.ino" on [31. March 2022](https://github.com/arendst/Tasmota/commit/d176aeaaf64899d68bbbe4263e34ddc0c1fe29c8) . With this you can create charts with seconds at x-axis. With cstr="cnth"+s(hours*240)+"/240" and then $gc(lt s4h "wr" "Leistung [W]" cstr2).
I can downgrade to 11.0.0.6 and upload the script via the ScriptEditor and everything is working fine. Upgrade to 12.x and the problem reappears :(.
My big array s4h[960] is filled up like this:
```
09:56:57.158 CMD: script?s4h
09:56:57.297 RSL: RESULT = {"script":{"s4h":[483,841,351,943,308,519,403,462,331,168,798,460,0,0,0,0,0,0,0 ..... ]
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP8266
- [x] Tasmota binary firmware version number used: 12.2.0, 12.1.1, (11.0.0.6)
  - [ ] Pre-compiled
  - [x] Self-compiled with TasmoCompiler
- [x] Flashing tools used: OTA (and even serial flashing)
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
- not relevant -
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
- not relevant -
```
- [x] Provide the output of this command: `Status 0`:
```
09:39:09.234 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_78D8A9","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
09:39:09.238 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T00:21:03","StartupUTC":"2022-11-11T08:18:06","Sleep":50,"CfgHolder":4617,"BootCount":5,"BCResetTime":"2022-11-10T20:22:38","SaveCount":13,"SaveAddress":"F7000"}}
09:39:09.243 RSL: STATUS2 = {"StatusFWR":{"Version":"12.2.0(TasmoCompiler-esp8266generic)","BuildDateTime":"2022-10-29T10:52:19","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"358/699"}}
09:39:09.248 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FRITZ!Box",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
09:39:09.257 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":574,"Free":428,"Heap":12,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","00C04582","042E0001","00000003","00000000","C000E989","00000004","00001000","54000000","00000000"],"Drivers":"1,2,4,6,8,10,12,18,19,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,53"}}
09:39:09.262 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-78D8A9-6313","IPAddress":"192.168.178.150","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.178.1","DNSServer2":"0.0.0.0","Mac":"50:02:91:78:D8:A9","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
09:39:09.266 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_78D8A9","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
09:39:09.270 RSL: STATUS7 = {"StatusTIM":{"UTC":"2022-11-11T08:39:09","Local":"2022-11-11T09:39:09","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":99}}
09:39:09.274 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-11-11T09:39:09","MT175":{"Total_in":0.00,"Total_out":0.00,"Power_curr":0}}}
09:39:09.279 RSL: STATUS11 = {"StatusSTS":{"Time":"2022-11-11T09:39:09","Uptime":"0T00:21:03","UptimeSec":1263,"Heap":12,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Wifi":{"AP":1,"SSId":"FRITZ!Box","BSSId":"3C:A6:2F:E8:2D:D6","Channel":1,"Mode":"11n","RSSI":32,"Signal":-84,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```

- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```
- not relevant -
```

### TO REPRODUCE
Self compiled via [TasmoCompiler](https://github.com/benzino77/tasmocompiler) and these defines to use SML and google chart:
```
#ifndef USE_SML_M
#define USE_SML_M
#endif
#ifndef USE_SML_SCRIPT_CMD
#define USE_SML_SCRIPT_CMD
#endif
#ifndef USE_GOOGLE_CHARTS
#define USE_GOOGLE_CHARTS
#endif
#ifndef LARGE_ARRAYS
#define LARGE_ARRAYS
#endif
#ifndef USE_SCRIPT_WEB_DISPLAY
#define USE_SCRIPT_WEB_DISPLAY
#endif
#ifndef USE_EEPROM
#define USE_EEPROM
#endif
#ifdef EEP_SCRIPT_SIZE
#undef EEP_SCRIPT_SIZE
#endif
#define EEP_SCRIPT_SIZE 6200
```

Create a new script (I upload my big script via the ScriptEditor):
```
>D 40
hour=0
; 4h power chart
M:s4h=0 960

>S
hour=hours
;put a random number into array for testing every 15s
if (secs%15==0)
then
	s4h=rnd(1000)
endif

; set x axis index to 4 hours a 15 sec therefore /240, no decimal point
hour-=4
if (hour<0)
then
	cstr2="cnth"+s(1.0((24-4+hours)*240)+(mins*4))+"/240"
else
	cstr2="cnth"+s(1.0((hours-4)*240)+(mins*4))+"/240"
endif
hour=hours

>W
; 4h power chart
$<div id="chart1" style="text-align:center;width:400px;height:100%%;padding:0px"></div>
$gc(lt s4h "wr" "Leistung [W]" cstr2)
$var options = {
$chartArea:{left:60,width:'83%%'},
$width:'100%%',
$legend:'none',
$vAxis:{format:'# W',viewWindow:{min:-300}},
$explorer:{actions:['dragToZoom', 'rightClickToReset']},
$title:'Verbrauch 4 Stunden [Watt]'
$};
$gc(e)
```

### EXPECTED BEHAVIOUR
With Tasmota 11.0.0.6 (includes the new cnth) the 4h chart (last 4h) works perfect. See screenshots.

### SCREENSHOTS
Working 4h Google Chart with cstr2="cnth"+s(1.0((hours-4)*240)+(mins*4))+"/240". Full 4 hours and on the right side is the actual time (left = -4h). The 24h chart below has no issues with the x-axis labels. Correct time stamps.
![Tasmota 11 0 0 6 Google Chart](https://user-images.githubusercontent.com/33122175/201297640-e0d9350f-9e8a-4b94-bd86-01e6f93e7498.png)

With Tasmota 12.1 or 12.2 I got this here. On the right side is the actual time-2h. And only ~2 hours on X-Axis. And take a look at the 24h chart labels.
![Tasmota 12 2 0 Google Chart](https://user-images.githubusercontent.com/33122175/201360622-738b4ba3-ec36-44c9-a029-3a6eb93a29f3.png)

After restart/boot I got this:
![Tasmota 12 2 0 Google Chart boot](https://user-images.githubusercontent.com/33122175/201303542-ddb449c4-c153-41cd-ba31-6b33718e1e9e.png)
Then after few secs:
![Tasmota 12 2 0 Google Chart error](https://user-images.githubusercontent.com/33122175/201303596-6abad1a1-a74f-4e95-909c-d70d9fa786f8.png)
And after ~30s this:
![Tasmota 12 2 0 Google Chart boot 2](https://user-images.githubusercontent.com/33122175/201303649-5c160c57-0b93-45c6-8ed7-b16fe7cc7239.png)

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
@gemu2015  Can you have a look and help?

**Comment by gemu2015** [comment]
i am already in contact with @ottelo9 at another forum about this issue.
i think we can close this here

**Comment by MarcoLeoncino** [comment]
Hi everyone, I am using the following code, based on the example you gave here above.

`>D 
hour=0
temp=0
M:s4h=0 960
cstr2="cnth0/120"

>T
temp=DS18B20#Temperature

>S
hour=hours

if (secs%15==0)
then
s4h=temp
endif

hour-=4
if (hour<0)
then
cstr2="cnth"+s(1.0((24-4+hours)*240)+(mins*4))+"/240"
else
cstr2="cnth"+s(1.0((hours-4)*240)+(mins*4))+"/240"
endif
hour=hours

>W
$<div id="chart1" style="width:360px;height:360px;margin:-15px 0 0 -18px;"></div>
$gc(lt s4h "wr" "Temperature [°C]" cstr2)
$var options = {
$chartArea:{left:30,width:'90%%',right:10},
$width:'90%%',
$legend:'none',
$vAxis:{format:'# °C',viewWindow:{min:0},viewWindow:{max:80}},
$title:'Boiler temperature last 4 hours [°C]'
$};
$gc(e)
#`

and I get a well working google chart. 

I have tried to replace the hours to 12, the minutes to 720, but I cannot get a working 12 h plot. 
Can you give me an hint about how the above code shall be modified to have a 12 hours plot?
Thanks a lot!

**Comment by gemu2015** [comment]
you can not keep 15 seconds resolution with 12 hours on an esp8266, so we switch to every minute

```
>D
hour=0
temp=0
M:s4h=0 720
cstr2="cnth0/120"

>T
temp=DS18B20#Temperature
>S
hour=hours
if (secs%60==0)
then
s4h=temp
endif

hour-=12
if (hour<0)
then
cstr2="cnth"+s(1.0((24-12+hours)*60)+mins)+"/60"
else
cstr2="cnth"+s(1.0((hours-12)*60)+mins)+"/60"
endif


>W
$<div id="chart1" style="text-align:center;width:400px;height:100%%;padding:0px"></div>
$gc(lt s4h "wr" "Temperature [°C]" cstr2)
$var options = {
$chartArea:{left:30,width:'90%%',right:10},
$width:'90%%',
$legend:'none',
$vAxis:{format:'# °C',viewWindow:{min:0},viewWindow:{max:80}},
$title:'Boiler temperature last 12 hours [°C]'
$};
$gc(e)
#
```

**Comment by MarcoLeoncino** [comment]
Thanks! Every 60 seconds is perfect!
