### ISSUE TITLE
zbbridge - device list is broken when EEPROM storage is used

### ISSUE THREAD

**Issue by Mrkvak** [arendst/Tasmota#17030]
### PROBLEM DESCRIPTION
List of devices (including their pretty names) is lost when device resets. The EEPROM is formatted to have `ZIGB_NAME2` and `saveZigbeeDevices()` is looking for `ZIGB_NAME4`. This causes `saveZigbeeDevices()` to silently fall thhrough and nothing is saved. The issue was likely introduced in commit f0cf998ca417d15c5dcf95f9eb7aa67fc6088c5a.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Zbbridge
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
1. Set device name (eg `ZbName 0x1234,testing`)
2. restart/powercycle device
3. The device won't be shown after reboot, and once it broadcasts again, it will be again visible as 0x1234

### EXPECTED BEHAVIOUR
Device name should be retained across reboots.

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
As explained in the closed PR
