### ISSUE TITLE
Home Assistant discovery for Sensors not working

### ISSUE THREAD

**Issue by tecno-roy** [arendst/Tasmota#17295]
I've build a magnet sensor module with WMOS-D1 mini (ESP8266) and as sensor the HMC5883L magnetometer.
Tasmota version 12.2.0.6
The Webinterface works fine and show the counters and induction values in uT.
My HomeAssistant (Superviesd) discover only the state data of my device. 
The sensor message has a syntax error:
18:53:52.419 MQT: GasMeter/tele/SENSOR = {"Time":"2022-12-06T18:53:52","COUNTER":{"C1":1156,"C2":0,"C3":0},"HMC5883L":{"XaxisInduction":-1031,"YaxisInduction":-888,"ZaxisInduction":1,"MagneticInduction":1360,"}

also the decovery message: 
18:53:52.419 MQT: GasMeter/tele/SENSOR = {"sn":{"Time":"2022-12-06T19:33:13","COUNTER":{"C1":1156,"C2":0,"C3":0},"HMC5883L":{"XaxisInduction":-1024,"YaxisInduction":-821,"ZaxisInduction":1,"MagneticInduction":1312,"},"ver":1}

I tried to correct the lines manually and published them via MQTT Explorer.
Discovery:
tasmota/discovery/BCDDC214C3A4/sensors = {"sn":{"Time":"2022-12-06T16:59:11","COUNTER":{"C1":1152,"C2":0,"C3":0},"HMC5883L":{"XaxisInduction":-454,"YaxisInduction":-238,"ZaxisInduction":1,"MagneticInduction":512}},"ver":1}

And a test with sensor data:
GasMeter/tele/SENSOR = {"Time":"2022-12-06T17:43:42","COUNTER":{"C1":1154,"C2":0,"C3":0},"HMC5883L":{"XaxisInduction":-463,"YaxisInduction":-242,"ZaxisInduction":1,"MagneticInduction":522}}
discovery and data works fine with my modification. 
All sensors were registered in the Home Assistant and the data was then displayed.

it looks like there is a little bug in the program?
The error is behind the last value - "MagneticInduction":123,"  - the last two letters - ," - are to much.

**Comment by barbudor** [comment]
PR already in
https://github.com/arendst/Tasmota/pull/17296/files

**Comment by tecno-roy** [comment]
Sorry,
my mistake, a closed curly bracket is missing at the end. 
For both (SENSOR and discovery)
Currently: ..."ver":1}
Should be: ..."ver":1}}
