### ISSUE TITLE
Not enough space on Wemos

### ISSUE THREAD

**Issue by kwaazaar** [arendst/Tasmota#17310]
I want to use the allsensors, but when uploading the file (firmware upload-screen), I get a not enough space.

**Comment by kwaazaar** [comment]
Figured it out myself: install http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz first. AFterwards it works.

**Comment by sfromis** [comment]
Instead of that, the simple procedure is to **not** download first, but do the upgrade directly via the URL from the OTA site (or another http server if you have one). Then Tasmota can automatically do a two-step upgrade via -minimal if and when needed.
