### ISSUE TITLE
Shelly 1v3 with Tasmota 12.2.0 forget DS18B20 Sensors

### ISSUE THREAD

**Issue by Basti-RX** [arendst/Tasmota#17352]
### PROBLEM DESCRIPTION
Shelly 1v3 with Tasmota 12.2.0 forget DS18B20 Sensors after a few hours

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Shelly 1v3
- [x] Tasmota binary firmware version number used: 12.2.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: NodeMCU-PyFlasher-4.0-x64
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

{"NAME":"Shelly 1v3 Temp","GPIO":[1344,0,0,1312,224,192,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

{"Status":{"Module":0,"DeviceName":"SHELLY-ZIRKULATIONSPUMPE","FriendlyName":["SHELLY-ZIRKULATIONSPUMPE"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:42:49","StartupUTC":"2022-12-11T15:45:08","Sleep":50,"CfgHolder":4617,"BootCount":514,"BCResetTime":"2022-09-19T09:04:13","SaveCount":2700,"SaveAddress":"F6000"},"StatusFWR":{"Version":"12.2.0(tasmota)","BuildDateTime":"2022.10.17 08:43:02","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"435/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Security Level 1",""],"TelePeriod":10,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]},"StatusMEM":{"ProgramSize":627,"Free":376,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"15701C","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000407","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"SHELLY-ZIRKULATIONSPUMPE","IPAddress":"192.168.178.54","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.178.10","DNSServer2":"0.0.0.0","Mac":"C4:5B:BE:76:92:E8","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.178.7","MqttPort":1883,"MqttClientMask":"SHELLY_ZIRKULATIONSPUMPE","MqttClient":"SHELLY_ZIRKULATIONSPUMPE","MqttUser":"sonoff","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2022-12-11T17:27:57","Local":"2022-12-11T18:27:57","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:33","Sunset":"16:52"},"StatusSNS":{"Time":"2022-12-11T18:27:57","Switch1":"OFF","DS18B20-1":{"Id":"01211399BDF7","Temperature":51.3},"DS18B20-2":{"Id":"0121139AAEC9","Temperature":48.7},"DS18B20-3":{"Id":"032111F98937","Temperature":50.7},"TempUnit":"C"},"StatusSTS":{"Time":"2022-12-11T18:27:57","Uptime":"0T01:42:49","UptimeSec":6169,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Security Level 1","BSSId":"38:10:D5:89:78:C5","Channel":11,"Mode":"11n","RSSI":100,"Signal":-43,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
DS18B20 hardware issue. Issue can not be solved in Tasmota code.

**Comment by sfromis** [comment]
Relevant link: https://github.com/cpetrich/counterfeit_DS18B20/

**Comment by Basti-RX** [comment]
Thank you for your answer. But please explain to me why sensors from the same order with similar ID's work perfectly on a Sonoff TH.

**Comment by sfromis** [comment]
Explaining with bad clones does not work exactly the same would likely take a deep analysis of the device, most likely not worth it.

**Comment by sfromis** [comment]
The usual thing to fiddle with for DS18B20 issues would be pullup strength, especially if not short wires.
