### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by pmknowles** [arendst/Tasmota#17372]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
This isn't an issue as such but it would be helpful if the documents could indicate from what version a new command is valid for. On Friday I compiled a ZigBee bin using TasmoCompiler. I have some Moes Temperature and Humidity sensors which suffer from the humidity scaling issues. I noticed ZbLoad in the commands list and spent 2 days trying to work out why it wouldn't work. I eventually found that ZbLoad only applies to version 12.2.0 (TasmoCompiler is still on 12.1)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [Y ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [Y] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [Y] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [Y] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [Y] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [TubesZB] Device used (e.g., Sonoff Basic): _____
- [12.1] Tasmota binary firmware version number used: _____
  - [N] Pre-compiled
  - [Y] Self-compiled
- [Y] Flashing tools used: ESPTools
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Tasmota docu describes commands available for latest release. Changes can be seen in [changelog.md](https://github.com/arendst/Tasmota/blob/development/CHANGELOG.md) There will be no info added when commands are introduced. Sorry, we dont have the resources to maintain the docu in such deep details. It is a lot of work to keep it (mostly) up to date with the changes done in Tasmota.

**Comment by pmknowles** [comment]
I'm sorry but how hard is it to do ZbLoad (v12.2+) when the new command is added? I've done numerous PRs to explain changes (like when the reset energy values commands were changed) to resolve issues being raised in the Google group.

**Comment by Jason2866** [comment]
We have been there, after a few weeks/month this info is not interresting anymore and just litters the docu. It does need maintaining.

**Comment by sfromis** [comment]
In case of trouble getting things to work, I'd much recommend to upgrade to latest release binary, before tearing out hairs, instead of assuming that current docs applies to older releases.

**Comment by pmknowles** [comment]
So, TasmoCompiler is currently on 12.1... I'm using ethernet and ZigBee which aren't in the release binaries. I agree that, once a major version change (V12 to V12) has happened knowing when a feature was introduced MIGHT be irrelevant but not in subversions. It also flies in the face of the advice on the upgrade page of 'It it ain't broke don't fix it'

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by s-hadinger** [comment]
@pmknowles We appreciate the immense work you're doing responding to users of Tasmota. About version in commands, we already tried and failed.

What I can say is that editing the Commands markdown page is hard and tedious. Unless you have a tool that would simplify this task, it's about editing scrambled markdown tables in a huge page. Not a pleasant experience.

**Comment by sfromis** [comment]
In the upgrade advice context, I consider an old version "broken" if it does not have the more recent features you want, and thus a good case for upgrading (of course with care). For new commands, it should be very easy to see that the command is not available in the particular version installed. What can be harder to check is enhanced behavior of commands, like new options for existing commands.

In principle, someone could create a tool, based on analysis of docs and/or source code, to detect what commands are present in each release, but due to the dynamic nature of how things are done, it would be a lot of work to verify the accuracy of such data for every release, and adapt to the differences in the source material.

More generally, while I could also see areas where a general improvement could be useful to users, my next question would be who can be expected to provide the ongoing effort to organize such strategies. Unless the answer would hypothetically be "me" I'm reluctant to make grand proposals.

**Comment by Jason2866** [comment]
For this example we have soon a solution. Time solves ;-)
Next release is just around the corner. It will be released before Christmas.
So let us ping @benzino77 to inform him and he gets prepared to update TasmoCompiler.

**Comment by pmknowles** [comment]
Yes, I’ve done a few edits on that page... openHAB has new document pages for each release (but they have far fewer releases)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jason2866** [comment]
> Yes, I’ve done a few edits on that page... openHAB has new document pages for each release (but they have far fewer releases)

We have discussed this variant too. Every release will add additional docu work. Tasmota main crew are only a few people. Every additional work "steals" time from coding new Tasmora features and bug fixing.
