### ISSUE TITLE
Wifi Connection issue with Update 12.3

### ISSUE THREAD

**Issue by stickilino** [arendst/Tasmota#17450]
Since 12.3 the Sonoff BasicR1 does not connect to Wifi anymore. Only downgrading by flashing solved the issue. Other sonoffs have as well bad Wifi connection but they are able to run. Update to 12.3.1 didn't solve the issue.

**Comment by Jason2866** [comment]
Please provide all infos requested in issue template, which you have deleted.
Without we cant help, and it will be closed.

**Comment by stickilino** [comment]
### PROBLEM DESCRIPTION
Since 12.3 the Sonoff BasicR1 does not connect to Wifi anymore. Only downgrading by flashing solved the issue. Other sonoffs have as well bad Wifi connection but they are able to run. Update to 12.3.1 didn't solve the issue.

### REQUESTED INFORMATION
- [ ] Device used Sonoff Basic R1
- [ ] Tasmota binary firmware version number used: 12.3 & 12.3.1
  - [ ] Pre-compiled YES
- [ ] Flashing tools used: OTA-Update
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`: can't because no connection
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`: NO

### TO REPRODUCE
_Steps to reproduce the behavior:
After reboot, device is not connecting. Status Light blinking, but does not offer Wifi for configuration.


### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen.
Connecting to Wifi


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._


### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**Comment by stickilino** [comment]
Within my network I have two Sonoff Basic R1, two Sonoff Basic R2, two Sonoff B1 light, five Sonoff S2X plugs.
The Basic R1 have Wifi problems since update on 12.3
Nothing else changed except the OTA update ...

**Comment by Jason2866** [comment]
Closing since needed infos are not provided
