### ISSUE TITLE
PID-Control destroys internal parameter with Tasmota Console in the Web UI

### ISSUE THREAD

**Issue by Wintespe** [arendst/Tasmota#17618]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

This problem report refers to the PID-feature implemented in xdrv_49_pid.ino.

Entering a command in the Tasmota webUI console menu, usually the syntax is:

     Command<Index> followed by an optional parameter

If you enter a Pid-command without the optional parameter the internal value - that the command refers to - is destroyed. It will be overwritten by zero. E.g. PidSp 20.0 set the internal value to 20.0 and just the command PidSp destroy it. Due to the described behaviour you are not able to read back the Pid-values via HTTP requests.

Code analysis
In the PID controller at line 278 in xdrv_49_pid.ino you find:

```
void CmndSetSp(void) {
  Pid.pid.setSp(atof(XdrvMailbox.data));
  ResponseCmndFloat(atof(XdrvMailbox.data), 1);
}
```

The statement 
`Pid.pid.setSp(atof(XdrvMailbox.data));`
writes something to the internal member, regardless of a command parameter exists or not. If there is no parameter, the internal value become 0.

The statement 
`ResponseCmndFloat(atof(XdrvMailbox.data), 1);`
return the entered and not the new setted value. This value can differ if, for example, it was too large and internally limited.

To fix the problem, without handling of unused index, change the function to:

```
void CmndSetSp(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setSp(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getSp(), 1);
}
```
This problem relates to all Pid commands. Refer to 
ADDITIONAL CONTEXT
for a solution.

Another issue and a feature request for the PID-feature is in preparation. Should I open a new request for this?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): NodeMcu
- [x] Tasmota binary firmware version number used: 11.0.1 and avove
  - [ ] Pre-compiled
  - [x] Self-compiled
- [ ] Flashing tools used:  Tasmotizer
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
na
```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
na
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
na

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

16:39:41.077 **CMD: PidSp 19.5**
16:39:41.083 RSL: RESULT = {"PidSp":19.5}
16:39:56.299 **CMD: status 10**
16:39:56.308 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-12-30T16:39:56","DS18B20":{"Id":"DFD5E30264FF","Temperature":26.9},"PID":{"PidPv":0.00,"PidSp":19.50,"PidPb":5.00,"PidTi":1800.00,"PidTd":15.00,"PidInitialInt":0.50,"PidDSmooth":3.00,"PidAuto":1,"PidManualPower":0.00,"PidMaxInterval":300,"PidUpdateSecs":0,"PidPower":0.00},"TempUnit":"C"}}
16:40:05.859 **CMD: PidSp**
16:40:05.865 RSL: RESULT = {"PidSp":0.0}
16:40:13.931 **CMD: status 10**
16:40:13.940 RSL: STATUS10 = {"StatusSNS":{"Time":"2022-12-30T16:40:13","DS18B20":{"Id":"DFD5E30264FF","Temperature":26.8},"PID":{"PidPv":0.00,"PidSp":0.00,"PidPb":5.00,"PidTi":1800.00,"PidTd":15.00,"PidInitialInt":0.50,"PidDSmooth":3.00,"PidAuto":1,"PidManualPower":0.00,"PidMaxInterval":300,"PidUpdateSecs":0,"PidPower":0.00},"TempUnit":"C"}}

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Entering a command in the Tasmota console, usually the syntax is:
Command followed by an optional Value

If Value is missing, the internal value is returned.
If Value is present, the internal value will be overwritten and the new (setted) one is returned. 

Remark: The entered and the new internal value can be different. E.g. if the new value was too high and was limited internally. The internal value should returned.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
na

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

To fix the Pid problems replace line 267 .. 333 in xdrv_49_pid.ino 
Remark: For a xx.Set() member function the corresponding xx.Get() member function exists in the PID class. 

```
void CmndSetPv(void) {
  Pid.last_pv_update_secs = Pid.current_time_secs;
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setPv(atof(XdrvMailbox.data), Pid.last_pv_update_secs);
  // also trigger running the pid algorithm if we have been told to run it each pv sample
  if (Pid.update_secs == 0) {
    // this runs it at the next second
    Pid.run_pid_now = true;
  }
  ResponseCmndFloat(Pid.pid.getPv(), 1);
}

void CmndSetSp(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setSp(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getSp(), 1);
}

void CmndSetPb(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setPb(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getPb(), 1);
}

void CmndSetTi(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setTi(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getTi(), 1);
}

void CmndSetTd(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setTd(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getTd(), 1);  
}

void CmndSetInitialInt(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setInitialInt(atof(XdrvMailbox.data));
  ResponseCmndNumber(Pid.pid.getInitialInt());
}

void CmndSetDSmooth(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setDSmooth(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getDSmooth(), 1);
}

void CmndSetAuto(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setAuto(atoi(XdrvMailbox.data));
  ResponseCmndNumber(Pid.pid.getAuto());
}

void CmndSetManualPower(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setManualPower(atof(XdrvMailbox.data));
  ResponseCmndFloat(Pid.pid.getManualPower(),1);
}

void CmndSetMaxInterval(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.pid.setMaxInterval(atoi(XdrvMailbox.data));
  ResponseCmndNumber(Pid.pid.getMaxInterval());
}

void CmndSetUpdateSecs(void) {
  if (XdrvMailbox.data_len > 0 && XdrvMailbox.payload != -99) Pid.update_secs = (atoi(XdrvMailbox.data));
  if (Pid.update_secs < 0)
    Pid.update_secs = 0;
  ResponseCmndNumber(Pid.update_secs);
}
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
You're right.

I'll fix now replacing ``atof()`` also with ``CharToFloat()`` as the atof library is way to big. (See comments at CharToFloat()).

**Comment by Wintespe** [comment]
@[arendst](https://github.com/arendst) I changed atof() to CharToFloat()
Result: 654944 bytes were bloated to 654992 bytes.
This is probably due to the fact that atoi() is called in many other places.

**Comment by arendst** [comment]
No. It's caused by a few other atof()'s. If I have only USE_TIMEPROP and USE_PID in the mix I gain 8k!!

I'll change all atof() and will release soon. Hold tight.

**Comment by Wintespe** [comment]
Ok, Thanks.
What about the question:  Another issue and a feature request for the PID-feature is in preparation. Should I open a new request for this?

**Comment by arendst** [comment]
Yes pls. If it's an issue open an issue. If it's a feature request open a discussion

**Comment by Wintespe** [comment]
Thanks for the effort
