### ISSUE TITLE
MQTT Full Topic cannot be set to %topic%/%prefix%/ 

### ISSUE THREAD

**Issue by fritz47110815** [arendst/Tasmota#17624]
### PROBLEM DESCRIPTION
MQTT Full Topic cannot be set to %topic%/%prefix%/ 
After the restart Full Topic will be set to NaN

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP3266
- [x] Tasmota binary firmware version number used: 12.3.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Included Firmware Upgrade
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
22:52:35.990 CMD: Backlog Template; Module; GPIO 255
22:52:36.049 MQT: NaN/RESULT = {"NAME":"Sonoff S26R2","GPIO":[32,1,1,1,0,0,0,0,224,320,0,0,0,0],"FLAG":0,"BASE":8}
22:52:36.261 MQT: NaN/RESULT = {"Module":{"8":"Sonoff S2X"}}
22:52:36.463 MQT: NaN/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Open Configuration MQTT and file %topic%/%prefix%/ under Full Topic. Allow restart

### EXPECTED BEHAVIOUR
Full Topic will be set to %topic%/%prefix%/

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
All my devices have `%topic%/%prefix%/` and work with that.

You should always fill in the documentation parts of the template to show what happens.

**Comment by fritz47110815** [comment]
I am sorry - it was a misconfiguration of the MQTT broker.

**Comment by fritz47110815** [comment]
Misconfiguration - no issue
