### ISSUE TITLE
Tasmota + Vindriktning +WPSE342 => CCS811 Not detected [HW SOLVED]

### ISSUE THREAD

**Issue by Spiace1974** [arendst/Tasmota#17647]
I wanted to add to the IKEA Vindriktning the abilty to connect to Wifi and broadcast some informations.
I used :
- Vindriktning 
- Wemos D1 Mini 
- Velleman WPSE342 (combo board that senses the atmospheric quality by using the popular CCS811 and BME280 ICs being i2c compatible)

**Problem** : When I uploaded Tasmota Mega to the Wemos board and switched it on, I received only the informations from the BME 280 and the Vindriktning.

**Searching** :

- Pin "Wake" of WPSE342 to GND => It didn't change.
- Pin "Wake" of WPSE342 to 3V3 => It didn't change

**Solution (RTFM)** :
On this combo board , you can choose the i2c address of the 2 sensors:

- BME280 : Open 0x77 / Close 0x76
- CCS811 : Open 0x5B / Close 0x5A

As I read in the list of supported I2C devices, the BME280 can either use i2c 0x77 or 0x76 address, and the CCS811 can only use i2c 0x5A address.

With a soldering iron, some solder and a soldering point between the two pins on the WPSE342 to choose the address 0x5A, it works.

Would it be possible to insert the two addresses (0x5A and 0x5B) for the ccs811 sensor in the tasmota code so that it works right away ?

(*In the worst case, this issue will allow others to solve this problem with a little less difficulty*)

**Comment by barbudor** [comment]
This is already supported with USE_CCS811_V2
I've pushed a PR to @Jason2866 's builds for swapping USE_CCS811 to USE_CCS811_V2 if he is ok with that
https://github.com/Jason2866/Tasmota-build/pull/11
