### ISSUE TITLE
all settings gone

### ISSUE THREAD

**Issue by montyfert** [arendst/Tasmota#17744]
me again 
uptill yesterday everything working great had weather icon in the middle mqtt temps either side .
today had to set it up again .

_Originally posted by @montyfert in https://github.com/arendst/Tasmota/discussions/13590#discussioncomment-4728444_

**Comment by montyfert** [comment]
woud it be posible to add config backup option .
thanks 
martin

**Comment by montyfert** [comment]
hi there isnt a backup config in the wled web ui.
martin

**Comment by sfromis** [comment]
Look harder, in the "Configuration" menu.

**Comment by montyfert** [comment]
no still cant find it 
![image](https://user-images.githubusercontent.com/74438819/213541157-b031fe8f-811b-4f3d-88c0-716a01cbb91b.png)

**Comment by sfromis** [comment]
I was referring to what you have in Tasmota, and that screenshot is not from Tasmota.

**Comment by montyfert** [comment]
am i in the wrong place

**Comment by barbudor** [comment]
Yes
Here is Tasmota
Wled is here : https://github.com/Aircoookie/WLED

**Comment by montyfert** [comment]
thanks

**Comment by arendst** [comment]
Closing as not a tasmota issue.
