### ISSUE TITLE
sum of Friendly Names total characters exceed limit

### ISSUE THREAD

**Issue by segaura** [arendst/Tasmota#17919]
### PROBLEM DESCRIPTION
Enabling PCF8574 support allow to add up to 32 additional input/output.
All of them can be paired with a long Friendly Name (32 characters recommended for Alexa integration, but field is not limited to).
Easily the sum of the length appeards to exceed the maximum allowed (less than 200 characters) so the `FriendlyName` field, for instance, in serialized "`STATUS`" topic become malformed (truncated).

### REQUESTED INFORMATION
_See, my friends, I've_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Wemos D1 Mini 4MB Flash
- [X] Tasmota binary firmware version number used: 12.3.1
  - [X] Self-compiled
- [X] Flashing tools used: OTA via tasmota-minimal 12.3.1 already installed
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

15:08:24.032 CMD: Backlog Template; Module; GPIO 255
15:08:24.110 MQT: my/home/topic/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
15:08:24.325 MQT: my/home/topic/stat/RESULT = {"Module":{"18":"Generic"}}
15:08:24.577 MQT: my/home/topic/stat/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"32":"Button1"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"640":"I2C SDA"},"GPIO13":{"608":"I2C SCL"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [X] Provide the output of this command: `Status 0`:

**please note the malformed (truncated) FriendlyName field in the first response row**

```lua

15:15:07.604 CMD: Status 0
15:15:07.613 MQT: my/home/topic/stat/STATUS = {"Status":{"Module":18,"DeviceName":"my-real-device-name","FriendlyName":["01234567890123456789012345678901","01234567890123456789012345678901","01234567890123456789012345678901","01234567890123456789012345678901","01234567890123456789012345678901","01234567890123456789012],"Topic":"ingresso","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
15:15:07.659 MQT: my/home/topic/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"0T00:07:06","StartupUTC":"2023-02-08T14:08:01","Sleep":50,"CfgHolder":4617,"BootCount":18,"BCResetTime":"2023-02-06T18:52:03","SaveCount":87,"SaveAddress":"F6000"}}
15:15:07.695 MQT: my/home/topic/stat/STATUS2 = {"StatusFWR":{"Version":"12.3.1(tasmota)","BuildDateTime":"2023-02-06T19:30:57","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"491/699"}}
15:15:07.718 MQT: my/home/topic/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["myhomessid",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C009","2805C80001000600003C5A0A002800000000","80800080","00006000","00004000","00000000"]}}
15:15:07.750 MQT: my/home/topic/stat/STATUS4 = {"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":25,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640E0","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F8A4787","04100001","000000CF","010013C0","40003A01","00004000","00000000","04000020","00000000"],"Drivers":"1,2,3,4,5,6,8,9,10,12,20,21,24,26,28,29,62","Sensors":"1,2,3,4,5,6"}}
15:15:07.783 MQT: my/home/topic/stat/STATUS5 = {"StatusNET":{"Hostname":"ingresso-6209","IPAddress":"192.168.1.140","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.103","DNSServer2":"8.8.8.8","Mac":"A0:20:A6:0A:F8:41","Webserver":2,"HTTP_API":1,"WifiConfig":2,"WifiPower":17.0}}
15:15:07.811 MQT: my/home/topic/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.222","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0AF841","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:15:07.835 MQT: my/home/topic/stat/STATUS7 = {"StatusTIM":{"UTC":"2023-02-08T14:15:07","Local":"2023-02-08T15:15:07","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"08:10","Sunset":"17:58"}}
15:15:07.857 MQT: my/home/topic/stat/STATUS10 = {"StatusSNS":{"Time":"2023-02-08T15:15:07","PCF8574-1":{"D0":1,"D1":1,"D2":1,"D3":1,"D4":1,"D5":1,"D6":1,"D7":1}}}
15:15:07.872 MQT: my/home/topic/stat/STATUS11 = {"StatusSTS":{"Time":"2023-02-08T15:15:07","Uptime":"0T00:07:06","UptimeSec":426,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":25,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"myhomessid","BSSId":"00:EB:D8:17:9E:9E","Channel":2,"Mode":"11n","RSSI":98,"Signal":-51,"LinkCount":1,"Downtime":"0T00:00:05"}}}
```

### TO REPRODUCE

- enable all (four?) PCF8574 related `#define`s while building custom image
- Configuration -> PCF8574 -> put all the 8 additional GPIO in output mode
- Configuration -> Others -> assign a long enough friendly name to each of the 8 outputs, e.g. 32 characters each, like mine "`01234567890123456789012345678901`"

### EXPECTED BEHAVIOUR
- Friendly Name should be well formed or
- An error should be shown while trying to enter too long Friendly Names or
- Documentation could give guidance on how to configure Friendly Name, specifically linking this to the PCF8574 and other GPIO expansion modules, which suffer the problem the most

### ADDITIONAL CONTEXT
- MQTT enabled
- The problem does not limit normal device operation
- I've had only issues while adding the devide to TasmoAdmin, see https://github.com/TasmoAdmin/TasmoAdmin/issues/771
- I already solved my only-8-additional-GPIO-issue, limiting my FriendlyNames

**Comment by Jason2866** [comment]
@segaura You are kindly invited to add the info to the Tasmota documentation.
It is Open Source too.

**Comment by segaura** [comment]
Thanks for all the insights and suggestions, I am new to most of these "advanced usages" of Tasmota.

Regarding the 32 chars limit, it is possible that I have seen this [documentation paragraph](https://tasmota.github.io/docs/Commands/#management) and my brain remembered the limit and the word Alexa altogether

![image](https://user-images.githubusercontent.com/11215285/217608735-d26fb698-772c-45b2-ad75-60827c1dd1a2.png)

neither this `FriendlyName<x>` nor the corresponding input box in the WebUI enforces the limit on the size to 32 characters, regardless of the reason why this limit was documented or presente somewhere else.

Same for adding string pool size dimension in documentation, I have not enough understanding to propose a correct PR in the documentation project, but I can try:  can you point me to where the pool is created/accessed in the codebase?

In addition, it is not clear to me if it is possible, or why it is not recommended, to allow a custom build to expand this limit, for instance when someone knows while building that he is going to connect 32 "named" relays to a single device.

**Comment by barbudor** [comment]
I though FriendlyNames where limited to 8?
May be I was limiting my head to the ESP8266...

**Comment by sfromis** [comment]
You are correct about the [8-name limit](https://github.com/arendst/Tasmota/blob/development/tasmota/include/tasmota.h#L133), barbudor

I imagine that the next suggestion would be to increase the limit to accommodate the number of possible power channels :grinning:

**Comment by barbudor** [comment]
Ah, I was afraid he wants 32 friendly names 😂
