### ISSUE TITLE
When upgradig devices with Si7021 Temp Sensor, randomly shows NULL! value

### ISSUE THREAD

**Issue by Gordus-Arrechus** [arendst/Tasmota#18054]
### PROBLEM DESCRIPTION
After upgrading to 12.4.0, 2 devices with Temperature Sensor Si7021 show temp as NULL! randomly, it works eventually but randomly shows as Null

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff Basic & ESP01
- [X ] Tasmota binary firmware version number used: 12.4.0
  - [X] Pre-compiled
  - [ ] Self-compiled
- [X ] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Load 12.4.0 on device with Si7021 Sensor, if you go back to 12.3.1 no issue.

### EXPECTED BEHAVIOUR
Temperature should be a float value and not NULL!!

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
Already addressed in https://github.com/arendst/Tasmota/issues/17944
