### ISSUE TITLE
CE Smart Home Dimmer (WF500D) failed to work with tasmota 12

### ISSUE THREAD

**Issue by wyxcoder** [arendst/Tasmota#18095]
I have CE Smart Home Dimmer (WF500D), I flashed with 8.5 and it worked fine. But After I flashed with 12, It doesn't work anymore. Any suggestions?

**Comment by barbudor** [comment]
Crystal balls being under maintenance could you please elaborate a little more?
12 not being an exact Tasmota version please provide exact version
Also please upgrade to latest development version and report logs with Weblog 3 from the start of Tasmota
Thanks

**Comment by wyxcoder** [comment]
Thanks for the quick reply. I figured out there was a break change after 8. So I retried by upgrade to 9 first and then latest, it worked.
