### ISSUE TITLE
LSC rgbww RGB stripe with brighter led since 12.3.1

### ISSUE THREAD

**Issue by kotarokun** [arendst/Tasmota#18137]
### PROBLEM DESCRIPTION
Since updating my LSC rgbww led strips after soldering an esp12 like seeing [here](https://templates.blakadder.com/lsc_smart_connect_led_strip.html) is very brighter in lowest warm white level. I use these at night under my bed an in version 12.3.1 and 12.4 it is much much brighter in lowest level of warm white light. 
After flashing back to 12.2 it is normal dark Like I know from before. So it seems like an software change.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): LSC rgbww led stripe
- [x] Tasmota binary firmware version number used: 12.3.1 and 12.4
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: tasmotadmin in Home assistant 
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
22:17:38.082 SRC: WebConsole from 192.168.179.176
22:17:38.085 CMD: Grp 0, Cmd 'BACKLOG', Idx 1, Len 26, Pld -99, Data 'Template; Module; GPIO 255'
22:17:38.314 CMD: Grp 0, Cmd 'MODULE', Idx 1, Len 0, Pld -99, Data ''
22:17:38.319 MQT: OG/SZ/stat/DVES_C5B807/MODULE = {"Module":{"0":"LSC RGBW Strip"}}
22:17:38.520 SRC: Backlog
22:17:38.523 CMD: Grp 0, Cmd 'GPIO', Idx 1, Len 3, Pld 255, Data '255'
22:17:38.532 MQT: OG/SZ/stat/DVES_C5B807/GPIO = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"1088":"IRrecv"},"GPIO4":{"416":"PWM1"},"GPIO5":{"419":"PWM4"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"417":"PWM2"},"GPIO13":{"420":"PWM5"},"GPIO14":{"418":"PWM3"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}
22:17:38.610 HTP: Befehl

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
2:20:22.382 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 0, Data '0'
22:20:22.388 MQT: OG/SZ/stat/DVES_C5B807/STATUS = {"Status":{"Module":0,"DeviceName":"OG_SZ_RGBWW","FriendlyName":["Schlafzimmer RGB Bett"],"Topic":"DVES_C5B807","ButtonTopic":"","Power":1,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":1,"PowerRetain":1,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
22:20:22.393 MQT: OG/SZ/stat/DVES_C5B807/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://192.168.xxx.90:9541/data/firmwares/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:35:27","StartupUTC":"2023-03-08T20:44:55","Sleep":50,"CfgHolder":4617,"BootCount":304,"BCResetTime":"2020-09-13T11:38:37","SaveCount":9877,"SaveAddress":"FA000"}}
22:20:22.399 MQT: OG/SZ/stat/DVES_C5B807/STATUS2 = {"StatusFWR":{"Version":"12.2.0(tasmota)","BuildDateTime":"2022.10.17 08:43:02","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"452/699"}}
22:20:22.403 MQT: OG/SZ/stat/DVES_C5B807/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxx",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["04028239","2805C80001000600003C5A0A192800000000","10080280","00006000","00004000","00000000"]}}
22:20:22.414 MQT: OG/SZ/stat/DVES_C5B807/STATUS4 = {"StatusMEM":{"ProgramSize":627,"Free":376,"Heap":21,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000407","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
22:20:22.423 MQT: OG/SZ/stat/DVES_C5B807/STATUS5 = {"StatusNET":{"Hostname":"DVES-C5B807-6151","IPAddress":"192.168.xxx.88","Gateway":"192.168.xxx.x","Subnetmask":"255.255.255.0","DNSServer1":"192.168.xxx.1","DNSServer2":"0.0.0.0","Mac":"EC:FA:BC:C5:xx:xx","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
22:20:22.427 MQT: OG/SZ/stat/DVES_C5B807/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.xxx.34","MqttPort":1883,"MqttClientMask":"DVES_C5B807","MqttClient":"DVES_C5B807","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
22:20:22.435 MQT: OG/SZ/stat/DVES_C5B807/STATUS7 = {"StatusTIM":{"UTC":"2023-03-08T21:20:22","Local":"2023-03-08T22:20:22","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"07:18","Sunset":"18:43"}}
22:20:22.440 MQT: OG/SZ/stat/DVES_C5B807/STATUS10 = {"StatusSNS":{"Time":"2023-03-08T22:20:22"}}
22:20:22.448 MQT: OG/SZ/stat/DVES_C5B807/STATUS11 = {"StatusSTS":{"Time":"2023-03-08T22:20:22","Uptime":"0T00:35:27","UptimeSec":2127,"Heap":21,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"POWER1":"on","Dimmer":1,"Color":"3,0,0,0,3","HSBColor":"0,100,1","White":1,"CT":500,"Channel":[1,0,0,0,1],"Scheme":0,"Fade":"on","Speed":5,"LedTable":"on","Wifi":{"AP":1,"SSId":"xxxxl","BSSId":"E0:28:6D:46:xx:xx","Channel":1,"Mode":"11n","RSSI":46,"Signal":-77,"LinkCount":1,"Downtime":"0T00:00:05"}}}


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
After update to 12.3.1 or 12.4 it is bright. And after downgrade to 12.2 it is normal low light. Even after Repetition 

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by kotarokun** [comment]
Nothing? Or is there an fault of my side?

**Comment by Nsalty84** [comment]
Glad I'm not the only one.

Just updated my bulbs (CSH-B22WW10W) from 12.0.2 to 12.5 and wondered why they got so much brighter. 
12.2 is fine, problem starts with 12.3.1, guess I'll be sticking to 12.2

**Comment by mkaatman** [comment]
I'm going to try this on some of my bulbs that I want to be brighter! Subscribing to see what comes of this.

**Comment by stefanbode** [comment]
can you check if `ledtable 0` and `ledtable 1` makes still a difference on the new version in low light conditions? I checked the light code and there is no change visible. From which date is the latest release that works? I go back to November 2022 and did not find something relevant

**Comment by jonschz** [comment]
Have you tried to backup your configuration and then `Reset 6`? I have had lights act up in weird ways after upgrading, which got fixed by a reset.
