### ISSUE TITLE
Web Admin Password and User automatically capitalized in new SmartThings Edge Driver

### ISSUE THREAD

**Issue by Dncgpt6149** [arendst/Tasmota#18159]
### PROBLEM DESCRIPTION
I am running Tasmota 12.4.0 on an ESP32 board and got the full version of the SmartThings new Edge driver
After my device is installed, Smartthings driver is installed, all is working well with no web admin password.

Then i proceed to create a password and I enter it in the web admin. Default user is "admin" and is case sensitive.

I introduce the same user name and password in SmartThings device settings screen.
Right there in the settings screen, both the first letter of the user name and the first letter of the password password are capitalized.
As such, "admin" becomes "Admin" and SmartThings no longer communicated with the device (cannot authenticate)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): __ESP32___
- [x ] Tasmota binary firmware version number used: __12.4.0___
  - [x ] Pre-compiled
  - [ ] Self-compiled
- [x ] Flashing tools used: _ESP Flasher____
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Well, Tasmota admin mode user id is fixed at "Admin". Tasmota does not capitalize anything you may be doing outside of Tasmota, and whatever you have have in SmartThings is not part of the Tasmota project.
