### ISSUE TITLE
Suggestion: Prevent flashing zbbridge on 1M devices

### ISSUE THREAD

**Issue by hardfalcon** [arendst/Tasmota#18346]
After flashing the Tasmota 12.4.0 tasmota-minimal.bin.gz image onto my Nous A1T, I've unfortunately flashed the tasmota-zbbridge.bin.gz image onto the device because I had somehow overlooked that this isn't intended for 1M devices. It seems that there's no way to flash anything else, neither the minimal image nor https://github.com/Jason2866/ESP8266MinimalHTTPUpdater (even with `SetOption78 1`, I still get the `Upload Failed` `Not enough space` error) other than flashing using a serial console (which would require me to more or less physically damage/destroy the device's plastic casing).

IMO it would therefore be a desirable feature to prevent flashing zbbridge on 1M devices to prevent other people from committing the same mistake.

**Comment by arendst** [comment]
Sorry you managed to flash the wrong binary image.

At OTA time the type of binary file is checked and if wrong an error message is thrown. The functionality of the new binary is unknown. At restart time after the OTA update again the new binary functionality is unknown too. So keeping people safe from OTA uploading bad binaries is not possible.

Think of it like a microwave oven; when just walked the dog in the rain you wouldn't put your dog into the microwave to dry. If you lived in the USA you would even find a note in the user guide what NOT to put in the microwave. In the rest of the world we are supposed to know not to put it in there ;-)
