### ISSUE TITLE
Ser2Net from SmartMeter bad data

### ISSUE THREAD

**Issue by ressof** [arendst/Tasmota#18400]
### PROBLEM DESCRIPTION
I get bad data and different data from a Electric Smart Meter that sends data by serial link to a Wemos D1 mini on GPIO3. I have the tasmota act as an Ser2Net device and also meassure temperature with a DHT22 and transfer that by MQTT to domoticz.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Wemos D1 mini pro
- [x] Tasmota binary firmware version number used: 12.4.0 & 12.3.0
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: OTA
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
06:28:00.345 MQT: stat/elmatare/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
06:28:00.580 MQT: stat/elmatare/RESULT = {"Module":{"0":"Generic"}}
06:28:00.840 MQT: stat/elmatare/RESULT = {"GPIO0":{"3840":"Output Hi"},"GPIO1":{"0":"None"},"GPIO2":{"1216":"AM2301"},"GPIO3":{"5120":"TCP Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"5088":"TCP Tx"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
06:29:16.307 MQT: stat/elmatare/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":50,"Free":461,"Rules":"ON System#Boot do TCPStart 8888,192.168.0.10 endon"}}
06:29:16.541 MQT: stat/elmatare/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
06:29:16.788 MQT: stat/elmatare/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
06:29:42.212 MQT: stat/elmatare/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"elmatare","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
06:29:42.220 MQT: stat/elmatare/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T09:18:32","StartupUTC":"2023-04-12T20:11:10","Sleep":50,"CfgHolder":4617,"BootCount":33,"BCResetTime":"2023-04-12T18:45:26","SaveCount":63,"SaveAddress":"FC000"}}
06:29:42.226 MQT: stat/elmatare/STATUS2 = {"StatusFWR":{"Version":"12.3.0(TasmoCompiler-esp82664M)","BuildDateTime":"2023-04-12T20:08:53","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"380/699"}}
06:29:42.234 MQT: stat/elmatare/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["smarthome",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
06:29:42.251 MQT: stat/elmatare/STATUS4 = {"StatusMEM":{"ProgramSize":608,"Free":1436,"Heap":21,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","0890458E","04260001","600207C3","180C0000","D032F881","000B208C","00201000","54000040","00000080"],"Drivers":"1,2,4,6,7,8,10,12,18,19,22,24,26,29,30,35,37,38,41,45,50,62","Sensors":"1,2,4,5,6,7,8,9,14,26,27,38,39,46,47,55,58,59,63,65,72,73,74,88"}}
06:29:42.262 MQT: stat/elmatare/STATUS5 = {"StatusNET":{"Hostname":"elmatare-7799","IPAddress":"192.168.20.26","Gateway":"192.168.20.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.20.1","DNSServer2":"83.255.255.2","Mac":"4C:11:AE:13:BE:77","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
06:29:42.268 MQT: stat/elmatare/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_13BE77","MqttUser":"DVES_USER","MqttCount":2,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
06:29:42.275 MQT: stat/elmatare/STATUS7 = {"StatusTIM":{"UTC":"2023-04-13T05:29:42","Local":"2023-04-13T06:29:42","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00"}}
06:29:42.284 MQT: stat/elmatare/STATUS10 = {"StatusSNS":{"Time":"2023-04-13T06:29:42","AM2301":{"Temperature":14.6,"Humidity":63.6,"DewPoint":7.8},"TempUnit":"C"}}
06:29:42.292 MQT: stat/elmatare/STATUS11 = {"StatusSTS":{"Time":"2023-04-13T06:29:42","Uptime":"0T09:18:32","UptimeSec":33512,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"Wifi":{"AP":1,"SSId":"smarthome","BSSId":"C2:74:AD:13:CD:91","Channel":11,"Mode":"11n","RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
Dont se anything in the log

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I should get this from the SmartMeter when I connect with telnet
/ELL5\253833635_A
0-0:1.0.0(210421202531W)
1-0:1.8.0(00000077.881*kWh)
1-0:2.8.0(00000000.001*kWh)
1-0:3.8.0(00000003.875*kvarh)
1-0:4.8.0(00000002.678*kvarh)
1-0:1.7.0(0004.169*kW)
1-0:2.7.0(0000.000*kW)
1-0:3.7.0(0000.229*kvar)
1-0:4.7.0(0000.504*kvar)
1-0:21.7.0(0000.608*kW)
1-0:41.7.0(0002.441*kW)
1-0:61.7.0(0001.120*kW)
1-0:22.7.0(0000.000*kW)
1-0:42.7.0(0000.000*kW)
1-0:62.7.0(0000.000*kW)
1-0:23.7.0(0000.000*kvar)
1-0:43.7.0(0000.000*kvar)
1-0:63.7.0(0000.229*kvar)
1-0:24.7.0(0000.194*kvar)
1-0:44.7.0(0000.310*kvar)
1-0:64.7.0(0000.000*kvar)
1-0:32.7.0(232.9*V)
1-0:52.7.0(229.8*V)
1-0:72.7.0(233.6*V)
1-0:31.7.0(002.8*A)
1-0:51.7.0(010.7*A)
1-0:71.7.0(004.9*A)
!2577

but I get something like this, different every 10 seconds when the smartmeter sends its data

0-0:1.0.0(230413064257W)
1-0:1.8.0(00002868.367*kWh)
1-0:2.8.0(00000000.004*kWh)
1-0:3.8.0(00001172.559*kvarh)
1-0:4.8.0(00000389.522*kvarh)
1-0:1.7.0(0000.414*kW)
1-0:2.7.0(0000.000*kW)
1-0:3.7.0(0000.000*kvar)
1-:4.70(00.14*W)
10:1..0000.98kW
1-:4.70(00.00*W)
10:2..0000.00kW
-0237.(00000*kar
-0437.(00000*kar
-0637.(00000*kar
-0247.(00011*kar
-0447.(00006*kar
-0647.(00007*kar
-0327.(29.*

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ressof** [comment]
I think I resolved the issue by adding this to user_config_override
#define TCP_BRIDGE_BUF_SIZE    1024  // size of the buffer, above 132 required for efficient XMODEM

The buffer is 256 as default.

**Comment by arendst** [comment]
Fixed by OP
