### ISSUE TITLE
SDM120 Data Jumping about

### ISSUE THREAD

**Issue by nobbyneb** [arendst/Tasmota#18511]
Hi, i have a single SDM120 meter connected to a Wemos D1 mini via the widely used TTL to [RS485 convertor](https://www.amazon.co.uk/dp/B07DJ4TGY3?psc=1&ref=ppx_yo2ov_dt_b_product_details) - the data is received by Tasmota and is being parsed via MQTT fine, however the data is erratic and jumps back to '0' for most parameters, every few seconds - the voltage in particular is concerning as this is obviously static (as indicated by the display on the meter itself). I've attached a quick clip.

I am using good quality connection cable, the distance is only around 50cm. I have 5 other SDM120s in a separate (non-Tasmota) setup and the data from them is very stable. I have tried with two different Wemos with the latest Sensors installed and seeing the same behaviour. Is there anything else i should try or is this a known issue?

Many thanks

https://user-images.githubusercontent.com/5697598/234474621-bcca0a4c-0fe7-4111-93cf-85df2921ef8f.MOV

**Comment by arendst** [comment]
Closing while no response.

**Comment by nobbyneb** [comment]
Apologies i have been away. I am getting the following error, _"NRG: Energy reset by invalid data"_ which coincindes with the appearance of null values. This is completely random, but typically once a minute at least. Screenshot attached. I have replaced the SDM120 Meter and continue to get the same error, so this is isolated to the ESP or RS485 module. I've also attached screenshot of the pin config  I have ordered another modbus reader and will try a different ESP device to see if the issue disappears. Will revert shortly, thank you.
 
![IMG_1602](https://github.com/arendst/Tasmota/assets/5697598/b7887c54-c685-415d-bbcd-07f0319ff982)

![Screenshot 2023-05-21 at 20 35 22](https://github.com/arendst/Tasmota/assets/5697598/74372f1b-06ec-4e61-8f18-f1dae0f65e3c)

**Comment by arendst** [comment]
> I'm not sure why.

I do. The ESP32 implementation ALWAYS uses hardware serial. The ESP8266 can only use hardware serial on GPIO1/3 or GPIO13/15 resulting in stable comms. ALl other ESP8266 use software serial resulting in occasional misses as you found out.

**Comment by nobbyneb** [comment]
That explains it, thank you!

**Comment by Guido19691** [comment]
Hi, I found this old thread, I'm trying the same thing: Wemos D1 Mini with Eastron SDM120 using Tasmota. With ESP32 I succeeded using GPIO16/17. But now I try with the D1 mini. Flashed latest version of Tasmota (15.0.1) on it, no problem. For the module parameters I choose Generic (18) just as in the picture. But to my surprise I do not see the options for SDMx20 for the GPIO's, only general Rx/Tx. How Come? What am I doing wrong here?

**Comment by sfromis** [comment]
You need to use a build including support for SDM120, see https://tasmota.github.io/docs/BUILDS/

**Comment by Guido19691** [comment]
> You need to use a build including support for SDM120, see https://tasmota.github.io/docs/BUILDS/

Thanks!! OK installed the build with sensors, now I have support for the SDMx20. But next strange thing. When I connect the RX/TX of the RS485 converter pcb to GPIO13/15, the D1 mini won't boot up and Tx LED on the RS485 pcb is lit. When I connect to the pins marked Rx/Tx of the D1 mini, now the D1 mini boots up and at least the Tx LED is flashing, but no response from the SDM120. With ESP32 it works (GPIO16/17)....Looks like the D1 mini does not like the load on the pins GPIO13/15

**Comment by sfromis** [comment]
You need to know your pins, and not just connect stuff and pray.

A significant difference between ESP32 and ESP8266 is that with ESP32, you can config gpio pins (including serial) wherever you like due to the multiplexer. Using gpio 16/17 has no special status. With ESP8266, you can only get hardware serial if using the exact right pins, where TX/RX is gpio 1/3 or 15/13 respectively.

With ESP8266, gpio 15 is a strapping pin where boot will fail if the pin is pulled high, and high=inactive is default for UART. Also, gpio 1 is a strapping pin, where boot will fail if pulled low. Thus, you need to be extra careful about what you do with TX.

**Comment by Guido19691** [comment]
> You need to know your pins, and not just connect stuff and pray.
> 
> A significant difference between ESP32 and ESP8266 is that with ESP32, you can config gpio pins (including serial) wherever you like due to the multiplexer. Using gpio 16/17 has no special status. With ESP8266, you can only get hardware serial if using the exact right pins, where TX/RX is gpio 1/3 or 15/13 respectively.
> 
> With ESP8266, gpio 15 is a strapping pin where boot will fail if the pin is pulled high, and high=inactive is default for UART. Also, gpio 1 is a strapping pin, where boot will fail if pulled low. Thus, you need to be extra careful about what you do with TX.

Ok sounds a bit confusing....how is it than even possible to use RS485 with the D1 mini? Do you have a source perhaps where I can read about this?

**Comment by sfromis** [comment]
If it works with ESP32, it should also work with ESP8266, as long as you make sure to correctly connect the TX/RX pins, and probably use gpio 1/3 since gpio 15/13 is hit by the strapping issue causing boot failure. If in doubt, try swapping tx/rx.

Searching the Tasmota [docs](https://tasmota.github.io/docs/) site for "rs485" does give a few hits, but if you already had it working with ESP32, not really much to find there.
