### ISSUE TITLE
How to use factory calibration data (Shelly Plus 1PM)

### ISSUE THREAD

**Issue by Tobi266** [arendst/Tasmota#18708]
### Discussed in https://github.com/arendst/Tasmota/discussions/18678

<div type='discussions-op-text'>

<sup>Originally posted by **Tobi266** May 17, 2023</sup>
Hi,

I flashed a Shelly Plus 1PM with Tasmota OTA. 
Guide: https://github.com/tasmota/mgos32-to-tasmota32

I extracted the shelly.bin with the factory calibrations.
![calibration](https://github.com/arendst/Tasmota/assets/84711635/c01f4a2e-5d7d-4785-8470-bc842bc232a8)

But how can I add/use these in Tasmota?

Thanks
</div>

**Comment by arendst** [comment]
Let's keep the discussion as main doc.
