### ISSUE TITLE
Atlas Scientific EZO modules, multiple ORP modules

### ISSUE THREAD

**Issue by SimonFili** [arendst/Tasmota#18767]
Everything is fine with using multiple EZO modules with different i2c addresses.  But the issue of i2cscan remains.  So I'm opening an issue.

High level:  6 EZO modules connected to an ESP32 compiled for EZO.  All is working, I see the output of all the EZO.  But I2CSCAN is giving this error: {"I2CScan":"Error 5 at 0x02"}.   I've disabled all other i2cdrivers not used.

Thanks,

### Discussed in https://github.com/arendst/Tasmota/discussions/18746

<div type='discussions-op-text'>

<sup>Originally posted by **SimonFili** May 29, 2023</sup>
Hi all,

I properly compiled Tasmota32 S3 and enabled the EZO ORP module.  I can see it
![image](https://github.com/arendst/Tasmota/assets/7669537/f1f3954d-4169-41ac-af59-637018cc28bb)

My issue is that I need to read multiple EZO ORP module that have multiple I2C address. 

Right now, I can only see one.

15:50:27.696 CMD: i2cscan
15:50:28.702 MQT: stat/ESP32S3_T1/RESULT = {"I2CScan":"Error 5 at 0x02"}

I know we can run multiple EZO modules at different I2C address. I did before pH, DO, EC.

What would be needed in the code of these modules to enable reading many of the same module on different address?

Thanks! 

</div>

**Comment by sfromis** [comment]
Opening multiple issues for the same situation is not the way to go.

In the other thread, you posted about seeing 4 different EZO ORP values, both on the Tasmota front page and in the published JSON. That looked very much like you found a solution. I2CScan errors may be up to wiring issues, or sensors not well-behaved on the bus.

**Comment by SimonFili** [comment]
Sorry if I opened multiple issue, I was not aware.

To be clear, **the only issue I'm opening is the i2cScan error.**  All the other issues I had have been resolved, and I discussed them in the case.

So why is there an i2cscan issue, I think the discussion gives more context.  If I need to rewrite it to be more concise, I can do that.

Thanks, Simon

**Comment by Jason2866** [comment]
@ tichris0 Can you help? We don't have any of this modules.

**Comment by tichris0** [comment]
Unfortunately, I do not own multiple EZO devices and can't really test this case.  As far as the driver's concerned, it merely reports itself via I2cSetActiveFound, which I imagine i2cscan would simply output all the strings reported by the sensors.  I'd have to check the i2cscan function to see how/why it would return an error.  It's been a couple years.  I'll try and see if I can download the latest code again over the weekend to see why it may fail.

**Comment by SimonFili** [comment]
If you need me to test, I have 6 EZO connected to an ESP32.  Let me know

**Comment by SimonFili** [comment]
@tichris0 Worked a bit more on this project. Here's some information if it can help.

ESP32-S3 compiled for EZO: Version [Tasmota 12.5.0.3](https://bit.ly/tasmota)
Pins used for i2c:
![image](https://github.com/arendst/Tasmota/assets/7669537/a15a7989-4868-4162-ba7f-05f3ed8f6c85)

**The display on the web page of the ESP32**
![image](https://github.com/arendst/Tasmota/assets/7669537/165f2721-577a-4b59-9d90-ce8ba8980f3c)

**A table with all the devices:**
![image](https://github.com/arendst/Tasmota/assets/7669537/30f75a4c-2d79-4e2b-9c75-394574de4970)

**i2cscan**
13:15:48.108 MQT: stat/ESP32S3_T1/RESULT = **{"I2CScan":"Error 5 at 0x02"}**

**i2cdriver**  Here I disabled (!) everything I did not need.
{"I2CDriver":"!7,!8,!9,!10,!11,!12,!13,!14,!15,!17,!18,!20,!24,!29,!31,!36,!41,!42,!44,!46,!48,55,!58,!62,!65,!69,!76,!77"}

Let me know if you need more information.

Thanks! Simon

**Comment by SimonFili** [comment]
I just saw an error in my table, will fix it soon.  Working on it!

**Comment by SimonFili** [comment]
Alright!  So I went back to the compiler (gitpod) and compiled for ESP32S3 with only the EZO EC.
That tested OK, i2cscan worked.  
I could check all other EZO i2c address, so all modules confirmed.

Then compiled again with EZO EC + EZO ORP
i2cscan was ok with 2 EZO chip.
then tested with EC + 2 ORP, worked fine, no error

Then I compiled again with ECO EC+ORP+pH
Re-installed all EZO like before and it WORKS!  No error in i2cscan.

See above post updated.

So maybe there was something in the old compile version but now with version 13.0.0.0.2, all is good.

I only changed those line in the my_user_config.h
#define USE_EZOPH
#define USE_EZOORP 
#define USE_EZOEC  

Sorry for this, not sure what happened.
