### ISSUE TITLE
reset esp32 con tasmota 12.5

### ISSUE THREAD

**Issue by mascolo74** [arendst/Tasmota#18783]
<!-- Thanks for reporting a problem for this project. READ THIS FIRST:
installazione tasmota 12.5 su esp 32 wromm 

### PROBLEM DESCRIPTION
installazione tasmota 12,5 ok riavvio dispositivo, modifica del modulo gpio 2-4-21-23 pulsante gpio 25-26-32-33 rele_i riavvio del modulo, emulazione beko  riavvio del modulo, a questo punto si ha un reset dei gpio del wifi, necessita ricominciare da capo impossibile finire la configurazione

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): ___esp32__
- [ ] Tasmota binary firmware version number used: __12.5___
  - [  -] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: ____web /tasmotizer_
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by mascolo74** [comment]
chiedo scusa errore di tastiera per commento sopra.
installazione tasmota 12.5 su esp 32, comportamento strano su due schedine.
installazione ok , inserimento wifi e collegamento wifi ok, inserimento gpio 2/4/21/23 pulsante gpio 4/ 25/26/27 ok riavvio del modulo si perde tutta la configurazione bisogna rifarla compreso il wifi.

**Comment by barbudor** [comment]
No comprendo

This is an English only forum
Please use Google translate before posting as other users do

**Comment by stefanbode** [comment]
I apologize keyboard error for comment above.
tasmota 12.5 installation on esp 32, strange behavior on two cards.
installation ok, wifi insertion and wifi connection ok, gpio 2/4/21/23 insertion gpio 4/25/26/27 button ok restarting the module the whole configuration is lost, you have to redo it including the wifi.

Hmm even the translate is not clear for me.... looks like it did not save the config. Pls check "savedata" in the console and if it is 0 set it to 1. Also multiple restarts because of a electrical issue will reset the device after some restarts.
