### ISSUE TITLE
Power1#data does not trigger

### ISSUE THREAD

**Issue by pkkrusty** [arendst/Tasmota#18834]
### PROBLEM DESCRIPTION
According to docs, any command with JSON response triggers on <command>#data. Power#data seems to be an exception. Power#state works on state change, but if a repeated command is sent, i.e. Power1 1 then Power1 1, it would make sense for Power1#data to trigger both times.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): Mini D1
- [ x] Tasmota binary firmware version number used: 12.5.0.1
  - [ ] Pre-compiled
  - [ x] Self-compiled
- [ x] Flashing tools used: esptool.py
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
14:09:06.453 MQT: battery-ac-controller/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
14:09:06.673 SRC: Backlog
14:09:06.675 CMD: Grp 0, Cmd 'MODULE', Idx 1, Len 0, Pld -99, Data ''
14:09:06.681 MQT: battery-ac-controller/stat/RESULT = {"Module":{"18":"Generic"}}
14:09:06.924 SRC: Backlog
14:09:06.926 CMD: Grp 0, Cmd 'GPIO', Idx 1, Len 3, Pld 255, Data '255'
14:09:06.935 MQT: battery-ac-controller/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"224":"Relay1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"1088":"IRrecv"},"GPIO13":{"1056":"IRsend1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
14:09:35.826 MQT: battery-ac-controller/stat/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":530,"Free":301,"Rules":"on power1#data do IRHVAC {\"Vendor\":\"GREE\",\"Model\":1,\"Mode\":\"Cool\",\"Power\":\"On\",\"Celsius\":\"On\",\"Temp\":16,\"FanSpeed\":\"Max\",\"SwingV\":\"Low\",\"SwingH\":\"Off\",\"Quiet\":\"Off\",\"Turbo\":\"On\",\"Econo\":\"Off\",\"Light\":\"On\",\"Filter\":\"Off\",\"Clean\":\"Off\",\"Beep\":\"Off\",\"Sleep\":-1} endon on power1#data do IRHVAC {\"Vendor\":\"GREE\",\"Model\":1,\"Mode\":\"Cool\",\"Power\":\"Off\",\"Celsius\":\"On\",\"Temp\":16,\"FanSpeed\":\"Max\",\"SwingV\":\"Low\",\"SwingH\":\"Off\",\"Quiet\":\"Off\",\"Turbo\":\"On\",\"Econo\":\"Off\",\"Light\":\"On\",\"Filter\":\"Off\",\"Clean\":\"Off\",\"Beep\":\"Off\",\"Sleep\":-1} endon"}}
14:09:36.042 SRC: Backlog
14:09:36.043 CMD: Grp 0, Cmd 'RULE', Idx 2, Len 0, Pld -99, Data ''
14:09:36.051 MQT: battery-ac-controller/stat/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
14:09:36.292 SRC: Backlog
14:09:36.294 CMD: Grp 0, Cmd 'RULE', Idx 3, Len 0, Pld -99, Data ''
14:09:36.299 MQT: battery-ac-controller/stat/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
14:10:04.001 MQT: battery-ac-controller/stat/STATUS = {"Status":{"Module":18,"DeviceName":"Battery AC Controller","FriendlyName":["Battery AC Controller"],"Topic":"battery-ac-controller","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
14:10:04.011 MQT: battery-ac-controller/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T01:19:40","StartupUTC":"2023-06-09T12:50:24","Sleep":50,"CfgHolder":4802,"BootCount":2,"BCResetTime":"2023-06-09T11:02:33","SaveCount":14,"SaveAddress":"F8000"}}
14:10:04.019 MQT: battery-ac-controller/stat/STATUS2 = {"StatusFWR":{"Version":"12.5.0.1(tasmota)","BuildDateTime":"2023-06-09T12:45:19","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":160,"Hardware":"ESP8266EX","CR":"480/699"}}
14:10:04.028 MQT: battery-ac-controller/stat/STATUS3 = {"StatusLOG":{"SerialLog":3,"WebLog":3,"MqttLog":0,"SysLog":3,"LogHost":"192.168.3.48","LogPort":514,"SSId":["Roatan","beersheba"],"TelePeriod":900,"Resolution":"55C181C0","SetOption":["00208008","2805C80001000600003C5A00192800000000","000000C9","08006000","00004000","00000000"]}}
14:10:04.039 MQT: battery-ac-controller/stat/STATUS4 = {"StatusMEM":{"ProgramSize":629,"Free":392,"Heap":21,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","0F2A068E","04000121","00000003","00000000","40000800","00000080","00200000","00000800","00000000"],"Drivers":"1,2,4,5,9,10,13,20,29,38,50,59","Sensors":"1,2","I2CDriver":"4"}}
14:10:04.047 MQT: battery-ac-controller/stat/STATUS5 = {"StatusNET":{"Hostname":"battery-ac-controller","IPAddress":"192.168.3.15","Gateway":"192.168.2.1","Subnetmask":"255.255.254.0","DNSServer1":"192.168.2.1","DNSServer2":"0.0.0.0","Mac":"E8:DB:84:AF:8B:61","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
14:10:04.055 MQT: battery-ac-controller/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.3.48","MqttPort":1883,"MqttClientMask":"pkkrusty_%06X","MqttClient":"pkkrusty_AF8B61","MqttUser":"pkkrusty","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":16}}
14:10:04.063 MQT: battery-ac-controller/stat/STATUS7 = {"StatusTIM":{"UTC":"2023-06-09T14:10:04","Local":"2023-06-09T14:10:04","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+00:00","Sunrise":"06:37","Sunset":"19:34"}}
14:10:04.070 MQT: battery-ac-controller/stat/STATUS10 = {"StatusSNS":{"Time":"2023-06-09T14:10:04"}}
14:10:04.077 MQT: battery-ac-controller/stat/STATUS11 = {"StatusSTS":{"Time":"2023-06-09T14:10:04","Uptime":"0T01:19:40","UptimeSec":4780,"Heap":19,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"beersheba","BSSId":"10:FE:ED:89:2A:49","Channel":6,"Mode":"11n","RSSI":54,"Signal":-73,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
No output, rule doesn't trigger.

```

### TO REPRODUCE
Use power#data or Power1#data, and no trigger happens.

### EXPECTED BEHAVIOUR
Acts according to docs. Any command that generates a JSON response will trigger <command>#data

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
As I [mentioned](https://discord.com/channels/479389167382691863/790182324939128832/1116718853242761326) on Discord, my experience/expectation is that the JSON-based triggers are not always available for names "shadowed" by the built-in triggers.

Hence, this rule does not fire either:
`Rule1 on Switch1 do Var1 %value% endon`
By the normal syntax for JSON triggers, that would fire, as the payload is not one-level (having a single field).
`{"Time":"2023-06-09T18:41:39.806+02:00","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON"}`

**Comment by pkkrusty** [comment]
If this receives feedback of `can't/won't fix` I'll attempt to adjust the docs to reflect the limitation.

**Comment by Elix-g** [comment]
I also noticed recently, that the JSON-based trigger don't work for relays (anymore). I'm pretty sure that it was working properly in previous releases (like 9.5.0). And you're right, when it should come to interesting details or limitations, the docs are pretty incomplete or outdated.

Small hint: Power1#State fires a rule properly.

**Comment by sfromis** [comment]
Yes, `Power1#state` is the intended way. Doing a test with 9.5.0 did not confirm your claim of it working differently in that version. Neither `Power#data` nor `Power1#data` fired for the JSON payload published.

**Comment by Elix-g** [comment]
Then I'm wrong with the version. I found a bunch of rules in my recordings which use the JSON-based trigger. Used the rules ages ago.
However, `Power1#State` works but is unattractive when triggering blink. The state changes upon every tick and therefore, rules using the state-trigger fire again and again.

**Comment by arendst** [comment]
As @sfromis noticed ONLY ``Power1#state`` is supported. ``Power1#data`` is not supported simply because the first solutions immediatly triggers the rule engine when a power state change occurs.
