### ISSUE TITLE
Available only 1 PWM although defined 4 on ESP32

### ISSUE THREAD

**Issue by RJSDevel** [arendst/Tasmota#18933]
The same in Home assistant

`{"NAME":"CONFIG","GPIO":[1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,416,0,416,416,416,0,1,1,1,0,0,0,0,1,1,1,1,4704,0,0,1],"FLAG":0,"BASE":1}`

![image](https://github.com/arendst/Tasmota/assets/12229274/fde1b1e6-4a9b-44e8-8499-c3a2364b55b4)
![image](https://github.com/arendst/Tasmota/assets/12229274/910d00e7-9d06-4587-9e9b-8fe435c91fcf)

**Comment by barbudor** [comment]
You have defined 4 times the same
Read the doc
https://tasmota.github.io/docs/Lights

**Comment by RJSDevel** [comment]
I've got it! Thank you! But it is not obviously(
