### ISSUE TITLE
Issue with alexa based dimming/speed control

### ISSUE THREAD

**Issue by kanavkapoor7** [arendst/Tasmota#19076]
I have been using tasmota on my ESP devices for the past 2 years. Presently im facing an issue where I have Tasmota 13.0.0.2 installed which is used to control fan speed through PWM pin. The same is used with alexa using hue emulation. This has been working seamlessly for the past 2 years but today this stopped working. I am not able to control the speed using alexa anymore. Alexa is able to switch ON and OFF the fan but speed control is not working. However using the Tasmota GUI the speed control is working fine. Nothing has been changed or updated from my end. Can you please suggest if any changes were done by alexa team which could have resulted in this. Or any remedy for the same ?

**Comment by s-hadinger** [comment]
I am not aware of any change in Tasmota with regards to Alexa Hue Emulation. Could you please downgrade to a previous version and confirm that it's still working with a lower version?

If so please provide logs with `weblog 4` log level with both versions
