### ISSUE TITLE
MQTT Configuration : Topic becomes the hostname

### ISSUE THREAD

**Issue by justoke** [arendst/Tasmota#19154]
### PROBLEM DESCRIPTION
When changing MQTT configuration via the web interface, specifically changes the Topic property, it seems this should just change the topic that the device uses for sending MQTT messages, however actual behaviour is that  after the device has rebooted it assigns a host name as the topic. This surely can't be by design. There isn't any relationship between a topic and the host name, unless by design or convention and personal preference.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Basic
- [x] Tasmota binary firmware version number used: 13.0.0
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: Tasmota Webinstaller [English]
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
07:43:44.451 MQT: stat/tasmota_A26B8E/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
07:43:44.659 MQT: stat/tasmota_A26B8E/RESULT = {"Module":{"1":"Sonoff Basic"}}
07:43:44.914 MQT: stat/tasmota_A26B8E/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
BEFORE topic change, device defaults
07:50:19.626 MQT: stat/tasmota_A26B8E/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_A26B8E","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
07:50:19.632 MQT: stat/tasmota_A26B8E/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:18:10","StartupUTC":"2023-07-20T06:32:09","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2023-07-18T20:05:15","SaveCount":18,"SaveAddress":"FA000"}}
07:50:19.638 MQT: stat/tasmota_A26B8E/STATUS2 = {"StatusFWR":{"Version":"13.0.0(tasmota)","BuildDateTime":"2023-06-26T10:42:07","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285N08","CR":"387/699"}}
07:50:19.644 MQT: stat/tasmota_A26B8E/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["miHome",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
07:50:19.658 MQT: stat/tasmota_A26B8E/STATUS4 = {"StatusMEM":{"ProgramSize":634,"Free":368,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14325E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62,68","Sensors":"1,2,3,4,5,6","I2CDriver":"7"}}
07:50:19.665 MQT: stat/tasmota_A26B8E/STATUS5 = {"StatusNET":{"Hostname":"tasmota-A26B8E-2958","IPAddress":"192.168.1.67","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"9C:9C:1F:A2:6B:8E","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
07:50:19.670 MQT: stat/tasmota_A26B8E/STATUS6 = {"StatusMQT":{"MqttHost":"myserver1.mq.net","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A26B8E","MqttUser":"rtmqttpub","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
07:50:19.676 MQT: stat/tasmota_A26B8E/STATUS7 = {"StatusTIM":{"UTC":"2023-07-20T06:50:19","Local":"2023-07-20T07:50:19","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"05:08","Sunset":"20:44"}}
07:50:19.682 MQT: stat/tasmota_A26B8E/STATUS10 = {"StatusSNS":{"Time":"2023-07-20T07:50:19"}}
07:50:19.709 MQT: stat/tasmota_A26B8E/STATUS11 = {"StatusSTS":{"Time":"2023-07-20T07:50:19","Uptime":"0T00:18:10","UptimeSec":1090,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"miHome","BSSId":"E8:65:D4:CD:CA:89","Channel":6,"Mode":"11n","RSSI":100,"Signal":-38,"LinkCount":1,"Downtime":"0T00:00:03"}}}
>>>>>>>>>>>>>>>>>>>>
AFTER TOPIC change:
07:53:26.850 CMD: Status 0
07:53:26.858 MQT: stat/pwr126711/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"pwr126711","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
07:53:26.893 MQT: stat/pwr126711/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:00:50","StartupUTC":"2023-07-20T06:52:36","Sleep":50,"CfgHolder":4617,"BootCount":11,"BCResetTime":"2023-07-18T20:05:15","SaveCount":20,"SaveAddress":"F8000"}}
07:53:26.925 MQT: stat/pwr126711/STATUS2 = {"StatusFWR":{"Version":"13.0.0(tasmota)","BuildDateTime":"2023-06-26T10:42:07","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285N08","CR":"384/699"}}
07:53:26.946 MQT: stat/pwr126711/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["miHome",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
07:53:26.983 MQT: stat/pwr126711/STATUS4 = {"StatusMEM":{"ProgramSize":634,"Free":368,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14325E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62,68","Sensors":"1,2,3,4,5,6","I2CDriver":"7"}}
07:53:27.000 MQT: stat/pwr126711/STATUS5 = {"StatusNET":{"Hostname":"pwr126711-2958","IPAddress":"192.168.1.67","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"9C:9C:1F:A2:6B:8E","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
07:53:27.025 MQT: stat/pwr126711/STATUS6 = {"StatusMQT":{"MqttHost":"myserver1.mq.net","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A26B8E","MqttUser":"rtmqttpub","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
07:53:27.050 MQT: stat/pwr126711/STATUS7 = {"StatusTIM":{"UTC":"2023-07-20T06:53:27","Local":"2023-07-20T07:53:27","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"05:08","Sunset":"20:44"}}
07:53:27.071 MQT: stat/pwr126711/STATUS10 = {"StatusSNS":{"Time":"2023-07-20T07:53:27"}}
07:53:27.079 MQT: stat/pwr126711/STATUS11 = {"StatusSTS":{"Time":"2023-07-20T07:53:27","Uptime":"0T00:00:51","UptimeSec":51,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"miHome","BSSId":"E8:65:D4:CD:CA:89","Channel":6,"Mode":"11n","RSSI":100,"Signal":-40,"LinkCount":1,"Downtime":"0T00:00:03"}}}
07:57:44.396 MQT: tele/pwr126711/STATE = {"Time":"2023-07-20T07:57:44","Uptime":"0T00:05:08","UptimeSec":308,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"miHome","BSSId":"E8:65:D4:CD:CA:89","Channel":6,"Mode":"11n","RSSI":100,"Signal":-37,"LinkCount":1,"Downtime":"0T00:00:03"}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Change the topic under MQTT configuration. After device reboots go and observe the console output. Also the web interface is not accessible after reboot as you will have to type the new hostname into the browser address bar to refresh it.

Note this from the Status 0 BEFORE and AFTER sections:
BEFORE:
MQTT Configuration
Topic setting = tasmota_%06X
Status 0
"Topic":"tasmota_A26B8E"
"Hostname":"tasmota-A26B8E-2958" 

AFTER:
MQTT Configuration
Topic setting = pwr126711
Status 0
"Topic":"pwr126711"
"Hostname":"pwr126711-2958"

### EXPECTED BEHAVIOUR
Changing the MQTT topic will not change the hostname

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
BEFORE - Default setting after flash web installation
![image](https://github.com/arendst/Tasmota/assets/26506785/a53cb689-2ea0-4fb2-81dc-8b95058993c9)
Status 0
"Topic":"tasmota_A26B8E"
"Hostname":"tasmota-A26B8E-2958" 
AFTER - User changed the topic
![image](https://github.com/arendst/Tasmota/assets/26506785/3f5189cb-5455-4030-9f2b-c41765f963fc)
Status 0
"Topic":"pwr126711"
"Hostname":"pwr126711-2958"

### ADDITIONAL CONTEXT
While some use cases might want to use the topic to link the device hostname to the published commands, this is not a convention that should be by design. At least if an alternative topic is set, the host name should be optionally affected.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
It is [documented](https://tasmota.github.io/docs/Commands/#hostname) behavior that default host name (unless you config a better one) is `MQTT_TOPIC-<4digits>`

As I see it, the default name setup (both host name and topic) are there to make it possible to create multiple Tasmota devices without default names becoming the same, but preferable to come up with your own naming strategy.

**Comment by justoke** [comment]
Thank you @sfromis for the quick response. I use the mac address formatted into a string, to create a unique identifier for the host name - in my opinion, this would be the default for a hostname. Starting with that, then adding some sort of placeholder in the topic for that would ensure that each device was accessible in MQTT terms at a unique topic subscription. 

It just seems putting this convention means that if you want to keep default hostname and change a topic you are stuck with this. Even when I just put a hostname under the wifi settings, it still put a suffix on the end, even though I put just a single string value.

Anyway, I'll adapt and move on.

**Comment by sfromis** [comment]
> Even when I just put a hostname under the wifi settings, it still put a suffix on the end, even though I put just a single string value.

I'm configuring single string host names all the time, without getting any suffix added. Only place I see a suffix is if you configure such a topic, and let the host name default including the suffix. If you want to stick with the default host name based on the default topic, you'll have to explicitly configure this.
