### ISSUE TITLE
Light not illuminating after power on with Fade enabled and Dimmer value 1 using PWM

### ISSUE THREAD

**Issue by thornley-david** [arendst/Tasmota#19228]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I discovered that the fade function causes the lowest Dimmer setting 1 to not illuminate when power cycling. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____  **Tuya compatible Downlight (Moes)** 
- [x] Tasmota binary firmware version number used: _____ **13.0.0 (also reproduced in 12.4.0)**
  - [x] Pre-compiled
  - [ ] Self-compiled 
- [x] Flashing tools used: _____ **web installer (then upgrade to 13.0.0 before reproducing and reporting)**
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

{"NAME":"Tuya_DL_8266","GPIO":[0,0,0,0,416,419,0,0,417,420,418,0,0,0],"FLAG":0,"BASE":18}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

14:08:12.586 CMD: STATUS 0
14:08:12.588 SRC: WebConsole from 10.11.0.251
14:08:12.591 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 0, Data '0'
14:08:12.598 MQT: tasmota/dl-lounge6/stat/STATUS = {"Status":{"Module":0,"DeviceName":"dl-lounge6","FriendlyName":["Tasmota"],"Topic":"dl-lounge6","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
14:08:12.605 MQT: tasmota/dl-lounge6/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"Lounge","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"External System","Uptime":"0T23:31:14","StartupUTC":"2023-07-30T13:36:58","Sleep":50,"CfgHolder":4617,"BootCount":68,"BCResetTime":"2023-04-06T18:55:40","SaveCount":3384,"SaveAddress":"F5000"}}
14:08:12.611 MQT: tasmota/dl-lounge6/stat/STATUS2 = {"StatusFWR":{"Version":"12.4.0(tasmota)","BuildDateTime":"2023-02-24T15:32:38","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"368/699"}}
14:08:12.618 MQT: tasmota/dl-lounge6/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["HOMEIOT",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00008080","00006008","00004000","00000000"]}}
14:08:12.631 MQT: tasmota/dl-lounge6/stat/STATUS4 = {"StatusMEM":{"ProgramSize":632,"Free":368,"Heap":22,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
14:08:12.640 MQT: tasmota/dl-lounge6/stat/STATUS5 = {"StatusNET":{"Hostname":"dl-lounge6-6436","IPAddress":"10.5.0.163","Gateway":"10.5.0.1","Subnetmask":"255.255.240.0","DNSServer1":"10.5.0.1","DNSServer2":"0.0.0.0","Mac":"A4:CF:12:DD:B9:24","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
14:08:12.646 MQT: tasmota/dl-lounge6/stat/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.0.50","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_DDB924","MqttUser":"DVES_USER","MqttCount":4,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
14:08:12.652 MQT: tasmota/dl-lounge6/stat/STATUS7 = {"StatusTIM":{"UTC":"2023-07-31T13:08:12","Local":"2023-07-31T14:08:12","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"05:22","Sunset":"20:30"}}
14:08:12.658 MQT: tasmota/dl-lounge6/stat/STATUS10 = {"StatusSNS":{"Time":"2023-07-31T14:08:12"}}
14:08:12.668 MQT: tasmota/dl-lounge6/stat/STATUS11 = {"StatusSTS":{"Time":"2023-07-31T14:08:12","Uptime":"0T23:31:14","UptimeSec":84674,"Heap":20,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":89,"MqttCount":4,"POWER":"ON","Dimmer":1,"Color":"0000000201","HSBColor":"0,0,0","White":1,"CT":250,"Channel":[0,0,0,1,1],"Scheme":0,"Fade":"ON","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"HOMEIOT","BSSId":"B6:8B:A9:1E:23:5A","Channel":1,"Mode":"11n","RSSI":60,"Signal":-70,"LinkCount":4,"Downtime":"0T00:00:08"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

14:06:58.324 CMD: FADE
14:06:58.331 MQT: tasmota/dl-lounge6/stat/RESULT = {"Fade":"ON"}
14:07:03.048 CMD: Weblog 4
14:07:03.054 MQT: tasmota/dl-lounge6/stat/RESULT = {"WebLog":4}
14:07:03.317 CFG: Saved to flash at F8, Count 3381, Bytes 4096
14:07:05.212 CMD: FADE
14:07:05.214 SRC: WebConsole from 10.11.0.251
14:07:05.217 CMD: Grp 0, Cmd 'FADE', Idx 1, Len 0, Pld -99, Data ''
14:07:05.223 MQT: tasmota/dl-lounge6/stat/RESULT = {"Fade":"ON"}
14:07:08.508 WIF: Checking connection...
14:07:08.585 MQT: tasmota/dl-lounge6/tele/STATE = {"Time":"2023-07-31T14:07:08","Uptime":"0T23:30:10","UptimeSec":84610,"Heap":23,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":4,"POWER":"OFF","Dimmer":1,"Color":"0000000201","HSBColor":"0,0,0","White":1,"CT":250,"Channel":[0,0,0,1,1],"Scheme":0,"Fade":"ON","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"HOMEIOT","BSSId":"B6:8B:A9:1E:23:5A","Channel":1,"Mode":"11n","RSSI":56,"Signal":-72,"LinkCount":4,"Downtime":"0T00:00:08"}}
14:07:18.024 CMD: DIMMER 1
14:07:18.026 SRC: WebConsole from 10.11.0.251
14:07:18.029 CMD: Grp 0, Cmd 'DIMMER', Idx 1, Len 1, Pld 1, Data '1'
14:07:18.032 SRC: Light
14:07:18.040 MQT: tasmota/dl-lounge6/stat/RESULT = {"POWER":"ON","Dimmer":1,"Color":"0000000201","HSBColor":"0,0,0","White":1,"CT":250,"Channel":[0,0,0,1,1]}
14:07:18.318 CFG: Saved to flash at F7, Count 3382, Bytes 4096
14:07:23.867 CMD: POWER 0
14:07:23.869 SRC: WebConsole from 10.11.0.251
14:07:23.872 CMD: Grp 0, Cmd 'POWER', Idx 1, Len 1, Pld 0, Data '0'
14:07:23.879 MQT: tasmota/dl-lounge6/stat/RESULT = {"POWER":"OFF"}
14:07:23.881 MQT: tasmota/dl-lounge6/stat/POWER = OFF
14:07:24.336 CFG: Saved to flash at F6, Count 3383, Bytes 4096
14:07:26.908 CMD: POWER 1
14:07:26.910 SRC: WebConsole from 10.11.0.251
14:07:26.913 CMD: Grp 0, Cmd 'POWER', Idx 1, Len 1, Pld 1, Data '1'
14:07:26.920 MQT: tasmota/dl-lounge6/stat/RESULT = {"POWER":"ON"}
14:07:26.924 MQT: tasmota/dl-lounge6/stat/POWER = ON
14:07:27.320 CFG: Saved to flash at F5, Count 3384, Bytes 4096

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Fade 1
Dimmer 1
Power 0
Power 1

You'll note the Light does not illuminate, setting a dimmer value > 1 will cause the light to turn on. Only a dimmer value of 1 will introduce this, and I discovered this behaviour as I use "Dimmer -10" to dim steps which floor at 1.

I noticed setting a higher minimum DimmerRange value does not address the issue (which is what hightlighted to me this was a potential bug), so I suspect it must be related to the fade animation logic in the xdrv_04_light.ino

This behaviour does not happen when "Fade 0".

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

I expect the light to return to illuminated state between POWER 0 and POWER 1 when DIMMER is 1.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
For context, some Discord discussion here:
https://discord.com/channels/479389167382691863/490244847568158751/1135524765084426271

**Comment by s-hadinger** [comment]
I believe it's an edge case scenario. Is it a real life use case? Does it need fixing?

**Comment by thornley-david** [comment]
I would argue yes it's a real life scenario, I use a zigbee dimmer switch (ikea one with dim down/up and on and off). The dim down uses "DIMMER -10", and floors at 1% lowest brightness (which is still valid), when I turn the lights off and on again in the morning, they don't turn on... until I bump the dim up button too.

**Comment by s-hadinger** [comment]
@thornley-david It was indeed a nasty bug and easy to fix. Thanks for reporting.

Patch is in #19246

**Comment by thornley-david** [comment]
Many thanks @s-hadinger, good to hear/see it was a simple fix. I figured it was somewhere around that area of the code :)
