### ISSUE TITLE
Tasmota v13.0.0 IRHVAC GREE { ,"Light":"On", } not work

### ISSUE THREAD

**Issue by hamadfayyad** [arendst/Tasmota#19231]
Tasmota v13.0.0 IRHVAC gree { ,"**Light":"On**", } not work

i  downgrade to  Tasmota 12.5.0 it's working

**Comment by Jason2866** [comment]
Try latest release

**Comment by Jason2866** [comment]
Closing since no feedback. Feel free to reopen when the issue is still there with latest Tasmota version
