### ISSUE TITLE
Request to support esp32 hardware watchdog function

### ISSUE THREAD

**Issue by xsp1989** [arendst/Tasmota#19417]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I did something unusual to the device, but I found that the device did not do an automatic restart, then I used the restart -3 command and found that the device did not do a watchdog reset.
I did the following test
1. I tested the 12.5.0 firmware compiled by myself. After entering the restart -3 command in the web console, the device has not been reset and there is no response.
2. Tested the latest version 13.1.0, if I enter reset -3 in the web console, the command will be automatically converted to restart 1, and then restart automatically, but if I send the same command from mqtt, the device will not restart.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ZB-GW03
- [ ] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [x] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Request to support esp32 hardware watchdog function.Thanks

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
We disabled early in the process the hardware watchdog because it caused many troubles and many false positives. We never felt any need to enable it later n
