### ISSUE TITLE
Typo in xdsp_19_max7219_matrix.ino

### ISSUE THREAD

**Issue by SN-8023** [arendst/Tasmota#19507]
in the file tasmota/tasmota_xdsp_display/xdsp_19_max7219_matrix.ino for the MAX7219 there are several typos (max2719, max7291 etc). Is this supposed to be like this?

btw. great project. Hats off.

**Comment by Jason2866** [comment]
The driver supports the max2719 and max7219

**Comment by sfromis** [comment]
As those names are from internal labels without material impact, I'd expect the differences being to separate the later matrix support from the original 7-segment support, as the Tasmota build structure inherited from Arduino needs labels to be unique, also outside of each `.ino` file.

**Comment by barbudor** [comment]
> The driver supports the max2719 and max7219

There is no such chip as the MAX2719
