### ISSUE TITLE
Gosund SP1 - Can't change Firmware - "Upload failed - not enough space"

### ISSUE THREAD

**Issue by grenelt** [arendst/Tasmota#19612]
Was able to change from 13.1.0 to 13.1.0.3 teleinfo (actually another issue - rule with tele-ENERGY#Power doesn't work anymore) via minimal firmware on a Gosund SP1 - but i can't change back to regular firmware, because the none of the firmware versions (even minimal) didn't fit again.

I tried to "reset 6" and instant update after reboot, but no change.

I used these binaries: http://ota.tasmota.com/tasmota/release-13.1.0/

Information says:
![grafik](https://github.com/arendst/Tasmota/assets/474834/fc3be29f-91f7-4287-b3c0-59a4409b94db)

**Comment by grenelt** [comment]
Found a **solution**: The 8.5.1 minimal image was small enough to down-/upgrade again.

**Comment by ireun** [comment]
Thanks for the tip, worked for me for the newest tasmota!
