### ISSUE TITLE
Modbusbridge causes memory leak

### ISSUE THREAD

**Issue by jeroenst** [arendst/Tasmota#19733]
### PROBLEM DESCRIPTION
When using modbusbridge  for writing modbus registers  Tasmotagets out of memory and becomes unreachable.

It started after upgrading to 13.0 but back on 12.5 the issue remains. 

I'm already investigating it and trying to find the leak. 

PR will follow when fixed. 

![Screenshot_20231013_075852_Chrome](https://github.com/arendst/Tasmota/assets/2833940/0615ac21-7e5f-4962-bfae-d6a3f68aabaa)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic):  Astra Rocketcontroller 
- [x] Tasmota binary firmware version number used: 13.1
  - [x] Pre-compiled 13.1, 12.5
  - [x] Self-compiled 12.5
- [x] Flashing tools used: website
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
11:38:39.060 CMD: Backlog Template; Module; GPIO 255
11:38:39.063 SRC: WebConsole from 192.168.0.123
11:38:39.065 CMD: Grp 0, Cmd 'BACKLOG', Idx 1, Len 26, Pld -99, Data 'Template; Module; GPIO 255'
11:38:39.098 SRC: Backlog
11:38:39.100 CMD: Grp 0, Cmd 'TEMPLATE', Idx 1, Len 0, Pld -99, Data ''
11:38:39.111 MQT: 0004/TASMOTA-HEATPUMP/stat/RESULT = {"NAME":"ASTRA R4A4","GPIO":[1,1,1,1,576,1,1,1,480,1,1,1,9440,9408,1,1,0,640,608,1,0,224,225,1152,0,0,0,0,227,226,160,161,162,0,0,163],"FLAG":0,"BASE":1}
11:38:39.346 SRC: Backlog
11:38:39.348 CMD: Grp 0, Cmd 'MODULE', Idx 1, Len 0, Pld -99, Data ''
11:38:39.359 MQT: 0004/TASMOTA-HEATPUMP/stat/RESULT = {"Module":{"0":"ASTRA R4A4"}}
11:38:39.596 SRC: Backlog
11:38:39.598 CMD: Grp 0, Cmd 'GPIO', Idx 1, Len 3, Pld 255, Data '255'

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
11:40:27.607 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 0, Data '0'
11:40:27.619 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota","","",""],"Topic":"0004/TASMOTA-HEATPUMP","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[15,15,15,15,15,15,15,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":1,"SwitchRetain":1,"SensorRetain":1,"PowerRetain":1,"InfoRetain":1,"StateRetain":1,"StatusRetain":1}} (retained)
11:40:27.676 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release-12.5.0/tasmota32.bin","RestartReason":"Software reset CPU","Uptime":"0T00:09:07","StartupUTC":"2023-10-14T09:31:20","Sleep":50,"CfgHolder":4617,"BootCount":81,"BCResetTime":"2023-08-17T16:01:29","SaveCount":1073}} (retained)
11:40:27.720 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS2 = {"StatusFWR":{"Version":"13.1.0.4(tasmota32)","BuildDateTime":"2023-10-14T11:24:11","Core":"2_0_14","SDK":"4.4.6.231011","CpuFrequency":160,"Hardware":"ESP32-D0WD v1.0","CR":"418/699"}} (retained)
11:40:27.751 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":3,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["J&A",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["000082E9","2805C80001000600003C5A0A192800000000","000000E8","00206000","80044180","00000000"]}} (retained)
11:40:27.798 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS4 = {"StatusMEM":{"ProgramSize":1874,"Free":1005,"Heap":126,"StackLowMark":1,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DIO","Features":["00000809","9F9AD7DF","0015A001","B7F7BFCF","05DA9BC4","E0360DC7","480840D2","20200000","D4BC482D","010A81B1"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,60,62,63,66,67,68,82,86,87,88,90","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,105,109,127","I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48,58,62,65,69,76,77,82"}} (retained)
11:40:27.879 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS5 = {"StatusNET":{"Hostname":"TASMOTA-HEATPUMP","IPAddress":"192.168.0.131","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"62.179.104.196","DNSServer2":"213.46.228.196","Mac":"0C:8B:95:E0:69:A4","IP6Global":"","IP6Local":"fe80::e8b:95ff:fee0:69a4","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"62.179.104.196","DNSServer2":"213.46.228.196","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":2,"WifiPower":17.0}} (retained)
11:40:27.933 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.jst-it.nl","MqttPort":8883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_E069A4","MqttUser":"0004","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}} (retained)
11:40:27.964 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS7 = {"StatusTIM":{"UTC":"2023-10-14T09:40:27","Local":"2023-10-14T11:40:27","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":99,"Sunrise":"08:12","Sunset":"18:59"}} (retained)
11:40:28.003 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS10 = {"StatusSNS":{"Time":"2023-10-14T11:40:27","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON"}} (retained)
11:40:28.030 MQT: 0004/TASMOTA-HEATPUMP/stat/STATUS11 = {"StatusSTS":{"Time":"2023-10-14T11:40:28","Uptime":"0T00:09:08","UptimeSec":548,"Heap":124,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":1,"Berry":{"HeapUsed":5,"Objects":65},"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"J&A","BSSId":"80:2A:A8:51:5D:76","Channel":6,"Mode":"11n","RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:13"}}} (retained)


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Poll and write to Modbus device using mqtt commands

### EXPECTED BEHAVIOUR
No decrease of free heap

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Discussed on Discord:
https://discord.com/channels/479389167382691863/490244847568158751/1162097276609626153

**Comment by jeroenst** [comment]
The leak only happens when writing data to the Modbus device registers.

I searched tasmota/tasmota_xdrv_driver/xdrv_63_modbus_bridge.ino and lib/lib_basic/TasmotaModbus-3.6.0/src/TasmotaModbus.cpp but every malloc is followed by a free, I can't find an exception on that.

Could fragmentation cause such a big memory occupation?

**Comment by jeroenst** [comment]
Also on the latest commit from this morning, the memory leak is still occurring.

**Comment by jeroenst** [comment]
I did several changes and now don't have the memory leak anymore. I suspect that the bytes reserved in the malloc at https://github.com/arendst/Tasmota/blob/715b64dc2821f4cb6e03404118ec49b8afa33cb0/tasmota/tasmota_xdrv_driver/xdrv_63_modbus_bridge.ino#L903 has to be doubled. 

Also ModbusTCP suffers from this I suppose:
https://github.com/arendst/Tasmota/blob/715b64dc2821f4cb6e03404118ec49b8afa33cb0/tasmota/tasmota_xdrv_driver/xdrv_63_modbus_bridge.ino#L699

**Comment by jeroenst** [comment]
That seems to work without any leak. I also added some other memory related fixes that can cause leaking which I'm testing this night. If results are good, I will send the PR tomorrow.

**Comment by jeroenst** [comment]
Tested the fix this night and no memory leak occurs anymore.

![image](https://github.com/arendst/Tasmota/assets/2833940/a0e52488-d2e1-4856-acd3-171d0944201c)


Thanks to @Rolandwalraven for discussing about the wrong memory allocation and to the Tasmota team for their great work.
