### ISSUE TITLE
tasmota starting wifi manager when wifi's ssid is hidden and both AP's ssids have the same size

### ISSUE THREAD

**Issue by RaphaelSquair** [arendst/Tasmota#20218]
### PROBLEM DESCRIPTION
I configured the wifi's ssid of both APs to be the same, so when configuring the device i could change the ssid1 and mantain acess to the device in ssid2 if necessary in the future. but when the router's ssid is hidden and both the AP's ssids are the same, the device starts wifi_manager even if the wificonfig is 4(RETRY)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): wemos d1 mini pro
- [x] Tasmota binary firmware version number used: 13.2.0
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: Platform IO
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Set the APs ssid1 and ssid2 to be the same, and use a wifi with hidden ssid

### EXPECTED BEHAVIOUR
first it should connect to the hidden wifi , second it should not raise the wifi_manager

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
I've tracked the problem to a exact line (L881) it look like it compare if ssid1 equals ssid2 in size but not if they are filled.

if (!strlen(SettingsText(SET_STASSID1)) && !strlen(SettingsText(SET_STASSID2))) {

here is the link
https://github.com/arendst/Tasmota/blame/c6ecaf9bd717c59ad4835d0cd2f786fed2f06fb4/tasmota/tasmota_support/support_wifi.ino#L881C3-L881C3

I dont know what exatcly is causing the device o not connect in the hidden wifi ssid but i think i correctly tracked the second part of the problem.

**Comment by Jason2866** [comment]
Hidden SSID is not supported.
