### ISSUE TITLE
Berry LED Animation Example doesn't work due to missing function

### ISSUE THREAD

**Issue by benjaminnestler** [arendst/Tasmota#20393]
### PROBLEM DESCRIPTION
I try to execute the leds_animation.be example code in the embedded berry console by removing comment around the `import lens_animation` statement.

If I ran the example code in the embedded berry console, the **_Led animation_** button appears on the Management page and not on the main page of Tasmota. The `web_add_main_button()` should be used instead of the `web_add_button()` function.

In the file [tasmota/berry/animate_demo/leds_animation.be](https://github.com/arendst/Tasmota/blob/development/tasmota/berry/animate_demo/leds_animation.be), there is a missing method 
`page_ctl()`. Instead of this function a wrong function - maybe a copy & paste error - `def show_migrate_to_factory(p)` is implemented (seems to be a method from the partition wizard example).

The error issued in the berry console after running the example:
```berry
Exception> 'attribute_error' - the 'Leds_animation_UI' object has no attribute 'page_ctl'
stack traceback:
                <unknown source>: in function `<lambda>`
```

There are further copy & paste fragments from partition wizard code. Like this
```
"<form id=but_part_mgr style='display: block;' action='leds_anim' method='get'><button>Leds animation</button></form><p></p>")
```

The link to the [Leds animation documentation](https://tasmota.github.io/docs/Leds_animation/) on the created website leads to a 404 page.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): LuatOS ESP32C3 DevKit
- [ x] Tasmota binary firmware version number used: current development 
  - [ ] Pre-compiled
  - [x] Self-compiled
- [ x] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Run the leds_animation.be code in the embedded berry console.

### EXPECTED BEHAVIOUR
A working example.

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
Sorry `leds_animation.be` is very early work to test the feasibility of a web UI. It is not working yet and shouldn't have been there in the first place (should be only in my private repo).

Please ignore
