### ISSUE TITLE
Running =>hostname in Tasmota Scripting Language disables it vs the console

### ISSUE THREAD

**Issue by letshin** [arendst/Tasmota#20489]
### PROBLEM DESCRIPTION
When hostname is set through Tasmota Script, the Script checkbox is disabled on the subsequent reboot, although the hostname has successfully changed.. This doesn't happen when hostname is set through the console

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): ESP 12F_____
- [ x] Tasmota binary firmware version number used: 12.4
  - [ ] Pre-compiled
  - [x ] Self-compiled
- [ x] Flashing tools used: Flasher
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua

  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
include 
```
>BS
=>hostname test
```

### EXPECTED BEHAVIOUR
Hostname to have been changed and script continues being enabled 

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
Hostname command force a reboot of tasmota
By adding it in the script you make tasmota rebooting in loop this triggering a boot loop which lead Tasmota to disable your script as bogus

If you had provided the logs as requested, you would see a line similar to
"QRC some settings have been reset" or something similar

Behave as designed
