### ISSUE TITLE
Tasmota PlatformIO Customized serial Rx pin is not functioning properly.

### ISSUE THREAD

**Issue by createskyblue** [arendst/Tasmota#20490]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP32-C3
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____

### TO REPRODUCE
_Steps to reproduce the behavior:_

The latest version of the Tasmota branch.
Tasmota 分支 最新版本
`platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.01.00/platform-espressif32.zip`

"After customizing the serial Rx pin, data reception is not working properly. Below is the minimal code that reproduces the issue."
自定义串口Rx引脚后无法正常接收数据，下面是可以复现该问题的最小代码

[Esp32C3_dev_pio_Serial_test.zip](https://github.com/platformio/platform-espressif32/files/13932174/Esp32C3_dev_pio_Serial_test.zip)

```
#include <Arduino.h>

void setup() {
    Serial.begin(921600, SERIAL_8N1, 5, 4); // Rx = 5, Tx = 4
    Serial.print("READY\n\r");

}

void loop() {
    if (Serial.available()) {
        Serial.write(Serial.read());
    }
}

```

```
[env:esp32-c3-devkitm-1]
; platform = espressif32
platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.01.00/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
; change microcontroller
board_build.mcu = esp32c3
board_build.flash_mode = dio
; change MCU frequency
board_build.f_cpu = 160000000L
upload_protocol = esptool

; build_flags =
;     -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;     -D CONFIG_ARDUHAL_LOG_COLORS=1
;     -D CONFIG_LWIP_IP_FORWARD=1
;     -D CONFIG_LWIP_IPV4_NAPT=1
;     -D CONFIG_LWIP_L2_TO_L3_COPY=1

;     -D ARDUINO_USB_CDC_ON_BOOT=0
;     -D ARDUINO_USB_MODE=0
  

;     ; -D USE_UDP_LOG
;     -DUSE_ESP_IDF_LOG -DLOG_LOCAL_LEVEL=5 -DTAG="\"ARDUINO\"" -DCONFIG_LOG_COLORS
debug_server =
  ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
  -f
  ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts/board/esp32c3-builtin.cfg
  
build_type = release
monitor_filters = esp32_exception_decoder
debug_tool = esp-builtin
upload_port = COM20
monitor_port = COM20
board_build.partitions = default.csv
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
```

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

The purpose of this code is to print the data received from the serial port, but it doesn't work properly in this PlatformIO version.
这个代码的作用是将串口收到的数据打印出来，但是在这个plaofmtio版本中无法正常工作

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by barbudor** [comment]
Tasmota environment is to build Tasmota, not anyone's code
Do you have a qualified issue with Tasmota ?
