### ISSUE TITLE
SONOFF D1 - POWERONSTATE not restored

### ISSUE THREAD

**Issue by Ciberyan** [arendst/Tasmota#20777]
### Discussed in https://github.com/arendst/Tasmota/discussions/20722

<div type='discussions-op-text'>

<sup>Originally posted by **Ciberyan** February 14, 2024</sup>
Hello All
I migrate my **Sonoff D1 dimmer** to **Tasmota 13.3.0**, as many of my Sonoff switches
Everythings is working as expected, Power On, Off, Dimming but NOT the POWERONSTATE
Whatever I set, the connected light doesnt comes up as I would like, and as I have set it through **"POWERONSTATE 1"**
In the WEBUI and in the console at power on I get :
The state of the output is right,ie **ON**, but no light
The dimmer stay at the level it was before, but no light

To get the light comes on I need either
Change the DIMMER value slightly (issuing the same value doesnt change)
Or send a Power Off then Power ON

As I plan to put it in my ceiling, I need the light come up on his own when powered

Does anybody involved in the D1 already see that behaviour ?

Thanks in advance for any idea 

PS : the Lights On at PowerOn works ok in the Ewelink application when downgraded to standard Sonoff firmware

PS2 : Upgrade to 13.4.0 doenst change anything obviuosly

D1 doenst have rules so I cant write something to avoid this behaviour

We are vey close of a funcionning system but No Power On at startup is a no go

Hopefully someone will/can handle that

Cant we imagine to have a kind of sequence executed automatically  at powerup doing POWER 0 then right after a Power 1
</div>

**Comment by MacGH23** [comment]
Have a similar issue with a Nous A1T and Refoss P11 wall plug.
With 13.4 the last state is not saved.
I can setup fixed ON and OFF (PowerOnState 0/1) but 3 Restore last is not working

**Comment by stefanbode** [comment]
there is a setoption63 I think that in the boot process check the current state an set it. Maybe switching it OFF may solve this. set it to 1.

**Comment by MacGH23** [comment]
unfortunately not.

**Comment by stefanbode** [comment]
Can you upload the log file with loglevel4. Please one time when the relay was off before boot and one when the relay was on before boot. It is not a general problem and we will find out.

**Comment by Jason2866** [comment]
Closing since no feedback

**Comment by Ciberyan** [comment]
Sorry
I am out my home for business and cant make the test
I am sure the problem is still alive but I cant help more for the moment
Sorry for that

**Comment by Jason2866** [comment]
Please reopen when you have verified not working

**Comment by MacGH23** [comment]
Sorry, was on vacation and forgot to answer
[onoff.txt](https://github.com/arendst/Tasmota/files/15246360/onoff.txt)
