### ISSUE TITLE
Fade out on CCT bulb (with SO92) when set to warm - problem since v13.0.0

### ISSUE THREAD

**Issue by KLLKP** [arendst/Tasmota#20945]
Short story:
Light with dimm and white color temp. (2 PWMs).
SO92 Off: 
	PWM1 - Cold white
	PWM2 - Warm white
SO92 On: 
	PWM1 - Brightness 
	PWM2 - Color Temp (Cold/Warm white)

When it comes to fade out (power on->off) it use both PWMs regardless of SO92 but should use just PWM1 when SO92.
It was OK up to 12.5.0, since 13.0.0 its wrong.

Below whole story...

Hi to all here!

I use device with "SetOption92 1" (CCT - second PWM as Color Temp instead of Warm White) and it looks like fade command doesn't follow set SetOption92, effect is strange. 
Same about Fade when light is turned off and when turned on - strange effect. 
Strange effect means that during fade CT color is changing (not like using dimmer slider only).
Before i used proper setup (template fix and SO92 - see below) using web slider on tasmota page also gave strange effect.

Tested at many values of speed. Don't know if fade follows DimmerRange too, can't judge it at now.

To make my bulb works properly with tasmota web sliders (CT and dimmer)  i had to use SetOption92, change PWMs number (channels?) and invert one.

Template:
{"NAME":"Azzardo AZ3206 LightBulb","GPIO":[0,0,0,0,0,0,0,0,449,0,416,0,0,0],"FLAG":0,"BASE":18}
GPIO12: PWM_i - 2
GPIO14: PWM - 1

Commands:
SetOption92 1
Fade 1
Speed 2
DimmerRange 30,100

Device: Azzardo AZ3206 bulb with dimmer and color temp.
Board: Tuya TYWE2S 
ESP Chip Id: 12345371 (ESP8285N08)
Flash Size:	1024 KB
Program Size:	646 KB

Flash image:  tasmota.bin (precompiled - flashed by webinstaller)
Program Version	13.4.0(tasmota)
Build Date & Time	2024-02-14T16:13:56
Core/SDK Version	2_7_6/2.2.2-dev(38a443e)

Regards
Chris
[tasmota.bin](https://ota.tasmota.com/tasmota/release/tasmota.bin)

**Comment by KLLKP** [comment]
I investigated problem of fade a bit more... to better follow fade steps i used various speed (2-30).
1) when light is on: fade between CT Warm and Cool and back - works fine.
2) when temp is set to Cool {"POWER":"ON","Dimmer":100,"Color":"FF00","White":100,"CT":153,"Channel":[100,0]}
Fade in and out (power on/off) - works fine.
3) when temp is set to Warm {"POWER":"ON","Dimmer":100,"Color":"00FF","White":100,"CT":500,"Channel":[0,100]}
Fade in (power on) - works fine
Fade out (power off) - at the same time it race through dimm and colour - dimmer reduce brightnes (ok) but it also change temp from Warm to Cool at every fade steps (with pure cool at least).

So.. its all about fade out when CT is warm.

Ledtable on/off doesn't change that behavior.

**Comment by KLLKP** [comment]
Hi,
I'v checked a bit more and... it works as should with tasmota-lite ver. 9.2.0 up to 12.5.0, since 13.0.0 it works bad.

Tested with official builds [https://ota.tasmota.com/]:
	tasmota-lite ver.  9.2.0 - OK :)
	tasmota-lite ver. 10.0.0 - OK :)
	tasmota-lite ver. 12.0.2 - OK :)
	tasmota-lite ver. 12.5.0 - OK :)
	tasmota-lite ver. 13.0.0 - BAD :( ..dimm with color race!
	tasmota-lite ver. 13.1.0 - BAD :( ..dimm with color race!
	tasmota-lite ver. 13.4.0 - BAD :( ..dimm with color race!

How to reproduce:
Needed: 
	Light bulb with Dimmer + CT (SO92: Cold/Warm white - second PWM as Color Temp instead of Warm White)
	{"NAME":"Azzardo AZ3206 LightBulb","GPIO":[0,0,0,0,0,0,0,0,449,0,416,0,0,0],"FLAG":0,"BASE":18}
Initial commands:
	SetOption92 1
	Fade 1
	Speed 8
	DimmerRange 30,100
Commands to prepare a test:
     Power1 1
     Dimmer 100
     CT 500
Run test with:
     Power1 0
Symptom:
     Instead of just dimm out it: dimm with changing color from warm to cold white.

Checked on 10 bulbs.

**Comment by KLLKP** [comment]
Anyone read this? Something is missing here or unclear? Any details should be added?

**Comment by s-hadinger** [comment]
Yes. Thanks for the details. Since it used to work fine, it will be easier to fix. I will work on it

**Comment by KLLKP** [comment]
> Yes. Thanks for the details. Since it used to work fine, it will be easier to fix. I will work on it

Thanks.... its good to hear ;)
If You have any question.. just ask.
You can look into LightAnimate() [xdrv_04_light.ino], there probobly shlould be handled SO92 somewhere after call calcGamma.... There is solution for ChannelWhite_when_PWMCT, maybe its good place for fix.

**Comment by s-hadinger** [comment]
I think the faulty commit is https://github.com/arendst/Tasmota/commit/9d57a19be3b2d48acb2885dd8435cd0bc204b029

**Comment by KLLKP** [comment]
Hi 
I can confirm that problem is solved, good job.
Thank You.
