### ISSUE TITLE
Documentation for comands 'subscribe' and 'subscribe2' is swapped

### ISSUE THREAD

**Issue by apostrophe55** [arendst/Tasmota#21302]
Unfortunately the documentation for the two commands is swapped/not correct

![grafik](https://github.com/arendst/Tasmota/assets/16974610/5b509a9d-6054-4245-9a89-b495affc1e64)

_Originally posted by @apostrophe55 in https://github.com/arendst/Tasmota/discussions/12858#discussioncomment-9228915_

**Comment by s-hadinger** [comment]
Thanks. I tried to clarify the doc
