### ISSUE TITLE
Send JSON to MQTT with Tasmota not working

### ISSUE THREAD

**Issue by raduigret** [arendst/Tasmota#21478]
### Discussed in https://github.com/arendst/Tasmota/discussions/21477

<div type='discussions-op-text'>

<sup>Originally posted by **raduigret** May 23, 2024</sup>
I have 2 Tasmotas flashed with same standard FW.
On tasmota A, if I send JSON format via UART, it is send via MQTT as below:
**MQT: tele/tasmota_234e33h/RESULT = {"SerialReceived":{"test":2}}**
but on tasmota B, if I send same payload, it reported as below in console:
**CMD: {"test":2}**

Both have same configuration: 
![image](https://github.com/arendst/Tasmota/assets/80286831/5783e934-c1c6-414b-8f2a-575f35885928)

the only exception is that A (that works) was configured some months before and I forgot what default settings I changed and runs Tasmota 13.4.0.4,
while B (that does not work) has Tasmota 14.0.0 and default settings.

Please help me how to configure it to send received json from serial via MQTT as above.</div>

**Comment by sfromis** [comment]
Do not open an issue when there is already a discussion about how to make it work.
