### ISSUE TITLE
Matter Custom/Unknown Cluster Cluster exposed on Endpoints ClusterId 5 (0x005) --> Scene cluster from Matter 1.0 specs

### ISSUE THREAD

**Issue by lboue** [arendst/Tasmota#21613]
### PROBLEM DESCRIPTION
Hello,

I noticed an Matter Custom/Unknown Cluster Cluster exposed on Endpoint 2 **ClusterId 5 (0x005**) by Tasmota.
Could you tell us what this cluster is that is not recognised in Home Assistant?

![image](https://github.com/arendst/Tasmota/assets/938089/dc8302b1-0668-46c7-aa2c-7bed282a28dd)

![image](https://github.com/arendst/Tasmota/assets/938089/5b095f69-9d7f-45e6-a9b7-dee24f32bd32)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): M5 [ATOM Lite](https://docs.m5stack.com/en/core/atom_lite)
- [ ] Tasmota binary firmware version number used: Tasmota 14.1.0.2 (87148ae-tasmota32) 
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: [_____](https://tasmota.github.io/install/)
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
21:29:50.335 RSL: RESULT = {"NAME":"ESP32-DevKit","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
21:29:50.560 RSL: RESULT = {"Module":{"1":"ESP32-DevKit"}}
21:29:50.815 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"7648":"Input1"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"0":"None"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"0":"None"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
21:30:30.880 RSL: STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_D686D0","ButtonTopic":"0","Power":"0","PowerLock":"0","PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
21:30:30.928 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Vbat power on reset","Uptime":"0T00:07:51","StartupUTC":"2024-06-11T20:22:39","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2024-06-11T20:54:20","SaveCount":17}}
21:30:30.964 RSL: STATUS2 = {"StatusFWR":{"Version":"14.1.0.2(87148ae-tasmota32)","BuildDateTime":"2024-06-11T15:32:03","Core":"3_0_1","SDK":"5.1.4.240602","CpuFrequency":160,"Hardware":"ESP32-PICO-D4 v1.0","CR":"412/699"}}
21:30:30.979 RSL: STATUS3 = {"StatusLOG":{"SerialLog":3,"WebLog":2,"MqttLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["*****",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000020"]}}
21:30:31.014 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":2017,"Free":862,"Heap":101,"StackLowMark":2,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640C8","FlashFrequency":40,"FlashMode":"DIO","Features":["0809","9F9AD7DF","0015A001","B7F7BFCF","05DA9BC4","E0360DC7","480840D2","20200000","D4BC482D","810A80B1","00000014"],"Drivers":"1,2,!3,!4,!5,7,!8,9,10,11,12,!14,!16,!17,!20,!21,!24,26,!27,29,!34,!35,38,50,52,!59,!60,62,!63,!66,!67,!68,!73,82,!86,!87,!88,!121","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,105,109,127","I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48,58,62,65,69,76,77,82"}}
21:30:31.088 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-D686D0-1744","IPAddress":"192.168.1.195","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.254","DNSServer2":"9.9.9.9","Mac":"4C:75:25:D6:86:D0","IP6Global":"","IP6Local":"fe80::4e75:25ff:fed6:86d0%st1","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"192.168.1.254","DNSServer2":"9.9.9.9","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":16.0}}
21:30:31.138 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D686D0","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
21:30:31.158 RSL: STATUS7 = {"StatusTIM":{"UTC":"2024-06-11T20:30:31Z","Local":"2024-06-11T21:30:31","StartDST":"2024-03-31T02:00:00","EndDST":"2024-10-27T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:53"}}
21:30:31.177 RSL: STATUS10 = {"StatusSNS":{"Time":"2024-06-11T21:30:31"}}
21:30:31.187 RSL: STATUS11 = {"StatusSTS":{"Time":"2024-06-11T21:30:31","Uptime":"0T00:07:52","UptimeSec":472,"Heap":104,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Berry":{"HeapUsed":27,"Objects":312},"Wifi":{"AP":1,"SSId":"*****","BSSId":"C0:8A:DE:22:C5:B8","Channel":13,"Mode":"HT20","RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Setup Matter on Tasmota
2. Add Waterleak Local sensors
3. Pair Tasmota device with Apple Home
4. Pair Tasmota device with Home Assistant

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
Do not expose this unknown cluster.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I can't find ClusterId 5 (0x005) here:
[connectedhomeip: List of currently defined spec clusters](https://github.com/project-chip/connectedhomeip/blob/master/docs/spec_clusters.md)

**HA Matter diag file**
[matter-2a4bd9d95d966aefd2521cccecaf2a8f-Waterleak-247c0c4d17d994c5ecb4c62ecba09c69.json](https://github.com/user-attachments/files/15794537/matter-2a4bd9d95d966aefd2521cccecaf2a8f-Waterleak-247c0c4d17d994c5ecb4c62ecba09c69.json)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by lboue** [comment]
@s-hadinger told me 0x0005 is the old Zigbee Scene cluster.

This seems to have been replaced by cluster 0x0062. This can be found in the ‘Matter-1.3-Core-Specification.pdf’: ‘ 1.4. Scenes Management Cluster'.

**Comment by s-hadinger** [comment]
This was indeed changed between Matter 1.2 and Matter 1.3:
"Based on the ZCL Scenes Cluster, Updated the Cluster ID to 0x0062, the name to Scenes Man­agement[...]"

It's surprising that cluster 0x0005 is marked as unknown, it is still valid up to Matter 1.2. Using cluster 0x0062 requires the device revision number to be updated, which is not the case in Tasmota.

**Comment by Jason2866** [comment]
Looks like a bug in Home Assistant to me.

**Comment by lboue** [comment]
I will open an issue for this bug. Thanks.
