### ISSUE TITLE
MCP23017 address 0x27 not working

### ISSUE THREAD

**Issue by piotranon** [arendst/Tasmota#21953]
### PROBLEM DESCRIPTION
Using a MCP23017 gpio expander I2C address of 0x27 is not working.
In docs https://tasmota.github.io/docs/MCP230xx/, there is a provided list of chip adresses and I2C adresses, but adress of 0x27 can't be controlled, when i change the i2c adress of the device to any other from 0x20 to 0x26 its working correctly.

In I2CDevices list i found that adress 0x27 is not specified in driver xdrv_67.
https://github.com/arendst/Tasmota/blob/development/I2CDEVICES.md

In https://tasmota.github.io/docs/MCP230xx/ should be provided a info of supported i2c adresses or adresses of xdrv_67 should be extended to 0x27.

Is it intended to limit address to 0x26?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): **wemos d1 mini, mcp23017 with 16ch relay**
- [x] Tasmota binary firmware version number used: **2_7_7/2.2.2-dev(38a443e)**
  - [ ] Pre-compiled
  - [x] Self-compiled with **USE_MCP23XXX_DRV** and 
- [x] Flashing tools used: **Tasmota Web installer**
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
23:40:05.940 RSL: RESULT = {"NAME":"My board","GPIO":[0,0,0,0,640,608,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}
23:40:06.147 RSL: RESULT = {"Module":{"0":"My board"}}
23:40:06.353 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"640":"I2C SDA"},"GPIO5":{"608":"I2C SCL"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
23:41:51.995 RSL: RESULT = {"Rule1":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
23:41:52.202 RSL: RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
23:41:52.453 RSL: RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":187,"Free":324,"Rules":"on file#mcp23x.dat do {\"NAME\":\"My expander\",\"GPIO\":[224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255]} endon"}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
23:42:42.494 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_21B23F","ButtonTopic":"0","Power":"0","PowerLock":"0","PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
23:42:42.498 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:19:26","StartupUTC":"2024-08-12T22:23:16","Sleep":50,"CfgHolder":4617,"BootCount":18,"BCResetTime":"2024-08-12T23:01:56","SaveCount":46,"SaveAddress":"3FB000"}}
23:42:42.505 RSL: STATUS2 = {"StatusFWR":{"Version":"14.1.0.4(tasmota)","BuildDateTime":"2024-08-12T21:58:08","Boot":31,"Core":"2_7_7","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"345/699"}}
23:42:42.510 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Dom_402",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
23:42:42.522 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":723,"Free":1324,"Heap":22,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["0809","8F9AC78F","04368001","000000CF","010013C0","C000F981","00004084","00201000","54000020","00020080","00000000"],"Drivers":"1,2,!3,!4,!5,!6,7,!8,9,10,12,!16,!18,!19,!20,!21,!22,!24,26,!27,29,!30,!35,!37,38,!45,50,62,!67,!68","Sensors":"1,2,3,4,5,6","I2CDriver":"7,77"}}
23:42:42.527 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-21B23F-4671","IPAddress":"192.168.0.135","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"1.1.1.1","DNSServer2":"8.8.8.8","Mac":"84:F3:EB:21:B2:3F","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
23:42:42.531 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_21B23F","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
23:42:42.536 RSL: STATUS7 = {"StatusTIM":{"UTC":"2024-08-12T22:42:42Z","Local":"2024-08-12T23:42:42","StartDST":"2024-03-31T02:00:00","EndDST":"2024-10-27T03:00:00","Timezone":"+01:00","Sunrise":"05:39","Sunset":"20:10"}}
23:42:42.540 RSL: STATUS10 = {"StatusSNS":{"Time":"2024-08-12T23:42:42"}}
23:42:42.546 RSL: STATUS11 = {"StatusSTS":{"Time":"2024-08-12T23:42:42","Uptime":"0T00:19:26","UptimeSec":1166,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Wifi":{"AP":1,"SSId":"Dom_402","BSSId":"02:EB:D8:20:48:32","Channel":4,"Mode":"11n","RSSI":82,"Signal":-59,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
Compile binary with **USE_MCP23XXX_DRV** and use device MCP23017 gpio expander with set adress to 0x27.
GPIO4 mapped to I2C SDA.
GPIO5 mapped to I2C SCL.
and connected to MCP23017 to coresponding ports sda -> sda, scl ->scl.
I created file mcp23x.dat with 
```
{"NAME":"MCP23017","GPIO":[224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287]} 
```
because im using MCP23017 with 16chanel relay.
- [x] I2CScan log
```
23:43:26.529 CMD: I2CScan
23:43:26.549 RSL: RESULT = {"I2CScan":"Device(s) found at 0x27"}
```
### EXPECTED BEHAVIOUR
Driver should be allowed to controll i2c device at adress of 0x27.

### SCREENSHOTS
![image](https://github.com/user-attachments/assets/7c3a85bc-563e-494b-8d7a-609c93a8bd78)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Looking into the [driver](https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_67_mcp23xxx.ino), I'm seeing lines as:
```
* I2C Address: 0x20 - 0x26 (0x27 is not supported)
...
#define MCP23XXX_ADDR_START      0x20     // 32
#define MCP23XXX_ADDR_END        0x26     // 38
```

Thus, the driver will not even look at address `9x27`. IIRC one issue was conflicts with LCD displays locked at address `0x27`, but not having experience with either, I can't say how things are "supposed" to work, or if it is just making sure that the docs lists this restriction.

*Maybe* it would work for you if you change the driver to not end addresses at `0x26`.
