### ISSUE TITLE
Bluetooth BT BLE devives (EQ3) not connecting properly

### ISSUE THREAD

**Issue by AleXSR700** [arendst/Tasmota#22267]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I do not know if this is related to issue https://github.com/arendst/Tasmota/issues/21445, but after upgrading my esp32/esp32c3 devices to 14.2.0.6, my eQ3 devices are no longer connecting reliably.

I have 8 Xiaomi devices and 8 EQ3s. The Xiaomis (running ATC firmware) seem to work but the EQ3s just show `20:44:07.951 EQ3: 001A2208C9FA: trv operation failed - retrying -12` (with the respective device ID).

Interestingly, I see all 8 EQ3 TRVs right after a restart and they briefly show the correct temperatures in the WebUI. But then the connection starts failing and all values are set to 0.

Does anybody have similar issues?

EDIT: Reverted to 13.4.0 (http://ota.tasmota.com/tasmota32/release-13.4.0/tasmota32-bluetooth.bin) and it works again. So seems that something is broken in 14.2.0.6 again.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): esp32 and esp32c3
- [x ] Tasmota binary firmware version number used: 14.2.0.x
  - [x ] Pre-compiled
  - [ x] Self-compiled
- [x ] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
14:22:13.465 CMD: status 0
14:22:13.475 MQT: stat/tasmota_F66EEC/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_F66EEC","ButtonTopic":"0","Power":"0","PowerLock":"0","PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
14:22:13.519 MQT: stat/tasmota_F66EEC/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://192.168.0.2:8000/tasmota32c3-bluetooth.bin","RestartReason":"Software reset digital core","Uptime":"0T00:02:38","StartupUTC":"2024-10-11T13:19:35","Sleep":50,"CfgHolder":4618,"BootCount":1,"BCResetTime":"2024-10-11T14:19:40","SaveCount":6}}
14:22:13.567 MQT: stat/tasmota_F66EEC/STATUS2 = {"StatusFWR":{"Version":"14.2.0.6(bluetooth)","BuildDateTime":"2024-10-10T23:20:25","Core":"3_1_0","SDK":"5.3.1.240924","CpuFrequency":160,"Hardware":"ESP8685 v0.4","CR":"429/699"}}
14:22:13.593 MQT: stat/tasmota_F66EEC/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["BaumlerlangenHA24",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004002","00000000"]}}
14:22:13.625 MQT: stat/tasmota_F66EEC/STATUS4 = {"StatusMEM":{"ProgramSize":1725,"Free":1154,"Heap":85,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":"DIO","Features":["0809","8F9AC7CF","00148001","000000CF","011013C0","C0000981","40004080","00200000","5400082C","40000080","00000004"],"Drivers":"1,2,!3,!4,!5,7,!8,9,10,12,!16,!20,!21,!24,26,!27,29,!35,38,50,52,!59,62,!68,79,82,85,!121","Sensors":"1,2,3,5,6,40,52,62,127","I2CDriver":"7"}}
14:22:13.685 MQT: stat/tasmota_F66EEC/STATUS5 = {"StatusNET":{"Hostname":"tasmota-F66EEC-3820","IPAddress":"192.168.0.22","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.0.1","DNSServer2":"0.0.0.0","Mac":"54:32:04:F6:6E:EC","IP6Global":"","IP6Local":"fe80::5632:4ff:fef6:6eec%st1","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"192.168.0.1","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":19.0}}
14:22:13.751 MQT: stat/tasmota_F66EEC/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F66EEC","MqttUser":"mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
14:22:13.789 MQT: stat/tasmota_F66EEC/STATUS7 = {"StatusTIM":{"UTC":"2024-10-11T13:22:13Z","Local":"2024-10-11T14:22:13","StartDST":"2024-03-31T02:00:00","EndDST":"2024-10-27T03:00:00","Timezone":"+01:00","Sunrise":"07:05","Sunset":"18:07"}}
14:22:13.810 MQT: stat/tasmota_F66EEC/STATUS10 = {"StatusSNS":{"Time":"2024-10-11T14:22:13"}}
14:22:13.823 MQT: stat/tasmota_F66EEC/STATUS11 = {"StatusSTS":{"Time":"2024-10-11T14:22:13","Uptime":"0T00:02:38","UptimeSec":158,"Heap":87,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":4,"Objects":47},"Wifi":{"AP":1,"SSId":"BaumlerlangenHA24","BSSId":"F8:D2:AC:D6:92:A0","Channel":6,"Mode":"HT40","RSSI":100,"Signal":-45,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [x ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
14:24:16.816 CMD: trvperiod 30
14:24:16.819 SRC: WebConsole from 192.168.0.168
14:24:16.821 CMD: Grp 0, Cmd 'TRVPERIOD', Idx 1, Len 2, Pld 30, Data '30'
14:24:16.832 MQT: stat/tasmota_F66EEC/RESULT = {"trvperiod":30}
14:24:19.725 EQ3: 001A2214ADC8: Poll fail not sent because EQ3HideFailedPoll
14:24:19.727 EQ3: 001A2214ADC8: trv operation failed - no more retries -12
14:24:19.735 MQT: tele/tasmota_F66EEC/BLE = {"BLEOperation":{"opid":"3","stat":"-12","state":"FAILNOTIFY","MAC":"001A2214ADC8","u":"128","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","notifychar":"d0e8434d-cd29-0996-af41-6c90f4e0eb2a","write":"03180A0B0E1808000000000000000000"}}
14:24:23.428 M32: A4C138F28078: New ATC at slot 4

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Upgrade to 14.2.0 and enable BLE (if not already enabled). Check console for EQ3-TRV messages.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
@btsimonh Can you please have a look?

**Comment by SteWers** [comment]
It is working fine in 14.0.0.1

**Comment by btsimonh** [comment]
@Jason2866 - family issues, but I'll try to take a look :(

**Comment by btsimonh** [comment]
works on fresh build of 14.2.0.1 on S3.  EQ3 polling all good, out of 10 polls of three devices, only one failure (to be expected).
works on build of 14.2.0.5.....
I note that 1248bd138c7eda34fe91d9f60721a78210a27b56 changes the core version (commit before 14.2.0.6)
works with 14.3.0.1 69f7f155dd3750ff44f620556d3d46c3ae25beda
But... possibly more failed to connect, a few in a row.

**Comment by btsimonh** [comment]
@AleXSR700 could you try again?  If with 14.3.0.1 you still have consistent failures, check your wifi traffic (including MQTT, etc.).  I had none beyond the GUI.  Wifi and BLE do NOT play nice....  If possible, check serial logs with all connections closed to the esp.
If necessary, I will build for 'std' esp32 (I have some webcam boards I bought for Eq3 use because of external antennas), and test again; just not sure when.

**Comment by AleXSR700** [comment]
I will start a new build and start testing tomorrow.

Btw, you are building the base binaries instead of the `bluetooth` variant?

```
#define USE_MI_ESP32 
#define USE_BLE_ESP32 
#define USE_EQ3_ESP32
```

These are all part of the bluetooth variant (not sure if there is more to it than this plus the libs).

I will test as before with the `bluetooth` variant and if that fails, build and test the base image with those three  enabled manually to countercheck.

**Comment by btsimonh** [comment]
I built `tasmota32s3-bluetooth` with the above. (bluetooth variants did not used to have USE_BLE_ESP32 or USE_EQ3_ESP32.  now it seems they all do?) 

I double checked configs, and it seems FIRMWARE_BLUETOOTH contains all for EQ3 except in _mi32 variants.

so double check your `platformio_tasmota_cenv.ini` is the same as the `platformio_tasmota_cenv_sample.ini` (for your c3), and the pure bluetooth variants should be fine.  The fact that you have logs from the EQ3 driver indicate your build contained everything required.

**Comment by btsimonh** [comment]
I don't have a c3 to test with :(.  could you try on plain esp32?

**Comment by Jason2866** [comment]
There is a big update ahead for the BLE legacy stuff. Look in open PRs ;-)

**Comment by AleXSR700** [comment]
> I don't have a c3 to test with :(. could you try on plain esp32?

Yes, I have a devkit esp32. So if you have a build you would like me to test, happy to.

**Comment by AleXSR700** [comment]
> There is a big update ahead for the BLE legacy stuff. Look in open PRs ;-) There is no TRV driver for the MI BLE (and there will be none). The MI BLE is the more actual BLE code.

Would kind of be nice to have one BLE variant for all BLE devices :)

**Comment by Jason2866** [comment]
> Would kind of be nice to have one BLE variant for all BLE devices :)

Will not happen since the drivers have different goals and design concepts.

**Comment by btsimonh** [comment]
looking at the berry in the PR, seems an EQ3 driver could be written in berry over the 'new' legacy stuff? (I am not volunteering!).

**Comment by AleXSR700** [comment]
@btsimonh @SteWers 👍 
Did you test with latest TRV firmware 1.46 or above?

I now flashed the tasmota32-bluetooth and tasmota32c3-bluetooth from here: https://github.com/tasmota/install/releases/tag/2024-10-16.d.e39f1cc83f17100adc41fb8b6d18a792ecd50c11

I wanted to rule out any build issues.

Neither the ESP32 nor the ESP32C3 seem to work properly. In the WebUI I see all my ATC information (Xiaomi Mijia devices) correctly but all my EQ3s only show 0 values (except for RSSI, which is not a value published by the EQ3). 

So all set point temperatures, valve positions and batteries are 0 all the time.

I flashed the downloaded binaries and then performed a reset 1. Then connected back to network, turned on BLE and power cycled.

**Comment by AleXSR700** [comment]
> I don't know the firmware of the TRV.

It is displayed when you put the batteries in. 
In the newer firmware (1.46 and above) the manufacturer changed the pairing mechanism/key.
https://github.com/arendst/Tasmota/issues/16775

So if the tested EQ3 firmware is older, the issue might be related to the linked one and would not affect all EQ3 devices.
I upgraded of mine to 1.46, so it is not possible to test if it would work with the older ones.

**Comment by SteWers** [comment]
> It is displayed when you put the batteries in.

Mine has version 1.20

**Comment by btsimonh** [comment]
mine are all older firmware.
it's odd that is works for you with older TAS, but newer EQ3 firmware - the key stuff was some time ago.
I'd suggest that the key stuff was not about the key (I don't think it needed it in the end?  it just worked again after some tweaks?), but about doing some handshake.  Maybe check the commits associated with https://github.com/arendst/Tasmota/issues/16775 and see what was added to make it work then, then check for changes in the idf/nimble?

**Comment by AleXSR700** [comment]
> mine are all older firmware.
> it's odd that is works for you with older TAS, but newer EQ3 firmware - the key stuff was some time ago.

No, I deliberately stayed with firmware versions newer than that handshake/pairing change.
So firmware v12 and v13 versions post https://github.com/arendst/Tasmota/issues/16775

> Maybe check the commits associated with https://github.com/arendst/Tasmota/issues/16775 and see what was added to make it work then, then check for changes in the idf/nimble?

Since all of your devices are older firmware but work and the same applies for SteWers, I was thinking the same thing. Seems like a change made back im v12 to fix the compatibility with newer EQ3 firmware is no longer present or working in v14.

Maybe @h2zero has an idea?

**Comment by btsimonh** [comment]
looked for my 'spare' eq3 today (the one i dismantled and broke the wheel on...) to see if I could upgrade it and test.
But it's not going to happen:
![20241019_092443](https://github.com/user-attachments/assets/163ef9df-6dbe-457d-b401-610bca5fedee)
Washing has so far not brought it to life....

**Comment by btsimonh** [comment]
ok, that one is fubar.  (It does now start, but I can't read the display).
I found another... (one which had broken off the rad).  It's now on 1.46, and I get at a distance of 20cm:
```
15:44:09.723 EQ3: 001A22092FB7: Op queued len now 1
15:44:09.725 EQ3: 001A22092FB7: Op dequeued len now 0
15:44:12.314 BLE: failed subscribe for notify
15:44:12.438 BLE: BLETask: op failed -12
15:44:13.691 EQ3: 001A22092FB7: trv operation failed - retrying -12
15:44:13.697 RSL: BLE = {"BLEOperation":{"opid":"1","stat":"-12","state":"FAILNOTIFY","MAC":"001A22092FB7","u":"128","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","notifychar":"d0e8434d-cd29-0996-af41-6c90f4e0eb2a","write":"03180A130F2C09000000000000000000"}}
15:44:15.956 BLE: failed subscribe for notify
```
It works with the Calorbt app.
5 other EQ3 have responded....
Tas version 14.3.0.1 on esp32S3

I'll check it out some more.

**Comment by btsimonh** [comment]
@Staars Cristian - help :).  You have latest and intimate knowledge of esp-nimble-cpp....
@h2zero too if you are able.

We're hitting AddLog(LOG_LEVEL_ERROR,PSTR("BLE: failed subscribe for notify")); - line 1921 in tasmota\tasmota_xdrv_driver\xdrv_79_esp32_ble.ino

This is happening only for EQ3 firmware versions which have 'new' security.
Seems to me that the device is connected, has a valid characteristic, says that characteristic can notify, but then nimble is telling us it can't subscribe.... (pNCharacteristic->subscribe returns false).

Any advice or guidance appreciated.
br,
Simon

**Comment by Staars** [comment]
In line 1911:
`            if(pNCharacteristic->subscribe(true, BLE_ESP32::BLEGenNotifyCB)) {`

You try to subscribe to an indication and not a notification. Is this intended?

**Comment by Staars** [comment]
Ahh, no ... it is the opposite. forget it.

**Comment by Staars** [comment]
But at least in 1911 an incomplete function signature is used - missing the `response`. IDK if this is a problem.

**Comment by btsimonh** [comment]
14.1.0 (lvgl-haspmota) - not working,
trying 14.0.0.2..... not working.
13.4.1.1 (lvgl-haspmota)- BLE does not work at all.
13.4.0(lvgl-haspmota) works.

**Comment by AleXSR700** [comment]
> 14.1.0 (lvgl-haspmota) - not working,
> trying 14.0.0.2..... not working.
> 13.4.1.1 (lvgl-haspmota)- BLE does not work at all.
> 13.4.0(lvgl-haspmota) none of the eq3 work.  maybe something is wrong with my build.
> 

See the opening post of this thread. I linked the build for 13.4.0 there. Just download that one. It won't have yourWifi or mqtt settings of course, but should at least work for testing.

**Comment by h2zero** [comment]
If I was to guess I would say that it's failing to subscribe because it should write to the descriptor with response request as per BT specifications. The older devices/firmwares wouldn't accept that in the past so that's the reason for writing without response now. At least that's what i remember.

**Comment by btsimonh** [comment]
come to it in the morning, and 13.4.0 on S3 is working for all Eq3, including ones running older firmware and the one running 1.46 - it must have just been taking it's time getting the data, and I rushed the assessment.
I'll walk forward again in versions.
@Staars - `response` is defaulted to true in the header for the function.  but from h2zero, maybe this is the issue....  maybe it needs false.
@h2zero - could this https://github.com/h2zero/esp-nimble-cpp/commit/5b24c8d681f967be85dd6dd1566657f7a47b0c06 be involved? - or is that only for BLE servers?

**Comment by btsimonh** [comment]
@Staars @h2zero - the PR works with both of the versions of EQ3 firmware that I have.
Please have a quick look and comment.
(I thought this may be in the characteristics properties, but the props are always `characteristic props 0x1A` for both firmwares).

**Comment by btsimonh** [comment]
@AleXSR700  - I can't seem to find individual artifacts for the PR, but I assume the firmwares are all in  https://github.com/arendst/Tasmota/actions/runs/11424841639/artifacts/2078856871 - 138mbytes.

**Comment by Staars** [comment]
> @Staars @h2zero - the PR works with both of the versions of EQ3 firmware that I have. Please have a quick look and comment. (I thought this may be in the characteristics properties, but the props are always `characteristic props 0x1A` for both firmwares).

I suppose the needed response value is device specific (here for the EQ-3). So the PR looks good to me.

Since a few days we can easily customise the Arduino framework for a specific Tasmota build, which is especially useful for (before impossible) individual Bluetooth settings including the log level.
If it is not enough to add a build flag, like: `-DCONFIG_NIMBLE_CPP_LOG_LEVEL=3` to `build_flags `
you can bake these kind of things into the Arduino framework now with:
```
custom_sdkconfig  =  CONFIG_NIMBLE_CPP_LOG_LEVEL=3
```

I did not test this particular use case yet. Maybe you need to provide both sections, it is still e very new feature and not finally finished.

**Comment by btsimonh** [comment]
@Staars - did you test notify to get battery from MI in your new implementation yet?
The PR mod will affect MI32 when using BLE32 - i.e. it uses the same notify fn.
If you test and find that `response` MUST be true for the MI battery read fn, then I'll make it EQ3 specific somehow.... - let me know.

**Comment by AleXSR700** [comment]
Thank you all!
I was away for the weekend but will also test tomorrow :)

**Comment by Staars** [comment]
> @Staars - did you test notify to get battery from MI in your new implementation yet? The PR mod will affect MI32 when using BLE32 - i.e. it uses the same notify fn. If you test and find that `response` MUST be true for the MI battery read fn, then I'll make it EQ3 specific somehow.... - let me know. (I don't have an MI style device that required connection....)

As I converted basically all my devices to PVVX I can not tell ATM. It was a cumbersome procedure anyway and I suggest to wait for "real world" user issues. But if I stumble across findings I will report here.

**Comment by AleXSR700** [comment]
Completely off topic, but will you maybe implement BTHome into the normal bluetooth variant so it can be used on devices that also handle EQ3? 

Right now it is either BTHome (tasmota legacy ble) or Pvvx  (soon deprecated) with EQ3 (current `-bluetooth` variant).

**Comment by AleXSR700** [comment]
I am not sure if this is possible, but the ble experts here might be able to say:
It seems to me as if the EQ3 makes the device less stable.

I have 8 Mijia temp+hum sensors and 8 EQ3s. My esp32 devices (esp32 & esp32c3) work without crashes when I only use the Mijia devices.
When the TRVPeriod is lowered, it seems to increase the crash frequency a lot.
So with TRVPeriod 300 my esp32c3 devices crash multiple times per day. When I increase to 3600, the devices seem to not crash more than once.

It is still too early since the update to say for sure, but is it possible that somehow the EQ3 driver blocks the wifi-ble module too long or something like that? Layman talking here...

**Comment by btsimonh** [comment]
> the versions I built without EQ3 support or when the driver was broken

was it like this?:
```
#define USE_MI_ESP32 
#define USE_BLE_ESP32 
//#define USE_EQ3_ESP32
```
i.e. using the BLE_ESP32 version of BLE?

There is a big interaction between BLE of any form and wifi.  Basically on ESP32, you CAN'T mix them.  Really for BLE and TAS we should have one device doing BLE, and another doing wifi.

e.g. when I built webcam+ble, and then used the webcam UI, no device would last more than ~30 mins, some crashed in < 1 min.

Reducing TRVPeriod -> more MQTT & more time with active BLE connections -> more BLE + more wifi -> more crashes :(.

Using just MI sensors, it's using very little BLE, and so the risk is reduced (basically just hearing adverts, no active connections).

see also https://github.com/arendst/Tasmota/issues/20970 and other reported BLE issues.

**Comment by AleXSR700** [comment]
Why is an active connection needed for EQ3 but not Mijia? The esp32 devices receive data without active connection. But they need an active connection for the query?
If so, can the duration if this active connection maybe be reduced/optimized?

Again, just asking as a layman.

I have found that the active checking via the TRVPeriod is rarely needed. The TRV will report any change without being queried (and that is received by the tasmota esp32 without active connection). So only an initial query is needed to get the starting value whenever the esp32 device or the Home Automation server are restarted. Apart from that, any change will be actively broadcast by the TRV and received by the esp32 tasmota devices.

**Comment by btsimonh** [comment]
@AleXSR700 - sorry for the delay.  The EQ3 needs to be `read`, which requires a connection, whereas the MI devices broadcast their stats in BLE adverts - so anyone can hear the info without connecting.  The exception to this is some MI devices don't include battery level, but this can be read using a connection.

So far as I remember, 'any change will be actively broadcast by the TRV' is not true.  We will only get updated info from the TRVs when we ask for it.  (i.e. at the TRV interval).

**Comment by AleXSR700** [comment]
> So far as I remember, 'any change will be actively broadcast by the TRV' is not true.  We will only get updated info from the TRVs when we ask for it.  (i.e. at the TRV interval).

Thanks for your response.
Nope, the above is definitely true. I have set the TRVPeriod to 1 hour and I get constant updates when the TRV is running. It sends updates whenever there is a change in temperature (I think also valve). No need to ask for it :)

Just manually change the temperature at the dial or via HA and you will see that it broadcasts once it has received the command (be it via dial or via MQTT).

**Comment by Einstein67** [comment]
I can agree with btsimonh's observations. If TRVperiod is set to 0, no values come from the valves. Regardless of whether I control them via the app or change the temperature on the dial.
I change the value with the status of my heating circuit. 
Heating circuit pumps on --> TRVPeriod 300
Heating circuit pumps off --> TRVPeriod 0
When the circuit is not running, I can only see the current temperature setting, but only the last valve position. But that doesn't interest me at all at this point. An active query using ‘TRV status’ is always possible.

**Comment by AleXSR700** [comment]
> I can agree with btsimonh's observations. If TRVperiod is set to 0, no values come from the valves. Regardless of whether I control them via the app or change the temperature on the dial.

Please set TRVPeriod to something high, like 3600 and then use the dial.
You should see the publish in the console.
I know I do. So either that is new in TRV firmware 1.46 or TRVPeriod 0 disables the TRV all together (have not tested that myself).

**Comment by AleXSR700** [comment]
@btsimonh 
I thought about this a bit more and I was wondering if maybe we are staying connected "needlessly".

For sure the TRV publishes whenever there is a change and tasmota does not need to connect to receive that message. Essentially it behaves like a Mijia thermometer etc. They publish and anyone within reach can listen. Not exactly safe, but what the heck...

So I think right now you are connecting, querying the status and waiting for the response before disconnecting.
I think you could simply send a command to the TRV and then wait for the response *without* being connected.

Any valid command will trigger the publish and any device will see it (without being connected).

That should significantly reduce the duration of the connection to the pure time that is needed for sending the command.

**Comment by AleXSR700** [comment]
> The advertisments from the TRVs (data send periodically and without connection) do not contain any useful data for us.  The only way to get useful data is to connect to each TRV in turn, and make some request (any - since upon any request, the TRV will send a 'notification' containing the latest data).  In order to receive a notification, you must be connected.  

Here I am not sure if this is not a contradiction to your first paragraph.

As you mentioned, when you send a command, the TRV will respond with the data we need. So you do not need to stay connected and wait for a response, you just need to send a command and then you will automatically get a response.
You could of course add a verification, i.e. send the command, remain disconnected, send another command if there is no response within 5 s of the first command. Only connect if this fails 3 times.

Should this not significantly reduce the connection duration and hence the shared wifi/ble blocking?

**Comment by lbs4pich** [comment]
Hello, is there any fix now for Firmware > 1,46

**Comment by AleXSR700** [comment]
> Hello, is there any fix now for Firmware > 1,46

Isn't 1.46 the latest (and probably final) version? Or was there another update?
Tasmota worked after the last comitts from this thread.  But I have not tried the latest release. Has that stopped working again?

**Comment by andrei-marinache** [comment]
I updated one of my EQ3 TRVs to 1.48 about two weeks ago and since then I can't connect to it using any Tasmota version, I just tried today with Tasmota 14.4.1.1 (de3a7f3-bluetooth).

```
14:30:29.984 CMD: trv devlist
14:30:29.986 SRC: WebConsole from 192.168.69.125
14:30:29.988 CMD: Grp 0, Cmd 'TRV', Idx 1, Len 7, Pld -99, Data 'devlist'
14:30:29.991 EQ3: cmd index: 1
14:30:29.995 MQT: stat/tasmota_F9DCC4/EQ3 = {"devices":{"001A2216F340":-80}}
14:30:29.998 MQT: stat/tasmota_F9DCC4/RESULT = {"trv":"Done"}
14:30:36.932 WIF: Checking connection...
14:30:37.134 EQ3: poll overrun, deferred - last loop only got to 1, not 16
14:30:38.179 BLE: failed to connect to device low level rc 0xd
14:30:38.187 BLE: failed to connect to device
14:30:39.136 EQ3: 001A2216F340: trv operation failed - retrying -11
14:30:39.144 MQT: tele/tasmota_F9DCC4/BLE = {"BLEOperation":{"opid":"3601","stat":"-11","state":"FAILCONNECT","MAC":"001A2216F340","u":"128","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","notifychar":"d0e8434d-cd29-0996-af41-6c90f4e0eb2a","write":"03180C1C0E1D25000000000000000000"}}
14:30:42.387 CMD: trv 001A2216F340 state 1
14:30:42.389 SRC: WebConsole from 192.168.69.125
14:30:42.391 CMD: Grp 0, Cmd 'TRV', Idx 1, Len 20, Pld 1, Data '001A2216F340 state 1'
14:30:42.395 EQ3: cmd index: 1
14:30:42.397 EQ3: 001A2216F340: Op queued len now 1
14:30:42.398 EQ3: queued
14:30:42.402 MQT: stat/tasmota_F9DCC4/RESULT = {"trv":"queued"}
14:30:56.941 WIF: Checking connection...
14:31:09.229 BLE: failed to connect to device low level rc 0xd
14:31:09.232 BLE: failed to connect to device
14:31:10.143 EQ3: 001A2216F340: trv operation failed - retrying -11
14:31:10.150 MQT: tele/tasmota_F9DCC4/BLE = {"BLEOperation":{"opid":"3602","stat":"-11","state":"FAILCONNECT","MAC":"001A2216F340","u":"128","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","notifychar":"d0e8434d-cd29-0996-af41-6c90f4e0eb2a","write":"03180C1C0E1D25000000000000000000"}}
14:31:15.134 NTP: Sync time...
14:31:15.217 WIF: DNS resolved 'pool.ntp.org' (44.32.133.2) in 81 ms
14:31:15.294 RTC: UTC 2024-12-28T13:31:16Z, DST 2024-03-31T02:00:00, STD 2024-10-27T03:00:00
14:31:16.000 RTC: Synced by NTP
14:31:16.950 WIF: Checking connection...
14:31:36.953 WIF: Checking connection...
14:31:37.155 EQ3: poll overrun, deferred - last loop only got to 1, not 16
14:31:40.174 BLE: failed to connect to device low level rc 0xd
14:31:40.178 BLE: failed to connect to device
14:31:41.155 EQ3: 001A2216F340: Poll fail not sent because EQ3HideFailedPoll
14:31:41.157 EQ3: 001A2216F340: trv operation failed - no more retries -11
14:31:41.164 MQT: tele/tasmota_F9DCC4/BLE = {"BLEOperation":{"opid":"3603","stat":"-11","state":"FAILCONNECT","MAC":"001A2216F340","u":"128","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","notifychar":"d0e8434d-cd29-0996-af41-6c90f4e0eb2a","write":"03180C1C0E1D25000000000000000000"}}
14:31:41.188 EQ3: 001A2216F340: Op dequeued len now 0
```

**Comment by bademux** [comment]
@andrei-marinache hi, did you manage to make it work?

**Comment by andrei-marinache** [comment]
No, I've installed a bluetooth proxy on an esphome device, I am using it in Homeassistant.

**Comment by crazy-ahmet** [comment]
It seems 1.48 doesn´t work anymore. any solution for a downgrade?
