### ISSUE TITLE
Managed to flash a LSC PIR Sensor with "TYWE3S" but...

### ISSUE THREAD

**Issue by DerpyDoom** [arendst/Tasmota#6763]
Hello.

I managed to flash my PIR sensor from the company LSC by providing external 3.3v to the board. They use the Chip called "TYWE3S", the problem is since the board has an MCU for battery management when I remove my external 3.3v it is not accessible anymore since the second chip only wakes the tywe3s up for a few seconds and then powers it down.

My question is how can I push something to MQTT on startup so I know that some "movement" was detected. I tried [this](https://github.com/arendst/Tasmota/wiki/TYWE3S) page but it seems like the section for modules with MCUs is empty.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
