### ISSUE TITLE
sonoff mini need help 

### ISSUE THREAD

**Issue by Rikzg** [arendst/Tasmota#6769]
Hi guys, 

First of all thanks for this amazing firmware. 

I have tried to upload the firmware 6.6.0 via OTA to a sonoff mini device and I thought that everything was fine. But the device don't want to boot with the new firmware. I tried to use the FTDI mode to bringt the mini back to life but I can't establish a connection to the ship. I saw another bug report on here with the same issue like mine but I don't know how what they mean with `reset 5` 

Can anyone help me out to bring the mini back to life?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
