### ISSUE TITLE
Add hour on counter

### ISSUE THREAD

**Issue by Max123459** [arendst/Tasmota#6770]
Hello,

for some devices (like soundsystem) it would be interesting to see with the added sonoff pow how long they are turned on (since installation, ...). 

So if power consumption is higher than 10 watts the system is running and not in standby and the counter can run.

And than something like:
Hours running: 5300h

**Comment by meingraham** [comment]
I would recommend using a home automation hub for this kind of use case. You have greater ability to implement more complex logic for a state machine and can also track usage at whatever granularity you desire.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
