### ISSUE TITLE
POW R2, send no MQTT message if wattage is zero

### ISSUE THREAD

**Issue by toppe** [arendst/Tasmota#6774]
Hi,

Currently I'm setting up an POW R2 for measure the usage of the wasmachine. Also I'm looking for a way to send a notification when it's finished.

To report the power usage frequently to Domoticz I've changed the  ```TelePeriod``` to ```10``` and the reports are coming in as expected.

As always the is one but... Here it come's: But I cannot find any option to temporarily turn-off the MQTT message's I've the usage is 0 for 2 minutes (as example) so the "last seen" in Domoticz does not keep's updated.

Any one?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
Have you looked in wiki section commands for `PowerDelta` ?
