### ISSUE TITLE
DeepSleepTime doesn't work

### ISSUE THREAD

**Issue by chedxb** [arendst/Tasmota#6786]
Hi there,

I am not sure if this is a bug or a configuration issue.

I have a Sonoff Basic, configured as Generic (18) with 6.7.1 and I am trying to configure DeepSleepTime via Console, however I am getting {"Command":"Unknown"} message. As per the Wiki, it should work  »6.6.0.18

Does it need any other configuration change?

Best,

Savas

**Comment by meingraham** [comment]
@chedxb 

Apologies, this was missing in the documentation of this new feature. To use DeepSleep you have to compile your own firmware and enable `USE_DEEPSLEEP`

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
