### ISSUE TITLE
Rotary encoder and PWM output

### ISSUE THREAD

**Issue by mzhur** [arendst/Tasmota#6791]
Dear All, 
All start to use Tasmota becouse it is preaty product with a lot of incredible facility. But lot of DIY devices in my home use the local connection between sensor and activator connected to the one device. For example rotary encoder connected to 2xGPIO change dimmer (PWM duty cycle on the other GPIO) and in the same time all of features could be controlled from MQTT/Domotics and all sensor changes reported to MQTT/Domotics etc. I try ti find same fuctionality but nothing result. It should be possible over server, but it is not right way, becouse survivability system will go down in this case. I try to add this myself but now project Tasmota is so dificult for my looser programing level :-).
Would it possible to realise in this project?

**Comment by ascillato2** [comment]
Yes,

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
