### ISSUE TITLE
Ability to Incorporate into SmartThings 

### ISSUE THREAD

**Issue by ncsufire** [arendst/Tasmota#6805]
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Have you looked for this feature in other issues and in the wiki?**  Yes

**Is your feature request related to a problem? Please describe.**  No

**Describe the solution you'd like**  
There is a device handler and Smart App that has been created (with a different .bin file) by erocm1231 to bring a flashed Sonoff device into SmartThings.  I would like to see this program be able to work with erocm1231's code.  https://github.com/arendst/Tasmota/issues?utf8=%E2%9C%93&q=

**Describe alternatives you've considered**  
Installing erocm1231's software and using the firmware with the application; it does not incorporate the SI7021 sensor. 

**Additional context**  
Thank you

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Tasmotas main goal is to be used with standard mqtt brokers.
Including support for more probitary solutions will reduce functions available in Tasmota.
A PR is welcome and maybe! is considered to include if code size increase is minimal.
There will be probably no driver programmed from the developer....
Since Tasmota is Open Source feel free to fork and make the adaptions you want.

**Comment by andrethomas** [comment]
The simplest would be to request erocm1231 to include support for the Si7021 sensor in his binary.

**Comment by ncsufire** [comment]
Thanks for your reply.  I have done so but thought with the Hue and the
other options this might be a good enhancement.

**Comment by Jason2866** [comment]
Tasmota already has Alexa Hue support

**Comment by ncsufire** [comment]
Correct.  My hope was for those who wanted another option.  Thank you for
the consideration.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
