### ISSUE TITLE
Latest firmware with 8 rules.

### ISSUE THREAD

**Issue by buldoog** [arendst/Tasmota#6809]
Could you compile your latest software with 8 rules? I try and try, but my Sonoff Bridge doesn't work perfectly. He doesn't remember the settings or resets to the default settings. 
I need 8 rules to translate 30 RF codes into the mqtt commands of my curtains.
Sincerely
Robert

**Comment by andrethomas** [comment]
You might want to take a look at scripting as an alternative for more complex local processing - See the wiki here https://github.com/arendst/Tasmota/wiki/Scripting-Language

**Comment by buldoog** [comment]
Sounds good, I have to try.
I think it will be able to solve the problem.
Thank you.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
