### ISSUE TITLE
Shutter Input range rendering with black theme

### ISSUE THREAD

**Issue by localhost61** [arendst/Tasmota#6814]
> **GUIDE**
>
> This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
>
> Please DO NOT OPEN AN ISSUE:
>  - If your Tasmota version is not the latest from the development branch, please update your device before submitting your issue. Your problem might already be solved. The latest precompiled binaries of Tasmota can be downloaded from http://thehackbox.org/tasmota/
>  - If you have a issue when flashing was done via Tuya Convert
>  - If your issue is a flashing issue, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
>  - If your issue is compilation problem, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
>  - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue
>  - If your issue is a Wi-Fi problem or MQTT problem, please try the steps provided in the [FAQ](https://github.com/arendst/Tasmota/wiki/FAQ) and troubleshooting wiki articles
>
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

### BUG DESCRIPTION
<img src="https://user-images.githubusercontent.com/33861984/68070443-9801de80-fd6e-11e9-808b-4b6ac251af2a.png" width="300">
<img src="https://user-images.githubusercontent.com/33861984/68070588-d7c9c580-fd70-11e9-8953-da31611b041c.png" width="300">

As you can see on the first screenshot, the shutter's slider is rather ugly in black theme, compared to white's one. The misalignment is more obvious and the tracker background is not transparent. This apply to Firefox for Windows an Android (I don't know for other browsers, I don't use them). I couldn't find a solution by myself despite seeking the web, it's above my skills. 

- This behavior is not restricted to latest version, sadly it's "by design".
- The black theme is the one found on the [wiki page](https://github.com/arendst/Tasmota/wiki/WebUI#themes)
- The module is brand new and was fully erased before flashing, no parasitic settings inside.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: ``Backlog Template; Module; GPIO``:
  ```
  Configuration output here:


  ```
- [ ] If using rules, provide the output of this command: ``Backlog Rule1; Rule2; Rule3``:
  ```
  Rules output here:


  ```
- [ ] Provide the output of this command: ``Status 0``:
  ```
  STATUS 0 output here:


  ```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ ``weblog 4`` _for more debug information)_
  ```
  Console output here:


  ```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
On windows with firefox 68.0.1 it doesn't look that bad:

![image](https://user-images.githubusercontent.com/11044339/68071947-3c405100-fd80-11e9-9989-55f07a68b8f5.png)

**Comment by arendst** [comment]
I cannot reproduce. The lay-out is defined by both the tasmota css code AND your browser's HTML5 slider implementation.

My Androids screenshot looks different from my firefox screenshot as the browsers tend to implement HTML sliders differently byt both are bearable I think.

**Comment by arendst** [comment]
Considering the lack of ON/OFF status too I suspect you changed some importent GUI css parameters leading to your experience.

Cannot help you here.

**Comment by localhost61** [comment]
Thanks Theo, glad to see it's only on my side ;-)
You make me remind I activated `USE_JAVASCRIPT_ES6` and that's certainly the reason why.
This is the source code it produces in Firefox EME 64.0:
```
<!DOCTYPE html><html lang="en" class=""><head><meta charset='utf-8'><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"/><title>Tasmota - Main Menu</title><script>var x=null,lt,to,tp,pc='';eb=s=>document.getElementById(s);qs=s=>document.querySelector(s);sp=i=>eb(i).type=(eb(i).type==='text'?'password':'text');wl=f=>window.addEventListener('load',f);function la(p){var a='';if(la.arguments.length==1){a=p;clearTimeout(lt);}if(x!=null){x.abort();}x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState==4&&x.status==200){var s=x.responseText.replace(/{t}/g,"<table style='width:100%'>").replace(/{s}/g,"<tr><th>").replace(/{m}/g,"</th><td>").replace(/{e}/g,"</td></tr>").replace(/{c}/g,"%'><div style='text-align:center;font-weight:");eb('l1').innerHTML=s;}};x.open('GET','.?m=1'+a,true);x.send();lt=setTimeout(la,2345);}lb=(v,p)=>la(`&${v}=${p}`);lc=(v,i,p)=>la(`&${v}${i}=${p}`);wl(la);function jd(){var t=0,i=document.querySelectorAll('input,button,textarea,select');while(i.length>=t){if(i[t]){i[t]['name']=(i[t].hasAttribute('id')&&(!i[t].hasAttribute('name')))?i[t]['id']:i[t]['name'];}t++;}}wl(jd);</script><style>div,fieldset,input,select{padding:5px;font-size:1em;}fieldset{background:#4f4f4f;}p{margin:0.5em 0;}input{width:100%;box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;background:#dddddd;color:#000000;}input[type=checkbox],input[type=radio]{width:1em;margin-right:6px;vertical-align:-1px;}select{width:100%;background:#dddddd;color:#000000;}textarea{resize:none;width:98%;height:318px;padding:5px;overflow:auto;background:#222222;color:#008000;}body{text-align:center;font-family:verdana,sans-serif;background:#181818;}td{padding:0px;}button{border:0;border-radius:0.3rem;background:#1fa3ec;color:#ffffff;line-height:2.4rem;font-size:1.2rem;width:100%;-webkit-transition-duration:0.4s;transition-duration:0.4s;cursor:pointer;}button:hover{background:#0e70a4;}.bred{background:#d43535;}.bred:hover{background:#931f1f;}.bgrn{background:#47c266;}.bgrn:hover{background:#5aaf6f;}a{text-decoration:none;}.p{float:left;text-align:left;}.q{float:right;text-align:right;}</style></head><body><div style='text-align:left;display:inline-block;color:#eeeeee;min-width:340px;'><div style='text-align:center;color:#eeeeee;'><noscript>To use Tasmota, please enable JavaScript<br></noscript><h3>Sonoff Dual R2 Module</h3><h2>Tasmota</h2></div><div id='l1' name='l1'></div><div><span class='p'>Close</span><span class='q'>Open</span></div><div><input type='range' min='0' max='100' value='0' onchange='lc("u", 1, value)'></div><table style='width:100%'><tr><td style='width:50%'><button onclick='la("&o=1");'>Toggle 1</button></td><td style='width:50%'><button onclick='la("&o=2");'>Toggle 2</button></td></tr></table><div></div><p><form action='cn' method='get'><button>Configuration</button></form></p><p><form action='in' method='get'><button>Information</button></form></p><p><form action='up' method='get'><button>Firmware Upgrade</button></form></p><p><form action='cs' method='get'><button>Console</button></form></p><p><form action='.' method='get' onsubmit='return confirm("Confirm Restart");'><button name='rst' class='button bred'>Restart</button></form></p><div style='text-align:right;font-size:11px;'><hr/><a href='https://bit.ly/tasmota' target='_blank' style='color:#aaa;'>Tasmota 7.0.0.1 by Theo Arends</a></div></div></body></html>
```

**Comment by localhost61** [comment]
The lack of ON/OFF is due to the fact the target was a Wemos module with no relay and not completely setup. But the behavior was the same on the Dual R2 running in production as shutters with an older version.

**Comment by arendst** [comment]
Using the source code you provided before on FireFox the output looks fine with me:

![image](https://user-images.githubusercontent.com/11044339/68073906-47ea4280-fd95-11e9-8a14-043b77f7028c.png)

I'm also using ES6enabled and have no problem what so ever.

There must be more going on with your browser settings and or cache.

**Comment by localhost61** [comment]
OK, then I close the issue and tell later my findings.
Thanks again.

**Comment by localhost61** [comment]
I'm reluctant to screw up my laptop setup to troubleshoot my issue. But I've upgraded  my Android mobile to 68.2 with no enhancement. Despite this I've found a laptop were the WebUI is not corrupted, I will investigate on this basis.

**Comment by localhost61** [comment]
As is doesn't seem to be related to the Firefox version, I'm now, investigating on my laptop with a new empty profile with no plugin, no `about:config` hack, no theme, no nothing.

@arendst Please, when opening the debugger with Ctrl+Shift+S  on the Tasmota device WebUI, do you have `resource://gre` as an added Source of code for javascript??? My browser don't but the working one does.

Now, in the inspector, if i select the input[range] element, looking at the style there is an active background attribut associated to inputs which is #dddddd. If I uncheck it I get the proper slider aspect. On the working browser it changes nothing :-?

<img src=https://user-images.githubusercontent.com/33861984/68219741-d0135680-ffe6-11e9-8884-4852a2b920cf.png width=80%>
<img src=https://user-images.githubusercontent.com/33861984/68220601-52e8e100-ffe8-11e9-9ce3-f89c6badeb60.png width=80%>

**Comment by localhost61** [comment]
From the source code of this page, removing the `background` attribute from the `input` style works too.
![2019-11-05 16_36_19-_D__RnD_Arduino_Sonoff_doc_Tasmota htm - Notepad++](https://user-images.githubusercontent.com/33861984/68222150-d73c6380-ffea-11e9-854a-b0d5b9e5dddb.png)

**Comment by localhost61** [comment]
Then I compiled a fork were I modified `HTTP_HEAD_STYLE1[]` and `WSContentSendStyle_P()` to remove this field in webserver.ino and it solved my issue with no apparent side effect. :-)

**Comment by localhost61** [comment]
I'm still on this...
Making some tests on mobiles, I found that the light [Mozilla Firefox Focus 8](https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=fr) don't render the slider properly on 3 different Android mobiles I could test (API22-26) when, on the same mobiles, [Dolfin 2019](https://play.google.com/store/search?q=dolfin&c=apps&hl=fr) handle them nicely.

**Comment by localhost61** [comment]
@arendst are you using Firefox too on Android 9? Because on my Android 8 mobile and latest Firefox 68.3.0 the `input range` slider is still bugged. I'm on my way to submit an issue on bugzilla.

**Comment by arendst** [comment]
I'm using chrome on android and have no issues with the slider.

**Comment by localhost61** [comment]
Then try Firefox on Android 9 and I think you will ;-)

**Comment by arendst** [comment]
Just installed firefox and indeed, the slider should have been transparent...

**Comment by localhost61** [comment]
Thanks for checking
