### ISSUE TITLE
Serial transparent bridge

### ISSUE THREAD

**Issue by Matze2018** [arendst/Tasmota#6828]
Is a transparent serial bridge with tasmota possible?
A Transparent serial bridge like 192.168.1.145:23 that can be used as an complete serial port over wifi?
At the moment i can only send some parameters over a terminal program to the tasmota console?

**Comment by Jason2866** [comment]
Serial bridge does not work with ports. It uses mqtt for the serialbridge function

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Matze2018** [comment]
Sorry i can´t find a discription how to use mqtt for the serialbridge function.
What i need to set on the mqtt broker?

**Comment by Jason2866** [comment]
Nothing :-) you receive the serial received stuff as mqtt message
To send just send the payload with serialsend command over mqtt.
See wiki for usage

**Comment by Matze2018** [comment]
I got it! Tank you!!!
My Serial device sends only data if i send a SerialSend X21 to it.
Can i do this on startup once?

**Comment by Jason2866** [comment]
Something like that
`Rule1 on system#boot do backlog baudrate 9600; serialsend X21 endon on`

**Comment by Matze2018** [comment]
Thank you ... but it is not working :-(
If i put this in the console is it saved automaticly?
Where can i see the saved rules?

**Comment by Jason2866** [comment]
You have to enable with `rule1 1` Please read wiki section rules

**Comment by Matze2018** [comment]
Now it works!!!
Thank You for your Help!!!
