### ISSUE TITLE
Continuous Exception errors running Tasmota

### ISSUE THREAD

**Issue by GaryMilne** [arendst/Tasmota#6836]
I have successfully flashed my 8266 (on a TYWE3S) with the current release version of Tasmota and it generates an exception error shown below and does a continuous error loop about every 0.5 seconds.
![Exception](https://user-images.githubusercontent.com/16356949/68100713-0dfd6700-fe8f-11e9-84b7-9389aea10d55.JPG)

I also tried using version 5.14.0 and got the same result. Any suggestions on what the issue could be would be appreciated?

**Comment by blakadder** [comment]
These errors might be caused by a bad flash or its power supply related. You provided almost no information on the type of device

Did you do an erase flash before doing a serial flash?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
