### ISSUE TITLE
Highlight the major positions on the clock

### ISSUE THREAD

**Issue by robin13** [arendst/Tasmota#6848]
**Is your feature request related to a problem? Please describe.**  

Making a minimalist clock with only WS2812 LEDs but no external markings, it can be difficult to identify where 12, 3, 6, 9 are to get a reference for what the actual time is.

Image of my clock for illustration:
![IMG_20191106_104131](https://user-images.githubusercontent.com/174291/68286954-37caaf80-0082-11ea-9de5-58f73e84b162.jpg)

**Describe the solution you'd like**  
The ability to highlight (defining colour, brightness, and the interval (each hour, only the quarters, or only 12) the hour markers of the clock

**Describe alternatives you've considered**  
Painting numbers onto the clock... but this would take away from the minimalist design

**Comment by arendst** [comment]
Try command ``color6 808000``

**Comment by robin13** [comment]
Damn - I missed that in the documentation!  Thank you! :heart:
