### ISSUE TITLE
FrequencySet unknown Command Tasmota 6.6.0

### ISSUE THREAD

**Issue by kinghill44** [arendst/Tasmota#6849]
Hello

I get the Message unknown command on sonoff POW R2 with tasmota 6.6.0.
Is that a Bug, or did i something wrong?

I have tried
FrequencySet 0
FrequencySet 50.0
FrequencySet 50.000

Same @ all comands.

**Comment by Jason2866** [comment]
Sonoff Pow and Pow R2 has no frequency measuring capable chipset.
So command is not supported

**Comment by kinghill44** [comment]
Thank you!
