### ISSUE TITLE
Auto change Visual on 6.7.1 after adding fifth relay

### ISSUE THREAD

**Issue by sommo** [arendst/Tasmota#6851]
Hi,
After adding a fifth relay on configuration board (generic 18), the web page display the the status of toggle button from on/off to 0/1 automatically.
Is it a regular behaviour?

**Comment by arendst** [comment]
Yes. As designed. The screen would be too wide for phone.

**Comment by sommo** [comment]
It could be avoided by some set command?
Anyway thank you

**Comment by sommo** [comment]
A better question, via mqtt does it still reply with its state on/off or it also change mqtt replay query? Cause I have a plugin for check it state... just for asking I could check it by querying it my self

**Comment by ascillato2** [comment]
Mqtt does not change.
