### ISSUE TITLE
Tasmota Emulator Not Work "BlitzWolf SHP (45)"

### ISSUE THREAD

**Issue by donotoverdriveit** [arendst/Tasmota#6864]
Hi!

I use Tasmota 6.7.1 on a "BlitzWolf SHP (45)" Unfortunately, the emulator "Hue Bridge" and "Belkin WeMo" does not work. Alexa just does not recognize new devices.

It also does not work with an older Tasmota version.

Ask for help, thanks!

![grafik](https://user-images.githubusercontent.com/52773550/68417625-098ac400-0197-11ea-9e2b-a21a835f929b.png)

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
