### ISSUE TITLE
SwitchRetain and auto discovery

### ISSUE THREAD

**Issue by gabter1** [arendst/Tasmota#6869]
It seems that when SetOption19 1, auto discovery is set, the SwitchRetain 1 command does not have any effect. In the console, when the switches get published, (retained) is not displayed, and in Home Assistant, the status of the switches is not retained after a HA reboot. Relay status is working fine and the console log shows that it is retained.
Any ideas?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
