### ISSUE TITLE
Just an improvement request for your good documentation

### ISSUE THREAD

**Issue by m4rten** [arendst/Tasmota#6879]
Hi,

just got an suggestion to improve your documentation.
I wasted some time to find the correct format to use the http request method for sending 433MHz Codes... maybe an  additional example will help like an explanation that special characters need a % sign before you type the hexcode from the ascii table.

http://<ip>/cm?cmnd=rfcode%20%23<insert code here>
%20 = space
%23 = #

Kind regards,
Marten

below the part of your documentation where those examples could be inserted.

Sending commands with web requests

Commands can be executed via web (HTTP) requests, for example:

http://<ip>/cm?cmnd=Power%20TOGGLE
http://<ip>/cm?cmnd=Power%20On
http://<ip>/cm?cmnd=Power%20off
http://<ip>/cm?user=admin&password=joker&cmnd=Power%20Toggle

Any spaces or special characters (e.g., ;) must be replaced with their respective ASCII hex codes.

**Comment by meingraham** [comment]
OK, done. Please review and close this issue.

FYI - the wiki is open for user collaboration. You may edit it directly in the future.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
