### ISSUE TITLE
Configure Time under Configuration

### ISSUE THREAD

**Issue by une18** [arendst/Tasmota#6880]
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Have you looked for this feature in other issues and in the wiki?** 
Time 14:24:17
Timezone +2
Worked these commands, but could not find in Wiki.
Would like to have it as other Configuration buttons instead of commands.
https://github.com/arendst/Tasmota/wiki/Commands#how-to-use-commands
![image](https://user-images.githubusercontent.com/36228588/68528550-027dc600-02fd-11ea-80e5-64a38d9f30d4.png)

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
It is difficult for many users to use commands. Would like to use them as less as possible

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Have a button and window for Time and Timezone setting
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
The commands are documented in the wiki:
https://github.com/arendst/Tasmota/wiki/Commands#timezone
https://github.com/arendst/Tasmota/wiki/Commands#time

Adding UI dialogs consumes program memory that may be better used for new features or enhancements.

**Comment by Jason2866** [comment]
The way you describe is loosing time after a power loss.
It is for users where no wifi network is available. 
If your device is connected to wifi, it will get the time from the NTP server.

What you suggest is not needed

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
