### ISSUE TITLE
Upgrade Decode Tools to Python 3

### ISSUE THREAD

**Issue by meingraham** [arendst/Tasmota#6882]
@curzon01 Norbert,

Installation of the decode tools Python dependencies throws warnings regarding deprecation of Python 2.7 commencing in 2020. This occurs when the tool encounters errors and executes some statements which are not proper Python3 syntax. Otherwise it seems to run under Python3 OK. Nevertheless, this should be confirmed.

This Python issue seems also to be at the heart of being able to get PyCurl installed properly under WIndows 10. @Jason2866 pointed me toward a workaround (hack). The information on installing the dependencies has been added by @blakadder to the decode tools README.

Mike

P.S. Apologies for making a request rather than performing the task... but my Python skills are bad at best and knowing the necessary Python2 vs. Python3 syntax changes is a bridge too far :wink:

**Comment by blakadder** [comment]
new docs explaining the Win 10 workaround are PRd #6884

**Comment by curzon01** [comment]
Will have a look but currently I'm busy and also offline (not really but development related) so it have to wait 2+ weeks from my side.

**Comment by ascillato2** [comment]
Closing this request has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
