### ISSUE TITLE
PWM on more than one channel

### ISSUE THREAD

**Issue by Emmpunkt** [arendst/Tasmota#6887]
I´m trying to setup a Wemos Mini with two PWM-Outputs. Two different Lamps.
The problem is, that Lamp No2 only works if No1 is switched on.
If i switch No1 off, No2 is also switched off. (In the GUI still on)

My setup:
Wemos D1 Mini
Tasmota 7.0.0.4
Type: Generic (18)
D2 GPIO4 PWM2 (38)
D1 GPIO5 PWM1 (37)
SetOption68 1

Did i something wrong or missunderstood this function?
Regards M.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by s-hadinger** [comment]
This is a confirmed bug that appeared between 6.7.1 and 7.0.2. We are investigating.
