### ISSUE TITLE
Time setting

### ISSUE THREAD

**Issue by Performance20** [arendst/Tasmota#6899]
I use the standard config, only select a language. After the modul come back I have alwayis as time: RSL: tele/tasmota/STATE = {"Time":"1970-01-01T00:09:57","Uptime":"0T00:09:59","UptimeSec":599,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":29,"...

I flashed the standard software, directly load from the github, only select a coutry and keep all other option like default. Nntpserver are default, but nothing
happen to update the date & time. Always showing year 1970....
Same after resett flash to defauslts.

Waht is wrong and how can I get the right time and date. I tried as well the time command but nothing happen. Always the same date/time.

Regards Helge

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
