### ISSUE TITLE
Lose settings after change from sonoff.h

### ISSUE THREAD

**Issue by Goodlife1987** [arendst/Tasmota#6906]
Hello, 
there is a problem after changing parameters in sonoff.h
When i change and flash the new built (6.7.1)firmware.bin it cant save anything.
You can see it when you save timers and reconnect the sonoff from the energie. It will lose every settings from timer.

for example

const uint8_t MAX_TIMERS = 16;
into
const uint8_t MAX_TIMERS = 17;

or

const uint8_t MAX_RULE_SETS = 3;
into
const uint8_t MAX_RULE_SETS = 4;

Best regards

**Comment by ascillato2** [comment]
If you change those defines, the memory settings map got scrambled and don't fit into memory. See comments in the code. 

Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
