### ISSUE TITLE
Blown fuse about setting a profile (Digoo DG-SP202)

### ISSUE THREAD

**Issue by Stooovie** [arendst/Tasmota#6911]
Hello, after setting the correct profile (Digoo DG-SP202) and clicking Save, the device rebooted and right after hearing the two relays, it blew the fuse in the fuse box and apparently also in itself. The device is now dead. 

Is there anything to learn or did I just get a lemon? Thanks.

**Comment by ascillato2** [comment]
* Have you tested your device before flashing Tasmota?
* Have you connect anything to the output of the plug?

If no, then your device was faulty and you should ask for a refund.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
