### ISSUE TITLE
HC-SR04 Multiple Sensors per ESP8266

### ISSUE THREAD

**Issue by itbeyond** [arendst/Tasmota#6912]
It would be really nice to be able to support two or more HC-SR04 units per ESP8266. 

I understand we would need to assign a second set of Echo and Trig pins potentially so unsure how the code would be able to identify which pair of gpios go with each of the SR04's but I have a requirement for my garage door controller which needs a second distance sensor to measure the parking spot for the vehicle (ie: car in <100cm or out >100cm).

**Comment by Jason2866** [comment]
To solve the job you want you can use a ToF sensor VL53L0x for the second.
Support for two or more HC-SR04 needs to bed done by someone
A PR is welcome, keep the code size in mind increase has to be small.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
