### ISSUE TITLE
Is Armtronix Single Wifi Dimmer (v0.3) w/o Atmega working with Tasmota?

### ISSUE THREAD

**Issue by thomas-lentz** [arendst/Tasmota#6918]
### ISSUE DESCRIPTION - TROUBLESHOOTING
I bought an Armtronix Single Version without Atmega Chip, because according to their description this is only needed for future Alexa support. The idea was to use Tasmota on the ESP to have the Alexa support. Unfortunately the TASMOTA WIKI article [Armtronix Dimmers](https://github.com/arendst/Tasmota/wiki/Armtronix-Dimmers) states:

> The dimmers contain an ESP8266 for the wifi connection and an Atmega328 which monitors the mains frequency and dimm the lights using a triac and phase controlled dimming.

According to the TASMOTA WIKI description my board would not be able to dim (because of the Atmega missing), but it works fine with its native (very basic) Firmware.

### REQUESTED INFORMATION
Can I flash Tasmota on my Armtronix Single Wifi Dimmer (v0.3) without having an Atmega on board and it would still work? I don't want to "brick" the device.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in issues (https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Armtronix Single Wifi Dimmer (v0.3) 
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
You will not brick the device. 

First of all, backup the actual firmware for safe testing.

Then flash Tasmota.

If your device don't use any external MCU, so you should use the GENERIC module in config to set a new template.

If you need help on that, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
