### ISSUE TITLE
Description field in "Other parameters" config

### ISSUE THREAD

**Issue by moelski** [arendst/Tasmota#6929]
Hi, 
I use 12 Smart Socket within my house. If you connect to a device you only have the IP address to guess what the device is used for. 
So what do you think about adding a simple description field to tasmota? Just an input field in the "Other parameters" configuration where you can place a small device description like "Washing machine". 
This information could be part of the info topic in MQTT and displayed on the index page. 
Could be very handy in most cases. 

Example for MQTT Message: 
```
tele/sonoff/INFO1 
{"Module":"Gosund SP1  v23","Version":"6.7.1(sonoff)","FallbackTopic":"cmnd/IOT-Steckdose-01_fb/","GroupTopic":"sonoffs"**,"Description":"Washing machine"**}
```

**Comment by blakadder** [comment]
or you can use:
- topic
- friendly name
- custom template name which becomes module name when applied

**Comment by moelski** [comment]
That's possible. 
But a description field would be easier to handle. 
And you can change the description without creating new topic in MQTT.

**Comment by Jason2866** [comment]
This additional info would cost extra flash space.

**Comment by arendst** [comment]
As suggested before use the Friendly name field for your request.

**Comment by moelski** [comment]
Thx for that. 
But Friendly name is not part of the MQTT massage, is'n it?

**Comment by arendst** [comment]
It's part of ``status``

**Comment by moelski** [comment]
Ok. But STATUS will not be send to the MQTT server automatically?

**Comment by Jason2866** [comment]
A small rule will do the job

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
