### ISSUE TITLE
Sonoff restart turns off devices

### ISSUE THREAD

**Issue by Crashoverride87** [arendst/Tasmota#6951]
Hi,

i had the problem, that my sonoff basics lose the wifi connection, so I use this for all sonoff basics via mqtt:
SONOFFIP/cm?user=USERNAME&password=PASSWORD&cmnd=restart%201

The device after the sonoff was farther ON. Since the last update the devices turn off, and then on. This is not good, because I restarted the sonoffs every 3 hours. I have now downgraded to 6.6.0 and thats works fine.

**Comment by ascillato2** [comment]
That behaviour is not normal and I could not reproduce it.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
