### ISSUE TITLE
No Emulation Option

### ISSUE THREAD

**Issue by TobiasF1986** [arendst/Tasmota#6959]
Hello,
I flashed my Tuya plug with Tasmota. I Would like to use it with Alexa, but I can not find the option to activate the Emulation.
![1](https://user-images.githubusercontent.com/45529372/69069358-9ef34700-0a26-11ea-8dc4-f49f4bfad8b8.png)

**Comment by s-hadinger** [comment]
Tuya-convert contains a minimal version Tasmota-wifiman required to configure wifi. You need then to OTA upgrade to Tasmota standard version. 

Tuya-convert needs that the firmware is below 512Kb which disqualifies standard Tasmota version.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by mararn1618** [comment]
Hm, no matter which bin I upload after initially flashing my SB50 lightbulb, I cannot get the emulation options to show.

**Comment by ascillato** [comment]
Please, try the following:

First update to http://thehackbox.org/tasmota/tasmota-minimal.bin

And then, after it restarts, update to http://thehackbox.org/tasmota/tasmota.bin

**Comment by mararn1618** [comment]
Hi @ascillato, that has worked thanks! (although I have used the official release location https://github.com/arendst/Tasmota/releases)

I assume when it didn't work for me, it had never actually worked to flash my bulb to tasmota.bin (7.1.1), but it stayed at a build that was provided with tuya-convert.

Some (obvious) hints for the other people with the same problem:
 - When flashing, always check the version string in the web ui of your device. Did it really upgrade?
 - As @ascillato suggested, always upgrade to tasmota-minimal.bin if you already have a larger version installed (I assume some devices could have memory issues upgrading from large->large?)
 - When flashing, try both the (1) OTA upgrade via web ui and (2) upload bin file via web ui. The first one didn't work for my device.

Thanks once again!

**Comment by ascillato** [comment]
Hi, glad to know that now it is working for you. Seems that your device was never updating before.

FYI, thehackbox.org/tasmota are also the official release. See explanation in Tasmota's readme. The difference is that I linked to latest version from the development branch that have latests fixes.
