### ISSUE TITLE
Sonoff reset on power cut

### ISSUE THREAD

**Issue by vjversatile** [arendst/Tasmota#6966]
So, i recently upgraded to 6.7.1 via OTA update. dont remember what version i was on before this and never had this problem for over a year before this on the older version.

Today, i came home and saw that all of my Sonoff's were reset and with default config. Asked the folks at home and they mentioned there was some continuous power cut in the afternoon.

To reproduce the scenario, i reconfigured the Sonoff's to the desired state and then switched the power on and off. It still worked fine. A bit later, i did a continuous power ON/Off a few times and tadaaa... the sonoff lost config again.

What could be the problem?

**Comment by ascillato** [comment]
Hi,

That is a feature. See https://github.com/arendst/Tasmota/wiki/Fast-power-cycle-device-recovery

**Fast power cycle device recovery**: See command **SetOption65** (you can disable it if you want)

and also,

**Boot Loop Protection**: See command **SetOption34** (you can disable it if you want)

Commands in the wiki: https://github.com/arendst/Tasmota/wiki/Commands

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
