### ISSUE TITLE
Tuya basic push button not working

### ISSUE THREAD

**Issue by abhitheawesomecoder** [arendst/Tasmota#6976]
I have a tuya devices similar to sonoff basic. I flashed it with tasmota. Now, every thing is working except the black push button. May be the pcb is using other gpio for black push button. I tried different gpio pin numbers with no luck. Please check the device circuit in pic. attached. When I push button nothing happens in tasmota console. May be I am not able to find right gpio pin

![IMG_20191120_151531](https://user-images.githubusercontent.com/3944526/69230965-4949a680-0bae-11ea-97fe-cc554a9d0ffa.jpg)
![IMG_20191120_151544](https://user-images.githubusercontent.com/3944526/69231081-772eeb00-0bae-11ea-9f6c-ee3b90f95105.jpg)

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
