### ISSUE TITLE
change status ds18b20

### ISSUE THREAD

**Issue by michau86** [arendst/Tasmota#6981]
How to change the state of the relay on / off when the temperature (ds18b20 sensor) is above 35 degrees? what command

**Comment by Tommy-LSA** [comment]
-> rules

Check Wiki, there is an example 

Von meinem iPhone gesendet

**Comment by michau86** [comment]
I put "rule1 on DS18B20_1#temperature>35 do power1 1 endon" but nothing changed

**Comment by Tommy-LSA** [comment]
Type

Rule1

And post output here

Von meinem iPhone gesendet

**Comment by michau86** [comment]
04:56:02 CMD: rule1
04:56:02 RSL: stat/sonoff/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":466,"Rules":"on DS18B20_1#temperature>30 do power7 1 endon"}

**Comment by michau86** [comment]
04:58:07 CMD: rule1
04:58:07 RSL: stat/sonoff/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":466,"Rules":"on DS18B20_1#temperature>35 do power1 1 endon"}

**Comment by Tommy-LSA** [comment]
Your Sensor shows values in the log? Please post the logoutput where the sensor goes through the 35 

Von meinem iPhone gesendet

**Comment by michau86** [comment]
what command can I see the logs for?

**Comment by Tommy-LSA** [comment]
If your sensor properly works you‘ll see cyclic log entries for the sensor. Each time you see a log entry with „Sensor“ the rule get fired. 

Von meinem iPhone gesendet

**Comment by michau86** [comment]
05:30:17 RSL: tele/sonoff/STATE = {"Time":"2019-11-21T05:30:17","Uptime":"0T00:29:59","UptimeSec":1799,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"airlive_1","BSSId":"84:16:F9:9B:E9:CC","Channel":1,"RSSI":58,"LinkCount":1,"Downtime":"0T00:00:05"}}
05:30:17 RSL: tele/sonoff/SENSOR = {"Time":"2019-11-21T05:30:17","DS18B20":{"Temperature":34.5},"TempUnit":"C"}

**Comment by michau86** [comment]
i  changed temperature to 30 but i don't see switching when temp is above

**Comment by Tommy-LSA** [comment]
Change your rule from

on DS18B20_1#temperature>35 do power1 1 endon

into

on DS18B20#temperature>35 do power1 1 endon

You only have one sensor and you have to use the same sensor name as
shown in the log


Am 21.11.2019 um 05:35 schrieb michau86:

**Comment by Tommy-LSA** [comment]
I use a device with 2 sensors. Then tasmota shows the sensors
enumerated, but not if you have only one sensor.

05:44:03 MQT: tele/stadtweg/eg/heizung/SENSOR =
{"Time":"2019-11-21T05:44:03","DS18B20-1":{"Id":"04167492A1FF","Temperature":53.9},"DS18B20-2":{"Id":"0516735E7CFF","Temperature":35.6},"TempUnit":"C"}

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
