### ISSUE TITLE
TuyaMCU BecaThermostat Wiki

### ISSUE THREAD

**Issue by emanuelecavestri** [arendst/Tasmota#6991]
Hi,
i'm working to implement tasmota with a Tuya BecaThermostat.

in the attachment the wiki with increased instruction
[becaInstruction.txt](https://github.com/arendst/Tasmota/files/3877191/becaInstruction.txt)

Yesterday i'm directly edited the wiki but today i can't. You can merge wiki with the info in my file?
Thx

**Comment by blakadder** [comment]
Hold on for a few days and everything will be revealed ;)
