### ISSUE TITLE
why cannot connect to mqtt host ?

### ISSUE THREAD

**Issue by dony71** [arendst/Tasmota#7000]
I have sonoff tasmota on IP 192.168.1.100 behind the router 
Router connected to subnet 10.2.x.x, has IP 10.2.1.200
I'm also running mosquitto server on IP 10.2.1.100 with port 1883 TCP
I have done port forwarding 1883 on the router 
But why sonoff cannot connect to host (mosquitto server)?
What I'm missing? please help .....

**Comment by dony71** [comment]
Btw, 
I have laptop also behind the router on IP 192.168.1.10 and I can ping mosquitto server IP 10.2.1.100

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
