### ISSUE TITLE
TM1638 leds & 7 Segment Display

### ISSUE THREAD

**Issue by andreas6** [arendst/Tasmota#7001]
I test TM1638 board with Tasmota.

So far I have input for all buttons, but I can't control the LEDs or send a message to 7 segment display from Tasmota console. 
Also didn't find anything about it on WiKi on Commands etc.

I want to display messages to TM1638 7 segment display.

Is it full implemented?

**Comment by Jason2866** [comment]
It is not implemented. The Tasmota TM1638 driver does only support the switches.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
