### ISSUE TITLE
Add support for a different Parity to support more Modbus Smartmeter

### ISSUE THREAD

**Issue by kugelkopf123** [arendst/Tasmota#7004]
It would be nice to use the SBC ALE3 Modbus SmartMeter. But its using another parity than the current SML driver accept. As far as i can see, this is the Problem.
I've tried 8E1 on my Raspberrypi with this SBC Smart Meter and it worked. 
It would be nice to choose another parity (more than just 7E1 and 8N1) within this Driver to support more Meter. Just like you can switch the Baudrate.

Link Modbus SmartMeter from SBC: 
[SBC ALE3 Modbus](https://www.sbc-support.com/uploads/tx_srcproducts/26-527_ENG_DS_EnergyMeter-ALE3-with-Modbus_01.pdf)

Library I tried on my Raspberry Pi:
[https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/sbc.go](https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/sbc.go)

Thanks!

**Comment by meingraham** [comment]
@gemu2015 ⬆️

**Comment by s-hadinger** [comment]
TasmotaSerial currently does not support parity at all. It only supports 8N1 or 8N2.

7E1 is emulated by the SML driver by calculating the 8th bit, but TasmotaSerial just passes the 8 bits. This would require TasmotaSerial to send an additional parity bit, but we are already very short in IRAM.

@arendst and @gemu2015 any idea?

**Comment by arendst** [comment]
It's also a matter of timing. Adding a test for parity screws current timing unless for every parity a seperate handler is used. This increases code size considerably.

Alternative is using hardware serial only. That could work with less code.

In any case it's back to sqair one and test and measure.

**Comment by arendst** [comment]
We might reconsider TasmotaSerial based on https://github.com/plerup/espsoftwareserial again

**Comment by s-hadinger** [comment]
I was thinking of only sending parity but not testing parity on receive. Selecting 8N2 will silently ignore the received parity.

Send might be easier to change without IRAM impact. What is the baud rate for Modbus?

**Comment by kugelkopf123** [comment]
As far as I know, there is no special baudrate for Modbus. It could be from 4800 to 19200. Typically its 9600baud.

**Comment by gemu2015** [comment]
i implemented 8E1 for my sml driver (on my fork) for hardware serial.
i am waiting for confirmation by @kugelkopf123 to to a pr.

**Comment by s-hadinger** [comment]
9600 baud is slow enough and shouldn't require that the code sending serial is in IRAM. Hardware serial is still the preferred option.

**Comment by andig** [comment]
Hi, I'm author of mbmd linked above. I've just tried connecting an ALE3 meter to mbmd and failed- device does not answer. Did you experience any problem talking to ALE3?

**Comment by nikito7** [comment]
My meter use 8o2

**Comment by gemu2015** [comment]
added full serial config option to modbus

usage:

after type m
+1,3,m,0,9600,*,1,2,01040000,01040002,01040004

you may specify
N =no parity
E =even parity
O =odd parity

and number of stop-bits

mN1
mN2
mE1
mE2
mO1
mO2

e.g
+1,3,mO2,0,9600,*,1,2,01040000,01040002,01040004

**Comment by nikito7** [comment]
Needs Hardware Serial?

**Comment by gemu2015** [comment]
Yes only hardware serial

**Comment by nikito7** [comment]
Working. ESP32.

Thank you
