### ISSUE TITLE
platformio.ini override

### ISSUE THREAD

**Issue by bvduijn** [arendst/Tasmota#7005]
**Have you looked for this feature in other issues and in the wiki?**  
yup

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
Add an option to override the default platformio.ini to retain user specific settings

**Describe alternatives you've considered**  
Modify the file everytime i do a pull from the master repo

**Additional context**  
If you could add a line in the platformio.ini like:

```
[platformio]
extra_configs = platformio_override.ini

```
This file could function the same way as user_config_override.h. Put in .gitignore and this way userspecific settings could remain in that file. Settings like:
- default_envs
- build_flags (-DUSE_CONFIG_OVERRIDE
- upload_port
- ... any other settings 

Kind regards,
Bert

**Comment by Jason2866** [comment]
@bvduijn  I like the idea. Please make a PR for

**Comment by ascillato2** [comment]
Closing as PR #7014 was proposed
