### ISSUE TITLE
Cyclical Timer

### ISSUE THREAD

**Issue by bkeevil** [arendst/Tasmota#7009]
How would I go about using the Tasmota to do a cyclical timer? For example I want to run a pump for 3 minutes every hour. Is this doable?

**Comment by meingraham** [comment]
Enter these two statements in the Tasmota web Console:
```
Rule1 ON Time#Minute|60 DO Power1 ON ENDON

Backlog PulseTime1 280; Rule1 1
```
Please close this issue. If you have further questions, please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
