### ISSUE TITLE
Suport for Iotty Switch

### ISSUE THREAD

**Issue by AFUman** [arendst/Tasmota#7019]
Is there any support for the Iotty Smart Switches or is there already a plan?

Chris

**Comment by meingraham** [comment]
New devices can be supported through the Tasmota Template feature. Please refer to the wiki.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
From a google search, there are no internal photos of that device. If that device has an ESP8266 chip, it might be supported by Tasmota. If does not have an ESP8266, it won't be supported.

**Comment by AFUman** [comment]
I have make Picture from the Iotty Switch this has a ESP-12S and a 
CY8C4245PVI-482
1725 0 03
CYP 625977

![IMG_20191225_164351](https://user-images.githubusercontent.com/28683249/71448125-1ad46380-2738-11ea-9360-a1b552d1303c.jpg)
![IMG_20191225_164357](https://user-images.githubusercontent.com/28683249/71448126-1dcf5400-2738-11ea-8bc6-134aebb66f85.jpg)
![IMG_20191225_164430](https://user-images.githubusercontent.com/28683249/71448127-2031ae00-2738-11ea-9266-f8acd5b3fad2.jpg)
