### ISSUE TITLE
NTP-Server via DHCP-Options

### ISSUE THREAD

**Issue by BearTi** [arendst/Tasmota#7026]
Hi,

I´ve a router with OpenWRT and set as DHCP-Options "42,10.200.0.1", means the NTP server is send via the DHCP request of a client.

When I connect my Tosmata socket (Gosund 111) with my router the NTP server is not set (command "ntpserver" in the Tosmata console).

Do I make something wrong or is this DHCP option not supported?

Thanks

**Comment by meingraham** [comment]
https://github.com/arendst/Tasmota/issues/5283#issuecomment-466888846

Please close this issue and address further questions to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
