### ISSUE TITLE
rule trigger issue for switch1#state=1 or 0

### ISSUE THREAD

**Issue by balvant813** [arendst/Tasmota#7043]
I have a sonoff basic switch with PIR sensor connected as switch2n (gpio1) and piano button connected to switch1 (gpio3).
Wanted behaviors:

1. on PIR trigger, power is on for 30 secs.   fires a mqtt message PIR ON and OFF
(this behavior works well)
    
2. When Piano switch in on, power is ON till Piano switch is OFF (irrespective of PIR state). When Piano switch is off PIR behavior is active. 
THIS behavior does not WORK
rule2 never triggers when piano switch is turned on or off  i.e.  switch1#state=1 or 0. The   STATUS  10 does show ON and OFF for switch1.

 **don't know why rule2 with Switch1#state=1 or 0 never triggers?**

`12:38:05 CMD: status 0
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS = {"Status":{"Module":1,"FriendlyName":["BrainCnt LtSwitch 3wyMain 113"],"Topic":"basicR1_113_braincnt_3wmain","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[1,1,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T17:44:49","StartupUTC":"2019-11-26T23:53:16","Sleep":50,"CfgHolder":4617,"BootCount":36,"SaveCount":18575,"SaveAddress":"FB000"}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS2 = {"StatusFWR":{"Version":"6.7.1(sonoff)","BuildDateTime":"2019-10-26T13:19:13","Boot":7,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["netAppliancesUiFi_2","netAppliancesUiFi"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00000129","2805C8000100060000005AFF000000000000","00000001"]}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS4 = {"StatusMEM":{"ProgramSize":564,"Free":440,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","0000F081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS5 = {"StatusNET":{"Hostname":"basicR1_113_braincnt_3wmain-568","IPAddress":"192.168.200.113","Gateway":"192.168.200.1","Subnetmask":"255.255.254.0","DNSServer":"192.168.200.1","Mac":"84:0D:8E:56:96:32","Webserver":2,"WifiConfig":2}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.200.100","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_569632","MqttUser":"unraidMQTT","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS7 = {"StatusTIM":{"UTC":"Wed Nov 27 17:38:05 2019","Local":"Wed Nov 27 12:38:05 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"-05:00","Sunrise":"02:16","Sunset":"10:58"}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS10 = {"StatusSNS":{"Time":"2019-11-27T12:38:05","Switch1":"ON","Switch2":"OFF"}}
12:38:05 MQT: stat/basicR1_113_braincnt_3wmain/STATUS11 = {"StatusSTS":{"Time":"2019-11-27T12:38:05","Uptime":"0T17:44:49","UptimeSec":63889,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":2,"SSId":"netAppliancesUiFi","BSSId":"B0:BE:76:18:76:00","Channel":6,"RSSI":96,"LinkCount":1,"Downtime":"0T00:00:05"}}}`

### RULES:
`12:40:23 CMD: rule1
12:40:23 MQT: stat/basicR1_113_braincnt_3wmain/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":410,"Rules":"on switch2#state=1 do backlog power on; ruletimer1 30 ; Var1 1 endon on rules#timer=1 do Var1 3 endon"}

12:41:09 CMD: rule2
12:41:09 MQT: stat/basicR1_113_braincnt_3wmain/RESULT = {"Rule2":"ON","Once":"OFF","StopOnError":"OFF","Free":311,"Rules":"on Switch1#state=1 do rule1 0 endon on Switch1#state=0 do backlog power off; rule1 1; Var1 2 endon on Var1#State=3 do backlog power off; Var1 0 break on Var1#State=2 do backlog power off; Var1 0 endon"}

12:41:41 CMD: rule3
12:41:41 MQT: stat/basicR1_113_braincnt_3wmain/RESULT = {"Rule3":"ON","Once":"OFF","StopOnError":"OFF","Free":274,"Rules":"on switch2#state=1 do publish stat/basicR1_113_braincnt_3wmain/PIR ON endon  on switch2#state=0 do publish stat/basicR1_113_braincnt_3wmain/PIR OFF endon on power1#state do publish cmnd/basicR1_158_braincnt_3wslave/LedState %value% endon"}`

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
