### ISSUE TITLE
Lost all connections to device after MQTT configuration update

### ISSUE THREAD

**Issue by madilla** [arendst/Tasmota#7045]
### ISSUE DESCRIPTION - TROUBLESHOOTING
I flashed tasmota 7.0.0 into a MPV2RO-US, everything is going great.
I can connect to it through its local IP. I changed the configuration on generic(18) and when I click toggle, I hear the click the plug does. Now when I go to configure the MQTT to connect to the MQTT broker (version 5.1) I have running on my HASS.io. My MQTT broker is running fine on my Hass.io, it has login auth so I entered the Hass.io local ip, the username, password and a topic to the MQTT parameters and hit save. After a moment, I lose connection through the local ip to the mpv2ro plug. Its not connected to my wifi at all. Using the button on the side of the plug does nothing. Has this been bricked? The actual button doesn't work either.

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [X ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Tasmota/issues)
- [X ] Searched the problem in the wiki (https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): MPV2RO-US
- [ ] Tasmota binary firmware version number used: 7.0.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X ] Flashing tools used: tuya-convert
- [ ] Provide the output of this command: ``Backlog Template; Module; GPIO``:
  ```
  Configuration output here:
Not available

  ```
- [ ] If using rules, provide the output of this command: ``Backlog Rule1; Rule2; Rule3``:
  ```
  Rules output here:
Not available

  ```
- [ ] Provide the output of this command: ``Status 0``:
  ```
  STATUS 0 output here:
Not available

  ```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ ``weblog 4`` _for more debug information)_
  ```
  Console output here:
Not available

  ```

MQTT log:

1574823517: mosquitto version 1.6.3 starting
1574823517: Config loaded from /etc/mosquitto.conf.
1574823517: Loading plugin: /usr/share/mosquitto/auth-plug.so
1574823517:  ├── Username/password checking enabled.
1574823517:  ├── TLS-PSK checking enabled.
1574823517:  └── Extended authentication not enabled.
1574823517: |-- *** auth-plug: startup
1574823517: Opening ipv4 listen socket on port 1883.
1574823517: Opening ipv6 listen socket on port 1883.
1574823517: Opening websockets listen socket on port 1884.
1574823517: Warning: Mosquitto should not be run as root/administrator.
1574891673: Saving in-memory database to /data/mosquitto.db.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you in this case. 

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
