### ISSUE TITLE
Exception while connect to wifi

### ISSUE THREAD

**Issue by mooonsee** [arendst/Tasmota#7051]
Hi guys,

I've tried to flash firmware on my sonoff basic.
It is not first device - but first where I found the issues.
Before flashing device works fine with original firmware connected to ewelink account.

After clearing:
esptool.py --port COM6 erase_flash
esptool.py --port COM6 erase_region 0x20000 0x4000

I've try to flash with latest 6.7.1 (I've try with 5.1.4, 6.1.1, 6.3 as well, but also no success with working).

Everything end with success flushing, after which I can see sonoff_xxxx network and I try to connect with it.
As result, on miniterm I see exception while my computer is connecting and opening home page of sonoff. Output placed at the end.

Do you have any suggestions what to do next?
My goal is to connect device do Home Assistant.

00:00:00 CFG: Loaded from flash at FA, Count 10
00:00:00 Project sonoff Sonoff Version 6.7.1(sonoff)-STAGE
00:00:00 WIF: WifiManager active for 3 minutes
00:00:00 HTP: Web server active on sonoff-7530 with IP address 192.168.4.1

Exception (28):
epc1=0x4010167e epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffa90 end: 3fffffc0 offset: 01a0
3ffffc30:  ffffffff 3fffc6fc 00000001 3ffefc48  
3ffffc40:  00000000 000000c8 3ffffd60 00000000  
3ffffc50:  40281fd8 00000030 3ffffd00 3ffffd60  
3ffffc60:  3fff48ec 00000010 7ffff860 4023ec17  
3ffffc70:  0000000d 00000000 00000020 40100940  
3ffffc80:  00000000 0000000d 3ffffcdc 4023ec41  
3ffffc90:  3fff48ec 3ffffd0c 3ffffcdc 4023ee4c  
3ffffca0:  00000000 3ffffd00 3ffffcdc 4023ee7c  
3ffffcb0:  3ffffd0c 00000023 3ffffd00 4023ecdc  
3ffffcc0:  000000c8 40281fd8 3fff4264 40210b63  
3ffffcd0:  3fff3b9c 3fff4264 3ffffd00 4023f000  
3ffffce0:  40281fd8 80ffffff 3fff4c14 4023119a  
3ffffcf0:  000000c8 3fff4264 3ffefc48 40210c09  
3ffffd00:  3fff4b9c 0023002f 00040000 3fff48ec  
3ffffd10:  000d000f 00000000 3ffefc48 4023111c  
3ffffd20:  3fff30e4 00000000 3ffefc48 4022b1c4  
3ffffd30:  40243cb0 00000000 00001388 3fffc278  
3ffffd40:  00000000 3fff4c14 00000022 4010189a  
3ffffd50:  00000000 4027c626 4027c626 4022b296  
3ffffd60:  40213a59 00000004 3ffffd90 4023ea7d  
3ffffd70:  3fff4264 3ffffd90 3ffefc48 3ffffd90  
3ffffd80:  00000000 4027c626 3ffefc48 4022c39e  
3ffffd90:  65766100 3fff4300 80000001 00000030  
3ffffda0:  00000000 00000000 4bc6a7f0 00000000  
3ffffdb0:  3fff30e4 00000020 40100cc0 00000f8a  
3ffffdc0:  00000000 00000000 3ffe8700 00000b68  
3ffffdd0:  00000f8a ffffffff 3ffe8700 4023ff52  
3ffffde0:  00000003 00000020 0000029f 40101385  
3ffffdf0:  3fff30e4 00000003 3ffffe30 4023ea7d  
3ffffe00:  00000000 3ffffe30 3ffefc48 40210624  
3ffffe10:  3fff1d68 00000000 3ffefc48 4022bfcb  
3ffffe20:  3fff4314 3fff4288 3ffffec8 4023ea7d  
3ffffe30:  00747300 3fff4288 80ff4264 4023ea9c  
3ffffe40:  00000001 3fff4288 3fff4264 40213aa1  
3ffffe50:  74736f00 00000001 3ffffea0 00000001  
3ffffe60:  3ffffea0 3fff4374 00000000 40210624  
3ffffe70:  00000001 00000001 3fff434c 402428ea  
3ffffe80:  00000001 4020153c 3fff434c 401000e1  
3ffffe90:  3fff434c 3fff42a4 3fff434c 4021065a  
3ffffea0:  3fff0000 3fff0000 80ff4094 8023c1c6  
3ffffeb0:  3fff434c 3fff42a4 3fff4264 4022ece6  
3ffffec0:  0000002f 80000000 81ff4b00 0000002f  
3ffffed0:  80005054 00000020 40100cc0 00000f87  
3ffffee0:  3fff42a4 00000001 3fff4264 40231aec  
3ffffef0:  00000001 00000001 00000000 3fff2db8  
3fffff00:  00000000 3fff4c14 3fff4264 3fff2db8  
3fffff10:  00000001 3fff4288 3fff4264 4022edfc  
3fffff20:  40243cb0 00000000 00001388 402487e8  
3fffff30:  00000000 3fff4c14 3fff4b9c 4023c55e  
3fffff40:  000000e7 00000000 00000005 4022ee92  
3fffff50:  00000000 3fff2ec0 3ffe8700 4022eeba  
3fffff60:  0011f420 3fff2ec0 3ffe8700 4023ff52  
3fffff70:  40240dc6 00000025 00000025 4020d3f8  
3fffff80:  3fffdad0 00000000 00000f87 40227e1b  
3fffff90:  3fffdad0 00000000 3fff2d78 3fff2db8  
3fffffa0:  3fffdad0 00000000 3fff2d78 40240094  
3fffffb0:  feefeffe feefeffe 3ffe8700 401008a5  
<<<stack<<<

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v11c3757b
~ld

**Comment by ascillato** [comment]
Hi,

the combination 6.7.1(sonoff)-STAGE was never provided, so you are using a core in beta stage

Please, use instead the precompiled bins (latest Tasmota 7.0.0.6) that are builded with a stable core (release 2.6.1) http://thehackbox.org/tasmota/tasmota.bin
