### ISSUE TITLE
Smart Config causing Exception(0) Issue

### ISSUE THREAD

**Issue by Picotronic** [arendst/Tasmota#7059]
> **GUIDE**
>
> This troubleshooting issue template is meant to help Tasmota users with difficult problems. It is aimed to be opened if using the wiki and the support chat could not solve the issue. The Github Issue tracker is NOT a general discussion forum!
>
> Please DO NOT OPEN AN ISSUE:
>  - If you have general questions or you need help on Tasmota usage, go to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
>  - If your Tasmota version is not the latest from the development branch, please update your device before submitting your issue. Your problem might already be solved. The latest precompiled binaries of Tasmota can be downloaded from http://thehackbox.org/tasmota/
>  - If your issue is about a new device, please use the Tasmota [Template](../wiki/Templates) feature.
>  - If your issue is a flashing issue, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
>  - If your issue is compilation problem, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)
>  - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue
>  - If your issue is a Wi-Fi problem or MQTT problem, please try the steps provided in the [FAQ](https://github.com/arendst/Tasmota/wiki/FAQ) and troubleshooting wiki articles
>
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

### ISSUE DESCRIPTION - TROUBLESHOOTING
I am using Tasmota version 6.6.0 in order to avail smart config feature, since it is not available in the latest version. I am using arduino core 2.5.2. I have commented the "#define USE_WEBSERVER" and uncommitted smartconfig in user_config feature to get the device in smart config mode at the startup. As soon as the device starts it goes to the smart config mode but in exactly 10 sec device through an exception (0). I Commented the smartconfig.begin function in code and the code was running fine.

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff 
- [x] Tasmota binary firmware version number used: 6.6.0
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: Platformio
- [x] Flashing tools used: esptool.py
- [ ] Provide the output of this command: ``Backlog Template; Module; GPIO``:
  ```
  Configuration output here:

Exception (0):
epc1=0x40224150 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffa50 end: 3fffffc0 offset: 01a0
3ffffbf0:  3ffffd00 3ffffcf0 00000018 40103698  
3ffffc00:  00000002 00000001 40102ca4 00000104  
3ffffc10:  3ffe9f30 0001d2d6 7fffffff 00000000  
3ffffc20:  3fff0059 00000000 00000008 40102b7c  
3ffffc30:  3ffffd29 3ffffd50 00000000 ffff0208  
3ffffc40:  3ffffd20 2c9f030c 4000050c 3fffc278  
3ffffc50:  40102b7c 3fffc200 00000022 3ffe9f30  
3ffffc60:  400043f0 00000030 00000018 ffffffff  
3ffffc70:  400044ab 3fffc718 3ffffd60 08000000  
3ffffc80:  60000200 08000000 00000003 00000000  
3ffffc90:  0000ffff 00042035 00002035 000f9000  
3ffffca0:  3fff02b4 3fff11a8 00000000 00000030  
3ffffcb0:  4020aaf2 00000030 00000013 ffffffff  
3ffffcc0:  40212d2e 0000ec48 00000585 00000e01  
3ffffcd0:  3fff02b4 00000000 3fff005e 0000ffff  
3ffffce0:  000001b0 3fffc6fc 00000000 3ffef694  
3ffffcf0:  3fff02b4 3fff0178 00000000 00000030  
3ffffd00:  00000000 00000009 000000c9 00000003  
3ffffd10:  000001b0 3fffc6fc 00000000 402120ea  
3ffffd20:  303a3030 39303a30 3fff0020 00000030  
3ffffd30:  ffffffff 00000020 00000003 40212ca6  
3ffffd40:  00000000 4000444e 00000008 4021b868  
3ffffd50:  00000002 40106033 00000001 60000200  
3ffffd60:  00000002 4000410f 00001001 00000205  
3ffffd70:  3fffc718 40004a3c 000000f9 3fff02b4  
3ffffd80:  3fffc718 401062c4 000000f9 3ffe837c  
3ffffd90:  4021fdce 3ffef694 00000000 3fff0175  
3ffffda0:  3ffef5a6 3ffef5ad 3fff01a0 40212d3b  
3ffffdb0:  00000e00 3fff005e 0000000d 40100398  
3ffffdc0:  3ffffead 3fff02b4 3fff01a0 3fff0175  
3ffffdd0:  3fff0178 3fff02b4 3fff01a0 4021c5a4  
3ffffde0:  40102bfd 0000000c 00000000 40102b7c  
3ffffdf0:  00000002 2c9f030c 4000050c 3fffc278  
3ffffe00:  40102b7c 3fffc200 00000022 3fffc278  
3ffffe10:  4020ed3d 00000030 00000000 ffffffff  
3ffffe20:  4020ed49 00000000 00000014 00000001  
3ffffe30:  40102bfd 00000004 00000000 40102b7c  
3ffffe40:  40102bfd 00000004 00000000 0000001c  
3ffffe50:  0000000c 2c9f030c 4000050c 3fffc278  
3ffffe60:  40102b7c 3fffc200 00000022 3fffc278  
3ffffe70:  40225ed8 00000030 00000010 ffffffff  
3ffffe80:  4020c092 00002710 000026e6 00000000  
3ffffe90:  00004bc6 00000000 00000001 00000003  
3ffffea0:  00000000 3fffc6fc 00000000 00002710  
3ffffeb0:  3fff01f4 3fffdad0 3fff12e8 00000030  
3ffffec0:  00000004 000000f5 3fff12e8 00000030  
3ffffed0:  00000032 3fffdad0 3fff12e8 00000030  
3ffffee0:  401058d3 00050c75 3fff3ccc 00000000  
3ffffef0:  3ffee880 3fff3ccc 00000014 40224160  
3fffff00:  00000001 00000000 3fff249c 4020970b  
3fffff10:  00000000 4bc6a7f0 00002718 3fff12e8  
3fffff20:  00000000 4bc6a7f0 00002718 3fff12e8  
3fffff30:  00000000 00000000 4bc6a7f0 00000000  
3fffff40:  00000000 00000014 4010030e e7ae147a  
3fffff50:  00000000 00000000 00000000 4020c08b  
3fffff60:  3ffe85c0 3fff01f0 0000280a 4020c08b  
3fffff70:  3fffdad0 00000000 000000fa 3fff12e8  
3fffff80:  3fffdad0 3fff01f0 00002718 4021c75a  
3fffff90:  00000000 00000000 00000001 3fff12e8  
3fffffa0:  3fffdad0 00000000 3fff12b8 402222b8  
3fffffb0:  feefeffe feefeffe 3ffe8608 401008fd  
<<<stack<<<








  ```
- [ ] If using rules, provide the output of this command: ``Backlog Rule1; Rule2; Rule3``:
  ```
  Rules output here:


  ```
- [ ] Provide the output of this command: ``Status 0``:
  ```
  STATUS 0 output here:


  ```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ ``weblog 4`` _for more debug information)_
  ```
  Console output here:


  ```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Sorry, this build is to old and not supported anymore. The core 2.5.2 has errors and security issues.
