### ISSUE TITLE
blitzwolf shp7 successfully flashed how do you find the right Config?

### ISSUE THREAD

**Issue by gitpower2017** [arendst/Tasmota#7060]
Hello,

I hope I'm in the right place.
I successfully flashed a BW-SHP7 with Tasmota.
(if you are interested I have pictures of the hardware, solder points)
But how do I find the right configuration?

Regards
Lothar

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
