### ISSUE TITLE
no ws2812 in Tasmota 7.1.0

### ISSUE THREAD

**Issue by mpuff** [arendst/Tasmota#7067]
Hello,

i have updatet to the latest 7.1 and now i have no option to add ws2812 for a gpio pin in the generic module.

Is there a way to activate it?

Kind regards

**Comment by ascillato** [comment]
Hi, if you have updated to Tasmota_basic.bin, there is ws2812 support on that lite firmware. You need to update to the full version: Tasmota.bin
