### ISSUE TITLE
multiple libraries were found !!

### ISSUE THREAD

**Issue by Ahmed933** [arendst/Tasmota#7070]
i followed all steps mentioned in https://tasmota.github.io/docs/#/Arduino-IDE and when compiling tasmota.ino i always have this errors and i don't why i removed all libraries arduino/libraries folder and copy those in tasmota/lib and paste them again into arduino/libraries and still have these errors
what should i do, thanks in advance :)

F:\ATC IOSS Team\Software\Arduino\arduino-1.8.10\portable\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506/bin/xtensa-lx106-elf-ar: unable to rename 'core\core.a'; reason: File exists

Multiple libraries were found for "NewPing.h"
 Used: F:\ATC
Multiple libraries were found for "ESP8266HTTPClient.h"
 Used: F:\ATC
Multiple libraries were found for "IRremoteESP8266.h"
 Used: F:\ATC
Multiple libraries were found for "SPI.h"
 Used: F:\ATC
Multiple libraries were found for "ESP8266WiFi.h"
 Used: F:\ATC
Multiple libraries were found for "PubSubClient.h"
 Used: F:\ATC
Multiple libraries were found for "ihx.h"
 Used: F:\ATC
Multiple libraries were found for "ESP8266mDNS.h"
 Used: F:\ATC
Multiple libraries were found for "Ticker.h"
 Used: F:\ATC
Multiple libraries were found for "DNSServer.h"
 Used: F:\ATC
Multiple libraries were found for "TasmotaSerial.h"
 Used: F:\ATC
Multiple libraries were found for "esp-knx-ip.h"
 Used: F:\ATC
Multiple libraries were found for "EEPROM.h"
 Used: F:\ATC
Multiple libraries were found for "ESP8266WebServer.h"
 Used: F:\ATC
Multiple libraries were found for "NeoPixelBus.h"
 Used: F:\ATC
Multiple libraries were found for "TasmotaModbus.h"
 Used: F:\ATC
Multiple libraries were found for "ESP8266httpUpdate.h"
 Used: F:\ATC
Multiple libraries were found for "ArduinoJson.h"
 Used: F:\ATC
Multiple libraries were found for "Wire.h"
 Used: F:\ATC
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module)

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
