### ISSUE TITLE
Sonoff LED Dimmer(Slider) webGUI do not work...

### ISSUE THREAD

**Issue by timtimsson** [arendst/Tasmota#7073]
Hi team,
I use 4 old sonoff LED controller with v6.6.0.10 - it works
After update to v7.1.0 with mqtt and console the Dimmer is working, but if i use the slider(Dimmer) do **not** work ...(at movement no update to console/mqtt)
The Silder (warm/cold) is working well.
Any ideas?
Thanks!

**Comment by s-hadinger** [comment]
Fixed in the latest release. 

https://github.com/arendst/Tasmota/commit/5524075b04e28548e71254ae01205a58d02ecaac
