### ISSUE TITLE
Sonoff B1 Module not working - gui slider missing 7.1.1.1

### ISSUE THREAD

**Issue by timtimsson** [arendst/Tasmota#7084]
Hello team,
Sonoff B1 Module not working - gui slider missing 7.1.1.1
Thanks

**Comment by arendst** [comment]
????

![image](https://user-images.githubusercontent.com/11044339/69957761-9d844d00-1503-11ea-864d-5a7a4aa98f9d.png)

**Comment by timtimsson** [comment]
hi theo,
i compile with arduino 1.8.10 - 2.6.2 by my one with the latest github from my old 6.6.0.
//#define USE_CONFIG_OVERRIDE
#define FIRMWARE_BASIC
???
![tasmo](https://user-images.githubusercontent.com/17343162/69960239-408b9580-1509-11ea-97be-5a1c354c4c31.jpg)

![tasmo1](https://user-images.githubusercontent.com/17343162/69961506-4df64f00-150c-11ea-9ff9-911ed8d6f368.jpg)

**Comment by arendst** [comment]
There you have it. 

tasmota-basic does NOT support the B1 driver as can be found in the Release notes.

**Comment by timtimsson** [comment]
OMG! i waste your time - i'm so sorry!!!
