### ISSUE TITLE
smart plug spontaneously reset

### ISSUE THREAD

**Issue by bartgrefte** [arendst/Tasmota#7104]
### PROBLEM DESCRIPTION
Smart plug spontaneously reset to default settings, the settings that are present after flashing Tasmota using tuya-convert. No clue as of why, there was no power failure or something. 
Had to reconfigure wifi, the template and still have to redo the re-calibration. Now where did I put the old lightbulbs...

### REQUESTED INFORMATION
- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Hihome WPP-16S
- [X] Tasmota binary firmware version number used: 7.0.0.3, just OTA'd to 7.1.1.
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: Tuya-convert
- [X] Provide the output of command: ``Backlog Template; Module; GPIO``:
 ```
12:29:26 RSL: stat/tasmota/RESULT = {"NAME":"HIhome WPP-16S","GPIO":[17,0,0,0,134,132,0,0,131,56,21,0,0],"FLAG":0,"BASE":49}
12:29:26 RSL: stat/tasmota/RESULT = {"Module":{"0":"HIhome WPP-16S"}}
12:29:26 RSL: stat/tasmota/RESULT = {"GPIO":"Not supported"}
 ```
- [X] Provide the output of this command: ``Status 0``:
```
12:37:03 RSL: stat/tasmota/STATUS = {"Status":{"Module":0,"FriendlyName":["Tasmota"],"Topic":"tasmota","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
12:37:03 RSL: stat/tasmota/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:16:53","StartupUTC":"2019-12-04T11:20:10","Sleep":50,"CfgHolder":4617,"BootCount":993,"SaveCount":1007,"SaveAddress":"F8000"}}
12:37:03 RSL: stat/tasmota/STATUS2 = {"StatusFWR":{"Version":"7.1.1(tasmota)","BuildDateTime":"2019-12-01T13:00:09","Boot":7,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX"}}
12:37:03 RSL: stat/tasmota/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Buffy's IoT network",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
12:37:03 RSL: stat/tasmota/STATUS4 = {"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
12:37:03 RSL: stat/tasmota/STATUS5 = {"StatusNET":{"Hostname":"tasmota-7029","IPAddress":"192.168.4.4","Gateway":"192.168.4.1","Subnetmask":"255.255.255.0","DNSServer":"1.1.1.1","Mac":"2C:F4:32:04:1B:75","Webserver":2,"WifiConfig":2}}
12:37:03 RSL: stat/tasmota/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_041B75","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
12:37:03 RSL: stat/tasmota/STATUS7 = {"StatusTIM":{"UTC":"Wed Dec 04 11:37:03 2019","Local":"Wed Dec 04 12:37:03 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:25","Sunset":"16:54"}}
12:37:03 RSL: stat/tasmota/STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
12:37:03 RSL: stat/tasmota/STATUS10 = {"StatusSNS":{"Time":"2019-12-04T12:37:03","ENERGY":{"TotalStartTime":"2019-12-02T10:01:36","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
12:37:03 RSL: stat/tasmota/STATUS11 = {"StatusSTS":{"Time":"2019-12-04T12:37:03","Uptime":"0T00:16:53","UptimeSec":1013,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Buffy's IoT network","BSSId":"C6:FB:E4:74:2E:EE","Channel":13,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:07"}}}
```

### TO REPRODUCE
Only happened once yet, no clue as of why, would like to know why this could've happened.

### EXPECTED BEHAVIOUR
Tasmota doesn't delete config.

edit: Something I noticed after the OTA update, the led in the button is now blinking (instead of being off) when the relay is set to off. That didn't happen with the previous firmware.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
