### ISSUE TITLE
implement option to present WiFi RSSI in dbm instead of percent

### ISSUE THREAD

**Issue by RoadRunnr** [arendst/Tasmota#7113]
**Have you looked for this feature in other issues and in the wiki?**  

Yes,

**Is your feature request related to a problem? Please describe.**  

Having the RSSI in percent instead of dbm is user friendly, but not very precise.

**Describe the solution you'd like**  

A SetOption to choose between the current percent presentation and dbm.

**(Please, remember to close the issue when the problem has been addressed)**  

I would implement this myself and send a PR, just wanting to know if this has a chance of being accepted before I invest the time.

**Comment by ascillato** [comment]
Hi,

Dupplicated from https://github.com/arendst/Tasmota/issues/3532

**Comment by andrethomas** [comment]
I think it should stay as % for the sake of simplicity to users.

**Comment by meingraham** [comment]
It can stay as % as default... but allow users to change it with a SetOption if they desire? This way most users retain the current output but those that want dBm can change the setting?

**Comment by Jason2866** [comment]
I would like to have dbm too. Should be possible https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/station-class.html#rssi

**Comment by ascillato** [comment]
@Jason2866 here is the actual code in Tasmota:

https://github.com/arendst/Tasmota/blob/b347c53846c84f17f246ab25cb373c87a0c747b6/tasmota/support_wifi.ino#L55-L67

**Comment by jziolkowski** [comment]
Instead of adding a SetOption to select one over another, IMO it's better to have RSSI always displayed and use a SetOption to optionally add dBm value as well. RSSI (while simplified) is a very useful on-glance quick diagnose wifi metric. Forcing external tools to poll the device for something so trivial is - IMO again - a bit overkill.

**Comment by RoadRunnr** [comment]
> Instead of adding a SetOption to select one over another, IMO it's better to have RSSI always displayed and use a SetOption to optionally add dBm value as well.

My plan was to also switch the value of the RSSI in the MQTT topic when the SetOption is in use. Displaying both on the WebUI is fine, but adding another node to the MQTT json is IMHO overkill.

Anyhow, after looking a bit more at the RSSI code I've decided that the changes are going to be quite simple. So, I'm going to just build it over the weekend, send a PR and then we can discuss based on an actual implementation.

**Comment by jziolkowski** [comment]
But in any scenario, RSSI won't be reported as -dBm?

**Comment by Jason2866** [comment]
@jziolkowski  It is in dBm if the conversion is NOT done Adrian showed.
I deleted the conversion and i get `"RSSI dBm":-51`

**Comment by jziolkowski** [comment]
RSSI dBm does not make sense, because RSSI by design is a unitless value. You have either RSSI, or dBm. Using "RSSI dBm" is like saying "percent Celsius"

**Comment by Jason2866** [comment]
Whatever you want :-) Just edit the text in that line

**Comment by jziolkowski** [comment]
The point is not how that node is named. What I'm saying is: keep RSSI 0-100. If user wants to display dBm value, don't present it as RSSI, because it is not.

**Comment by Jason2866** [comment]
It is named correctly if you change the line. There is NO RSSI anymore...
`10:01:17 MQT: tele/sonoff-53CBF8/STATE = {"Time":"2019-12-06T10:01:17","Uptime":"0T00:00:12","UptimeSec":12,"Vcc":3.041,"Heap":29,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Jason_Home_WLAN","BSSId":"00:A0:57:2A:BD:19","Channel":13,"Wifi dBm":-54,"LinkCount":1,"Downtime":"0T00:00:06"}}`

**Comment by jziolkowski** [comment]
dBm is enough, as it's a sub-dictionary of Wifi anyway :) However I still prefer having RSSI in place and dBm as an additional node, enabled with setoption

**Comment by andrethomas** [comment]
This thread is indeed entertaining...

**Comment by jziolkowski** [comment]
RSSI and dBm, best of both worlds. +1

**Comment by andrethomas** [comment]
Yup, now we can add all the rounding errors and find the missing wifi waves...
