### ISSUE TITLE
INA219 Calibration Commands

### ISSUE THREAD

**Issue by daniam75** [arendst/Tasmota#7116]
I have a wemos d1 mini using tasmota-sensors.bin with a INA219 board connected.  The sensor is recognized and outputs voltage, amps and power but the amperage is incorrect.  I should be getting 1.07 amps and I'm getting 3.23 amps.  I see there are commands to calibrate the amperage, CurrentSet but when I issue the command it just tells me error.  Is there a way for me to calibrate this sensor?  Do the calibration commands work?  CurrentSet, VoltageSet, PowerSet.

**Comment by ascillato** [comment]
See command `Sensor13`
