### ISSUE TITLE
Trigger fires perpetual, not only on value changes

### ISSUE THREAD

**Issue by AIexBV** [arendst/Tasmota#7119]
I need the total energy of a smart plug. Because the total energy counter is not readable directly, I use the event to put the value in a variable like this:

`Rule1 on Energy#Total do var1 %value% endon`

Basically that works, but unfortunately the trigger fires each second, even if there is no load on the plug and there is no change in the value. I think, the triggers should only fire, if the values behind them have changed. Is that a possible bug?

**Comment by ascillato** [comment]
As designed because you didn't put any condition and also because your rule has one-shot disabled.
