### ISSUE TITLE
interlock fails in tuyamcu (with mqtt or on the console)

### ISSUE THREAD

**Issue by biotecov** [arendst/Tasmota#7126]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Tuya-MCU wall touch switch with 4 buttons, flashed with tasmota 7.1.1.1 and with 7.2.0.
I selected module 55 (tuya MCU), then:
backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4 (this activates successfully the four buttons)
and finally
backlog interlock 1,2,3,4; interlock onI selected module 55 (tuya MCU), then:
backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4
and finally
backlog interlock 1,2,3,4; interlock on

Command "powerX on" on the console or mqtt activates relayX and ledX (as expected), but then, "powerY on" switches off relayX and ledX but fails to activate relayY and ledY. Issuing a second instance of "powerY" does the expected action.

Interlock works as expected with the touch pad, but not with commands: command "powerX on" on the console or mqtt activates relayX and ledX (as expected), but then, "powerY on" switches off relayX and ledX but fails to activate relayY and ledY. Issuing a second instance of "powerY" does the expected action.

In other words, interlock switches off the relay that was on, but fails to switch on the new relay via console or mqtt commands. This happens with any combination of X and Y (via commands) and for any interlock definition.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): wall touch switch based on Tuya MCU
- [ ] Tasmota binary firmware version number used: 7.1.1.1 and 7.2.1
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: Visual
- [x] Flashing tools used: tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
10:20:13 CMD: Backlog Template; Module; GPIO 255
10:20:13 MQT: stat/lasmeigas/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
10:20:14 MQT: stat/lasmeigas/RESULT = {"Module":{"55":"Tuya MCU"}}
10:20:14 MQT: stat/lasmeigas/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"107":"Tuya Tx"},"GPIO2":{"0":"None"},"GPIO3":{"108":"Tuya Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
10:07:33 CMD: status 0
10:07:33 MQT: stat/lasmeigas/STATUS = {"Status":{"Module":55,"FriendlyName":["Tasmota","Tasmota2","Tasmota3","Tasmota4"],"Topic":"lasmeigas","ButtonTopic":"0","Power":4,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
10:07:33 MQT: stat/lasmeigas/STATUS1 = {"StatusPRM":{"Baudrate":9600,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:09:34","StartupUTC":"2019-12-07T08:57:59","Sleep":50,"CfgHolder":6711,"BootCount":3,"SaveCount":18,"SaveAddress":"FA000"}}
10:07:33 MQT: stat/lasmeigas/STATUS2 = {"StatusFWR":{"Version":"7.1.2(tasmota)","BuildDateTime":"2019-12-06T17:32:23","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX"}}
10:07:33 MQT: stat/lasmeigas/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["LasMeigasWPA","LasMeigas505"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C009","2805C8000000060000005A00000000000000","00000000","00000000"]}}
10:07:33 MQT: stat/lasmeigas/STATUS4 = {"StatusMEM":{"ProgramSize":572,"Free":428,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashMode":0,"Features":["00000809","8FDAE397","043683A1","22B617CD","01001BC0","00007981"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
10:07:33 MQT: stat/lasmeigas/STATUS5 = {"StatusNET":{"Hostname":"lasmeigas-7373","IPAddress":"10.0.1.174","Gateway":"10.0.1.201","Subnetmask":"255.255.255.0","DNSServer":"10.0.1.201","Mac":"2C:F4:32:1F:3C:CD","Webserver":2,"WifiConfig":4}}
10:07:33 MQT: stat/lasmeigas/STATUS6 = {"StatusMQT":{"MqttHost":"my.mqtt.host.org","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1F3CCD","MqttUser":"LasMeigasIoT","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
10:07:33 MQT: stat/lasmeigas/STATUS7 = {"StatusTIM":{"UTC":"Sat Dec 07 09:07:33 2019","Local":"Sat Dec 07 10:07:33 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"08:41","Sunset":"17:46"}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
00:00:00 CFG: Loaded from flash at FA, Count 10
00:00:00 Project tasmota Tasmota Version 7.1.2(tasmota)-2_6_1
00:00:00 SNS: Hardware Serial
00:00:00 WIF: Connecting to AP1 LasMeigasWPA in mode 11N as lasmeigas-7373...
00:00:07 WIF: Connected
00:00:07 HTP: Web server active on lasmeigas-7373 with IP address 10.0.1.174
09:58:09 MQT: Attempting connection...
09:58:09 MQT: Connected
09:58:09 MQT: tele/lasmeigas/LWT = Online (retained)
09:58:09 MQT: cmnd/lasmeigas/POWER = 
09:58:09 MQT: tele/lasmeigas/INFO1 = {"Module":"Tuya MCU","Version":"7.1.2(tasmota)","FallbackTopic":"cmnd/DVES_1F3CCD_fb/","GroupTopic":"cmnd/tasmotas
/"}
09:58:09 MQT: tele/lasmeigas/INFO2 = {"WebServerMode":"Admin","Hostname":"lasmeigas-7373","IPAddress":"10.0.1.174"}
09:58:09 MQT: tele/lasmeigas/INFO3 = {"RestartReason":"Software/System restart"}
09:58:09 MQT: stat/lasmeigas/RESULT = {"POWER1":"OFF"}
09:58:09 MQT: stat/lasmeigas/POWER1 = OFF
09:58:09 MQT: stat/lasmeigas/RESULT = {"POWER2":"OFF"}
09:58:09 MQT: stat/lasmeigas/POWER2 = OFF
09:58:09 MQT: stat/lasmeigas/RESULT = {"POWER3":"OFF"}
09:58:09 MQT: stat/lasmeigas/POWER3 = OFF
09:58:09 MQT: stat/lasmeigas/RESULT = {"POWER4":"OFF"}
09:58:09 MQT: stat/lasmeigas/POWER4 = OFF
09:58:13 MQT: tele/lasmeigas/STATE = {"Time":"2019-12-07T09:58:13","Uptime":"0T00:00:14","UptimeSec":14,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"Loa
dAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"LasMeigasWPA","BSSId":"00:18:39:AE:5C:FC","Ch
annel":6,"RSSI":34,"LinkCount":1,"Downtime":"0T00:00:08"}}
09:59:58 CMD: weblog 4
09:59:58 MQT: stat/lasmeigas/RESULT = {"WebLog":4}
09:59:58 CFG: Saved to flash at F8, Count 12, Bytes 4096
10:00:00 TYA: Send "55aa00000000ff"
10:00:00 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:00 TYA: Heartbeat
10:00:04 CMD: backlog interlock 1,2,3,4; interlock on
10:00:04 SRC: WebConsole from 10.0.1.114
10:00:04 CMD: Group 0, Index 1, Command "BACKLOG", Data "interlock 1,2,3,4; interlock on"
10:00:04 SRC: Backlog
10:00:04 CMD: Group 0, Index 1, Command "INTERLOCK", Data "1,2,3,4"
10:00:04 MQT: stat/lasmeigas/RESULT = {"Interlock":"OFF","Groups":"1,2,3,4"}
10:00:05 SRC: Backlog
10:00:05 CMD: Group 0, Index 1, Command "INTERLOCK", Data "on"
10:00:05 TYA: Send "55aa0006000501010001000d"
10:00:05 MQT: stat/lasmeigas/RESULT = {"Interlock":"ON","Groups":"1,2,3,4"}
10:00:05 {"TuyaReceived":{"Data":"55AA0007000501010001000E","Cmnd":7,"CmndData":"0101000100","DpId":1,"DpIdType":1,"DpIdData":"00"}}
10:00:05 TYA: fnId=11 is set for dpId=1
10:00:05 TYA: RX Relay-1 --> MCU State: Off Current State:Off
10:00:05 CFG: Saved to flash at F7, Count 13, Bytes 4096
10:00:08 WIF: Checking connection...
10:00:08 WIF: Connected
10:00:11 TYA: Send "55aa00000000ff"
10:00:11 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:11 TYA: Heartbeat
10:00:22 TYA: Send "55aa00000000ff"
10:00:22 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:22 TYA: Heartbeat
10:00:28 WIF: Checking connection...
10:00:28 WIF: Connected
10:00:33 TYA: Send "55aa00000000ff"
10:00:33 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:33 TYA: Heartbeat
10:00:44 TYA: Send "55aa00000000ff"
10:00:44 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:44 TYA: Heartbeat
10:00:48 WIF: Checking connection...
10:00:48 WIF: Connected
10:00:55 TYA: Send "55aa00000000ff"
10:00:55 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:00:55 TYA: Heartbeat
10:01:06 TYA: Send "55aa00000000ff"
10:01:06 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:01:06 TYA: Heartbeat
10:01:08 WIF: Checking connection...
10:01:08 WIF: Connected
10:01:17 TYA: Send "55aa00000000ff"
10:01:17 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:01:17 TYA: Heartbeat
10:01:28 WIF: Checking connection...
10:01:28 WIF: Connected
10:01:28 TYA: Send "55aa00000000ff"
10:01:28 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:01:28 TYA: Heartbeat
10:01:39 TYA: Send "55aa00000000ff"
10:01:39 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:01:39 TYA: Heartbeat
10:01:47 CMD: power1 on
10:01:47 SRC: WebConsole from 10.0.1.114
10:01:47 CMD: Group 0, Index 1, Command "POWER", Data "on"
10:01:47 TYA: Send "55aa0006000501010001010e"
10:01:47 MQT: stat/lasmeigas/RESULT = {"POWER1":"ON"}
10:01:47 MQT: stat/lasmeigas/POWER1 = ON
10:01:47 {"TuyaReceived":{"Data":"55AA0007000501010001010F","Cmnd":7,"CmndData":"0101000101","DpId":1,"DpIdType":1,"DpIdData":"01"}}
10:01:47 TYA: fnId=11 is set for dpId=1
10:01:47 TYA: RX Relay-1 --> MCU State: On Current State:On
10:01:47 CFG: Saved to flash at F6, Count 14, Bytes 4096
10:01:48 WIF: Checking connection...
10:01:48 WIF: Connected
10:01:50 TYA: Send "55aa00000000ff"
10:01:50 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:01:50 TYA: Heartbeat
10:01:56 CMD: power3 on
10:01:56 SRC: WebConsole from 10.0.1.114
10:01:56 CMD: Group 0, Index 3, Command "POWER", Data "on"
10:01:56 TYA: Send "55aa0006000501010001000d"
10:01:56 MQT: stat/lasmeigas/RESULT = {"POWER1":"OFF"}
10:01:56 MQT: stat/lasmeigas/POWER1 = OFF
10:01:56 TYA: Send "55aa0006000501010001000d"
10:01:56 MQT: stat/lasmeigas/RESULT = {"POWER3":"ON"}
10:01:56 MQT: stat/lasmeigas/POWER3 = ON
10:01:56 {"TuyaReceived":{"Data":"55AA0007000501010001000E","Cmnd":7,"CmndData":"0101000100","DpId":1,"DpIdType":1,"DpIdData":"00"}}
10:01:56 TYA: fnId=11 is set for dpId=1
10:01:56 TYA: RX Relay-1 --> MCU State: Off Current State:Off
10:01:56 {"TuyaReceived":{"Data":"55AA0007000501010001000E","Cmnd":7,"CmndData":"0101000100","DpId":1,"DpIdType":1,"DpIdData":"00"}}
10:01:56 TYA: fnId=11 is set for dpId=1
10:01:56 TYA: RX Relay-1 --> MCU State: Off Current State:Off
10:01:56 CFG: Saved to flash at F5, Count 15, Bytes 4096
10:02:01 TYA: Send "55aa00000000ff"
10:02:01 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:01 TYA: Heartbeat
10:02:08 WIF: Checking connection...
10:02:08 WIF: Connected
10:02:12 TYA: Send "55aa00000000ff"
10:02:12 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:12 TYA: Heartbeat
10:02:23 TYA: Send "55aa00000000ff"
10:02:23 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:23 TYA: Heartbeat
10:02:28 WIF: Checking connection...
10:02:28 WIF: Connected
10:02:34 TYA: Send "55aa00000000ff"
10:02:34 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:34 TYA: Heartbeat
10:02:45 TYA: Send "55aa00000000ff"
10:02:45 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:45 TYA: Heartbeat
10:02:48 WIF: Checking connection...
10:02:48 WIF: Connected
10:02:56 TYA: Send "55aa00000000ff"
10:02:56 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:02:56 TYA: Heartbeat
10:03:00 SRC: Switch
10:03:00 MQT: stat/lasmeigas/RESULT = {"POWER1":"ON"}
10:03:00 MQT: stat/lasmeigas/POWER1 = ON
10:03:00 {"TuyaReceived":{"Data":"55AA00070005030100010010","Cmnd":7,"CmndData":"0301000100","DpId":3,"DpIdType":1,"DpIdData":"00"}}
10:03:00 TYA: fnId=13 is set for dpId=3
10:03:00 TYA: RX Relay-3 --> MCU State: Off Current State:Off
10:03:00 CFG: Saved to flash at F4, Count 16, Bytes 4096
10:03:04 {"TuyaReceived":{"Data":"55AA00070005030100010111","Cmnd":7,"CmndData":"0301000101","DpId":3,"DpIdType":1,"DpIdData":"01"}}
10:03:04 TYA: fnId=13 is set for dpId=3
10:03:04 TYA: RX Relay-3 --> MCU State: On Current State:Off
10:03:04 TYA: Send "55aa0006000501010001000d"
10:03:04 MQT: stat/lasmeigas/RESULT = {"POWER1":"OFF"}
10:03:04 MQT: stat/lasmeigas/POWER1 = OFF
10:03:04 SRC: Switch
10:03:04 MQT: stat/lasmeigas/RESULT = {"POWER3":"ON"}
10:03:04 MQT: stat/lasmeigas/POWER3 = ON
10:03:04 {"TuyaReceived":{"Data":"55AA0007000501010001000E","Cmnd":7,"CmndData":"0101000100","DpId":1,"DpIdType":1,"DpIdData":"00"}}
10:03:04 TYA: fnId=11 is set for dpId=1
10:03:04 TYA: RX Relay-1 --> MCU State: Off Current State:Off
10:03:04 CFG: Saved to flash at FB, Count 17, Bytes 4096
10:03:07 TYA: Send "55aa00000000ff"
10:03:07 {"TuyaReceived":{"Data":"55AA000000010101","Cmnd":0,"CmndData":"01"}}
10:03:07 TYA: Heartbeat
10:03:08 WIF: Checking connection...
10:03:08 WIF: Connected

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

select module 55 (tuya MCU), then:
backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4
backlog interlock 1,2,3,4; interlock on
power1 on
power2 on

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

relay1 shoud switch off (this happens) and relay2 switch on (but this fails)

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Interlock DOES work as expected when pushing buttons manually.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi, please, for more debug information, can you complete the template? STATUS 0 and the output of the console when you are performing those actions. Remember to set weblog to 4. Thanks.

**Comment by biotecov** [comment]
> ### PROBLEM DESCRIPTION
> 
> _A clear and concise description of what the problem is._
> 
> Tuya-MCU wall touch switch with 4 buttons, flashed with tasmota 7.1.1.1 and with 7.2.0.
> I selected module 55 (tuya MCU), then:
> backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4 (this activates successfully the four buttons)
> and finally
> backlog interlock 1,2,3,4; interlock onI selected module 55 (tuya MCU), then:
> backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4
> and finally
> backlog interlock 1,2,3,4; interlock on
> 
> Command "powerX on" on the console or mqtt activates relayX and ledX (as expected), but then, "powerY on" switches off relayX and ledX but fails to activate relayY and ledY. Issuing a second instance of "powerY" does the expected action.
> 
> Interlock works as expected with the touch pad, but not with commands: command "powerX on" on the console or mqtt activates relayX and ledX (as expected), but then, "powerY on" switches off relayX and ledX but fails to activate relayY and ledY. Issuing a second instance of "powerY" does the expected action.
> 
> In other words, interlock switches off the relay that was on, but fails to switch on the new relay via console or mqtt commands. This happens with any combination of X and Y (via commands) and for any interlock definition.
> ### REQUESTED INFORMATION
> 
> _Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_
> 
>     * [x]  Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
> 
>     * [x]  Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
> 
>     * [x]  Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
> 
>     * [x]  Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
> 
>     * [ ]  Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
> 
>     * [x]  Device used (e.g., Sonoff Basic): wall touch switch based on Tuya MCU
> 
>     * [ ]  Tasmota binary firmware version number used: 7.1.1.1 and 7.2.1
>       
>       * [ ]  Pre-compiled
>       * [x]  Self-compiled
>         
>         * [x]  IDE / Compiler used: Visual
> 
>     * [x]  Flashing tools used: tuya-convert
> 
>     * [x]  Provide the output of command: `Backlog Template; Module; GPIO 255`:
> 
> 
> ```
>   Configuration output here:
> ```
> 
>     * [ ]  If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
> 
> 
> ```
>   Rules output here:
> ```
> 
>     * [ ]  Provide the output of this command: `Status 0`:
> 
> 
> ```
>   STATUS 0 output here:
> ```
> 
>     * [ ]  Provide the output of the Console log output when you experience your issue; if applicable:
>       _(Please use_ `weblog 4` _for more debug information)_
> 
> 
> ```
>   Console output here:
> ```
> 
> ### TO REPRODUCE
> 
> _Steps to reproduce the behavior:_
> 
> select module 55 (tuya MCU), then:
> backlog tuyamcu 12,2; tuyamcu 13,3; tuyamcu 14,4
> backlog interlock 1,2,3,4; interlock on
> power1 on
> power2 on
> ### EXPECTED BEHAVIOUR
> 
> _A clear and concise description of what you expected to happen._
> 
> relay1 shoud switch off (this happens) and relay2 switch on (but this fails)
> ### SCREENSHOTS
> 
> _If applicable, add screenshots to help explain your problem._
> ### ADDITIONAL CONTEXT
> 
> _Add any other context about the problem here._
> 
> **(Please, remember to close the issue when the problem has been addressed)**

**Comment by biotecov** [comment]
Hello, I updated the info as you requested. On the log, look in particular at these:

at 10:01:47 I issued "power1 on" (physical result: led1 and relay1 turned on)
at 10:01:56 I issued "power3 on" (result: led1 and relay1 turned off, but led3 and relay3 remained physically off [=not correct])

at 10:03:00 I pushed manually button 1 (result: led1 and relay1 turned on)
at 10:03:04 I pushed manually button 3 (result: led1 and relay1 turned off, and led3 and relay3 turned on [=correct])

**Comment by Tommy-LSA** [comment]
Interlock seems not to set within a backlog queue. I‘ve seen this also. Setting it as solo command works

Von meinem iPhone gesendet

**Comment by biotecov** [comment]
@Tommy-LSA thanks for the clue, but I'm affraid is not my case. I tried that too, several times (activating interlock as a solo command too), and to be sure, I just repeated now the test before writing back, and results are the same. Interlock works in all cases for the touch pad but fails in all cases with commands.

In my working setup I am using "interlock 1,3 2,4" instead of "interlock 1,2,3,4" because I have dedicated this switch to control two shutters, and once more, the same is observed, again: buttons 1 and 3, and buttons 2 and 4 behave as expected from the touchpad, but fail with commands. I have implemented a work-around with rules that works well, but this is beyond the bug report. For the bug report I reset one of the devices and did exactly what is explained above.

Ricardo.

**Comment by biotecov** [comment]
@ascillato2 Hello, you marked this as "awaiting feedback". I wonder if you are still awaiting for more feedback from me. Maybe you did not notice that I completed all the missing info following your request. Please tell me if you want me to make more test. I am using a workaround but I believe what I reported is a bug in the communication between the ESP and the Tuya MCU.

**Comment by biotecov** [comment]
@ascillato2 Good year to all, and especially to the devels. This issue is a bug from my point of view, and can be a potential source of troubles for unaware users. Although I have solved the practical problem with a workaround that works for me, I believe it should not be closed without some attention from the devels.

**Comment by ascillato2** [comment]
@biotecov

Hi, any news on this? Have you tried latest version from development branch? Some fixes has been added to the codebase.

**Comment by ascillato2** [comment]
@biotecov

Hi, any news on this? Have you tried latest version from development branch? Some fixes has been added to the codebase.

Please, when you have time report back if your issue is solved. Thanks.
