### ISSUE TITLE
Set range for analog value with AdcParam

### ISSUE THREAD

**Issue by robin13** [arendst/Tasmota#7181]
I am using an analogue capacitive soil moisture sensor which outputs a voltage.  Reading using the Analog input on A0 I get a value between 720 (dry) and 200 (wet).  That's small subsection of the entire range 0 -> 1023, but also it is very difficult for me to represent in my head (or in a graph) how "wet" the soil is when I e.g. get the value 250 (quite wet).  What I would like is to be able to output the equivalent 0->100 reading.
I imagine this being configured with `AdcParam` something like:
```
AdcParam 4 200 720 100 0
```
Where 4 = Remap analogue values.
`<param1>` = lower limit
`<param2>` = upper limit
`<param3>` = value for lower limit
`<param4>` = value for upper limit

In the example I have deliberately set the value for upper limit to a number lower than the value for upper limit because in my example I want 0 to be "dry" and 100 to be "wet", so while `<param1>` should always be less than `<param2>`, `<param3>` and `<param4>` should just be a range where it is not important which is greater.
So going back to the example above, the value `250` would be:
```
int( ( ( (<param2> - <analogue-value>) / ( <param2> - <param1> ) ) * ( <param3> - <param4> ) ) + <param4> )
or
int( ( ( 720 − 250 ) ÷ ( 720 − 200 ) ) × (  100 − 0 ) ) + 0
= 90
```
So the result `90` (of 100) is much more meaningful than 250 as a measure of "wetness".

**Comment by effelle** [comment]
@robin13  `AdcParam` has not a setting for pure analog, is just for temperature and light. What you want is to scale the result using `scale` and a var.

`Syntax: SCALEx value, fromLow, fromHigh, toLow, toHigh` 

Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for **Tasmota software feature requests and bug reporting**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
