### ISSUE TITLE
Ruletimer1 doesn't work

### ISSUE THREAD

**Issue by BeatMaster** [arendst/Tasmota#7186]
Hello, 
i have on a SonOff Pow Tasmota 7.1.2.

I have these rules active.

rule1 on Energy#Power<10 do rule2 1 endon on Energy#Power>110 do rule2 0 endon

rule2 on Energy#Power<10 do ruletimer1 10 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxx endon

When the Energy drops below 10 the counter starts, but the websend doesn't start.

`20:50:38 RUL: ENERGY#POWER>10 performs "rule2 0"

20:50:38 RSL: RESULT = {"Rule2":"OFF","Once":"ON","StopOnError":"OFF","Free":337,"Rules":"on Energy#Power<9 do ruletimer1 10 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxxc endon"}

20:50:40 RUL: ENERGY#POWER>10 performs "rule2 0"

20:50:40 RSL: RESULT = {"Rule2":"OFF","Once":"ON","StopOnError":"OFF","Free":337,"Rules":"on Energy#Power<9 do ruletimer1 10 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxx endon"}

20:50:42 RUL: ENERGY#POWER>10 performs "rule2 0"

20:50:42 RSL: RESULT = {"Rule2":"OFF","Once":"ON","StopOnError":"OFF","Free":337,"Rules":"on Energy#Power<9 do ruletimer1 10 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxx endon"}

**Rule Change**

20:50:44 RUL: ENERGY#POWER<9 performs "rule2 1"

20:50:44 RSL: RESULT = {"Rule2":"ON","Once":"ON","StopOnError":"OFF","Free":337,"Rules":"on Energy#Power<9 do ruletimer1 10 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxx endon"}

20:50:44 RUL: ENERGY#POWER<9 performs "ruletimer1 10"`

But then the same message will repeat

`07:30:28 RSL: RESULT = {"Rule2":"ON","Once":"ON","StopOnError":"OFF","Free":234,"Rules":"on Energy#Power<10.0 do ruletimer1 9 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxxxxxxx; websend [maker.ifttt.com:80]/trigger/trockner4/with/key/xxxxxxxxxxx endon"}

07:30:28 RUL: ENERGY#POWER<10.0 performs "ruletimer1 9"

07:30:28 RSL: RESULT = {"T1":9,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}

07:30:30 RUL: ENERGY#POWER<10.0 performs "rule2 1"

07:30:30 RSL: RESULT = {"Rule2":"ON","Once":"ON","StopOnError":"OFF","Free":234,"Rules":"on Energy#Power<10.0 do ruletimer1 9 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxxxxxxx; websend [maker.ifttt.com:80]/trigger/trockner4/with/key/xxxxxxxxxxx endon"}

07:30:30 RUL: ENERGY#POWER<10.0 performs "ruletimer1 9"

07:30:30 RSL: RESULT = {"T1":9,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}

07:30:31 RUL: ENERGY#POWER<10.0 performs "rule2 1"

07:30:31 RSL: RESULT = {"Rule2":"ON","Once":"ON","StopOnError":"OFF","Free":234,"Rules":"on Energy#Power<10.0 do ruletimer1 9 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxxxxxxx; websend [maker.ifttt.com:80]/trigger/trockner4/with/key/xxxxxxxxxxx endon"}

07:30:31 RUL: ENERGY#POWER<10.0 performs "ruletimer1 9"

07:30:31 RSL: RESULT = {"T1":9,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}

07:30:33 RUL: ENERGY#POWER<10.0 performs "rule2 1"

07:30:33 RSL: RESULT = {"Rule2":"ON","Once":"ON","StopOnError":"OFF","Free":234,"Rules":"on Energy#Power<10.0 do ruletimer1 9 endon on rules#timer=1 do backlog websend [maker.ifttt.com:80]/trigger/trockner1/with/key/xxxxxxxxxxx; websend [maker.ifttt.com:80]/trigger/trockner4/with/key/xxxxxxxxxxx endon"}

07:30:33 RUL: ENERGY#POWER<10.0 performs "ruletimer1 9"`

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
