### ISSUE TITLE
Maximum power usage on a CWWW controller

### ISSUE THREAD

**Issue by titomontes** [arendst/Tasmota#7199]
### PROBLEM DESCRIPTION
Hello
I´m using an Arilux LC06 (RGBWW) controller, on Tasmota 7.1.2, but only using CW/WW, all working correctly in HA. Question is, if I mix both colors, I won´t get full light intensity, since in the mixdown both channels are lowered to 8.8-8.9V. Whe I try Setoption68, it IS possible to get 100% from both channels. I understand that this is so by design, to get as much brightness as with one color.
Question is: Is there a way to force full intensity with both channels preserving the use of a slider control for color mix and brightness in HA?

Thanks a lot

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Arilux LC06
- [ ] Tasmota binary firmware version number used: 7.1.2
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: OTA
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

16:52:02 MQT: stat/arilux2/RESULT = {"NAME":"Arilux LC06","GPIO":[17,255,255,255,9,40,255,255,38,39,255,41,37],"FLAG":0,"BASE":18}
16:52:02 MQT: stat/arilux2/RESULT = {"Module":{"0":"Arilux LC06"}}
16:52:02 MQT: stat/arilux2/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"9":"Switch1"},"GPIO5":{"40":"PWM4"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"38":"PWM2"},"GPIO13":{"39":"PWM3"},"GPIO14":{"0":"None"},"GPIO15":{"41":"PWM5"},"GPIO16":{"37":"PWM1"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

16:54:08 MQT: stat/arilux2/STATUS = {"Status":{"Module":0,"FriendlyName":["Encimera cocina"],"Topic":"arilux2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
16:54:08 MQT: stat/arilux2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"arilux","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"External System","Uptime":"0T00:22:42","StartupUTC":"2019-12-12T15:31:26","Sleep":50,"CfgHolder":4617,"BootCount":5,"SaveCount":44,"SaveAddress":"F8000"}}
16:54:08 MQT: stat/arilux2/STATUS2 = {"StatusFWR":{"Version":"7.1.2(tasmota)","BuildDateTime":"2019-12-06T11:22:22","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285"}}
16:54:08 MQT: stat/arilux2/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Montes01",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005AFF000000000000","00000000","00000000"]}}
16:54:08 MQT: stat/arilux2/STATUS4 = {"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
16:54:08 MQT: stat/arilux2/STATUS5 = {"StatusNET":{"Hostname":"arilux2-3191","IPAddress":"192.168.1.36","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"C4:4F:33:8F:8C:77","Webserver":2,"WifiConfig":4}}
16:54:08 MQT: stat/arilux2/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_8F8C77","MqttUser":"tito1","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
16:54:08 MQT: stat/arilux2/STATUS7 = {"StatusTIM":{"UTC":"Thu Dec 12 15:54:08 2019","Local":"Thu Dec 12 16:54:08 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:34","Sunset":"16:53"}}
16:54:08 MQT: stat/arilux2/STATUS10 = {"StatusSNS":{"Time":"2019-12-12T16:54:08","Switch1":"OFF"}}
16:54:08 MQT: stat/arilux2/STATUS11 = {"StatusSTS":{"Time":"2019-12-12T16:54:08","Uptime":"0T00:22:42","UptimeSec":1362,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Dimmer":100,"Color":"000000837C","HSBColor":"0,0,0","Channel":[0,0,0,51,49],"CT":322,"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"Montes01","BSSId":"34:97:F6:61:67:C0","Channel":11,"RSSI":94,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
Hello
I´m using an Arilux LC06 (RGBWW) controller, on Tasmota 7.1.2, but only using CW/WW, all working correctly in HA. Question is, if I mix both colors, I won´t get full light intensity, since in the mixdown both channels are lowered to 8.8-8.9V. Whe I try Setoption68, it IS possible to get 100% from both channels. I understand that this is so by design, to get as much brightness as with one color.
Question is: Is there a way to force full intensity with both channels preserving the use of a slider control for color mix and brightness in HA?

Thanks a lot

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
You can use `SetOption37 128` to decouple RGB and CW. Also `Color FFFFFFFFFF` forces all channels to max, if your power supply can handle it.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
