### ISSUE TITLE
Tasmota UI not accessible by browser

### ISSUE THREAD

**Issue by ackerschott** [arendst/Tasmota#7201]
Web UI is not accessible but API commands work.
Update via API not possible

here is the status 0 reply:

{"Status":{"Module":8,"FriendlyName":["Tannenbaum"],"Topic":"Tannenbaum","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"Drucker","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"url=https://github.com/arendst/Tasmota/releases/download/v7.1.2/tasmota-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:34","StartupUTC":"2019-12-12T19:06:31","Sleep":50,"CfgHolder":4617,"BootCount":374,"SaveCount":1554,"SaveAddress":"F9000"},"StatusFWR":{"Version":"6.7.1(sonoff)","BuildDateTime":"2019.10.26 13:25:04","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["ASUS","FritzBoxBalken"],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["54200009","2805C8000100060000005AFF000000000000","00000001"]},"StatusMEM":{"ProgramSize":564,"Free":436,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000407","8FDAE397","043683A0","22B617CD","01001BC0","0000F081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"},"StatusNET":{"Hostname":"Tannenbaum-6371","IPAddress":"192.168.1.66","Gateway":"192.168.1.250","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.250","Mac":"60:01:94:5D:D8:E3","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"192.168.1.5","MqttPort":1883,"MqttClientMask":"Tannenbaum","MqttClient":"Tannenbaum","MqttUser":"uwe","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Thu Dec 12 19:09:05 2019","Local":"Thu Dec 12 20:09:05 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:21","Sunset":"16:21"},"StatusSNS":{"Time":"2019-12-12T20:09:05"},"StatusSTS":{"Time":"2019-12-12T20:09:05","Uptime":"0T00:02:34","UptimeSec":154,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":45,"MqttCount":1,"POWER1":"ON","Wifi":{"AP":2,"SSId":"FritzBoxBalken","BSSId":"34:31:C4:2B:A9:2F","Channel":6,"RSSI":96,"LinkCount":1,"Downtime":"0T00:00:05"}}}

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
