### ISSUE TITLE
State of the switches as well as the state of the relay on the main web page

### ISSUE THREAD

**Issue by YaLiC** [arendst/Tasmota#7218]
**Have you looked for this feature in other issues and in the wiki?**  
yes i was looking

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
no, it's not a problem

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
I would like to see the state of the switches as well as the state of the relay on the main web page, in the case when the switches are not connected to the relay and are used in the rules

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Will not be done see #7193
