### ISSUE TITLE
reset a device that has no config

### ISSUE THREAD

**Issue by Chavell3** [arendst/Tasmota#7221]
HI,
I have a problem, that my flashed Blitzwolf BW-SHP2(first flashed to 6.6.0) are not reachable after an upgrade to the latest firmware via the plugs web interface.
I had installed the 6.6.0 release what was working some time and now wanted to upgrade to the 6.7.1 release but after the upgrade it seems the device has no config, as it is not reacting to the button press nor it is connecting to my wifi(what has worked before).
I've searched, how to reset the device so it would publish it's default wifi, but all I've read about are not working.
I tried fast poweron and poweroff 10 times, 4 times... but nothing changes...
Maybe some of you have an idea how to reset the device ?

Thanks.
BR Chavell3

**Comment by markolonius** [comment]
I have this same exact issue on 3 of my teckin sp20 smart plug switches.  Upgraded and reset by holding the button for 40 seconds.  Only to find it no longer responsive to anything.  These things are a pain to open and would rather avoid doing that.  Anyone has any ideas what changed from 6.6.0.9 to latest and if its possible to fix without doing serial flash.
