### ISSUE TITLE
reset a device that has no config

### ISSUE THREAD

**Issue by Chavell3** [arendst/Tasmota#7222]
### PROBLEM DESCRIPTION
my flashed Blitzwolf BW-SHP2(first flashed to 6.6.0) is not reachable after an upgrade to the latest firmware via the plugs web interface.
I had installed the 6.6.0 release what was working some time and now wanted to upgrade to the 6.7.1 release but after the upgrade it seems the device has no config, as it is not reacting to the button press nor it is connecting to my wifi(what has worked before).
I've searched, how to reset the device so it would publish it's default wifi, but all I've read about are not working.
I tried fast poweron and poweroff 10 times, 4 times... (what I have read somewhere) but nothing changes...
Maybe some of you have an idea how to reset the device ?

### REQUESTED INFORMATION
- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [wiki](https://github.com/arendst/Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Blitzwolf BW-SHP2
- [x] Tasmota binary firmware version number used: 6.6.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: 
- [x] Flashing tools used: tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
not applicable
  Configuration output here:
not applicable
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
not applicable
  Rules output here:
not applicable
- [x] Provide the output of this command: `Status 0`:
not applicable
  STATUS 0 output here:
not possible
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
not applicable
  Console output here:
not applicable

### TO REPRODUCE
not recommended

### EXPECTED BEHAVIOUR
after the update I thought the settings on the plug will remain...

### SCREENSHOTS
not applicable

### ADDITIONAL CONTEXT
Maybe some of you have an idea how to reset the device ?

**Comment by Jason2866** [comment]
Have you looked, if the device opens a AP?

**Comment by Chavell3** [comment]
yes that was one of the first thing I checked too, should have mentioned that.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
