### ISSUE TITLE
DS16xx temperature sensors

### ISSUE THREAD

**Issue by BASM** [arendst/Tasmota#7227]
**Have you looked for this feature in other issues and in the wiki?**  

Yes

**Is your feature request related to a problem? Please describe.**  
I can't use DS1624 and other DS16xx sensors.

**Describe the solution you'd like**  
I can add support for this, if no one does it and does not mind.

**Describe alternatives you've considered**  
Buy another sensors? booooo

**Additional context**  
I think to get the LM75AD as example, or give me a better example

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
> I can add support for this, if no one does it and does not mind.

Great. Please do a PR. If you need help, please just ask. Thanks

**Comment by BASM** [comment]
This is sensors support up to 8 devices on the i2c bus. This commit will be display only one device on the i2c bus. I did not understand how to make support for all devices, create 8 functions Xsns59 .. Xsns66 ??? Or how?

**Comment by ascillato2** [comment]
If you want, you can check the ds18x20 driver on how to implement that https://github.com/arendst/Tasmota/blob/development/tasmota/xsns_05_ds18x20.ino
