### ISSUE TITLE
SK6812 RGBW (similar to ws2812b) not working correctly after upgrade from 6.7.1 to 7.1.2

### ISSUE THREAD

**Issue by ameennihad** [arendst/Tasmota#7263]
After upgrade from **Tasmota 6.7.1 to 7.1.2**, my LED strip doesn't work as it used to be, the colors are not right, it seems that all RGB channels in each pixel are getting the same value (i.e. the color is always while), WW channel is always off, only 40 of the 60 LEDs can be controlled.

In the **user_config_override.h** file I have the following settings for both firmware versions:
#define USE_WS2812
#define USE_WS2812_CTYPE     NEO_GRBW

Pixels are 60 in both.
If I downgrade to 6.7.1 everything works fine.

I tried the following in 7.1.2 but with no effect:
- Added #define USE_WS2812_DMA to **user_config_override.h**
- Changed board_build.f_cpu to 160000000L in **platformio.ini**
- Changed #define USE_WS2812_HARDWARE to NEO_HW_SK6812 in **user_config_override.h**
- Changed #define USE_WS2812_CTYPE to NEO_RGBW in **user_config_override.h**

I checked the change log for all versions above 6.7.1 but I couldn't find any change related to this issue, btw my strip is connected to GPIO4 and I'm using generic ESP12 module.

**Comment by Jason2866** [comment]
DMA has never worked if you use GPIO 4!! DMA only works on GPIO 3. 
This is a ESP hardware restriction from ESP82xx. It is documented in my_user_config.h.
