### ISSUE TITLE
Add default sorting option to settings

### ISSUE THREAD

**Issue by uivc** [arendst/Tasmota#7276]
![2019-12-21_12-26-51](https://user-images.githubusercontent.com/5981561/71307368-927b5900-23ed-11ea-8cf6-2d76357369bf.png)

**Have you looked for this feature in other issues and in the docs?**  
Checked

**Is your feature request related to a problem? Please describe.**  
Sorting

**Describe the solution you'd like**  
Would be nice to be able to set the default sorting of the main device list in settings, especially sort by Name, e.g. of you got your devices named with Living Room *, Hallway *, etc. they all come in sequence.

**Describe alternatives you've considered**  
Checked settings and clicked headers

**Comment by Jason2866** [comment]
There is no device overwiew in Tasmota?!

**Comment by uivc** [comment]
> 
> 
> There is no device overwiew in Tasmota?!

Here's the default overview, I have 12 devices, but they're all sorted by the way I added them. Not sorted after name, like I would prefer to.

**Comment by Jason2866** [comment]
You dont have added a picture

**Comment by effelle** [comment]
Please close this issue and address this to the [TasmoAdmin](https://github.com/reloxx13/TasmoAdmin/issues) GitHub. 

Thanks.

**Comment by Jason2866** [comment]
This not Tasmota! This is a helper tool for Tasmota. NOT maintained here nor from the author of Tasmota. Please visit the site of the author @shantur  https://github.com/IOTReboot/TasUI/tree/master
Please close this issue because it is wrong here. Thx
