### ISSUE TITLE
Restore Configuration on first boot.

### ISSUE THREAD

**Issue by BASM** [arendst/Tasmota#7306]
**Have you looked for this feature in other issues and in the docs?**  

yes

**Is your feature request related to a problem? Please describe.**  

I can't fast deploy/restore configuration if reset. Resetting the configuration has become very easy.

**Describe the solution you'd like**  

Add "Restore Configuration" on first boot menu.

**Describe alternatives you've considered**  

I don't know. Do recovery in two steps? Not user friendly.

**Additional context**  

It became extremely important because of the default reset after 3 power cycles. 
You may reset  besauce of poor AC/DC. For example, I added 4 relay to Sonoff 4ch,
switch on 8 relays and got reset configuration after 2-5 minuts.

**(Please, remember to close the issue when the problem has been addressed)**  

Of course.

**Comment by ascillato** [comment]
You can disable the boot loop protection if you need with `setoption36` and `setoption65`.

The restore configuration is already there in the webUI menu of Tasmota as BACKUP and as RESTORE.

Besides, you can send by mqtt, serial, http or in the console, a `backlog` with all the config you need.

Also, you can put your settings as Default, using _user_config_override.h_ as explained in the docs.

If you need further assistance with any of the supported options, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by BASM** [comment]
Restore Configuration exist
![1](https://user-images.githubusercontent.com/157529/71421550-97aa0380-268c-11ea-9bca-76352ceb0dd4.png)

Restore Configuration don't exist
![2 png](https://user-images.githubusercontent.com/157529/71421591-f0799c00-268c-11ea-8267-a54520b187b9.png)

**Comment by BASM** [comment]
It have by main menu, but not on initial setup. Please reopen issue.

**Comment by ascillato** [comment]
Ah, ok, you want the **_restore configuration button_** on the **_AP menu_**.

From the AP menu you can access all Tasmota menus but using their actual address. For example, typing `http://192.168.4.1/rs?` on the browser will take you to the **restore config menu**. Also you can access the console etc etc.

Anyway, I like your request. Make totally sense to have that button. Will make a PR to add that button later on.

Thanks for sharing and explaining your ideas. Very appreciated. :+1:

**Comment by ascillato** [comment]
The PR #7314 has been submitted for revision.

**Comment by ascillato** [comment]
The PR #7329 has been submitted for revision.
