### ISSUE TITLE
A nice way to activate the unit's WAP if you make a mistake in the config

### ISSUE THREAD

**Issue by Just-another-pleb** [arendst/Tasmota#7313]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

Sorry folks.   I goofed with the previous effort.
My bad.

I recently bought a Bauhn power board which supports Tasmota.
It has 3 power points.

All is/was ok, but one day I nearly bricked it by mistake.
(That has since been resolved but in doing this, I thought of this suggestion)

Problem seen:
If you make a mess of the config and can't access the unit you are in trouble.
To access it, you have to turn off the existing WAP it uses before it will activate its WAP.

Suggestion:
The WAP to which it connects is not always nice/easy to turn off. Other things may be using it.
Though you would need initial access to the device when flashing it (which is a given) have an option which allows the board's WAP to be activated even if it sees the "main" WAP.
This could be easily done by LONG PRESSING the button.
I suggest that as there may be times when a normal pressing could turn a point on/off.
So a LONG PRESS could be a "sneaky way" of doing it.

That way if something messes up in the config, unplug the board; plug it in; LONG PRESS the button to activate the WAP; log into the board's WAP and board; edit/fix the problem.
The power cycle is maybe optional. I just included it as an option to help define events needed to happen before it allows this to happen.
Maybe after 3 minutes of power up this option is no longer available.
3 - a nominal time also configurable in the settings.

This way you don't need to turn off your WAP to get the board to turn on it's WAP.

Just a thought.

**Comment by ascillato** [comment]
Hi,

It is already implemented. Please read the docs or ask in the Tasmota Chat.

hint: 4 short presses.
