### ISSUE TITLE
Support for Iotty Smart Switch

### ISSUE THREAD

**Issue by AFUman** [arendst/Tasmota#7327]
I have collected some information about the iotty Smart Switch. Perhaps the information will help you to use Tasmota on it.
For one, there is an ESP-12S there as well
CY8C4245PVI-482 this is an MCU. I am enclosing photos of the circuit board, I hope this helps.
![IMG_20191225_164351](https://user-images.githubusercontent.com/28683249/71449959-97773a00-2758-11ea-9076-bcb582d0bba4.jpg)
![IMG_20191225_164357](https://user-images.githubusercontent.com/28683249/71449961-9b0ac100-2758-11ea-9b44-5b354f7f4686.jpg)
![IMG_20191225_164430](https://user-images.githubusercontent.com/28683249/71449965-9e9e4800-2758-11ea-8d9a-99a4f982c644.jpg)

**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
