### ISSUE TITLE
Sonoff mini custom switch

### ISSUE THREAD

**Issue by vanlooverenkoen** [arendst/Tasmota#7330]
I bought a sonoff mini because for testing my new project. This is what I want to do: I have 1 light bulb (philips hue) that is always connected to mains. This way I can still use the Philips Hue app to control my lights. I want to use the sonoff mini to use the switch to trigger a mqtt message. That message is captured by Home Assistant. and home assistant will perform certain actions on that mqtt message. For example: It is 7am. The light should turn on/off with 50% brightness. at 11am. the light should turn of/off with 100% brigthness. At 10pm the light should turn on/off. with 70% brightness and a warm color. .... I also want to register double/tripple clicks to handle different actions. Is this possible with tasmota? I used tasmota only for simple things with a sonoff basic. I want to use tasmota because of the easy configurability.

What I would like to see is the option to use the sonoff mini switch as a separate trigger. And make sure that the relay is always open. and never closed by the sonoff mini.

**Comment by ascillato** [comment]
That can be done using rules feature of Tasmota. Please check the docs, there are examples similar to what you are asking.

If you need further assistant on that, please address this to the Tasmota support chat. Thanks
