### ISSUE TITLE
Sonoff RF-Bridge no longer recognizes devices

### ISSUE THREAD

**Issue by erniecs** [arendst/Tasmota#7332]
### PROBLEM DESCRIPTION
_Ich habe meine Sonoff RF-Bridge mit Tasmota 8.1.0 upgedated seit dem Update erkennt die Bridge keine Werte von meinen Rauchmeldern und meiner Fernbedienung mehr. Mit der Firmware 6.7.1 hat noch alles Problemlos funktioniert. Wenn ein Rauchmelder auslöst oder ich einen Knopf auf der Fernbedienung drücker kommt immer nur "CMD:" aber es stehen keine Werte mehr dahinter._

GOOGLE TRANSLATE OF PROBLEM DESCRIPTION:

I have updated my Sonoff RF-Bridge with Tasmota 8.1.0 since the update the bridge no longer detects values from my smoke detectors and my remote control. Everything worked smoothly with firmware 6.7.1. If a smoke detector triggers or I press a button on the remote control, there is only "CMD:" but there are no values behind it.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff RF-Bridge
- [x ] Tasmota binary firmware version number used: 8.1.0
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

13:17:04 MQT: tele/sonoff/STATE = {"Time":"2019-12-26T13:17:04","Uptime":"0T16:30:11","UptimeSec":59411,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"xxxx","BSSId":"xx:xx:xx:xx:xx:xx","Channel":1,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:06"}}
13:20:44 CMD: 
13:20:44 CMD: 
13:20:44 CMD: 
13:20:44 CMD: 
13:20:44 CMD: 
13:22:04 MQT: tele/sonoff/STATE = {"Time":"2019-12-26T13:22:04","Uptime":"0T16:35:11","UptimeSec":59711,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"xxxx","BSSId":"xx:xx:xx:xx:xx:xx","Channel":1,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:06"}}

```

### TO REPRODUCE
_ the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Das Problem ist mit C50W Rauchmeldern so wie mit einer Sonoff RM433. Die Bridge erkennt das ein Befehl kommt, aber wie im Log zu sehen, werden keine Werte übertragen 

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Aejoh** [comment]
Same problem. I'm back to 7.1.2 so it still works.

**Comment by ascillato** [comment]
GOOGLE TRANSLATE OF PROBLEM DESCRIPTION:

I have updated my Sonoff RF-Bridge with Tasmota 8.1.0 since the update the bridge no longer detects values from my smoke detectors and my remote control. Everything worked smoothly with firmware 6.7.1. If a smoke detector triggers or I press a button on the remote control, there is only "CMD:" but there are no values behind it.

**Comment by rjduraocosta** [comment]
Same problem here also.

**Comment by arendst** [comment]
Provide output of commands ``status 0`` and ``serialconfig``

**Comment by Aejoh** [comment]
After a serial programming it works for me. (8.1.0)

**Comment by Jason2866** [comment]
With lastest commit https://github.com/arendst/Tasmota/commit/5682675ac9faa14c6a80c80f3754015191d88900it is fixed

**Comment by rjduraocosta** [comment]
> With lastest commit [5682675](https://github.com/arendst/Tasmota/commit/5682675ac9faa14c6a80c80f3754015191d88900it) is fixed

Tested just now and I can confirm that it is fixed.

Thanks a lot for your work.

**Comment by erniecs** [comment]
> Nach einer seriellen Programmierung klappt es bei mir. (8.1.0)

Kann ich bestätigen.
Danach von 8.1.0 auf 8.1.0.1 über OTA upgedatet und es läuft auch

**Comment by arendst** [comment]
So it was just caused by missed serial config data upgrade.

If users had execute serialconfig 8N1 and seriallog 0 once the issue was solved too
