### ISSUE TITLE
Wifi disconnect on some Sonoff devices

### ISSUE THREAD

**Issue by markusmainz** [arendst/Tasmota#7337]
Hello i use many Sonoff devies like pow dual and so on.

one of my 6 Sonoff dual R2 disconnects with newer firmware the latest version which is working without problems is 

And one of my Sonoff 4 CH pro has the same problem ... with firmwares above 
I reseted the devices and flashed new but the problem still appears.

`20:16:24 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:16:29 WIF: verbunden
20:16:29 MQT: Verbindungsversuch...
20:16:29 MQT: verbunden
20:16:29 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:16:29 MQT: cmnd/sonoff4ch1/POWER = 
20:16:49 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:16:54 WIF: verbunden
20:16:54 MQT: Verbindungsversuch...
20:16:54 MQT: verbunden
20:16:54 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:16:54 MQT: cmnd/sonoff4ch1/POWER = 
20:17:14 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:17:19 WIF: verbunden
20:17:19 MQT: Verbindungsversuch...
20:17:19 MQT: verbunden
20:17:19 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:17:19 MQT: cmnd/sonoff4ch1/POWER = 
20:17:37 MQT: Verbindungsversuch...
20:17:37 MQT: Verbindung fehlgeschlagen aufgrund von IP:1883, rc -2. Wiederversuch in 10 s
20:17:39 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:17:44 WIF: verbunden
20:17:54 MQT: Verbindungsversuch...
20:17:59 MQT: Verbindung fehlgeschlagen aufgrund von IP:1883, rc -2. Wiederversuch in 10 s
20:18:13 MQT: Verbindungsversuch...
20:18:13 MQT: verbunden
20:18:13 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:18:13 MQT: cmnd/sonoff4ch1/POWER = 
20:18:27 MQT: Verbindungsversuch...
20:18:27 MQT: verbunden
20:18:27 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:18:27 MQT: cmnd/sonoff4ch1/POWER = 
20:18:48 MQT: Verbindungsversuch...
20:18:48 MQT: verbunden
20:18:48 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:18:48 MQT: cmnd/sonoff4ch1/POWER = 
20:19:09 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:19:14 WIF: verbunden
20:19:14 MQT: Verbindungsversuch...
20:19:14 MQT: verbunden
20:19:14 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:19:14 MQT: cmnd/sonoff4ch1/POWER = 
20:19:34 WIF: verbinden mit AP2 ssid in Modus 11N als sonoff4ch1...
20:19:39 WIF: verbunden
20:19:39 MQT: Verbindungsversuch...
20:19:39 MQT: verbunden
20:19:39 MQT: tele/sonoff4ch1/LWT = Online (beibehalten)
20:19:39 MQT: cmnd/sonoff4ch1/POWER = 

Antwort von IP: Bytes=32 Zeit=11ms TTL=255
Antwort von IP: Bytes=32 Zeit=5ms TTL=255
Antwort von IP: Bytes=32 Zeit=4ms TTL=255
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Antwort von IP: Bytes=32 Zeit=5ms TTL=255
Antwort von IP: Bytes=32 Zeit=7ms TTL=255
Antwort von IP: Bytes=32 Zeit=3ms TTL=255
Antwort von IP: Bytes=32 Zeit=9ms TTL=255
Antwort von IP: Bytes=32 Zeit=5ms TTL=255
Antwort von IP: Bytes=32 Zeit=10ms TTL=255
Antwort von IP: Bytes=32 Zeit=5ms TTL=255
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Antwort von IP: Bytes=32 Zeit=3ms TTL=255
Antwort von IP: Bytes=32 Zeit=7ms TTL=255`

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
