### ISSUE TITLE
2gang dimmer flash to tasmota

### ISSUE THREAD

**Issue by Bajger-M** [arendst/Tasmota#7345]
Hi, I'd like to flash my dimmer on the tasmota. Could anyone help me? I can't figure out where to connect vcc, gnd, rx, tx ... and in what way. the older version was 4 holes but here are more

**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Bajger-M** [comment]
![81556653_10212152581930128_8193503819179491328_o](https://user-images.githubusercontent.com/56199312/71523386-112e3580-28c9-11ea-9804-fa03c8ffe4be.jpg)

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by DanyaFilatov** [comment]
Hi,
I have the same device.
It can be flashed using Tuya-Convert.
Pinout is presented on the image.
![IMG_20200111_202815-m](https://user-images.githubusercontent.com/18166483/73174590-69df3100-4108-11ea-9317-600e2a6930e4.jpg)

It looks pretty similar to the QS-WiFi-D01 150W Dimmer, excepting that here we have 2 dimming channels. Counters for buttons are on IO13 and IO5. Both channels shares the same UART TX, so it must use different command sequences.

Unfortunately I lost the original firmware during my experiments and can not sniff UART sequences anymore. It would be fantastic if somebody can send me this firmware.

**Comment by DanyaFilatov** [comment]
Do not forget that IO0 and both RE1 and RE2 pins shall be connected to GND in order to flash the chip using UART.
