### ISSUE TITLE
New 13A SP23 doesnt have a esp8266

### ISSUE THREAD

**Issue by jj-uk** [arendst/Tasmota#7363]
https://github.com/arendst/Tasmota/wiki/Teckin-SP23

The latest 13Amp version of the sp23 does not have power monitoring and does NOT contain a ESP8266.

They look different too. The 13A versions have a standoff on the pins.

Maybe this page should be updated to warn users not to buy the 13A version.

**Comment by meingraham** [comment]
The docs can be edited by users.
