### ISSUE TITLE
Led lamp resets after severa on off switches of the inline switch

### ISSUE THREAD

**Issue by blautob** [arendst/Tasmota#7384]
My wife is quite impazient and switches a lamp with an inline switch on the cable on and off several time if tasmota is not fast enough to boot up. This leads to the fact that the wifi settings seem to be reset and the wifimanager starts up again. 

Is there any command or setting to change this behaviour? (E.g. change the number of on/off switches to a higher number in order that the reset is executed)?

**Comment by Jason2866** [comment]
For this there is `SetOption65 1`
As explained in Documentation
