### ISSUE TITLE
MI Desk Lamp crashes

### ISSUE THREAD

**Issue by Sonne12** [arendst/Tasmota#7409]
I flased Tasmota 8.1.0.1 as a MI Desk Lamp. I can see the counter values in the serial log but after a few seconds of playing with the rotary encoder it crashes and restarts. After a few restarts Wifi is also dead and i need to reflash the firmware.

**Comment by pauldogg** [comment]
I am experiencing the same issue; what information can I provide to help?

**Comment by curt7000** [comment]
Same issue as well, running Tasmota 8.1
