### ISSUE TITLE
Connect failed to MQTT Broker (Mosquito)

### ISSUE THREAD

**Issue by beachie13** [arendst/Tasmota#7432]
Hi, 

I have the current version of Tasmota installed on a Tuya based device as of the 04/01/2020. I have a Sonoff based device that is up and running fine. 

The host name in MQTT configuration is correctly directed at the IP Address of the Home Assistant installation as per the below: 

![image](https://user-images.githubusercontent.com/59493924/71759084-9c27b500-2ef3-11ea-9caf-2a4c8f80fb39.png)

And shown on my router at 
![image](https://user-images.githubusercontent.com/59493924/71759098-c11c2800-2ef3-11ea-9d50-534ac6e6172f.png)

Mosquito is set with no login details and anonymous set as true.

However I receive the below error. 

00:00:00 CFG: Loaded from flash at FB, Count 27
00:00:00 Project tasmota Tasmota Version 8.1.0(tasmota)-2_6_1
00:00:00 WIF: Connecting to AP1 BAB2.4G in mode 11N as plug1-0225...
00:00:07 WIF: Connected
00:00:07 HTP: Web server active on plug1-0225 with IP address 192.168.1.106
04:04:08 MQT: Attempting connection...
04:04:08 MQT: Connect failed to 192.168.1.121:1883, rc 5. Retry in 10 sec

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
