### ISSUE TITLE
zigbee sensor autodiscovery in Home Assistant

### ISSUE THREAD

**Issue by chrisdaloa** [arendst/Tasmota#7439]
Hi, I installed Zigbee2Tasmota, I paired an AQARA Temp Sensor and it work. Now, there is a way to auto-discovery the sensor in Home Assistant? With command "SetOption19 on" I can auto-discovery the firmware data but not the Zigbee Sensor Data. Thanks

**Comment by Jason2866** [comment]
AD for Zigbee is NOT implemented

**Comment by reef-actor** [comment]
Is this due to resource limitations or is it just waiting for someone to have a go?

**Comment by Jason2866** [comment]
Someone has to do ;-)  
The author of the zigbee stuff dont use HA and has no HA knowledge.
