### ISSUE TITLE
Resolving wrong IP Address

### ISSUE THREAD

**Issue by ObiToo55** [arendst/Tasmota#7443]
Information button on Main Menu
AP1 SSId (RSSI)	Aruba (52%, -74 dBm)
Hostname	Leeslampje
IP Address	192.168.178.69
Gateway	192.168.178.1
Subnet Mask	255.255.255.0
DNS Server	192.168.178.1			<- should be 192.168.178.**5**
MAC Address	60:01:94:CB:FD:6E

So I entered the Console:
![afbeelding](https://user-images.githubusercontent.com/57967136/71780568-630b4580-2fc4-11ea-93db-3fef5ceb8207.png)

After hitting Enter the result will be:
![afbeelding](https://user-images.githubusercontent.com/57967136/71780574-8930e580-2fc4-11ea-8584-5b73796c87d4.png)

And the Information button on Main Menu again:
![afbeelding](https://user-images.githubusercontent.com/57967136/71780579-9cdc4c00-2fc4-11ea-8046-49fa5ce19e39.png)

I am using Program Version | 8.1.0(tasmota)

Is this a bug, or am I doing something wrong ?
BTW the same will happen trying to enter IPAddress2 (Gateway)

**Comment by Jason2866** [comment]
Your network setup is somewhere wrong. NOT a error in Tasmota.
Tasmota uses what has been told via DHCP

**Comment by 5chufti** [comment]
that was not the mistake, just omit the "=" when entering an ip
```
08:54:33 CMD: ipaddress4 = 10.254.11.253
08:54:33 RSL: RESULT = {"IPAddress4":"0.254.11.253"}
08:55:28 CMD: ipaddress4 10.254.11.253
08:55:28 RSL: RESULT = {"IPAddress4":"10.254.11.253"}
```
for the initial wrong DNS: it is not clear if they use dhcpd or antered the wrong DNS manually.
would be a nice feature to indicate using dhcp on info page.
