### ISSUE TITLE
Sonoff RF Programming Mode without bridging of R21

### ISSUE THREAD

**Issue by Szabos** [arendst/Tasmota#7444]
Hello,

I want to flash a Sonoff RF with Tastmota but I have one problem.

I soldered a cable on R21 to bridge them. My Sonoff fall from the table and I caught him on this cable. After that, the solder pads were torn out. So now I can´t bridge R21 anymore.

After a closer look at the PCB and the schematic, I think one contact of R21 will go to the small IC near to this pad. But where is the other contact pin going?

Or is there another solution to bridge R21 and bring the Sonoff RF in Programming Mode?

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
