### ISSUE TITLE
Consistent WiFi problems with v7 and v8

### ISSUE THREAD

**Issue by KDMcMullan** [arendst/Tasmota#7446]
### PROBLEM DESCRIPTION
When flashed with v7 or v8 TASMOTA, I am unable to reliably obtain and maintain a WiFi connection. Devices tried are:
Sonoff S20, Sonoff Basic, Sonoff T1, NodeMCU
Router: Sagemcom FAST5364

Further, with the S20 and T1, when I attempted to revert v8.1 back to 6.7.1 by OTA, I received a message to the effect that it had failed due to compatibility. (The Sonoff Basic did not show this behaviour: the OTA "downgrade" worked fine.) All considered, I suspect that  WiFi was the problem. Instead, I cable-flashed them to 6.7.1 and they are working perfectly.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): See list above
- [X] Tasmota binary firmware version number used: 8.2 and 7.1
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: ESPtool v2.6
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
rads01/stat/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
rads01/stat/RESULT = {"Module":{"1":"Sonoff Basic"}}
rads01/stat/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"4":"DS18x20"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}```
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
N/A
```
- [X] Provide the output of this command: `Status 0`:
```
rads01/stat/STATUS = {"Status":{"Module":1,"FriendlyName":["rads01"],"Topic":"rads01","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":2,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
```
- [X] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
When I experience the issue, there's no access to the console.
```

### TO REPRODUCE
Flash with TASMOTA 7.2 or 8.1.
Connect using TASMOTA inbuilt webserver
Enter WiFi username / password
Restart
Attempt repeatedly to connect by WiFi.

### EXPECTED BEHAVIOUR
I may or may not get a connection immediately. When I get the connection, there's a high propbabiliy that I'll loose it again in a few minutes.

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
Given that the forums are not inundated with people experiencing network problems with the v7 and v8 binaries, and the inconsistent nature of the problem, I'd guess that there is some particular inconsistency between the core and my router. Builds using core 2.2.2, core 2.5.2 and core 2.6.0 have always worked well for me. It's possible that core 2.6.1 is struggling with my modem.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
