### ISSUE TITLE
Can we have "console history" / "command history"?

### ISSUE THREAD

**Issue by g6094199** [arendst/Tasmota#7483]
**Have you looked for this feature in other issues and in the docs?**  
yes 

**Is your feature request related to a problem? Please describe.**  
no

**Describe the solution you'd like**  
It would be nice to have the console command history of lets say the last 20 commands so you can do copy n paste easier. And maybe, what be much better, have a click on the command in the history to copy the it automatically to the command field.

**Describe alternatives you've considered**  
manual copy n paste from a notepad :-(

**Additional context**

**Comment by ascillato** [comment]
Not enough memory for that. An esp8266 is very tiny and it doesn't have enough resources for that.
