### ISSUE TITLE
Poweronstate 3 not working as expected with on/off switch

### ISSUE THREAD

**Issue by multijohn** [arendst/Tasmota#7497]
### PROBLEM DESCRIPTION
_On power up Tasmota, relay goes at off position with classic on/off switch when the switch is in off position.
I notice that when cutting the power( in console), at capacitors discharge time, the state goes from on to off just before the module powering down.
setoption63 tested not solve
switchmode 0
poweronstate 3  _

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: 8.1.0
  - [ v] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
{"NAME":"QS-WIFI-S03","GPIO":[17,255,255,255,255,0,0,0,82,21,0,0,0],"FLAG":0,"BASE":1}
 {"Module":{"0":"QS-WIFI-S03"}}
 {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"82":"Switch1n"},"GPIO13":{"21":"Relay1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
19:48:36 CMD: Status 0
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS = {"Status":{"Module":0,"FriendlyName":["Tasmota"],"Topic":"Front_bedroom_ceiling_light_primary","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:28:07","StartupUTC":"2020-01-12T17:20:29","Sleep":50,"CfgHolder":4617,"BootCount":121,"SaveCount":592,"SaveAddress":"FA000"}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"388/699"}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["CONN-X","CONN-X"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00008200","00000000"]}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS5 = {"StatusNET":{"Hostname":"Front_bedroom_ceiling_light_pri","IPAddress":"192.168.204.226","Gateway":"192.168.204.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.204.1","Mac":"BC:DD:C2:A5:B1:0E","Webserver":2,"WifiConfig":4}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.204.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A5B10E","MqttUser":"admin","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS7 = {"StatusTIM":{"UTC":"Sun Jan 12 17:48:36 2020","Local":"Sun Jan 12 19:48:36 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+02:00","Sunrise":"09:40","Sunset":"18:16"}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS10 = {"StatusSNS":{"Time":"2020-01-12T19:48:36","Switch1":"OFF"}}
19:48:36 MQT: stat/Front_bedroom_ceiling_light_primary/STATUS11 = {"StatusSTS":{"Time":"2020-01-12T19:48:36","Uptime":"0T00:28:07","UptimeSec":1687,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"CONN-X","BSSId":"8C:E0:81:90:E8:6C","Channel":1,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Turn the power off when the relay status is on and the switch position is off (remote turn on) then 
connect the power again _

### EXPECTED BEHAVIOUR
_Relay should return to on position, turns to off_

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please update to latest Tasmota version from development branch

Thehackbox.org/tasmota

**Comment by multijohn** [comment]
I have updated to latest version, still no change , when power is lost and the switch is in off position the relay returns to off after power up!

**Comment by multijohn** [comment]
I think that one TOGGLE command is generated when the power fades (at power cut)!
some times i can see in console MQT power off before the connection lost, BUT must be publish , because i have tested with mqtt disconnected!
Also, another same module with same version but with momentary switch not having any issue!

**Comment by multijohn** [comment]
Upadate,
When the switch is in off position , relay not always starts at off position but toggles!
1st power on,relay starts at offposition 2nd maybe at off again, 3d at on, 4th at off position.
I thing that the switchmode 0 toggles when powering off and changes the poweronstate value.
Please advise.

**Comment by multijohn** [comment]
Is only me with this problem?

**Comment by multijohn** [comment]
I'm seeing responses to other issues, but not on this. You think that i am wrong and is hardware related issue?
Please someone advice , i don't remember had this with 6.7.1 on same hardware!

**Comment by multijohn** [comment]
Seem's to be fixed with version 8.1.0.3(338499d-tasmota)-2_6_1 thank you devs!
Closing

**Comment by multijohn** [comment]
It was better with yesterday's version, but not perfect!
Now i have locked out of the module and i mast reflash again!
After some power cycles tests suddenly it just not connicting anymore!
I will try 6.7.1 once again to tell for sure, as i remember that it hadn't that kind os issues!

**Comment by ascillato2** [comment]
> It was better with yesterday's version, but not perfect!
> Now i have locked out of the module and i mast reflash again!
> After some power cycles tests suddenly it just not connicting anymore!

In that case, it is better to address this in the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by multijohn** [comment]
Finaly, the problem comes from my hardware that works similar as shelly 1! When switch is closed (sw in to phase), input is high, and when the power fades becomes low and normally tasmota registers the status change just before power goes to 0 (capacitors discarded)!
I found some kind of working solution with switchmode 7 and some switchdebounce tweak ! 
Tasmota can cover many situations,
Thank you!

**Comment by multijohn** [comment]
Finaly, the problem comes from my hardware that works similar as shelly 1! When switch is closed (switch-in to phase), input is high, and when the power fades becomes low and normally tasmota registers the status change just before power goes to zero (capacitors discarded)!

May i ask why with Sleep 0 the problem is gone? Highest consumption of the esp? Can something done at the software side to prevent this with default Sleep 50?
Thank you!
