### ISSUE TITLE
Receive IR Command via MQTT

### ISSUE THREAD

**Issue by superwinni2** [arendst/Tasmota#7501]
**Have you looked for this feature in other issues and in the docs?**  
Yes, haven't found anything about it.

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
Make a MQTT "Item" where the last received IR Codes are send to?

**Describe alternatives you've considered**  

**Additional context**  
I want/need to receive also IR Codes via YTF IR Bridge and want so send them to my MQTT Broker.

For example: You can make your own "Universal Remote" and got a interface for IR <-> Network or anything like that.

**Comment by Jason2866** [comment]
It is implememted. Please read the documentation.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
