### ISSUE TITLE
Webservice sporadically unresponsive

### ISSUE THREAD

**Issue by aschmidt74** [arendst/Tasmota#7508]
### PROBLEM DESCRIPTION
MQTT and ping response is swift and 100% - but half of my sonoff basics randomly dont respond on http. This seems to have been an issue in earlier versions, but I am running the current v810 FW.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff Basic
- [ ] Tasmota binary firmware version number used: 8.1.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
similar to this (the device in question is inaccessible):
01:48:27 CMD: Backlog Template; Module; GPIO 255
01:48:27 RSL: stat/cleanair/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
01:48:27 RSL: stat/cleanair/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```

- [X] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
similar to this (the device in question is inaccessible):
01:52:08 CMD: Status 0
01:52:08 RSL: stat/cleanair/STATUS = {"Status":{"Module":1,"FriendlyName":["Luftbefeuchter"],"Topic":"cleanair","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
01:52:08 RSL: stat/cleanair/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Exception","Uptime":"0T01:46:40","StartupUTC":"2020-01-13T23:05:28","Sleep":50,"CfgHolder":4617,"BootCount":10,"SaveCount":22,"SaveAddress":"F6000"}}
01:52:08 RSL: stat/cleanair/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"377/699"}}
01:52:08 RSL: stat/cleanair/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["<deleted>",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000080","00000000"]}}
01:52:08 RSL: stat/cleanair/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
01:52:08 RSL: stat/cleanair/STATUS5 = {"StatusNET":{"Hostname":"tasmota-CleanAir","IPAddress":"192.168.6.101","Gateway":"192.168.6.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.6.1","Mac":"EC:FA:BC:07:71:D8","Webserver":2,"WifiConfig":4}}
01:52:08 RSL: stat/cleanair/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.6.55","MqttPort":1883,"MqttClientMask":"Luftbefeuchter","MqttClient":"Luftbefeuchter","MqttUser":"iobroker","MqttCount":4520,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
01:52:08 RSL: stat/cleanair/STATUS7 = {"StatusTIM":{"UTC":"Tue Jan 14 00:52:08 2020","Local":"Tue Jan 14 01:52:08 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:39","Sunset":"17:18"}}
01:52:08 RSL: stat/cleanair/STATUS10 = {"StatusSNS":{"Time":"2020-01-14T01:52:08"}}
01:52:08 RSL: stat/cleanair/STATUS11 = {"StatusSTS":{"Time":"2020-01-14T01:52:08","Uptime":"0T01:46:40","UptimeSec":6400,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":4520,"POWER":"ON","Wifi":{"AP":1,"SSId":"<deleted>","BSSId":"34:2C:C4:38:D1:EA","Channel":6,"RSSI":34,"Signal":-83,"LinkCount":2,"Downtime":"0T00:30:21"}}}
01:52:08 RSL: stat/cleanair/STATUS12 = {"StatusSTK":{"Exception":29,"Reason":"Exception","EPC":["4000df64","00000000","00000000"],"EXCVADDR":"00000000","DEPC":"00000000","CallChain":["4025bca7","4025bc3c","4025bbe3","4025ad44","4025ad6d","402587d8","40254b3d","4024d5ba","402594cf","40000f58","40258f42","40262693","40261f53","40000f49","40000f49","40000e19","40001878","40105865","4010586b","4010000d","40260e38","40260de9","401009b4","401024ac","4010575f","40103043","40103224","401036e6","4000050c","40103408","402466e1"]}}
```
### TO REPRODUCE
webservice on 5 devices comes and goes. not reproducible.

### EXPECTED BEHAVIOUR
meaningful http 200 response

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
