### ISSUE TITLE
Telemetry send via PowerDelta has "old" values

### ISSUE THREAD

**Issue by kintrupf** [arendst/Tasmota#7509]
### PROBLEM DESCRIPTION
I have set the "PowerDelta" on my Gosund plug to 110, so i'D expect a telemetry message when I get a change of 10 watts. I've attached a lamp with classic bulbs which draws around 160 Watts.
I would expect a telemetry message when I switch the plug on or off, since the power drawn changes by much more than 10 watts.
That in itself seems to work, I get a telemetry message each time the switch is toggled. However, the values reported are obviously the *old* values from before the toggle.

Switching on:
`09:49:06 MQT: plug02/stat/POWER = ON
09:49:06 MQT: plug02/stat/STATUS8 = {"StatusSNS":{"Time":"2020-01-14T09:49:06","ENERGY":{"TotalStartTime":"2019-12-13T00:08:28","Total":0.130,"Yesterday":0.017,"Today":0.043,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}`

Switching off:
`09:51:22 MQT: plug02/stat/POWER = OFF
09:51:22 MQT: plug02/stat/STATUS8 = {"StatusSNS":{"Time":"2020-01-14T09:51:22","ENERGY":{"TotalStartTime":"2019-12-13T00:08:28","Total":0.132,"Yesterday":0.017,"Today":0.046,"Power":166,"ApparentPower":185,"ReactivePower":81,"Factor":0.90,"Voltage":230,"Current":0.801}}}`

Sometimes I do get a reading of Power=0 when switching off, but not very often.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Gosund SP1 v23
- [X] Tasmota binary firmware version number used: 8.1.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
`09:47:43 MQT: plug02/stat/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
09:47:43 MQT: plug02/stat/RESULT = {"Module":{"55":"Gosund SP1 v23"}}
09:47:44 MQT: plug02/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"158":"LedLinki"},"GPIO2":{"0":"None"},"GPIO3":{"17":"Button1"},"GPIO4":{"134":"BL0937 CF"},"GPIO5":{"132":"HLWBL CF1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"131":"HLWBL SELi"},"GPIO13":{"56":"Led1i"},"GPIO14":{"21":"Relay1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}`
  Configuration output here:

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

`09:52:02 CMD: Status 0
09:52:02 MQT: plug02/stat/STATUS = {"Status":{"Module":55,"FriendlyName":["Plug02"],"Topic":"plug02","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
09:52:02 MQT: plug02/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://192.168.178.17:8082/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T21:00:59","StartupUTC":"2020-01-13T11:51:03","Sleep":50,"CfgHolder":4617,"BootCount":17,"SaveCount":146,"SaveAddress":"FB000"}}
09:52:02 MQT: plug02/stat/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":4,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"354/699"}}
09:52:02 MQT: plug02/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FKHOME",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
09:52:02 MQT: plug02/stat/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
09:52:02 MQT: plug02/stat/STATUS5 = {"StatusNET":{"Hostname":"plug02-2417","IPAddress":"192.168.178.42","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"DC:4F:22:EB:A9:71","Webserver":2,"WifiConfig":4}}
09:52:02 MQT: plug02/stat/STATUS6 = {"StatusMQT":{"MqttHost":"homeserver","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_EBA971","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
09:52:02 MQT: plug02/stat/STATUS7 = {"StatusTIM":{"UTC":"Tue Jan 14 08:52:02 2020","Local":"Tue Jan 14 09:52:02 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:39","Sunset":"17:18"}}
09:52:02 MQT: plug02/stat/STATUS9 = {"StatusPTH":{"PowerDelta":110,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
09:52:02 MQT: plug02/stat/STATUS10 = {"StatusSNS":{"Time":"2020-01-14T09:52:02","ENERGY":{"TotalStartTime":"2019-12-13T00:08:28","Total":0.132,"Yesterday":0.017,"Today":0.046,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
09:52:02 MQT: plug02/stat/STATUS11 = {"StatusSTS":{"Time":"2020-01-14T09:52:02","Uptime":"0T21:00:59","UptimeSec":75659,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"FKHOME","BSSId":"C0:25:06:DD:77:67","Channel":1,"RSSI":100,"Signal":-33,"LinkCount":1,"Downtime":"0T00:00:06"}}}`
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I would expect that the telemetry message reflects the power change that triggered it.
For example, if the watts go up from 0 to above the set treshold for powerdelta the resulting telemetry message should not read 0 watts.

Maybe the device should wait for a second before the telemetry message is sent to get a stable reading? On the web front-end the power reading takes a second or two before it changes after toggling the switch, but the telemetry message is send immediately with the old values.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
While trying to help you I see that in the first two message you show a status8 immediatly after the Power ON:
```
09:49:06 MQT: plug02/stat/POWER = ON 
09:49:06 MQT: plug02/stat/STATUS8 = {"StatusSNS":{"Time":"2020-01-14T09:49:06","ENERGY":{"TotalStartTime":"2019-12-13T00:08:28","Total":0.130,"Yesterday":0.017,"Today":0.043,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
```

Where does the ``status 8`` come from?

Normal behaviour is this:
```
16:19:44 MQT: stat/shp5/RESULT = {"POWER1":"ON"}
16:19:44 MQT: stat/shp5/POWER1 = ON
16:19:47 MQT: tele/shp5/SENSOR = {"Time":"2020-01-16T16:19:47","ENERGY":{"TotalStartTime":"2019-06-03T15:18:50","Total":15.118,"Yesterday":0.076,"Today":0.054,"Power":19.05,"ApparentPower":21.30,"ReactivePower":9.50,"Factor":0.89,"Voltage":226.0,"Current":0.094}}
```
Notice the three seconds time difference between the power ON and the sensor message. This time is used to calculate any power difference. As the energy sensors are slow you cannot expect to receive immediate results from either power, voltage or current.

To calculate power difference every second the current power is stored and within a three second window a difference related to ``PowerDelta`` setting will signal if a message will be returned. It is impossible to measure power difference in a smaller time frame.

Also power, voltage and current measuring is time related so expect a growing and declining value when applying and removing power. That's why the three second window is used too.

Bottomline, use the correct tools at the correct time.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
