### ISSUE TITLE
Cannot reach admin panel on AP1 after connecting AP2

### ISSUE THREAD

**Issue by berk-can** [arendst/Tasmota#7517]
I have specified two AP's one being home wifi other is temporary wifi, when my home wifi is turned off I am turning on temp wifi for fast action then close it (as home wifi takes time to turn on) I was doing this switch every day for 2 weeks, and today when I turn on my home wifi (being AP1) snoff basic has connected it, get IP address but I couldnt reach webserver, I closed AP1 and activated AP2, then everything worked seamlessly. To be sure I turned off AP2 and turned on AP1, tasmota has connected to it but again I couldnt reach to webserver.
What might be causing it?

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
