### ISSUE TITLE
Unable to turn on/off LG climate

### ISSUE THREAD

**Issue by adrianofoschi** [arendst/Tasmota#7520]
### PROBLEM DESCRIPTION
I'm using sonoff basic with ir transmitter diode to send IR signals to my tv, climate etc.
I'm using a receiver diode to capture the IR signals from the remote across tasmota console.
The procedure works perfectly with my tv but doesn't work with the climate.

### REQUESTED INFORMATION

The IR receiver codes from original remote control (sometimes I receive "LG" protocol signals, sometimes UNKNOWN...):
```
ON
10:25:25 MQT: tele/presa_libera/RESULT = {"Time":"2020-01-15T10:25:25","IrReceived":{"Protocol":"UNKNOWN","Bits":28,"Hash":"0x08800347"}}

OFF
10:26:06 MQT: tele/presa_libera/RESULT = {"Time":"2020-01-15T10:26:06","IrReceived":{"Protocol":"UNKNOWN","Bits":28,"Hash":"0x088C0051"}}
```
The IR receiver codes from an android remote app with my smartphone:
```
ON
11:48:10 MQT: tele/presa_libera/RESULT = {"Time":"2020-01-15T11:48:10","IrReceived":{"Protocol":"LG","Bits":28,"Data":"0x880325A"}}

OFF
11:48:31 MQT: tele/presa_libera/RESULT = {"Time":"2020-01-15T11:48:31","IrReceived":{"Protocol":"LG","Bits":28,"Data":"0x88C0051"}}
```
The restart reason if I use the original remote signals (with "Hash" instead "Data")
```
11:06:39 MQT: tele/presa_libera/INFO3 = {"RestartReason":"Fatal exception:28 flag:2 (EXCEPTION) epc1:0x402458c4 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}
```

```
### TO REPRODUCE
I'm using homeassistant mqtt.publish service to send the IR signal, and it works perfectly with my tv. If I send the IR with "hash" keyword via transmitter the sonoff-basic restarts.


### EXPECTED BEHAVIOUR
The sonoff should send the code and the climate turns on.

**Comment by Jason2866** [comment]
You have to use the Tasmota-IR version

**Comment by adrianofoschi** [comment]
I updated the issue with more details about the IR codes that I received from original remote or android app.

**Comment by Jason2866** [comment]
Please close. Solution is already explained and described (in Discord).

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
