### ISSUE TITLE
Show friendly names at web ui bottons

### ISSUE THREAD

**Issue by Pewibe** [arendst/Tasmota#7524]
**Have you looked for this feature in other issues and in the docs?**  yes

**Is your feature request related to a problem? Please describe.**  yes
_A clear and concise description of what the problem is._
At a multi relay device I often mix up the function of the individual relays.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
1. Instead of writing the first friendly name as only one in the headline of the web ui, Tasmota should write each friendly name to each button. See attached screenshot.
2. A friendly name "FriendlyName0" for the device should be allowed. See attached screenshot.
3. Color should be used for the buttons to indicate the status. For color handycapped people the status text can stay somehow. See attached screenshot.
4. Only if put hands on this issue you should think about the use of colors for the buttons. Today the red color of the Neustart / restart button under a couple of blue buttons sticks the user's eyes first to a button with lowest usage. All design guides say tha the most used button shoud be marked red (I guess this is setup or console). 

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._
![image](https://user-images.githubusercontent.com/42893315/72455504-2d840a80-37c3-11ea-8bca-3b12e5bdf63a.png)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
Try `WebButton<x> Description`

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
