### ISSUE TITLE
Shutter-openduration/closeduration measured via Shelly2.5 energiemeter.

### ISSUE THREAD

**Issue by kugelkopf123** [arendst/Tasmota#7528]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
As a owner of some Shelly2.5 devices that I use for my shutters, it would be nice if the calibration of the shutteropenduration & shuttercloseduration time is measured via the energiemeter. 
Ie: The shutter is fully open. You write into the console: "getShutterTime1" and the shutter closes. At the same time a seperate Timer starts or record the time when the shutter starts moving and the timer stops as the energiemeter isn't recognize energie anymore. The timer value gets safed as shuttercloseduration. After five seconds the Shutter fully opens and the same happens for shutteropenduration. Perhaps this is an Option. I don't know how fast the energiemeter recognize  powerchanges. 

**Describe alternatives you've considered**  
-

**Additional context**  
-

**(Please, remember to close the issue when the problem has been addressed)**  
Ok

**Comment by ascillato** [comment]
See https://github.com/arendst/Tasmota/issues/7509#issuecomment-575211932

As the power measurement takes time, it won't be enough fast to do a proper time calibration. Instead, you should use the calibration procedure explained in the docs.

Thanks for sharing your ideas.

**Comment by joba-1** [comment]
For reference:

my shelly 2.5 original firmware does automatic calibration like this. It somehow immediately detects endstops have cut power. So it is not a hardware limitation.
