### ISSUE TITLE
Wired humidity sensor compatible with the new Temperature Sensor Addon for Shelly 1/1PM?

### ISSUE THREAD

**Issue by Gamester17** [arendst/Tasmota#7529]
Does anyone know if there is a wired Humidity sensor like example Si7021 or AM2301 that is compatible that comes with the GPIO-adapter comes with the new Temperature Sensor Addon for Shelly 1/1PM?

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

Can I flash the Shelly 1/1PM with the latest Tosmota and then just connect a Si7021 or AM2301 sensor to a Shelly 1/1PM using their GPIO-adapter from that new Temperature Sensor Addon instead of a DS18b20 based temperature only sensor that Shelly sells for their addon?

I was hoping that Shelly themselves had plans to sell a nicely packaged Si7021 or AM2301-based wired humidity sensor would be compatible with their new GPIO-adapter for Shelly 1/1PM that comes in that Temperature Sensor Addon. 

The reason that I ask is that I have a (dumb) dehumidifier and been wanting to make smart and was wondering if could manage to do so with only a single all-in-one Shelly product that would support both electricity consumption measurement like the Shelly 1PM as well as be able to via its GPIO-ports to directly connect a wired humidity sensor like the Si7021 or AM2301 sensors similar to the ones that are sold by Itead for their Sonoff TH series.

Note! This is a feature request related #7469 and pre-sale question since I have not yet bought one.

PS: Sure I could use a Shelly 1PM and a separate wireless Humidity sensor and automate it that as a solution, but I think that having wired humidity sensor like Si7021 or AM2301 directly wired to Shelly 1PM and Shelly 1 would make for nicer integrated products.

**Comment by ascillato** [comment]
Duplicated issue. See it in already opened issues.
