### ISSUE TITLE
Beca thermostat questions (tuya)

### ISSUE THREAD

**Issue by multijohn** [arendst/Tasmota#7546]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
Tuya beca thermostat time.
I read in the wiki that thermostat is mainly supported by latest tasmota, and I'd like to ask if there is any method to pass the time when tasmota boots after ntp initial !
I found the following
https://github.com/arendst/Tasmota/wiki/tuya-protocols
BecaThermostat(WIP)
**Describe the solution you'd like**  
When tasmota boot's pass the time to thermostat

**Describe alternatives you've considered**  
Don't have programming skills to provide alternatives , just asking!

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
