### ISSUE TITLE
Allow for retaining int for mcp230xx (Sensor29)

### ISSUE THREAD

**Issue by MadDoct** [arendst/Tasmota#7553]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Allow for the mqtt int report message from mcp230xx to be retained, if powerretain is on...

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by cpha-pt** [comment]
That would be a welcomed feature!
