### ISSUE TITLE
Color calibration for Alexa...

### ISSUE THREAD

**Issue by mano1979** [arendst/Tasmota#7565]
I have existing wifi led strip control devices which I made myself and want to update them to tasmota.
However, the colors don't match up. Orange, the color we use most, is more a lime green.

I found this file: https://github.com/arendst/Tasmota/blob/a2e250f00881d36cc09e591f73b14b4c08bcbf27/lib/NeoPixelBus-2.5.0.09/src/internal/HtmlColorNames.cpp

and tried to adjust the color values in there to match the real time colors, but this makes no difference.
is there anything else I can try? It is only needed for control with an amazon echo device.

**Comment by s-hadinger** [comment]
Explore the light options here: https://tasmota.github.io/docs/#/Lights?id=light-options
