### ISSUE TITLE
Blind position error

### ISSUE THREAD

**Issue by fjramirez1987** [arendst/Tasmota#7574]
I have done all the steps to configure my blind but the slide bar is not located where it should be placed.

If I press up, I should go all the way. The bar does not reach the end, it stays at 10%.

In the console I could see a fluctuation in the position parameter. I have tried several versions of tasmot and the same thing happens. I am currently with 7.2.0.

This is my console log when I press up:

`14:16:46 RSL: stat/tasmota/RESULT = {"POWER1":"ON"}
14:16:46 RSL: stat/tasmota/POWER1 = ON
14:16:47 SHT: Shutter 1: Real. 100, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 0.05 [s], freq 0
14:16:47 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":0,"direction":1}}
14:16:47 SHT: Shutter 1: Real. 1600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 0.80 [s], freq 0
14:16:47 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:48 SHT: Shutter 1: Real. 3600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 1.80 [s], freq 0
14:16:48 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:49 SHT: Shutter 1: Real. 5600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 2.80 [s], freq 0
14:16:49 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":28,"direction":1}}
14:16:50 SHT: Shutter 1: Real. 7600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 3.80 [s], freq 0
14:16:50 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:51 SHT: Shutter 1: Real. 9600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 4.80 [s], freq 0
14:16:51 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:52 SHT: Shutter 1: Real. 11600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 5.80 [s], freq 0
14:16:52 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:53 SHT: Shutter 1: Real. 13600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 6.80 [s], freq 0
14:16:53 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:54 SHT: Shutter 1: Real. 15600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 7.80 [s], freq 0
14:16:54 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:55 SHT: Shutter 1: Real. 17600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 8.80 [s], freq 0
14:16:55 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:56 SHT: Shutter 1: Real. 19600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 9.80 [s], freq 0
14:16:56 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:56 RSL: stat/tasmota/RESULT = {"POWER1":"OFF"}
14:16:56 RSL: stat/tasmota/POWER1 = OFF
14:16:56 SHT: Shutter 1: Real. 20000, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 10.0 [s], freq 0
14:16:56 RSL: stat/tasmota/SHUTTER1 = 10
14:16:56 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":10,"direction":0}}`

**Comment by bjschuit** [comment]
This is a known bug in Tasmota ATM. It should be fixed in 8.1.1. 
See https://github.com/arendst/Tasmota/issues/7471
