### ISSUE TITLE
Blind position error

### ISSUE THREAD

**Issue by fjramirez1987** [arendst/Tasmota#7575]
### PROBLEM DESCRIPTION
I have done all the steps to configure my blind but the slide bar is not located where it should be placed.

If I press up, I should go all the way. The bar does not reach the end, it stays at 10%.

In the console I could see a fluctuation in the position parameter. I have tried several versions of tasmota and the same thing happens. I am currently with 7.2.0.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff Dual R2
- [X] Tasmota binary firmware version number used: 7.2.0
  - [ ] Pre-compiled
  - [X] Self-compiled
    - [X] IDE / Compiler used: GitPod
- [X] Flashing tools used: ESPEasy
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

4:16:46 RSL: stat/tasmota/RESULT = {"POWER1":"ON"}
14:16:46 RSL: stat/tasmota/POWER1 = ON
14:16:47 SHT: Shutter 1: Real. 100, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 0.05 [s], freq 0
14:16:47 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":0,"direction":1}}
14:16:47 SHT: Shutter 1: Real. 1600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 0.80 [s], freq 0
14:16:47 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:48 SHT: Shutter 1: Real. 3600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 1.80 [s], freq 0
14:16:48 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:49 SHT: Shutter 1: Real. 5600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 2.80 [s], freq 0
14:16:49 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":28,"direction":1}}
14:16:50 SHT: Shutter 1: Real. 7600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 3.80 [s], freq 0
14:16:50 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:51 SHT: Shutter 1: Real. 9600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 4.80 [s], freq 0
14:16:51 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:52 SHT: Shutter 1: Real. 11600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 5.80 [s], freq 0
14:16:52 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:53 SHT: Shutter 1: Real. 13600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 6.80 [s], freq 0
14:16:53 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:54 SHT: Shutter 1: Real. 15600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 7.80 [s], freq 0
14:16:54 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:55 SHT: Shutter 1: Real. 17600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 8.80 [s], freq 0
14:16:55 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":18,"direction":1}}
14:16:56 SHT: Shutter 1: Real. 19600, Start: 0, Stop: 20000, dir 1, motordelay 0, rtc: 9.80 [s], freq 0
14:16:56 RSL: tele/tasmota/RESULT = {"Shutter1":{"Position":8,"direction":1}}
14:16:56 RSL: stat/tasmota/RESULT = {"POWER1":"OFF"}
14:16:56 RSL: stat/tasmota/POWER1 = OFF

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, update to latest Tasmota (8.1.0.4) and address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
