### ISSUE TITLE
Baudrate ändern beim Zähler auslesen mit gemu2015/universal8

### ISSUE THREAD

**Issue by Kludi2019** [arendst/Tasmota#7576]
Hallo alle zusammen,

sorry, falls ich das jetzt, beim ersten mal, nicht richtig mache.....:-(

Ich nutze die gemu2015 Software Universal8, in der kompilierten Version 7.1.2.6 . Mein Zähler ist ein L+G ZMR120AReS2R2sfCS. Das ist ein Zähler, der zum Senden mit dem Syntax: /?! CR LF mit 300 Baud angeregt werden muss. Das funktioniert mit folgendem Script auch:

>B

=>sensor53 r

>M 1
+1,5,o,0,300,,16,20,2F3F210D0A,063030300D0A
1,0.0.1(@1,Zählernummer,,Meter_number,0
1,0.9.1(@#),Zeitstempel,Uhr,time-stamp,0
1,=h===================
1,1.8.0(@1,Gesamtverbrauch,KWh,Total_in,3
1,1.8.1(@1,HT_Verbrauch,KWh,HT_Total_in,3
1,1.8.2(@1,NT_Verbrauch,KWh,NT_Total_in,3
1,=h===================
1,36.7.0(@1,Leistung_L1,kW,kW_L1,2
1,56.7.0(@1,Leistung_L2,kW,kW_L2,2
1,76.7.0(@1,Leistung_L3,kW,kW_L3,2
1,16.7.0(@1,Leistung_L1+L2+L3,kW,kW_L1+L2+L3,2
1,=h===================
1,31.7.0(@1,Strom_L1,A,I_L1,2
1,51.7.0(@1,Strom_L2,A,I_L2,2
1,71.7.0(@1,Strom_L3,A,I_L3,2
#
Jetzt müsste eigentlich auf 9600 Baud umgestellt werden, damit die Aktualisierung nicht immer 73 Sekunden dauert. Es geht nur darum, aktuelle Änderungen im Netz zügig mitschreiben zu können.

Wie könnte ich nach dem Ansprechen des Zählers mit 300 Baud, auf 9600 umstellen? 

Leider sind meine Programmierkenntnisse nicht sehr groß, daher bitte ich hier um Unterstütung.

Vielen Dank im Voraus

Gruß
Gerhard

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
