### ISSUE TITLE
Setup Switch2 as stand alone

### ISSUE THREAD

**Issue by BBBits** [arendst/Tasmota#7590]
In an attempt to keep my HA simple , I have not employed any external logic .
Tasmota is controlled with Alexa via WeMo emulation.
Have recently got a few of the Sonoff Mini's & added another switch to the OTA jumper.
I also enabled KNX thinking it would be straight forward to use the extra switch to turn everything off as I left the room.
Simply enabling the GPIO as switch2 had the unexpected effect of having switch2 controlling Relay1 ?
This is where I see a Problem to report.
If I enable another pin as Relay2 , I can configure KNX to do what I want BUT Alexa Can No longer control the Light. ( Only one relay allowed I presume )
Any Idea how I can get this simple setup Working without a switch2 controlling Relay1 ?
Barry

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
