### ISSUE TITLE
Unique format for variables

### ISSUE THREAD

**Issue by Pewibe** [arendst/Tasmota#7593]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
I use the content of a VARx as information output inside rules, e.g. "Text%varx%". Setting "Var1 2" it shows "Text2". After "Sub1 1" it shows "Text1.000" which is not unique / not nice.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Maybe a "SetOptionX" to define number of trailing decimal places combined with selection of decimal character (english, german, ...) like
0 = show integer (default)
1 = show decimal point with 1 place (#.#)
2 = show decimal point with 2 place (#.##)
3 = show decimal point with 3 place (#.###)
11 = show decimal comma with 1 place (#,#)
12 = show decimal comma with 2 place (#,##)
13 = show decimal comma with 3 place (#,###)

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
No idea.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Already implemented. See docs for decimal precision, command CalcRes

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
