### ISSUE TITLE
Support for Sonoff Micro

### ISSUE THREAD

**Issue by saikek** [arendst/Tasmota#7620]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
This post is intended to store information about `Sonoff Micro` USB device.

**Describe the solution you'd like**  
It should be possible to use `Sonoff Micro` with Tasmota.

**Describe alternatives you've considered**  
Not Much.

**Additional context**  
There is a new chip CKW04 that was introduced by ITead guys. Support for Tasmota is unknown at this moment.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by saikek** [comment]
# Dissasembly
I've just received mine - in order to dissasemble it i had to scratch case all over. 
It seems everything is much simpler - you need really thin screwdriver to be inserted exactly where red marks are. Than it will un-snap and you can use another scredriwer to un-snap other sides.

![bottom](https://user-images.githubusercontent.com/1169207/73213685-e564d080-4150-11ea-9088-9cf124bc55ba.png)
![top](https://user-images.githubusercontent.com/1169207/73213687-e5fd6700-4150-11ea-9043-5eef0a451896.png)

**Comment by saikek** [comment]
# SPI connection
Board contains `V`, `G, `R`, `T` Pin group on one side 

and `LOG`, `R`, `T`, `RST` and button on the other. 

I've tried connecting my programmer to the device (3.3V), but default way of copying firmware does not work here  - not an ESP-compatible.
```
@esp_tool -pCOM12 -b115200 -a0x0000 -s0x100000 -or esp82XX.bin
```

**Comment by saikek** [comment]
More images of device:
![dissasembly](https://user-images.githubusercontent.com/1169207/73213973-8489c800-4151-11ea-984d-0414df42005c.png)
![bottom_pcb](https://user-images.githubusercontent.com/1169207/73213972-8489c800-4151-11ea-99bb-4feb2be4174a.png)

**Comment by meingraham** [comment]
@saikek 

Tasmota is only compatible with the ESP8266/ESP8285 Wi-Fi SoC. esp_tool is provided by Espressif to work with their chips. The Micro uses a different chip. Neither esp_tool nor Tasmota are supported on this chip.

**Comment by ascillato2** [comment]
Sorry, Tasmota only works on ESP8266 and ESP8285 devices.
