### ISSUE TITLE
Add support for Nokia 5110 Display (PCD8544 platform)

### ISSUE THREAD

**Issue by saikek** [arendst/Tasmota#7628]
**Have you looked for this feature in other issues and in the docs?**  
Yes, docs (displays section) and forum (1 similar entry).

**Is your feature request related to a problem? Please describe.**  
It would be great to support Nokia 5110 displays (SPI, PCD8544 platform)

**Describe the solution you'd like**  
Either update documentation with correct `DisplayModel` for his platform, or add another one.

**Describe alternatives you've considered**  
Not using display.

**Additional context**  
This is 4-pin SPI display with `84x48` screen resolution and blue backlight.

Connection seems to be very much similar to this particular [comment](https://github.com/arendst/Tasmota/issues/2557#issuecomment-444454436) or [issue](https://github.com/arendst/Tasmota/issues/2557#issuecomment-416267793)

I've used following connection:

| TFT Pin | Pin Name        | Node MCU (Wemos) Pin | Tasmota Config |
| ------- | --------------- | -------------------- | -------------- |
| RST     | Reset           | RST                  | ----           |
| CE      | chip select     | D8 (GPIO 15)         | SPI CS (66)    |
| DC      | Data/Command    | D0 (GPIO 16)         | SPI DC (67)    |
| Din     | Serial Data In  | D7 (GPIO 13)         | ----           |
| Clk     | Serial Clock    | D5 (GPIO 14)         | ----           |
| Vcc     | 3.3 voltage     | 3.3V                 | ----           |
| BL      | Backlight, 3.3V | D2 (GPIO 04)         | Backlight (68) |
| GND     | Ground          | Ground               | ----           |

And in code I have un-commented all directives related to SPI. Howevr none of selected DisplayModels does not show any test on screen.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing as nobody is working on this. If anyone is interested on working on this, please provide a PR. Thanks.
