### ISSUE TITLE
Gosund SP1 is "leaking" current when toggled off with Tasmota

### ISSUE THREAD

**Issue by thewavelength** [arendst/Tasmota#7629]
### PROBLEM DESCRIPTION
Measuring with a multimeter, the Gosund SP1 is "leaking" current up to 0.5 V while toggled off. This causes simple light bulbs to still light up a little bit.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): [Gosund SP1](https://github.com/arendst/Tasmota/wiki/Gosund-SP1)
- [x] Tasmota binary firmware version number used: 7.1.2.6
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
{"NAME":"Generic","GPIO":[0,158,0,17,134,132,0,0,131,56,21,0,0],"FLAG":0,"BASE":55}
{"Module":{"55":"Gosund SP1 v23"}}
{"GPIO0":{"0":"None"},"GPIO1":{"158":"LedLinki"},"GPIO2":{"0":"None"},"GPIO3":{"17":"Button1"},"GPIO4":{"134":"BL0937 CF"},"GPIO5":{"132":"HLWBL CF1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"131":"HLWBL SELi"},"GPIO13":{"56":"Led1i"},"GPIO14":{"21":"Relay1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
{"Status":{"Module":55,"FriendlyName":["Tasmota-5704"],"Topic":"tasmota-5704","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
{"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/tasmota-wifiman.bin","RestartReason":"Power on","Uptime":"0T00:15:54","StartupUTC":"2020-01-30T20:50:41","Sleep":50,"CfgHolder":4617,"BootCount":30,"SaveCount":78,"SaveAddress":"F5000"}}
{"StatusFWR":{"Version":"7.1.2.6(tasmota)","BuildDateTime":"2019-12-17T18:07:38","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"372/1151"}}
{"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["x",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
{"StatusMEM":{"ProgramSize":451,"Free":552,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0F400082","04048000","00000005","000000C0","00000080"],"Drivers":"1,2,3,4,9,10,12,16","Sensors":"1,2,3"}}
{"StatusNET":{"Hostname":"tasmota-5704-5704","IPAddress":"192.168.178.51","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.101","Mac":"24:62:AB:34:16:48","Webserver":2,"WifiConfig":2}}
{"StatusMQT":{"MqttHost":"x","MqttPort":1883,"MqttClientMask":"DVES_5704","MqttClient":"DVES_5704","MqttUser":"tasmota-5704","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
{"StatusTIM":{"UTC":"Thu Jan 30 21:06:35 2020","Local":"Thu Jan 30 22:06:35 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:23","Sunset":"17:43"}}
{"StatusSNS":{"Time":"2020-01-30T22:06:35","ENERGY":{"TotalStartTime":"2019-12-17T19:51:26","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
{"StatusSTS":{"Time":"2020-01-30T22:06:35","Uptime":"0T00:15:54","UptimeSec":954,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"x","BSSId":"x","Channel":1,"RSSI":82,"Signal":-59,"LinkCount":1,"Downtime":"0T00:00:06"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
Use multimeter and measure while device is toggled off.

### EXPECTED BEHAVIOUR
No "leaking" current should go through the SP1. Can this be fixed?

### ADDITIONAL CONTEXT
The status page of the SP1 shows 0 V. It seems like some sort of calibration is off.

**Comment by ascillato** [comment]
That is hardware issue. Can't be solved by software. Sorry.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
