### ISSUE TITLE
Blitzwolf BW-SHP7 template issue?

### ISSUE THREAD

**Issue by blueboi69** [arendst/Tasmota#7630]
Hi,
I'm trying to configure Blitzwolf BW-SHP7 with 
Program Version | 8.1.0(tasmota)
Core/SDK Version | 2_6_1/2.2.2-dev(38a443e).

Device flashed, calibrated. The relays are working fine, but I have a strange issue with the Power and Current values. The maximum Power value I can reach is 34W. I tried to hook on a light bulb with 23W and something else with 6W. I got a merged result, 29W. Current always arount 0.145-0.144A
But if I plug in something more power hungry it just displays 34W.
I have a soldering iron, 30W. If I switch it on, I get the result of 30W. If I switch the bulb and the soldering iron together, it should be 30+23=53W. But it displays only 34W.
If I plug in a vacuumcleaner, still 34W.

I have another Blitzwolf BW-SHP7 with the original firmware, that displays the results correct.

Can someone help?
Thanks!

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
