### ISSUE TITLE
Can't enable MQTT on Teckin SB50

### ISSUE THREAD

**Issue by tatsumara** [arendst/Tasmota#7648]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Whenever i'm trying to enable mqtt, the page reloads and displays "This site can't be reached."
The page reloads every now and again, with the same message and the light flickers.
It's trying to access a very long url, if i open the main page again after while it works again, but mqtt is disabled.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Teckin SB50
- [x] Tasmota binary firmware version number used: 8.1.0.5
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
{"NAME":"Teckin SB50","GPIO":[255,255,255,255,40,255,255,255,38,39,37,255,255],"FLAG":0,"BASE":18}
{"Module":{"0":"Teckin SB50"}}
{"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"40":"PWM4"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"38":"PWM2"},"GPIO13":{"39":"PWM3"},"GPIO14":{"37":"PWM1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
13:11:08 RSL: STATUS = {"Status":{"Module":0,"FriendlyName":["Yami"],"Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
13:11:08 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Hardware Watchdog","Uptime":"0T00:07:02","StartupUTC":"2020-02-02T12:04:06","Sleep":50,"CfgHolder":4617,"BootCount":110,"SaveCount":392,"SaveAddress":"F8000"}}
13:11:08 RSL: STATUS2 = {"StatusFWR":{"Version":"8.1.0.5(26cee00-tasmota)","BuildDateTime":"2020-02-01T21:00:20","Boot":7,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"319/699"}}
13:11:08 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Chloe-SM200",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028021","2805C8000100060000005AFF000000000000","00000000","00000000"]}}
13:11:08 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":569,"Free":432,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440C8","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
13:11:08 RSL: STATUS5 = {"StatusNET":{"Hostname":"Yami","IPAddress":"192.168.0.2","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"62.117.5.126","Mac":"3C:71:BF:3F:72:C6","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
13:11:08 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Feb 02 12:11:08 2020","Local":"Sun Feb 02 13:11:08 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:19","Sunset":"17:48"}}
13:11:08 RSL: STATUS10 = {"StatusSNS":{"Time":"2020-02-02T13:11:08"}}
13:11:08 RSL: STATUS11 = {"StatusSTS":{"Time":"2020-02-02T13:11:08","Uptime":"0T00:07:02","UptimeSec":422,"Heap":27,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":100,"Color":"255,0,0,255","HSBColor":"0,100,100","White":100,"Channel":[100,0,0,100],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"Chloe-SM200","BSSId":"34:2C:C4:1B:33:C6","Channel":11,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:10"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Ticking the checkbox next to Enable MQTT

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
MQTT being enabled.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
