### ISSUE TITLE
Suggestions for correcting errors in the documentation

### ISSUE THREAD

**Issue by kugelkopf123** [arendst/Tasmota#7658]
Not really a Feature Request more some corrections for the Docs.

Possibility to use Rules with JSON Array Payload eg:
`ENERGY":{"Power":[0,0],"ApparentPower":[0,0],"ReactivePower":[0,0],"Factor":[0.00,0.00],Current":[0.000,0.000]}`
Issue: #6160
Would be nice to find an explanation in the [rules](https://tasmota.github.io/docs/#/Rules?id=examples-of-available-triggers) section from the docs, how to get the first or second entry of this array from the Payload.
eg:
`rule1 on ENERGY#Current[1]>0.500 do backlog power1 0;power2 0; endon on ENERGY#Current[2]>0.500 do backlog power1 0;power2 0;endon`

BTW, would be nice if this rule got corrected in the [Shelly2.5](https://tasmota.github.io/docs/#/devices/Shelly-2.5?id=use-rules-to-control-shutter-endpoints) device documentation.

And in the "[Template](https://tasmota.github.io/docs/#/devices/Shelly-2.5?id=template)" section of this Device there is also an Error.
`Backlog SetOption1 1; SetOption11 1; SetOption32 1`

`Setoption32 1 `
is definitely too short for almost everything. I would suggest to "setoption32 20" and an information or Link to Setoption32 Command, so that the people know for what this option is. (Hold time)

Thanks for this great Project!

**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
no
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
You can do 😀 
Just click on top of the page on `Improve this article` and you can start a PR

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
