### ISSUE TITLE
Support of weather stations

### ISSUE THREAD

**Issue by valentapat** [arendst/Tasmota#7664]
How, or where I can add my contribution (in subject) ?
I have fully function support 433MHz weather station temperature sensors as 
LIDL Auriol, 
Sencor, 
pool WT 0122 
etc,   
verified on Wemos D1 mini.

**Comment by meingraham** [comment]
Is this a set of sensors attached to a D1 Mini? If it's a configuration that you set up as a template, you can add the template to the [repository](https://templates.blakadder.com/). If it involves a bit more "assembly", perhaps a new article for inclusion under [Cool Projects](https://tasmota.github.io/docs/#/Cool-Projects). You can also share your setup on the [Tasmota Discord](https://discord.gg/Ks2Kzd4) #Projects-Gallery.
