### ISSUE TITLE
WIFI unstable connection with tasmota 8.1 and core 2.6.1

### ISSUE THREAD

**Issue by mikroelektron** [arendst/Tasmota#7682]
I'm using Tasmota for long time, i have built an app to record and monitor the online/offline status of my hardware devices.. i have installed Tasmota on 5  different hardware devices and record data since 3 months ..recently, i have updated the firmware to all devices to 8.1 (core2.6.1).
The Result of three month of recording: each device turn on and off each day about 3-5 times. 
I note that the turning off period is about (10-50) seconds in 80% of all cases, some times that duration is in minutes. there is no case the offline duration exceed one hour. The number of total devices that connect with my router less than 10.
The strange behavior is when i see some device go offline for long period (minutes) ,  i cut the main power supply from the device and reconnect it again, after that it connects directly (less than 5 seconds), this happened with all cases that the offline period continued for minutes. 
I have read all information in Tasmota website about the WiFi issues, and i try all listed procedures. but until now the problem not solved.

**Comment by ascillato** [comment]
As the template is missing we can't help.

Please, try `reset 3` and then a power cycle.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
