### ISSUE TITLE
Button and led are not working

### ISSUE THREAD

**Issue by radinsky** [arendst/Tasmota#7689]
### PROBLEM DESCRIPTION
Button of this switch is not working,
toggling from web gui and mqtt works perfect,
please advise
Here's the switch I'm using:
https://www.aliexpress.com/item/33016227381.html

Tried all of Module types...

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): https://www.aliexpress.com/item/33016227381.html

- [x] Tasmota binary firmware version number used: Tasmota 8.1.0.2

  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: tuya convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
02:02:15 CMD: Backlog Template; Module; GPIO 255
02:02:15 MQT: stat/kitchen/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
02:02:15 MQT: stat/kitchen/RESULT = {"Module":{"10":"Sonoff Touch"}}
02:02:15 MQT: stat/kitchen/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
02:01:45 CMD: Backlog Rule1; Rule2; Rule3
02:01:45 MQT: stat/kitchen/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
02:01:45 MQT: stat/kitchen/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
02:01:45 MQT: stat/kitchen/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}

```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

01:58:48 MQT: stat/kitchen/STATUS = {"Status":{"Module":10,"FriendlyName":["Tasmota"],"Topic":"kitchen","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
01:58:48 MQT: stat/kitchen/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T07:27:40","StartupUTC":"2020-02-06T17:31:08","Sleep":50,"CfgHolder":4617,"BootCount":33,"SaveCount":144,"SaveAddress":"F4000"}}
01:58:48 MQT: stat/kitchen/STATUS2 = {"StatusFWR":{"Version":"8.1.0.2(tasmota)","BuildDateTime":"2019-12-30T19:07:34","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"314/699"}}
01:58:48 MQT: stat/kitchen/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wifiap",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
01:58:48 MQT: stat/kitchen/STATUS4 = {"StatusMEM":{"ProgramSize":452,"Free":548,"Heap":27,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0F400082","04048000","00000005","000000C0","00000080"],"Drivers":"1,2,3,4,9,10,12,16","Sensors":"1,2,3"}}
01:58:48 MQT: stat/kitchen/STATUS5 = {"StatusNET":{"Hostname":"kitchenwallswitch","IPAddress":"10.0.1.223","Gateway":"10.0.1.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.1.1","Mac":"2C:F4:32:B0:44:62","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
01:58:48 MQT: stat/kitchen/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.1.201","MqttPort":1883,"MqttClientMask":"kitchen","MqttClient":"kitchen","MqttUser":"userxxx","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
01:58:48 MQT: stat/kitchen/STATUS7 = {"StatusTIM":{"UTC":"Fri Feb 07 00:58:48 2020","Local":"Fri Feb 07 01:58:48 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:12","Sunset":"17:56"}}
01:58:48 MQT: stat/kitchen/STATUS10 = {"StatusSNS":{"Time":"2020-02-07T01:58:48"}}
01:58:48 MQT: stat/kitchen/STATUS11 = {"StatusSTS":{"Time":"2020-02-07T01:58:48","Uptime":"0T07:27:40","UptimeSec":26860,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"wifiap","BSSId":"64:A5:C3:65:2E:35","Channel":1,"RSSI":100,"Signal":-46,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
02:03:01 MQT: stat/kitchen/RESULT = {"WebLog":4}
02:03:02 CFG: Saved to flash at FB, Count 145, Bytes 4096

```

### TO REPRODUCE
Flash the switch with tasmota

### EXPECTED BEHAVIOUR
Button and led should work

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
