### ISSUE TITLE
Please Add a Option to Send ZbZNPReceived & ZbZCLReceived to MQTT

### ISSUE THREAD

**Issue by tcwj2008** [arendst/Tasmota#7693]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
no

**Describe the solution you'd like**  
Add a Option to send the ZbZNPReceived Rawdata and ZbZCLReceived json to MQTT

**Describe alternatives you've considered**  
read the debug log from MQTT

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
The problem is that enabling MQTT message for those message will swamp all users with raw data. These messages are only sent to logs with loglevel 3. One easy workaround would be to enable MqttLog at level 3. You will then receive `ZbZNPReceived` and `ZbZCLReceived` data.

**Comment by blakadder** [comment]
tuyamcu has a setoption to enable sending extra data so everyone has a choice

**Comment by s-hadinger** [comment]
Good point, I think I can reuse `SetOption66` for Zigbee as well. There is little chance that you have both Tuya MCU and Zigbee on same device and wanting different logging for both protocols.
