### ISSUE TITLE
Compilation error with Zigbee, scripts and FAT support.

### ISSUE THREAD

**Issue by JumpmanJunior** [arendst/Tasmota#7706]
### PROBLEM DESCRIPTION
Compilation error when enabling Zigbee, scripts and FAT support.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Lolin board
- [ ] Tasmota binary firmware version number used: not applicable
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: PlatformIO
- [ ] Flashing tools used: not applicable
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
not applicable

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
not applicable

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
not applicable

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
not applicable

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Compilation with USE_SCRIPT, USE_SCRIPT_FATFS and USE_ZIGBEE does not work. Output in attachment. Compilation without Zigbee or without FAT support works without problems.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Compilation with errors.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

[compilation.txt](https://github.com/arendst/Tasmota/files/4178057/compilation.txt)

**Comment by ascillato2** [comment]
Hi,

You are using an _old core_ for that. You need to use **latest STAGE core** or the **freezed STAGE version** for Tasmota.

rename **_platformio_override_sample.ini_** file to **_platformio_override.ini_** in order to use latest Arduino Core.

Doing that, you will activate the latest core as the override file states:

```ini
[core_active]
; Select one core set for platform and build_flags
;platform                  = ${core_2_6_1.platform}
;build_flags               = ${core_2_6_1.build_flags}

;platform                  = ${core_2_6_3.platform}
;build_flags               = ${core_2_6_3.build_flags}

platform                  = ${tasmota_core_stage.platform}
platform_packages         = ${tasmota_core_stage.platform_packages}
build_flags               = ${tasmota_core_stage.build_flags}

;platform                  = ${core_stage.platform}
;platform_packages         = ${core_stage.platform_packages}
;build_flags               = ${core_stage.build_flags}
```

If you need further assistance on that, please address this to the Tasmota support chat. Thanks.
