### ISSUE TITLE
Support for Brightness and Temperature Lights

### ISSUE THREAD

**Issue by DanielZimmer** [arendst/Tasmota#7708]
Have some Verve Design ACL04HA lights, they run a TYWE2L module and I'm testing swapping this out for an ESP-12.  They are Cool/Warm white lights and use 2 PWM Channels to control the lights but one channel is for brightness and the other channel is for colour temperature. 
ie. PWM1 = 100%
PWM2 = 0% 
is full bright, warm white

and PWM1 = 100%
PWM2 = 100%
is 100% full bright, cool white

This doesn't look to be a configuration option within Son-Off

**Comment by s-hadinger** [comment]
Hint: `Module 48`

https://tasmota.github.io/docs/#/Lights?id=pwm-ct
