### ISSUE TITLE
Support for Brightness, Colour Temperature on 2 PWM channels

### ISSUE THREAD

**Issue by DanielZimmer** [arendst/Tasmota#7709]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
I have some Verve Design ACL04HA lights, they run a TYWE2L module and I'm testing swapping this out for an ESP-12. They are Cool/Warm white lights and use 2 PWM Channels to control the lights but one channel is for brightness and the other channel is for colour temperature.
With the standard configuration they behave strange as Tasmota is expecting one channel to be warm white led and one channel cool white leds.

ie. PWM1 = 100%
PWM2 = 0%
is full bright, warm white

and PWM1 = 100%
PWM2 = 100%
is 100% full bright, cool white

This doesn't look to be a configuration option within Tasmota

**Describe the solution you'd like**  
Add a configuration option to allow PWM1 Brightness and PWM2 colour temperature

**Describe alternatives you've considered**  
Alternatively this could be a configuration option under option 37

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
You can control each pwm channels using channel command

**Comment by s-hadinger** [comment]
Hint: `Module 48`

https://tasmota.github.io/docs/#/Lights?id=pwm-ct

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
