### ISSUE TITLE
Adding Zerotier VPN would be awesome as hell

### ISSUE THREAD

**Issue by Damontir** [arendst/Tasmota#7712]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_no_

**Describe the solution you'd like**  
_adding my network name and boom -> iot-vpn_

**Describe alternatives you've considered**  
_nothing_

**Additional context**  
_http://zerotier.com_

**(Please, remember to close the issue when the problem has been addressed)**  

Hi!

i'm only a user and dont understand a lot of what you guys here doing, so my deep acknowledgement for what you do here. awesome work!

i just played around with Zerotier bc i need to vpn some devices in different locations and in both locations are a lot tasmota devices in use.

if i could add them into my zerotier vpn, it would make a biiiiiig improvement for me and maybe others like the idea as well.

Big regards
Robert

**Comment by ascillato2** [comment]
Hi,

Thanks for sharing your ideas, but a VPN uses a lot of RAM and it is not feasible to be implemented in a tiny microcontroller like the ESP8266 that have few bytes of RAM.

As explained in zerotier website, the VPN is aimed to be hosted in a RASPBERRY for example, and that device acts as a "BRIDGE" to connect to your devices on your LAN by VPN.

Closing as can't be implemented.
