### ISSUE TITLE
Display timezone information, current date and time, DST/ST rules and NTP server in Information screen

### ISSUE THREAD

**Issue by apastuszak** [arendst/Tasmota#7715]
I would like this information to be displayed in the Information screen, if it doesn't take up too much RAM to do it.

It would be helpful to have all of these set correctly.  To do that, you need to know what they are set for now.

**Comment by meingraham** [comment]
`Backlog NTPServer1;NTPServer2;NTPServer3;Timezone;TimeSTD;TimeDST`
