### ISSUE TITLE
Compile Timers to Tasmota firmware (in xdrv_09_timers.ino)

### ISSUE THREAD

**Issue by vencakratky** [arendst/Tasmota#7729]
### PROBLEM DESCRIPTION
Hello, I would like add 2 Timers direct to Firmware compilation. I wrote some Syntax with "Timer" in xdrv_09_timers.ino, but i have something bad. 
Please, can somebody help me, how should the syntax for 2 timers be correct? 
Or I write it to wrong file?
Now i have:
```
#ifdef USE_TIMERS
Timer1 {"Arm":1,"Mode": 1,"Window":0,"Days":"SMTWTFS","Repeat":1,"Output":1,"Action":1}
Timer2 {"Arm":1,"Mode": 2,"Window":0,"Days":"SMTWTFS","Repeat":1,"Output":1,"Action":0}
```
but this is incorrect

There is code from xdrv_09_timers.ino:
https://pastebin.com/jQpP78Zt  

THANK YOU.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Sonof Basic
- [ ] Tasmota binary firmware version number used: 8.1.0
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: Visual Studio Code
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
https://pastebin.com/jQpP78Zt

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Sorry, so far timers can't be defined at compiling time. There is no option for that.
