### ISSUE TITLE
add temperature calibration to ultrasonic sensors

### ISSUE THREAD

**Issue by mamrai1** [arendst/Tasmota#7731]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
Yes. low accurancy of ultrasonic sensor with temperature changes 

**Describe the solution you'd like**  
using a temperature sensor along with the ultrasonic and calibrate the range readings.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
Is it possible to calibrate/correct an ultrasonic sensor value by a temperature sensor?
ex. SR04T uses constant speedofsound at 15 Celsius of 340m/s.
and time=range*2/velocity

Using a formula like speedofsound= 331m/s+ (0.6*temp) will give a very higher accurancy!
and the reported range by the sensor will be:

New range = range/340 * (331+0.6*temp)

or can it be done with rules?
i see that it can't be done with rules because there is no DIV function? Only Add and Multiply?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
It can be done by rules. You have to enable the [expressions](https://tasmota.github.io/docs/#/Rules?id=expressions-in-rules) functions to have support for multiplication and division.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
