### ISSUE TITLE
Switching on/off mains power multiple times resets device

### ISSUE THREAD

**Issue by DoktorHeisenberg** [arendst/Tasmota#7735]
### PROBLEM DESCRIPTION
I have two LED Panels that can switch between multiple modes in brightness/light color. Switching the modes works like this:
Panel is in Mode 1 -> turning light switch off -> turning it on again within 3 seconds -> Panel is in mode 2

After the normal light switch and before the LED Panel I've installed a Sonoff Basic with Tasmota 8.1 flashed via serial. If I switch the built in relay on/off the light mode changes and everything is great. But if I set the default state of the relay to "on" and switch of the light switch more then 3 to 4 times so it also powers off the Sonoff, my device gets somehow factory resetted. It won't sign in into my WLAN anymore and the led is blinking. I have to press the button on the Sonoff 7 times to get the AP Mode and redo my configurations to get it back to work. 

At first I thought It's just an hardware issue. Then I bought a second LED Panel, also integrated it in the same setup above with another Sonoff Basic on 8.1 and I get the same problem again. After that, I thought maybe the hardware is just not made for fast power cycles, but I was curios. I have another lamp with a Sonoff Basic and an older firmware 6.5. I tried power cycling it with the default relay state configured to be on and...I just can't make it die. I switched it on/off like 10 times fast in a row and the module just works as expected.
I flashed the Sonoff devices with the old firmware 6.5 and the problem is gone. Like with my old lamp, I can power cycle the led panels fast without any problem. So somehow this seem to be a problem with newer firmwares only.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Sonoff Basic
- [ ] Tasmota binary firmware version number used: 8.1
  - [*] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
Power cycle sonoff basic fast (under 3 secs) multiple times in a row on firmware 8.1

### EXPECTED BEHAVIOUR
Devices just turns on again.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi, your issue is that you are using your device in a non standard way. Your sonoff basic was not meant to be used in series with your switch (see the schematic of installation in the sonoff basic manual). For your usecase (that you need to control a light from wifi and also from a switch with mains) it would be better to use a shelly 1 (https://Shelly.cloud)

If you don't want that and you want to take the risk of burning your sonoff basic because of the repetitive power cycles, you can disable the bootloop protection of Tasmota.
In the console type:
```yaml
Setoption65 1
Setoption36 0
```
For more information on these commands and features, please refer to the docs (http://tasmota.com)
Hope this helps. 

If you need further assistant on this, please address it to the Tasmota support [chat] (https://discord.gg/Ks2Kzd4). Thanks

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
