### ISSUE TITLE
global prefix in home assistant autodiscover mode (SetOption19 1)

### ISSUE THREAD

**Issue by bartplessers** [arendst/Tasmota#7741]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
I want to subscribe more specific to MQTT messages generated by tasmota in autodiscover mode (SetOption19 1)

**Describe the solution you'd like**  
It would be great to have a configurable general prefix, i.e. "sonoff", so I could subscribe to all my tasmota devices with just one wildcard, i.e.

`mosquitto_sub -d -h localhost -t sonoff/#`

**Describe alternatives you've considered**  
(n.a.)

**Additional context**  
(n.a.)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Already implemented. See grouptopic in commands in the docs.
