### ISSUE TITLE
PowerDelta gives unexpected behavior and wrong reporting

### ISSUE THREAD

**Issue by bartplessers** [arendst/Tasmota#7748]
### PROBLEM DESCRIPTION
Running 8.1.0.8(643d3d0-tasmota) on a Sonoff POW R2 device
Settings:
- PowerDelta 110
- TelePeriod 300

I expect changes in power consumption of more than 10W to be reported immediately.

However, If I place a light bulb of 50W (with manual switch) behind the POW R2 and switch it on/off (POW R2 stays always on)
- turn the bulb ON --> mqtt-reporting almost immediately
- turn the bulb OFF --> mqtt message takes sometimes more than 10 seconds before reporting
- turn the bulb ON again --> often it reports a lower power consumption, i.e. 9W in stead of 50W
After that you have to wait till TelePeriod expires. So in the worst case you have 5 minutes of wrong information...

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x ] Device used (e.g., Sonoff Basic): Sonoff POW R2
- [ x ] Tasmota binary firmware version number used: 8.1.0.8
  - [ x ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: ESPTOOL.EXE (http://www.letscontrolit.com/downloads/ESPEasy_R120.zip )
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
22:37:35 CMD: Backlog Template; Module; GPIO 255
22:37:36 MQT: tasmota-113/stat/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
22:37:36 MQT: tasmota-113/stat/RESULT = {"Module":{"43":"Sonoff Pow R2"}}
22:37:36 MQT: tasmota-113/stat/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"145":"CSE7766 Tx"},"GPIO2":{"0":"None"},"GPIO3":{"146":"CSE7766 Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ o ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
22:41:42 CMD: Backlog Rule1; Rule2; Rule3
22:41:43 MQT: tasmota-113/stat/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
22:41:43 MQT: tasmota-113/stat/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
22:41:43 MQT: tasmota-113/stat/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
22:38:31 MQT: tasmota-113/stat/STATUS = {"Status":{"Module":43,"FriendlyName":["Tasmota"],"Topic":"%hostname%","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:38:31 MQT: tasmota-113/stat/STATUS1 = {"StatusPRM":{"Baudrate":4800,"SerialConfig":"8E1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:24:25","StartupUTC":"2020-02-16T21:14:06","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2020-02-16T20:59:16","SaveCount":35,"SaveAddress":"F9000"}}
22:38:31 MQT: tasmota-113/stat/STATUS2 = {"StatusFWR":{"Version":"8.1.0.8(643d3d0-tasmota)","BuildDateTime":"2020-02-16T17:00:13","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"336/699"}}
22:38:31 MQT: tasmota-113/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["BEARFORCE-IoT",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C8000100068000005A00000000000000","00000000","00000000"]}}
22:38:31 MQT: tasmota-113/stat/STATUS4 = {"StatusMEM":{"ProgramSize":569,"Free":432,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
22:38:31 MQT: tasmota-113/stat/STATUS5 = {"StatusNET":{"Hostname":"tasmota-113","IPAddress":"192.168.3.113","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"A4:CF:12:B5:DB:47","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
22:38:31 MQT: tasmota-113/stat/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.bearforce.org","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_B5DB47","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
22:38:31 MQT: tasmota-113/stat/STATUS7 = {"StatusTIM":{"UTC":"Sun Feb 16 21:38:31 2020","Local":"Sun Feb 16 22:38:31 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"07:57","Sunset":"18:11"}}
22:38:31 MQT: tasmota-113/stat/STATUS9 = {"StatusPTH":{"PowerDelta":103,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
22:38:31 MQT: tasmota-113/stat/STATUS10 = {"StatusSNS":{"Time":"2020-02-16T22:38:31","ENERGY":{"TotalStartTime":"2020-02-16T20:59:16","Total":0.256,"Yesterday":0.000,"Today":0.256,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":235,"Current":0.000}}}
22:38:31 MQT: tasmota-113/stat/STATUS11 = {"StatusSTS":{"Time":"2020-02-16T22:38:31","Uptime":"0T00:24:25","UptimeSec":1465,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"BEARFORCE-IoT","BSSId":"F0:79:59:D4:11:24","Channel":6,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
see description

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
immediate mqtt reporting when power consumption changes more than defined in PowerDelta

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi, please search in issues. This has been addressed before several times. Thanks.

Duplicated issue
