### ISSUE TITLE
Counter1 value changed to previous value after electricity outage

### ISSUE THREAD

**Issue by jackkitley** [arendst/Tasmota#7766]
### PROBLEM DESCRIPTION
I have a "counter1" setup on a d1 mini. The counter works on a pulse from my water meter. Yesterday the counter was at 483. The electricity went off at 11pm last night for 2 hours and then again for 2 hours at 4am the next morning.

This morning the counter is now at 310. It has loaded an old value.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Wemos D1 Mini
- [ ] Tasmota binary firmware version number used: 8.1.0
  - [x ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: 
- [x ] Flashing tools used: Node MCU flasher OSX
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
08:51:17 MQT: stat/water_meter/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
08:51:18 MQT: stat/water_meter/RESULT = {"Module":{"18":"Generic"}}
08:51:18 MQT: stat/water_meter/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"42":"Counter1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

08:51:53 MQT: stat/water_meter/STATUS = {"Status":{"Module":18,"FriendlyName":["Water Meter"],"Topic":"water_meter","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
08:51:53 MQT: stat/water_meter/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"0T03:48:22","StartupUTC":"2020-02-21T04:03:31","Sleep":50,"CfgHolder":4617,"BootCount":10,"SaveCount":28,"SaveAddress":"F8000"}}
08:51:53 MQT: stat/water_meter/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2020-02-17T13:22:47","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"369/699"}}
08:51:53 MQT: stat/water_meter/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["3_stanley_road",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C8000000060000005A00000000000000","00000000","00000000"]}}
08:51:53 MQT: stat/water_meter/STATUS4 = {"StatusMEM":{"ProgramSize":567,"Free":436,"Heap":20,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashMode":3,"Features":["00000809","8FDAE397","003683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
08:51:53 MQT: stat/water_meter/STATUS5 = {"StatusNET":{"Hostname":"water_meter-6631","IPAddress":"192.168.88.38","Gateway":"192.168.88.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.88.1","Mac":"84:0D:8E:82:19:E7","Webserver":2,"WifiConfig":4}}
08:51:53 MQT: stat/water_meter/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.88.54","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_8219E7","MqttUser":"admin","MqttCount":3,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
08:51:53 MQT: stat/water_meter/STATUS7 = {"StatusTIM":{"UTC":"Fri Feb 21 07:51:53 2020","Local":"Fri Feb 21 08:51:53 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"07:48","Sunset":"18:19"}}
08:51:53 MQT: stat/water_meter/STATUS10 = {"StatusSNS":{"Time":"2020-02-21T08:51:53","COUNTER":{"C1":310}}}
08:51:53 MQT: stat/water_meter/STATUS11 = {"StatusSTS":{"Time":"2020-02-21T08:51:53","Uptime":"0T03:48:22","UptimeSec":13702,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"Wifi":{"AP":1,"SSId":"3_stanley_road","BSSId":"18:E8:29:64:5C:09","Channel":6,"RSSI":84,"Signal":-58,"LinkCount":2,"Downtime":"0T00:01:20"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

08:52:18 CFG: Saved to flash at F7, Count 29, Bytes 4096
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Im not sure how to reproduce

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

I expect the counter value to not change and to just count up.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
[https://imgur.com/a/hpbGAC8](url)

You can see from the above image, the electricity went off at 10pm to 12pm. it then went off again at 4am to 6am. After the 1st outage the value dropped from 2800 to around 1400.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
As designed. The counter value is stored in RAM, so in a power outage Tasmota will loose its value.

This cannot be stored in flash in order to reduce the flash burnout. The memory chip that uses the esp8266 has a limitation of 100.000 writes cycles before it fails. So in order to extend the life of the device, not everything is saved and also at a low frequency. For example, the power values are saved only at midnight.

As a workaround for you, you can use any automation software to store this data.
