### ISSUE TITLE
xdrv_13_display:26:22: error: renderer.h: No such file or directory

### ISSUE THREAD

**Issue by isokdz** [arendst/Tasmota#7782]
hi.i want to use USE_DISPLAY_SH1106 . But  i am getting this error

 
xdrv_13_display:26:22: error: renderer.h: No such file or directory

 #include <renderer.h>

                      ^

compilation terminated.

exit status 1
renderer.h: No such file or directory

**Comment by arendst** [comment]
Just veriefied. Compiles fine as long as you have downloaded the complete repository with all it's libraries.
