### ISSUE TITLE
Flash KingArt WiFi curtain Switch 

### ISSUE THREAD

**Issue by hisso538** [arendst/Tasmota#7815]
**Have you looked for this feature in other issues and in the docs?**  yes

**Is your feature request related to a problem? Please describe.**  its not a problem
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  help locate and flash the chip with tasmota, I have WiFi curtain Switch, KingArt, need to flash it with tasmota 
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  i have tried some pins on the board but couldnt reach boot flash
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  i will attach a picture of the motherboard
_Add any other context or screenshots about the feature request here._

![94f84a1a18b644cd099b5000f239ded0e5bf0cdb](https://user-images.githubusercontent.com/60488737/75605497-13d92100-5aec-11ea-950b-2e68bba8bacc.jpeg)
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
