### ISSUE TITLE
Tasmato supports just one relais?

### ISSUE THREAD

**Issue by ChangeTheCode** [arendst/Tasmota#7816]
Hi together,

I'm not sure if this is really an issue or it is more an question. I bought a Shelly 2.5 and I flashed the tasmota firmeware on it. Everything works fine expect in case I try to toggle the second relai. 

this won't work tasmato tell me via the UI this port should be on but the light does not turn on either there is a relai sound. 

Do I miss to change something in the Tasmato fireware or this this a sign that the hardware has a defect? 

Thanks is this the wrong place - please close this issue.

**Comment by ascillato2** [comment]
You need to tell TASMOTA which module are you using. Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
