### ISSUE TITLE
Teckin UK SP23 light doesn't stay on

### ISSUE THREAD

**Issue by mattydanby** [arendst/Tasmota#7818]
My SP23 was bought in late 2018 and Tasmota flash attempts v7.2.0-8.1.0 work but I'm unable to get the button light to stay on when the toggle is on.

I have also changed the BlitzWolf SHP (45) GPIOs to the values stated here: https://templates.blakadder.com/teckin_SP23.html

How can I now change to a v6 Tasmota version firmware as it seems I might have chosen a later version that isn't supported?

**Comment by ascillato2** [comment]
It is supported. You have some misconfiguration. Without the requested template, we don't have any information to help you so the bot automatically close your issue.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
