### ISSUE TITLE
ESW15-US help

### ISSUE THREAD

**Issue by temocastro** [arendst/Tasmota#7824]
I load the tasmota, tried the esw1 template but not exactly controlling the relay, had anybody tried?

**Comment by Shumphead** [comment]
@temocastro do u have a guide I can follow for flashing the ESW15?  I followed the information here https://tasmota.github.io/docs/Getting-Started/ and was able to get tasmota to flash to the device and it persist when I power cycle the 3.3v connection. However, when I plug it in to the wall it loads the stock firmware again... Do u have any idea what I am missing?

**Comment by temocastro** [comment]
Did you make the jumper to D0 to gnd? I believe I had to do that in order
to let it pass the programming

**Comment by Shumphead** [comment]
Thanks for the quick reply. Yeah I split the gnd wire to D0.  Tasmota is persisting on the plug. But it appears to be on a different partition that is booted only when it's in flash mode.  When I plug it into the wall it still has the stock firmware. Do you recall needing to do anything different from a standard flash? Tomorrow I will dig into the partitions and see if I need to flash it to one of the others.

**Comment by temocastro** [comment]
I will program another tomorrow and will take pictures and notes

**Comment by NeoMatrixJR** [comment]
Did this happen?  I'm also curious how to flash?  Can you use Tuya Convert and flash OTA or do you have to open it up?

**Comment by Shumphead** [comment]
Unfortunately, you need to open the device up. It's pretty easy. my problems went away when I tried it again. I still need to flash another plug and can do a mini writeup.
