### ISSUE TITLE
Double Ww,Wc pwm channels

### ISSUE THREAD

**Issue by Muszek1996** [arendst/Tasmota#7828]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
I made custom pcb to drive my bathroom led's where i have 2 zones with temperature adjustable white led strips.
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Additional remaping with SetOption37
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
Using 2 tasmota devices instead of 1
**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
This is not currently supported and there are no short term plans to support it. 

You can use `SetOption68 1` and manually control each channel.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
