### ISSUE TITLE
Have one switch control relay and one send MQTT signal.

### ISSUE THREAD

**Issue by SamPhoenix91** [arendst/Tasmota#7847]
I have a switch that controls the relay but after adding a door sensor I can't get the switch to control the relay but the door sensor to send an MQTT signal,

**Comment by ascillato** [comment]
Duplicated issue. Please search in issues as this has been addressed several times before. Also, check in the docs as there are examples on how to do that.
If you need further assistant, please address this to the Tasmota support chat. 
Thanks
