### ISSUE TITLE
Compile problem with both knx and sensors selected at the same time

### ISSUE THREAD

**Issue by Phonog** [arendst/Tasmota#7853]
### PROBLEM DESCRIPTION

I am compiling a custom version using gitpod. I need a version with sensors, knx, expressions and conditionals in rules. I have set the corresponding flags and/or #defines in the configuration files, and started the compilation. I get the following error :
/workspace/Tasmota/tasmota/xsns_59_ds1624.ino: In function 'void DS1624Show(bool)':
/workspace/Tasmota/tasmota/xsns_59_ds1624.ino:193:47: error: cannot convert 'char*' to 'float' for argument '2' to 'void KnxSensor(uint8_t, float)'
         KnxSensor(KNX_TEMPERATURE, temperature);
The function knxsensor() expects a float as the second argument, but the function ds1624show() passes a string as the second argument. It seems that some changes in knxsensor() have not been propagated to every caller, at least ds1624show().

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Dual R2
- [x] Tasmota binary firmware version number used: 8.1.0.10
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: Gitpod
- [x] Flashing tools used: EspEasy
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
N/A
  Configuration output here:

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
N/A
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
N/A
  STATUS 0 output here:

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
N/A
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Before compiling, select both "knx" and "sensors" options

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Compilation with no error

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/5046774/75889760-aef43280-5e2d-11ea-94be-5af5cb416ed7.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing this issue as it has been fixed.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
