### ISSUE TITLE
Tuya switch with Tasmota 8.1

### ISSUE THREAD

**Issue by irek74** [arendst/Tasmota#7869]
I've a smart switch (one touch button) from Ali with Tasmota firmware (flashed by me). Switch works fine with template Tuya MCU (54) but I need to change it's behaviour and I don't know how to do it. By touching the button once, I need the backlight of button to turn on and relay should be closed for about 500ms. After that time relay should by open and backlaight of the button should remain on. By touching the button for the second time, backlight of the button should turn off and relay must be closed for another 500ms and after that time the relay should be opened again. PulseTime command helps in relation to relay but it also changing state of the button's backlight. I need to controll relay and button's backlight separatelly. If you know how to do it (if it's even possible) I'll appreciate your support.
Regards
Irek

**Comment by ascillato** [comment]
Yes, that can be done with Tasmota. Please read the docs and then please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
