### ISSUE TITLE
Increase rules char limit

### ISSUE THREAD

**Issue by denisfrench** [arendst/Tasmota#7873]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
The current rule character limit (511 x 3 sets) might be more constraining than the actual processing or RAM limitations of an ESP8266.

Onboard processing of sensor outputs is preferable for critical applications (eg boiler temp control), but I am running up against the rule char limit to completely implement my use-case. 

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
A modest increase in the rule char limit, noting that with the currrent 511 x 3 sets almost full, Tasmota is still running fine and reporting 30kB of free memory.

Could this be allocated dynamically, somewhat like how the settings are now stored?

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
The boiler control must continue to work even if the internet or MQTT broker is down, hence offboard processing has been excluded.

I am already juggling individual rules between sets to fit within each 511 char limit.

I have done some code optimisation and re-use (using events similar to functions), but can't see any obvious further improvements I could make at this time.

**Additional context**  
_Add any other context or screenshots about the feature request here._
Note ESPEasy allocates 2048 x 4 sets of rules; this might be too much and invite issues due to RAM or processing limitations.

My use-case is currently working fine using ESPEasy on identical hardware to my test rig (reporting 13344 free mem), however I would like to switch to Tasmota due to MQTT over TLS, and other improvements.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
In addition to RAM it also eats Flash as you want to store your rules don't you. ESPEasy uses Spiffs (or FS as it is called these days) decreasing the amount of code flash space.

If rule space is tight try scripts for a change.
