### ISSUE TITLE
libraries for AC AUX

### ISSUE THREAD

**Issue by akdri** [arendst/Tasmota#7881]
**Have you looked for this feature in other issues and in the docs?**  
Hi, I have libraries to control the air conditioners of the AUX brand.
I don't know how to adapt these libraries to work with Tasmota.
Now I use these libraries to control my AC with ESP8266 connected to an SQL server
I attach the liberias in case someone could integrate them into Tasmota.

Thank you
[AUX_IR.zip](https://github.com/arendst/Tasmota/files/4308242/AUX_IR.zip)

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Tasmota uses the https://github.com/crankyoldgit/IRremoteESP8266 for IR devices
To get your device supported you have to open a feature request there.
