### ISSUE TITLE
GRV RFID 125

### ISSUE THREAD

**Issue by LiveSide** [arendst/Tasmota#7885]
**Have you looked for this feature in other issues and in the docs?**  
I used the search function. However, nothing found that helps me

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
I would like to integrate the GRV RFID 125 module and continue to use scanned RFID codes.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Der RFID-Code ist zu scannen. Dann für eine bestimmte Zeit angezeigt (variabel) und dann wieder entfernt.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
I have not considered any alternatives. I want to use RFID 125.
I also use a Wemos D1 mini and process the information in the IO broker.

**Additional context**  
_Add any other context or screenshots about the feature request here._
![image](https://user-images.githubusercontent.com/25540062/76297238-d298fc00-62b7-11ea-8ccf-a4995bd21304.png)

**(Please, remember to close the issue when the problem has been addressed)**  
all right

**Comment by Jason2866** [comment]
A similar module is already supported: RDM 6300
For reading NFC there is support for the PN 532.

There will be no driver written since there are alternatives for this uage.

If you want to have support for the module GRV RFID 125, you have to submit a PR.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
