### ISSUE TITLE
Tasmota cmnd/tasmota/status

### ISSUE THREAD

**Issue by LaBoss** [arendst/Tasmota#7898]
### PROBLEM DESCRIPTION
Good afternoon I have 10 shelly's with tasmota and I wanted to put the firmware verification on Homeassistant!

I have my topics configured like this:

In docs (https://tasmota.github.io/docs/#/integrations/Home-Assistant?id=useful-automations)  it says if post to topic  cmnd/tasmotas/STATUS with payload 2

Should receive a status on stat/tasmota/STATUS2

But I don't get anything

I tried to publish in the following topics

- shellies/luzes/entrada/cmnd/STATUS 
- shellies/luzes/cmnd/STATUS 
- shellies/cmnd/tasmotas/STATUS 
- shellies/cmnd/entrada/tasmotas/STATUS 
- shellies/cmnd/STATUS 

Another Question..Is there a way to publish on any topic and all the tasmotas updated via OTA Url??

Any Help?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Shelly 2.5
- [X] Tasmota binary firmware version number used: 8.1.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: espeasy
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
15:58:36 MQT: shellies/luzes/entrada/stat/RESULT = {"NAME":"Shelly 2.5","GPIO":[56,0,17,0,21,83,0,0,6,82,5,22,156],"FLAG":2,"BASE":18}
15:58:36 MQT: shellies/luzes/entrada/stat/RESULT = {"Module":{"0":"Shelly 2.5"}}
15:58:36 MQT: shellies/luzes/entrada/stat/RESULT = {"GPIO0":{"56":"Led1i"},"GPIO1":{"0":"None"},"GPIO2":{"17":"Button1"},"GPIO3":{"0":"None"},"GPIO4":{"21":"Relay1"},"GPIO5":{"83":"Switch2n"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"6":"I2C SDA"},"GPIO13":{"82":"Switch1n"},"GPIO14":{"5":"I2C SCL"},"GPIO15":{"22":"Relay2"},"GPIO16":{"156":"ADE7953 IRQ"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
```
- [X] Provide the output of this command: `Status 0`:
```
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS = {"Status":{"Module":0,"FriendlyName":["Tasmota","Tasmota2"],"Topic":"entrada","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"5T04:27:24","StartupUTC":"2020-03-07T10:32:00","Sleep":50,"CfgHolder":4617,"BootCount":17,"SaveCount":532,"SaveAddress":"F8000"}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"389/699"}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MyHome",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008029","2805C8000100060000005A00000000000000","00000000","00000000"]}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS5 = {"StatusNET":{"Hostname":"ShellyCorredorEntrada","IPAddress":"192.168.1.41","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"EC:FA:BC:C4:82:6D","Webserver":2,"WifiConfig":4}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.12","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C4826D","MqttUser":"devices","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS7 = {"StatusTIM":{"UTC":"Thu Mar 12 14:59:24 2020","Local":"Thu Mar 12 15:59:24 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"07:08","Sunset":"18:51"}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS10 = {"StatusSNS":{"Time":"2020-03-12T15:59:24","Switch1":"OFF","Switch2":"OFF","ANALOG":{"Temperature":46.1},"ENERGY":{"TotalStartTime":"2020-02-23T15:57:02","Total":2.127,"Yesterday":0.115,"Today":0.012,"Power":[0,10],"ApparentPower":[0,19],"ReactivePower":[0,2],"Factor":[0.00,0.54],"Frequency":50,"Voltage":235,"Current":[0.000,0.081]},"TempUnit":"C"}}
15:59:24 MQT: shellies/luzes/entrada/stat/STATUS11 = {"StatusSTS":{"Time":"2020-03-12T15:59:24","Uptime":"5T04:27:24","UptimeSec":448044,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"ON","Wifi":{"AP":1,"SSId":"MyHome","BSSId":"CC:19:A8:30:29:10","Channel":1,"RSSI":62,"Signal":-69,"LinkCount":1,"Downtime":"0T00:00:06"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
```

### TO REPRODUCE
Publish to cmnd/tasmota/status

### EXPECTED BEHAVIOUR
receive status on topic

### SCREENSHOTS
![Sem Título](https://user-images.githubusercontent.com/5363187/76532975-46c9d000-646f-11ea-8995-ac44a24555c8.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by lalo-uy** [comment]
cmnd/shellies/luzes/suite/STATUS
