### ISSUE TITLE
tx23 wind sensor isn't working

### ISSUE THREAD

**Issue by NBB07** [arendst/Tasmota#7902]
hello,
i'm happy to see, the tx23 will be supported.
i've enabled the support for this sensor in my_user_config and build the image for my wemos d1 mini pro.

there are only 2 sensors connected. 1x BME280 (D1 & D2) and tx23 (D5).
No sensor were recognized :-(
if the tx23 is not activated in my_user_config, the BME280 is working fine.

thanks for your great work!

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
