### ISSUE TITLE
Sunrise and Sunset times are off

### ISSUE THREAD

**Issue by mcguirepr89** [arendst/Tasmota#7918]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
The sunrise and sunset time for the latitude and longitude that I set are very wrong.
The sunrise and sunset times for the timezone which would correspond with those geo coordinates are also wrong.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): Sonoff Basic
- [x ] Tasmota binary firmware version number used: 8.1.0
  - [x ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x ] Flashing tools used: esptool
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
11:35:21 MQT: stat/standinglamp/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
11:37:14 MQT: stat/standinglamp/STATUS = {"Status":{"Module":1,"FriendlyName":["Tasmota"],"Topic":"standinglamp","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:37:14 MQT: stat/standinglamp/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:18:14","StartupUTC":"2020-03-14T17:19:00","Sleep":50,"CfgHolder":4617,"BootCount":11,"SaveCount":188,"SaveAddress":"F4000"}}
11:37:14 MQT: stat/standinglamp/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":7,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"339/699"}}
11:37:14 MQT: stat/standinglamp/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Tullulah 2.4GHz",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
11:37:14 MQT: stat/standinglamp/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
11:37:14 MQT: stat/standinglamp/STATUS5 = {"StatusNET":{"Hostname":"standingLamp","IPAddress":"192.168.0.106","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"C4:4F:33:8A:C9:75","Webserver":2,"WifiConfig":4}}
11:37:14 MQT: stat/standinglamp/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.107","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_8AC975","MqttUser":"openhabian","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
11:37:14 MQT: stat/standinglamp/STATUS7 = {"StatusTIM":{"UTC":"Sat Mar 14 17:37:14 2020","Local":"Sat Mar 14 11:37:14 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"-06:00","Sunrise":"00:05","Sunset":"12:11"}}
11:37:14 MQT: stat/standinglamp/STATUS10 = {"StatusSNS":{"Time":"2020-03-14T11:37:14"}}
11:37:14 MQT: stat/standinglamp/STATUS11 = {"StatusSTS":{"Time":"2020-03-14T11:37:14","Uptime":"0T00:18:14","UptimeSec":1094,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Tullulah 2.4GHz","BSSId":"B8:A3:86:4C:E7:AC","Channel":11,"RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

set latitude to 42.010679289210515
and longitude to 42.010679289210515,-87.67497539520265

see that the sunrise and sunset values in the timer are off by several hours

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

I expect the timer's sunrise and sunset values to correspond to those of the region indicated by the geo coordinates

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
The values for longitude and latitude are not valid

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
