### ISSUE TITLE
Relay Serial To MQTT

### ISSUE THREAD

**Issue by alfista2600** [arendst/Tasmota#7920]
Hi,

Please let me know if there is a better place to post this usage question. I'm trying to relay incoming serial commands to a MQTT Topic. I don't know if this is supposed to happen automatically, so:

I've built this rules thinking one would work - as entered into the console:
Rule1 ON SerialReceived#Data DO Publish moisture/sensor %value% ENDON

but it doesn't seem to...

#staysafeandcode

cheers

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
