### ISSUE TITLE
ESP-01 4Relays configuration help with tasmota

### ISSUE THREAD

**Issue by sparviero79** [arendst/Tasmota#7940]
Hello to all. I have recently flashed ESP-01 with the tasmota firmware V8.1.0 which is inserted in a 4 relay circuit, as in the photo attached below, but I can't get it to work. I tried with various guides that I found around, like this: https://github.com/arendst/Tasmota/wiki/LC-Technology-WiFi-Relay
but I can't get the relays activated. I hope I haven't flashed my ESP-01 in vain and have to burr it.
Thanks so much for your cooperation.

![Immagine](https://user-images.githubusercontent.com/43518843/76868725-9f321080-6867-11ea-944d-c98190c80eb9.jpg)

**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sparviero79** [comment]
![Immagine](https://user-images.githubusercontent.com/43518843/76868655-86295f80-6867-11ea-9653-06df95f1f7b6.jpg)

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
Have you tried https://templates.blakadder.com/LC-ESP01-4R-5V.html
