### ISSUE TITLE
wifi LED on sonoff POW R2 - strange behavior

### ISSUE THREAD

**Issue by kpalczewski** [arendst/Tasmota#7946]
### PROBLEM DESCRIPTION
blue LED isn't showing right status.
RED led is ok. it's off when it should, it's on when it should.
blue led blinks when it's connected for first time (I think should be solid), turned off when relay is off, turned on when it's connected AND relay is on (that's ok).

### REQUESTED INFORMATION

Sonoff POW R2
Firmware: Tasmota v8.1.0 Doris (Dec 25, 2019), release version (pre-compiled)
uploaded with esptool 2.1 (linux, binary)

`Backlog Template; Module; GPIO 255`:
the command doesn't work, I think I disabled all logs, because wiki said I should due to power monitoring.
`Status 0`:
same ^

### TO REPRODUCE
Flashed tasmota 8.1.0 to sonoff pow r2, connected with ios device, set up wifi (ssid, password), led is blinking, I can see sonoff device on my router.
Tried with 2 different sonoff pow r2 devices. same with every device.

### EXPECTED BEHAVIOUR
blue led is solid when connected, blinking when isn't, off when wifi is off / device is off.
blue led is independent from red led.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
