### ISSUE TITLE
IR Receive UNKNOWN

### ISSUE THREAD

**Issue by alexmc1510** [arendst/Tasmota#7958]
Hello all,

Actual configuration:
- Sonoff RF Bridge Hack to add IR emitter and receiver to PIN 4 and 5.
- Module: Sonoff Bridge
- GPIO4: IRreceive
- GPIO5: IRsend

Results:
I am able to read all the codes from IR and from RF but for IR almost 90% of my devices Samsung, LG tv don't appear as recoginized and gives me "UNKNOWN" protocol. So that, I can not reproduce this signals.
The only device that works fine is a NEC sound system. I can receive and send without any trouble.

Is there any way to increase this number of known protocols?

Thanks in advance,

**Comment by s-hadinger** [comment]
Yes. Use `Tasmota-IR` version. It supports many protocols
