### ISSUE TITLE
thehackbox dns not resolving

### ISSUE THREAD

**Issue by Wheaties466** [arendst/Tasmota#8000]
### PROBLEM DESCRIPTION
the dns record for thehackbox.org is coming back empty. I have tried from multiple networks and multiple public DNS servers, including root servers, and it doesn't seem to resolve.

dig thehackbox.org @8.8.8.8

; <<>> DiG 9.16.0 <<>> thehackbox.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 22822
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;thehackbox.org.			IN	A

;; Query time: 4033 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Mar 24 21:13:41 EDT 2020
;; MSG SIZE  rcvd: 43

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

This isn't a firmware related issue.
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
dig thehackbox.org @8.8.8.8

### EXPECTED BEHAVIOUR
the domain name to resolve to the server hosting the website and firmware.

### SCREENSHOTS

![image](https://user-images.githubusercontent.com/5346303/77491684-d7f85980-6e14-11ea-8c87-772199e44ede.png)

### ADDITIONAL CONTEXT
none

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Tested and it is up again.

Please, try again.
