### ISSUE TITLE
Unstable Wifi

### ISSUE THREAD

**Issue by tb205gti** [arendst/Tasmota#8023]
### PROBLEM DESCRIPTION
SonOff Bacic, Tasmota 8.2.0.
SI7021 on GPIO 14
Intermittent WiFi connection. Wifi is up 10 seconds, then down 10-15 seconds, then up 10 seconds and so on.

I have been running Tasmota on multiple devices for quite some time, but one of them keeps on acting up. I tried to reset back to standard, tried backups, tried other networks etc - but it stays the same. Unsure if this is a hardware issue or a sw issue. I think it could be a sw issue since the wifi is stable if there is continous traffic to the tasmota/sonoff. (eg. firmware upload). 
If sleep is disabled (sleep 0) - the connection is somewhat stable - it is up, but the occasional packet loss. If sleep is set to 150 - then it is stable..

- [ ] Provide the output of this command: `Status 0`:
```
20:47:44 MQT: stat/kaelderlys/STATUS = {"Status":{"Module":1,"FriendlyName":["Kaelderlys"],"Topic":"kaelderlys","ButtonTopic":"0","Power":1,"PowerOnState":0,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
20:47:44 MQT: stat/kaelderlys/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://catcams.dk/tasmota-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:10:38","StartupUTC":"2020-03-29T19:37:06","Sleep":50,"CfgHolder":4617,"BootCount":5,"BCResetTime":"2020-03-28T20:04:52","SaveCount":16,"SaveAddress":"F9000"}}
20:47:44 MQT: stat/kaelderlys/STATUS2 = {"StatusFWR":{"Version":"8.2.0(tasmota)","BuildDateTime":"2020-03-20T14:45:23","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"330/699"}}
20:47:44 MQT: stat/kaelderlys/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"MqttLog":0,"SysLog":1,"LogHost":"domus1","LogPort":514,"SSId":["CatCams","CatCams"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["54000008","2805C8000100060000005AFF000000000000","00000000","00000000"]}}
20:47:44 MQT: stat/kaelderlys/STATUS4 = {"StatusMEM":{"ProgramSize":577,"Free":424,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","000000CD","010013C0","C000F981","00000004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
20:47:44 MQT: stat/kaelderlys/STATUS5 = {"StatusNET":{"Hostname":"kaelderlys-1038","IPAddress":"192.168.0.99","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"2C:3A:E8:3B:C4:0E","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
20:47:44 MQT: stat/kaelderlys/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.16","MqttPort":1883,"MqttClientMask":"Kaelderlys","MqttClient":"Kaelderlys","MqttUser":"home","MqttCount":26,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
20:47:44 MQT: stat/kaelderlys/STATUS7 = {"StatusTIM":{"UTC":"2020-03-29T19:47:44","Local":"2020-03-29T20:47:44","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:32","Sunset":"19:16"}}
20:47:44 MQT: stat/kaelderlys/STATUS10 = {"StatusSNS":{"Time":"2020-03-29T20:47:44","SI7021":{"Temperature":23.8,"Humidity":33.1,"DewPoint":6.6},"TempUnit":"C"}}
20:47:44 MQT: stat/kaelderlys/STATUS11 = {"StatusSTS":{"Time":"2020-03-29T20:47:44","Uptime":"0T00:10:38","UptimeSec":638,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":26,"POWER1":"ON","Wifi":{"AP":1,"SSId":"CatCams","BSSId":"88:1F:A1:36:80:96","Channel":13,"RSSI":72,"Signal":-64,"LinkCount":26,"Downtime":"0T00:03:00"}}}
```

- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  
### TO REPRODUCE

Power on, enable sleep. (sleep 50)

### EXPECTED BEHAVIOUR
 A stable wifi connection..

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
