### ISSUE TITLE
WS2812B- long lines

### ISSUE THREAD

**Issue by BugsonPL** [arendst/Tasmota#8032]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Looks like Tasmota 8.2.0 official .bin FV has problem with handling bigger amount of LED's (in my case >=180), with ~20 LED Tasmota works fine.
The same hardware works fine with WLED firmware.
I have tried Wemos D1 mini and NodeMCU boards the same results Tasmota not working, WLED ok.

Maybe it is the meter of internal pull-up pin configuration.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Wemos D1 mini
- [x] Tasmota binary firmware version number used: 8.2.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: ESPEasy Flasher
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
18:01:37 RSL: stat/tasmota_EA44D0/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
18:02:54 RSL: stat/tasmota_EA44D0/RESULT = {"Module":{"18":"Generic"}}
18:07:22 RSL: stat/tasmota_EA44D0/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"158":"LedLinki"},"GPIO3":{"0":"None"},"GPIO4":{"7":"WS2812"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
18:10:09 RSL: stat/tasmota_EA44D0/STATUS = {"Status":{"Module":18,"FriendlyName":["NodeMCU"],"Topic":"tasmota_EA44D0","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:33","StartupUTC":"2020-03-30T17:09:36","Sleep":50,"CfgHolder":4617,"BootCount":13,"BCResetTime":"2020-03-30T14:14:43","SaveCount":37,"SaveAddress":"F7000"}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS2 = {"StatusFWR":{"Version":"8.2.0(tasmota)","BuildDateTime":"2020-03-20T14:45:23","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"348/699"}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Zdzislawa40",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS4 = {"StatusMEM":{"ProgramSize":577,"Free":424,"Heap":25,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","000000CD","010013C0","C000F981","00000004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS5 = {"StatusNET":{"Hostname":"tasmota_EA44D0-1232","IPAddress":"192.168.11.187","Gateway":"192.168.11.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.11.2","Mac":"68:C6:3A:EA:44:D0","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_EA44D0","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS7 = {"StatusTIM":{"UTC":"2020-03-30T17:10:10","Local":"2020-03-30T18:10:10","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:30","Sunset":"19:18"}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS10 = {"StatusSNS":{"Time":"2020-03-30T18:10:10"}}
18:10:10 RSL: stat/tasmota_EA44D0/STATUS11 = {"StatusSTS":{"Time":"2020-03-30T18:10:10","Uptime":"0T00:00:34","UptimeSec":34,"Heap":25,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":81,"Color":"8BCF38","HSBColor":"87,73,81","Channel":[55,81,22],"Scheme":0,"Width":1,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"Zdzislawa40","BSSId":"50:C7:BF:AF:B8:84","Channel":11,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
18:10:40 RSL: stat/tasmota_EA44D0/RESULT = {"WebLog":4}
18:10:41 CFG: Saved to flash at F6, Count 38, Bytes 4096
18:10:43 WIF: Checking connection...
18:10:49 HTP: Main Menu
18:10:51 SRC: WebGui from 192.168.11.108
18:10:51 CMD: Group 0, Index 1, Command "HSBCOLOR", Data "142"
18:10:51 RSL: stat/tasmota_EA44D0/RESULT = {"POWER":"ON","Dimmer":81,"Color":"38CF6F","HSBColor":"142,73,81","Channel":[22,81,44]}
18:10:52 SRC: WebGui from 192.168.11.108
18:10:52 CMD: Group 0, Index 2, Command "HSBCOLOR", Data "43"
18:10:52 RSL: stat/tasmota_EA44D0/RESULT = {"POWER":"ON","Dimmer":81,"Color":"76CF96","HSBColor":"142,43,81","Channel":[46,81,59]}
18:10:52 CFG: Saved to flash at F5, Count 39, Bytes 4096
18:10:54 SRC: WebGui from 192.168.11.108
18:10:54 CMD: Group 0, Index 1, Command "DIMMER", Data "8"
18:10:54 RSL: stat/tasmota_EA44D0/RESULT = {"POWER":"ON","Dimmer":8,"Color":"0B140F","HSBColor":"142,43,8","Channel":[4,8,6]}
18:10:54 CFG: Saved to flash at F4, Count 40, Bytes 4096
18:10:55 SRC: WebGui from 192.168.11.108
18:10:55 RSL: stat/tasmota_EA44D0/RESULT = {"POWER":"OFF"}
18:10:55 RSL: stat/tasmota_EA44D0/POWER = OFF
18:10:55 CFG: Saved to flash at FB, Count 41, Bytes 4096
18:10:56 HTP: Console
18:11:04 WIF: Checking connection...
18:11:24 WIF: Checking connection...

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Connect 180 WS2812B

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Hi, what is the output of command `Pixels` on the console?

**Comment by ascillato2** [comment]
Please, when you have time, tell us if the amount of pixels was correctly defined using pixels command. Thanks.

**Comment by BugsonPL** [comment]
Yes the amount of pixels was correctly defined.
