### ISSUE TITLE
How to delete/remove rules?

### ISSUE THREAD

**Issue by tpre** [arendst/Tasmota#8037]
I have a Gosund SP111 flashed with Tasmota 8.2.0 DE. I set a rule which accidently switches of 3 seconds after switching on. I was not able to find out how to delete this rule. Overwriting the rule or turning the rule of has had no effect. The only way was to reset the device.

**Comment by fabiosoft** [comment]
Same for me... how can i edit or remove a rule?

**Comment by meingraham** [comment]
https://tasmota.github.io/docs/Rules/#delete-rule

**Comment by fabiosoft** [comment]
Amazing! 
Thanks
