### ISSUE TITLE
Support for Shelly EM

### ISSUE THREAD

**Issue by ilgrank** [arendst/Tasmota#8055]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
It seems to me that Shelly EM isn't currently supported, even tho it should be using the same ADE7953 chip as the Shelly 2.5

**Describe the solution you'd like**  
Add support for shelly EM?

Many thanks!

**Comment by ascillato** [comment]
Hi,

As you are the one that owns that device, please, open it and post photos of the board.

**Comment by ascillato** [comment]
Then, if it has an ESP8266 chip and an ADE7953, you should backup the stock firmware (as explained in the docs) and then flash Tasmota. After that, you should test the GPIO outputs in order to make a new template (as explained in the docs). These steps are explained very well on the docs, but if you need further help you can ask here or in the Tasmota Support Chat.

**Comment by effelle** [comment]
@digiblur has/had one. 
He tested it with the stock firmware but I don't know if he changed the firmware.
On his [review](https://www.youtube.com/watch?v=pdo0IzpEEMI
) you can see the internals too.

**Comment by digiblur** [comment]
I did flash it later as well with Tasmota. I had some issues with the little relay if I remember right but I don't use it anyways. Let me see if I can find the template.

**Comment by ilgrank** [comment]
I have one indeed, but it is currently hooked up in a remote location, and so I cannot open it. I have read several times in the shelly support forum it should be using the same chip as the 2.5.

**Comment by ascillato2** [comment]
@ilgrank 

Hi, any news on this? Were you able to open it and takes some photos of the board?

**Comment by ilgrank** [comment]
@ascillato2 : we're in lockdown for Covid-19 here, but since there's photos of it it here https://www.youtube.com/watch?v=pdo0IzpEEMI
as @effelle had pointed out, I was thinking it was enough..

**Comment by djbx83** [comment]
Photos attacched.
![IMG_2136](https://user-images.githubusercontent.com/1845518/79069637-11174180-7cd0-11ea-8b70-3f128893fc78.jpg)
![IMG_2137](https://user-images.githubusercontent.com/1845518/79069640-12e10500-7cd0-11ea-9b46-ad2ac13cbc66.jpg)

**Comment by ilgrank** [comment]
Thanks @djbx83

**Comment by ascillato** [comment]
Great! Thanks.

So, seems that the only missing is just someone that has this device to flash it and test the GPIOs and make a template for it.

**Comment by digiblur** [comment]
Try this one.  Pinned it out a while back and got it working for the most part except the relay as it was acting weird from what I remember.

{"NAME":"Shelly EM","GPIO":[0,0,0,0,0,0,0,0,6,156,5,21,0],"FLAG":2,"BASE":18}

**Comment by djbx83** [comment]
ShellyEM doesn't use standard pins but they are much smaller... I can't understard what cable I've to use to connect my usb-ftdi... help me!

**Comment by digiblur** [comment]
Breadboard jumpers work fine.

**Comment by djbx83** [comment]
Sorry digiblur, but breadbord jumpers are slightly wider, and I can't insert wire in socket

**Comment by digiblur** [comment]
That's what I used to flash mine, mine were smaller than dupont male jumpers.

**Comment by ilgrank** [comment]
I have seen photos of people using stripped ethernet wires in that holes

**Comment by ascillato2** [comment]
Hi, Any news on this? Could you try the template from @digiblur ?

**Comment by ilgrank** [comment]
@ascillato2 : we're in lockdown for Covid-19 here, and so I can't move from home and as I wrote before, the EM is in a remote location.
As far as I know, there's no way of remotely flashing Tasmota to a Shelly,but please correct me if I'm wrong.
Will test it as soon as lockdown is lifted
Thanks!

**Comment by ascillato** [comment]
@ilgrank 
Hi, sorry, I forgot to tag. That message was intended to @djbx83

@djbx83 
Hi, Any news on this? Could you try the template from @digiblur ?

**Comment by djbx83** [comment]
I've used a small piece of ethernet cable @ascillato2 @ascillato as suggested by @ilgrank 
But..... unfortunatly I've bricked shelly and ftdi programmer... ooops!

**Comment by ilgrank** [comment]
@djbx83 : you tried to  flash it while it was mains powered?

**Comment by djbx83** [comment]
Yes @ilgrank .... LOL

**Comment by ilgrank** [comment]
@djbx83 whoops :(
You're lucky you didn't fry your USB ports then..

**Comment by ascillato2** [comment]
@djbx83 

> unfortunatly I've bricked shelly and ftdi programmer

Hi,

Your device is burnt? you couldn't reflash it? The only way to brick an ESP8266 is by applying more than 3.3V to VCC and GND pins.

Hope you weren't flashing with AC connected.

**Comment by ilgrank** [comment]
@ascillato2 : yes, he was flashing with mains connected, that's what he replied me on his last message

**Comment by Frigorio** [comment]
> 
> 
> Try this one. Pinned it out a while back and got it working for the most part except the relay as it was acting weird from what I remember.
> 
> {"NAME":"Shelly EM","GPIO":[0,0,0,0,0,0,0,0,6,156,5,21,0],"FLAG":2,"BASE":18}

Mmmm no, It doesn't look good to me...
![IMG_20200523_180840](https://user-images.githubusercontent.com/43074128/82735281-c05c2500-9d20-11ea-8306-c75c03e0f4b7.png)

**Comment by Frigorio** [comment]
Ok, changed analog to user (15) and now **if the relay is on** the meter is working...

![immagine](https://user-images.githubusercontent.com/43074128/82740107-e0eaa600-9d45-11ea-97d2-67172918dea6.png)

**Comment by ascillato** [comment]
@Frigorio 

Great!!! Thank you very much for testing and sharing the template.

Can I ask you one little favour? Can you please add this template to the Template repository? https://templates.blakadder.com/new.html

Thanks.

**Comment by Frigorio** [comment]
> Ok, changed analog to user (15) and now **if the relay is on** the meter is working...

Stupid me... SetOption21 was OFF 🤣 


> Can I ask you one little favour? Can you please add this template to the Template repository?

Sure!

**Comment by ilgrank** [comment]
@Frigorio 
 
> > Ok, changed analog to user (15) and now **if the relay is on** the meter is working...
> Stupid me... SetOption21 was OFF 🤣

So now the meter is working anyways (even if relay off), right?
Also, to fix the temperature misreading you used a temperature offset?
Thanks!

**Comment by Frigorio** [comment]
> So now the meter is working anyways (even if relay off), right?

Yes, meter is working.

> Also, to fix the temperature misreading you used a temperature offset?

Nope, to enable the template to work I had to set <analog> to User (15) so no temperature is read...

**Comment by ilgrank** [comment]
@ascillato so while the basic functionality is there, there's still some data missing

**Comment by ascillato2** [comment]
https://templates.blakadder.com/shelly_EM.html

**Comment by ilgrank** [comment]
@ascillato2 : so the issue @Frigorio was having (no temperature read) has been fixed?

**Comment by Frigorio** [comment]
Nope. I had to change ADC0 to User (15) otherwise the relay "was acting
weird" as @digiblur <https://github.com/digiblur> said.

**Comment by mugnier102** [comment]
Do you have 2 channel ? I flashed mine and has got only 1 measure. Is it normal ?
Does that mean only channel 1 or both channel ?
Could someone change comment on template to indicate ADC0 to User(15) and SetOption21 ?

**Comment by Frigorio** [comment]
> Do you have 2 channel ? I flashed mine and has got only 1 measure. Is it normal ?
I only have 1 channel connected, but as you can see in my screenshot the measure displayed is dual...

**Comment by ilgrank** [comment]
@Frigorio : and so you're lacking temperature monitoring, right?

**Comment by Sonnenberg** [comment]
Hello

I also got a ShellyEM and flashed with Tasmota.
so far so good and everything went according to plan

I connected the Shelly but I just don't get any values. does anyone know why?

I took the template as described here
![04](https://user-images.githubusercontent.com/68426912/87782934-c3145b80-c833-11ea-8afd-da0465a3fdc2.jpg)
![05](https://user-images.githubusercontent.com/68426912/87782942-c6a7e280-c833-11ea-8e65-03b0c617ef20.jpg)
![01](https://user-images.githubusercontent.com/68426912/87782950-cb6c9680-c833-11ea-9420-c253040d0906.jpg)
![02](https://user-images.githubusercontent.com/68426912/87782962-d0314a80-c833-11ea-89bc-2c6b209efc0b.jpg)
![03](https://user-images.githubusercontent.com/68426912/87782964-d293a480-c833-11ea-9c6d-664a29a61e03.jpg)

**Comment by ilgrank** [comment]
@Sonnenberg this issue is closed, you better ask @ascillato to re-open it, since the current template seem to
a) not be working correctly (alas, I can't test it until I get to my EM location)
b) missing temperature data anyways.

**Comment by Frigorio** [comment]
@Sonnenberg You have to set command "SetOption21 1" to enable energy
monitoring when power is off.

**Comment by Sonnenberg** [comment]
hi i'm not sure i had tried it with setoption21 on. I will test it again later and then report

**Comment by ilgrank** [comment]
@Frigorio: but still lacking temperature, right?

**Comment by Sonnenberg** [comment]
no, according to my memory, the temperature shows 152 degrees. however, this is switched off with ADC0 user (15). it makes no difference whether the relay is switched on or off

**Comment by ilgrank** [comment]
@Sonnenberg it's a safety measure, you should know if your equipment is overheating :)

**Comment by Sonnenberg** [comment]
I switched SetOption21 to 1.
with this template:
{"NAME": "Shelly EM", "GPIO": [0,0,0,0,0,0,0,0,6,156,5,21,0], "FLAG": 15, "BASE": 18}

![001](https://user-images.githubusercontent.com/68426912/87822193-5ae46a80-c871-11ea-9974-79b6e18a8171.JPG)
![002](https://user-images.githubusercontent.com/68426912/87822222-659eff80-c871-11ea-83ec-715b763b5c63.JPG)

with this template: {"NAME": "Shelly EM", "GPIO": [0,0,0,0,0,0,0,0,6,156,5,21,0], "FLAG": 2, "BASE": 18}
I have the following result.

![003](https://user-images.githubusercontent.com/68426912/87822419-b7478a00-c871-11ea-9475-ea6995f4e860.JPG)

I tried both templates with SetOption21 1, but I still don't get any values in watts & volts.
I do not understand this because a post with the same Tasmota version gets at least the values displayed

**Comment by seamus65** [comment]
Are you getting no reading because you are clamped over the whole cable and not just one tail?
The live and neutral will cancel each other out if you put the clamp iver both.

**Comment by Sonnenberg** [comment]
Yes of course
you are absolutely right, I could have thought of that on my own;)

![ok](https://user-images.githubusercontent.com/68426912/87872642-bf5f1100-c9ba-11ea-8f2b-0eb13705dfee.jpg)

sometimes you can't see the forest for the trees ^^
okay that works
now we only have the "problem" with the relay

best regards and thanks so far for your help =)
@ilgrank , do you have the right template at work?

**Comment by Frigorio** [comment]
@Sonnenberg which "problem" do you have with the switch?

Il dom 19 lug 2020, 12:24 Sonnenberg <notifications@github.com> ha scritto:

**Comment by Sonnenberg** [comment]
I have now turned "SetOption21" off
the relay is working properly

but the temperature is still missing,
if this is switched on, the relay switches off again immediately

the temperature problem has already been mentioned above.

**Comment by arendst** [comment]
Guys, if the temperature switches the relay off it means it either detects and overtemp or the tmeperature calculation is wrong.

In this case it's obvious the calculation is wrong. You'll have to change ADCPARAMs according to the installed NTC resistor bridge.

**Comment by Sonnenberg** [comment]
exactly, the temperature is so high
that the Shelly or Tasmota turns off the device
a security function that is super but I'm a little afraid to destroy the Shelly by testing it.

I have installed Tasmota on all my devices and I am very satisfied with it, but I was probably a bit hasty with the ShellyEM, because I probably can't use Tasmota as I would have liked

**Comment by zbuh** [comment]
I've flashed with Tasmota 8.3.1, loaded the template and SetOption21 to On.
But I can only see the relay. No power information. Any clue of what may I'm doing wrong?

**Comment by zbuh** [comment]
a new erase and flash fixed!

**Comment by ilgrank** [comment]
zbuh: meaning you also see temperature?

**Comment by zbuh** [comment]
no. no temperature

**Comment by mugnier102** [comment]
@Sonneberg:
You have missed the most important physical part.
YOu must have only 1 wire in the shelf. You're picture show that you put red and blue wire in the shelf.
 Move your shelf to have only the red wire (or the blue if you prefer...).
Putting both make the blue one to cancel the red one..... and so the measure is 0.

**Comment by Frigorio** [comment]
@ilgrank wrote:
> so the issue @Frigorio was having (no temperature read) has been fixed?
> @Frigorio : and so you're lacking temperature monitoring, right?

@arendst wrote:
> Guys, if the temperature switches the relay off it means it either detects and overtemp or the tmeperature calculation is wrong.
> In this case it's obvious the calculation is wrong. You'll have to change ADCPARAMs according to the installed NTC resistor bridge.

I can confirm that ADCPARAMs are wrong, I asked Dimitar Dimitrov for ShellyEM's NTC parameters and I'm waiting for a feedback ([permalink](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/3601666286599376)).

**Comment by Frigorio** [comment]
> I can confirm that ADCPARAMs are wrong, I asked Dimitar Dimitrov for ShellyEM's NTC parameters and I'm waiting for a feedback ([permalink](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/3601666286599376)).
OK. Dimitar Dimitrov said that _"Shelly EM do not have NTC"_
So, if Shelly EM has no temperature sensor, what the hack is A0 used for?

**Comment by kaciker** [comment]
Hello, I just flashed Tasmota to a EM that worked during 2 years with Shelly firm. After check all templates that I see, the device show only one chanel (I had fisically two) and the power showed is wrong, less than real.


I tested changing septoption21 and no changes in 0/1

Can someone help me ?

This is with https://templates.blakadder.com/shelly_EM.html

![2021-05-26_10h27_23](https://user-images.githubusercontent.com/7668181/119628028-04d74080-be0d-11eb-9373-4cf841390d55.png)


![2021-05-26_10h26_29](https://user-images.githubusercontent.com/7668181/119627894-e5d8ae80-be0c-11eb-8fbf-fbcfe3234c58.png)

**Comment by kaciker** [comment]
After several tries without success, I have come back to Shelly firm by OTA again, with this fantastic tool:
https://github.com/arendst/mgos-to-tasmota/

**Comment by zbuh** [comment]
@kaciker I went back to Shelly firm with that, but it stopped updating at version 1.9.7, newer versions are not updated...
Did you had success updating to newer versions?

**Comment by hugomon** [comment]
> Hello, I just flashed Tasmota to a EM that worked during 2 years with Shelly firm. After check all templates that I see, the device show only one chanel (I had fisically two) and the power showed is wrong, less than real.
> 
> I tested changing septoption21 and no changes in 0/1
> 
> Can someone help me ?
> 
> This is with https://templates.blakadder.com/shelly_EM.html
<details>
<summary>Click to expand!</summary>

> ![2021-05-26_10h27_23](https://user-images.githubusercontent.com/7668181/119628028-04d74080-be0d-11eb-9373-4cf841390d55.png)
> 
> ![2021-05-26_10h26_29](https://user-images.githubusercontent.com/7668181/119627894-e5d8ae80-be0c-11eb-8fbf-fbcfe3234c58.png)
</details>

It's strange. 

![](https://i.imgur.com/0P2WzYl.png)

![](https://i.imgur.com/pFZ08ov.png)

Try `{"NAME":"Shelly EM","GPIO":[0,0,0,0,0,0,0,0,640,3456,608,224,0,1],"FLAG":0,"BASE":18}`

**Comment by vtainc** [comment]
> @kaciker I went back to Shelly firm with that, but it stopped updating at version 1.9.7, newer versions are not updated... Did you had success updating to newer versions?

If you wish to update to version higher than 1.9.7 then you must:

1. Prepare firmware using https://github.com/ioprev/shelly-firmware
2. Flash firmware using for example Tasmotizer *.bin 

after this you will have latest firmware and no problems when upgrading/downgrading.
