### ISSUE TITLE
Better support for LCD 2004A 20x4 

### ISSUE THREAD

**Issue by tthk** [arendst/Tasmota#8062]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
LCD display support is currently on for 16x2 characters display.  Please support 2004A I2C display, which is 20x4.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Changes to remove 16x2 hardcoded display resolution and allow user to select 20x4.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
LCD 2004 can be used, but because Tasmota initialized it as 16x2, the formatting is off.

**Additional context**  
_Add any other context or screenshots about the feature request here._
I've made a change in two files which allows 20x4 sized LCD.  I am submitting a pull request and will reference this issue.
A feature request for this exact issue was closed a while back:
https://github.com/arendst/Tasmota/issues/669

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing as the thread continues at #8064
