### ISSUE TITLE
Warema EWFS

### ISSUE THREAD

**Issue by alekob** [arendst/Tasmota#8065]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
Flashed Tasmota v8.2.0 to a Sonoff RF 433 bridge and tried to learn codes from a "Warema EWFS 8 channel transmitter" but no codes are recognized. AFAIK, EWFS does not use rolling codes compared to their new WMS protocol

**Describe the solution you'd like**  
Support EWFS code recognizion / transmission

**Describe alternatives you've considered**  
Used Broadlink's RMPro device, which is able to learn / receive EWFS codes, but has no MQTT support / problems with node red

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
