### ISSUE TITLE
Turn TUYA modules into SHUTTER module aka AC Line detection

### ISSUE THREAD

**Issue by rokrodic** [arendst/Tasmota#8070]
Hi. 
I do not know where to turn to, but here's a tutorial for anyone who wants to make modification to Tasmota to make TUYA AC Line detecting modules with relays work as SHUTTER module. You can even use them as any other module.

Hopefully you find links useful. It's a small contribution to the comunity. I explain which changes to make and where for the code to detect zero crossings as a button... 

https://youtu.be/cBtZAbc9_q8

https://www.rodic.si/tasmota-tuya-shutters-arduino-ac-line/  (schematics) 

Greetings from Slovenija, 
Rok Rodič, GreenEyedExplorer

**Comment by ascillato** [comment]
Hi, please help us and add that information to the docs. You can make a PR to update any article. Thanks.
