### ISSUE TITLE
MH-Z19b sensor not supported anymore?

### ISSUE THREAD

**Issue by Bdegier** [arendst/Tasmota#8071]
I just upgraded from 8.1.0 to 8.2.0 and now my CO2 sensor is not supported anymore. I an using several MH-Z19b sensors, which used to be type 60 (Tx) and 61 (Rx) but they don't show up anymore. Attached is a screenshot of my 8.1.0 configuration.

![MH-Z19b support in 8 1 0](https://user-images.githubusercontent.com/61080285/78459706-23372580-76bb-11ea-9362-a0628aec8a0e.JPG)

**Comment by ascillato** [comment]
Please, use tasmota-sensors.bin for sensors' support. Thanks.

If you need further assistant, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
