### ISSUE TITLE
Sonoff TH16 + A2301 Temp and MQTT 

### ISSUE THREAD

**Issue by sommertrip** [arendst/Tasmota#8077]
Hi, I am running Tasmota 8.2 on a Sonoff TH16 + A2301 Temp Sensor, 
I´ve also configured MQTT to be published to local MQTT Server running on Synology in Docker. 
Switch On/Off is working properly, but I´m having problemes with subscribing Temp/Humidity trough MQTT. 
I´m attaching some pictures of the sonoff,
<img width="375" alt="Bildschirmfoto 2020-04-05 um 20 50 16" src="https://user-images.githubusercontent.com/15965995/78507252-5642ed00-777f-11ea-894a-f3d97d221beb.png">
<img width="375" alt="Bildschirmfoto 2020-04-05 um 20 50 32" src="https://user-images.githubusercontent.com/15965995/78507257-580cb080-777f-11ea-95bd-4d8eef643237.png">
<img width="1393" alt="Bildschirmfoto 2020-04-05 um 20 50 56" src="https://user-images.githubusercontent.com/15965995/78507260-593ddd80-777f-11ea-85df-7ae21895b366.png">
I have tried several Plugins to subscribe to the MQTT, server, but none is displaying Temp and Humidity.
The Server log is showing the following. 
<img width="1393" alt="Bildschirmfoto 2020-04-05 um 20 54 17" src="https://user-images.githubusercontent.com/15965995/78507325-b9348400-777f-11ea-9d81-167c868ea59e.png">
MQtt fix is showing the data.
<img width="1397" alt="Bildschirmfoto 2020-04-05 um 20 57 39" src="https://user-images.githubusercontent.com/15965995/78507420-2cd69100-7780-11ea-902e-b25c3faa7974.png">
actually I don´t know how to proceed
thx. Karl

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
