### ISSUE TITLE
Tasmota 8.2.0  SetOption19 1 does not make switches, buttons discoverable

### ISSUE THREAD

**Issue by quintinsleeking** [arendst/Tasmota#8090]
Tasmota 8.2.0  SetOption19 1 does not make switches, buttons discoverable.

I checked the logs and it seems that switches and buttons dont get set as discoverable when SetOption19 is set to 1.

Home assistant picks up my relays and analog sensor but no switches or buttons.

Please could someone advise if its an error i am making?

**Comment by effelle** [comment]
Read the Docs `here` for the new configuration.
