### ISSUE TITLE
XdrvMailbox.grpflg Should Check All MQTT Group Topics

### ISSUE THREAD

**Issue by pcdiem** [arendst/Tasmota#8095]
**Have you looked for this feature in other issues and in the docs?**  Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Now that they can be up to four MQTT group topics, XdrvMailbox.grpflg should probably be true is the topic matches any of the four group topics. Right now it is only set to true if it matches group topic 1.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Change support_command.ino line 185 to a loop to check all four group topics.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
You are right. Will fix this.
