### ISSUE TITLE
MCP23017 Auto-Off function with rule generates lot of traffic (pinmode 6)

### ISSUE THREAD

**Issue by Dreamoffice** [arendst/Tasmota#8101]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
i m using this rule:
`rule1 on MCP230XX#D8 == 1  do ruletimer1 1 endon on rules#timer=1 do Sensor29 8,0 endon`
the rule is working but generates a lot of traffic in console and even on the mqtt broker. the pinmode is 6, with the command `Sensor29 8,0` the output is off. but the ruletimer is active and fires every second.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____Nodemcu
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [X] Self-compiled
    - [x] IDE / Compiler used: _____VS Code
- [x] Flashing tools used: _____VS Code
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
06:51:40 CMD: Backlog Template; Module; GPIO 255
06:51:41 MQT: stat/test/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
rule1 on MCP230XX#D8 == 1  do ruletimer1 1 endon on rules#timer=1 do Sensor29 8,0 endon
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
06:50:32 CMD: Backlog Rule1; Rule2; Rule3
06:50:32 MQT: stat/test/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":430,"Rules":"on MCP230XX#D8 == 1  do ruletimer1 1 endon on rules#timer=1 do Sensor29 8,0 endon"}

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
06:53:28 CMD: Status 0
06:53:28 MQT: stat/test/STATUS = {"Status":{"Module":0,"FriendlyName":["Tasmota"],"Topic":"test","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:53:28 MQT: stat/test/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"0T12:12:09","StartupUTC":"2020-04-08T17:41:19","Sleep":50,"CfgHolder":4617,"BootCount":22,"BCResetTime":"2020-04-03T08:59:47","SaveCount":143,"SaveAddress":"F5000"}}
06:53:28 MQT: stat/test/STATUS2 = {"StatusFWR":{"Version":"8.2.0.1(tasmota)","BuildDateTime":"2020.03.25 08:55:30","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"326/699"}}
06:53:28 MQT: stat/test/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SKYDSL",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
06:53:28 MQT: stat/test/STATUS4 = {"StatusMEM":{"ProgramSize":589,"Free":412,"Heap":23,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000407","8FDAE397","043683A1","000004CD","010013F1","C000F981","00000004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6,9,29"}}
06:53:28 MQT: stat/test/STATUS5 = {"StatusNET":{"Hostname":"TestObjekt","IPAddress":"192.168.1.153","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"EC:FA:BC:58:A1:D1","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
06:53:28 MQT: stat/test/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.152","MqttPort":1883,"MqttClientMask":"Testobjekt","MqttClient":"Testobjekt","MqttUser":"openhabian","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
06:53:28 MQT: stat/test/STATUS7 = {"StatusTIM":{"UTC":"2020-04-09T05:53:28","Local":"2020-04-09T06:53:28","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:10","Sunset":"19:33"}}
06:53:28 MQT: stat/test/STATUS10 = {"StatusSNS":{"Time":"2020-04-09T06:53:28","MCP230XX":{"D0":1,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0,"D8":1,"D9":1,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}}
06:53:28 MQT: stat/test/STATUS11 = {"StatusSTS":{"Time":"2020-04-09T06:53:28","Uptime":"0T12:12:09","UptimeSec":43929,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"SKYDSL","BSSId":"38:10:D5:EB:57:42","Channel":6,"RSSI":64,"Signal":-68,"LinkCount":1,"Downtime":"0T00:00:06"}}}


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
06:54:42 SRC: Rule
06:54:42 CMD: Gruppe 0, Index 1, Befehl "RULETIMER", Daten "1"
06:54:42 MQT: stat/test/RESULT = {"T1":1,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
06:54:43 RUL: MCP230XX#D8 == 1  performs "ruletimer1 1"
06:54:43 SRC: Rule
06:54:43 CMD: Gruppe 0, Index 1, Befehl "RULETIMER", Daten "1"
06:54:43 MQT: stat/test/RESULT = {"T1":1,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
i m using this rule:
`rule1 on MCP230XX#D8 == 1  do ruletimer1 1 endon on rules#timer=1 do Sensor29 8,0 endon`
the rule is working but generates a lot of traffic in console and even on the mqtt broker. the pinmode is 6, with the command `Sensor29 8,0` the output is off. but the ruletimer is active and fires every second.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
the ruletimer starts when the output pin switches the relay on an. why is ruletimer active when the relay is off and the condition is not true? 

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
<img width="693" alt="Bildschirmfoto 2020-04-09 um 08 59 15" src="https://user-images.githubusercontent.com/35889916/78866844-7228e600-7a40-11ea-8a3a-b0a184400258.png">

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi, the rule trigger is incorrect ( `rule1 on MCP230XX#D8 == 1 do ...` ). The spaces you added makes the behaviour like if that was `rule1 on MCP230XX#D8 do ...`

Please, retype it as  `rule1 on MCP230XX#D8=1 do ruletimer1 1 endon on rules#timer=1 do Sensor29 8,0 endon`
