### ISSUE TITLE
Add RuleSet in Template definition

### ISSUE THREAD

**Issue by akram** [arendst/Tasmota#8102]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Many devices cannot work as-is with tasmota Template and often requires an additionnal RuleSet to protect them from being bricked or malfunctionned.
Right now, when on installs a new Template for a device, it often has to add an additional set of rules separately.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
That would be great if we can have a Device configuration including the Template and RuleSet to apply with it.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
Right now, we have to create the Template, then apply the Rules and enable them.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Yes, you are right. Required rules must be added later. But they can't be added on the template. You have to manualy introduced them. There is no enough space in a template to add everything.
