### ISSUE TITLE
How to sent with rf433 continous for 2 seconds

### ISSUE THREAD

**Issue by andreas-nn** [arendst/Tasmota#8112]
**Have you looked for this feature in other issues and in the docs?**  
Yes, but I have not found anything for my problem
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Sending the rf433-Signal for a medium time repeated
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
A parameter for the rfkey-Function
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
Repeated send the order
**Additional context**  
_Add any other context or screenshots about the feature request here._
Not one
**(Please, remember to close the issue when the problem has been addressed)**  

I use tasmota-firmware at the sonoff rf-bridge. It works good.
But now I use a rf433-switch which activate a relay with the time I press the button at the remote control.

I need i.e. two or three seconds of rf-signal.
How can I simulate this with the tasmota rf433 commands?

Thanks
Andreas

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
