### ISSUE TITLE
Wiki links are all dead

### ISSUE THREAD

**Issue by rolandow** [arendst/Tasmota#8115]
Last week I installed Tasmota on a smart plug. It's really disappointing (and annoying, to be honest) to see that all the wiki links are dead. Links found on google, but also references in github issues, all point to the same frontpage on github.

For example in ticket #2219 is ended with "See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.". Clicking it leads nowhere.

Is there not a way to fix this with redirects?

**Comment by Jason2866** [comment]
If you look at the start page here you see https://tasmota.github.io/docs
No, old outdated wiki will NOT be reactivated. Reason Google will still reference when it is still there.

**Comment by lalo-uy** [comment]
May be wipe all old wiki and put there a link to new docs.
