### ISSUE TITLE
Moes Dimmer Switch (US model)

### ISSUE THREAD

**Issue by nj2299** [arendst/Tasmota#8117]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

The dimmer range on this device is 150 to 1000 - as per feedback from the device.  When the dimmer range is set, the device does only change when sending the command Dimmer 75 and above.  Below Dimmer 75 (assuming this is percent) the dimmer stays at the lowest setting. Essentially the full dimming range is controlled between 75-100.  Second issue is that the LED stops responding to any status changes or commands from the console.   It does flash red when power cycled.  The White LED seems to stop responding.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Moes Dimmer DSC01
- [x] Tasmota binary firmware version number used:  8.2.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: Tuya Convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:

15:23:10 RSL: stat/tasmota_BA8FF1/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
15:23:10 RSL: stat/tasmota_BA8FF1/RESULT = {"Module":{"54":"Tuya MCU"}}
15:23:11 RSL: stat/tasmota_BA8FF1/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"107":"Tuya Tx"},"GPIO2":{"0":"None"},"GPIO3":{"108":"Tuya Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
15:23:29 RSL: tele/tasmota_BA8FF1/STATE = {"Time":"2020-04-10T15:23:29","Uptime":"3T13:55:21","UptimeSec":309321,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Dimmer":68,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"CNN","BSSId":"C4:71:54:3D:97:90","Channel":11,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:16"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
02:29:27 CMD: status 0
02:29:27 SRC: WebConsole from 192.168.1.133
02:29:27 CMD: Group 0, Index 1, Command "STATUS", Data "0"
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS = {"Status":{"Module":54,"FriendlyName":["Tasmota"],"Topic":"tasmota_BA8FF1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:18","StartupUTC":"2020-04-11T01:27:09","Sleep":50,"CfgHolder":4617,"BootCount":13,"BCResetTime":"2020-04-06T13:17:40","SaveCount":87,"SaveAddress":"F5000"}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS2 = {"StatusFWR":{"Version":"8.2.0(tasmota)","BuildDateTime":"2020-03-20T14:45:23","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"312/699"}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["CNN",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS4 = {"StatusMEM":{"ProgramSize":577,"Free":424,"Heap":26,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashMode":0,"Features":["00000809","8FDAE397","043683A0","000000CD","010013C0","C000F981","00000004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS5 = {"StatusNET":{"Hostname":"tasmota_BA8FF1-4081","IPAddress":"192.168.1.121","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"98:F4:AB:BA:8F:F1","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_BA8FF1","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS7 = {"StatusTIM":{"UTC":"2020-04-11T01:29:27","Local":"2020-04-11T02:29:27","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:06","Sunset":"19:36"}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS10 = {"StatusSNS":{"Time":"2020-04-11T02:29:27"}}
02:29:27 RSL: stat/tasmota_BA8FF1/STATUS11 = {"StatusSTS":{"Time":"2020-04-11T02:29:27","Uptime":"0T00:02:18","UptimeSec":138,"Heap":26,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":80,"MqttCount":0,"POWER":"ON","Dimmer":74,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"CNN","BSSId":"C4:71:54:3D:97:90","Channel":11,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:08"}}}
02:29:32 TYA: Send "55aa00000000ff"
02:29:32 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
02:29:32 TYA: Heartbeat
02:29:38 WIF: Checking connection...

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

- Setup device as TuyaMCU - Module (54)
- enter command in console - TuyaMCU 21,2
- enter command in console - dimmerrange 150,1000

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Expect that the Dimmer command would be able to use the full 0-100 range
Expect that the white LED would respond to changes of state as set by the LEDState and LEDpower commands

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
The device does connect to the network, and does respond to commands in the console.  Just not as expected.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by nj2299** [comment]
I don’t think I filled the issue template for the check boxes properly.  Sorry about that.

**Comment by effelle** [comment]
Please edit it and add the result of  `status 0` and show us what happens when you issue the command in console (set it to weblog 4).

**Comment by nj2299** [comment]
Thank you for fixing the format.  I've checked the steps i've taken, and added the output from the status 0 with the weblog 4 set.

**Comment by Jontron123** [comment]
Try setting LedTable 0 and see if that helps the dimmer command.

I assume you means a Moes DS01? I have a TreatLife DS01 which is similar to a Moes DS01 and had a similar issue with the dimming range. After turning off LedTable, the dimming range works as expected.

**Comment by nj2299** [comment]
You are correct, it is the Moes DS01.  Setting the LedTable 0 fixed the issue with the range!  Thank you!!

Do you also have the issue with the white power LED not responding?

**Comment by broken** [comment]
I'm having the same issue with the status light on my TreatLife DS01. It is worth noting that my switch on version 8.1.0 does not have this issue, only the switches on 8.2.0. Thus, I have my suspicion the problem is in the upgrade, but I cannot confirm. I don't want to upgrade the 8.1.0 switches, and I cannot downgrade the 8.2.0 switches even with SetOption78 disabled.

**Comment by ascillato2** [comment]
Hi, several fixes has been merger. Please, can you re test with latest version from the development branch? ( thehackbox.org/tasmota ) thanks.

**Comment by broken** [comment]
I just updated both of my switches to dev v8.2.0.4 and am still experiencing both issues. The status light does not turn on, and the Dimmer command does not have its full range. The one difference between @nj2299 and I is that my Dimmer command's lower limit is 50 and not 75. This was before and after the update.

**Comment by nj2299** [comment]
I've just updated to 8.2.0.4 as well and still have the same issues as before.

**Comment by philharlow** [comment]
It looks like I just missed the end of this ticket. Using the Treatlife Dimmer DS01, the ```ledtable 0``` command definitely helped the dimming function. Now It's just that white led issue. Can we compare changes between 8.1.0 and 8.2.0?

**Comment by broken** [comment]
A similar issue has been reopend with #8577
