### ISSUE TITLE
encrypt mqtt_passwd and webui passwd

### ISSUE THREAD

**Issue by excxapp** [arendst/Tasmota#8188]
**Have you looked for this feature in other issues and in the docs?**  
if we backup data, the passwd is unencrypted, so can encrypt passwd for safety,
this feature can deploy by self complie.

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
backup data id ver danger
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
user passwd can encrypt.(like AES [AESLib](https://github.com/DavyLandman/AESLib)  and so on .)
encrypt passwd and when use decode in program
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

now,we can backup data, and decode it.it very unsafe.
we can set encrypt key in code, and use this key to encrypt the password and serect info,
like AES [AESLib](https://github.com/DavyLandman/AESLib)  and so on .

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Not enough data. Pls fill in the template completely.

**Comment by excxapp** [comment]
ok, I filled.

**Comment by excxapp** [comment]
I have encrypt mqtt_passwd and add globalsign root ca cert  .
can i pr?

**Comment by ascillato2** [comment]
> can i pr?

yes, please. Thanks

**Comment by excxapp** [comment]
ok,i will clean some code and pr
