### ISSUE TITLE
Feature request: Reboot every X hours

### ISSUE THREAD

**Issue by smhgit** [arendst/Tasmota#8223]
Hi,

I have Wemos device that controls a contactor in my main breaker panel. For some reason, which currently I don't know why, Wemos D1 loss connection with my home hub. Up to now, it seems that turning  off / on the power solves the issue.

I know that reboot is not a good solution. It is always better to find the real cause. But sometimes it takes time to find the reason, and as the device is in the main panel, debugging is much more difficult.

I suggest that there will be an option that will trigger a reboot every N hours which will give some solution until reason will be found (as a result of debugging or maybe new release changes).

**Comment by ascillato** [comment]
Already supported using rules.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
