### ISSUE TITLE
LC-Tech 4 CH relay

### ISSUE THREAD

**Issue by TasmoFlash** [arendst/Tasmota#8228]
<Hi Guys
if one of you could integrate a device in Tasmota, try it now for one
week without success.
LC-Tech 4 CH relay
{"LCTech 4-Relay", // LC Technology Relay board 4 channel, based on ESP 01
      GPIO_USER, // GPIO00
      GPIO_RXD, // GPIO01 TX Serial RXD
      GPIO_USER, // GPIO02
      GPIO_TXD, // GPIO03 RX Serial TXD
      0,
      0,
      0, 0, 0, 0, 0, 0, // Flash connection
      0, 0, 0, 0, 0, 0
   }

thank you in advance

**Comment by taste66** [comment]
https://tasmota.github.io/docs/devices/LC-Technology-WiFi-Relay/

**Comment by TasmoFlash** [comment]
Danke hat geklappt super Service!!

Gesendet von Yahoo Mail auf Android 
 
  Am So., Apr. 19, 2020 at 20:53 schrieb Marc Smaak<notifications@github.com>:   


https://tasmota.github.io/docs/devices/LC-Technology-WiFi-Relay/
