### ISSUE TITLE
[Feature Request] Adding estimated costs at the WebUI for PowerPlugs

### ISSUE THREAD

**Issue by chimcen** [arendst/Tasmota#8234]
**Have you looked for this feature in other issues and in the docs?**  
Yes...

**Is your feature request related to a problem? Please describe.**  
Missing the possibility to see the estimated costs for the used electrical current.

**Describe the solution you'd like**  
dding estimated costs the WebUI for 
Is there a way to add in WebUI an overview for all costs incurred so far?

**Describe alternatives you've considered**  
...

**Additional context**  
Like this:
![Tasmota_Cost](https://user-images.githubusercontent.com/22658487/79757166-fd955780-831b-11ea-925c-b64984924db2.jpg)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi, 

Already available. 

Please see TARIFF command. 

Thanks

**Comment by chimcen** [comment]
Didn’t see this before - sry.

But can you help me by giving me an example how to configure this to see the costs like shown on my picture?
