### ISSUE TITLE
DHT22 issue

### ISSUE THREAD

**Issue by fireport** [arendst/Tasmota#8238]
### PROBLEM DESCRIPTION
After a while DHT22 reading become null. A software restart doesn't fix the problem. Only powering on/off the sonoff  temporary resolve the problem

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ X] Device used (e.g., Sonoff Basic): sonoff basic_____
- [ X] Tasmota binary firmware version number used: 8.2
  - [ X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ esptool.py] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
9:02:34 CMD: Backlog Template; Module; GPIO 255
19:02:34 MQT: stat/tasmota_C1E9D0/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
19:02:34 MQT: stat/tasmota_C1E9D0/RESULT = {"Module":{"1":"Sonoff Basic"}}
19:02:34 MQT: tele/tasmota_C1E9D0/STATE = {"Time":"2020-04-20T19:02:34","Uptime":"0T00:10:12","UptimeSec":612,"Heap":24,"SleepMode":"Normal","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"myhome","BSSId":"DC:39:6F:FD:A1:E5","Channel":1,"RSSI":100,"Signal":-23,"LinkCount":1,"Downtime":"0T00:00:06"}}
19:02:34 MQT: domoticz/in = {"idx":109,"nvalue":0,"svalue":"null;null;1","Battery":100,"RSSI":10}
19:02:34 MQT: tele/tasmota_C1E9D0/SENSOR = {"Time":"2020-04-20T19:02:34","AM2301":{"Temperature":null,"Humidity":null,"DewPoint":0.0},"TempUnit":"C"}
19:02:34 MQT: stat/tasmota_C1E9D0/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"2":"AM2301"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
  Configuration output here:

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

```
- [X ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
19:03:42 CMD: status 0
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS = {"Status":{"Module":1,"FriendlyName":["cappa"],"Topic":"tasmota_C1E9D0","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:11:20","StartupUTC":"2020-04-20T17:52:22","Sleep":50,"CfgHolder":4617,"BootCount":21,"BCResetTime":"2020-04-20T07:30:02","SaveCount":67,"SaveAddress":"F9000"}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS2 = {"StatusFWR":{"Version":"8.2.0(tasmota)","BuildDateTime":"2020-03-20T14:45:23","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"369/699"}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":3,"LogHost":"192.168.1.2","LogPort":514,"SSId":["myhome",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000400","00000000"]}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS4 = {"StatusMEM":{"ProgramSize":577,"Free":424,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","000000CD","010013C0","C000F981","00000004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS5 = {"StatusNET":{"Hostname":"sonoff_basic_01","IPAddress":"192.168.1.68","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.13","Mac":"2C:F4:32:C1:E9:D0","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C1E9D0","MqttUser":"user","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS7 = {"StatusTIM":{"UTC":"2020-04-20T18:03:42","Local":"2020-04-20T19:03:42","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"05:48","Sunset":"19:49"}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS10 = {"StatusSNS":{"Time":"2020-04-20T19:03:42","AM2301":{"Temperature":null,"Humidity":null,"DewPoint":0.0},"TempUnit":"C"}}
19:03:42 MQT: stat/tasmota_C1E9D0/STATUS11 = {"StatusSTS":{"Time":"2020-04-20T19:03:42","Uptime":"0T00:11:20","UptimeSec":680,"Heap":24,"SleepMode":"Normal","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"myhome","BSSId":"DC:39:6F:FD:A1:E5","Channel":1,"RSSI":100,"Signal":-23,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Wait some hours

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._


### ADDITIONAL CONTEXT
_Add any other context about the problem here._


**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
