### ISSUE TITLE
Support a PowerValue (Bitcoded) to set a bunch of Relais with one command

### ISSUE THREAD

**Issue by SebastianBaeumler** [arendst/Tasmota#8239]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
I control my garden watering system with a Sonoff 4CH Pro.
I wired my valves in a kind of matrix.
So Relais1 == 0 select valve 1 - 3 and Relais1 ==1 select valve 4 - 6.
I use it in an KNX environment with a server that is able to use the Tasmota Rest API.

If I change the valve selection all valve state became inverted.
That mean a valve that was off change to on and vice versa.

| Step | ValveSelection | Value 1/4 | Value 2/5 | Valve 3/6 | PowerSituation |
|:--:|:--:|:--:|:--:|:--:|:--:|
| 1 / all off | 0 / 1-3 | 0 / Off | 0 / Off | 0 / Off | Powered Values = 0|
| 2 / Valve1 = On | 0 / 1-3 | 1 / On | 0 / Off | 0 / Off | Powered Values = 1|
| 3 / change Selection | 1 / 4-6 | 1 / Off | 0 / On | 0 / On | Powered Values = 2|
| 4 / turn valve 5 off | 1 / 4-6 | 1 / Off | 1 / Off | 0 / On | Powered Values = 1|
| 5 / turn valve 6 off | 1 / 4-6 | 1 / Off | 1 / Off | 1 / Off | Powered Values = 0|
| 6 / change selection (go to start state)  | 0 / 1-3 | 1 / On | 1 / On | 1 / On | Powered Values = 3 __PowerOverload__|
| 7 / turn valve 1 off  | 0 / 1-3 | 0 / Off | 1 / On | 1 / On | Powered Values = 2|
| 8 / turn valve 2 off  | 0 / 1-3 | 0 / Off | 0 / Off | 1 / On | Powered Values = 1|
| 9 / turn valve 3 off  | 0 / 1-3 | 0 / Off | 0 / Off | 0 / Off | Powered Values = 0|

When changing the valve selection I need 2-3 commands to reduce the power usage of the valves and go to the target state.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

To avoid a power overload when change selection of valves and also to use a single KNX command, 
I would prefer to have a Value (e.g. PowerValue) that allow to write a Bitmask to select the outputs and the Status of the outputs.
On KNX the value could be a 2Byte value. 1st byte 
SelectionBitmask 2nd byte status.
On the Rest API I would suggest a command with 2 values. also selection bit mask and the status

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

I wrote the 'Backlog' option. This may help with the RestAPI, but this will not help in case of KNX.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
For your use case seems to be better the use of rules. You can use a VAR to manage all your states and write to that VAR.

First you can config that your KNX network sends the commands to a Tasmota's KNX TX Slot. 

Then by rules, move the receives command to a VAR. 

Then the VAR is the one that will power on and off your relays. 

For example, you send a 1 by KNX to turn on the valve 1. The rule that receives that value can be:
```lua
Rule1 on event#knxrx_val1 do var1 %value% endon
```
Then the VAR can be managed by other rules like:
```lua
on var1#state=1 do backlog power1 1;power2 0;power3 0 endon
```
