### ISSUE TITLE
Toggle output based on a set trigger temperature

### ISSUE THREAD

**Issue by Sc00by121** [arendst/Tasmota#8241]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
I am using a Sonoff/Tasmota to control a boiler.  I have a string of sensors monitoring flow,return and ambient air temp.  This works great however there is no ability set a frost stat temp.  There is currently no way (that I can see or find online) to set a minimum and maximum temp within Tasmota to trigger an output (switch on boiler)

**Describe the solution you'd like**  
The ability to set a min and max temp from a particular sensor (if more than one available) to switch an output.  Mimicking a frost stat

**Describe alternatives you've considered**  
Having a rule running on an external system to trigger the output when the reading gets sent over MQTT however this is risky if this network link gets interrupted.  The boiler would not fire.

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Already supported by the use of Tasmota's rules. 

Please, read the docs and search in issues. Thanks. 

If you need further assistant on Tasmota usage, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
