### ISSUE TITLE
Send wifi signal strength to HomeAssistant automatic discovery

### ISSUE THREAD

**Issue by jrhbcn** [arendst/Tasmota#8244]
Hi,

Tasmota both reports RSSI and Signal Strength for WiFi connection (following issues #7113 and PR #7145). However, only RSSI is added back to Home Assistant and Signal Strength is missing in automatic discovery. I am trying to unify the wifi reporting of all my IoT devices (it is a nightmare! but the majority seems to report dBm). Would it be possible to add this into Home Assistant discovery?

Thanks!

**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
It'd be good to have the same info in the status mqtt topic as attributes in Home Assistant.

**Describe alternatives you've considered**  
Convert RSSI to signal strength directly in Home Assistant but the entity cannot be added automatically to the Tasmota Device and looks as if an standalone entity.

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by effelle** [comment]
As you probably knows, we have dbm signal enabled in information page:
```c
EffE-WiFi (76%, -62 dBm)
```

**Comment by effelle** [comment]
As you probably knows, we have already `dBm` signal in information page:
```c
EffE-WiFi (76%, -62 dBm)
```
`RSSI` is already used in Home Assistant for metrics and to have `dBm` too a new sensor must be created, because a combined sensor with RSSI and dbm cant be used on history meaning code repetition and then grater space used on program memory.  
What I can do is to add the dBm value on the resume list of status sensor that will limit the space used, but will be not an information available for history.

**Comment by jrhbcn** [comment]
> What I can do is to add the dBm value on the resume list of status sensor that will limit the space used, but will be not an information available for history.

I think that is almost perfect. Info will be accessible to HomeAssistant (to create automations, etc.) and even if not available directly for history it could be forwarded to influxdb/grafana if history is needed anyway. 

Many thanks for looking into this and let me know if you need someone to test the solution. 

Regards,

**Comment by effelle** [comment]
Ok, I was about to change the resume list anyway. 
I'll add dBm on next update.
