### ISSUE TITLE
Problems with benzino77 tasmo online compiler

### ISSUE THREAD

**Issue by motorrad** [arendst/Tasmota#8245]
Hi there

since a few days im getting the following error with the online compiler development core stage german:
collect2: error: ld returned 1 exit status
*** [.pioenvs/custom/firmware.elf] Error 1
========================= [FAILED] Took 91.23 seconds =========================
Finished. Exit code: 1.

Not core stage is working

**Comment by device111** [comment]
so, its not a Problem from Tasmota. Go to  benzino77  Github and Report.
