### ISSUE TITLE
Can't compile Tasmota with USE_SCRIPT

### ISSUE THREAD

**Issue by Bettman66** [arendst/Tasmota#8256]
Pull Request # 8251 does not allow Tasmota to be created with USE_SCRIPT. The problem has already been solved here https://github.com/arendst/Tasmota/commit/f594c726097ae4311907060714caad1e3c3b5d91#diff-b04ab15e2078b31d160406a55b16fef1

**Comment by pcdiem** [comment]
Should I submit a fix for this?

**Comment by arendst** [comment]
It's fixed already

**Comment by Twillms84** [comment]
Hi, it seems that it's broken again. renderer.h No such file oder directory in xdrv_10_scripter.ino
