### ISSUE TITLE
add general nmea support

### ISSUE THREAD

**Issue by pljakobs** [arendst/Tasmota#8274]
**Have you looked for this feature in other issues and in the docs?**  

the GPS support in 8.x is very limited

**Is your feature request related to a problem? Please describe.**  
A feature request, or rather, asking if a certain feature is already being considered.
Here: provide data coming in from a serial nmea source (gps, or, in my case, a NASA Marine mast unit that provides wind speed and directions) as 
a) a structured json file in mqtt
b) possibly as a serial passthrough (which should already be possible with serial-bridge)

**Describe the solution you'd like**  
I have the unit connected to a serial input of a 8266, either hardware or software serial capable.
After configuration (in my case 4800bps, 8N1) and the mqtt topic, the topic is populated with a json file containing all decoded nmea sentences as key value pairs

**Describe alternatives you've considered**  
serial passthrough with local decoding

**Additional context**  
I would go ahead and make a first pass at this if there is any interest and it does fit the general direction Tasmota is taking.
It seems, that the xsns_60_GPS.ino implementation might not quite do what I'm looking at, at least it doesn't seem to be general enough.
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by kugelkopf123** [comment]
If not for the ESP8266 then it would be nice for the ESP32. UBLOXs ubx format, too.  ThumbUp
