### ISSUE TITLE
enn

### ISSUE THREAD

**Issue by ChristosKeleshis** [arendst/Tasmota#8301]
Hello,

I have one Sonoff4chPro R2 and i i am trying to read a State from an external switch which i have connected to GPIO1 and Ground using a pullup resistor (J1 jumper). I assigned GPIO01 as Switch8. From Tasmota console i monitor the status of Switch8 and it is changing correctly to ON or OFF in regards to the state of the physical switch. So far so good! This is what i want. However there is a problem which i do not understand. Whenever the physical switch connected on GPIO01 the Relay1 of the Sonoff4chProR2 is toggled. I tried GPIO02 and GPIO03 and i still get the same behavior. Can you please help?
Thanks!

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
