### ISSUE TITLE
How to use WebSend to submit voltage / watt data from a Sonoff POW R2 to my webservice

### ISSUE THREAD

**Issue by hagenbuch** [arendst/Tasmota#8337]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
I do not know how to use WebSend properly and can't find anything related in the docs

**Describe the solution you'd like**  
I would like to send measurements W, V, A from a Sonoff POW R2 for every 60 seconds to a webservice of mine via a http GET request.

**Describe alternatives you've considered**  
I succeeded to use WebSend in the command line: 

WebSend [mysite.com] /index.php?data=this

**Additional context**  
I have no idea how or where to set up a timer that starts a WebSend command and I have no Idea which template variable I need to use to post the voltage / wattage data. A small HowTo would be fantastic.

Thanks!
Andreas

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato** [comment]
You need to use rules to catch the value of the power, voltage, etc. and use websend for sending it.

Most of the data that is posted in your console can be used in rules.

If you see:

```lua
tele/sonoff-32A633/SENSOR = {"Time":"2019-12-09T12:01:26","ENERGY":{"TotalStartTime":"2019-05-06T14:20:29","Total":1368.188,"Yesterday":3.296,"Today":0.023,"Period":0.02,"Power":1.83,"ApparentPower":9.25,"ReactivePower":9.10,"Factor":0.20,"Voltage":236.0,"Current":0.039}}
```

You can use that as a trigger for rule ENERGY#POWER like:

```lua
rule1 1
rule1 on ENERGY#POWER do WebSend [mysite.com] /index.php?data=%value% endon
```

You can concatenate several rules into every rules' slot like:

```lua
rule1 1
rule1 on ENERGY#POWER do WebSend [mysite.com] /index.php?data1=%value% endon on ENERGY#VOLTAGE do WebSend [mysite.com] /index.php?data2=%value% endon
```

Check the docs at rules for more information. (http://tasmota.com)

If you need further assistant, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
