### ISSUE TITLE
Shutter Toggle with MQTT

### ISSUE THREAD

**Issue by fennec622** [arendst/Tasmota#8344]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
no
**Describe the solution you'd like**  
Hi

My shutter is connecting to WF-CS01 Curtain Switch

Is it possible to Toggle shutter with MQTT publish

Like

cmnd/shutterparents/shuttertoggle1

if level 0 shutter move to 100
if level 100 shutter move to 0
if level !=100 or level !=0 move to 100

Do you thinks it's possible ?
I wan't to open or close with zigbee button with just click

Thanks
**Describe alternatives you've considered**  
nothing
**Additional context**  
nothing
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Duplicated of issue https://github.com/arendst/Tasmota/issues/8309. Let's continue this thread there. Thanks.
