### ISSUE TITLE
The Github wiki is broken

### ISSUE THREAD

**Issue by nuxeh** [arendst/Tasmota#8361]
Hi, the Github wiki links persistent in issues on Github and elsewhere are broken. Thanks.

**Comment by AlexTransit** [comment]
wiki here
https://tasmota.github.io/docs/

**Comment by nuxeh** [comment]
Thanks @AlexTransit , I had seen that, but this is pretty incomplete, where are for example the list of console commands? This just detracts from the usability of this project, imo.

**Comment by meingraham** [comment]
@nuxeh 

Menu bar on the left, click on Commands?

Similar for other parts of the documentation. Also, there are additional major sections linked across the top menu bar.

**Comment by nuxeh** [comment]
Thanks @meingraham , my bad.

**Comment by AlexTransit** [comment]
@meingraham  
use search. (top page)

**Comment by meingraham** [comment]
@AlexTransit 

Huh?  My question mark was not me asking but rather inquiring if that was not what  @nuxeh needed. He got my meaning.
