### ISSUE TITLE
Name Device - Friendly name not send via mqtt

### ISSUE THREAD

**Issue by GiorgioRoma** [arendst/Tasmota#8366]
I installed the last version of tasmota-it 8.2.0.6  (2020-05-06T11:06:42)
I set friendly name in extra config ("**Luci Salone Laterali**"), but the command sent via mqtt is:

19:28:53 MQT: homeassistant/sensor/FAFE6A_status/config = {"name":"**Shelly 1** status"...........
the wrong name appears, in the Home Assistant Integration dashboard

Later I installed the version 8.2.0.3, and the problem is not there

**Comment by effelle** [comment]
`Friendlyname1` is no longer the name of the device and will be soon extended on sensors too (probably today). 
It uses the name of the module/template and can easily changed from Home Assistant integration.
