### ISSUE TITLE
Name Device - Friendly name not send via mqtt

### ISSUE THREAD

**Issue by GiorgioRoma** [arendst/Tasmota#8367]
### PROBLEM DESCRIPTION
I installed the last version of tasmota-it 8.2.0.6 (2020-05-06T11:06:42)
I set friendly name in extra config ("Luci Salone Laterali"), but the command sent via mqtt is:

19:28:53 MQT: homeassistant/sensor/FAFE6A_status/config = {"name":"Shelly 1 status"...........
the wrong name appears, in the Home Assistant Integration dashboard

Later I installed the version 8.2.0.3, and the problem is not there

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): _Shelly 1_
- [X] Tasmota binary firmware version number used: __8.2.0.6___
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: esptool
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
19:50:31 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"NAME":"Luci Salone Laterali","GPIO":[255,255,0,255,21,82,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}
19:50:31 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"Module":{"46":"Shelly 1"}}
19:50:32 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"GPIO0":{"0":"Nessuno"},"GPIO1":{"0":"Nessuno"},"GPIO2":{"0":"Nessuno"},"GPIO3":{"0":"Nessuno"},"GPIO4":{"21":"Relè1"},"GPIO5":{"82":"Switch1n"},"GPIO9":{"0":"Nessuno"},"GPIO10":{"0":"Nessuno"},"GPIO12":{"0":"Nessuno"},"GPIO13":{"0":"Nessuno"},"GPIO14":{"0":"Nessuno"},"GPIO15":{"0":"Nessuno"},"GPIO16":{"0":"Nessuno"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
19:51:59 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
19:51:59 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}
19:51:59 MQT: home/pianoterra/lucisalonelaterali/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Free":511,"Rules":""}

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS = {"Status":{"Module":46,"FriendlyName":["Luci Salone Laterali"],"Topic":"pianoterra/lucisalonelaterali","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:23:37","StartupUTC":"2020-05-06T17:28:46","Sleep":50,"CfgHolder":4617,"BootCount":11,"BCResetTime":"2020-05-06T17:00:27","SaveCount":33,"SaveAddress":"FB000"}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS2 = {"StatusFWR":{"Version":"8.2.0.6(4abf498-tasmota)","BuildDateTime":"2020-05-06T11:06:42","Boot":31,"Core":"2_7_0","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"432/699"}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Vodafone-37853567",""],"TelePeriod":300,"Resolution":"55A180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00000200","00000000"]}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS4 = {"StatusMEM":{"ProgramSize":585,"Free":416,"Heap":23,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashMode":3,"Features":["00000410","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS5 = {"StatusNET":{"Hostname":"LuciSaloneLaterali","IPAddress":"192.168.1.59","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"68:C6:3A:FA:FE:6A","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.13","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_FAFE6A","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS7 = {"StatusTIM":{"UTC":"2020-05-06T17:52:23","Local":"2020-05-06T19:52:23","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"06:20","Sunset":"21:13"}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS10 = {"StatusSNS":{"Time":"2020-05-06T19:52:23","Switch1":"OFF"}}
19:52:23 MQT: home/pianoterra/lucisalonelaterali/STATUS11 = {"StatusSTS":{"Time":"2020-05-06T19:52:23","Uptime":"0T00:23:37","UptimeSec":1417,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Vodafone-37853567","BSSId":"2C:91:AB:D3:3F:43","Channel":11,"RSSI":100,"Signal":-50,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
In 
homeassistant/sensor/FAFE6A_status/config = {"name":"Shelly 1.........
not appear the correct friendly name, but always "Shely 1"

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

19:54:55 MQT: homeassistant/sensor/FAFE6A_status/config = {"name":"**Shelly 1** status","stat_t":"home/pianoterra/lucisalonelaterali/HASS_STATE","avty_t":"home/pianoterra/lucisalonelaterali/LWT","pl_avail":"Online","pl_not_avail":"Offline","json_attr_t":"home/pianoterra/lucisalonelaterali/HASS_STATE","unit_of_meas":"%","val_tpl":"{{value_json['RSSI']}}","ic":"mdi:information-outline","uniq_id":"FAFE6A_status","dev":{"ids":["FAFE6A"],"name":"Shelly 1","mdl":"Shelly 1","sw":"8.2.0.6(4abf498-tasmota)","mf":"Tasmota"}} (salvato)
1
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

In another shelly 1 with tasmota 8.2.0.3 the name is correct:
00:00:04 MQT: homeassistant/sensor/117288_status/config = {"name":"**Luce Palo Giardino** status","stat_t":"home/giardino/lucepalo/HASS_STATE","avty_t":"home/giardino/lucepalo/LWT","pl_avail":"Online","pl_not_avail":"Offline","json_attr_t":"home/giardino/lucepalo/HASS_STATE","unit_of_meas":"%","val_tpl":"{{value_json['RSSI']}}","ic":"mdi:information-outline","uniq_id":"117288_status","dev":{"ids":["117288"],"name":"Luce Palo Giardino","mdl":"Shelly 1","sw":"8.2.0.3(6f51fd4-tasmota)","mf":"Tasmota"}} (salvato)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

As designed. Now the name is the name of the Template and no more the friendlyname1 of the relay1.

Duplicated issue. Please, Check https://github.com/arendst/Tasmota/issues/8306 Thanks

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
