### ISSUE TITLE
Change the PWM minimum frequency limit from 100 to a lower one

### ISSUE THREAD

**Issue by dan-cristian** [arendst/Tasmota#8388]
**Have you looked for this feature in other issues and in the docs?**  
Yes
**Is your feature request related to a problem? Please describe.**  
_I need to control a heater via a Wemos D1 Mini, PWM and a SSR, the PWM frequency for this needs to be around 50 Hz. Currently Tasmota only allows 100Hz as minimum frequency_

**Describe the solution you'd like**  
_Reduce the frequency limit to 1. Why is it set to 100 anyways?_

**Describe alternatives you've considered**  
_I made this work with micropython but is not an easy solution_

**Additional context**  
_None_

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by effelle** [comment]
Have a look on PR #8255 to know why. 
If I remember correctly there is a long story behind this PR, better ask to @s-hadinger for more details.

**Comment by s-hadinger** [comment]
I don't know why the minimum was set to 100Hz and I don't see a reason why we couldn't lower this minimum.

Let me check with the Arduino code what is the absolute minimum frequency.

**Comment by s-hadinger** [comment]
I tried going to very low frequencies, below 20Hz it's getting chaotic. I suppose some timers overflow. I propose to make a quick patch in Tasmota to lower the minimum to 20Hz for now.

Please don't use low frequencies for LEDs, it's flashing like hell :)

**Comment by arendst** [comment]
That's why I choose 100Hz ;-)

**Comment by dan-cristian** [comment]
40 as minimum works well for me, many thanks!
