### ISSUE TITLE
When Temperature/Humidity info is null, Dew Point also should be null instead of 0.0 °C

### ISSUE THREAD

**Issue by marecabo** [arendst/Tasmota#8411]
### PROBLEM DESCRIPTION
Situation:
- A Sonoff switch with Tasmota 8.2.0.6 and GPIO2 configured as "SI7021 (3)".
- However, the DHT22 sensor is **not** physically connected.
- Temperature and humidity report "null °C" and "null %" respectively (as expected).

Issue:
- The dew point reports "0.0 °C" which is not a valid value in a situation, where there is no temperature and humidity information.

I would have expected it to report "null °C" for the dew point in that situation as well.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff RF, Sonoff Basic (Issue is reproducible on both)
- [x] Tasmota binary firmware version number used: 8.2.0.6
  - [x] Pre-compiled from https://thehackbox.org/tasmota/
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: OTA
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
MQT: stat/sonoff1/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
MQT: tele/sonoff1/STATE = {"Time":"2020-05-10T17:59:15","Uptime":"0T00:10:12","UptimeSec":612,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"*****","BSSId":"*****","Channel":1,"RSSI":92,"Signal":-54,"LinkCount":1,"Downtime":"0T00:00:06"}}
MQT: tele/sonoff1/SENSOR = {"Time":"2020-05-10T17:59:15","SI7021":{"Temperature":null,"Humidity":null,"DewPoint":0.0},"TempUnit":"C"}
MQT: stat/sonoff1/RESULT = {"Module":{"2":"Sonoff RF"}}
MQT: stat/sonoff1/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"3":"SI7021"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```

- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:

_I do not use rules._

- [x] Provide the output of this command: `Status 0`:

```
MQT: stat/sonoff1/STATUS = {"Status":{"Module":2,"FriendlyName":["Sonoff1"],"Topic":"sonoff1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
MQT: stat/sonoff1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/tasmota-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:10:58","StartupUTC":"2020-05-10T16:49:03","Sleep":50,"CfgHolder":4617,"BootCount":20,"BCResetTime":"2020-03-22T20:14:25","SaveCount":1112,"SaveAddress":"F9000"}}
MQT: stat/sonoff1/STATUS2 = {"StatusFWR":{"Version":"8.2.0.6(4d84a02-tasmota)","BuildDateTime":"2020-05-10T18:00:15","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"423/699"}}
MQT: stat/sonoff1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["*****",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
MQT: stat/sonoff1/STATUS4 = {"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE797","043683A1","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
MQT: stat/sonoff1/STATUS5 = {"StatusNET":{"Hostname":"sonoff1-1818","IPAddress":"192.168.179.51","Gateway":"192.168.179.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.179.1","Mac":"*****","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
MQT: stat/sonoff1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.179.48","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_46871A","MqttUser":"mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
MQT: stat/sonoff1/STATUS7 = {"StatusTIM":{"UTC":"2020-05-10T17:00:01","Local":"2020-05-10T18:00:01","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"05:14","Sunset":"20:18"}}
MQT: stat/sonoff1/STATUS10 = {"StatusSNS":{"Time":"2020-05-10T18:00:01","SI7021":{"Temperature":null,"Humidity":null,"DewPoint":0.0},"TempUnit":"C"}}
MQT: stat/sonoff1/STATUS11 = {"StatusSTS":{"Time":"2020-05-10T18:00:01","Uptime":"0T00:10:58","UptimeSec":658,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"*****","BSSId":"*****","Channel":1,"RSSI":94,"Signal":-53,"LinkCount":1,"Downtime":"0T00:00:06"}}}
```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
MQT: tele/sonoff1/SENSOR = {"Time":"2020-05-10T17:54:15","SI7021":{"Temperature":null,"Humidity":null,"DewPoint":0.0},"TempUnit":"C"}
```

### TO REPRODUCE

- A Sonoff switch with Tasmota 8.2.0.6 and GPIO2 configured as "SI7021 (3)".
- However, the DHT22 sensor is **not** physically connected.

### EXPECTED BEHAVIOUR
- Temperature and humidity report "null °C" and "null %" respectively (as expected) and dew point _should_ report "null °C" as well instead of "0.0 °C".

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/23156476/81505511-fe545480-92ef-11ea-9e31-51e1f79eab37.png)

### ADDITIONAL CONTEXT
When the sensor is connected, everything works fine. This issue is only about the default value of the dew point value in the situation where it cannot be computed.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
@marecabo

Theo have fixed this. Please try latest version from development branch.

Thanks.
