### ISSUE TITLE
Ifan03 not saving module configuration after reboot

### ISSUE THREAD

**Issue by savage008** [arendst/Tasmota#8446]
### PROBLEM DESCRIPTION
After flashing latest tasmota on my ifan03 ican configure wifi, but when i try to configure module type to ifan03 it restarts and the result is after restart is still says Sonoff Basic Module
But when i configure it to Shelly 2, after restart it will state it is a shelly 2. Or any other option in the module list, ive tried several. Even ifan02 wil work. after setting it to ifan03 restart takes longer than normal and it resets itself to Sonoff Basic Module

### REQUESTED INFORMATION
How can i debug this or sort this out?

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS = {"Status":{"Module":1,"FriendlyName":["Tasmota"],"Topic":"tasmota_9D6F7A","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Power On","Uptime":"0T00:43:14","StartupUTC":"2020-05-14T16:13:35","Sleep":50,"CfgHolder":4617,"BootCount":3,"BCResetTime":"2020-05-14T17:10:24","SaveCount":10,"SaveAddress":"FA000"}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS2 = {"StatusFWR":{"Version":"8.3.0(tasmota)","BuildDateTime":"2020-05-14T16:17:08","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"330/699"}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SavageWifi",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS4 = {"StatusMEM":{"ProgramSize":588,"Free":412,"Heap":27,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640C8","FlashMode":3,"Features":["00000809","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS5 = {"StatusNET":{"Hostname":"tasmota_9D6F7A-3962","IPAddress":"192.168.179.221","Gateway":"192.168.179.1","Subnetmask":"255.255.255.0","DNSServer":"84.116.46.22","Mac":"18:FE:34:9D:6F:7A","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_9D6F7A","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS7 = {"StatusTIM":{"UTC":"2020-05-14T16:56:49","Local":"2020-05-14T17:56:49","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"05:09","Sunset":"20:23"}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS10 = {"StatusSNS":{"Time":"2020-05-14T17:56:49"}}
17:56:49 RSL: stat/tasmota_9D6F7A/STATUS11 = {"StatusSTS":{"Time":"2020-05-14T17:56:49","Uptime":"0T00:43:14","UptimeSec":2594,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":296,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SavageWifi","BSSId":"38:43:7D:45:51:34","Channel":9,"RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by blakadder** [comment]
You're having bootloops which after certain number of reboots resets your configuration to defaul. Did you erase flash memory and do a fresh serial flash?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
