### ISSUE TITLE
MQTT Connect Fails rc=-2

### ISSUE THREAD

**Issue by mrburns42** [arendst/Tasmota#8456]
I have a Sonoff Bridge that fails to connect via MQTT to the broker.   The broker is working as two other devices running Tasmota are able to connect without issue.   One of the other devices is my backup Sonoff Bridge.    I will attach the working and non-working information screen data for the two Sonoff Bridges below.  
Now, full disclosure of the history.  The working one went from stock firmware to Tasmota.  The non-working one was programmed with ESPURA first as a trial and then was programmed with Tasmota.  I thought some crap was left in the FLASH, so I have tried several ways to erase it.  I have reset the configuration, did a reset 5, had the erase box checked in Tasmotizer, and downloaded esptools.py and ran the flash_erase from there.   All those actions completed successfully, however, this Bridge still fails to connect to MQTT and gives the dreaded r=-2.  I tried putting the minimal firmware on it, then upgrading and just leaving it as a BASIC sonoff to test only the MQTT connection.  That still fails. 
Any suggestions to getting this one working?    I guess for the cost of the device, I should just buy another one, but it bothers me that I cannot figure out this one's issue.  
Thanks.

[Sonoff Bridge Module_Fails.txt](https://github.com/arendst/Tasmota/files/4638494/Sonoff.Bridge.Module_Fails.txt)
[Sonoff Bridge Module_Works.txt](https://github.com/arendst/Tasmota/files/4638495/Sonoff.Bridge.Module_Works.txt)

**Comment by Jason2866** [comment]
Sorry no. You did not left any information about the device as requested in issue template
