### ISSUE TITLE
PowerCal Command Error

### ISSUE THREAD

**Issue by funboxbolzer** [arendst/Tasmota#8471]
Hallo Version ist 8.3.0

ich möchte gerne an der GosundSP112 den Watt Wert einstellen. Wenn ich den Befehl "PowerCal" in der Konsole eintrage, erscheint.
`04:52:19 CMD: PowerCal
04:52:19 MQT: stat/tasmota_031FBB/RESULT = {"Command":"Error"}`

ist das ein Bug oder mein Fehler?

**Comment by ascillato** [comment]
Please, search in issues. This has been already addressed.

The correct command is POWERSET

Thanks.
