### ISSUE TITLE
Wemos D1 mini the I2C not working GPIO4 GPIO5

### ISSUE THREAD

**Issue by smokey1300** [arendst/Tasmota#8490]
### PROBLEM DESCRIPTION
Upgraded my wemos mini from 6.3 now the i2c doesn't work with same connections

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
 00:00:00 CFG: Loaded from flash at F5, Count 31
00:00:00 Project tasmota Wemos51 Version 8.3.1(tasmota)-2_7_1
00:00:00 WIF: Connecting to AP1 Polytarp24 Channel 8 BSSId 18:EF:63:35:A8:20 in mode 11N as wemos51-2340...
00:00:01 WIF: Connected
00:00:01 HTP: Web server active on wemos51-2340 with IP address 192.168.1.51
01:55:34 MQT: Attempting connection...
01:55:34 MQT: Connected
01:55:34 MQT: tele/wemos51/LWT = Online (retained)
01:55:34 MQT: cmnd/wemos51/POWER = 
01:55:34 MQT: tele/wemos51/INFO1 = {"Module":"Generic","Version":"8.3.1(tasmota)","FallbackTopic":"cmnd/DVES_CAC924_fb/","GroupTopic":"cmnd/tasmotas/"}
01:55:34 MQT: tele/wemos51/INFO2 = {"WebServerMode":"Admin","Hostname":"wemos51-2340","IPAddress":"192.168.1.51"}
01:55:34 MQT: tele/wemos51/INFO3 = {"RestartReason":"Software/System restart"}
01:55:38 MQT: tele/wemos51/STATE = {"Time":"2020-05-20T01:55:38","Uptime":"0T00:00:09","UptimeSec":9,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":27,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Polytarp24","BSSId":"18:EF:63:35:A8:20","Channel":8,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:03"}}
01:55:38 MQT: tele/wemos51/SENSOR = {"Time":"2020-05-20T01:55:38","DS18B20":{"Id":"051671C9F3FF","Temperature":22.4},"TempUnit":"C"}
02:00:38 MQT: tele/wemos51/STATE = {"Time":"2020-05-20T02:00:38","Uptime":"0T00:05:09","UptimeSec":309,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Polytarp24","BSSId":"18:EF:63:35:A8:20","Channel":8,"RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:03"}}
02:00:38 MQT: tele/wemos51/SENSOR = {"Time":"2020-05-20T02:00:38","DS18B20":{"Id":"051671C9F3FF","Temperature":22.3},"TempUnit":"C"}
02:05:29 APP: Serial logging disabled
02:05:38 MQT: tele/wemos51/STATE = {"Time":"2020-05-20T02:05:38","Uptime":"0T00:10:09","UptimeSec":609,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Polytarp24","BSSId":"18:EF:63:35:A8:20","Channel":8,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:03"}}
02:05:38 MQT: tele/wemos51/SENSOR = {"Time":"2020-05-20T02:05:38","DS18B20":{"Id":"051671C9F3FF","Temperature":22.6},"TempUnit":"C"}


```

### TO REPRODUCE
upgraded from Tasmota 6.3 now my BMP280 module doesn't have any values. Same exact connection used GPIO4(SDA) and GPIO5(SCL) for the module

### EXPECTED BEHAVIOUR
MQTT values and console not showing values

### SCREENSHOTS
Main menu normally showed the values for Temp, Humidy, Pressure

### ADDITIONAL CONTEXT
The 18B20 sensor still connected to GPIO0 still working fine

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by smokey1300** [comment]
Upgraded from Tasmota 6.3 now the GPIO4 GPIO5 don't work for I2C

**Comment by ascillato** [comment]
Please, complete the troubleshooting template. We need that to troubleshoot your issue. Thanks.

**Comment by blakadder** [comment]
You failed to read changes that happened between versions. Your sensors are not supported in tasmota.bin anymore, download tasmota-sensors.bin.

**Comment by smokey1300** [comment]
> You failed to read changes that happened between versions. Your sensors are not supported in tasmota.bin anymore, download tasmota-sensors.bin.

Yeah okay I loaded this version it doesn't work either

**Comment by smokey1300** [comment]
I loaded v8.3.0 tasmota-sensors.bin and everything works good.

**Comment by meingraham** [comment]
@smokey1300 

Now that you have the device is working, can you try upgrading to the latest development version to see if the problem was with some corruption or settings mismatch? If the problem returns, then there may be an issue with 8.3.1 to investigate... and you can always downgrade to 8.3.0 to resolve it.

Thanks.

**Comment by smokey1300** [comment]
> @smokey1300
> 
> Now that you have the device is working, can you try upgrading to the latest development version to see if the problem was with some corruption or settings mismatch? If the problem returns, then there may be an issue with 8.3.1 to investigate... and you can always downgrade to 8.3.0 to resolve it.
> 
> Thanks.

@blakadder Already closed this issue with v8.3.1 although it is not resolved only that v8.3.0 works as intended on the Wemos with i2c.

**Comment by meingraham** [comment]
@smokey1300 

Closed because you had "resolved" _your_ issue by downgrading... but I'm not certain that this confirms an issue with your flash/settings or with 8.3.1. Can you try upgrading?

**Comment by Schrumpfschlauch** [comment]
@meingraham 

I had exact the same issue  -> upgrad to 8.3.1.1(sensors) solved it!
