### ISSUE TITLE
ESP32 with wired LAN and PoE

### ISSUE THREAD

**Issue by nagyrobi** [arendst/Tasmota#8503]
**Have you looked for this feature in other issues and in the docs?**  
The need to run Tasmota on Ethernet-connected devices is obvious. We could finally dump all the issues WiFi may cause in certain cases and build stable and secure systems relying on cables.

**Is your feature request related to a problem? Please describe.**  
wESP32 is a very professional approach to the ESP family. https://wesp32.com/

Basically what it does is that it uses some of the ESP32-WROOM-32 pins connected to an Ethernet PHY module, which is also **PoE** (supporting IEEE 802.3at standard and passive modes) not only for powering the ESP module itself, but also giving enough power to other accessories like sensors etc.

In the original firmware the module's _WiFi part can be still used as a redundant backup connection_ to the network when wired network fails.

**Describe the solution you'd like**  
Please add support for this wESP32 module, now that ESP32 platform starts to be supported by Tasmota.

**Describe alternatives you've considered**  
There are none so far.

**Additional context**  
![kép](https://user-images.githubusercontent.com/1550668/82547490-20549f00-9b5a-11ea-9d3c-82b660050161.png)

I am aware this is not going to happen with two clicks, but it's worth the effort.

**Comment by s-hadinger** [comment]
The device costs 50€. That's quite high, especially compared to a regular esp32 and a POE splitter.

**Comment by nagyrobi** [comment]
It's not just an esp32 and a POE splitter. It has an Ethernet PHY module on it, allowing wired LAN connections with the module. How many other such modules are out there?

**Comment by Jason2866** [comment]
@s-hadinger  this board looks interesting https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

**Comment by nagyrobi** [comment]
Good find!
![kép](https://user-images.githubusercontent.com/1550668/82582411-501f9900-9b92-11ea-91e8-65e74f08a45c.png)
Let's collect all such models in this issue.

**Comment by ascillato2** [comment]
Have you tested if LAN connection works fine using Arduino core? Do you have any small sketch using that ethernet chip?

**Comment by nagyrobi** [comment]
Look here: https://github.com/OLIMEX/ESP32-POE

**Comment by s-hadinger** [comment]
Tasmota, esp32, ble, poe, ethernet, arduino compatible and affordable. I start to like it very much. Nice find!

**Comment by hagenbuch** [comment]
I support this feature request strongly: This family of devices need some power supply, running from a battery is mostly impossible du to the relatively high power demand of the Wifi.

Therefor, it is an advantage if we can power it via one cable only, thus Ethernet/LAN.

Also, ESP32 is one of the rare chips able to handle HTTPS / SSL / TLS properly. This is a precondition to maiking things like electrical door locks and the like...

It would be awesome if you could add LAN support...

**Comment by cg089** [comment]
+1 for ethernet support (esp32-poe works like a charm with ethernet and esphome)

**Comment by dweston** [comment]
> The device costs 50€. That's quite high, especially compared to a regular esp32 and a POE splitter.

@s-hadinger US$55 for a 1 off wESP32 is expensive, I agree. However it can be purchased in volume with a price as low as US38/unit in quantities >100. At that latter price it is starting to become realistic as a LED driver/sensor board when you take into account the board can deliver circa 13W @ 12V. PoE driven LED lighting becomes feasible when driven from a variety of cost effective PoE switches. I'm using [Netgear GS728TP](https://www.netgear.com/support/product/GS728TP.aspx) switches, which have a 190W total PoE power budget supplied from 16 PoE 802.3af ports (15W capable) and 8 PoE+ 802.3at (38W capable) ports [[can be purchased on eBay for as low as US $169.00](https://www.ebay.com.au/itm/NetGear-ProSafe-GS728TP-100NAS-24-Ports-Rack-Mountable-Ethernet-Switch/333378110345?epid=168468271&hash=item4d9ee24389:g:ygsAAOxylh1SKjrb&frcectupt=true)]. Averaged out over many ports, taking into account the cost of conventional LED power supply components provision & installation, results in a more manageable cost overall. Furthermore the GS728TP can be monitored and controlled via SNMP, enabling innovation in sector lighting energy management. Quiescent  power consumption of many LED drivers can be as high as several watts even with the luminaire (LED) fully turned off. So being able to fully disable the power supply to multiple drivers based on ambient light and body movement is attractive as well.

The dilemma remains with which firmware to implement on these devices. ESPHome on the wESP32 or the Olimex ESP32 PoE boards currently appears to be the way to go, but the prospect that a Tasmota variant is really the ultimate Holy Grail.

**Comment by s-hadinger** [comment]
Interesting perspectives. I believe anything above the $20 limit makes it harder for makers to hack and break. I'm still waiting my Olimex to arrive.

Tasmota on ESP32 is still early stage, but promising. Theo is very active on this front.

In order to drive LEDs at 13W, you will need both the on-board POE power supply to be sized for it (are they?) and some power drivers for the LEDs (MOSFET?). And a nice case to make it pretty.

**Comment by nagyrobi** [comment]
Where do you take this $20 limit from? 
As soon as Theo provides a statement that wESP32 can run Tasmota, I'll be sure to order at least 2 pieces. I'm pretty fed up with unreliable chinese pieces, and WiFi coverage issuses in certain cases. wESP32 seems to be a premium quality and I am willing to wire up things as much as possible.
And I bet I'm not the only one thinking like that.

**Comment by lbernstone** [comment]
Direct from the manufacturer:
https://www.mouser.com/new/espressif/espressif-esp32-ethernet-kit/

**Comment by arendst** [comment]
Ordered the olimex iso one to play with...

**Comment by hagenbuch** [comment]
I can send you one for free, we are in Germany, right?

**Comment by arendst** [comment]
We are in the Netherlands, small province of Germany ;-)

**Comment by hagenbuch** [comment]
Not yet :) Well I can send it to the Netzerlands too if you like.

**Comment by arendst** [comment]
Pls mail me from the github mainpage

**Comment by hagenbuch** [comment]
Done :)

**Comment by TrDA-hab** [comment]
https://norvi.lk/industrial-esp32-norvi-iiot/

**Comment by hagenbuch** [comment]
Yeah thanks, close but no LAN / Ethernet. Wifi inside a metal box is not exactly what I need :)

**Comment by TrDA-hab** [comment]
@hagenbuch 
Sorry!
https://aliexpress.ru/item/4000016520686.html
https://aliexpress.ru/item/4000188817036.html
https://www.olimex.com/Products/IoT/ESP32/ESP32-GATEWAY/open-source-hardware
https://olimex.wordpress.com/2017/02/09/esp32-evb-our-new-board-for-iot-first-prototypes-are-ready/

**Comment by hagenbuch** [comment]
Thank you. I knew most of the. Now the only question is: Are they all supported by tasmota and / or how do we make a configuration file for them if they are not yet supported?

**Comment by nagyrobi** [comment]
Well, hopefully soon we will be able to make a config almost the same way as we would do with the ESP8266-based units.

Today I was in a place where I could have instantly suggested to use Tasmota for a small automation task, but was not able to because of the WiFi requirement of ESP8266. Here only Ethernet is available and deploying WiFis just for this reason is simply unacceptable.

**Comment by Jason2866** [comment]
@nagyrobi @hagenbuch @TrDA-hab 
Since Theo ordered a Olimex ESP32 ISO he will work on (for sure).
Just give him a little time. It is done when it is done 😊

**Comment by nagyrobi** [comment]
I don't mean to rush anyone. I was just emphasizing that the need of LAN without any WiFi is a real need.

**Comment by arendst** [comment]
Currently only works on Olimex ESP32-PoE and I haven't tesetd the PoE functionality yet ;-)

**Comment by BBBits** [comment]
loaded the new build on an Olimex ESP32-PoE & noticed a couple of things.
device rebooted repeatedly while connected via eth. It is still requiring the AP mode to be configured before it will stop restarting. can this be disabled by default ?

Lables for the different interfaces would make it clearer what is what in the information page.
I.E. eth_hostname ,eth_mac ,eth_ip  etc
![tas32 info](https://user-images.githubusercontent.com/6020029/84741147-b2897f00-b002-11ea-99f8-f890a6d9ba16.JPG)

**Comment by arendst** [comment]
> It reboots repeatedly

Within seconds or every three minutes? If it's every 3 minutes you could have changed either ``wificonfig`` or disabled wifi al together with ``wifi 0``. You could also have configured the correct wifi credentials to make it stop starting the AP mode.

> Lables for the different interfaces would make it clearer what is what in the information page.

The top IP address is the ethernet IP address as can be seen from the Hostname ending in ``_eth``. The second IP address is the wifi address. The third one is an AP address although at that time the AP is not even running. A remnant from the ESP32 implementation.

**Comment by arendst** [comment]
Were you able to use PoE?

**Comment by BBBits** [comment]
POE working fine,
It rebooted every 3 mins perhaps , didn't time it. wasn't a short time.
I do see what ip info is where , but it would make sense to define them clearly.
there are  lables all saying IP Address without specifically associating it to an interface.

**Comment by BBBits** [comment]
I have disabled wifi to stop it restating , 
In the big picture , I would like to have all the local esp82xx's connect to the esp32 AP.
can I leave the AP running without it rebooting ?

**Comment by arendst** [comment]
Currently you can't as the implementation is still based on esp8266 initial installation. How many clients do you expect the ESP32 can service? I don't know but I'm not expecting that many.

**Comment by kugelkopf123** [comment]
As far as i know there is a limit set to 10 devices on AP mode.

**Comment by arendst** [comment]
Ok. This looks better.

![image](https://user-images.githubusercontent.com/11044339/84776575-c328fd80-afe0-11ea-89ce-cfea7ae30053.png)

Now also tested with a Ubiquiti PoE adapter GP-V480-032G. 
Another Ubiquiti PoE adapter GP-A240-050G fails to power my Olimex.

**Comment by arendst** [comment]
With the latest commit you get three new commands to configure "any" ESP32 ethernet interface either based on LAN8720 (Olimex) or TLK110.

You will also need a template for the Olimex to function well so before upgrading first install this template.

```
{"NAME":"Olimex ESP32-PoE","GPIO":[65504,65504,65504,65504,65504,65504,0,0,5536,65504,65504,65504,65504,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,65504,65504,65504,65504,65504,0,0,65504],"FLAG":0,"BASE":1}
```

**Comment by nagyrobi** [comment]
Theo, please be aware that according to the Ethernet standards a client device cannot have more than one default gateway set. Units operating with more gateways are the routers, which based on various (manual or automatic) routing tables are able to route traffic according to these.

I guess it's not the scope of ESP32 to implement an entire routing platform so may I suggest to draw a line here and accept a statement that a device can only have one single default gateway set. Things can get complicated when a user connects with a device to two different networks using DHCP for example. Which one will win? The last one which connected will always overwrite the default gateway address?

Perhaps a kind of priority setting would be helpful here, helping to decide which interface is allowed to set the default gateway using DHCP and when.
For example:
- Priority Ethernet: the default gateway is set from Ethernet when link established. When Ethernet not connected, default gateway can be set from WiFi.
- Priority WiFi (the other way around):  the default gateway is set from WiFi when connected. If wifi not connected, default gateway can be set from Ethernet.
These all above of course only when using DHCP or with static addresses and default gateway set. One could configure manually static address to the interface and not set a default gateway - that's the easiest case because you take the default gateway from the other one.

Whenever the default gateway address changes due to intermittent connectivity, network connections have to be reset.

**Comment by nagyrobi** [comment]
> Another Ubiquiti PoE adapter GP-A240-050G (24V) fails to power my Olimex.
Note that this is not a standard 802.3af PoE adapter, this is a so-called passive, older Ubiquiti-proprietary adapter. This shouldn't work.

**Comment by BBBits** [comment]
Thanks Theo, good having the isolation between the interfaces.
My usage idea is not huge.
although I have a heap of devices , 
there are only 6 mini's  that are hard wired to lights and also controlled by PIR's. the extra switch Input just sends out knx packets on some of them.
I was hoping to just connect those 6 devices to the ESP32  .
Haven't considered all the network issues yet but think an isolated one is probably less caos than a bridge. was considering changing the knx to broadcast instead of multicast on the isolated network.

**Comment by arendst** [comment]
@nagyrobi thanks for the PoE adapter info. Makes sense to me. I've also readup on this and noticed there is PoE and PoE.

Regarding the "router" functionality it will indeed NOT be supported by Tasmota. The fact you saw the AP info in the information page was just a remnant from the ESP8266 to ESP32 conversion which is fixed now; the AP was never allive.

![image](https://user-images.githubusercontent.com/11044339/84876969-2f127100-b088-11ea-92ba-e398dbc8d900.png)

So for now let's close this issue as being fixed and see when other ethernet hardware turns up what is not supported by the current solution. At least PoE is transparent to the software solution as far as I can see.

**Comment by dweston** [comment]
@nagyrobi have you tried flashing a wESP32 with this latest version of Tasmota32 as yet?

I have access to one of these modules with an IoT dev group I'm working with. I'm in the process of retrieving it in order to try flashing it with this latest version. If I'm successful I'll report it here.

**Comment by nagyrobi** [comment]
My wESP32 and Olimex are still on the way...

**Comment by BBBits** [comment]
i think there is an issue with the interface used as gateway.
If I turn wifi off , timeserver is not contacted & we stay at 1970
Enable wifi & ntp update is ok

**Comment by nagyrobi** [comment]
Yep, that's what I was talking about. Extra care should be taken when enabling/disabling interfaces: unless somebody deliberately wants to avoid using gateway addresses (static IP without gateway set), it should be ensured that **only one** gateway address is **always set**, no matter how interfaces go up or down.

**Comment by arendst** [comment]
There is only one gateway address supported within Tasmota. There is also only one network supported within Tasmota. So both ethernet AND wifi have to be in the same network if enabled.

The latest commit makes sure that if ethernet only is configured the DHCP supplied gateway, netmask and DNS server are set correctly.

**Comment by nagyrobi** [comment]
If both ethernet and wifi are in the same network, how does Tasmota decide which interface is actually used when sending packets? For example, when contacting the NTP server?

**Comment by arendst** [comment]
I don't know. Does it matter as long as it's the same network? I know Tasmota does nothing with regards to network selection.

**Comment by nagyrobi** [comment]
It does, as network switches handle packets based on MAC address in Layer2 networking (the same network). It will cause trouble if a packet goes out on one interface, but answer is coming back on the other. If we go one layer up, where the wifi interface and the ethernet interface have different IP addresses, communication will not establish if packet is sent out via one IP and the answer is coming back to the other.

With such an ESP32 having both LAN and WiFi we usually want redundant (backup) connections to achieve higher reliability, some kind of priority system would make the system more aware of what's happening there, like detect when ethernet link drops, and then automatically switch on to WiFi, and switch WiFi off as soon as Ethernet comes back etc

**Comment by arendst** [comment]
Understand. Will need to dive deep in the espressif/arduino/esp32 core code of available features to find how to bind what to what.

If anyone feels the need too I'm open for any hints.

**Comment by nagyrobi** [comment]
https://github.com/nodemcu/nodemcu-firmware/blob/dev-esp32/components/modules/eth.c
see
```
  { "start",            SYSTEM_EVENT_ETH_START,           empty_arg     },
  { "stop",             SYSTEM_EVENT_ETH_STOP,            empty_arg     },
  { "connected",        SYSTEM_EVENT_ETH_CONNECTED,       empty_arg     },
  { "disconnected",     SYSTEM_EVENT_ETH_DISCONNECTED,    empty_arg     },
  { "got_ip",           SYSTEM_EVENT_ETH_GOT_IP,          eth_got_ip    },
```
also `#include "eth_phy/phy_ip101.h"` - this is another module type?

**Comment by hagenbuch** [comment]
To Theo and all the others involved: Thank you very much for working so much on the ESP32 / Olimex version. Unfortunately, i am not able to contribute right now but as soon as I have more time, i will  :)

**Comment by Jason2866** [comment]
Should be no problem, ethernet and Wifi -> there is no bridge

**Comment by nagyrobi** [comment]
OK let's see it in action...

**Comment by Jason2866** [comment]
and Lwip NAT is Arduino standard  ;-)
To get a bridge running is "some" work. It will not happen by accident ;-)

**Comment by arendst** [comment]
@nagyrobi I see nothing binding related in the NodeMcu code. It's more or less a copy of the espressif code with an addition of type IP101.

See my xdrv_82_ethernet.ino also considering the callbacks you mention specifically, they are there too.

So for now indeed let's see when things get out of hands.

In the worst case I can always decide to support either ethernet OR wifi.

**Comment by BBBits** [comment]
Still having issues with ntp.
had a sniff around support_rtc.ino
in RtcSecond() 
Rtc.ntp_time = sntp_get_current_timestamp();  Is Not called if global_state.wifi_down

changed 
if (!global_state.wifi_down) {
To
if ((!global_state.wifi_down)||(!global_state.eth_down)) {
And it now updates time.
So not an interface gateway problem.

**Comment by arendst** [comment]
I'm afraid I didn't sync all my ethernet related changes correctly. NTP worked fine for me as I had this change locally. I'll revisit the differences as I was quite sure I changed most wifi_down to network_down already although not all must be changed.

My fault. Sorry.

**Comment by arendst** [comment]
Verified to work too:

![ESP32-POE-ISO-2](https://user-images.githubusercontent.com/11044339/85033976-d6bf9a00-b181-11ea-8669-3425133db77c.jpg)

**Comment by nagyrobi** [comment]
Trying tasmota32-sensors.bin from the [precompiled binaries](https://github.com/arendst/Tasmota/tree/firmware/firmware/tasmota32) but I get:
```
14:53:35 CMD: Ethernet
14:53:35 RSL: stat/tasmota_B90D58/RESULT = {"Command":"Unknown"}
```

**Comment by Jason2866** [comment]
@nagyrobi  You need in your `user_config_override.h` following defines:

`#define USE_ETHERNET`

**Comment by nagyrobi** [comment]
Ah ok. Any chance to enable `USE_ETHERNET` for the daily dev builds?

**Comment by nagyrobi** [comment]
Working on wESP32:
![kép](https://user-images.githubusercontent.com/1550668/85151450-148cf300-b254-11ea-991e-2adcf7ef451a.png)

**Comment by nagyrobi** [comment]
Template for wESP32:
`{"NAME":"wESP32","GPIO":[0,0,1,0,1,1,0,0,1,1,1,1,5568,5600,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}`

@arendst what's the difference between 65504 and 1 inside the template?

**Comment by arendst** [comment]
To make the template more readable I changed 65504 to 1 in the template (handling). It also makes the text length more managable. Tasmota internal still uses 65504 but that's transparent to the user. Pls stop using 65504.

> Any chance to enable USE_ETHERNET for the daily dev builds?

As ethernet uses the same GPIOs as hardware SPI it would need to become a seperate binary. I need to make a table of what can be used together with what regarding ESP32.

**Comment by nagyrobi** [comment]
For wESP32:
![kép](https://user-images.githubusercontent.com/1550668/85152352-2fac3280-b255-11ea-97a9-d61a460c335b.png)

Ethernet module is on GPIO 16 and 17.

**Comment by nagyrobi** [comment]
> Pls stop using 65504.
You've posted a template for Olimex using 65504 instead of 1. I also noticed that Configure Template in the webinterface is broken when using 1's, but loads correctly when using 65504.

So the correct template should be this?
`{"NAME":"wESP32","GPIO":[0,0,1,0,1,1,0,0,1,1,1,1,5568,5600,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}`

**Comment by arendst** [comment]
> Ethernet module is on GPIO 16 and 17.

That's what tasmota want you to configure as those GPIO's are different on all Ethernet implementation. What the Ethernet driver ``xdrv_82_ethernet.ino`` does for you is handling GPIO's as documented in the beginning of the file. Excerpt:
```
/*********************************************************************************************\
 * Ethernet support for ESP32
 *
 * Dedicated fixed Phy pins
 * GPIO17 - EMAC_CLK_OUT_180
 * GPIO19 - EMAC_TXD0(RMII)
 * GPIO21 - EMAC_TX_EN(RMII)
 * GPIO22 - EMAC_TXD1(RMII)
 * GPIO25 - EMAC_RXD0(RMII)
 * GPIO26 - EMAC_RXD1(RMII)
 * GPIO27 - EMAC_RX_CRS_DV
 *
 * {"NAME":"Olimex ESP32-PoE","GPIO":[1,1,1,1,1,1,0,0,5536,1,1,1,1,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
 * {"NAME":"wESP32","GPIO":[1,1,1,1,1,1,0,0,0,1,1,1,5568,5600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}
 *
\*********************************************************************************************/
```
So ther is a lot more to it than thos two user GPIO's

**Comment by nagyrobi** [comment]
On both Olimex and wESP32 I experience ocasional timeout errors in the browser. WiFi, Ethernet, both produce this.

**Comment by arendst** [comment]
Correct. Be my guest to find a solution knowing that the errors are produced by the core software (Not Tasmota).

**Comment by nagyrobi** [comment]
Any reason why your wESP32 template differs from mine? I've double checked the pins available on the board...

**Comment by arendst** [comment]
Yours is the correct one.

**Comment by Jason2866** [comment]
@nagyrobi  You can find a unofficial Ethernet build from latest development branch here:
https://github.com/Jason2866/Merge/tree/firmware

**Comment by BBBits** [comment]
Hi Theo, Instead of starting a new issue , thought I would use this one.
Tried a DHT11 on the ESP32
when DhtPinState is called , XdrvMailbox.index has been loaded with 1184 hence the driver fails to initialize.
`if ((XdrvMailbox.index >= GPIO_DHT11) && (XdrvMailbox.index <= GPIO_SI7021)) {`
I couldn't find where it is initialized to do the (>>5) on the value or whatever else is required.
Barry

**Comment by arendst** [comment]
Ah thnx. I missed that one. Will fix.

**Comment by arendst** [comment]
I see intermittent
```
15:35:12 DHT: Timeout waiting for start signal high pulse
15:36:06 DHT: Timeout waiting for start signal high pulse
15:36:20 DHT: Timeout waiting for start signal high pulse
15:36:22 DHT: Timeout waiting for start signal high pulse
15:36:32 DHT: Checksum failure 01 5A 00 0F 6B =? 6A
15:36:44 DHT: Timeout waiting for start signal high pulse
15:36:56 DHT: Timeout waiting for start signal high pulse
```
probably as a result of timing issue differences on ESP32. For now I leave fixing to the community

**Comment by thermseekr** [comment]
Gentlemen,

THANK YOU THANK YOU THANK YOU so much for this. I have a couple Olimex PoE boards sitting for almost two years in my "one day" box which I bought dreaming that one day :) Tasmota would support them. Looks like this day has arrived, and now I can start desiging the automation for my new home. Construction starts second half of 2021, and will include a technical room where all things energy, datacomm and automation will reside. All cabled :)))

Wish you a very happy new year. 

Tales

**Comment by labmaster** [comment]
Great Work 

sorry for a maybe stupid question.
I have compiled a Tasmota32 Version with Ethernet Support (10.1.0) flashed it on a Olimex POE board and it works works so far. (with DHCP)
Now i need to set fixed specific IP addresse for the ethernet port.
I have tried to find information on this but without success.


Even if i have to do it directly in the sourcecode it would be fine.
(i already checked "xdrv_82_esp32_ethernet.ino" but was not able to modifiy it to have a fixed IP.)

Any hint ?  

Many Thanks
Walter

**Comment by nagyrobi** [comment]
If you want to assign a static IP address click on the console button on the Tasmota webpage. Enter:` ipaddress1 [input your desired IP address]` then `restart 1` to apply the changes. Commands `ipaddress2` and `ipaddress3` set the _gateway_ and _netmask_.

**Comment by labmaster** [comment]
Thanks for your answer
unfortunately i can not find anything about changing the ethernet interface IP there, only the common way to change the Wifi IP, or do i miss something ?

**Comment by nagyrobi** [comment]
it's the same for wifi and ethernet I assume

**Comment by labmaster** [comment]
No, command ipaddress1 only affects Wifi.,
If wifi is disabled (command Wifi 0) then command  ipaddress1 does nothing

**Comment by barbudor** [comment]
Indeed there is today no commands
I've taken the action to work on that.
Please wait until end of the week

**Comment by labmaster** [comment]
That would be really great.

**Comment by barbudor** [comment]
That has already been done
Commands for ESP32 ethernet configuration EthIpAddress, EthGateway, EthSubnetmask, EthDnsServer1 and EthDnsServer2 (#14385)

**Comment by thermseekr** [comment]
Awesome! Thank you very much!

**Comment by Stonedfield** [comment]
I am successfully using the WT32-ETH01 with Ethernet only and like to know if it is possible to disable WiFi by default already in user_config_override.h as I am never want to use the WiFi option at no time.

**Comment by ascillato** [comment]
> ...if it is possible to disable WiFi by default already in user_config_override.h as I am never want to use the WiFi option at no time.

in _user_config_override.h_ you can add:

```cpp
#define USER_RULE1 "ON system#boot DO wifi 0 ENDON"
#define USER_BACKLOG "Rule1 1"
```

Remember to erase all flash before flashing (or do `reset 1` afterwards) so as to make Tasmota use the defaults you put in _user_config_override.h_

**Comment by smartboart** [comment]
Hi thanks for the ethernet olimex poe tasmota Firmware...since Update to 11.0.0.1 the ethernet Connecticut does not work Anymore..anybody Else with this issue here? Can i get ethernet Version 10.0.0.1 somewhere to download again?

**Comment by barbudor** [comment]
There is no standard Tasmota build for the Olimex board
If you want Ethernet support you should compile your own build as specified in the docs.

**Comment by labmaster** [comment]
@smartboart 
Here is a binary for the Olimex ESP-POE with included Ethernet driver support:
[tasmota32.factory.zip](https://github.com/arendst/Tasmota/files/8102932/tasmota32.factory.zip)

This binary is compiled with the following  "my_user_config.h" and "platformio_override.ini"
[config.zip](https://github.com/arendst/Tasmota/files/8102935/config.zip)

Maybe this is useful for you.

**Comment by smartboart** [comment]
Hello i have already installed pre Compiled bin file 10.0.0.1which is fine for olimex.. from jason2866..see link..
https://github.com/Jason2866/Merge/tree/firmware
His old Version Was food...11.0.0.1 from this link des not work ..
I Found his Version 10 again..

**Comment by smartboart** [comment]
Here ist ethernet pre compiled v11..https://github.com/Jason2866/Tasmota-specials/blob/firmware/firmware/tasmota32/other/tasmota32-ethernet.bin

**Comment by smartboart** [comment]
Here is pre compiled v10 which works
https://github.com/Jason2866/Tasmota-specials/blob/v10.1.0/firmware/tasmota32/other/tasmota32-ethernet.bin

**Comment by barbudor** [comment]
If Jason 's ethernet v11 doesn' t work please open a new issue and provide all required informations

**Comment by dexterbot80** [comment]
Hello. Can you help me to enable ethernet port for OLIMEX ESP32-GATEWAY board ? I use Tasmota V10 pre ethernet compiled.
My RJ45 leds blinking but i do not be able to connect the board to the network using the ethernet port.
[ESP32-GATEWAY.pdf](https://github.com/arendst/Tasmota/files/8884536/ESP32-GATEWAY.pdf)
Thank you

**Comment by sfromis** [comment]
I have no experience with that board, but as a first longshot, I'd be strongly tempted to try if the template for another ESP32 Ethernet device from Olimex "happens" to work.
https://templates.blakadder.com/olimex_ESP32-POE.html

More generally, the config commands EthAddress, EthClockMode and EthType needs to match the hardware.
https://tasmota.github.io/docs/Commands/#ethernet
Default values may work, but not for all boards....

**Comment by s-hadinger** [comment]
I will check tomorrow with Olimex POE but I believe that the default values match Olimex Ethernet boards for Eth parameters

**Comment by dexterbot80** [comment]
Hello, #ethernet commands  not working for OLIMEX ESP32-GATEWAY? I can't set static ip 
Can anyone tell me what I'm doing wrong here?
Thanks

```
04:04:07.171 CMD: Ethernet
04:04:07.183 MQT: stat/SGP30_LIVING/RESULT = {"Ethernet":"ON"}
04:04:20.096 CMD: EthAddress
04:04:20.109 MQT: stat/SGP30_LIVING/RESULT = {"EthAddress":0}
04:04:30.215 CMD: EthClockMode
04:04:30.228 MQT: stat/SGP30_LIVING/RESULT = {"EthClockMode":3}
04:04:42.633 CMD: EthType
04:04:42.647 MQT: stat/SGP30_LIVING/RESULT = {"EthType":0}
04:04:56.206 CMD: EthIpAddress
04:04:56.219 MQT: stat/SGP30_LIVING/RESULT = {"Command":"Unknown"}
04:05:07.877 CMD: EthGateway
04:05:07.891 MQT: stat/SGP30_LIVING/RESULT = {"Command":"Unknown"}
04:05:20.956 CMD: EthSubnetmask
04:05:20.969 MQT: stat/SGP30_LIVING/RESULT = {"Command":"Unknown"}

```

**Comment by sfromis** [comment]
Probably using a too old Tasmota binary. Docs try to match current binaries, and new features are added often.

**Comment by dexterbot80** [comment]
Hello, It is posible to use BME680 and SGP30 sensors with OLIMEX ESP32 POE and Tasmota **ethernet** connected ? Thank you

**Comment by sfromis** [comment]
Yes

**Comment by dexterbot80** [comment]
> Yes
Thanks for the extremely quick response.
You could help me with a bin file

**Comment by sfromis** [comment]
Just the standard tasmota32.bin

**Comment by dexterbot80** [comment]
> 
I need to use BME680 and SGP30 sensors on I2c

**Comment by sfromis** [comment]
Obviously, and that was what my answer covers.

**Comment by dexterbot80** [comment]
I understand, so in standard tasmota32 bin I activate the i2c pins and the BME680 and SGP30 sensors will be detected automatically. Brilliant
Can you help me with the latest version please? Thank you professor :)

**Comment by Jason2866** [comment]
There is a big help, our docu ;-)  https://tasmota.com

**Comment by dexterbot80** [comment]
i see the website but when i install Visual Studio and Platformio my computer crash - esp 32 is more faster than my PC :)

**Comment by sfromis** [comment]
Why do you start with Visual studio and all that? The page linked has a bold **Install Tasmota using....**

**Comment by dexterbot80** [comment]
Hi, Do you say that the ethernet port can be activated on tasmota32-allsensors.bin for example?

**Comment by sfromis** [comment]
You do not need allsensors for what you posted about, just use the default Tasmota build.

**Comment by Jason2866** [comment]
Anyway, if will lock this CLOSED issue. If you have questions. Please open in Discussions.
