### ISSUE TITLE
NodeMCU not connecting after wifi configuration

### ISSUE THREAD

**Issue by dikodahan** [arendst/Tasmota#8521]
### PROBLEM DESCRIPTION
Flashed a NodeMCU with the latest Tasmota (8.3.1). Was able to connect to it via the tasmota-XXXXXX wifi network without any issues. I configured my wifi network and after rebooting it refuses to connect to my wifi network.

The error message I am getting in the Arduino IDE monitor is:

```
00:09:43 WIF: Connecting to AP1 XXXXXXXXX in mode 11N as NodeMCU...
00:09:52 WIF: Connect failed as AP cannot be reached
```

I tried to install it as a bin file with a flasher program and also through the Arduino IDE. In all cases the initial wifi worked but after setting the wifi network credentials it is not connecting.
I obviously configured the 2.4GHz network SSID and PW correctly.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X ] Device used (e.g., Sonoff Basic): NodeMCU 1.0
- [ ] Tasmota binary firmware version number used: 8.3.1
  - [X ] Pre-compiled
  - [ ] Self-compiled
    - [ X] IDE / Compiler used: Arduino IDE 1.8.12
- [ X] Flashing tools used: NodeMCU-PyFlasher-4.0
- [ X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here: 
00:00:14 CMD: Backlog Template; Module; GPIO 255
00:00:14 RSL: stat/tasmota_0F1BB9/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
00:00:14 RSL: stat/tasmota_0F1BB9/RESULT = {"Module":{"1":"Sonoff Basic"}}
00:00:14 RSL: stat/tasmota_0F1BB9/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
00:03:24 CMD: Backlog Rule1; Rule2; Rule3
00:03:24 RSL: stat/tasmota_0F1BB9/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
00:03:25 RSL: stat/tasmota_0F1BB9/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
00:03:25 RSL: stat/tasmota_0F1BB9/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}

```
- [ X] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
00:02:23 CMD: Status 0
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_0F1BB9","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"0T00:02:24","StartupUTC":"","Sleep":50,"CfgHolder":4617,"BootCount":6,"BCResetTime":"1970-01-01T00:00:00","SaveCount":9,"SaveAddress":"3FA000"}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-05-23T23:57:00","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"334/699"}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["security-md",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS4 = {"StatusMEM":{"ProgramSize":635,"Free":2436,"Heap":29,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":2,"Features":["00000809","8FDAE797","003683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS5 = {"StatusNET":{"Hostname":"NodeMCU","IPAddress":"(IP unset)","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"2C:3A:E8:0F:1B:B9","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
00:02:23 RSL: stat/tasmota_0F1BB9/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0F1BB9","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
00:02:24 RSL: stat/tasmota_0F1BB9/STATUS7 = {"StatusTIM":{"UTC":"1970-01-01T00:02:23","Local":"1970-01-01T00:02:23","StartDST":"1970-01-01T00:00:00","EndDST":"1970-01-01T00:00:00","Timezone":"+00:00","Sunrise":"20:13","Sunset":"05:47"}}
00:02:24 RSL: stat/tasmota_0F1BB9/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:02:24"}}
00:02:24 RSL: stat/tasmota_0F1BB9/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:02:24","Uptime":"0T00:02:24","UptimeSec":144,"Heap":29,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":33,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"security-md","BSSId":"FF:FF:FF:FF:FF:FF","Channel":7,"RSSI":100,"Signal":31,"LinkCount":0,"Downtime":"0T00:00:00"}}}

```
- [ X] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
00:04:16 CMD: weblog 4
00:04:16 RSL: stat/tasmota_0F1BB9/RESULT = {"WebLog":4}


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Seems like it may be a compatibility issue with NodeMCU devices. Just flash a NodeMCU, run it and set up the initial wifi configuration and try to see if it connects.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Connect to wifi network

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
