### ISSUE TITLE
HUE emulation not working on Tasmota 8.3.1

### ISSUE THREAD

**Issue by marcolinux46** [arendst/Tasmota#8531]
I'm trying to use HUE emulation but not work...
I can see the UDP packet from console but the Alexa App don't find nothing.
I have also an echo Dot...

This is what i see when i start the search from App:
![hue_emul](https://user-images.githubusercontent.com/65719155/82760379-73954e80-9df3-11ea-969d-e06bb7efb75e.JPG)

I make the search with hue bridge v1

**Comment by ascillato** [comment]
Please, open a new issue with the troubleshooting template fully completed in order to have more information for debugging. Thanks.

**Comment by Jason2866** [comment]
Can not reproduce. All my Tasmota devices do work with Alexa and Tasmota v.8.3.1
