### ISSUE TITLE
rule > 511 char not uploaded correct via console truncated after 511

### ISSUE THREAD

**Issue by riker65** [arendst/Tasmota#8533]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): lolin esp 8266
- [x] Tasmota binary firmware version number used: 8.3.1
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [x ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
...rule...
08:12:50 SRC: Backlog
08:12:50 CMD: Group 0, Index 1, Command "RULE", Data ""
08:12:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":545,"Free":232,"Rules":"on systemboot
```
- [x ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
21:08:50 CMD: status 0
21:08:50 SRC: WebConsole from 192.168.1.195
21:08:50 CMD: Group 0, Index 1, Command "STATUS", Data "0"
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS = {"Status":{"Module":0,"DeviceName":"TA_WP_H_P1_P2_Lolin1","FriendlyName":["TA_WP_H_P1_P2_Lolin1","Tasmota2","Tasmota3","Tasmota4"],"Topic":"TA_WP_H_P1_P2_Lolin1","ButtonTopic":"0","Power":9,"PowerOnState":0,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[2,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Hardware Watchdog","Uptime":"0T01:19:33","StartupUTC":"2020-05-24T17:49:17","Sleep":50,"CfgHolder":4617,"BootCount":66,"BCResetTime":"2020-05-14T08:53:45","SaveCount":508,"SaveAddress":"F9000"}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-05-18T15:39:35","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"485/699"}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":3,"MqttLog":3,"SysLog":1,"LogHost":"192.168.0.22","LogPort":514,"SSId":["TR7272","TR_ESP"],"TelePeriod":10,"Resolution":"558180C0","SetOption":["00008029","2805C8000100060000005A00000000000000","000000C8","00000000"]}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS4 = {"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":23,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashMode":3,"Features":["00000809","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS5 = {"StatusNET":{"Hostname":"TA_WP_H_P1_P2_Lolin1-6261","IPAddress":"192.168.1.205","Gateway":"192.168.0.31","Subnetmask":"255.255.240.0","DNSServer":"192.168.0.31","Mac":"60:01:94:59:18:75","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.9","MqttPort":1893,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_591875","MqttUser":"TR_MQTT","MqttCount":4,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS7 = {"StatusTIM":{"UTC":"2020-05-24T19:08:50","Local":"2020-05-24T21:08:50","StartDST":"2020-03-08T02:00:00","EndDST":"2020-11-01T02:00:00","Timezone":"+02:00","Sunrise":"05:57","Sunset":"21:36"}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS10 = {"StatusSNS":{"Time":"2020-05-24T21:08:50","Switch1":"ON","DS18B20-1":{"Id":"0210917769EA","Temperature":25.9},"DS18B20-2":{"Id":"02199177A4A4","Temperature":26.1},"TempUnit":"C"}}
21:08:50 MQT: stat/TA_WP_H_P1_P2_Lolin1/STATUS11 = {"StatusSTS":{"Time":"2020-05-24T21:08:50","Uptime":"0T01:19:33","UptimeSec":4773,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":4,"POWER1":"ON","POWER2":"OFF","POWER3":"OFF","POWER4":"ON","Wifi":{"AP":1,"SSId":"TR7272","BSSId":"2A:E8:29:37:7F:89","Channel":1,"RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:07"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by riker65** [comment]
see rule 1 

ending ;publish cmn..."}

rule should be longer

```
on systemboot do
	backlog teleperiod 10;VAR9 57;VAR8 47;MEM1 F_OFF;power0 0; publish tele/WP/%topic%/Act RB
endon 
on Power1#State=0 do
	backlog Power3 0;MEM1 F_OFF;publish tele/WP/%topic%/R1_F F_OFF
endon 
on Power1#State=1 do
	backlog MEM1 F_ON;publish tele/WP/%topic%/R1F_ON F_ON;
endon 
on Power2#State=1 do
	backlog power3 0; publish cmnd/TA_ESP0143/power1 1;publish tele/WP/%topic%/R2t2_1 p1T-St;RuleTimer2 600; 
endon 
on Rules#Timer=2 do
	backlog publish tele/WP/%topic%/R2T20 T2P10 ;power2 0;publish cmnd/TA_ESP0143/power1 0;
endon


so it is truncated

```

**Comment by riker65** [comment]
in https://tasmota.github.io/docs/Rules/#rule-syntax
There are three separate rule sets called Rule1, Rule2 and Rule3. Each rule set can contain many rules which are dynamically compressed. Number of rules that can fit in a rule set varies. Expect at least 1000 characters available per rule set.

**can not 1000 chars per set !!!**

**Comment by ascillato2** [comment]
From your Log:

```lua
"Length":540,"Free":232
```

That means that you still have space for more rules in the slot `RULE1`.

Compressed rules can't be fully seen in the Tasmota console. The buffer is not enough. That is why you can't write a very long rule at once and must be done by parts using:

`RULE1 ON ....`

and then

`RULE1 + ON .....`

and then

`RULE1 + ON .....`,

and so on, using chunks of less of 511 characters.

**Comment by riker65** [comment]
Hi, thanks for that, but how do I verify or download the full rule?

**Comment by meingraham** [comment]
From what I saw, @s-hadinger recently added that compressed rules are output to the Console in 500-byte "chunks" so the entire rule set can be inspected. Try a newer development version to get this newer feature.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
