### ISSUE TITLE
Sonoff T1 double press does not toggle relay with buttontopic

### ISSUE THREAD

**Issue by wastlchuck** [arendst/Tasmota#8535]
### PROBLEM DESCRIPTION
According to https://tasmota.github.io/docs/Buttons-and-Switches/#changing-default-functionality, when setting SetOptions1 ON and defining a ButtonTopic, double press should toggle the relay. With 8.3.1, this does not work anymore. Power ON is sent to ButtonTopic instead of Topic.
I've seen that handling of multi press has changed with 8.3.1, but I couldn't figure out how this is related to my issue. Or is the documentation for changing default functionality not up to date?

### REQUESTED INFORMATION

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Sonoff T1 1CH
- [X] Tasmota binary firmware version number used: _____
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
22:26:27 MQT: stat/switch_sr/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
22:26:27 MQT: stat/switch_sr/RESULT = {"Module":{"1":"Sonoff Basic"}}
22:26:28 MQT: stat/switch_sr/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [X] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
22:27:56 MQT: stat/switch_sr/STATUS = {"Status":{"Module":1,"DeviceName":"switch_sr","FriendlyName":["switch_sr"],"Topic":"switch_sr","ButtonTopic":"led_sr","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:27:56 MQT: stat/switch_sr/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:06:02","StartupUTC":"2020-05-24T21:21:54","Sleep":50,"CfgHolder":4617,"BootCount":6,"BCResetTime":"2020-05-24T20:54:32","SaveCount":44,"SaveAddress":"F8000"}}
22:27:56 MQT: stat/switch_sr/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-05-18T15:39:35","Boot":7,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"400/699"}}
22:27:56 MQT: stat/switch_sr/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["mySSID",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000800B","0F05C8000100060000005A00000000000000","00000000","00000000"]}}
22:27:56 MQT: stat/switch_sr/STATUS4 = {"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
22:27:56 MQT: stat/switch_sr/STATUS5 = {"StatusNET":{"Hostname":"switch_sr-3803","IPAddress":"192.168.178.48","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"60:01:94:BF:AE:DB","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
22:27:56 MQT: stat/switch_sr/STATUS6 = {"StatusMQT":{"MqttHost":"openhabianpi","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_BFAEDB","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
22:27:56 MQT: stat/switch_sr/STATUS7 = {"StatusTIM":{"UTC":"2020-05-24T21:27:56","Local":"2020-05-24T22:27:56","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:57","Sunset":"20:36"}}
22:27:56 MQT: stat/switch_sr/STATUS10 = {"StatusSNS":{"Time":"2020-05-24T22:27:56"}}
22:27:56 MQT: stat/switch_sr/STATUS11 = {"StatusSTS":{"Time":"2020-05-24T22:27:56","Uptime":"0T00:06:02","UptimeSec":362,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Herbert 52 20cm Single","BSSId":"C8:0E:14:84:91:B9","Channel":6,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
```
  Console output here:
22:30:36 APP: Button1 multi-press 1
22:30:36 APP: Button1 multi-press 2
22:30:37 MQT: cmnd/led_sr/POWER = ON
```

### TO REPRODUCE
Console:
- SetOptions1 1
- ButtonTopic SomeOtherTopic

Double press sonoff button

### EXPECTED BEHAVIOUR
Double press toggles the relay.

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by effelle** [comment]
Take that part of the docs with a grain of salt, because is under rework. In the meantime if you need to toggle the relay with 2 press you can use setoption73 and a simple rule.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
