### ISSUE TITLE
Add "Blink" to timer actions

### ISSUE THREAD

**Issue by M95D** [arendst/Tasmota#8548]
I would like to have my lights blink at a specific time to remind me to go to bed. :-) There is no easy way to do this.

**Have you looked for this feature in other issues and in the docs?**  
Yes. There's timers to turn off the lights (and stay off) and there's the **power<x> blink** command, but it's not available for timers.

**Is your feature request related to a problem? Please describe.**  
No.

**Describe the solution you'd like**  
Simply add a new timer action for **Blink**.

**Describe alternatives you've considered**  
Several timers in succession: this won't blink fast.
Rules: it's much more complicated than adding blink as a timer action.

**Additional context**  
N/A.

**(Please, remember to close the issue when the problem has been addressed)**  
OK.

**Comment by arendst** [comment]
There was a reason why blink was removed from timers simply because a simple rule can do that and more:
```
on clock#timer=1 do power1 blink endon
``

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
