### ISSUE TITLE
RF pairing not working

### ISSUE THREAD

**Issue by daniel-lo** [arendst/Tasmota#8549]
8.3.1.2 (also with 8.3.1.1)

I have huge probs pairing my rf remote .. with my 4ch pro rev2. I double tap the physical button and nothing happens.
Also it seems that expecially Button 1 has problems when manually pressed .. 2-4 seem to work better. Via Web-IF everything works well.

Is there a limitation related to the RF use in newer tasmota version?
Is there a way to trigger RF pairing via console?

BR

**Comment by arendst** [comment]
Tasmota is in no way involved in RF pairing.
