### ISSUE TITLE
After update all of my sonoffs after click on immediatelly turn off. :(

### ISSUE THREAD

**Issue by spider7611** [arendst/Tasmota#8552]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Updated my 4 sonoff basics 8.1 to the latest firmware. Use this sonoffs with home assistant. After update every thing was ok. Then about 2-3 hours after all of my sonoff switched off and if I want to turn on and click on all of them immediatelly turn off. What is the problem and how can I solve this?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____ Sonoff Basic
- [ ] Tasmota binary firmware version number used: _____ 8.3.1
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
15:34:35 CMD: Status 0
15:34:35 MQT: sonoff_5/stat/STATUS = {"Status":{"Module":1,"DeviceName":"Sonoff 5","FriendlyName":["Sonoff 5"],"Topic":"sonoff_5","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":1,"PowerRetain":0}}
15:34:35 MQT: sonoff_5/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://192.168.1.242:9999/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:04:47","StartupUTC":"2020-05-26T14:29:48","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2020-03-22T07:45:19","SaveCount":41,"SaveAddress":"FB000"}}
15:34:35 MQT: sonoff_5/stat/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020.05.18 15:47:35","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"383/699"}}
15:34:35 MQT: sonoff_5/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":1,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["spider2",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["400A8209","2805C8000100060000005A00000000000000","00000200","00000000"]}}
15:34:35 MQT: sonoff_5/stat/STATUS4 = {"StatusMEM":{"ProgramSize":589,"Free":412,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["0000040E","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
15:34:35 MQT: sonoff_5/stat/STATUS5 = {"StatusNET":{"Hostname":"sonoff_5-6346","IPAddress":"192.168.1.175","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.242","Mac":"DC:4F:22:E5:38:CA","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
15:34:35 MQT: sonoff_5/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.242","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_E538CA","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
15:34:35 MQT: sonoff_5/stat/STATUS7 = {"StatusTIM":{"UTC":"2020-05-26T14:34:35","Local":"2020-05-26T15:34:35","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:55","Sunset":"20:38"}}
15:34:35 MQT: sonoff_5/stat/STATUS10 = {"StatusSNS":{"Time":"2020-05-26T15:34:35"}}
15:34:35 MQT: sonoff_5/stat/STATUS11 = {"StatusSTS":{"Time":"2020-05-26T15:34:35","Uptime":"0T00:04:47","UptimeSec":287,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"spider2","BSSId":"50:C7:BF:3E:09:AB","Channel":1,"RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

5:35:47 MQT: sonoff_5/stat/POWER = ON
15:35:47 MQT: domoticz/in = {"idx":41,"nvalue":0,"svalue":"","Battery":100,"RSSI":4}
15:35:47 MQT: sonoff_5/tele/STATE = {"Time":"2020-05-26T15:35:47","Uptime":"0T00:05:59","UptimeSec":359,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":97,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"spider2","BSSId":"50:C7:BF:3E:09:AB","Channel":1,"RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:03"}}
15:35:47 MQT: sonoff_5/stat/RESULT = {"POWER":"OFF"}
15:35:47 MQT: sonoff_5/stat/POWER = OFF

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Sorry we cant help you didnt provide any data.

**Comment by Jason2866** [comment]
You have strange domoticz traffic via mqtt. Check your settings. Check your mqtt broker.
Your setup is screwed somewhere

**Comment by ascillato2** [comment]
Hi, 

Please,

Check if you have retained messages on your broker
Check your switchmode config
Check your mqtt broker
Check old issues
Complete the troubleshooting template or address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
