### ISSUE TITLE
SetOption19 site effect on Scheme (Reset to 0)

### ISSUE THREAD

**Issue by reimerp** [arendst/Tasmota#8557]
### PROBLEM DESCRIPTION
Having SO19 to ON seems to set Scheme to 0 on Device Restart

Background: The WS2812 seems to use much Power (even more than PWM) so the device runs in a hardware watchdog reset occasionally. Than a couple of Settings are reset, Scheme is 0 and also Color is set to white. I figured out that this is true also for a simple device Restart and this only if Option19 is ON.
I think this was working in a 7.x release but I have not verified. The Autodiscovery Feature was under heavy devolopment whicht is working smoothly for my other devices, 

There is already a visable effect on a running sceme when issuing a `SO19 ON`: The effect 'freezes'
 but the device is responding (no watchdog issues)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): ESP-01 + WS2812 Module 
- [ x] Tasmota binary firmware version number used: 8.3.1
  - [x ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```:
01:02:36 MQT: stat/tasmota/rgb/RESULT = {"NAME":"RGB","GPIO":[255,56,7,255,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":18}
01:02:36 MQT: stat/tasmota/rgb/RESULT = {"Module":{"0":"RGB"}}
01:02:37 MQT: stat/tasmota/rgb/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"56":"Led1i"},"GPIO2":{"7":"WS2812"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["TasmotaRGB"],"Topic":"tasmota/rgb","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":1,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"groups/wohnzimmer","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:25:26","StartupUTC":"2020-05-26T22:38:42","Sleep":0,"CfgHolder":4617,"BootCount":15,"BCResetTime":"2020-05-26T22:03:21","SaveCount":54,"SaveAddress":"F6000"},"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-05-18T15:39:35","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"358/699"},"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":1,"LogHost":"hassbian","LogPort":514,"SSId":["WehLAN",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00128228","2805C8000100060000005A00000000000000","00000200","00000000"]},"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14400B","FlashMode":3,"Features":["00000809","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"tasmota-rgb","IPAddress":"192.168.176.25","Gateway":"192.168.176.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.176.1","Mac":"84:0D:8E:A4:93:6F","Webserver":2,"WifiConfig":2,"WifiPower":17.0},"StatusMQT":{"MqttHost":"hassbian","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A4936F","MqttUser":"tasmota","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-05-26T23:04:08","Local":"2020-05-27T01:04:08","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"05:54","Sunset":"21:39"},"StatusSNS":{"Time":"2020-05-27T01:04:08"},"StatusSTS":{"Time":"2020-05-27T01:04:08","Uptime":"0T00:25:26","UptimeSec":1526,"Heap":22,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":1000,"MqttCount":1,"POWER":"ON","Dimmer":50,"Color":"128,0,0","HSBColor":"0,100,50","Channel":[50,0,0],"Scheme":6,"Width":1,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"WehLAN","BSSId":"98:9B:CB:33:B0:51","Channel":13,"RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE

```
Scheme 6;
SetOption19 ON;
Restart 1;
```

### EXPECTED BEHAVIOUR
The Scheme settings shounld be retained.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
I played with other Options which might be related: 0 and 20, they are working as expected unless you active 19, and don't change the behavior afterwards.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by effelle** [comment]
As designed. The Discovery will revert `Settings.light_scheme` to `0` as soon as you restart the device and is needed to correctly handle the color under HA. 
I will check if with the new light management is still necessary, perhaps is safe to remove now.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
