### ISSUE TITLE
Power monitor timing variance

### ISSUE THREAD

**Issue by dtmr-e** [arendst/Tasmota#8561]
I'd like to use the power monitor in my plug to stop a grinder after a programmed time: Tasmota should detect the start of the motor (with the power monitor) and a rule should turn it off after a programmed time. Alas, the timing is not reliable enough for my purposes. 1s error observed, 0.1s error desired. Is that normal/unavoidable or could that be fixed?

--- Details

I use this rule (in words: wait for user to start motor, run 10s, off for 5s, repeat):

RULE1 ON ENERGY#Power>10 DO BACKLOG DELAY 100; POWER OFF; DELAY 50; POWER ON; RULE1 5 ENDON

Sometimes the grinder runs for up to 1s longer than on other occasions.

- Are power monitor circuits too slow generally?

- Is the one in my plug slower than average (BL0937 in Gosund SP111)?

- Would it be much faster if I don't care about all those values (watt, voltage, current) and would change the source code to just read the voltage?

- Does Tasmota have a built-it time slot pattern that is too slow, for example does it only check the power monitor every 500ms or so?

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
