### ISSUE TITLE
Split Total Energy value on Shelly 2.5

### ISSUE THREAD

**Issue by cmiguelcabral** [arendst/Tasmota#8567]
**Have you looked for this feature in other issues and in the docs?**  
Yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Shelly 2.5 has two integrated power meters. It happens that Home Assistant uses the total energy value to calculate daily and monthly consumptions and therefore calculate the costs. Has Tasmota is adding the two values, it's impossible to calculate such things when we connect different devices on the two channels of the Shelly.
 **Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
I would like to have the Total Energy split in two like is already being done on Power,  Apparent Power, etc... As you can always add the two values, but can never split them after being merged.
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
No alternatives found possible...
**Additional context**  
_Add any other context or screenshots about the feature request here._
![image](https://user-images.githubusercontent.com/3021283/83177461-047f6900-a117-11ea-978b-a170b55e908b.png)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Omega236** [comment]
Is anything else being done here?

As it is currently, the Shelly is often not usable
