### ISSUE TITLE
Mqtt report on every executed rule with MqttLog=0

### ISSUE THREAD

**Issue by Christian-fhs** [arendst/Tasmota#8569]
I am running Tasmota 8.3.1 and implemented following ruleset:
```
rule1  
   on analog#a0 do var1=(var1*63+%value%)/64 break 
   on var1#State do var3=var2-var1 endon 
   on var3#State>2 do var2=var1 endon 
   on var3#State<-2 do var2=var1 endon 
   on var2#State do publish cmnd/druck/druck %var2% endon
```

This works fine, except that every executed rule generates an mqtt output, even if the mqttlog=0/1.

```
4:54:49 RUL: ANALOG#A0 performs "var1=(var1*63+120)/64"
14:54:49 MQT: stat/Pumpensteuerung_test/RESULT = {"Var1":"119.969"}
14:54:49 RUL: VAR1#STATE performs "var3=var2-var1"
14:54:49 MQT: stat/Pumpensteuerung_test/RESULT = {"Var3":"0.149"}
```

Listening to the topic "cmnd/druck/druck" works as intended. But still my network gets spammed with all these useless reports.
I compiled the sources with the macro #define USE_EXPRESSION to allow arithmetic operations in the ruleset.

**Comment by ascillato** [comment]
As designed. MQTTLOG is not meant for that. And every operation has a RESULT to be shown on the console.
