### ISSUE TITLE
disable GPIO for specific hours

### ISSUE THREAD

**Issue by elkorleone** [arendst/Tasmota#8580]
hi guys!! probably anyone had this problem before...
I have a Wemos mini working right to switch on/off a light.
A PIR is the switch.
Now I have setting SwitchMode 13 and PulseTime 110 (rele on at motion and retain till motion is off with 5sec delay)
It works perfectly.
But now I wanna it only works in the night (from sunrise to sunset).
How can I do that?
maybe setting rele unavailable during this hours in a rule, but I dont know how to do

**Comment by meingraham** [comment]
There is a rule in the Rule Cookbook that does this. Look there.
