### ISSUE TITLE
Wificonfig 2 - does not connect after restart

### ISSUE THREAD

**Issue by JoeSydney** [arendst/Tasmota#8596]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I have SO56 and SO57 set to On. I have 2 access points with the same SSID. When I have WifiConfig 5, taking an access point down (offline) the behaviour is as expected - all Tasmota devices that were connected to that access point immediately reconnects to the other access point.

However, when I have WifiConfig set to 2, it takes up to 10 minutes for the devices to connect to the other access point. This is regardless of whether I log in to the Wifi Manager to restart the devices, or allow the devices to restart themselves according to WifiConfig 2.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Mixture of devices - the problem is independent of device. Devices include plugs, switches and lights from Arlec, Deta, Brilliant, etc
- [X] Tasmota binary firmware version number used: 8.3.1
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: Tuya Convert (this is not applicable to the problem)
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
1. Setoption56 and Setoption57 to On
2. Wificonfig 2
3. Set up 2 access points with the same SSID
4. Turn on a device and let it connect to one of the access points 
5. Turn off the access point to which it has connected

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
According to Wificonfig 2, the device should go into access point mode (Wifi manager). When it is restarted manually or automatically, it should connect to the other access point that is still running.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
I think it's related to #8635 and solved there. Pls try latest dev version
