### ISSUE TITLE
WebSend: Reply to the HTTP request could control switch

### ISSUE THREAD

**Issue by hagenbuch** [arendst/Tasmota#8613]
WebSend is able to make a request to a http server. This works well for me.

However, it would be fantastic if I could send an "OFF" or "ON" string as reply from the server to the device and the device would change its status accordingly. If something else than ON or OFF or maybe TOGGLE are being received, nothing should happen.

In theory, it would be possible to send any command but this might be a little too dangerous. One could as well implement password checking in the reply but that might be overblown as the request can have basic authentication already.

I know you guys want to control everything via MQTT and I understand why - there are just real use cases wher MQTT is not available, for various reasons. HTTP works gret in that case, let's hope the ESP32 version will be able to handle proper HTTPS, then I'd be in heaven :-)

Andreas

**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
I have no option to use MQTT in my case, that's why I'd like to have the feedback channel.

**Describe the solution you'd like**  
Reply from the WebSend request would be able to turn the switch of a Sonoff Pow R2

**Describe alternatives you've considered**  
Making a second HTTP Get request from "outside" would mean I have to introduce port forwarding, which opens the device up to the  internet, not such a good idea IMHO.

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

You can achieve that using rules.

Please, check the docs and if you need further assistance, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. 

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
