### ISSUE TITLE
Support for ODROID GO with screen

### ISSUE THREAD

**Issue by hagenbuch** [arendst/Tasmota#8630]
**Have you looked for this feature in other issues and in the docs?**  
Yes, I found this post:
https://github.com/arendst/Tasmota/issues/6775

**Is your feature request related to a problem? Please describe.** 
I would humbly suggest that this issue be reopened, now as ESP32 support is there.

**Describe the solution you'd like**  
Suggest to reopen ticket: Support for Odroid GO because ESP32 is supported now

**Describe alternatives you've considered**  
I could start a new post but then the old one woudl carry contradictory information.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Looking at the circuit diagramm https://github.com/hardkernel/ODROID-GO/blob/master/Documents/ODROID-GO_REV0.1_20180518.pdf
There is nothing special. Tasmota will run on the device.
Only the Display ILI9341 is not supported.

**Comment by hagenbuch** [comment]
Thanks. I'll try!

**Comment by Jason2866** [comment]
@hagenbuch could not resist... https://www.pollin.de/p/odroid-go-mobile-spielekonsole-kit-810887

**Comment by hagenbuch** [comment]
I know, that's exactly what I ordered and bullt already.

**Comment by Jason2866** [comment]
No, Tasmota writes a new partition table. Everything will be overwritten

**Comment by ascillato2** [comment]
Hi, Any news on this?

**Comment by Jason2866** [comment]
Hi Adrian, my Odroid Go is ordered. Should arrive the next days.

**Comment by arendst** [comment]
I'd like to order one too but alas not possible to Die Niederlande:

> Es befinden sich derzeit Artikel in Ihrem Warenkorb, welche nicht in Ihr angegebenes Lieferland versendet werden können. Bitte klicken Sie oben "Zurück zum Shop" und löschen Sie die rot markierten Artikel aus Ihrem Einkaufswagen um Ihre Bestellung fortzusetzen.

I probably need to urge someone to send it to me...

**Comment by hagenbuch** [comment]
Well I could have sent you one.. :) Shall I still?

I guess templates will be going here: https://github.com/blakadder/templates/tree/master/_templates

Maybe the screen is new and / or the speakers. Also not sure how Tasmota deals with SD-Cards, would be awesome.

**Comment by arendst** [comment]
There is one in the mail already.

Templates should go there but for now it's only on the ESP32 doc page.

**Comment by gemu2015** [comment]
@hagenbuch 
scripting has full support for sd cards (also on esp32) 
you can display the card directory  and may upload and download files and manipulate them in a script.

**Comment by Jason2866** [comment]
Theo has fixed the bug in the Displaydriver.
You can try now with latest development version and this (not complete!) Template.
Display is working and can be dimmed via slider.
`{"NAME":"Odroid","GPIO":[32,1,1,1,1,768,1,1,1,1,416,1,1,1,736,672,0,800,1,704,0,1,1,1,0,0,0,0,1,1,1,1,1,0,0,1],"FLAG":0,"BASE":1}`

**Comment by Jason2866** [comment]
No close

**Comment by Jason2866** [comment]
in work...
