### ISSUE TITLE
wiki tasmota conditional syntax unclear

### ISSUE THREAD

**Issue by riker65** [arendst/Tasmota#8644]
Hi all, anyone having a good example for conditional rules? I am confused with the syntax.  which brackeds are required , which not...
.https://tasmota.github.io/docs/Rules/#conditional-rules it not giving consistent examples....at least i do not understand them
Rules - Tasmota
Documentation (Wiki) for Tasmota
IF (<logical-expression>) 
   <statement> {; <statement>}  {ELSEIF (<logical-expression>) <statement-list>} 
   [ELSE <statement-list>] 
   ENDIF
thanks

**Comment by meingraham** [comment]
```
  ON Event#ckMng DO
    IF (%value%<%Mem1%) Var5 0
    ELSE Var5 1
    ENDIF
  ENDON

  ON Event#aDiff DO
    IF (%value%==0) RuleTimer1 0;Power1 0
    ELSEIF (%Var4%==0) RuleTimer1 %Mem4%;Power1 %Var5%
    ENDIF
  ENDON
```
