### ISSUE TITLE
webUI not available 

### ISSUE THREAD

**Issue by poseidogithub** [arendst/Tasmota#8647]
Hello;

disclaimer: I'm new to tasmota and an overall newbie on IT related matters. I've searched around for my problem but couldnt find anything I could understand.

The thing is that I've flashed via FTDI a esp8266ex smart bulb with 8.2 and updated to 8.3.1 trough the web interface.

the symtom I'm getting is that Webui stops working (to me randomly) under normal operation. The device answers to pings normally, and I can interact with it trough MQTT but webUI is just not responding. Wifi is stable.

Is there any troubleshooting guide I can follow to provide you with more details?

thanks!

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
