### ISSUE TITLE
OpenTherm status	FAULT (0x0)

### ISSUE THREAD

**Issue by yann1420** [arendst/Tasmota#8662]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I compiled tasmota 8.3.1 code and configured according instructions https://tasmota.github.io/docs/OpenTherm/ for a Ihor Melnyk adaptor (http://ihormelnyk.com/opentherm_adapter) adapter. Hooked up an Intergas Prestige boiler (https://www.intergas-verwarming.nl/en/trade/products/prestige/prestige-cw6/) on pins 11&12 of the X4 connector .

**when connecting I get these type of errors
_11:25:41 [OTH]: perform handshake
11:25:42 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT_**

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [* ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [* ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [* ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [* ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [* ] Device used (e.g., Sonoff Basic): _wemos mini____
- [* ] Tasmota binary firmware version number used: _8.3.1. ____
  - [ ] Pre-compiled
  - [* ] Self-compiled
    - [* ] IDE / Compiler used: _gitpod____
- [ *] Flashing tools used: __wemos___
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
11:30:03 [OTH]: perform handshake
11:30:04 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT
11:30:12 CMD: Backlog Template; Module; GPIO 255`
11:30:12 SRC: WebConsole from 192.168.178.70
11:30:12 CMD: Group 0, Index 1, Command "BACKLOG", Data "Template; Module; GPIO 255`"
11:30:12 SRC: Backlog
11:30:12 CMD: Group 0, Index 1, Command "TEMPLATE", Data ""
11:30:12 MQT: stat/tasmota-3805/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
11:30:12 SRC: Backlog
11:30:12 CMD: Group 0, Index 1, Command "MODULE", Data ""
11:30:12 MQT: stat/tasmota-3805/RESULT = {"Module":{"18":"Generic"}}
11:30:13 SRC: Backlog
11:30:13 CMD: Group 0, Index 1, Command "GPIO", Data "255`"

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
11:31:59 CMD: Group 0, Index 1, Command "BACKLOG", Data "Rule1; Rule2; Rule3"
11:31:59 SRC: Backlog
11:31:59 CMD: Group 0, Index 1, Command "RULE", Data ""
11:31:59 MQT: stat/tasmota-3805/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
11:31:59 SRC: Backlog
11:31:59 CMD: Group 0, Index 2, Command "RULE", Data ""
11:31:59 MQT: stat/tasmota-3805/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
11:32:00 SRC: Backlog
11:32:00 CMD: Group 0, Index 3, Command "RULE", Data ""
11:32:00 MQT: stat/tasmota-3805/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
11:32:00 [OTH]: perform handshake
11:32:01 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
11:33:01 CMD: status 0
11:33:01 SRC: WebConsole from 192.168.178.70
11:33:01 CMD: Group 0, Index 1, Command "STATUS", Data "0"
11:33:01 MQT: stat/tasmota-3805/STATUS = {"Status":{"Module":18,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota-3805","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:33:01 MQT: stat/tasmota-3805/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Exception","Uptime":"1T15:07:56","StartupUTC":"2020-06-09T19:25:05","Sleep":50,"CfgHolder":4617,"BootCount":36,"BCResetTime":"2020-06-05T14:44:07","SaveCount":57,"SaveAddress":"F9000"}}
11:33:01 MQT: stat/tasmota-3805/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-06-05T07:34:26","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"364/699"}}
11:33:01 MQT: stat/tasmota-3805/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":3,"MqttLog":2,"SysLog":0,"LogHost":"syslog","LogPort":514,"SSId":["titania","openwrt"],"TelePeriod":20,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
11:33:01 MQT: stat/tasmota-3805/STATUS4 = {"StatusMEM":{"ProgramSize":602,"Free":400,"Heap":22,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164068","FlashMode":3,"Features":["00000809","8FDAE797","043683A1","000000CD","010013C0","C000F981","00000224"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6,69"}}
11:33:01 MQT: stat/tasmota-3805/STATUS5 = {"StatusNET":{"Hostname":"tasmota-3805-3805","IPAddress":"192.168.178.81","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.60","Mac":"80:7D:3A:78:EE:DD","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
11:33:01 MQT: stat/tasmota-3805/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_78EEDD","MqttUser":"schepers","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
11:33:01 MQT: stat/tasmota-3805/STATUS7 = {"StatusTIM":{"UTC":"2020-06-11T10:33:01","Local":"2020-06-11T11:33:01","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:53"}}
11:33:01 MQT: stat/tasmota-3805/STATUS10 = {"StatusSNS":{"Time":"2020-06-11T11:33:01","OPENTHERM":{"conn":"FAULT","settings":3,"SLAVE":{"FAULT":0,"CH":0,"DHW":0,"FL":0,"COOL":0,"CH2":0,"DIAG":0,"RAW":0},"BTMP":{"FAULT":0,"REQ":0.0,"ACT": 0.0}}}}
11:33:01 MQT: stat/tasmota-3805/STATUS11 = {"StatusSTS":{"Time":"2020-06-11T11:33:01","Uptime":"1T15:07:56","UptimeSec":140876,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"titania","BSSId":"70:5A:9E:27:9F:1D","Channel":11,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}}
11:33:01 MQT: stat/tasmota-3805/STATUS12 = {"StatusSTK":{"Exception":3,"Reason":"Exception","EPC":["40101a0d","00000000","00000000"],"EXCVADDR":"400354c0","DEPC":"00000000","CallChain":["40101b10","40101b10","40101daf","40258ec4","40258ec4","402517d1","402518cc","4000050c","40252353","40101daf","4025237c","40254299","40101de6","402585f5","40101daf","4026a2d8","4025168d","402514b3","40274786","40274797","4026ff9b","40000f49","40000f49","40000e19","40105b71","40105b77","4010000d","40268dec","40268d9d","401059b9","401011c8"]}}
11:33:05 [OTH]: perform handshake
11:33:06 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
1:45:03 [OTH]: perform handshake
11:45:03 WIF: Checking connection...
11:45:04 [OTH]: Processing response. Status=TIMEOUT, Response=0x0
11:45:04 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I expect the handshake to be successful as per the documentation. Example:
00:00:01 [OTH]: perform handshake
00:00:01 [OTH]: Processing response. Status=SUCCESS, Response=0x4003011B
00:00:01 [OTH]: getLastResponseStatus SUCCESS. Slave Cfg: 4003011B
00:00:01 [OTH]: Processing response. Status=SUCCESS, Response=0xC0000000
00:00:02 [OTH]: Setting Boiler Temp. Old: 0, New: 85

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
**The adapter communicates with the boiler given the following response:**
11:39:41 CMD: backlog ot_flags ;ot_tboiler ;ot_twater ;ot_save_setpoints ;ot_ch 
11:39:41 SRC: WebConsole from 192.168.178.70
11:39:41 CMD: Group 0, Index 1, Command "BACKLOG", Data "ot_flags ;ot_tboiler ;ot_twater ;ot_save_setpoints ;ot_ch "
11:39:41 SRC: Backlog
11:39:41 CMD: Group 0, Index 1, Command "OT_FLAGS", Data ""
11:39:42 SRC: Backlog
11:39:42 CMD: Group 0, Index 1, Command "OT_TBOILER", Data ""
11:39:42 MQT: stat/tasmota-3805/RESULT = {"ot_tboiler":60.0}
11:39:42 SRC: Backlog
11:39:42 CMD: Group 0, Index 1, Command "OT_TWATER", Data ""
11:39:42 MQT: stat/tasmota-3805/RESULT = {"ot_twater":45.0}
11:39:42 SRC: Backlog
11:39:42 CMD: Group 0, Index 1, Command "OT_SAVE_SETPOINTS", Data ""
11:39:42 MQT: stat/tasmota-3805/RESULT = {"ot_save_setpoints":"Done"}
11:39:42 SRC: Backlog
11:39:42 CMD: Group 0, Index 1, Command "OT_CH", Data ""
11:39:42 MQT: stat/tasmota-3805/RESULT = {"ot_ch":0}
11:39:50 [OTH]: perform handshake

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by yury-sannikov** [comment]
hi @yann1420 can you please provide more information on your hardware and how it's connected? Which GPIO pins do you use to connect the adapter to the board? Which voltage do you have on the OpenTherm line when you connect the adapter to the boiler?
Also, you may use https://github.com/ihormelnyk/opentherm_library/blob/master/examples/OpenThermMaster_Demo/OpenThermMaster_Demo.ino to make sure your master (your adapter) is able to connect to the slave (boiler) and check that your hardware part is 100% operational.

**Comment by yury-sannikov** [comment]
I'm using Wemos D1 R2 and this is my config:
![image](https://user-images.githubusercontent.com/6585448/85947420-45a3ac80-b953-11ea-9bf4-fae19bfb5310.png)

**Comment by yury-sannikov** [comment]
Can you also copy the output of `GPIO 255`?
I don't see anything like `"GPIO0":{"203":"OpenTherm TX"}` in your configuration output above.
```
MQT: stat/boiler/RESULT = {"GPIO0":{"203":"OpenTherm TX"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"202":"OpenTherm RX"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}```

**Comment by yann1420** [comment]
Hello Yuriy, Per your request :

12:25:05 CMD: GPIO 255
12:25:05 SRC: WebConsole from 192.168.178.70
12:25:05 CMD: Group 0, Index 1, Command "GPIO", Data "255"
12:25:05 MQT: stat/tasmota-3805/RESULT = {"GPIO0":{"205":"OpenTherm TX"},"GPIO1":{"0":"None"},"GPIO2":{"4":"DS18x20"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"204":"OpenTherm RX"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
12:25:05 [OTH]: perform handshake
12:25:07 [OTH]: Processing response. Status=TIMEOUT, Response=0x0
12:25:07 [OTH]: getSlaveConfiguration failed. Status=TIMEOUT
![MyOpenTherm-config](https://user-images.githubusercontent.com/28255659/85999892-194c6680-ba0d-11ea-96a3-6b29d1946fdd.png)

I see I have a different "generic" module then you have (generic-18 vs generic-0). Can that make the difference?

**Comment by yury-sannikov** [comment]
The configuration looks good. I would suggest playing with the author's https://github.com/ihormelnyk/opentherm_library/blob/master/examples/OpenThermMaster_Demo/OpenThermMaster_Demo.ino to make sure the hardware and wiring part is ok.

**Comment by yury-sannikov** [comment]
Also, if you connect an adapter to the boiler the OT line voltage should read something between 15-18 volts (24..48 volts from the boiler if it's open-ended). If you put 3.3v between IN pin (near R4) and GND the voltage on the OT line should drop to something between 5 and 7 volts. That way you can check the adapter -> boiler hardware part.

**Comment by yury-sannikov** [comment]
@yann1420 any luck with troubleshooting it?

**Comment by yann1420** [comment]
Hello Yury, I have been out of the (home) office the last couple of weeks and will now be on holiday for 3 weeks.
My goal is to respond the second week of September.

**Comment by mr-varga** [comment]
Have you solve the problem? I have the same...

**Comment by santik** [comment]
I have the same

**Comment by yury-sannikov** [comment]
hi @santik, I know you're working with Igor on this issue. Could you please update the thread when you figure this out?

**Comment by yann1420** [comment]
Hello Yury,
I assume you have better understanding of OT or at least of the code that has been used here and therefore I have questions that you can answer:
- From the OT v2.2 specification (found on the web) I read there are plenty more functions.  For instance, exported as **OT18** is the "**CH water pressure**". And **OT19** is the  **DHW flow rate** but appears not to be exported. Is it because of the code or the implementation of my CH-boiler that I see only a subset?
- There is a field called **RAW** , what does this represent?
- What is the difference between the command **ot_ch** and **ot_flags ch**

Thanks in advance, Yann

**Comment by malinduta** [comment]
Hello @yury-sannikov,
I am also interested on the informations from the post above.
Can you provide more information?

**Comment by krzakx** [comment]
Hello.
I've tried pretty sure every combination and still got TIMEOUT (like open ends?)
Having ~17V on Boiler Terminals while everything wired up.

My Boiler has OpenTherm version 4 (double confirmed with support). Could this be an issue?

**Comment by yann1420** [comment]
OpenTherm v4 ?  AFAIK, V3 is the latest.
The voltage is DC or AC ?

**Comment by krzakx** [comment]
Yes it is v4.
In general is blurry, but you can find device on market that does support OP**+** (yes, plus) v4.
Additionaly please take look at this URL https://www.opentherm.eu/document/opentherm-protocol-specifications-v4-0/ it's empty if opened but the addres speaks for itself.

The voltage on Boiler terminals is DC. Wire connections really looks ok. From soft configuration I've checked every combinantion. I am looking for seting-up another new ESP8266+OT Board set....

**Comment by krzakx** [comment]
Side question.
Do you have room regulator/room thermostat communicating in OT? if yes, than is Wemos between somehow as gateway?

In my case I do not posses any room regulator either vendor specific either potential free relay.

**Comment by yann1420** [comment]
I am using [Home Assistant ](https://www.home-assistant.io/) (HA) that amongst others uses [Tasmota](https://tasmota.github.io/docs/) as a protocol to communicate with IoT devices. One of them is a Wemos D1 Mini (ESP8622) that is hooked up to a [Ihor Melnyk OpenTherm adapter](http://ihormelnyk.com/).
The temperature reading comes from a little [Xiaomi BLE](https://nl.aliexpress.com/item/4000528071010.html?spm=a2g0o.productlist.0.0.20251d3fgJyDgp&algo_pvid=9f128ca8-1356-4ccc-9c7f-7a1ff004fd62&algo_exp_id=9f128ca8-1356-4ccc-9c7f-7a1ff004fd62-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000028197988292%22%7D&pdp_npi=2%40dis%21EUR%219.63%216.74%21%21%21%21%21%402100bdcf16652565570623618efb25%2112000028197988292%21sea&curPageLogUid=dzgSy6sNIL6Q) thermometer of which the signal is going to HA. HA has on its turn various types software thermostats that controls the Wemos.
Is this what you are asking?

**Comment by yann1420** [comment]
> Yes it is v4. In general is blurry, but you can find device on market that does support OP**+** (yes, plus) v4. Additionaly please take look at this URL https://www.opentherm.eu/document/opentherm-protocol-specifications-v4-0/ it's empty if opened but the addres speaks for itself.
> 
> The voltage on Boiler terminals is DC. Wire connections really looks ok. From soft configuration I've checked every combinantion. I am looking for seting-up another new ESP8266+OT Board set....

In the meanwhile I updated my small amount of OT knowledge. Indeed there is a V4 that has some extra ID's (commands) and more clarity on the protocol.

**Comment by krzakx** [comment]
> Is this what you are asking?
Yes, this is what I was asking for as I was wondering if that I am lacking any OT Vendor specific thermostat is an my issues but NO that is not the case.

The news is that with ESPHome OT specific config burnt to my Wemos it work out.... Unfortunately I have no clue why I failed with Tasmota.

PS. Can you please share source for OT v4. knowledge?

**Comment by yann1420** [comment]
I understand that you killed your Wemos using ESPhome and that you want to use Tasmota instead. Correct?

My OT knowledge comes from an old pal who worked as a programmer for boiler producer and in that time he had access to the info. And AFAIK there is no Opentherm information public available (apart from V2.2 )

**Comment by krzakx** [comment]
Oh.... no no, by "burnt" I meant flashed ESPHome specific configured binary file into Wemos ;).
Regrads

**Comment by yann1420** [comment]
OK, that is another explanation of the meaning of **burnt**.  :) 
Would you mind sharing your YAML, I would like to compare but do not want to reflash the MQTT Wemos at the beginning of the winter season.

**Comment by krzakx** [comment]
Config that I've use comes from this project:
https://github.com/rsciriano/ESPHome-OpenTherm/blob/main/opentherm.yaml

**Comment by yann1420** [comment]
> Config that I've use comes from this project: [ESPHome-OpentTherm](https://github.com/rsciriano/ESPHome-OpenTherm/blob/main/opentherm.yaml) Note: this is YAML confi file for ESPHome core component **not** for HA configuration.yaml

thnx

**Comment by serhat-ozkara** [comment]
I also have the same issue with my ESP32 running 12.2.0
