### ISSUE TITLE
Zigbee & Scripting

### ISSUE THREAD

**Issue by TheRocktagon** [arendst/Tasmota#8665]
In xdrv_10_scripter.ino Line 3995 the } is wrong,

Using Script and Zigbee i must delete 2 lines (68 & 69) in xdrv_10_scripter:
uint32_t EncodeLightId(uint8_t relay_id);
uint32_t DecodeLightId(uint32_t hue_id);

cause of double pre definition

Many other Errors i fixed but i can't remeber, sry. But now i have an Acoount and post it.

BTW - ESP32 is not working, i tried it in Arduino and Visual Studio Code.
I'm using a Wemos D32 Pro (and some other ESP32 boards), Options are Zigbee, scripting(with SD Fat), I2C, SD Card, RC Switch, MQTT (and maybe ILI9341 Touch display)

**Comment by s-hadinger** [comment]
I will look at it.

ZIgbee is not supported in ESP32 (yet).
