### ISSUE TITLE
Cant add esp32 cam to tasmoadmin got  error.

### ISSUE THREAD

**Issue by Blak-DK** [arendst/Tasmota#8672]
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_cam_1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software reset CPU","Uptime":"0T00:00:59","StartupUTC":"2020-06-12T20:11:52","Sleep":50,"CfgHolder":4617,"BootCount":8,"BCResetTime":"2020-06-12T20:54:26","SaveCount":15},"StatusFWR":{"Version":"8.3.1.3(webcam)","BuildDateTime":"2020-06-12T15:45:33","Core":"1_0_4","SDK":"v3.2.3-14-gd3e562907","CpuFrequency":240,"Hardware":"ESP32","CR":"396/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXXX Net","XXXXX"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00800000","00000000"]},"StatusMEM":{"ProgramSize":1176,"Free":1984,"Heap":103,"PsrMax":4095,"PsrFree":3345,ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE787","001403A1","000000CD","010013C0","40000181","80004020"],"Drivers":"1,2,3,4,5,7,8,9,10,12,20,21,24,26,27,81","Sensors":"1,2,3,5,6"},"StatusNET":{"Hostname":"tasmota_cam_1-1096","IPAddress":"1XXXXX","Gateway":"XXXXX","Subnetmask":"255.255.255.0","DNSServer":"XXXXX","Mac":"XXXXXXX","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"10.10.0.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_952448","MqttUser":"XXXXX","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-06-12T20:12:51","Local":"2020-06-12T21:12:51","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:53"},"StatusSNS":{"Time":"2020-06-12T21:12:51"},"StatusSTS":{"Time":"2020-06-12T21:12:51","Uptime":"0T00:00:59","UptimeSec":59,"Heap":103,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":58,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Blak´s Net","BSSId":"F0:9F:C2:2D:47:C5","Channel":1,"RSSI":100,"Signal":-41,"LinkCount":1,"Downtime":"0T00:00:03"}}}

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please address that to Tasmoadmin repository. Thanks.
