### ISSUE TITLE
MODBUS with script is not returning any values

### ISSUE THREAD

**Issue by tiagofreire-pt** [arendst/Tasmota#8677]
### PROBLEM DESCRIPTION
I'm using a script to get values from a smart energy meter, using a RS485-to-TTL and a Wemos D1 mini.

I see the TX and RX leds on the RS485 converter blinking within the same rhythm defined in the script (3500 ms). So, I'm assuming the smart meter is communicating with success with the Wemos d1 mini.

Connections, on the TTL side (converter -> wemos):

RX -> D4 (GPIO2)
TX -> D1 (GPIO5)

I **successfully** get values from this same smart energy meter with the MODBUS integration on Home Assistant:

```yaml

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N
  timeout: 10

sensor:
  - platform: modbus
    scan_interval: 2
    registers:
      - name: 'Instantaneous Frequency'
        hub: energy_box_1
        slave: 1
        register: 127
        register_type: input
        unit_of_measurement: 'Hz'
        count: 1
        scale: 0.1
        offset: 0
        precision: 2
        # long unsigned
        data_type: uint
       
      - name: 'Switch Control State'
        hub: energy_box_1
        slave: 1
        register: 132
        register_type: input
        count: 1
        # conversão de 1/256
        scale: 0.00390625
        offset: 0
        ## 0 para disconectado - 1 para conectado - 2 para preparado a reconectar
        # precision: 0
        data_type: uint
 
      - name: 'Instantaneous Voltage L1'
        hub: energy_box_1
        slave: 1
        register: 108
        register_type: input
        unit_of_measurement: 'V'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned -- https://github.com/edphackathon/EDPIoTHackathon2017/blob/master/Documentation/hardware-intermediate-eb-comm.md#modbus-master-slave-for-arduino
        data_type: uint
 
      - name: 'Instantaneous Current L1'
        hub: energy_box_1
        slave: 1
        register: 109
        register_type: input
        unit_of_measurement: 'A'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned
        data_type: uint
       
      - name: 'Instantaneous Power factor'
        hub: energy_box_1
        slave: 1
        register: 123
        register_type: input
        unit_of_measurement: 'p.u.'
        count: 1
        scale: 0.001
        offset: 0
        precision: 3
        # long unsigned
        data_type: uint
 
  - platform: modbus
    scan_interval: 5
    registers:
      - name: "Instantaneous Active power + (Sum of all phases)"
        hub: energy_box_1
        slave: 1
        register: 121
        register_type: input
        unit_of_measurement: 'W'
        count: 1
        scale: 1
        offset: 0
        precision: 1
        # long unsigned
        data_type: custom
        structure: '>Q'
       
      - name: "Instantaneous Active power - (Sum of all phases)"
        hub: energy_box_1
        slave: 1
        register: 122
        register_type: input
        unit_of_measurement: 'W'
        count: 1
        scale: 1
        offset: 0
        precision: 1
        # long unsigned
        data_type: int
 
      - name: 'Current active tariff'
        hub: energy_box_1
        slave: 1
        register: 11
        register_type: input
        count: 1
        # conversão de 1/256
        scale: 0.00390625
        offset: 0
        precision: 0
        # unsigned
        data_type: uint
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Wemos D1 mini
- [X] Tasmota binary firmware version number used: 8.3.1
  - [ ] Pre-compiled
  - [X] Self-compiled
    - [x] IDE / Compiler used: tasmota container compiler, with 8.3.1 and core 2.6.7.
- [X] Flashing tools used: tasmotizer 1.1a
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
14:01:01 CMD: Backlog Template; Module; GPIO 255
14:01:01 SRC: WebConsole from 192.168.10.33
14:01:01 CMD: Group 0, Index 1, Command "BACKLOG", Data "Template; Module; GPIO 255"
14:01:02 SRC: Backlog
14:01:02 CMD: Group 0, Index 1, Command "TEMPLATE", Data ""
14:01:02 MQT: stat/tasmota_4C713F/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
14:01:02 SRC: Backlog
14:01:02 CMD: Group 0, Index 1, Command "MODULE", Data ""
14:01:02 MQT: stat/tasmota_4C713F/RESULT = {"Module":{"18":"Generic"}}
14:01:02 SRC: Backlog
14:01:02 CMD: Group 0, Index 1, Command "GPIO", Data "255"
14:01:02 MQT: stat/tasmota_4C713F/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```

- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [X] Provide the output of this command: `Status 0`:
```
14:01:36 CMD: Status 0
14:01:36 SRC: WebConsole from 192.168.10.33
14:01:36 CMD: Group 0, Index 1, Command "STATUS", Data "0"
14:01:36 MQT: stat/tasmota_4C713F/STATUS = {"Status":{"Module":18,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_4C713F","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:14:01","StartupUTC":"2020-06-13T12:47:35","Sleep":50,"CfgHolder":4617,"BootCount":44,"BCResetTime":"2020-06-13T11:34:54","SaveCount":95,"SaveAddress":"F5000"}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS2 = {"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-06-13T10:30:52","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"358/699"}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"MqttLog":4,"SysLog":4,"LogHost":"","LogPort":514,"SSId":["PSA_WIFI",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS4 = {"StatusMEM":{"ProgramSize":636,"Free":364,"Heap":23,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","87E8678F","043E1FA1","140000CF","410013F1","C800FDC9","00000024"],"Drivers":"1,2,3,4,6,8,9,10,12,13,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,3,4,5,6,29,53"}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS5 = {"StatusNET":{"Hostname":"tasmota_4C713F-4415","IPAddress":"192.168.11.212","Gateway":"192.168.11.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.11.1","Mac":"EC:FA:BC:4C:71:3F","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.10.61","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4C713F","MqttUser":"mosquitto","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS7 = {"StatusTIM":{"UTC":"2020-06-13T13:01:36","Local":"2020-06-13T14:01:36","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:54"}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS10 = {"StatusSNS":{"Time":"2020-06-13T14:01:36","MODBUS":{"Voltage_P1":0.00,"Current_P1":0.00,"Power_P1":0.00,"Power_Factor_P1":0.000,"Frequency_P1":0.00}}}
14:01:36 MQT: stat/tasmota_4C713F/STATUS11 = {"StatusSTS":{"Time":"2020-06-13T14:01:36","Uptime":"0T00:14:01","UptimeSec":841,"Vcc":2.980,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"PSA_WIFI","BSSId":"2C:FD:A1:3E:31:58","Channel":11,"RSSI":100,"Signal":-40,"LinkCount":1,"Downtime":"0T00:00:03"}}}


```
- [X] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
14:02:44 CMD: weblog 4
14:02:44 SRC: WebConsole from 192.168.10.33
14:02:44 CMD: Group 0, Index 1, Command "WEBLOG", Data "4"
14:02:44 MQT: stat/tasmota_4C713F/RESULT = {"WebLog":4}
14:02:46 MQT: tele/tasmota_4C713F/STATE = {"Time":"2020-06-13T14:02:46","Uptime":"0T00:15:11","UptimeSec":911,"Vcc":2.978,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"PSA_WIFI","BSSId":"2C:FD:A1:3E:31:58","Channel":11,"RSSI":100,"Signal":-42,"LinkCount":1,"Downtime":"0T00:00:03"}}
14:02:46 MQT: tele/tasmota_4C713F/SENSOR = {"Time":"2020-06-13T14:02:46","MODBUS":{"Voltage_P1":0.00,"Current_P1":0.00,"Power_P1":0.00,"Power_Factor_P1":0.000,"Frequency_P1":0.00}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

I'm using this actived script:

```
>D 

>B
=>sensor53 r

>M 1

+1,2,m,0,9600,MODBUS,5,30,0104006C,0104006D,01040079,0104007B,0104007F

1,010402UUuu@i0:0.1,Voltage,V,Voltage_P1,18
1,010402UUuu@i1:0.1,Current,A,Current_P1,18
1,010404UUuuUUuu@i2:1,Active Power,W,Power_P1,18
1,010402UUuu@i3:0.001,Power Factor,pu,Power_Factor_P1,19
1,010402UUuu@i4:0.1,Frequency,Hz,Frequency_P1,18
#
```

Compiled the binary with this config, as stated in: https://tasmota.github.io/docs/Smart-Meter-Interface/

```
#ifndef USE_SCRIPT
#define USE_SCRIPT
#endif
#ifndef USE_SML_M
#define USE_SML_M
#endif
#ifdef USE_RULES
#undef USE_RULES
#endif

#define SML_MAX_VARS 5
```

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

The values should get visible and reported back to the variables, respectively.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

**General data types send by this smart energy meter:**

![image](https://user-images.githubusercontent.com/41837236/84569481-d9378380-ad7e-11ea-81c3-af9a55403e2d.png)

in: https://github.com/edphackathon/EDPIoTHackathon2017/blob/master/Documentation/hardware-intermediate-eb-comm.md

**MODBUS:**

![image](https://user-images.githubusercontent.com/41837236/84569497-05eb9b00-ad7f-11ea-85a7-71a961bc29e0.png)

in: https://github.com/edphackathon/EDPIoTHackathon2017/blob/master/Documentation/hardware-intermediate-eb.md#eb-introduction

**Register addresses and data types:**

![image](https://user-images.githubusercontent.com/41837236/84569508-1734a780-ad7f-11ea-87f9-79ad5e8c93d1.png)

In: https://www.edpdistribuicao.pt/sites/edd/files/normative_docs/DEF-C44-509.pdf

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by tiagofreire-pt** [comment]
I detected that is not available an option for transmission with 8N2, just for 8N1:

```
- m = MODBus binary coding with serial mode 8N1
- M = MODBus binary coding with serial mode 8E1
```

In: https://tasmota.github.io/docs/Smart-Meter-Interface/#meter-declaration



This smart meter uses 8N2:

![image](https://user-images.githubusercontent.com/41837236/84569940-00dc1b00-ad82-11ea-9bf1-de8dca0ca901.png)

In: https://www.edpdistribuicao.pt/sites/edd/files/normative_docs/DEF-C44-509.pdf

Is this relevant?

**Comment by gemu2015** [comment]
did you check in debug mode what comes back from the meter ?
go to console and type : sensor53 d1
you should see the hex values coming from the meter.
(to revert to normal mode you must type sensor53 d0)

according 8N2 your home assistant setup also uses 8N1
don't think that is the reason

**Comment by tiagofreire-pt** [comment]
> did you check in debug mode what comes back from the meter ?
> go to console and type : sensor53 d1
> you should see the hex values coming from the meter.
> (to revert to normal mode you must type sensor53 d0)
> 
> according 8N2 your home assistant setup also uses 8N1
> don't think that is the reason

This is the output:

```
16:37:14 MQT: stat/tasmota_4C713F/RESULT = {"Time":"2020-06-13T16:37:14","SML":{"CMD":"dump: 1"}}
16:37:14 : 01 04 08 00 00 01 b3 00 00 00 00 
16:37:14 : 20 06 
16:37:17 : 01 84 04 42 c3 
16:37:18 WIF: Checking connection...
16:37:20 : 01 04 0a 01 f4 01 02 09 0b 0e 
16:37:20 : 0a 0d 0c d7 57 
16:37:23 : 01 04 04 09 16 00 15 
16:37:23 : d8 13 
16:37:26 : 01 84 04 42 c3 
16:37:29 : 01 04 08 00 00 01 a1 00 00 00 
16:37:29 : 00 98 05 
16:37:32 : 01 84 04 42 c3 
16:37:35 : 01 04 0a 01 f4 01 02 09 0b 0e 
16:37:35 : 0a 0d 0c d7 57 
16:37:38 : 01 04 04 09 19 00 14 29 d0 
16:37:38 WIF: Checking connection...
16:37:41 : 01 84 04 42 c3 
16:37:44 : 01 04 08 00 00 01 84 00 00 00 00 d5 
16:37:44 : c2 
```

**Comment by gemu2015** [comment]
looks a bit strange
try requesting one register only
(from the docs: the number of requested registers is fixed to 2, however with the char 'r' before the hex string the complete request string may be specified
...r010400000001,r010400020003,...)

try with one register only and one value

+1,2,m,0,9600,MODBUS,5,30,r0104006C0001

**Comment by tiagofreire-pt** [comment]
With this script:

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,MODBUS,5,100,0104006C
 
1,010402UUuu@i0:0.1,Voltage,V,Voltage_P1,18
#
```

The output, for > 30 seconds (polling each 10 sec):

```
17:03:14 CMD: sensor53 d1
17:03:14 SRC: WebConsole from 192.168.10.33
17:03:14 CMD: Group 0, Index 53, Command "SENSOR", Data "d1"
17:03:14 MQT: stat/tasmota_4C713F/RESULT = {"Time":"2020-06-13T17:03:14","SML":{"CMD":"dump: 1"}}
17:03:19 : 01 04 04 09 18 00 17 38 11 
17:03:29 : 01 04 04 09 1a 00 18 
17:03:29 : d9 d5 
17:03:30 WIF: Checking connection...
17:03:39 : 01 04 04 09 1b 00 18 88 15 
17:03:49 : 01 04 04 09 1a 00 17 99 d1 
17:03:50 WIF: Checking connection...
17:03:55 MQT: tele/tasmota_4C713F/STATE = {"Time":"2020-06-13T17:03:55","Uptime":"0T00:10:10","UptimeSec":610,"Vcc":2.993,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":99,"MqttCount":1,"Wifi":{"AP":1,"SSId":"PSA_WIFI","BSSId":"2C:FD:A1:3E:31:58","Channel":11,"RSSI":100,"Signal":-38,"LinkCount":1,"Downtime":"0T00:00:03"}}
17:03:55 MQT: tele/tasmota_4C713F/SENSOR = {"Time":"2020-06-13T17:03:55","MODBUS":{"Voltage_P1":0.00}}
```

**Comment by gemu2015** [comment]
ok looks better,
the decoder however is wrong needs 
010404 .... 
may be a long or float value

**Comment by tiagofreire-pt** [comment]
This parameter (Voltage_P1) is a "Long unsigned". 

New script:

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,MODBUS,5,100,0104006C
 
1,010404UUuuUUuu@i0:0.1,Voltage,V,Voltage_P1,18
#
```

The output:

```
17:12:27 CMD: sensor53 d1
17:12:27 SRC: WebConsole from 192.168.10.33
17:12:27 CMD: Group 0, Index 53, Command "SENSOR", Data "d1"
17:12:27 MQT: stat/tasmota_4C713F/RESULT = {"Time":"2020-06-13T17:12:27","SML":{"CMD":"dump: 1"}}
17:12:29 : 01 04 04 09 24 00 17 f8 1d 
17:12:30 WIF: Checking connection...
17:12:39 : 01 04 04 09 22 00 
17:12:39 : 17 18 1c 
17:12:49 : 01 04 04 09 22 00 17 
17:12:49 : 18 1c 
17:12:50 WIF: Checking connection...
17:12:59 : 01 04 04 09 24 
17:12:59 : 00 17 f8 1d 
17:13:09 : 01 04 04 09 22 00 17 
17:13:09 : 18 1c 
17:13:10 WIF: Checking connection...
```

The voltage value continues to be reported as 0.00 Volt. :(

**Comment by tiagofreire-pt** [comment]
The manual states the "long unsigned" are 2 bytes long. The UUuu (2 bytes?) previously used fails, and also UUuuUUuu (4 bytes?)

**Comment by tiagofreire-pt** [comment]
@arendst , could you also give a hand on this, please? :)

Thanks for both of you.

**Comment by gemu2015** [comment]
the meter returns 4 bytes payload (+2 bytes crc)
e.g. 01 04 04 09 22 00 17 18 1c
09 22 00 17 being the payload 
according to your table above register 6c = unsigned long
however 0922 = 2338 looks like voltage times 10 =????
if the decoder fails probably the crc is wrong
if the crc would be ok it would decode something 
the crc on transmit is obviously ok, otherwise the meter would not respond

**Comment by gemu2015** [comment]
did you switch back to normal mode ?
in debug mode the decoder is not active

**Comment by tiagofreire-pt** [comment]
> the meter returns 4 bytes payload (+2 bytes crc)
> e.g. 01 04 04 09 22 00 17 18 1c
> 09 22 00 17 being the payload
>
> however 0922 = 2338 looks like voltage times 10 =????

Yes, the scaler is 10^-1, or, 0.1, leading to a voltage of 233.8 Volt.

> did you switch back to normal mode ?
> in debug mode the decoder is not active

No, I'm running this with debug (sensor53 d1) all the time, since you suggest it. lol

Disabling it, with this one:

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,MODBUS,5,100,0104006C
 
1,010404UUuuuuuu@i0:0.1,Voltage,V,Voltage_P1,2
#
```

I now get a value, but widely missing the target:

```
17:39:42 MQT: tele/tasmota_4C713F/SENSOR = {"Time":"2020-06-13T17:39:42","MODBUS":{"Voltage_P1":200.00}}
```

**Comment by gemu2015** [comment]
your decoder is still wrong
UUuuuuuu is not defined.
use either uuUUuuUU or UUuuUUuu

**Comment by tiagofreire-pt** [comment]
@gemu2015 , finally!

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,MODBUS,5,100,0104006C
 
1,010404UUuuxxxx@i0:10,Voltage,V,Voltage_P1,2
#
```

![image](https://user-images.githubusercontent.com/41837236/84574301-75708300-ad9d-11ea-960d-0d665d20fed8.png)

YAY! :D :D :D

**Comment by gemu2015** [comment]
ok, now proceed to the other values
good look

**Comment by ascillato2** [comment]
Great to know that now it is working for you. 

Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by tiagofreire-pt** [comment]
@gemu2015 , 

I'm getting errors, reading the L1 current values:

```
>D 

>B
=>sensor53 r

>M 1

+1,14,m,1,9600,MODBUS,5,100,0104006D
 
1,010404UUuuxxxx@i0:10,Current,V,Current_P1,2
#
```

Output:

```
18:29:55 : 01 84 04 42 c3 
```

![image](https://user-images.githubusercontent.com/41837236/84575297-034f6c80-ada4-11ea-9522-bae75a493845.png)

I'm sure the register is correct (0x006C or 109).

**Comment by gemu2015** [comment]
go to raw mode for all your queries, may be your meter doesn't like 2 registers at once
+1,14,m,1,9600,MODBUS,5,100,r0104006D0001

**Comment by tiagofreire-pt** [comment]
> +1,14,m,1,9600,MODBUS,5,100,r0104006D0001

That instruction does not output anything on debug mode:

```
>D 

>B
=>sensor53 r

>M 1

+1,14,m,1,9600,MODBUS,5,100,r0104006D0001
 
1,010404UUuuxxxx@i0:10,Current,V,Current_P1,2
#
```

**Comment by tiagofreire-pt** [comment]
This behavior occurs also with the 0x007B register (power factor).

**Comment by gemu2015** [comment]
there are only 2 modes without prefix 2 registers are fetched.
with prefix r the number of register to fetch must be appended.
since it worked to fetch 6c 
try the following, fetching 2 registers at once (both with index 0)

+1,14,m,1,9600,MODBUS,5,100,0104006C
 
1,010404UUuuxxxx@i0:10,Voltage,V,Voltage_P1,2
1,010404xxxxUUuu@i0:10,Current,V,Current_P1,2
#

**Comment by tiagofreire-pt** [comment]
> +1,14,m,1,9600,MODBUS,5,100,0104006C
> 
> 1,010404UUuuxxxx@i0:10,Voltage,V,Voltage_P1,2
> 1,010404xxxxUUuu@i0:10,Current,V,Current_P1,2

Does not work properly, as both voltage and current get the same value (the one from voltage):

```
18:56:59 MQT: tele/tasmota_4C713F/SENSOR = {"Time":"2020-06-13T18:56:59","EB":{"Voltage_P1":232.20,"Current_P1":232.20,"Power_P1":367.00,"Frequency_P1":50.00}}
```

**Comment by gemu2015** [comment]
that should not be the case. from the values of your dump above the "long" words are different.
post your complete script

**Comment by tiagofreire-pt** [comment]
> that should not be the case. from the values of your dump above the "long" words are different.
> post your complete script

The one: 

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,EB,5,50,0104006C
 
1,010404UUuuxxxx@i0:10,Voltage,V,Voltage_P1,2
1,010404UUuuxxxx@i0:10,Current,A,Current_P1,2
#
```

**Comment by gemu2015** [comment]
second line is wrong, look at my post

**Comment by tiagofreire-pt** [comment]
> second line is wrong, look at my post

I'm just blind after all these hours looking at this! :D

It worked.

```
19:12:09 MQT: tele/tasmota_4C713F/SENSOR = {"Time":"2020-06-13T19:12:09","EB":{"Voltage_P1":231.10,"Current_P1":2.60}}
```

What I'm not be able to address is the power factor, reading its own register (0x007B), the smart meter returns an error.

**Comment by gemu2015** [comment]
i have no idea why your meter returns an error here.
since others work, these are probably not implemented at your model

**Comment by tiagofreire-pt** [comment]
> i have no idea why your meter returns an error here.
> since others work, these are probably not implemented at your model

Oddly, it works on HA, using its decimal number 123.

**Comment by kugelkopf123** [comment]
Perhaps it would be great to add this meter to the docs. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tiagofreire-pt** [comment]
> Perhaps it would be great to add this meter to the docs.
> 
> Sent with [GitHawk](http://githawk.com)

I will, soon. As this is a huge step into it and widely expected in the community. :)

**Comment by gemu2015** [comment]
ok, i think i found the reason,
7B is there, but 7c is only there on 3 phase meters. do you have a single phase meter ?
this would explain the error when grabbing 2 registers at once

**Comment by tiagofreire-pt** [comment]
Mine is single phase.

Even using this:

```
>D
 
>B
=>sensor53 r
 
>M 1
 
+1,14,m,1,9600,EB,5,50,0104007B
 
1,010404UUuuxxxx@i0:1000,PF1,pu,PFactor_P1,3
#
```

I get error messages.

**Comment by gemu2015** [comment]
yes but try to fetch 7a, but read 2. part of payload
+1,14,m,1,9600,EB,5,50,0104007A
1,010404xxxxUUuu@i0:1000,PF1,pu,PFactor_P1,3

**Comment by gemu2015** [comment]
ok, but 7a is "double long" above decoder won't work
but the error should be gone

**Comment by gemu2015** [comment]
still wondering why raw mode does not work (single register read)
+1,14,m,1,9600,EB,5,50,r0104007B0001
1,010404UUuu@i0:1000,PF1,pu,PFactor_P1,3

**Comment by gemu2015** [comment]
if reading 2 registers at 7a works, this decoder might work
+1,14,m,1,9600,EB,5,50,0104007A
1,010406xxxxxxxxUUuu@i0:1000,PF1,pu,PFactor_P1,3

**Comment by tiagofreire-pt** [comment]
@gemu2015 , you deserve a really huge bronze statue!!! 

```
>D 

>B
=>sensor53 r

>M 1

+1,14,m,1,9600,EB,5,10,0104006C,01040079,0104007F,0104007A
 
1,010404UUuuxxxx@i0:10,Voltage,V,Voltage_P1,2
1,010404xxxxUUuu@i0:10,Current,V,Current_P1,2
1,010408UUuuUUuuxxxxxxxxxxxx@i1:1,Power,W,Power_P1,2
1,01040aUUuuxxxx@i2:10,Frequency,Hz,Frequency_P1,2
1,010406xxxxxxxxUUuu@i3:1000,Power Factor,pu,PFactor_P1,3
#
```

Many, many thanks!
