### ISSUE TITLE
Feature Request: add command to power cycle GPIO14

### ISSUE THREAD

**Issue by tomeraviram** [arendst/Tasmota#8681]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
It happened to me few times that after a long period of using DS18B20 temperature sensor on GPIO14 the sensor stops sending temperature or sends wrong reading. I tried to restart/reset the device in order to fix the issue few time without success, and I could only get it back to work by powering the device off and turning it back on, after which the sensor began sending the correct temperature.

**Describe the solution you'd like**  
Is it possible to add a command that power cycles GPIO14 (turns off/on the VCC) in order to reset the connected sensor?
Alternatively, is it possible to add a command to power cycle the whole device without loosing WIFI and MQTT settings, similar to "reset 1" which to my understanding power cycles the device after reset to firmware defaults only without erasing WIFI and MQTT settings?

**Describe alternatives you've considered**  
I tried to restart/reset the device in order to fix the issue few time without success.
I also tried setting GPIO14 as LED/RELAY/PWM in order to power it off.

**Comment by ascillato2** [comment]
For restarting Tasmota you can use the command RESTART.

If you want to make a restart timer, you can use a rule to trigger that restart.

Anyway, it should be better that you fix that sensor. May be it is defect.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
