### ISSUE TITLE
HUE Simulation missing ", so ignorde by Alexa

### ISSUE THREAD

**Issue by TheRocktagon** [arendst/Tasmota#8685]
Usinge Scripting and Hue (and Zigbee usw)
I found an Error in xdrv_10

Line: 4821 *response+=String(EncodeLightId(hue_devs+devices_present+1))+"\":";
must be (adding "\""+):
                *response+="\""+String(EncodeLightId(hue_devs+devices_present+1,0))+"\":";

The " is missing in the String so it only reports:

http://192.168.178.58/apicode/lights
{235104865":{"state":........

and Alexa ignore it.
Withe the "\""+ it reports: 

{"235104865":{"state":........

and Alexa found the device.

**Comment by s-hadinger** [comment]
@gemu2015 Can you please check?

I'm not sure that the patch proposed here works in all cases.

**Comment by gemu2015** [comment]
@TheRocktagon 
can you check this fix ?

if (response) {
        if (devices_present) {
          *response+=",\"";
        }
        else {
          if (hue_devs>0) *response+=",\"";
          else *response+="\"";
        }
        *response+=String(EncodeLightId(hue_devs+devices_present+1))+"\":";
        Script_HueStatus(response,hue_devs);

**Comment by gemu2015** [comment]
ok reactivated my Alexa setup and checked, my fix works in all conditions doing pr soon.

**Comment by TheRocktagon** [comment]
Checked it without my modyfication and it works good. -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.06.20, 15:25 schrieb gemu <notifications@github.com>:

   
  @TheRocktagon can you check this fix ? 
  if (response) { if (devices_present) { *response+=",""; } else { if (hue_devs>0) *response+=",""; else *response+="""; } *response+=String(EncodeLightId(hue_devs+devices_present+1))+"":"; Script_HueStatus(response,hue_devs);

**Comment by TheRocktagon** [comment]
Hello, sry for the short disturbance again. Just a little hint, init the MCP Ic (Sensor29) in >B section by using scripting it doesen't work, just errors by booting.I only changing in tasmota. Ino:put "XsnsCall(FUNC_INIT)" before "XdrvCall(FUNC_INIT)" so the sensors would be init bevore the script starts and all works fine.Picture included.GreetsTorsten-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.06.20, 16:45 schrieb gemu <notifications@github.com>:

   
  ok reactivated my Alexa setup and checked, my fix works in all conditions doing pr soon.

**Comment by gemu2015** [comment]
ok, we have to ask @arends if something speaks against it.
otherwise good hint.

**Comment by gemu2015** [comment]
i will solve this by introducing a new section after sensor init, so to not break anything
executed after sensor init
>BS
will make a pr soon

  XdrvCall(FUNC_INIT);
  XsnsCall(FUNC_INIT);
#ifdef USE_SCRIPT
  Run_Scripter(">BS",3,0);
#endif

**Comment by arendst** [comment]
Yes. The driver needs to be init BEFORE the sensors. 

@gemu your solution looks OK.
