### ISSUE TITLE
Display comands are not working 

### ISSUE THREAD

**Issue by gamer123** [arendst/Tasmota#8692]
### PROBLEM DESCRIPTION
The display comands they are listet in the comand list do not work.
But I think there is another problem.

I tried the pre-compiled version tasmota-display 8.3.1.
I tried the pre-compiled version tasmota-display 8.1.0.
I tried the pre-compiled version sonoff-display 6.4.0.

And i made some own binaries and i used 8.3.1

#define USE_I2C // I2C using library wire (+10k code, 0k2 mem, 124 iram)
#ifdef USE_I2C

#define USE_DISPLAY // Add I2C Display Support (+2k code)
#define USE_DISPLAY_MODES1TO5 // Enable display mode 1 to 5 in addition to mode 0
#define USE_DISPLAY_SSD1306 // [DisplayModel 2] [I2cDriver4] Enable SSD1306 Oled 128x64 display (I2C addresses 0x3C and 0x3D) (+16k code)

#endif // USE_I2C
.

The problem is that the commands in the console are acknowledged as unknown.
I try to set up an OLED display with 64x48 pixel.

Display
DisplayModel 2
DisplayWidth 64
DisplayHeight 4

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): Wemos d1 mini Pro 
- [x ] Tasmota binary firmware version number used: tasmota display
  - [x ] Pre-compiled
  - [ x] Self-compiled
    - [x ] IDE / Compiler used: 2.7.1
- [X ] Flashing tools used: Tasmota PyFlasher 
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


19:23:47 SRC: WebConsole from 192.168.0.69
19:23:47 CMD: Group 0, Index 1, Command "STATUS", Data "0"
19:23:47 RSL: stat/tasmota_F4E97B/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_F4E97B","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:23:47 RSL: stat/tasmota_F4E97B/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"External System","Uptime":"0T00:01:09","StartupUTC":"2020-06-14T18:22:38","Sleep":50,"CfgHolder":4617,"BootCount":4,"BCResetTime":"2020-06-14T18:10:15","SaveCount":11,"SaveAddress":"F9000"}}
19:23:47 RSL: stat/tasmota_F4E97B/STATUS2 = {"StatusFWR":{"Version":"8.3.1(display)","BuildDateTime":"2020-05-18T15:41:58","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"374/699"}}
19:23:47 RSL: stat/tasmota_F4E97B/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Pencil_Gast",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
19:23:47 RSL: stat/tasmota_F4E97B/STATUS4 = {"StatusMEM":{"ProgramSize":546,"Free":456,"Heap":27,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashMode":3,"Features":["00000809","8FAAA59F","04049FA0","000000C1","010000C0","00004080","00000020"],"Drivers":"1,2,4,5,8,9,10,13,16","Sensors":"1,2,5,6"}}
19:23:48 RSL: stat/tasmota_F4E97B/STATUS5 = {"StatusNET":{"Hostname":"test","IPAddress":"192.168.0.77","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"A4:CF:12:F4:E9:7B","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
19:23:48 RSL: stat/tasmota_F4E97B/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F4E97B","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
19:23:48 RSL: stat/tasmota_F4E97B/STATUS7 = {"StatusTIM":{"UTC":"2020-06-14T18:23:48","Local":"2020-06-14T19:23:48","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:54"}}
19:23:48 RSL: stat/tasmota_F4E97B/STATUS10 = {"StatusSNS":{"Time":"2020-06-14T19:23:48"}}
19:23:48 RSL: stat/tasmota_F4E97B/STATUS11 = {"StatusSTS":{"Time":"2020-06-14T19:23:48","Uptime":"0T00:01:10","UptimeSec":70,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Pencil_Gast","BSSId":"38:10:D5:DB:42:A5","Channel":11,"RSSI":66,"Signal":-67,"LinkCount":1,"Downtime":"0T00:00:06"}}}
19



```
- [x ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

00:00:00 CFG: Loaded from flash at F5, Count 7
00:00:00 Project tasmota Tasmota Version 8.3.1(display)-2_7_1
00:00:00 WIF: Connecting to AP1 Pencil_Gast Channel 11 BSSId 38:10:D5:DB:42:A5 in mode 11N as test...
00:00:01 WIF: Connected
00:00:01 HTP: Web server active on test with IP address 192.168.0.77
18:10:16 RSL: tele/tasmota_F4E97B/INFO1 = {"Module":"Sonoff Basic","Version":"8.3.1(display)","FallbackTopic":"cmnd/DVES_F4E97B_fb/","GroupTopic":"cmnd/tasmotas/"}
18:10:16 RSL: tele/tasmota_F4E97B/INFO2 = {"WebServerMode":"Admin","Hostname":"test","IPAddress":"192.168.0.77"}
18:10:16 RSL: tele/tasmota_F4E97B/INFO3 = {"RestartReason":"Software/System restart"}
18:10:16 RSL: stat/tasmota_F4E97B/RESULT = {"POWER":"OFF"}
18:10:16 RSL: stat/tasmota_F4E97B/POWER = OFF
18:10:20 RSL: tele/tasmota_F4E97B/STATE = {"Time":"2020-06-14T18:10:20","Uptime":"0T00:00:09","UptimeSec":9,"Heap":30,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Pencil_Gast","BSSId":"38:10:D5:DB:42:A5","Channel":11,"RSSI":36,"Signal":-82,"LinkCount":1,"Downtime":"0T00:00:03"}}
18:10:41 CMD: display
18:10:41 RSL: stat/tasmota_F4E97B/RESULT = {"Command":"Unknown"}
18:11:10 CMD: displaymodel 2
18:11:10 RSL: stat/tasmota_F4E97B/RESULT = {"Command":"Unknown"}
18:11:24 CMD: DisplayModel 2
18:11:24 RSL: stat/tasmota_F4E97B/RESULT = {"Command":"Unknown"}
18:12:13 CFG: CR 374/699
18:12:13 LOG: SerialLog 2, WebLog 4, MqttLog 0, SysLog 0, LogHost , LogPort 514, TelePeriod 300
18:12:13 HTP: Configuration
18:12:13 CFG: Saved to flash at FA, Count 10, Bytes 4096
18:12:14 WIF: Checking connection...
18:12:16 HTP: Main Menu
18:12:18 HTP: Console
18:12:24 CMD: Display
18:12:24 SRC: WebConsole from 192.168.0.14
18:12:24 CMD: Group 0, Index 1, Command "DISPLAY", Data ""
18:12:24 RSL: stat/tasmota_F4E97B/RESULT = {"Command":"Unknown"}
18:12:34 WIF: Checking connection...
18:12:36 CMD: DisplayModel 2
18:12:36 SRC: WebConsole from 192.168.0.14
18:12:36 CMD: Group 0, Index 1, Command "DISPLAYMODEL", Data "2"
18:12:36 RSL: stat/tasmota_F4E97B/RESULT = {"Command":"Unknown"}

### TO REPRODUCE
Try to set up a tasmota-Display
I try to set up an OLED display with 64x48 pixel.


### EXPECTED BEHAVIOUR

Hm i would like to cofigure the display.


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._



### ADDITIONAL CONTEXT
I only selected the I2C ports At GIPO 1 and 2 
I selected the generic modul (18).
I try to set up an OLED display with 64x48 pixel.


**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, post status 0 output as requested. Thanks.

**Comment by gamer123** [comment]
Sorry for that i added the Status 0.

**Comment by Jason2866** [comment]
GPIO 1 and 2 are not the best choice. What do you get when you fire the command `i2cscan`

**Comment by device111** [comment]
change your GPIO Ports to 4 and 5 as Jason2866 suggested.
If you have a dev Board (NodeMCU, o.s) , the GPIO 2 are almost connected with the On-board LED.

**Comment by gamer123** [comment]
hello,

i changed the the port to 4 and 5. 
i used again the tasmota-display 8.3.1 with Tasmota-PyFlasher-1.0

i2cscan 
07:50:40 SRC: WebConsole from 192.168.8.103
07:50:40 CMD: Group 0, Index 1, Command "I2CSCAN", Data ""
07:50:40 RSL: stat/tasmota_F4E98B/RESULT = {"Command":"Error"}

i tried it with and without the display -->same result 

I2cdriver 

08:02:02 CMD: i2cdriver
08:02:02 SRC: WebConsole from 192.168.8.103
08:02:02 CMD: Group 0, Index 1, Command "I2CDRIVER", Data ""
08:02:02 RSL: stat/tasmota_F4E98B/RESULT = {"I2CDriver":"3,4,5,6,47"}

In my point of view i need driver 4, so it should be fine.

i use the wemos D1 mini pro with 4MB

The display is similar to 
https://www.reichelt.de/d1-shield-oled-display-0-66-1-67-cm-d1z-oled-0-66-p266074.html

in my point of view is the big question is why is the comand displaymodel 2 unknown in the webconsole.

**Comment by device111** [comment]
Your Display is not found. It is not a Problem with Tasmota programming. Please go to support chat, may some one can help you.

**Comment by sandu-bogdan** [comment]
how you solve? I have same problem...
