### ISSUE TITLE
Shutter control based on temperature

### ISSUE THREAD

**Issue by DarkShadowNight** [arendst/Tasmota#8698]
Hello All,

I'm new to Tasmota, but familiar with ESP and programming.
I bought a Sonoff 4Ch Pro r2 for controlling two shutters.
No big deal to get this working.

I also managed to get the temperature reading from a DS18B20 working.
Is it possible to control the shutters based on this temperature reading?

For example:
If temperature >= 22°C and temperature rise is faster than x °C/hour then close shutters for 75%.

Thanks

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
