### ISSUE TITLE
Koogeek door Sensor

### ISSUE THREAD

**Issue by salopette** [arendst/Tasmota#8708]
Hello, I got Koogeek door sensor today.
An esp8622 is installed!

can you flash that with Tasmota?

![sshot-5](https://user-images.githubusercontent.com/32480002/84810101-2596f380-b00b-11ea-9d53-d353aebe49b2.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/84810102-26c82080-b00b-11ea-9aa8-f2db4b0c0141.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/84810103-26c82080-b00b-11ea-9f86-326ca5ea559c.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/84810105-2760b700-b00b-11ea-9245-efb08ee21823.jpg)
![sshot-4](https://user-images.githubusercontent.com/32480002/84810106-2760b700-b00b-11ea-8922-2975cbbf8793.jpg)

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
