### ISSUE TITLE
Web password too long

### ISSUE THREAD

**Issue by tom2199** [arendst/Tasmota#8720]
### PROBLEM DESCRIPTION
I typed a web password in that was 128 chars, now I can't log in into the web ui.

### REQUESTED INFORMATION
- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Aisirer RGBW Modul
- [x] Tasmota binary firmware version number used: 8.3.1
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____

- [X] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
09:57:13 RSL: RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":32,"Free":479,"Rules":"ON Dimmer#Boot DO Power ON ENDON"}
09:57:14 RSL: RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
09:57:14 RSL: RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
```

### TO REPRODUCE
Set web password over 32 chars

### EXPECTED BEHAVIOUR
That the password would be saved. Of course, if it's too long, don't save it or save the first 32 chars.

### ADDITIONAL CONTEXT
I know it was stupid that I didn't read the docs beforehand, but power cycling doesn't work (maybe because of 8.3.1? I know it did work before) so this is my last chance. Is there any way to recover the web password? I have the URL and the full password I typed in.

**Comment by Jason2866** [comment]
Just do a serial flash. Dont forget to erase flash before flashing Tasmota.

**Comment by arendst** [comment]
A bit longer password should work. I won't duscuss if 125 character is a bit but hey, it's your device.

If you have access to the device by serial connection or mqtt you can simply execute command ``webpassword "`` to erase the password.

**Comment by tom2199** [comment]
Sadly I don't have a mqtt setup and i cannot serial flash it without destroying the device more or less. Is there any chance to know which password was saved by tasmota? The password I used was: "WJz1eZnKP9snSj6231Wchm3kkwKtEvDLwgxdCjmNOwG00TKR2IulEtGmMPi8FmpIIUKOwBTwobtpJH9AJcQxR4d05jCntfxVSlR3Q87fACAwA0wyBgBZoxBMWnbsSHGO"

**Comment by arendst** [comment]
I just tried your password on one of my devices and it worked!

Are you sure you used username ``admin``?

You might want to try to use the ``decode-config.py`` tool which needs the same password. Using a command line like 
```
python decode-config.py -d your-device-name -o config-dump-file -t bin --ignore-warnings -p WJz1eZnKP9snSj6231Wchm3kkwKtEvDLwgxdCjmNOwG00TKR2IulEtGmMPi8FmpIIUKOwBTwobtpJH9AJcQxR4d05jCntfxVSlR3Q87fACAwA0wyBgBZoxBMWnbsSHGO
```
It dumps the config and verifies a correct password. No real use in your case.

Anyway, the quick power toggles should still work so I suggest you just try again at least 7 quick power toggles.

**Comment by tom2199** [comment]
> I just tried your password on one of my devices and it worked!
> 
> Are you sure you used username `admin`?
> 
> You might want to try to use the `decode-config.py` tool which needs the same password. Using a command line like
> 
> ```
> python decode-config.py -d your-device-name -o config-dump-file -t bin --ignore-warnings -p WJz1eZnKP9snSj6231Wchm3kkwKtEvDLwgxdCjmNOwG00TKR2IulEtGmMPi8FmpIIUKOwBTwobtpJH9AJcQxR4d05jCntfxVSlR3Q87fACAwA0wyBgBZoxBMWnbsSHGO
> ```
> 
> It dumps the config and verifies a correct password. No real use in your case.
> 
> Anyway, the quick power toggles should still work so I suggest you just try again at least 7 quick power toggles.

Yes I used admin as the username, here is the complete URL that was send to my device:
```
http://192.168.178.39/co?t1=%7B%22NAME%22%3A%22Aisirer+RGBW%22%2C%22GPIO%22%3A%5B0%2C0%2C0%2C0%2C37%2C40%2C0%2C0%2C38%2C0%2C39%2C0%2C0%5D%2C%22FLAG%22%3A0%2C%22BASE%22%3A18%7D&wp=WJz1eZnKP9snSj6231Wchm3kkwKtEvDLwgxdCjmNOwG00TKR2IulEtGmMPi8FmpIIUKOwBTwobtpJH9AJcQxR4d05jCntfxVSlR3Q87fACAwA0wyBgBZoxBMWnbsSHGO&dn=Tischlampe&a0=Tischlampe&b2=2&save=
```

The decode-config.py gets me this result:
```
Load data from device '192.168.178.39'
ERROR 401 (@2623): Error on http GET request for http://192.168.178.39/dl - Unauthorized
Premature exit -  #401
```
So as expected. The power toggle doesn't work for some reason, I know it is not part of this issue but I recorded a short video:
https://www.youtube.com/watch?v=-5VXfmDTIWk
The lamp shouldn't turn on the 7th time, because tasmota should reset all the settings, or am I wrong? Am I doing something wrong? I've resetted multiple devices by mistake in the past, and now I can't do it even if I want to.

**Comment by arendst** [comment]
So for some reason the password is stored wrong considering the ``Unauthorized`` message.

I think your quick power cycles are too slow. make them a lot quicker pls.

**Comment by tom2199** [comment]
> So for some reason the password is stored wrong considering the `Unauthorized` message.
> 
> I think your quick power cycles are too slow. make them a lot quicker pls.

Thank you for your time, I appreciate the effort for trying to help me!
I recoreded it again, am I still doing something wrong? https://www.youtube.com/watch?v=Ec0Zin2GWNQ

**Comment by arendst** [comment]
Pls try eight times

**Comment by tom2199** [comment]
> Pls try eight times

Here's the video: https://www.youtube.com/watch?v=1SWXyMJ9Ff8
I even tried 9 and 10 times, still nothing unfortunately. Does it have something to do with the rule I've set up?

**Comment by arendst** [comment]
No. The rule should not be interfering.

Sorry, out of ideas

**Comment by tom2199** [comment]
So there is no option to recover my password? That's a shame, I thought if we could reproduce the steps it would be possible. Thank you for your help.
