### ISSUE TITLE
Configuring two APs / SSIDs, how exactly should the device behave?

### ISSUE THREAD

**Issue by JsBergbau** [arendst/Tasmota#8726]
### PROBLEM DESCRIPTION
No information how SSIDs are selected

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4) Don't want to register there as it does not respect privacy at all, sorry. 
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Just use Tasmota

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
You can configure 2 APs or SSIDs in parallel. However the FAQ https://tasmota.github.io/docs/FAQ/ doesn't state how the device is behaving.
Is second SSID only for backup? If so when SSID 1 is available again, will it switch to SSID 1? Or is it continoulsy connected with both Wifis, accepting MQTT commands on both?
### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![grafik](https://user-images.githubusercontent.com/37013344/85055369-f90ae500-b18c-11ea-97eb-d325b0195df8.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
It is only connected to one AP at any one time. So56 & So57 allow Tasmota to switch which AP it connects to based on best signal.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by JsBergbau** [comment]
Ok, I've found out. You have to set WifiConfig to 4 `4 = disable Wi-Fi Manager but retry the other AP without rebooting` then it won't create an AP to connect, but switches to alternate AP. But obviously it connects only back to AP1 when AP2 is gone. 
https://tasmota.github.io/docs/Commands/
