### ISSUE TITLE
Sonoff 4CH with DS18B20 Temperature Sensor

### ISSUE THREAD

**Issue by bug84** [arendst/Tasmota#8727]
hi
I have install on my sonoff 4ch  an DS18B20 Sensor on GPIO Pins (3.3V GND and io2) and with an 4.7KOhm Transistor between red and yellow.
In Configuration I select GPIO2 is the (4) DS18x20 Sensor. 
But not appear on Tasmota home Screen???
Also I have pinned the Data line to GPIO3 (TX), but don’t show me the Temperature).
On wires I have the 3.3v measured.

Can you help me? 

do I have to change something on sonoff or rewrite something on the firmware?

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
