### ISSUE TITLE
iBeacon JSON attributes (related to #8693)

### ISSUE THREAD

**Issue by Elix-g** [arendst/Tasmota#8745]
**Have you looked for this feature in other issues and in the docs?**  

Yes I did.

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

Thanks a lot for the swift implementation of #8693! Everything working fine except two details:

- The MAC address of detected iBeacons is now being omitted and not issued as part of the MQTT message.

- The decision, if a zero RSSI for a disappeared iBeacon is being sent by MQTT is still based on the iBeacon's MAC address. Having an iBeacon that uses MAC randomization, leads to frequent zero RSSI MQTT messages in the moment the beacons switches to another MAC address.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

- Add iBeacon's MAC address as a name/value pair to MQTT JSON string

- Modify condition which decides if zero RSSI is being sent for an iBeacon from disppeared MAC address to disappeared UID.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
could you please try this.
if it works for you ill do a pr

[xsns_52_ibeacon.ino.zip](https://github.com/arendst/Tasmota/files/4809498/xsns_52_ibeacon.ino.zip)

**Comment by Elix-g** [comment]
Thank you for the amazing response time!

Works like a charm, MAC address is part of the JSON message and no zero RSSI message issued after MAC address change:

![ibeacon_UID_vs_RSSI](https://user-images.githubusercontent.com/37552418/85225942-ea167380-b3d4-11ea-8081-7d4e9063752e.JPG)


One more detail: Is it easy to implement a defined JSON path? By using IBEACON__uid_ as a JSON name, it's difficult to parse the JSON message. Adding the UID as a name/value pair to a unique parent name improves the possibility to parse a message and would unify the message with those from other sensors. Assuming "IBEACON" as the sensor name:

{"Time":"2020-06-21T14:40:59","IBEACON":{"UID":"20D01D1B6EF64FADAE3DE340F7E98DBE","MAJOR":"000D","MINOR":"0007","MAC":"5348A6E47435","RSSI":-94}}

**Comment by gemu2015** [comment]
no problem, next try

[xsns_52_ibeacon.ino.zip](https://github.com/arendst/Tasmota/files/4809589/xsns_52_ibeacon.ino.zip)

**Comment by Elix-g** [comment]
Time for pr :-)

![ibeacon_UID_vs_RSSI_02](https://user-images.githubusercontent.com/37552418/85226970-8db65280-b3da-11ea-99cc-1b153c96f019.JPG)

Perfect now, many thanks again!

**Comment by ascillato2** [comment]
Closing as the PR has been submitted.

Thanks :+1:
