### ISSUE TITLE
Cannot flash Sonoff Mini with fw 3.5

### ISSUE THREAD

**Issue by vdiogo** [arendst/Tasmota#8750]
Using a iMac followed these steps:
1. Set up local server (http://localhost:1313) - and put the tasmota-lite.bin file in the server root 
2. Paired Sonoff with Ewelink and updated it to the newest version (3.5)
3. Delete it from Ewelink.
4. Hold the button for 5 sec. until it starts to blink constantly and connect to the wifi with password: 12345678
5. Go to 10.10.7.1 and set up Sonoff with your local network
6. Find IP address of Sonoff (192.168.86.68).
7. Using Postman send POST Request to "http://192.168.86.68:8081/zeroconf/ota_unlock" to unlock with this JSON:
`{"deviceid":"","data":{}}`
8. Do the same with URL: "http://192.168.86.68:8081/zeroconf/ota_flash" with JSON:
```
{
"deviceid": "MY DEVICE ID",
"data": {
"downloadUrl": "http://http://localhost:1313/tasmota-lite.bin",
"sha256sum":
"7351bd4342b112326472750ad94c9551a16db313715dfc244e078f63d6d14195"
}
}
```
After #8, the device blinks three times and still has the IP previously assigned, but cannot query the FW version. After disconnecting from power, when I send POST request to "http://192.168.86.68:8081/zeroconf/info" with this JSON:
{"deviceid":"","data":{}}

I get
```
{
    "seq": 2,
    "error": 0,
    "data": {
        "switch": "off",
        "startup": "off",
        "pulse": "off",
        "pulseWidth": 500,
        "ssid": "MY SSID",
        "otaUnlock": true,
        "fwVersion": "3.5.0",
        "deviceid": "MY DEVICE ID",
        "bssid": "DEVICE BSSID",
        "signalStrength": -54
    }
}
```

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): _____
- [ x] Tasmota binary firmware version number used: _____
  - [ x] Pre-compiled
  - [ x] Self-compiled
    - [ x] IDE / Compiler used: _____
- [ x] Flashing tools used: _____
- [ x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
