### ISSUE TITLE
Restore wiki with redirects to docs

### ISSUE THREAD

**Issue by wiebel** [arendst/Tasmota#8752]
While the move of the documentation from wiki to tasmota.github.io/docs/ might be all fine and good. Out there are gazillions of valuable information linking to https://github.com/arendst/Sonoff-Tasmota/wiki/... which will all be redirected to the repo itself. It would be awesome to have either the old wiki back with an big obsolescence warning on top linking to the new docs or even better having a redirection to the new doc site matching the topic accordingly.

**Comment by ascillato** [comment]
The wiki has been moved to docs. The old wiki doesn't exist anymore and can't be reactivated. The docs is the source of all the information for Tasmota. Everything that was in the wiki is now in the docs. You should look there. Thanks.
