### ISSUE TITLE
Additional Power Monitoring settings

### ISSUE THREAD

**Issue by finch6** [arendst/Tasmota#8765]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
With regards to the Current(amps), I would like the unit to cut power for a period of about 2-3hrs if the CurrentHigh is exceeded.

**Describe alternatives you've considered**  
I considered NodeRed, but I'm trying to keep the cost of the install as cheap as possible without any additional hardware.

**Additional context**  
I have a Sonoff POW R2 setup as an AC pump/motor controller.
I have scoured the forums and docs looking for the answer, but can't find it.

Under the Tasmota Commands>Power Monitoring you can set High/Low thresholds for Voltage, Current and Power. I'm looking for a way to switch off the device/cut power to it if these parameters are exceeded and remain off for a certain period of time.

With regards to the Current(amps), I would like the unit to cut power for a period of about 2-3hrs if the CurrentHigh is exceeded. The only "window" period I saw was MaxPowerWindow which unfortunately only works with Power(watts).

Ideally, when the pump runs dry, the pump speeds up increasing the Current(amps), when the threshold is exceeded, the POW R2 cuts power to the pump for 2hrs allowing the water tank to fill up again before the power comes back on to pump more water.

If having a MaxCurrentWindow is not an option, could the MaxPowerWindow be prolonged to something greater than 5mins?

Thanks in advance 😁

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
Take a look at the Rules Cookbook for examples on controlling a device based on sensor values.

Please address further questions to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://tasmota.github.io/docs/#/Home) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
