### ISSUE TITLE
Preset module type on flash

### ISSUE THREAD

**Issue by uviniciusc** [arendst/Tasmota#8775]
Hi,
Could i set module type before the flash? 
The Module Type need to be Generic(18) and the D6 G PIO12 Relay1 to Relay1i(29).

Is it possisble?

Thank you.

**Comment by ascillato2** [comment]
Your answer to your question is on https://github.com/arendst/Tasmota/pull/8766

Just uncomment line 56 of file my_user_config.h and set there the module template you want
