### ISSUE TITLE
TuyaMCU Switch hold function

### ISSUE THREAD

**Issue by root01** [arendst/Tasmota#8824]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

Hi,

is it possible to make a 2sec hold function on a TuyaMCU Switch like this: https://templates.blakadder.com/moes-WS-EUB3-WR.html

It works well es a 3gang switch but i need a hold function with Mqtt on button 2 und 3. With the nomal rule ( https://tasmota.github.io/docs/Rules/#button-single-press-double-press-and-hold ) it doesn't work.

**Comment by digiblur** [comment]
If the buttons/switches aren't directly attached to the ESP chip then it never sees them. The only other option would be for you to rewrite the firmware in the secondary MCU to look for these long presses and send a packet over so the ESP chip.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
