### ISSUE TITLE
Supported I2C device TSL 2561 / GY-2561 (Lux Sensor)

### ISSUE THREAD

**Issue by cniweb** [arendst/Tasmota#8827]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
not related to a problem

**Describe the solution you'd like**  
I would like to be able to read the I2C device TSL 2561 / GY-2561

**Describe alternatives you've considered**  
Self programmed with Arduino Library:
https://github.com/adafruit/Adafruit_TSL2561

**Additional context**  
Datasheet:
https://cdn-shop.adafruit.com/datasheets/TSL2561.pdf

**(Please, remember to close the issue when the problem has been addressed)**
OK

Thanks,
Chris

**Comment by sfromis** [comment]
I'm already using that sensor with Tasmota, no problem. You just have to flash tasmota-sensors.bin, or build your own binary if you  have special needs.

**Comment by cniweb** [comment]
@sfromis How can I use it? Unfortunately I didn't find any documentation.

**Comment by sfromis** [comment]
There are no special steps to use it, other than the very general setup of having flashed with tasmota-sensors.bin, configuring two pins for the I2C bus (I used the pretty standard gpio4=sda and gpio5=scl, but other pins mostly work too), and wiring the sensor appropriately. The reading appears on the Tasmota front page like `TSL2561 Illuminance 13.650 lx` , and in the published MQTT messages, along any other sensors present.

**Comment by cniweb** [comment]
![Screenshot_2020-07-02 Multisensor - Configure Module](https://user-images.githubusercontent.com/2334906/86299951-d3a4bf00-bc01-11ea-87fe-6cd6aa7583f5.png)
I configured, but no Sensor output is on he Tasmota front page  :worried:

**Comment by sfromis** [comment]
If you can't get it to work with right binary, you may have to do the usual stuff to hunt down issues, like triple-checking wiring and swap parts with known good parts, like if you have another I2C sensor to test with.

Command I2CScan allows you to check what devices Tasmota sees on the I2C bus, and command I2CDriver lets you check what drivers are supported by your binary. Number 16 has to be in the list for the TSL2561 to be supported. Right after boot, Tasmota will also report what devices it found on the I2C bus, check the console. There may be some risk of conflict if you also have other I2C devices wired up.

**Comment by cniweb** [comment]
OK, I check...

Binary is tasmato-sensor.bin (Ver. 8.3.1)

**I2CScan**
```
21:13:14 CMD: I2CScan
21:13:14 MQT: stat/multisensor/RESULT = {"I2CScan":"Device(s) found at 0x39"}
```
**I2CDriver**
```
21:13:39 CMD: I2CDriver
21:13:39 MQT: stat/multisensor/RESULT = {"I2CDriver":"7"}
```
Tasmota load I2C Driver number 7:

 xnrg_07 | ADE7953 | 0x38 | Energy monitor
-- | -- | -- | --

:raised_eyebrow:

**Comment by sfromis** [comment]
You have absolutely not flashed tasmota-sensors.bin. You may have tried, but failed. Read this:
https://tasmota.github.io/docs/Upgrading

**Comment by cniweb** [comment]
OK, I flashed tasmota-sensors.bin and it works! 👍 

![Screenshot_2020-07-03 Multisensor - Main Menu](https://user-images.githubusercontent.com/2334906/86413773-6dcc3c00-bcc2-11ea-9e90-77615aa68ba9.png)

Thanks

**Comment by TheBurgundyBear** [comment]
> I2CDriver

@sfromis, I'm having a similar issue as @cniweb. I2CDriver outputs:

`{"I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48"}`

How do I get 16??

**Comment by sfromis** [comment]
In the long time since then, the precompiled setup for [builds](https://github.com/arendst/Tasmota/blob/development/BUILDS.md) has changed to no longer have TSL2561 included in tasmota-sensors. To use the sensor with current Tasmota, you'll have to [compile](https://tasmota.github.io/docs/Compile-your-build/) your own binary adding `#define USE_TSL2561` to the base "tasmota" build environment, do not try to add to tasmota-sensors.
