### ISSUE TITLE
newer sonoff S31 device not working

### ISSUE THREAD

**Issue by tarasglek** [arendst/Tasmota#8835]
### PROBLEM DESCRIPTION
I bought 3 sonoff s31 devices from banggood within last 2 months, flashed them with 8.3.1, they report 0s for power.
I have an older s31 working great with 8.1.0, downgrading new S31 to 8.1.0 resulted in no change on behavior on new device :(

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff S31
- [x] Tasmota binary firmware version number used: 8.3.1
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: esptool
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
19:45:47 RSL: stat/tasmota_1B3169/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"145":"CSE7766 Tx"},"GPIO2":{"0":"None"},"GPIO3":{"146":"CSE7766 Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
19:47:01 RSL: stat/tasmota_1B3169/STATUS = {"Status":{"Module":41,"FriendlyName":["Tasmota"],"Topic":"tasmota_1B3169","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"tasmotas","OtaUrl":"http://192.168.1.226:8000/tasmota-8.1.0.bin","RestartReason":"Software/System restart","Uptime":"0T00:17:35","StartupUTC":"2020-07-01T18:29:26","Sleep":50,"CfgHolder":4617,"BootCount":7,"SaveCount":27,"SaveAddress":"F8000"}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019-12-25T12:33:25","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"317/699"}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":4,"LogHost":"192.168.1.226","LogPort":514,"SSId":["leader",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100068000005A00000000000000","00000000","00000000"]}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS4 = {"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS5 = {"StatusNET":{"Hostname":"Sonoff-s31","IPAddress":"192.168.1.44","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"CC:50:E3:1B:31:69","Webserver":2,"WifiConfig":4}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1B3169","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS7 = {"StatusTIM":{"UTC":"Wed Jul 01 18:47:01 2020","Local":"Wed Jul 01 19:47:01 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"04:51","Sunset":"20:57"}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS10 = {"StatusSNS":{"Time":"2020-07-01T19:47:01","ENERGY":{"TotalStartTime":"2020-07-01T18:22:37","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
19:47:01 RSL: stat/tasmota_1B3169/STATUS11 = {"StatusSTS":{"Time":"2020-07-01T19:47:01","Uptime":"0T00:17:35","UptimeSec":1055,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"leader","BSSId":"AC:84:C6:B2:B6:A0","Channel":2,"RSSI":62,"Signal":-69,"LinkCount":1,"Downtime":"0T00:00:08"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:

Jul  1 11:48:22 Sonoff-s31 ESP-SRC: WebConsole from 192.168.1.226
Jul  1 11:48:22 Sonoff-s31 ESP-CMD: Group 0, Index 1, Command "WEBLOG", Data "4"
Jul  1 11:48:22 Sonoff-s31 ESP-RSL: stat/tasmota_1B3169/RESULT = {"WebLog":4}
Jul  1 11:48:22 Sonoff-s31 ESP-CFG: Saved to flash at F7, Count 28, Bytes 4096
Jul  1 11:48:38 Sonoff-s31 ESP-WIF: Checking connection...
Jul  1 11:48:38 Sonoff-s31 ESP-WIF: Connected
```

### TO REPRODUCE
flip device on/off/reboot, still 0s for power usage

### EXPECTED BEHAVIOUR
showing power usage on homepage

### SCREENSHOTS
This problem doesn't happen on old device, which seems to have different hw?

old device:
![image](https://user-images.githubusercontent.com/857083/86280644-06fb3580-bb91-11ea-8f83-75bd97566f71.png)

new device:
![image](https://user-images.githubusercontent.com/857083/86280601-f480fc00-bb90-11ea-939e-b918ad248999.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
https://github.com/arendst/Tasmota/issues/8834#issuecomment-652584948
