### ISSUE TITLE
Support a curl request for tasmotized buttons

### ISSUE THREAD

**Issue by SkyBird1980** [arendst/Tasmota#8851]
**Have you looked for this feature in other issues and in the docs?**  
Sure i have :)

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
i want to use a tasmotized button to request a url. e.g. power on on another tazmotized device (plug, whatever) without using MQTT.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
a customized web request url for every button, maybe via console. better via webui.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
using mqtt would fullfill my request. but i don't want to have an extra device for mqtt server in my home lan

**Additional context**  
_Add any other context or screenshots about the feature request here._
- nothing --
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi, 

Your request is already supported. Please check command websend and rules' events. With that you can make any http request you want. 

Also, you can search in old issues. 

Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
