### ISSUE TITLE
Disable connection between switch and relay if script function is defined.

### ISSUE THREAD

**Issue by kugelkopf123** [arendst/Tasmota#8925]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
Yes!
I use a sonoff 4ch with a self compiled Tasmota FW. Need the script function on the sonoff to read a counter. I also use this Sonoff for my garden lamps. There is an "emergency button" connected via GND and IO2. GPIO2 is defined as switch5 in the device settings. I want to use the emergency button to switch all lamps on/off. Very annoying is that switch5 always automatically switches Relay1. With switch1-4 I can still understand this to some extent. But not with Switch5. According to Docs there seems to be no way to disable this function when using the script. 
According to Docs the function would be deactivated at Rules, if you would assign a function to Switch5 in a rule. At least that's how I understand the documentation.
Anyway. It makes no sense for me to have a choice of 8 switches, which all always control relay 1. 

**Describe the solution you'd like**  
A set option to disable the linking of Switch with Relay. Or all switches via Switch4 without a link to the relays.

**Describe alternatives you've considered**  
Already mentioned.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**Comment by arendst** [comment]
Or use rules.

Kindly ask Gemu to fix his scripter.

**Comment by kugelkopf123** [comment]
@arendst Thanks for your answer.
As already mentioned, rules is not an option. 
Is there an explanation why all switches are connected to relay1? None that I can see at the moment.
Connecting switch 1-4 to relay 1-4 would still make sense to me. But 5-8 would not. 

Mention @gemu2015 to get him on board.

**Comment by arendst** [comment]
It's all about automagic. Switch 5 can only be connected to relay1 as it overflows the max amount of obvious relays. Same for all other switches.

Why on earth would one want to connect additional switches to an already overcrowded CH4 except @kugelkopf123

**Comment by kugelkopf123** [comment]
> It's all about automagic. Switch 5 can only be connected to relay1 as it overflows the max amount of obvious relays. Same for all other switches.
> 
> Why on earth would one want to connect additional switches to an already overcrowded CH4 except @kugelkopf123

I'm not sure if you got me right. I have a feeling you're taking this a little too personally. 
I do not want switch5 to be connected to relay1 or any other relay. I want to be able to determine for myself what switch5 does. 
The sonoff 4ch is installed in a power sub-distribution unit and is not easily accessible. Well, I can explain to you why @kugelkopf123 ;) has installed another switch on this unit: So that my parents don't break their legs if the RaspberryPi hangs up again and doesn't turn on the light when they open the garden door, there is a standard light switch which, as mentioned above, is connected to the GPIO2 of the 4CH and turns on the garden lights. =)
Obviously there seems to be a kind of "switch" that "disconnects" the connection when using Rules. So it should be possible to use a set option or even a #define to break the connection. 
That's all I kindly ask for.

**Comment by meingraham** [comment]
@kugelkopf123 

Is `SetOption73` an option?

**Comment by kugelkopf123** [comment]
> @kugelkopf123
> 
> Is `SetOption73` an option?

I'm not shure if I had tried this. Perhaps not, because its mentioned in the docs for Buttons not for Switches. I can try again when I get home.
