### ISSUE TITLE
I2C polling rate

### ISSUE THREAD

**Issue by tnkaiser** [arendst/Tasmota#8953]
### PROBLEM DESCRIPTION
MPU6050 on I2C bus seems to be polled every second or so, useless for an MPU.  I need to find where to change the driver to allow it to poll the MPU6050 every 50msec or so.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ x] Device used (e.g., Sonoff Basic): WemosD1Mini
- [x] Tasmota binary firmware version number used: 8.3.1.7
  - [ ] Pre-compiled
  - [x ] Self-compiled
    - [x ] IDE / Compiler used: PlatformIO
- [x ] Flashing tools used: PlatformIO
- [ x] Provide the output of command: `Backlog Template; Module; GPIO 255`:

15:53:10 CMD: Backlog Template; Module; GPIO 255
15:53:10 MQT: stat/Rack1Accel/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
15:53:10 MQT: stat/Rack1Accel/RESULT = {"Module":{"0":"Generic"}}
15:53:10 MQT: stat/Rack1Accel/RESULT = {"GPIO0":{"6":"I2C SDA"},"GPIO1":{"0":"None"},"GPIO2":{"5":"I2C SCL"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
N/A

```
- [ ] Provide the output of this command: `Status 0`:
```
15:53:53 CMD: status 0
15:53:53 MQT: stat/Rack1Accel/STATUS = {"Status":{"Module":0,"DeviceName":"Rack1Accel","FriendlyName":["Rack1Accel"],"Topic":"Rack1Accel","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
15:53:53 MQT: stat/Rack1Accel/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:22:18","StartupUTC":"2020-07-21T14:31:35","Sleep":50,"CfgHolder":4617,"BootCount":38,"BCResetTime":"2020-07-19T23:20:27","SaveCount":75,"SaveAddress":"F7000"}}
15:53:53 MQT: stat/Rack1Accel/STATUS2 = {"StatusFWR":{"Version":"8.3.1.7(tasmota)","BuildDateTime":"2020-07-21T09:28:48","Boot":31,"Core":"2_7_2_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"403/699"}}
15:53:53 MQT: stat/Rack1Accel/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["OklaHomeA","OklaHomeA"],"TelePeriod":300,"Resolution":"5581C0C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000400","00006000"]}}
15:53:53 MQT: stat/Rack1Accel/STATUS4 = {"StatusMEM":{"ProgramSize":570,"Free":432,"Heap":23,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0FDAE796","04368001","000000C1","00000008","C000F981","00000004"],"Drivers":"1,2,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,4,5,6,32"}}
15:53:53 MQT: stat/Rack1Accel/STATUS5 = {"StatusNET":{"Hostname":"Rack1Accel-7554","IPAddress":"192.168.0.76","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"F4:CF:A2:D0:9D:82","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
15:53:53 MQT: stat/Rack1Accel/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.17","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D09D82","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
15:53:53 MQT: stat/Rack1Accel/STATUS7 = {"StatusTIM":{"UTC":"2020-07-21T14:53:53","Local":"2020-07-21T15:53:53","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"05:10","Sunset":"20:42"}}
15:53:53 MQT: stat/Rack1Accel/RESULT = {"AccelXAxis":3768.00,"AccelYAxis":1176.00,"AccelZAxis":16344.00}
15:53:53 MQT: stat/Rack1Accel/STATUS10 = {"AccelXAxis":3768.00,"AccelYAxis":1176.00,"AccelZAxis":16344.00},"MPU6050":{"Temperature":26.5,"AccelXAxis":3768.00,"AccelYAxis":1176.00,"AccelZAxis":16344.00,"GyroXAxis":-924.00,"GyroYAxis":-512.00,"GyroZAxis":-1445.00},"TempUnit":"C"}}
15:53:53 MQT: stat/Rack1Accel/STATUS11 = {"StatusSTS":{"Time":"2020-07-21T15:53:53","Uptime":"0T00:22:18","UptimeSec":1338,"Heap":23,"SleepMode":"Normal","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"OklaHomeA","BSSId":"1A:E8:29:14:2F:62","Channel":1,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:04"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
15:55:02 CMD: weblog 4
15:55:02 MQT: stat/Rack1Accel/RESULT = {"WebLog":4}
15:55:03 CFG: Saved to flash at F6, Count 76, Bytes 4096

```

### TO REPRODUCE
Connect MPU6050, watch WebUI for update


### EXPECTED BEHAVIOUR
Faster I2C (MPU6050 in particular) polling rate.


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._


### ADDITIONAL CONTEXT
changing FUNC_EVERY_SECOND to FUNC_EVERY_50_MSECOND in the driver (xsns_32_MPU6050.ino) does not fix the problem.


**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
It does fix the probe but it doesn't fix the web display.

Faster GUI updates can be obtained by changing ``WebRefresh`` but currently it only allows values a s low as 1000m Sec.

If you want lower values you need to change line 3300 in webserver.ino

No guarantees though as I did fix it to 1000 for a reason you are bound to explore...

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
