### ISSUE TITLE
need some help with Rules

### ISSUE THREAD

**Issue by 66schoollane** [arendst/Tasmota#8959]
hi internet,
could someone help with this problem i have with making a rule, I've a shelly that the relay needs to be on when 2nice plug has watts or amps under load.

Workings of the shelly
Firmware 1.70
Configured Shelly device to create WiFi Access Point and you can connect to its network. IP 192.168.33.1
Using the relay to power a vacuum cleaner

Workings of the 2nice UP111 Power Monitoring Plug,
Running Tasmota 8.3.1 Fred
connected to Shelly network
Operating a relay of a power tool.

Rule 1
  ON ENERGY#Current>0.025 DO http://192.168.33.1/relay/0?turn=toggle ENDON
  ON ENERGY#Current<0.025 DO http://192.168.33.1/relay/0?turn=toggle ENDON

im sure its my coding that needs correcting, 

thanks,

**Comment by ascillato** [comment]
Check websend command. 

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
