### ISSUE TITLE
Ailight bulb (Base 27) not working with 8.3.1

### ISSUE THREAD

**Issue by GeorgHohenberger** [arendst/Tasmota#8982]
After updating from 7.1.x to 8.3.1 my Avatar candle bulb is no longer working. It is not showing the sliders and buttons (as other bulbs do). nor it is accepting comands via console or mqtt.

I am using the official tasmota-lite8.3.1.bin image.

The template is {"base": 27, "flag": {"adc0": 0}, "gpio": [0, 0, 0, 0, 0, 0, 0, 0, 0, 143, 0, 144, 0], "name": "AVATAR"}

**Comment by ascillato** [comment]
Please, use the full version **_tasmota.bin_**

Thanks.
