### ISSUE TITLE
SetOption57 unstable after upgrade from 8.3.1 to 8.4.0

### ISSUE THREAD

**Issue by JoeSydney** [arendst/Tasmota#9006]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
After upgrading from 8.3.1 to 8.4.0, SetOption57 seems to be unstable in that after ALMOST EVERY 44 or 88 minutes (approx), the AP is switched, LWT shows off and on.

I have 2 APs with the same SSID.

This only happens on 2 devices (ceiling lights) that are on the "border" of the two APs.

As a work-around, I have had to disable SetOption57. 

No such issues were encountered in 8.3.1 and before. Also tried 8.4.0.1 and that also had the problem. In fact, the light did not connect back, and I had to power cycle it.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Verve Hana oyster lights
- [X] Tasmota binary firmware version number used: 8.4.0
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
1. Turn on Setoption57 on a device that is in the border of 2 APs with the same SSID

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
2. Switching to alternate AP to occur very infrequently (as experienced in previous release) when signal difference is more than 10dB

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Self answering

> This only happens on 2 devices (ceiling lights) that are on the "border" of the two APs.

the difference in "border" connections can easily be more than 10dB. As newer versions of Tasmota also tend to use more energy weak wifi even becomes more visible.

It's not that setoption57 is unstable; it's your wifi environment that is unstable and tasmota tries to correct it as much as possible.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
