### ISSUE TITLE
Improve UI for devices with multiple switches 

### ISSUE THREAD

**Issue by aschoelzhorn** [arendst/Tasmota#9015]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
It is only a usability problem.
I have more devices with have more switches like the Sonoff T1 2CH Module or the Gosund Wifi Smart Socket P1.
On the landing page of the device I see all a toggle for all switches named "Toggle 1", "Toggle 2", ... 
It would help the have better names for them, so that you know what for which switch the toggle is. 
See attached screenshots.
![GosundP1](https://user-images.githubusercontent.com/1025417/89128700-d859dd00-d4f7-11ea-83ca-9fedddfb5e2f.png)
![gosund_p1_settings](https://user-images.githubusercontent.com/1025417/89128703-dc85fa80-d4f7-11ea-94d8-f8efa0debc82.png)

**Describe the solution you'd like**  
Use the friendly names for the toggles

**Describe alternatives you've considered**  
Use the friendly name as mouse over hint.

**Additional context**  

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
https://tasmota.github.io/docs/Commands/#webbutton
