### ISSUE TITLE
MQTT - Send new value instantly after measure cycle, instead of periodically

### ISSUE THREAD

**Issue by Winteriver** [arendst/Tasmota#9017]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
Related to the problem: 
MQTT teleperiod cannot be set to less than 10
https://github.com/arendst/Tasmota/issues/527

Like mentioned above - the teleperiod cannot be set to less than 10. 
In Time critical applications this can be a real problem. An example:
The amount of fluid flowing per second is measured by a device runnung Tasmota and it sends the current value every 10 seconds with MQTT to - in my case - ioBroker. 
Another Tasmota Device with a connected Relais on a fluid valve should close when a specific amount of fluid is reached.
Now, when we have 100 ml/sec within these 10 seconds there runs 1L of fluid through the system, so - in worst case - I have 1L more fluid that I wanted to have.

**Describe the solution you'd like**  
I can understand, that you cannot make the teleperiod smaller that 10 seconds, like @arendst said [here](https://github.com/arendst/Tasmota/issues/527):
"(...) a complete measure cycle (Power, Current and Voltage) can take up to four seconds with very low loads."

My idea for a possible Solution would be to make an option in the menu to enable or disable the possibility to send the new value always with MQTT after a measure cycle is completed.
It would be great, if you could also make a limit like: "Period between messages should be at least: X seconds", so the MQTT Broker won't be flooded if the measure cycle is too fast.

As the devices are getting faster it would be even better, if you could set the "Period between messages should be at least: X seconds" from the Broker, because when I have fluid running I could make it to a low number to get fast values and after the process is finished I could it even disable it or set it to a very high number like 3600 seconds, because I dont need the value right now. This ways it saves energy and network bandwith.

This way time critical applications have a chance to be realised with Tasmota without much effort.

**Describe alternatives you've considered**  
I could measure how much fluid flowed through the system in the last 10 seconds and could calculate when my limit should be reached. But this needs a custom solution for every time critical application and does not always work.
For example, you cannot calculate if a door will be opened within the next 10 seconds.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

A teleperiod is a telemetry message (is a status message) and is not intended for your stated use case.

What you need is to use **_rules_** to check how much fluid have flown. Those are checked by default every 200msec, but you can lower that time with `SetOption34`

Please, check the docs for rules and check the rules cookbook for examples.

If you need further assistance with this, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by nord3214** [comment]
@Winteriver 
I had the same issue or atleast i wanted to determine the time when the info gets send. I have found out that if you just use the command:

`teleperiod now` 

instead of a number behind it sends the data instantly. I am Using io Broker and on my dashboard it just works fine.
Hope that helps.

**Comment by abc2006** [comment]
@nord3214 in which version does this work? I always get the answer 
19:45:59.581 MQT: stat/tasmota_56F37A/RESULT = {"TelePeriod":10}

But i will check for rules, too. thx

**Comment by sfromis** [comment]
Well, just issuing the TelePeriod command (even with an invalid useless argument like `now`) will result in the current TelePeriod value being printed, **and** the TelePeriod messages being published to MQTT (which should very much be visible in the console).

**Comment by abc2006** [comment]
Hi, thank you for this quick answer. As i am not that used to Tasmota yet, i am looking forward to decrease the MQTT-Update-Period of my power-meter-reader to 2, max 3 Seconds. Which solution do you recommend, if TelePeriod is *not* the right way to do that? Should i actually do this with rules?

**Comment by sfromis** [comment]
When it is energy monitoring, do not try getting more granular data by a low reporting interval, use [PowerDelta](https://tasmota.github.io/docs/Commands/#powerdelta) instead. This feature is for generating extra reporting when the consumption level changes, which works well for most devices. As a starting point, I like something like `PowerDelta 110` to get reporting when 10W up/down, but that obviously depends on what you are monitoring.
