### ISSUE TITLE
ESp32-WRoom-32 dont work

### ISSUE THREAD

**Issue by christianwis** [arendst/Tasmota#9065]
Hello friends,

I can't get the binaries published in tasmota ESP32 to work on an ESP32-WROOM-32 device.

I transferred the binaries according to the readme, but it doesn't work.

0x1000 bootloader_dout_40m.bin

 

0x8000 partitions.bin

 

0xe000 boot_app0.bin

 

0x10000 tasmota32.bin

could it be solved?

thank you
Christian

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
