### ISSUE TITLE
WindMeter (Sensor68) for ESP32

### ISSUE THREAD

**Issue by Ingenieur89** [arendst/Tasmota#9068]
**Have you looked for this feature in other issues and in the docs?**  
Yes.

**Is your feature request related to a problem? Please describe.**  
The WindMeter peripheral (Sensor68) is currently not working for ESP32. I cannot choose the Windmeter Spd GPIO.

**Describe the solution you'd like**  
Working WindMeter for ESP32. It is working very nice on ESP8266.

**Describe alternatives you've considered**  
-

**Additional context**  
-

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Without enabling define USE_WINDMETER you won't see the GPIO (on either ESP8266 or ESP32). So pls check if you enabled this define for ESP32 as it is default not defined in ``my_user_config.h``.

**Comment by ionultd** [comment]
I have just build Tasmota32 9.3.1 for sensors and have #define USE_WINDMETER in my user_config_override.h. When entering in the console Sensor68 parameter settings I gat an error as in [Image1](https://i.imgur.com/akbDyGM.png)
