### ISSUE TITLE
SM2135E not working with Tuya TYLC5 (esp8285)

### ISSUE THREAD

**Issue by CrudelisPL** [arendst/Tasmota#9073]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I can't control light bulb with sm2135e chip, I tried many configurations and asked help on discord, I am sure that I am doing everything right. There is Tuya TYLC5 module inside with esp8285 connected directly to sm2135e chip, there are also two pull ups on GPIO12 and GPIO14.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Polux G45, 5,5W, 470lm, E14
- [x] Tasmota binary firmware version number used:8.4
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: Tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:

13:34:38 RSL: STATE = {"Time":"2020-08-11T13:34:38","Uptime":"0T00:25:31","UptimeSec":1531,"Heap":26,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":100,"Color":"00000047B8","HSBColor":"249,100,0","White":100,"CT":404,"Channel":[0,0,0,28,72],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"DOM","BSSId":"30:5A:3A:6E:15:B8","Channel":6,"RSSI":100,"Signal":-40,"LinkCount":1,"Downtime":"0T00:00:03"}}
13:34:38 CMD: Backlog Template; Module; GPIO 255
13:34:38 SRC: WebConsole from 192.168.1.200
13:34:38 CMD: Group 0, Index 1, Command "BACKLOG", Data "Template; Module; GPIO 255"
13:34:38 SRC: Backlog
13:34:38 CMD: Group 0, Index 1, Command "TEMPLATE", Data ""
13:34:38 RSL: RESULT = {"NAME":"A65 SMDWWCW+RG","GPIO":[0,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}
13:34:39 SRC: Backlog
13:34:39 CMD: Group 0, Index 1, Command "MODULE", Data ""
13:34:39 RSL: RESULT = {"Module":{"0":"A65 SMDWWCW+RG"}}
13:34:39 SRC: Backlog
13:34:39 CMD: Group 0, Index 1, Command "GPIO", Data "255"
13:34:39 RSL: RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"181":"SM2135 Dat"},"GPIO13":{"0":"None"},"GPIO14":{"180":"SM2135 Clk"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:

```
13:30:45 CMD: Group 0, Index 1, Command "STATUS", Data "0"
13:30:45 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_2F696C","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
13:30:45 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Power On","Uptime":"0T00:21:38","StartupUTC":"2020-08-11T12:09:07","Sleep":50,"CfgHolder":4617,"BootCount":25,"BCResetTime":"2020-08-10T19:21:12","SaveCount":323,"SaveAddress":"FB000"}}
13:30:45 RSL: STATUS2 = {"StatusFWR":{"Version":"8.4.0(tasmota)","BuildDateTime":"2020-07-29T12:05:28","Boot":31,"Core":"2_7_2_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"380/699"}}
13:30:45 RSL: STATUS3 = {"StatusLOG":{"SerialLog":4,"WebLog":4,"MqttLog":0,"SysLog":4,"LogHost":"","LogPort":514,"SSId":["DOM",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008001","2805C8000100060000005A00000000000000","00000000","00006000"]}}
13:30:45 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":592,"Free":408,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
13:30:45 RSL: STATUS5 = {"StatusNET":{"Hostname":"RGB LED BULB 001","IPAddress":"192.168.1.253","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"24:62:AB:2F:69:6C","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
13:30:45 RSL: STATUS7 = {"StatusTIM":{"UTC":"2020-08-11T12:30:45","Local":"2020-08-11T13:30:45","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"05:38","Sunset":"20:12"}}
13:30:45 RSL: STATUS10 = {"StatusSNS":{"Time":"2020-08-11T13:30:45"}}
13:30:45 RSL: STATUS11 = {"StatusSTS":{"Time":"2020-08-11T13:30:45","Uptime":"0T00:21:38","UptimeSec":1298,"Heap":26,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":100,"Color":"00000047B8","HSBColor":"249,100,0","White":100,"CT":404,"Channel":[0,0,0,28,72],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"DOM","BSSId":"30:5A:3A:6E:15:B8","Channel":6,"RSSI":100,"Signal":-40,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```

- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_

I tried to find chip with I2CScan.
```
  Console output here:
RESULT = {"I2CScan":"Device(s) found at 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0a 0x0b 0x0c 0x0d 0x0e 0x0f 0x10 0x11 0x12 0x13 0x14 0x15 0x16 0x17 0x18 0x19 0x1a 0x1b 0x1c 0x1d 0x1e 0x1f 0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27 0x28 0x29 0x2a 0x2b 0x2c 0x2d 0x2e 0x2f 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x3a 0x3b 0x3c 0x3d 0x3e 0x3f 0x40 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4a 0x4b 0x4c 0x4d 0x4e 0x4f 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5a 0x5b 0x5c 0x5d 0x5e 0x5f 0x60 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 0x6a 0x6b 0x6c 0x6d 0x6e 0x6f 0x70 0x71 0x72 0x73 0x74 0x75 0x76 0x77 0x78 0x79 0x7a 0x7b 0x7c 0x7d 0x7e 0x7f"}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Flash with tuya-convert
2. Make a config with SM2135

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Control bulb with: SDA and SCL

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
[Reported](https://discord.com/channels/479389167382691863/479389167382691865/743253735697809452) as operational with a reworked [driver](https://cdn.discordapp.com/attachments/479389167382691865/743262157348536360/xlgt_04_sm2135.ino).

**Comment by arendst** [comment]
Well the "NEW" code doesn't work for the "old" LSC bulb as the colors are different; LSC is GRB and Polux is BGR. The timing seems fine but I hate the interrupt toggles. Need further investigation.

**Comment by arendst** [comment]
The latest commit contains most of @CrudelisPL code saused with Tasmota adjustements. The new code works fine with my LSC bulb but I couldn't test the Polux one.

Notice in order to use the Polux bulb you'll need a change in the template. The correct templates now are:
```
 * Action LSC SmartLed (GreenRedBlue)
 * {"NAME":"LSC RGBCW LED","GPIO":[0,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}
 * Polux E14 (BlueGreenRed) - Notice GPIO00 = 9 (Switch1)
 * {"NAME":"Polux RGBCW E14","GPIO":[9,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}
```
where the LSC template is unchanged but the Polux adds a ``switch1`` on GPIO0 just for detecting the needed RGB sequence change. The switch won't pop up in any status or state message as it is discarded as soon as the driver is initialized. Another Tasmota quirk which I like.

**Comment by Ganbit666** [comment]
I also have "Polux G45 5.5W 470lm E14" and I can't make it work either.
I tried
"{" NAME ":" Polux RGBCW E14 "," GPIO ": [9,0,0,0,0,0,0,0,181,0,180,0,0]," FLAG ": 0," BASE ": 18} "
And it still doesn't work. I opened it and they all match up. It looks as if SM2135E is not receiving a signal from ESP8285.
I also changed mapping RGBWcWw to B, G, R, Ww, Wc - "SetOption37 55"

Please help

**Comment by CrudelisPL** [comment]
I will compile later. But try this one:
[https://github.com/CrudelisPL/Tasmota](url)

**Comment by sfromis** [comment]
The great update from CrudelisPL is already included in the precompiled binary from http://thehackbox.org/tasmota/

**Comment by Ganbit666** [comment]
Thank you 
  Dnia 16 sierpnia 2020 18:02 sfromis   napisał(a):  
 The great update from CrudelisPL is already included in the precompiled binary from  zasobygwp.pl thehackbox.org

**Comment by Ganbit666** [comment]
Thank you 
  Dnia 16 sierpnia 2020 15:44 CrudelisPL   napisał(a):  
 I will compile later. But try this one:  
 github.com
