### ISSUE TITLE
why Rule command2,3 .. have no run, only run command1 !

### ISSUE THREAD

**Issue by wymanhns** [arendst/Tasmota#9092]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
22:31:32 CMD: Rule1 ON Power1#state=0 DO rule1 0;power1 1;var1 0 ENDON
22:31:32 RUL: Stored uncompressed, would compress from 50 to 46 (-8%)
22:31:32 MQT: stat/tasmota_0219D8/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":50,"Free":461,"Rules":"ON Power1#state=0 DO rule1 0;power1 1;var1 0 ENDON"}
22:31:50 CMD: Rule1 ON
22:31:50 MQT: stat/tasmota_0219D8/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":50,"Free":461,"Rules":"ON Power1#state=0 DO rule1 0;power1 1;var1 0 ENDON"}
22:31:53 MQT: tele/tasmota_0219D8/STATE = {"Time":"2020-08-14T22:31:53","Uptime":"0T00:05:12","UptimeSec":312,"Heap":6,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":36,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":2,"SSId":"Rm2713_2.4","BSSId":"C4:68:D0:59:7D:CA","Channel":7,"RSSI":34,"Signal":-83,"LinkCount":1,"Downtime":"0T00:00:06"}}
22:31:53 MQT: tele/tasmota_0219D8/SENSOR = {"Time":"2020-08-14T22:31:53","Switch1":"OFF","VL53L0X":{"Distance":9999}}
22:31:55 MQT: stat/tasmota_0219D8/RESULT = {"POWER":"ON"}
22:31:55 MQT: stat/tasmota_0219D8/POWER = ON
22:32:11 MQT: stat/tasmota_0219D8/RESULT = {"POWER":"OFF"}
22:32:11 MQT: stat/tasmota_0219D8/POWER = OFF
22:32:12 RUL: POWER1#STATE=0 performs "rule1 0;power1 1;var1 0"
22:32:12 MQT: stat/tasmota_0219D8/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":50,"Free":461,"Rules":"ON Power1#state=0 DO rule1 0;power1 1;var1 0 ENDON"}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Your syntax is wrong. You have to use `Backlog` 
You find examples how to use in examples for using rules

**Comment by wymanhns** [comment]
Thx use BackLog Oknow

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
