### ISSUE TITLE
more FEIT BPA800/RGBW/AG/2(P) Template issues

### ISSUE THREAD

**Issue by mrneutron42** [arendst/Tasmota#9179]
### PROBLEM DESCRIPTION
I just got 10 of the Feit RGBW A19 bulbs with model number BPA800/RGBW/AG/2P (FCC ID SYW-A19RGBWAG2) and I've loaded the latest pre-compiled Tasmota firmware version:  8.4.0.
I see there have been problems with these Feit template files in the past year:  https://github.com/arendst/Tasmota/issues/6534

The current posted template for these Feit BPA800/RGBW/AG/2P bulbs does not allow control of color - NO color sliders appear in the Tasmota Main web server page, only the CoolWhite-WarmWhite and Intensity sliders.
{"NAME":"BPA800/RGBW/AG/2P","GPIO":[0,0,0,0,37,38,0,0,141,142,140,0,0],"FLAG":0,"BASE":48}
from https://templates.blakadder.com/feit_electric-BPA800RGBWAG2P.html

The Tasmota Component choices 140, 141, & 142 do not appear in the pull-down menu choices for the GPIOs in the Tasmota Configure Template window.  As a result, GPIO boxes 12, 13 and 14 are empty.  
According to the template page, GPIO boxes 12, 13, 14 are the SM16716 LED driver chip's i2c Data, Power, and i2c Clock pins.

The end goal is to get color control of the Feit BPA800/RGBW/AD/2P bulbs.
Can Tasmota Component choices 140, 141, & 142 be added to the GUI pull-down choices so they can be selected in the Configure Template GUI? 
![IMG_20200826_231651](https://user-images.githubusercontent.com/70338169/91505105-6aa19680-e894-11ea-8298-e50221979d32.jpg)
![Tasmota Main Menu Feit RGBW](https://user-images.githubusercontent.com/70338169/91637876-2536b380-e9d1-11ea-814c-00449314ae31.JPG)
![Tasmota Configure Template empty boxes Feit RGBW](https://user-images.githubusercontent.com/70338169/91637909-4eefda80-e9d1-11ea-9065-69a687a3ca63.JPG)
![Tasmota Configure Template Feit RGBW](https://user-images.githubusercontent.com/70338169/91637847-f8829c00-e9d0-11ea-8d88-8b1a2eb0cf0f.JPG)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Xiaomi Philips
- [x] Tasmota binary firmware version number used: 8.4.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used:  tuya-convert
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
00:00:34 CMD: Backlog Template; Module; GPIO 255
00:00:34 RSL: stat/tasmota/RESULT = {"NAME":"BPA800/RGBW/AG/2P","GPIO":[0,0,0,0,37,38,0,0,141,142,140,0,0],"FLAG":0,"BASE":48}
00:00:34 RSL: stat/tasmota/RESULT = {"Module":{"0":"BPA800/RGBW/AG/2P"}}
00:00:35 RSL: stat/tasmota/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"37":"PWM1"},"GPIO5":{"38":"PWM2"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"141":"SM16716 DAT"},"GPIO13":{"142":"SM16716 PWR"},"GPIO14":{"140":"SM16716 CLK"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
04:20:58 CMD: Status 0
04:20:58 RSL: stat/tasmota/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
04:20:58 RSL: stat/tasmota/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:04:47","StartupUTC":"2020-08-28T03:16:11","Sleep":50,"CfgHolder":4617,"BootCount":29,"BCResetTime":"2020-08-27T16:58:14","SaveCount":325,"SaveAddress":"F5000"}}
04:20:58 RSL: stat/tasmota/STATUS2 = {"StatusFWR":{"Version":"8.4.0(lite)","BuildDateTime":"2020-07-29T12:06:18","Boot":31,"Core":"2_7_2_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"373/699"}}
04:20:58 RSL: stat/tasmota/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["homeland",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000"]}}
04:20:58 RSL: stat/tasmota/STATUS4 = {"StatusMEM":{"ProgramSize":473,"Free":528,"Heap":29,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F000783","04108001","00000006","010001C0","00000000","00004004"],"Drivers":"1,2,3,4,9,10,16,20,21,37","Sensors":"3"}}
04:20:58 RSL: stat/tasmota/STATUS5 = {"StatusNET":{"Hostname":"tasmota-5763","IPAddress":"192.168.7.213","Gateway":"192.168.7.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.7.1","Mac":"C4:4F:33:B2:56:83","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
04:20:58 RSL: stat/tasmota/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_B25683","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
04:20:58 RSL: stat/tasmota/STATUS7 = {"StatusTIM":{"UTC":"2020-08-28T03:20:58","Local":"2020-08-28T04:20:58","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:02","Sunset":"19:40"}}
04:20:58 RSL: stat/tasmota/STATUS10 = {"StatusSNS":{"Time":"2020-08-28T04:20:58"}}
04:20:58 RSL: stat/tasmota/STATUS11 = {"StatusSTS":{"Time":"2020-08-28T04:20:58","Uptime":"0T00:04:47","UptimeSec":287,"Vcc":3.435,"Heap":29,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":24,"Color":"2E0F","White":24,"CT":236,"Channel":[18,6],"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"homeland","BSSId":"A4:13:4E:8B:8B:E1","Channel":2,"RSSI":88,"Signal":-56,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
13:43:40 CMD: weblog 4
13:43:40 RSL: stat/tasmota/RESULT = {"WebLog":4}
13:43:40 CFG: Saved to flash at F7, Count 339, Bytes 4096
13:43:45 WIF: Checking connection...
13:44:05 WIF: Checking connection...
13:44:25 WIF: Checking connection...
13:44:45 WIF: Checking connection...
13:45:01 APP: Serial logging disabled
13:45:05 WIF: Checking connection...
13:45:11 RSL: tele/tasmota/STATE = {"Time":"2020-08-28T13:45:11","Uptime":"0T00:10:10","UptimeSec":610,"Vcc":3.434,"Heap":29,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":0,"POWER":"ON","Dimmer":16,"Color":"1514","White":16,"CT":326,"Channel":[8,8],"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"homeland","BSSId":"A4:13:4E:8B:8B:E1","Channel":2,"RSSI":66,"Signal":-67,"LinkCount":1,"Downtime":"0T00:00:04"}}
13:45:25 WIF: Checking connection...
13:45:45 WIF: Checking connection...
13:46:05 WIF: Checking connection...
13:46:25 WIF: Checking connection...
13:46:45 WIF: Checking connection...
13:47:05 WIF: Checking connection...
13:47:25 WIF: Checking connection...
13:47:45 WIF: Checking connection...
13:48:05 WIF: Checking connection...
13:48:25 WIF: Checking connection...
13:48:45 WIF: Checking connection...
13:49:05 WIF: Checking connection...
13:49:25 WIF: Checking connection...

  Console output here:

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Turn on.  Log into Tasmota web interface.  Try to configure template.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._


### ADDITIONAL CONTEXT
_Add any other context about the problem here._


**(Please, remember to close the issue when the problem has been addressed)**

**Comment by JaimeZX** [comment]
Try doing the upgrade. I'm running 8.4.0 and
{"NAME":"","GPIO":[0,0,0,0,37,47,0,0,141,142,140,0,0],"FLAG":0,"BASE":48}

**Comment by mrneutron42** [comment]
> Try doing the upgrade. I'm running 8.4.0 and the below is giving me satisfactory control:
> {"NAME":"","GPIO":[0,0,0,0,37,47,0,0,141,142,140,0,0],"FLAG":0,"BASE":48}
I already have version 8.4.0 loaded (see 2nd line of 1st post).
I just uploaded the 8.4.0 firmware file again...no change....no color control.
Your template yields the same no-color results.

**Comment by mrneutron42** [comment]
OK...problem diagnosed.   I've got color control!
I was following the Migration Path instructions and manually loading the "lite" versions of the bin files.
see https://tasmota.github.io/docs/Upgrading/#migration-path
Apparently, the "lite" versions don't support the SM16716 LED driver chip?
I tried loading the full tasmota.bin file and it failed.
![Tasmota full 8 4 0 fails](https://user-images.githubusercontent.com/70338169/91641430-f4af4380-e9e9-11ea-8b49-1f8a2fbc8b1a.JPG)
So, I tried loading the tasmota-minimal.bin.  That worked.
Then, I tried the full tasmota.bin file again, and it worked.

For future reference, during firmware upgrade/migration, can the minimal versions be loaded instead of the "lite" versions?

**Comment by ascillato** [comment]
Tasmota minimal is only for upgrading. It is a firmware just to free space and let the full version to be installed by OTA. Minimal does not have any driver and is not for normal usage or first flash. It is just an interim firmware in order to be able to update to the full version.

The lite version is just a Tasmota small version with few drivers intended for devices with poor power regulators. 

For normal usage use tasmota.bin that is the full version.

**Comment by mrneutron42** [comment]
For the record, my final template for these Feit BPA800/RGBW/AG/2P RGBW bulbs is:
{"NAME":"BPA800/RGBW/AG/2P","GPIO":[0,0,0,0,37,47,0,0,141,142,140,0,0],"FLAG":0,"BASE":48}

GPIO5 needs to be an inverted PWM to correctly control the CoolWhite-WarmWhite slider.
I also eliminated the leading space in the name BPA800/RGBW/AG/2P, because it caused the last P to be truncated in the Tasmota GUI.

**Comment by JaimeZX** [comment]
Glad you got it worked out!

**Comment by mrneutron42** [comment]
> Glad you got it worked out! If you figure out how to change the White Color Temp from Home Assistant, let me know. ;)

OK, will do.  I don't have a Home Assistant setup, yet.  Are you using a Raspberry Pi3 or Pi4?

**Comment by JaimeZX** [comment]
Just got a Pi4 off Amazon. HA install was easy. Adding devices was easy. These bulbs will automatically give you Color Temp, Color Picker, and Dimmer in the HA GUI. But trying to do a smooth dim or change color / color temp from a script or automation is so far escaping me.
