### ISSUE TITLE
shelly 1 Tasmota as momentary switch with feedback to Alexa - Rule required

### ISSUE THREAD

**Issue by kamilo558** [arendst/Tasmota#9181]
**Have you looked for this feature in other issues and in the docs?**  
Yes, but I have not yet been able to find a clear clarification.

**Is your feature request related to a problem? Please describe.**  
Is there a function or setting in Tasmota that I use the shelly 1 as a momentary switch with e.g. impulsetime 10 (sec) and the shelly internally stores this switching state and passes it to Alexa although the momentary switch has switched off the output after one second?

So:

- Alexa switch on
- Switch sets output for one second and switches off again (output goes to a current surge relay) but passes switching state 1 to Alexa

How could you get Alexa to send the switch a pulse signal again? I would have to say "Alexa, switch on" again to generate a pulsetime. But if I say Alexa switch off, no pulse would be generated by the switch...

Thanks a lot.

**Describe the solution you'd like**  
see above

**Describe alternatives you've considered**  
-

**Additional context**  
-

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
It's not supported out of the box, but maybe you can achieve this with scripting (not Rules). 

https://tasmota.github.io/docs/Scripting-Language/

**Comment by kamilo558** [comment]
OK. Is there a more simple way?

**Comment by Jason2866** [comment]
No

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

If you need further assistant, please just ask here or in the Tasmota support chat. Thanks. 

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
