### ISSUE TITLE
Wakeup light in 256 steps

### ISSUE THREAD

**Issue by jesseruiter** [arendst/Tasmota#9241]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
When the wakeup command is called, the light is still quite bright at the start and the fading isn't very smooth.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
When the wakeup command uses 256 (instead of 100) steps the fading will be smoother and I don't wake up directly when the value is 1%😁

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
I can't come up with an alternative solution.

**Additional context**  
_Add any other context or screenshots about the feature request here._
Not needed.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
Please give more details about your setup. What kind of light are you using (pwm?) and did you enable gamma correction with `LedTable 1`?

**Comment by jesseruiter** [comment]
I am using a 5050 SMD LED Strip in combination with a Magic Home controller. I don't use gamma correction, as LedTable == 0.

**Comment by jesseruiter** [comment]
However, I don't think it depends on my setup, but on the way the wakeup function is implemented. Right now the least bright is 1 percent (so 1/100) instead of the possible 1/256. The latter would result in a smoother wakeup pattern.

**Comment by s-hadinger** [comment]
Then I believe that you should enable Gamma Correction, otherwise the brightness goes very quickly to a high perceived value.

**Comment by jesseruiter** [comment]
I tried that function, but then my brightness of my led strip isn't lineair anymore and the initial brightness is still 1/100 instead of the possible 1/256. I think this issue is therefore a feature request, instead of a question.

**Comment by ascillato** [comment]
Hi,

Have you tried `LedTable 1`?

**Comment by jesseruiter** [comment]
Yes I did, but that made the smoothness of the LED strip's brightness worse.

**Comment by jesseruiter** [comment]
> I tried that function, but then my brightness of my led strip isn't lineair anymore and the initial brightness is still 1/100 instead of the possible 1/256. I think this issue is therefore a feature request, instead of a question.

But as said here, it is not so much a problem, but more a suggestion to smoothen the wake up pattern. Because I use the LED strip with the wakeup function as a wakeup light divided over 20 minutes, the experience would be better if the brightness is incremented 1/256 every ~5 seconds, instead of an increase of 1/100 every 12 seconds.

**Comment by ascillato2** [comment]
> LED strip with the wakeup function as a wakeup light divided over 20 minutes

Ok. With that time frame you need a higher resolution. With smaller time frames the 100 steps are smooth enough. 

Changing to feature request. Thanks for explaining.

**Comment by s-hadinger** [comment]
@jesseruiter I completely agree with you. When you use Gamma Correction `LedTable 1` it doesn't really make a difference because the first steps are very distant from each other and splitting in 256 wouldn't make a difference.

I don't have time in the short term to change this, but it shouldn't be a big change to the code, although we need to adjust the duration if it's 256 steps instead of 100.

**Comment by jesseruiter** [comment]
Thanks for your reaction! I look forward to the update sometime in the future.

**Comment by s-hadinger** [comment]
Oops, I observed a crash... Not ready
