### ISSUE TITLE
Tasmota sensor ver mdns problem

### ISSUE THREAD

**Issue by ryoma3111** [arendst/Tasmota#9249]
I rewrote the normal version to the sensor version to use the RF reception function, but the mdns function that worked fine in the normal version does not work in the sensor version.  I tried to set SetOption55 but it didn't improve.  In the information of WebUI, the mdns function is disabled.  By the way, the firmware for both versions is 8.4.0.

**Comment by Jason2866** [comment]
mDNS is not working reliable. This is a issue from Arduino ESP8266 core.
We discussed internally already to drop mDNS support.
Theo decided to keep it with the known issues...
You can open (another) issue in Arduino ESP8266 github for

**Comment by ryoma3111** [comment]
I built to ESP8266.  The build tool used esptool.py.

**Comment by Jason2866** [comment]
Not related to my statement. Every Tasmota version is for the ESP82XX. Esptool.py is the flashing tool. Nothing you can build a firmware. Building Tasmota is done with PlatformIO.
Please read the documentation for https://tasmota.github.io/docs/Compile-your-build/

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
