### ISSUE TITLE
Allow display of date in US format

### ISSUE THREAD

**Issue by stricklerlj61** [arendst/Tasmota#9260]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
US date format is not an option in display code

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Modify **_xdrv_13_display.ino_** at approximately line 637 to have below code
          case 'T':
            if (*cp=='U') {
              cp++;
              if (dp < (linebuf + DISPLAY_BUFFER_COLS) -8) {
                snprintf_P(dp, 9, PSTR("%02d" D_MONTH_DAY_SEPARATOR "%02d" D_YEAR_MONTH_SEPARATOR "%02d"), RtcTime.month, RtcTime.day_of_month, RtcTime.year%2000);
                dp += 8;
              }
            }else{
              if (dp < (linebuf + DISPLAY_BUFFER_COLS) -8) {
                  snprintf_P(dp, 9, PSTR("%02d" D_MONTH_DAY_SEPARATOR "%02d" D_YEAR_MONTH_SEPARATOR "%02d"), RtcTime.day_of_month, RtcTime.month, RtcTime.year%2000);
                  dp += 8;
              }
            }
            break;

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
Suffering thru it and explaining to all the users they have to change the way they think.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing this issue as this feature has been added by Theo. 

Thanks
