### ISSUE TITLE
Add Alexa support to shutters

### ISSUE THREAD

**Issue by stefanbode** [arendst/Tasmota#9274]
**Have you looked for this feature in other issues and in the docs?**  
Shutters can be tricked as dimmers or lamps, but the commands are not straight forward because you have to use off/on instead of up/down

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Add something like the Hue or Belkin, that Alexa found the shutter as a shutter device you can operate

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
At least Alexa can drive the shutter

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
exposing the shutter as a dimmer is a workaround but with wrong commands

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
Hue emulation does not support shutters with Alexa. Dimmer is the only possible workaround. 
Otherwise you need to code a specific Alexa skill or use home automation software
