### ISSUE TITLE
Error in measuring the energy

### ISSUE THREAD

**Issue by FISO291** [arendst/Tasmota#9278]
Voltage and current are measured on a Gosund SP111 socket. The power/apparent power was almost 1900W. The socket with Tasmota 8.5.0 calculated the following:

After 10 min 47Wh 
After 15min 70 Wh 
After 20min 94Wh 

But if I calculate E = P*t, the following should come out:

E(10min) = P * t = 1900W * 0,167h = 316Wh
E(15min) = P * t = 1900W * 0,250h = 475Wh 
E(20min) = P * t = 1900W * 0,333h = 633Wh 

How is it possible that the displayed value in the Tasmota interface is only 1/6 of what it should be? But since the correct power was measured, it can only be a calculation error by Tasmota?

p.s. Voltage and current were relatively constant at 8.4 - 8.8A and 224V. So the consumption should have been at 31Wh per minute and not 4.7Wh as I was shown on the Tasmota surface...

**Comment by arendst** [comment]
See #9263 and #9266
