### ISSUE TITLE
When setting Topic to equal MqttClient, the topic is reset to the defaults

### ISSUE THREAD

**Issue by agross** [arendst/Tasmota#9282]
### PROBLEM DESCRIPTION

I want to configure `Topic` and `MqttClient` using HTTP requests. (The issue is unrelated to using HTTP, the same error shows up when using the Console feature, but not when using the Web UI to configure these.)

Consider this:

```
14:14:45 CMD: MqttClient
14:14:45 MQT: home/something/power/stat/shelly1-2/RESULT = {"MqttClient":"shelly1-2"}
14:15:01 CMD: Topic
14:15:01 MQT: home/something/power/stat/shelly1-2/RESULT = {"Topic":"shelly1-2"}
14:15:07 CMD: Topic shelly1-2
14:15:07 SRC: WebConsole from 172.16.0.13
14:15:07 CMD: Group 0, Index 1, Command "TOPIC", Data "shelly1-2"
14:15:07 MQT: home/something/power/stat/shelly1-2/RESULT = {"Topic":"tasmota_%06X"}
```

As soon as I change the `Topic` to the same value as `MqttClient`, `Topic` gets reset to the firmware defaults. 

I first thought this might be due to the topic containing `1` and this being confused as `Topic 1`, but this is not the case.

The interesting bit is that it is possible to configure `Topic == MqttClient` using the web UI without problems.

### REQUESTED INFORMATION
- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Shelly 1
- [x] Tasmota binary firmware version number used: 8.5.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
This is unrelated to the issue, isn't it?
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
No rules used
```
- [ ] Provide the output of this command: `Status 0`:
```
14:26:10 CMD: Status 0 
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS = {"Status":{"Module":0,"DeviceName":"Shelly 1 #2 Bedroom Light Switch West","FriendlyName":["Shelly 1 #2 Bedroom Light Switch West"],"Topic":"shelly1-2","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:10:33","StartupUTC":"2020-09-10T13:15:37","Sleep":50,"CfgHolder":4617,"BootCount":11,"BCResetTime":"2020-09-07T20:21:06","SaveCount":71,"SaveAddress":"F5000"}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS2 = {"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-07T10:35:04","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"447/699"}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["127.0.0.1",""],"TelePeriod":10,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS5 = {"StatusNET":{"Hostname":"shelly1-2-7380","IPAddress":"172.16.0.165","Gateway":"172.16.0.3","Subnetmask":"255.255.255.0","DNSServer":"172.16.0.3","Mac":"E0:98:06:95:1C:D4","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt","MqttPort":1883,"MqttClientMask":"shelly1-2","MqttClient":"shelly1-2","MqttUser":"mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS7 = {"StatusTIM":{"UTC":"2020-09-10T13:26:10","Local":"2020-09-10T14:26:10","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:20","Sunset":"19:13"}}
14:26:10 MQT: home/bedroom/power/stat/shelly1-2/STATUS10 = {"StatusSNS":{"Time":"2020-09-10T14:26:10","Switch1":"ON"}}
14:26:11 MQT: home/bedroom/power/stat/shelly1-2/STATUS11 = {"StatusSTS":{"Time":"2020-09-10T14:26:10","Uptime":"0T00:10:33","UptimeSec":633,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"127.0.0.1","BSSId":"9C:D6:43:2C:53:20","Channel":1,"RSSI":100,"Signal":-47,"LinkCount":1,"Downtime":"0T00:00:03"}}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
See above.
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Configure MQTT client == topic using the web UI
1. Enter this into the Console: `Topic <value set in step 1>`

### EXPECTED BEHAVIOUR

Topic should not change.

**Comment by sfromis** [comment]
Reading docs is usually a good plan. https://tasmota.github.io/docs/Commands/#topic has the warning "Mqtt Topic can't be equal to Mqtt Client".

**Comment by agross** [comment]
Oh, I missed that. Thank you for the pointer.

Contrary to what the docs say, they actually can be equal when both are set via the web UI.

**Comment by agross** [comment]
@sfromis 

I also read the docs before posting here.

The way this useful piece of information about non-equality is formatted is not that helpful, though. I stopped reading the italic part after "If using MQTT to issue this command" because I don't use MQTT to issue the command.

My suggestion now is to place "(Mqtt Topic can't be equal to Mqtt Client)" on a separate line (perhaps even preceded by an empty line) to visually split it from the MQTT and group topics limitation.

**Comment by Jason2866** [comment]
Docs are Open Source too. A PR is welcome

**Comment by alxferraz** [comment]
why is that the these two parameters cant have the same value?

**Comment by jwinterton** [comment]
> why is that the these two parameters cant have the same value?

I'd be interested in the answer to that question too. I have always set the MQTTClient and Topic to the same unique (per device) name across all my Tasmota devices. So each device is unique but the MQTTClient and Topic are identical per device. e.g. my plugs are called plug1, plug2 .. plugx and this is used for the client and topic.

I only noticed the advice in the Docs not to do this recently - I was looking as I had the issue mentioned above where setting the Topic didn't work. I had never previously had an issue with this so I am guessing the restrictions were enforced in recent firmware.

Given the above my question is should I now go change them all to make client and topic different for each device? It seems to have worked for years?

**Comment by sfromis** [comment]
By now, it is a long time since that restriction was lifted, and there is no "should" about what to do. One downside of using same names for unrelated purposes is when the meaning of seeing or using a name somewhere may become "less clear".

**Comment by jwinterton** [comment]
Thanks @sfromis I am using older firmware (10.x) which I guess is why I am still seeing the restriction. I find having identifiable names for the MQTT log useful which is why I change it but I take your point. I guess I am ok for now then.
