### ISSUE TITLE
Time event not fired without NTP

### ISSUE THREAD

**Issue by ilvalle** [arendst/Tasmota#9284]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I've created the rule below but it doesn't work if you run `wifi off` before.
```
Rule
02:34:31 CMD: Rule
02:34:31 RSL: tasmota/stat/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":34,"Free":477,"Rules":"on Time#Minute=30 do wifi on endon"}
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): Sonoff Basic
- [ ] Tasmota binary firmware version number used: 8.5.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: est
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
2␀0:14:55 CMD: Backlog Template; Module; GPIO 255
20:14:55 MQT: tasmota/stat/RESULT = {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
20:14:56 MQT: tasmota/stat/RESULT = {"Module":{"1":"Sonoff Basic"}}
20:14:56 MQT: tasmota/stat/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
20:16:11 MQT: tasmota/stat/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":34,"Free":477,"Rules":"on Time#Minute=30 do wifi on endon"}
20:16:11 MQT: tasmota/stat/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
20:16:12 MQT: tasmota/stat/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
20:16:35 MQT: tasmota/stat/STATUS = {"Status":{"Module":1,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
20:16:35 MQT: tasmota/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Power On","Uptime":"0T00:02:48","StartupUTC":"2020-09-10T19:13:47","Sleep":50,"CfgHolder":4617,"BootCount":19,"BCResetTime":"2020-09-09T19:54:38","SaveCount":55,"SaveAddress":"F5000"}}
20:16:35 MQT: tasmota/stat/STATUS2 = {"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"341/699"}}
20:16:35 MQT: tasmota/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Pibu2",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00000200","00006000","00000000"]}}
20:16:35 MQT: tasmota/stat/STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
20:16:36 MQT: tasmota/stat/STATUS5 = {"StatusNET":{"Hostname":"TH_Deu","IPAddress":"192.168.100.100","Gateway":"192.168.100.250","Subnetmask":"255.255.255.0","DNSServer":"192.168.100.250","Mac":"C8:2B:96:02:EC:B2","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
20:16:36 MQT: tasmota/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.100.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_02ECB2","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
20:16:36 MQT: tasmota/stat/STATUS7 = {"StatusTIM":{"UTC":"2020-09-10T19:16:36","Local":"2020-09-10T20:16:36","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:20","Sunset":"19:13"}}
20:16:36 MQT: tasmota/stat/STATUS10 = {"StatusSNS":{"Time":"2020-09-10T20:16:36"}}
20:16:36 MQT: tasmota/stat/STATUS11 = {"StatusSTS":{"Time":"2020-09-10T20:16:36","Uptime":"0T00:02:49","UptimeSec":169,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Pibu2","BSSId":"F8:1A:67:09:9E:97","Channel":6,"RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:03"}}}


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
run the command `wifi off`, the device will reboot, the time starts from 1970-01-01T00:00:00

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
The rule should be fired 30minutes after the reboot, if the time is synchronized it works

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

It is designed as that. It is an intended behavior. If there is no Time source, Tasmota won't execute any time-related feature. 

If you want to have a stand-alone device, you can:

+ Add a Time source using a GPS chip or a battery backed DS clock.

OR

+ If you don't care about the time, you must instruct Tasmota about this by setting the time at startup. You can use a rule like: `rule1 on power1#boot do time 1599767508 endon`

If you want to set any particular time, you can use the epoch time from www.epochconverter.com

Thanks.
