### ISSUE TITLE
Not all devices are showing information.

### ISSUE THREAD

**Issue by nasked** [arendst/Tasmota#9289]
No se puede encontrar dispositivo. Reintente por favor. Esto suele ocurrir cuando el dispositivo está reiniciando o hay demasiados pedidos en el mismo.
ERROR de JSON => 4: Syntax error
Por favor, copie el mensaje completo del error y péguelo en un nuevo issue en GitHub de TasmoAdmin.
Respuesta JSON => {"Status":{"Module":39,"DeviceName":"Persiana_Despacho_1","FriendlyName":["Persiana_Despacho_1","Persiana_Despacho_2"],"Topic":"Persiana_Despacho","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://10.17.17.10:9999/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:09:07","StartupUTC":"2020-09-12T10:33:49","Sleep":50,"CfgHolder":4617,"BootCount":22,"BCResetTime":"2020-04-24T08:54:16","SaveCount":1474,"SaveAddress":"F7000"},"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"431/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Nasked",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000AC009","2805C8000100060000005A00000000000000","40000200","00006000","00000000"]},"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"Persiana_Despacho-7749","IPAddress":"10.17.17.116","Gateway":"10.17.17.1","Subnetmask":"255.255.255.0","DNSServer":"10.17.17.1","Mac":"C4:4F:33:8C:7E:45","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"10.17.17.100","MqttPort":1883,"MqttClientMask":"Persiana_Despacho","MqttClient":"Persiana_Despacho","MqttUser":"nasked","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-09-12T10:42:57","Local":"2020-09-12T11:42:57","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:23","Sunset":"19:08"},"StatusSNS":{"Time":"2020-09-12T11:42:57","Switch1":"ON","Switch2":"ON","Shutter1":{"Position":26,"Direction":0,"Target":27}},"StatusSTS":{"Time":"2020-09-12T11:42:57","Uptime":"0T00:09:08","UptimeSec":548,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Nasked","BSSId":"4C:5E:0C:A7:59:C0","Channel":5,"RSSI":94,"Signal":-53,"LinkCount":1,"Downtime":"0T00:00:03"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":200,"Close":210,"50perc":65,"Delay":0,"Opt":"0100","Calib":"12000:280:2680:900:1000"}}

**Comment by ascillato** [comment]
Tasmoadmin issues should be addressed to Tasmoadmin repository. Thanks. 

Los problemas con Tasmoadmin deben ser reportados en el sitio de Tasmoadmin. Gracias
