### ISSUE TITLE
LED on/blink when Wi-Fi and/or MQTT are NOT connected.

### ISSUE THREAD

**Issue by Skaning** [arendst/Tasmota#9304]
**Have you looked for this feature in other issues and in the docs?**  
Yes, it's not supported. However, there might be som workarounds I am not aware of.

**Is your feature request related to a problem? Please describe.**  
Well, kind of. I would like to have some active indication when Wifi or MQTT connection is lost, even when the default state of the LED is off.

**Describe the solution you'd like**  
I would like additional options to command LedState.

**Describe alternatives you've considered**  
I considered to have the default state of the LED on, but since some devices have very bright LEDs and is annoying especially night time. 

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated** (#9292). Sorry.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
