### ISSUE TITLE
"WebSend":"Connect failed"

### ISSUE THREAD

**Issue by harmonykorine** [arendst/Tasmota#9338]
I've just flashed my Sonoff bridge with tasmota and I'm trying to get my 8 switch RF controller to work with it on Samsung Smartthings hub. Everything seemed to be going well until I got to the part where I need to copy and paste de command codes over to the ST app. Here's what it show in the console box:

15:47:43 RUL: RFRECEIVED#RFKEY performs "WebSend [0.0.0.0:0] /?json={"RfReceived":{"RfKey":"1"}}"
15:47:49 RSL: RESULT = {"WebSend":"Connect failed"}

I have done the learning process of the buttons, that's why it says "RfKey":"1", but I don't know why it returns as "Connect Failed" and not "Done". Also, I'm not quite sure if the [0.0.0.0:0] is correct and, if it isn't I do not know how to change it and what to put it its place.

Hope someone is able to help me
Thanks!

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
15:47:43 RUL: RFRECEIVED#RFKEY performs "WebSend [0.0.0.0:0] /?json={"RfReceived":{"RfKey":"1"}}"
15:47:49 RSL: RESULT = {"WebSend":"Connect failed"}

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): _____Sonoff RF Bridge
- x[ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
