### ISSUE TITLE
"WebSend":"Connect failed"

### ISSUE THREAD

**Issue by harmonykorine** [arendst/Tasmota#9341]
've just flashed my Sonoff bridge with tasmota and I'm trying to get my 8 switch RF controller to work with it on Samsung Smartthings hub. Everything seemed to be going well until I got to the part where I need to copy and paste de command codes over to the ST app. Here's what it show in the console box:

```
15:47:43 RUL: RFRECEIVED#RFKEY performs "WebSend [0.0.0.0:0] /?json={"RfReceived":{"RfKey":"1"}}"
15:47:49 RSL: RESULT = {"WebSend":"Connect failed"}
```

I have done the learning process of the buttons, that's why it says "RfKey":"1", but I don't know why it returns as "Connect Failed" and not "Done". Also, I'm not quite sure if the [0.0.0.0:0] is correct and, if it isn't I do not know how to change it and what to put it its place.

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Command "WebSend" not going through.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): Sonoff RF Bridge
- [ x] Tasmota binary firmware version number used: 8.5.0
  - [ x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x ] Flashing tools used: Tasmotizer
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
18:40:12 CMD: Backlog Template; Module; GPIO 255
18:40:12 RSL: stat/tasmota_C23DBA/RESULT = {"NAME":"Sonoff Bridge","GPIO":[17,148,255,149,255,255,0,0,255,56,255,0,0],"FLAG":0,"BASE":25}
18:40:12 RSL: stat/tasmota_C23DBA/RESULT = {"Module":{"0":"Sonoff Bridge"}}
18:40:13 RSL: stat/tasmota_C23DBA/RESULT = {"GPIO0":{"17":"Button1"},"GPIO1":{"148":"Serial Tx"},"GPIO2":{"0":"None"},"GPIO3":{"149":"Serial Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"56":"Led1i"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}


```
- [x ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
18:41:38 CMD: Backlog Rule1; Rule2; Rule3
18:41:38 RSL: stat/tasmota_C23DBA/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Length":179,"Free":332,"Rules":"ON RfReceived#Data DO WebSend [0.0.0.0:0] /?json={\"RfReceived\":{\"Data\":\"%value%\"}} ENDON ON RfReceived#RfKey DO WebSend [0.0.0.0:0] /?json={\"RfReceived\":{\"RfKey\":\"%value%\"}} ENDON"}
18:41:38 RSL: stat/tasmota_C23DBA/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
18:41:38 RSL: stat/tasmota_C23DBA/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}


```
- [x ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
18:42:07 CMD: Status 0
18:42:07 RSL: stat/tasmota_C23DBA/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_C23DBA","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS1 = {"StatusPRM":{"Baudrate":19200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:11:17","StartupUTC":"2020-09-18T17:30:50","Sleep":50,"CfgHolder":4617,"BootCount":13,"BCResetTime":"2020-09-18T14:43:17","SaveCount":33,"SaveAddress":"F7000"}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS2 = {"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"377/699"}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["NET CASA 9 2G",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS5 = {"StatusNET":{"Hostname":"tasmota_C23DBA-7610","IPAddress":"192.168.0.32","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"189.5.128.114","Mac":"E0:98:06:C2:3D:BA","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C23DBA","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS7 = {"StatusTIM":{"UTC":"2020-09-18T17:42:07","Local":"2020-09-18T18:42:07","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:31","Sunset":"18:56"}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS10 = {"StatusSNS":{"Time":"2020-09-18T18:42:07"}}
18:42:07 RSL: stat/tasmota_C23DBA/STATUS11 = {"StatusSTS":{"Time":"2020-09-18T18:42:07","Uptime":"0T00:11:17","UptimeSec":677,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Wifi":{"AP":1,"SSId":"NET CASA 9 2G","BSSId":"98:1E:19:12:F7:8A","Channel":1,"RSSI":92,"Signal":-54,"LinkCount":1,"Downtime":"0T00:00:06"}}}


```
- [ x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
18:42:52 CMD: weblog 4
18:42:52 RSL: stat/tasmota_C23DBA/RESULT = {"WebLog":4}
18:42:53 CFG: Saved to flash at F6, Count 34, Bytes 4096
18:43:07 WIF: Checking connection...
18:43:27 WIF: Checking connection...
18:49:02 DMP: A4 1E 14 01 22 02 DA BD DB E8 55
18:49:02 RSL: tele/tasmota_C23DBA/RESULT = {"Time":"2020-09-18T18:49:02","RfReceived":{"Sync":7700,"Low":290,"High":730,"Data":"BDDBE8","RfKey":1}}
18:49:02 RUL: RFRECEIVED#DATA performs "WebSend [0.0.0.0:0] /?json={"RfReceived":{"Data":"BDDBE8"}}"
18:49:02 SRC: Rule
18:49:02 CMD: Group 0, Index 1, Command "WEBSEND", Data "[0.0.0.0:0] /?json={"RfReceived":{"Data":"BDDBE8"}}"
18:49:07 RSL: stat/tasmota_C23DBA/RESULT = {"WebSend":"Connect failed"}
18:49:07 RUL: RFRECEIVED#RFKEY performs "WebSend [0.0.0.0:0] /?json={"RfReceived":{"RfKey":"1"}}"
18:49:07 SRC: Rule
18:49:07 CMD: Group 0, Index 1, Command "WEBSEND", Data "[0.0.0.0:0] /?json={"RfReceived":{"RfKey":"1"}}"
18:49:13 RSL: stat/tasmota_C23DBA/RESULT = {"WebSend":"Connect failed"}
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
"WebSend":"Done"

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I'm trying to integrate my RM433 Rf Controller with the bridge, but every time I press a button the command comes back as "Connect Failed" when it should be "Done".

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
