### ISSUE TITLE
Tasmota multiple sensor topics

### ISSUE THREAD

**Issue by fizroy** [arendst/Tasmota#9343]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by fizroy** [comment]
I have 3  LYWSD03MMC ble sensors conected to a esp32 with tasmota, but the data from them is sent to the same mqtt topic tele/tasmota/SENSOR...and not all toghether but in different lines...i olso use openhab to recive the data from the sensors and since they all use the same topic and have different id's i get a log full of warnigs.
![unknown (1)](https://user-images.githubusercontent.com/36958354/93651335-d3a2a700-fa19-11ea-93d6-55393a7781c6.png)
![unknown](https://user-images.githubusercontent.com/36958354/93651338-d56c6a80-fa19-11ea-8159-75e8d961a4e8.png)
 is it posible to have all the sensors maybe report in the same line or have different sensor topic like for zigbee sensors or like POWER???

**Comment by schrej-zz** [comment]
You can use the REGEX transformation in the Openhab channels to prevent these warnings.

**Comment by fizroy** [comment]
I already use json for the data ...any tip on the REGEX part?

**Comment by fizroy** [comment]
Still it would be better if the dev's implement something like SetOption 89 but for ble devices.

**Comment by schrej-zz** [comment]
See https://community.openhab.org/t/mqtt-2-5-problem-with-receiving-status-updates-on-some-things/90054

**Comment by Jason2866** [comment]
Funny same answer i gave already in Discord before 😊

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
