### ISSUE TITLE
Air pressure offset zigbee

### ISSUE THREAD

**Issue by Oblivionevil** [arendst/Tasmota#9394]
**Have you looked for this feature in other issues and in the docs?**  

yes but i found only solution for i2c

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Sea level offset for zigbee devices 

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

Offset for pressure

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._
Hello,

today i paired my Aqara Temperature Humidity Sensor.
![Unbenannt](https://user-images.githubusercontent.com/34569567/94342988-5a0c4980-0015-11eb-91c1-a04ecb463ac4.jpg)

but it is not possible to calibrate the pressure level.
Is there a option to set an offset for the device ?

Thanks for the help

oblivionevil

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Mount the ausensensor ten meter higher...

**Comment by Oblivionevil** [comment]
Sorry misunderstanding the correct value is at the moment 990 hpa

**Comment by Jason2866** [comment]
What makes you think 990hpa is the correct value?
Two of your sensors show nearly identic values

**Comment by Oblivionevil** [comment]
3 Weather Stations show this value and online service

**Comment by Jason2866** [comment]
Most pressure sensors are very precise. In my experience better than temperature and humidity...
![Screenshot_20200926-184841](https://user-images.githubusercontent.com/24528715/94345886-5aaedb00-0029-11eb-9fdf-9117c046297f.png)
![Screenshot_20200926-184826](https://user-images.githubusercontent.com/24528715/94345895-639fac80-0029-11eb-9dbd-ac4935103912.png)

**Comment by Oblivionevil** [comment]
Altitude has no effect on zigbee

**Comment by Jason2866** [comment]
Okay, you want the feature sea pressure for zigbee! This is NOT a offset
Different thing. Sea pressure is calculated in Tasmota

**Comment by s-hadinger** [comment]
I didn't know about Sea Pressure calculation and can add it to Mqtt messages
