### ISSUE TITLE
Messages for NFC data and IR data inconsistent

### ISSUE THREAD

**Issue by drtorchwood** [arendst/Tasmota#9401]
### PROBLEM DESCRIPTION
This is not a real problem but an inconsistency in the json messages send for NFC and IR. 
The NFC messages report to `SENSOR`, e.g.
`wemos-NFC/SENSOR = {"Time":"2020-09-27T00:13:22","PN532":{"UID":"E9CE10A4", "DATA":"somedata"}}`
and with `DATA` written in capital letters. 

However, data received via IR reports to `RESULT`, e.g.
`wemos-NFC/RESULT = {"Time":"2020-09-27T00:29:26","IrReceived":{"Protocol":"NEC","Bits":32,"Data":"0xFE80E619"}}`
and `Data` in lower case letters. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): WEMOS-D1
- [X] Tasmota binary firmware version number used: 8.5.0.1
  - [ ] Pre-compiled
  - [X] Self-compiled
    - [ X] IDE / Compiler used: TasmoCompiler v2.4.5
- [X] Flashing tools used: File upload
- [X] Provide the output of command: `Backlog Template; Module; GPIO 255`:

```
{"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
{"Module":{"18":"Generic"}}
{"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"139":"PN532 Rx"},"GPIO5":{"138":"PN532 Tx"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"51":"IRrecv"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
- [X] Provide the output of this command: `Status 0`:
```
wemos-NFC/STATUS = {"Status":{"Module":18,"DeviceName":"Wemos-nfc","FriendlyName":["Wemos-nfc"],"Topic":"wemos-NFC","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
wemos-NFC/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz","RestartReason":"External System","Uptime":"0T00:32:19","StartupUTC":"2020-09-26T22:13:08","Sleep":50,"CfgHolder":4617,"BootCount":20,"BCResetTime":"2020-09-15T21:27:14","SaveCount":52,"SaveAddress":"F6000"}}
wemos-NFC/STATUS2 = {"StatusFWR":{"Version":"8.5.0.1(tasmota)","BuildDateTime":"2020-09-26T22:01:05","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"406/699"}}
wemos-NFC/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Heremias",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
wemos-NFC/STATUS4 = {"StatusMEM":{"ProgramSize":506,"Free":496,"Heap":17,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","0F8A4582","04260001","000000C1","00100000","C000F981","00000004","00000000"],"Drivers":"1,2,4,5,6,8,9,10,18,19,22,24,26,27,29,30,35,37","Sensors":"1,2,4,5,6,40"}}
wemos-NFC/STATUS5 = {"StatusNET":{"Hostname":"wemos-NFC-1418","IPAddress":"192.168.178.63","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"48:3F:DA:49:85:8A","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
wemos-NFC/STATUS6 = {"StatusMQT":{"MqttHost":"albert","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_49858A","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
wemos-NFC/STATUS7 = {"StatusTIM":{"UTC":"2020-09-26T22:45:27","Local":"2020-09-27T00:45:27","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"07:44","Sunset":"19:36"}}
wemos-NFC/STATUS10 = {"StatusSNS":{"Time":"2020-09-27T00:45:27"}}
wemos-NFC/STATUS11 = {"StatusSTS":{"Time":"2020-09-27T00:45:27","Uptime":"0T00:32:19","UptimeSec":1939,"Heap":16,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":39,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Heremias","BSSId":"34:81:C4:A8:9A:0A","Channel":6,"RSSI":46,"Signal":-77,"LinkCount":1,"Downtime":"0T00:00:03"}}}


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_

### TO REPRODUCE
Compile tasmota with tasmocompiler using the IRBasic template and the additonal parameters 
```
#ifndef USE_PN532_HSU 
#define USE_PN532_HSU                            // Add support for PN532 using HSU (Serial) interface (+1k8 code, 140 bytes mem)
// Optional defines, uncomment (remove //) as needed
  #define USE_PN532_CAUSE_EVENTS                 // Cause event execution for PN532_UID= and PN532_DATA=[if defined] (+ 30 bytes code)
  #define USE_PN532_DATA_FUNCTION                // Add sensor40 command support for erase, setting data block content (+1k7 code, 388 bytes mem)
  #define USE_PN532_DATA_RAW                     // Allow DATA block to be used by non-alpha-numberic data (+ 80 bytes code, 48 bytes ram)
#endif
```

### EXPECTED BEHAVIOUR
Both results (nfc and ir) should have the same format as they report similar results. 

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
DATA is fixed to Data

For legacy reasons topic cannot be changed.
