### ISSUE TITLE
Status 13 returns malformed json

### ISSUE THREAD

**Issue by theOzzieRat** [arendst/Tasmota#9402]
### PROBLEM DESCRIPTION
Having configured a D1 Mini as a shutter TasmoAdmin starts complaing about syntax errors in json when requesting the status. Upon investigation the status 13 command is returning its json with the final } missing.

`{"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":100,"Close":100,"50perc":50,"Delay":20,"Opt":"0000","Calib":"300:500:700:900:1000","Mode":"0"}}`

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): D1 Mini
- [ ] Tasmota binary firmware version number used: 8.5.0.1
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: TasmoAdmin
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  {"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
{"Module":{"18":"Generic"}}
{"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"37":"PWM1"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"21":"Relay1"},"GPIO13":{"22":"Relay2"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}
```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
02:53:18 CMD: Status 0
02:53:18 MQT: stat/garage_dropsaw/STATUS = {"Status":{"Module":18,"DeviceName":"Garage Dropsaw","FriendlyName":["Garage Dropsaw","Tasmota2"],"Topic":"garage_dropsaw","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
02:53:18 MQT: stat/garage_dropsaw/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://10.0.1.12:9541/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:21:23","StartupUTC":"2020-09-27T01:31:55","Sleep":50,"CfgHolder":4617,"BootCount":47,"BCResetTime":"2020-08-06T05:23:54","SaveCount":217,"SaveAddress":"F9000"}}
02:53:18 MQT: stat/garage_dropsaw/STATUS2 = {"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"391/699"}}
02:53:18 MQT: stat/garage_dropsaw/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ProAtomic IoT",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00000009","2805C8000100060000005A00000000000000","40000000","00006000","00000000"]}}
02:53:18 MQT: stat/garage_dropsaw/STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":22,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
02:53:18 MQT: stat/garage_dropsaw/STATUS5 = {"StatusNET":{"Hostname":"Sonoff-17","IPAddress":"10.0.10.17","Gateway":"10.0.10.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.10.1","Mac":"8C:AA:B5:0D:4C:00","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
02:53:18 MQT: stat/garage_dropsaw/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.1.12","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0D4C00","MqttUser":"sun-mqtt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
02:53:18 MQT: stat/garage_dropsaw/STATUS7 = {"StatusTIM":{"UTC":"2020-09-27T01:53:18","Local":"2020-09-27T02:53:18","StartDST":"2020-10-04T02:00:00","EndDST":"2020-04-05T03:00:00","Timezone":"+01:00","Sunrise":"06:44","Sunset":"18:36"}}
02:53:18 MQT: stat/garage_dropsaw/STATUS10 = {"StatusSNS":{"Time":"2020-09-27T02:53:18","Shutter1":{"Position":100,"Direction":0,"Target":100}}}
02:53:18 MQT: stat/garage_dropsaw/STATUS11 = {"StatusSTS":{"Time":"2020-09-27T02:53:18","Uptime":"0T00:21:23","UptimeSec":1283,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","PWM":{"PWM1":135},"Wifi":{"AP":1,"SSId":"ProAtomic IoT","BSSId":"92:F6:52:A4:BB:9E","Channel":6,"RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}}}
02:53:18 MQT: stat/garage_dropsaw/STATUS13 = {"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":0,"Close":0,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000"}}
```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
Configure device as Shutter and issue status 13. It will return malformed json.

### EXPECTED BEHAVIOUR
Return json that is properly encoded.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Fixed already in latest dev.
