### ISSUE TITLE
subscription not availableafter restart

### ISSUE THREAD

**Issue by kbfifi** [arendst/Tasmota#9417]
I'm using a Sonoff mini that switches a lamp. I made a rule that depends on on a subscription. Works great:
subscribe badkamerswitch, badkamer/switch2/state
rule1 on event#badkamerswitch=OFF do power OFF endon

Note that I saved this config by "restart 1"

However when I reboot the rule is still there but the subscription is gone and so the rule no longer works.

Intentionally or Bug? Or some option I need to change?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
