### ISSUE TITLE
Stepper Driver Counter for Position

### ISSUE THREAD

**Issue by canis-ferrin** [arendst/Tasmota#9439]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  
It schould be very useful to have a position counter reading for A4988 stepper driver, which shows the actual step between
0 and <number of steps> -1, I use it in FHEM, but PERL is not fast enough to count steps correctly by a subroutine.
Ithink, a wemos, an Electrodragon or a Sonoff cpuld handle this.

**Comment by stefanbode** [comment]
You can do this electrically. Define counter1 on a gpio and connect the gpio to the pwm. Now you get your counts. Maybe you take a look at the shutter function for stepper motors.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
