### ISSUE TITLE
Support for Energy Meter DTS6619?

### ISSUE THREAD

**Issue by sp0ok3r** [arendst/Tasmota#9508]
I changed the xnrg_10_sdm630 to work with the DTS6619 and it worked, but i wanted to show the last four registers, since the sdm630 its not the same. I wanted to see this last values in web

const uint16_t dts6619_start_addresses[] {
// 3P4 3P3 1P2 Unit Description
0x0000, // + - + V Phase 1 volts 0
0x0002, // + - - V Phase 2 volts 1
0x0004, // + - - V Phase 3 volts 2
0x0008, // + + + A Phase 1 current 3
0x000A, // + + - A Phase 2 current 4
0x000C, // + + - A Phase 3 current 5
0x0012, // + - + W Phase 1 power 6
0x0014, // + - + W Phase 2 power 7
0x0016, // + - - W Phase 3 power 8
0x001A, // + - + VAr Phase 1 volt amps reactive 9
0x001C, // + - - VAr Phase 2 volt amps reactive 10
0x001E, // + - - VAr Phase 3 volt amps reactive 11
0x002A, // + - + Phase 1 power factor 12
0x002C, // + - - Phase 2 power factor 13
0x002E, // + - - Phase 3 power factor 14
0x0036, // + + + Hz Frequency of supply voltages 15
0x0018, // + + + kvar total reactive power 16
0x0010, // + + + kWh total active energy power 17
0x0100, // + + + Kwh total active electricity power 18
0x0400 // + + + kVar reactive electricity power 19
};

**Comment by ascillato2** [comment]
> I changed the xnrg_10_sdm630 to work with the DTS6619 and it worked

Great, please provide a Pull Request and we can check further steps there. Thanks.
