### ISSUE TITLE
Using 6 relays as a 'Dimmer'

### ISSUE THREAD

**Issue by alextrical** [arendst/Tasmota#9523]
**Have you looked for this feature in other issues and in the docs?**  
Yes, it may exist but i don't know the correct keywords

**Is your feature request related to a problem? Please describe.**  
I'm looking to make a light fixture that 'dims' the light output by adjusting the amount of bulbs that are currently turned on via relays. 

i.e. 
0%      - All Relays off
1-17%   - 1 Relay on
18-33%  - 2 Relays on
34-50%  - 3 Relays on
51-66%  - 4 Relays on
67-83%  - 5 Relays on
84-100% - All Relays on

**Describe the solution you'd like**  
Ideally, I think the solution is creating a 'Virtual Dimmer' in a Rule, that can then be used as a variable to inform the Relay's which ones should be active and which should be inactive.
I have created the code in Arduino IDE that I would like to recreate in Tasmota.

**Describe alternatives you've considered**  
I know that lights are usually dimmed with a Triac, and dimmable bulbs, however i would like to have a solution that can work without needing specialist bulbs, in a fixture that has 6 sockets.
I have the code above working in WLED, but would like to use Tasmota as the base

**Additional context**  
[https://www.tinkercad.com/embed/cQdeem6aVcP](url)
`const int ledCount = 6;    // the number of LEDs in the bar graph
int ledPins[] = {3, 4, 5, 6, 7, 8};   // an array of pin numbers to which LEDs are attached

int offset = 0;
int val = 0;

void setup() {
  Serial.begin(9600);
  pinMode(A0, INPUT);
  for (int thisLed = 0; thisLed < ledCount; thisLed++) {  // loop over the pin array and set them all to output:
    pinMode(ledPins[thisLed], OUTPUT);
  }
}

void loop() {
  val = analogRead(A0); // read the input on analog pin 0:
  
  int ledLevel = map(val, 1220, 0, ledCount, 0);    // map the result to a range from 0 to the number of LEDs:

  for (int thisLed = 0 + offset; thisLed < ledCount + offset; thisLed++) {  // loop over the LED array:
    if (thisLed < ledLevel + offset) { // if the array element's index is less than ledLevel, turn the pin for this element on:
      digitalWrite(ledPins[thisLed % ledCount], HIGH);
    }
    else {    // turn off all pins higher than the ledLevel:
      digitalWrite(ledPins[thisLed % ledCount], LOW);
    }
  }
}`

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
https://discord.com/channels/479389167382691863/479389167382691865/765182395916746753
