### ISSUE TITLE
TUYAMCU output all data from MCU in POWER METER devices

### ISSUE THREAD

**Issue by ortegafernando** [arendst/Tasmota#9528]
**Have you looked for this feature in other issues and in the docs?**  
yes

**Is your feature request related to a problem? Please describe.**  
no

**Describe the solution you'd like**  
I will like to see also reactive power, power factor and aparent power.

**Describe alternatives you've considered**  
Read TUYAMCU papers, but I can't find solution

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

I have read web page about how to tasmotize ZMAI90 (power meter)
I have a eMylo device (clone).
Both ZMAI and eMylo have new versions that work with TUYAMCU (54) module.
But we only get current, power and voltage.

Could we get more parameters?

Could we get a SetOption to read all serial data and send to console to check if MCU is sending more data to Wifi Module? (to make debug process more easy)

Thanks a lot.

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
