### ISSUE TITLE
Stromcount for S0 Impulse like sOnOff POW

### ISSUE THREAD

**Issue by LurchiStromberg** [arendst/Tasmota#9546]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

Hi Folks!
I am new at this GitHub here so please forgive me if i do wrong.

I use Several sOnOff POW for Power Messurements with Tasmota Firmware.
Now I installed a Heat Pump at my Home and like to know, what Power Values this Pump have.
Sadly there is no meassurements build in the Web Interface of the Pump.
So I installed a Meter which is only connected to the Components of the Heat Pump.
So far so good.
The Meter has a S0 Port and i like to connect this Port to a WEMO ESP 8266 Board. I realized that already with ESP Easy but I am not satisfied with it.

I really like to have a similar Interface like it already exists for the sOnOff POW(2) at Tasmota.
Is there a way to connect the S0 wire to a GPIO of the Board and Take this Count for Current Power (Watt) ?
Then Values Engery Today, Yesterday and Total would be a Dream!
There should be settings to be able to tell Tasmota about the Count Values of the Meter. At my Meter its for example 1000 Pulses per kW/h.
The Meter is an Eurocount3.
https://www.ebay.de/itm/302452177982

Is that possible?

King Regards
Stromberg

**Comment by Jason2866** [comment]
There is support for Smart Meter Interface in Tasmota
 https://tasmota.github.io/docs/Smart-Meter-Interface/

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
