### ISSUE TITLE
Sonoff ZbBridge flashing docs

### ISSUE THREAD

**Issue by Repsionu** [arendst/Tasmota#9550]
**Have you looked for this feature in other issues and in the docs?**  
Yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
More info in documentation
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  
Addition to docs page: [https://zigbee.blakadder.com/Sonoff_ZBBridge.html](url)
In my case with lowly CH340 based level converter I had to connect **Z_RST to GND** also, otherwise Zigbee module was making Tasmotizing unstable :-( It was stuck at: **Identifying..**. after successful connection to ESP8266.
Maybe it would be of help for someone :-)
Best, JR

**Comment by MattWestb** [comment]
Its "normal" then connecting both the ESP, EFR32 and the serial converter to the same pins.
The EFR32 is getting the comtraffic from the com port and trying answering on it >> tasmoat flashing is failing.
I normally using one ESP D1 mini with one IKEA modul and i disconnecting the power to the EFR32 then flashing the tasmota. Its also possible connecting the EFR32 to the atinate comport pins (RX GIPO13 (D7) and TX GIPO15 (D8)) but its not practical then have the serial converter hard connected to the normal pins. 
The blakadders dock its good but not made for no tasmota standard installations and dont covering at all.
Very good that you sharing your experience / knowledge to the community :-)))
