### ISSUE TITLE
Sonoff Bridge Module stops working; UI Shows hieroglyphics signs

### ISSUE THREAD

**Issue by Nexder** [arendst/Tasmota#9572]
Hello,

i have 3 SonOff RF Bridges and all three are updated to Tasmota 8.5.0 Version

Sometimes (one time per week) the Bridges (independently from eachs other) stops working correctly.
When i connect to broken bridge the Webpage is shown hieroglyphics signs.
By click on the "Backup configuration" Button and after dowloading the backup, everything is fine again and the bridge is working like expected.
A simple reboot doesn't solve the issue.

The issue also exists with version 8.4.0 before.
I flashed the german version, after the automatic update it is a english version.

![bridge3](https://user-images.githubusercontent.com/48283061/96385362-a9b4df80-1193-11eb-928c-093738721649.png)
![bridge](https://user-images.githubusercontent.com/48283061/96385364-aa4d7600-1193-11eb-925c-eeea1f6e307f.png)
![bridge2](https://user-images.githubusercontent.com/48283061/96385365-aa4d7600-1193-11eb-9e14-acfe8af43f1b.png)

Hope that there is a fix.

**Comment by Jason2866** [comment]
Erase flash via esptool and flash it again. If the error is still there your hardware has a fault.
