### ISSUE TITLE
WS2812B on two channels

### ISSUE THREAD

**Issue by mikkihugo** [arendst/Tasmota#9574]
Hi,

Im trying to add two WS2812B strips on ports D1 and D2 on Lolin D1 mini.

They both work fine when i set the type to WS2812 on respective output but not if both have it at the same time. If both are set as WS2812 I loose control of D1.

Is there anything I can to do solve this and still use Tasmota? The kitchen builder forgot to add the return cable for the bus so I cannot put them in serial.

/M

**Comment by arendst** [comment]
Tasmota supports only ONE light device. So only one WS2812 string.

You would need to install a second Tasmota device to solve your issue.
