### ISSUE TITLE
Disable all leds on Sonoff S20

### ISSUE THREAD

**Issue by HennyN1955** [arendst/Tasmota#9624]
Would it be possible to disable all leds on Sonoff S20?

I have several S20s that I control with Domoticz on a RaspberryPI with MQTT
When I turn on the switch I would like the led in the button to remain off. Now I can see that a led turns blue when the switch is turned on. I have LedState 0 and LedPower1 off, but this does not give the desired result.
How can I achieve that? Or is this impossible?

Thanks for anyanswer

**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Disabling the blue led is only possible by physical means, as it is wired to gpio12, same as the relay. Snip or cover.

**Comment by HennyN1955** [comment]
> 
> 
> Disabling the blue led is only possible by physical means, as it is wired to gpio12, same as the relay. Snip or cover.

:-(
....is there no other way???

**Comment by sfromis** [comment]
Sure. You can burn it. Or use strong acid. Or get another device. :-D

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
