### ISSUE TITLE
serial-bridge with tasmota

### ISSUE THREAD

**Issue by spiderrr** [arendst/Tasmota#9637]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
no
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
interface ser2net in tasmota like espeasy ora other method
https://tasmota.github.io/docs/Commands/#serial-bridge
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
no
**Additional context**  
_Add any other context or screenshots about the feature request here._
no
**(Please, remember to close the issue when the problem has been addressed)**  
ok

**Comment by Jason2866** [comment]
Have you seen the command `TCPStart <port>`  See #8702

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
