### ISSUE TITLE
Garage Door Opener: Shorten the relay time

### ISSUE THREAD

**Issue by tepebox** [arendst/Tasmota#9639]
Hi... 

I have a device similar to this: https://aliexpress.com/item/32997953761.html.
Also I just bought a garage door opener: https://www.schartec.de/en/schartec-move-600-series-3-garage-door-opener-with-k-rails/.

Before that I had a different opener which worked perfectly with the Tuya based device. But with the new Schartec it doesn't. After a while I found out that the relay in the device closes for about a second when I send the command to open/close the door. The Schartec is not accepting this, it requires a shorter press on a button or in my case a shorter time the relay closes. So how can I teach the device only to activate the relay for about 0.5 seconds or even less?

I came accross the "Pulstime" command. So I though a "pulsetime 5" should do the job. However what happens is that the relay closes again and again in a rhythm of a few seconds. I can easily stop that by sending a "pulsetime 0". 

Here's the log:

22:25:13 CMD: pulsetime 5
22:25:13 SRC: WebConsole from 192.168.200.72
22:25:13 CMD: Group 0, Index 1, Command "PULSETIME", Data "5"
22:25:13 MQT: stat/garage/RESULT = {"PulseTime1":{"Set":5,"Remaining":5}}
22:25:13 CFG: Saved to flash at F4, Count 129, Bytes 4096
22:25:14 SRC: PulseTimer
22:25:14 TYA: Send "55aa0006000501010001000d"
22:25:14 MQT: stat/garage/RESULT = {"POWER":"OFF"}
22:25:14 MQT: stat/garage/POWER = OFF
22:25:14 {"TuyaReceived":{"Data":"55AA03070005010100010112","Cmnd":7,"CmndData":"0101000101","DpType1Id1":1,"1":{"DpId":1,"DpIdType":1,"DpIdData":"01"}}}
22:25:14 TYA: fnId=11 is set for dpId=1
22:25:14 TYA: RX Relay-1 --> MCU State: On Current State:Off
22:25:14 SRC: Switch
22:25:14 MQT: stat/garage/RESULT = {"POWER":"ON"}
22:25:14 MQT: stat/garage/POWER = ON
22:25:14 {"TuyaReceived":{"Data":"55AA03070005010100010011","Cmnd":7,"CmndData":"0101000100","DpType1Id1":0,"1":{"DpId":1,"DpIdType":1,"DpIdData":"00"}}}
22:25:14 TYA: fnId=11 is set for dpId=1
22:25:14 TYA: RX Relay-1 --> MCU State: Off Current State:On
22:25:14 SRC: Switch
22:25:14 MQT: stat/garage/RESULT = {"POWER":"OFF"}
22:25:14 MQT: stat/garage/POWER = OFF
22:25:16 {"TuyaReceived":{"Data":"55AA03070005010100010011","Cmnd":7,"CmndData":"0101000100","DpType1Id1":0,"1":{"DpId":1,"DpIdType":1,"DpIdData":"00"}}}
22:25:16 TYA: fnId=11 is set for dpId=1
22:25:16 TYA: RX Relay-1 --> MCU State: Off Current State:Off
22:25:18 TYA: Send "55aa00000000ff"
22:25:18 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
22:25:18 TYA: Heartbeat
22:25:29 TYA: Send "55aa00000000ff"
22:25:29 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
22:25:29 TYA: Heartbeat
22:25:31 CMD: pulsetime 0

Any idea how I can stop the device to start clicking? My gutt feeling is that I only control the time via pulstime the relay is waiting to close again, not the time it's closing... At least still my garage door is not moving...

Thanks

Thomas

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
