### ISSUE TITLE
Problem after upgrading Sonoff Touch with minimal 8.51

### ISSUE THREAD

**Issue by vpomax** [arendst/Tasmota#9650]
### PROBLEM DESCRIPTION
I tried to upgrade my Sonoff Touch via web interface from 5.14 to 8.51with a full version but it showed me a message "Upload buffer miscompare", then I downloaded a minimal version.
After upgrading with tasmota-minimal I do not recognize my Sonoff Touch in my lan with its IP.
Upgrade procedure ended fine, it show me to wait some seconds to restart... but it didn't restarted
Searching for it IP in my Lan I do not find it

### REQUESTED INFORMATION
What's happened? How can I restore my device?

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
Help my to find and restore my device

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
