### ISSUE TITLE
Use 'Friendly Name' on dashboard instead of 'Toggle 1/2' 

### ISSUE THREAD

**Issue by bluemodena** [arendst/Tasmota#9665]
Hi there... Since there is already a field to label the two tasmota outlets ...

![Screen Shot 2020-10-29 at 2 29 37 PM](https://user-images.githubusercontent.com/8422540/97627727-294b7580-1a02-11eb-88e3-4d353b6deb62.png)

it would be helpful if I could rename them on the Dashboard

![Screen Shot 2020-10-29 at 4 18 00 PM](https://user-images.githubusercontent.com/8422540/97627911-69aaf380-1a02-11eb-8d5f-0515caa309e9.png)

something like this...
![Screen Shot 2020-10-29 at 4 18 00 PM](https://user-images.githubusercontent.com/8422540/97628375-feadec80-1a02-11eb-83b3-012ee1c911d8.png)

**Comment by arendst** [comment]
Try webbutton
