### ISSUE TITLE
Use 'Friendly Name' on dashboard instead of 'Toggle 1 and Toggle 2' names

### ISSUE THREAD

**Issue by bluemodena** [arendst/Tasmota#9667]
Hi there... Since there is already a field to label the two tasmota outlets ... Configuration -> Configure Other 

![Screen Shot 2020-10-29 at 2 29 37 PM](https://user-images.githubusercontent.com/8422540/97627727-294b7580-1a02-11eb-88e3-4d353b6deb62.png)

it would be helpful if I could rename them on the Dashboard

![Screen Shot 2020-10-29 at 4 18 00 PM](https://user-images.githubusercontent.com/8422540/97627911-69aaf380-1a02-11eb-8d5f-0515caa309e9.png)

something like this...
![Screen Shot 2020-10-29 at 4 18 00 PM](https://user-images.githubusercontent.com/8422540/97628375-feadec80-1a02-11eb-83b3-012ee1c911d8.png)

**Have you looked for this feature in other issues and in the docs?**  
YES

**Is your feature request related to a problem? Please describe.**  
No, this is a pure enhancement request to make it easier to tell which outlet does what.

**Describe the solution you'd like**  
Listed above

**Describe alternatives you've considered**  
N/A

**Additional context**  
screenshots added inline above

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by sfromis** [comment]
Did you consider just using the feature Tasmota already has for customizing the toggle button labels in the web UI? [Webbutton](https://tasmota.github.io/docs/Commands/#webbutton)

**Comment by bluemodena** [comment]
Wonderful!  Thank you!  

Closing
