### ISSUE TITLE
Eurotronic SPZB0001 Host Flags

### ISSUE THREAD

**Issue by xTomi93** [arendst/Tasmota#9718]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

Hello Guys,

I switched from Zigbee2MQTT with CC2530 Stick to Zigbee2Tasmota with Sonoff Bridge, all work fine I am happy but for my SPZB0001 i miss the Host Flags Settings to activate manually the boost mode or windows open mode.

Zigbee2MQTT use this Payload:
 
`{
  "eurotronic_host_flags": {
    "mirror_display": false,
    "boost": false,
    "window_open": false,
    "child_protection": true
  }
}`

Its possible to implement this for Zigbee2Tasmota too or is it already implemented and I am only to stupid for use it, I dont can find any information in the docs

Best Regards 
Tom

**Comment by s-hadinger** [comment]
I will take a look. It's not clear in the Eurotronic documentation how to set these flags.
