### ISSUE TITLE
Sonoff RF Bridge Tasmota Portisch - sending signlas

### ISSUE THREAD

**Issue by marcelhen** [arendst/Tasmota#9742]
### PROBLEM DESCRIPTION

Hello,

I have a Sonoff Bridge 433 MHz (Tasmota / Portisch) running via MQTT on the HA. I want to use it to switch my shutters. If I set option RfRaw 166 I get the following code:

tele / tasmota_C3B1F5 / RESULT = {“Time”: “2020-11-02T09: 15: 30”, “RfRaw”: {“Data”: “AAA606012CFF86713355”}}

How can I send that now? If I copy it into the command line, nothing happens.

If I set the RfRaw 177 option, I unfortunately don’t receive anything …

I have already received several other codes with the RfRaw 177 option and have also converted them, so they can be switched with Home Assistant without any problems.

I currently have the following command:

cover:

- platform: "mqtt"

name: "Rolladen HWR"

command_topic: "cmnd/tasmota_C3B1F5/Backlog"

payload_open: "RfRaw AAA420F80110033001232355; RfRaw 0"

payload_close: "RfRaw AAA606012CFF86713355; RfRaw 0"

payload_stop: "RfRaw AAA606012CFF86715555; RfRaw 0"

But unfortunately it doesn’t work !!!

Best regards 
Marcel

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
See https://tasmota.github.io/docs/devices/Sonoff-RF-Bridge-433/#portisch-firmware-specific-usage

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
