### ISSUE TITLE
Tasmota flashed light switches relay keeps decoupling from physical switch

### ISSUE THREAD

**Issue by RamonBell** [arendst/Tasmota#9771]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Was running previous versions of Tasmota on Ayococor SW1 switches and also on Gosund SW1 switches. I was running various past Tasmota firmware. I recently up grade them all, twelve in total to the new firmware. Mostly to do group topic and multi press. But in the last two weeks, since I upgraded. All the switches are regularly have their relay decouple for the switch. You can toggle them from the Tasmota web ui and in home assistant. I went as far as taking some out of the wall check the wiring and doing a reset in the consule of Tasmota to try to get them to work. I did some investigating and I was able to fix the issue with SetOption73. By setting it to 1 then 0 the relay will reattach and you will be able to toggle the switches manually. But today they all come uncoupled again. I had to again use SetOption73 on all 40 plus switches including the three way switches that are also having the same issue.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: 8.5.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: OTA Tuya covert
- [X ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
00:59:06 CMD: status 0
00:59:06 MQT: bar_lights/stat/STATUS = {"Status":{"Module":0,"DeviceName":"Bar Lights","FriendlyName":["Bar Lights"],"Topic":"bar_lights","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:59:06 MQT: bar_lights/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"8T02:56:17","StartupUTC":"2020-10-30T21:02:49","Sleep":50,"CfgHolder":4617,"BootCount":25,"BCResetTime":"2020-10-30T22:02:58","SaveCount":1186,"SaveAddress":"F4000"}}
00:59:06 MQT: bar_lights/stat/STATUS2 = {"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"405/699"}}
00:59:06 MQT: bar_lights/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Bell WiFi",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00000200","00006000","00000000"]}}
00:59:06 MQT: bar_lights/stat/STATUS4 = {"StatusMEM":{"ProgramSize":595,"Free":408,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
00:59:06 MQT: bar_lights/stat/STATUS5 = {"StatusNET":{"Hostname":"bar_lights-6866","IPAddress":"192.168.1.109","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"B4:E6:2D:41:DA:D2","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
00:59:06 MQT: bar_lights/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.5","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_41DAD2","MqttUser":"mqtt_user","MqttCount":5,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
00:59:06 MQT: bar_lights/stat/STATUS7 = {"StatusTIM":{"UTC":"2020-11-07T23:59:06","Local":"2020-11-08T00:59:06","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"07:49","Sunset":"17:18"}}
00:59:06 MQT: bar_lights/stat/STATUS10 = {"StatusSNS":{"Time":"2020-11-08T00:59:06"}}
00:59:06 MQT: bar_lights/stat/STATUS11 = {"StatusSTS":{"Time":"2020-11-08T00:59:06","Uptime":"8T02:56:17","UptimeSec":701777,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":5,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Bell WiFi","BSSId":"50:C7:BF:75:E4:13","Channel":11,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:07"}}}
00:59:16 MQT: bar_lights/tele/STATE = {"Time":"2020-11-08T00:59:16","Uptime":"8T02:56:27","UptimeSec":701787,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"MqttCount":5,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Bell WiFi","BSSId":"50:C7:BF:75:E4:13","Channel":11,"RSSI":92,"Signal":-54,"LinkCount":1,"Downtime":"0T00:00:07"}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
01:03:05 MQT: bar_lights/stat/RESULT = {"Module":{"0":"Aoycocr SW1"}}
01:03:06 MQT: bar_lights/stat/RESULT = {"WifiPower":"17.0"}
01:04:05 MQT: bar_lights/tele/HASS_STATE = {"Version":"8.5.0(tasmota)","BuildDateTime":"2020-09-09T11:41:02","Module or Template":"Aoycocr SW1","RestartReason":"Software/System restart","Uptime":"8T03:01:16","Hostname":"bar_lights-6866","IPAddress":"192.168.1.109","RSSI":"94","Signal (dBm)":"-53","WiFi LinkCount":1,"WiFi Downtime":"0T00:00:07","MqttCount":5,"LoadAvg":19}
01:04:16 MQT: bar_lights/tele/STATE = {"Time":"2020-11-08T01:04:16","Uptime":"8T03:01:27","UptimeSec":702087,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":5,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Bell WiFi","BSSId":"50:C7:BF:75:E4:13","Channel":11,"RSSI":96,"Signal":-52,"LinkCount":1,"Downtime":"0T00:00:07"}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
I didn't have to reproduce it it just happened on its own. There was no recent changes to the Mosquito Mqtt server and no recent changes to Home Assistant, either upgrade or changes to any MQTT settings

### EXPECTED BEHAVIOUR
The switch is supposed to toggle the state of the light by means of the switch in the wall. I can toggle it in Home assistant but not at the wall itself.
### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Seems that in the update, some settings have scrambled, or some mqtt retained messages are interfering with your settings.

Try to do a `reset 6` and reconfigure your device again.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
