### ISSUE TITLE
Sonoff Zigbee bridge with Tasmota - include device info in the message

### ISSUE THREAD

**Issue by mgx0** [arendst/Tasmota#9788]
**Have you looked for this feature in other issues and in the docs?**  
yes but maybe I'm blind. Or is there any option to set to get this?

**Is your feature request related to a problem? Please describe.**  
no

**Describe the solution you'd like**  
get device manufacturer and model included in MQTT message like zigbee2mqtt does, in every message (currently I get model ID in separate message, but no battery level information

**Describe alternatives you've considered**  
get device information by asking the bridge, but that's not that fast

**Additional context**  

I am trying to migrate from Zigbee2MQTT to Sonoff ZBridge running Tasmota. Running Node-red

this is what I get from zigbee2mqtt, as an example
```
battery: 51
device: object
applicationVersion: 2
friendlyName: "sensorname"
ieeeAddr: "0x00158xxxxxxxx"
manufacturerID: 4151
manufacturerName: "LUMI"
model: "WSDCGQ01LM"
networkAddress: 15462
powerSource: "Battery"
type: "EndDevice"
elapsed: 25
humidity: 57.92
last_seen: "2020-11-09T13:49:54+01:00"
linkquality: 7
temperature: 14.32
voltage: 2915
```

**(Please, remember to close the issue when the problem has been addressed)**  
okay

**Comment by s-hadinger** [comment]
Hi, part of the information can be retrieved with `ZbStatus2`. There will be a new command to also dump the last known information (the ones displayed in the web UI). Stay tuned.

**Comment by kroon040** [comment]
also the last seen? that should be nice for the smoke detector, with also the notation in the web (so last seen 40m ago)

**Comment by mgx0** [comment]
yeah that would be also nice. It is displayed on the Tasmota web UI so it does exist
would be handy also for the water leak detector

**Comment by mgx0** [comment]
but looking at the data I'm getting, the message contents vary. Sometimes there is BatteryPercentage and sometimes not. This applies as well for temperature/humidity data and other sensor data. Looks like the sensors send multiple data which zigbee2mqtt combined into one.

an example from Xiaomi water leakage sensor

![Screen Shot 2020-11-10 at 20 22 20](https://user-images.githubusercontent.com/9897026/98723587-e2ab3300-2392-11eb-8007-55c0975890ae.png)
![Screen Shot 2020-11-10 at 20 25 00](https://user-images.githubusercontent.com/9897026/98723597-e3dc6000-2392-11eb-8b70-ca3f18852528.png)

**Comment by s-hadinger** [comment]
#9810 introduces a new `ZbInfo` command to display all known information of a device, including the last_seen in both seconds from now and absolute epoch time.

**Comment by mgx0** [comment]
that's great. I believe everyone will welcome if all of this information is supplied in every message coming from device, so we don't have to ask for it when we get updates.

I think it's a useful feature

**Comment by s-hadinger** [comment]
@mgx0 I'm reluctant to include all the information with every messages for two reasons: 1/ it will create a massive amout of traffic with essentially redundant information, 2/ messages received also include the source endpoint which may be important with regards to which actuator was used. `ZbInfo` does not publish the endpoint information on purpose (although the information is internally kept) for the sake of simplicity. If I added the endpoints to ZbInfo, it would quickly become unreadable.

MQTT gateways have much more horsepower than the tiny ESP8266, data persistence should definitely be done at this level.

**Comment by mgx0** [comment]
I understand. But what about an option to include it? a checkbox where everyone accepts the risk?
or is it really a no-go?

**Comment by s-hadinger** [comment]
I would prefer a Rule: whenever you receive a message, trigger a `ZbInfo` right after. Which makes me think that `ZbInfo` should maybe have a different prefix to avoid infinite loop.

**Comment by mgx0** [comment]
yeah for me that is a workaround from the start, but it is acceptable. It's true that I ran zigbee2mqtt on Pi4 so that power cannot be compared. should I close this issue then?

**Comment by s-hadinger** [comment]
You can use a simple rule as this one: `Rule3 on zbreceived#? do zbinfo %ZBDEVICE% endon`

I understand it's not perfect though because you may miss some information that was not kept into memory (Tasmota doesn't remember all attributes)

**Comment by mgx0** [comment]
good, thanks for that, I'll close this issue. but I have a question, last one.

when you look at the screenshot attached, you see two messages (look only at the originalPayload object, the others are calculated to keep up the structure I have built for zigbee2mqtt). Both arrived at the same second. Is the second one zbInfo? 

I have noticed that the second message is sent more frequently than the first one (that contains the sensor data). Is it some heartbeat message from the sensor itself or is it Tasmota sending this?

thanks a lot, I'll close this issue after you answer. or you can close it if you don't mind

<img width="503" alt="Screen Shot 2020-11-13 at 20 28 55" src="https://user-images.githubusercontent.com/9897026/99113239-30bc7280-25ef-11eb-9af4-b54d2b826714.png">

**Comment by s-hadinger** [comment]
Yes, that's part of the Xiaomi folklore. They sent sometimes messages compliant to ZCL, sometimes with their own format, including resending the `ModelId`.
Tasmota groups both messages into a single when they arrive within 350 ms.

**Comment by mgx0** [comment]
Perfect, thanks for perfect response, I appreciate it. Closing now
