### ISSUE TITLE
Compiling tasmota with Home Assistant support but without light support should be possible

### ISSUE THREAD

**Issue by Zer0x00** [arendst/Tasmota#9805]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
It should be possible to use the Home Assistant integration without compiling USE_LIGHTS into the firmware.
Right now it throws errors and the build operation fails (see screenshot)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Gitpod
- [X] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [X] Self-compiled
    - [X] IDE / Compiler used: Gitpod
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Create user_config_override.h with the following parameters set:
```
#ifndef USE_HOME_ASSISTANT
  #define USE_HOME_ASSISTANT
#endif

#ifdef USE_LIGHT
  #undef USE_LIGHT
#endif
```

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Compilation should succeed.

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/32687653/98706719-7b37b800-237f-11eb-9b0d-7d8f58d0d973.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
And for what use case should it be possible to separate the lights HA part?

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
