### ISSUE TITLE
Zigbee Light MQTT request/improvement

### ISSUE THREAD

**Issue by Bibinsa** [arendst/Tasmota#9807]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
Not really a problem but a improvement

**Describe the solution you'd like**  
In order to have Home Assistant sync'd with Tasmota-Zigbee, it could be useful to have the ability to
Publish ZbLight JSON message on a per device topic like` tele/Zigbee/5ADF/LIGHTSTATE` or something else.

Home Assistant could subscribe to this topic for state/brightness/color as every keys are present (Power, Dimmer, X, Y, ColorMode, Hue)

**Describe alternatives you've considered**  
Rule to copy ZbLight JSON on another MQTT topic : failed.

**Additional context**  
Sonoff Zigbee Bridge

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment]
This is what `SetOption89` is supposed to do. Are you asking for something different?

**Comment by Bibinsa** [comment]
> This is what `SetOption89` is supposed to do. Are you asking for something different?

Yes, `SetOption89` is doing well for tele response but not for `ZbLight` response.

```
12:39:53 CMD: ZbSend { "device":"0x34A7", "send":{"Power":"true"} }
12:39:53 MQT: tasmota/zbbridge-1/stat/RESULT = {"ZbSend":"Done"}
12:39:53 MQT: tasmota/zbbridge-1/tele/RESULT = {"ZbResponse":{"Device":"0x34A7","Name":"tradrfri_bulb_1","Command":"0006!01","Status":0,"StatusMessage":"SUCCESS","Endpoint":1,"LinkQuality":89}}
12:39:54 MQT: tasmota/zbbridge-1/tele/34A7/SENSOR = {"tradrfri_bulb_1":{"Device":"0x34A7","Name":"tradrfri_bulb_1","Power":1,"Endpoint":1,"LinkQuality":89}}
12:40:10 CMD: zblight 0x34A7
12:40:10 MQT: tasmota/zbbridge-1/stat/RESULT = {"ZbLight":{"tradrfri_bulb_1":{"Device":"0x34A7","Name":"tradrfri_bulb_1","Reachable":true,"Power":1,"Dimmer":254,"X":30138,"Y":26909,"CT":370,"ColorMode":2,"Hue":360}}}
12:40:10 MQT: tasmota/zbbridge-1/stat/RESULT = {"ZbLight":"Done"}
```

For color status we neeed `ZbLight` response because `ZbResponse` does not include all items (Dimmer, Power, X, Y CT, ...).
Unless I missed something in HomeAssistant Integration.

**Comment by s-hadinger** [comment]
Ok, got it. I will unify the different places where the JSON is published.

**Comment by Bibinsa** [comment]
Thanks !
