### ISSUE TITLE
Status Visualisation for Switches with SetOption114 enabled

### ISSUE THREAD

**Issue by Noschvie** [arendst/Tasmota#9819]
**Have you looked for this feature in other issues and in the docs?**  
yes
**Is your feature request related to a problem? Please describe.**  
Using an optocoupler with 3 channels as input device, each channel is configured as switch input, SetOption114 is enabled, MQTT is enabled and works fine. But there is no visualisation of the channel states in the main view.

**Describe the solution you'd like**  
I would love to have visualisation support in tasmota for these switches like for temperature sensors (DS18B20).

**Describe alternatives you've considered**  

**Additional context**  
`{"NAME":"Optokoppler 220V","GPIO":[0,0,0,0,0,0,0,0,161,160,162,0,0,0],"FLAG":0,"BASE":18}`
```
08:06:05 MQT: stat/tasmota_8635B2/RESULT = {"Switch1":{"Action":"ON"}}
08:06:52 MQT: stat/tasmota_8635B2/RESULT = {"Switch1":{"Action":"OFF"}}
```
![grafik](https://user-images.githubusercontent.com/48217146/98911664-42096000-24c5-11eb-896c-c49facd5e918.png)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
If you want, you can continue the work of @roblad for this request. His work is at https://github.com/roblad/Sonoff-Tasmota/blob/master/sonoff/xsns_95_switch_state_show.ino
