### ISSUE TITLE
no "Display" commands on tasmota-display

### ISSUE THREAD

**Issue by Ruebezahl11** [arendst/Tasmota#9844]
maybe a stupid mistake because this is my first attemt at platformio: I just built master 9.1.0 (display),but the display commands are missing

**Comment by Jaybirdrocksshards** [comment]
What is the best used for ethical and very unethical hacking my ex just
won't stop ruining everyone's lives she and her son's needs to be stopped

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
