### ISSUE TITLE
Sonoff 4ch pro ghost swtiching problem

### ISSUE THREAD

**Issue by forty76** [arendst/Tasmota#9869]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I have owned the Sonoff CH4 PRO for 2 years, I immediately found random activations of the buttons. Not knowing the source of the problem I searched online for similar experiences but these attributed the problem either to electrical disturbances and it was recommended to increase buttondebounce or to MQTT retain. I have made several attempts at both hardware and software without success. In the last month after the purchase of an RF door switch I accidentally found the activation of the buttons in conjunction with the sending of the RF code. I searched online and found other similar findings. The problem is that both the buttons and the RF433 commands pass through MCU STM32 so the ESP8285 receives the button activation signal, not knowing if it originated from a physical button or RF command, the Tasmota console shows “APP: Button1 level 1-0”.
After change I tested the device for 1 week and found the complete resolution of random button activation issues.
I think it is useful to inform in advance through this document those who are about to program Sonoff CH4 PRO with tasmota, simplifying the resolution of the problem. Especially since without targeted research online information is misleading.

Resolution: 
WARNING The Sonoff CH4 PRO is subject to radio frequency disturbances with random activation of the buttons. To eliminate interference due to the U7 (SYN470RU7 RF-433 module) you can cut the wire between U7 and U8 (MCU STM32f030c6). This line starts from pin 10 of U7, the part towards MCU can be soldered to ground (surrounding area). It is also possible to set the RF module (U7) in shutdown-mode by unsoldering or cutting pin 11.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Thanks.

Please, help us and add this to Tasmota docs.
