### ISSUE TITLE
Please add QS-WIFI-S04-2C module

### ISSUE THREAD

**Issue by avdlex** [arendst/Tasmota#9879]
**Have you looked for this feature in other issues and in the docs?**  
I didn't find any about this.

**Is your feature request related to a problem? Please describe.**  
No QS-WIFI-S04-2C module in list

**Describe the solution you'd like**  
Can you add QS-WIFI-S04-2C module ? I will test device with this template, all works good:
**{"NAME":"QS-WIFI-S04-2C","GPIO":[1,1,32,1,480,0,0,0,161,160,224,225,0,0],"FLAG":0,"BASE":18}**
Attention: it need "**switchdebounce 69**" command, this is AC Frequency Detection Switch
https://tasmota.github.io/docs/Buttons-and-Switches/#ac-frequency-detection-switch

**Comment by Jason2866** [comment]
Adding is done here https://templates.blakadder.com/new.html
Thx!
