### ISSUE TITLE
Battery staus not available in ZigbeeBridge

### ISSUE THREAD

**Issue by hcwmmhz** [arendst/Tasmota#9948]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**  

Zigbee device reports not all parameter values.

15:41:06 MQT: tele/tasmota_D9BA9B/SENSOR = {"ZbReceived":{"0x3B4C":{"Device":"0x3B4C","Name":"Sensor1","Temperature":23.61,"Humidity":46.5,"Pressure":1008,"PressureScale":-1,"PressureScaledValue":10088,"SeaPressure":1008,"Endpoint":1,"LinkQuality":147}}}

15:53:24 MQT: tele/tasmota_D9BA9B/SENSOR = {"ZbReceived":{"0x3B4C":{"Device":"0x3B4C","Name":"Sensor1","BatteryVoltage":2.97,"BatteryPercentage":86,"Temperature":23.56,"Humidity":46.21,"Pressure":1009,"SeaPressure":1009,"Endpoint":1,"LinkQuality":147}}}

How can i query all parameter from a zigbee device?

Thanks
CHris

**Comment by s-hadinger** [comment]
`ZbInfo 0x3B4C`
